<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.34">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>7&nbsp; Sintesi a posteriori – Psicometria</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/bayesian_inference/08_balance_prior_post.html" rel="next">
<link href="../../chapters/bayesian_inference/06_conjugate_families.html" rel="prev">
<link href="../../style/gauss.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-0a72236910a44089af39cd28873f322e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9908c7b05874059c2106d454ac00f1d0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QT5S3P9D31"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QT5S3P9D31', { 'anonymize_ip': true});
</script><style>html{ scroll-behavior: smooth; }</style>
<script>
window.MathJax = {
  tex: { inlineMath: [['$', '$'], ['\\(', '\\)']] },
  svg: { scale: 1, mtextInheritFont: true, fontCache: 'none', minScale: 1 },
  options: { renderActions: { addMenu: [0, '', ''] } },
  loader: { load: ['input/tex','output/svg'] }
};
</script><script>
window.MathJax = {
  tex: { inlineMath: [['$', '$'], ['\\(', '\\)']] },
  svg: { scale: 1, mtextInheritFont: true, fontCache: 'none', minScale: 1 },
  options: { renderActions: { addMenu: [0, '', ''] } },
  loader: { load: ['input/tex','output/svg'] }
};
// Suggerimento CSS: vedi sezione 3 per gli spazi attorno a display math
</script><script>
window.MathJax = {
  tex: {
    packages: {'[+]': ['boldsymbol']},
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  },
  svg: { fontCache: 'global' }
};
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../../style/_typography-extras.css">
<link rel="stylesheet" href="../../style/_code-extras.css">
<link rel="stylesheet" href="../../style/_math-extras.css">
<link rel="stylesheet" href="../../style/styles.css">
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/bayesian_inference/introduction_sec.html">Inferenza</a></li><li class="breadcrumb-item"><a href="../../chapters/bayesian_inference/07_summary_posterior.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sintesi a posteriori</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Psicometria</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/psicometria-r/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Attiva/disattiva la modalità lettore">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Informazioni generali</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Inferenza</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/01_bayes_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Inferenza bayesiana</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/02_uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Abbracciare l’incertezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/03_uncertainty_quantification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">La quantificazione dell’incertezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/04_statistical_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modelli statistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/05_subj_prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Aggiornare le credenze su un parametro: dal prior alla posterior</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/06_conjugate_families.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Distribuzioni coniugate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/07_summary_posterior.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sintesi a posteriori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/08_balance_prior_post.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">L’influenza della distribuzione a priori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/09_prior_pred_check.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Controllo predittivo a priori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/10_post_pred_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Distribuzione predittiva a posteriori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">MCMC</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/01_metropolis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">L’algoritmo di Metropolis-Hastings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/02_ppl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linguaggi di programmazione probabilistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/03_stan_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Introduzione pratica a Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/04_stan_diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Diagnostica delle catene markoviane</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/05_mcmc_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Controlli predittivi bayesiani (a priori e a posteriori) con <code>cmdstanr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/06_stan_odds_ratio_stan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Analisi bayesiana dell’odds ratio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/07_stan_two_means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Confrontare due medie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/08_stan_poisson_model_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Modello di Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/09_stan_gaussian_mixture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Modelli Mistura Gaussiani</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/10_stan_nuisance_parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Modelli con più di un parametro</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/11_stan_hier_beta_binom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Modello gerarchico beta-binomiale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/12_stan_parametrization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Parametrizzazioni centered e non-centered</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/13_bayesian_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Flusso di lavoro bayesiano</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive sulla sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Regressione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/01_reglin_frequentist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">La regressione lineare bivariata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/02_regr_toward_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">La regressione verso la media</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/03_reglin_bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Modello bayesiano di regressione lineare bivariata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/04_synt_sugar_sea_ice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Zucchero sintattico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/05_stan_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Regressione lineare in Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/06_specification_error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Errore di specificazione e bias da variabile omessa</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/07_one_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Inferenza bayesiana su una media</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/08_two_means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Confronto tra le medie di due gruppi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/09_effect_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">La grandezza dell’effetto: valutare la rilevanza pratica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/10_sample_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Pianificazione della dimensione campionaria</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/11_anova_1via.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">ANOVA ad una via</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">GLM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/01_logistic_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Regressione logistica con Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/02_one_proportion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Inferenza sulle proporzioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/03_two_proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Confronto tra due proporzioni con la regressione logistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/04_poisson_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Modello di Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/05_logistic_process.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Dal GLM a un modello processuale per dati binari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/06_missing_values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Dati mancanti in psicologia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive sulla sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Entropia</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/01_entropy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Entropia e informazione di Shannon</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/02_kl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">La divergenza di Kullback-Leibler</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/03_model_comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Valutare i modelli bayesiani</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Modelli</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/01_dynamic_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Il modello di revisione degli obiettivi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/02_dynamic_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Estensioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/03_rescorla_wagner.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Il modello di Rescorla–Wagner</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/04_study_method.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Decisione ottimale e utilità attesa: l’approccio bayesiano</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Crisi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/introduction_replication_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/01_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">La crisi della replicazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/02_limits_stat_freq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Limiti dell’inferenza frequentista</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/03_effect_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">La grandezza dell’effetto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/04_s_m_errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Errori di segno e errori di grandezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/05_p_values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">La fragilità del <em>p</em>-valore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/06_changes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Riforma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/07_degrees_of_freedom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">I gradi di libertà del ricercatore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/08_integrity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Integrità della ricerca</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Epilogo</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epiloque/epiloque.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Considerazioni Conclusive</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a01_shell.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">La Shell</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a01a_files.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Cartelle e documenti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a02_math_symbols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Simbologia di base</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a03_latex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Equazioni Matematiche in LaTeX</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a11_numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Numeri e intervalli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a12_sum_notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Sommatorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a13_sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">Insiemi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a14_combinatorics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">Calcolo combinatorio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a15_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">I</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a35_other_conjugate_families.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">J</span>&nbsp; <span class="chapter-title">Altre famiglie coniugate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a36_gamma_poisson_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">K</span>&nbsp; <span class="chapter-title">Modello coniugato Gamma-Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a40_metropolis_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">L</span>&nbsp; <span class="chapter-title">Metropolis: esempio Normale–Normale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a41_cmdstanr_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">M</span>&nbsp; <span class="chapter-title">Implementazione di modelli Bayesiani con Stan tramite <code>cmdstanr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a47_first_order_markov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">N</span>&nbsp; <span class="chapter-title">Catene di Markov</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a50_lin_fun.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">O</span>&nbsp; <span class="chapter-title">La funzione lineare</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a71_install_cmdstan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">P</span>&nbsp; <span class="chapter-title">Come installare CmdStan</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Sommario</h2>
   
  <ul class="collapse">
<li><a href="#riepilogo-numerico" id="toc-riepilogo-numerico" class="nav-link active" data-scroll-target="#riepilogo-numerico"><span class="header-section-number">7.1</span> Riepilogo numerico</a></li>
  <li><a href="#stima-puntuale" id="toc-stima-puntuale" class="nav-link" data-scroll-target="#stima-puntuale"><span class="header-section-number">7.2</span> Stima puntuale</a></li>
  <li><a href="#misurare-lincertezza-varianza-a-posteriori" id="toc-misurare-lincertezza-varianza-a-posteriori" class="nav-link" data-scroll-target="#misurare-lincertezza-varianza-a-posteriori">Misurare l’incertezza: varianza a posteriori</a></li>
  <li><a href="#intervallo-di-credibilit%C3%A0" id="toc-intervallo-di-credibilità" class="nav-link" data-scroll-target="#intervallo-di-credibilit%C3%A0"><span class="header-section-number">7.3</span> Intervallo di credibilità</a></li>
  <li><a href="#verifica-di-ipotesi-bayesiana" id="toc-verifica-di-ipotesi-bayesiana" class="nav-link" data-scroll-target="#verifica-di-ipotesi-bayesiana"><span class="header-section-number">7.4</span> Verifica di ipotesi bayesiana</a></li>
  <li><a href="#sintesi-della-distribuzione-a-posteriori-in-contesti-multivariati" id="toc-sintesi-della-distribuzione-a-posteriori-in-contesti-multivariati" class="nav-link" data-scroll-target="#sintesi-della-distribuzione-a-posteriori-in-contesti-multivariati"><span class="header-section-number">7.5</span> Sintesi della distribuzione a posteriori in contesti multivariati</a></li>
  </ul><div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ccaudek/psicometria-r/blob/main/chapters/bayesian_inference/07_summary_posterior.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/psicometria-r/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/bayesian_inference/introduction_sec.html">Inferenza</a></li><li class="breadcrumb-item"><a href="../../chapters/bayesian_inference/07_summary_posterior.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sintesi a posteriori</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-bayesian-inference-summary-posterior" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sintesi a posteriori</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="epigraph">
<blockquote class="blockquote">
<p>“The summary of a posterior distribution is an essential step for its interpretation. Point estimators and credible intervals are the most common Bayesian answers, but they should not make us forget the richness of the entire posterior.”</p>
<p>– <strong>Christian P. Robert</strong>, The Bayesian Choice (2007)</p>
</blockquote>
</div>
<section id="introduzione" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="introduzione">Introduzione</h2>
<p>Nei capitoli precedenti abbiamo imparato a costruire distribuzioni a posteriori combinando la nostra conoscenza preliminare (<em>prior</em>) con i dati osservati attraverso la verosimiglianza. Abbiamo visto come questo processo si realizzi in casi semplici, come la stima di una proporzione di successi con il modello Beta–Binomiale, e come possa essere generalizzato grazie al concetto di famiglie coniugate. Ora ci poniamo una domanda fondamentale: una volta che abbiamo ottenuto una distribuzione a posteriori, <em>come possiamo riassumerla e comunicarla in modo chiaro ed efficace?</em></p>
<p>Il <em>posterior</em> non è un singolo numero, ma un’intera distribuzione che rappresenta la nostra incertezza sul parametro. Nella pratica della ricerca psicologica, tuttavia, dobbiamo spesso sintetizzare queste informazioni per presentarle nei risultati di un articolo o per confrontarle con altre stime. Questo capitolo è dedicato proprio a questa esigenza: mostreremo come ricavare quantità riassuntive (media, mediana, moda) e come costruire intervalli credibili che esprimano in modo trasparente i valori più plausibili.</p>
<p>L’obiettivo non è ridurre l’inferenza bayesiana alla ricerca di un punto o di un intervallo, ma imparare a <em>comunicare l’incertezza</em> in modo comprensibile, senza perdere la ricchezza informativa del posterior. Come vedremo, anche nei contesti più complessi, la capacità di sintetizzare correttamente le distribuzioni a posteriori è ciò che distingue un’analisi meramente tecnica da una presentazione scientifica chiara e convincente.</p>
<section id="panoramica-del-capitolo" class="level3 unnumbered unlisted"><h3 class="unnumbered unlisted anchored" data-anchor-id="panoramica-del-capitolo">Panoramica del capitolo</h3>
<ul>
<li>Distribuzione a posteriori = conoscenza aggiornata.</li>
<li>Stime puntuali: MAP, media, mediana.</li>
<li>Incertezza: varianza e deviazione standard.</li>
<li>Intervalli di credibilità: simmetrici e HPD.</li>
<li>Verifica di ipotesi: probabilità a posteriori.</li>
</ul>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prerequisiti
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Leggere il capitolo <em>Posterior Inference &amp; Prediction</em> del testo di <span class="citation" data-cites="Johnson2022bayesrules">Johnson et al. (<a href="#ref-Johnson2022bayesrules" role="doc-biblioref">2022</a>)</span>.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-caution no-icon callout-titled" title="Preparazione del Notebook">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Preparazione del Notebook
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Load packages</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html">requireNamespace</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">mice</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section></section><section id="riepilogo-numerico" class="level2" data-number="7.1"><h2 data-number="7.1" class="anchored" data-anchor-id="riepilogo-numerico">
<span class="header-section-number">7.1</span> Riepilogo numerico</h2>
<p>La distribuzione a posteriori contiene in sé tutte le informazioni disponibili sui potenziali valori del parametro. Nel caso di un parametro unidimensionale o bidimensionale, possiamo rappresentare la distribuzione a posteriori mediante un grafico <span class="math inline">\(p(\theta \mid y)\)</span>. Tuttavia, quando ci troviamo di fronte a vettori di parametri con più di due dimensioni, risulta vantaggioso eseguire una sintesi numerica della distribuzione a posteriori. Possiamo distinguere due forme di sintesi numerica della distribuzione a posteriori: stima puntuale e intervallo di credibilità.</p>
</section><section id="stima-puntuale" class="level2" data-number="7.2"><h2 data-number="7.2" class="anchored" data-anchor-id="stima-puntuale">
<span class="header-section-number">7.2</span> Stima puntuale</h2>
<p>Nel contesto dell’<em>inferenza bayesiana</em>, stimare il valore più credibile di un parametro <span class="math inline">\(\theta\)</span> a partire dalla distribuzione a posteriori può avvenire attraverso tre statistiche principali: <em>moda, mediana e media</em>. La scelta tra queste dipende dalla forma della distribuzione a posteriori. Queste statistiche forniscono una <em>stima puntuale</em> della tendenza centrale della distribuzione, ossia il valore a cui attribuiamo il massimo grado di fiducia soggettiva, basandoci sia sui dati osservati sia sulle credenze a priori.</p>
<section id="moda-massimo-a-posteriori-map" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="moda-massimo-a-posteriori-map">Moda (<em>Massimo a Posteriori</em>, MAP)</h3>
<p>La moda della distribuzione a posteriori, nota come stima di <em>massimo a posteriori (MAP)</em>, corrisponde al valore del parametro <span class="math inline">\(\theta\)</span> a cui è associata la massima densità di probabilità. Questo concetto rappresenta l’estensione bayesiana della classica <em>stima di massima verosimiglianza (MLE)</em>, definita come:</p>
<p><span class="math display">\[
\hat{\theta}_{\text{ML}} = \arg \max_\theta L(\theta \mid y),
\]</span> dove <span class="math inline">\(L(\theta \mid y)\)</span> è la funzione di verosimiglianza. Nell’approccio bayesiano, l’informazione a priori <span class="math inline">\(p(\theta)\)</span> viene incorporata attraverso il teorema di Bayes, portando alla definizione della stima MAP:</p>
<p><span class="math display">\[
\hat{\theta}_{\text{MAP}} = \arg \max_\theta \, L(\theta \mid y) \, p(\theta).
\]</span> In altre parole, <span class="math inline">\(\hat{\theta}_{\text{MAP}}\)</span> massimizza la densità a posteriori non normalizzata, combinando in modo esplicito l’evidenza empirica con la conoscenza pregressa.</p>
<section id="limitazioni-della-stima-map" class="level4" data-number="7.2.0.1"><h4 data-number="7.2.0.1" class="anchored" data-anchor-id="limitazioni-della-stima-map">
<span class="header-section-number">7.2.0.1</span> Limitazioni della stima MAP</h4>
<p>Nonostante l’interpretazione intuitiva, la stima MAP presenta alcune limitazioni di cui è importante essere consapevoli. In primo luogo, la sua determinazione può risultare computazionalmente impegnativa, specialmente quando la distribuzione a posteriori viene campionata mediante metodi MCMC: individuare con precisione il massimo in uno spazio di parametri ad alta dimensionalità o con forme complesse richiede tecniche specifiche e può essere instabile.</p>
<p>In secondo luogo, la bontà della stima MAP dipende fortemente dalla forma della distribuzione a posteriori. In presenza di asimmetrie marcate o di multimodalità, il massimo globale potrebbe non essere rappresentativo della regione di alta probabilità, soprattutto se associato a un picco stretto ma isolato, mentre la maggior parte della massa probabilistica si trova altrove.</p>
<p>Infine, il MAP è intrinsecamente meno robusto di altre statistiche centrali, come la media o la mediana a posteriori, in quanto basato esclusivamente sul valore di massimo densità, ignorando la forma complessiva della distribuzione. Ciò lo rende sensibile a variazioni nella parametrizzazione del modello e poco informativo riguardo all’incertezza complessiva sul parametro.</p>
</section></section><section id="media-a-posteriori" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="media-a-posteriori">Media a posteriori</h3>
<p>La <em>media a posteriori</em> rappresenta il valore atteso del parametro <span class="math inline">\(\theta\)</span> rispetto alla sua distribuzione a posteriori. Formalmente, essa è definita come:</p>
<p><span class="math display">\[
\mathbb{E}[\theta \mid y] = \int \theta \, p(\theta \mid y) \, d\theta.
\]</span> Questa quantità costituisce una stima di <span class="math inline">\(\theta\)</span> che tiene conto dell’intera distribuzione a posteriori, integrando su tutti i possibili valori del parametro. Una proprietà notevole della media a posteriori è quella di essere lo stimatore che minimizza l’<em>errore quadratico medio (MSE)</em> nella previsione di <span class="math inline">\(\theta\)</span>, il che ne giustifica l’ampio utilizzo in contesti di ottimizzazione statistica.</p>
<p>Tuttavia, in presenza di distribuzioni a posteriori marcatamente <em>asimmetriche</em> o con <em>code pesanti</em>, la media potrebbe non rappresentare adeguatamente la regione di massima densità di probabilità. In tali casi, valori estremi possono influenzare eccessivamente la stima, allontanando la media dalla zona in cui è concentrata la maggior parte della massa probabilistica. Per questo motivo, in situazioni di asimmetria pronunciata, altre statistiche come la <em>mediana</em> o la <em>moda</em> a posteriori possono offrire una rappresentazione più appropriata della tendenza centrale.</p>
</section><section id="mediana-a-posteriori" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="mediana-a-posteriori">Mediana a posteriori</h3>
<p>La <em>mediana a posteriori</em> è definita come il valore del parametro <span class="math inline">\(\theta\)</span> che divide la distribuzione a posteriori in due parti di uguale probabilità: il 50% della massa probabilistica si trova al di sotto di tale valore e il restante 50% al di sopra. Formalmente, essa soddisfa la condizione:</p>
<p><span class="math display">\[
P(\theta \leq \hat{\theta}_{\text{med}} \mid y) = 0.5.
\]</span></p>
<p>Rispetto alla media e alla moda a posteriori, la mediana offre una misura di tendenza centrale particolarmente <em>robusta</em>, in quanto poco sensibile alla presenza di valori estremi o code distributive pesanti. Questa proprietà la rende preferibile in contesti in cui la distribuzione a posteriori presenta marcate <em>asimmetrie</em> o è <em>multimodale</em>, situazioni in cui la media può essere distortta da valori anomali e la moda può risultare instabile o non unica. Grazie alla sua stabilità, la mediana a posteriori fornisce una rappresentazione più affidabile della posizione centrale del parametro quando la forma della distribuzione è irregolare, garantendo una sintesi inferenziale solida anche in condizioni di elevata variabilità o non normalità.</p>
</section></section><section id="misurare-lincertezza-varianza-a-posteriori" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="misurare-lincertezza-varianza-a-posteriori">Misurare l’incertezza: varianza a posteriori</h2>
<p>Oltre a individuare il valore più plausibile del parametro <span class="math inline">\(\theta\)</span>, è fondamentale quantificare l’incertezza residua associata alla nostra stima. A questo scopo, la <em>varianza a posteriori</em> fornisce una misura della dispersione dei valori di <span class="math inline">\(\theta\)</span> attorno alla sua media, condizionatamente ai dati osservati <span class="math inline">\(y\)</span>. Formalmente, essa è definita come:</p>
<p><span class="math display">\[
\mathbb{V}(\theta \mid y) = \mathbb{E}\left[(\theta - \mathbb{E}[\theta \mid y])^2 \mid y \right] = \int (\theta - \mathbb{E}[\theta \mid y])^2 \, p(\theta \mid y) \, d\theta.
\]</span></p>
<p>Un modo equivalente per calcolarla è attraverso l’identità:</p>
<p><span class="math display">\[
\mathbb{V}(\theta \mid y) = \mathbb{E}[\theta^2 \mid y] - \left(\mathbb{E}[\theta \mid y]\right)^2.
\]</span></p>
<p>Per interpretare più facilmente l’incertezza nella stessa unità di misura del parametro <span class="math inline">\(\theta\)</span>, è utile considerare la <em>deviazione standard a posteriori</em>, data semplicemente dalla radice quadrata della varianza.</p>
<p>In conclusione, mentre la moda (MAP), la media e la mediana a posteriori forniscono diverse misure di tendenza centrale per la stima puntuale di <span class="math inline">\(\theta\)</span>, la varianza (e la deviazione standard) a posteriori ne quantificano l’affidabilità. La scelta tra le diverse statistiche dipende dalla forma della distribuzione a posteriori e dagli obiettivi dell’analisi. Nel loro insieme, questi indicatori consentono di comunicare in modo sintetico non solo la migliore stima del parametro, ma anche il grado di confidenza ad essa associato, elemento cruciale in qualsiasi processo inferenziale.</p>
</section><section id="intervallo-di-credibilità" class="level2" data-number="7.3"><h2 data-number="7.3" class="anchored" data-anchor-id="intervallo-di-credibilità">
<span class="header-section-number">7.3</span> Intervallo di credibilità</h2>
<p>Nell’inferenza bayesiana, l’intervallo di credibilità è uno strumento utilizzato per definire un intervallo che contiene una determinata percentuale della massa della distribuzione a posteriori del parametro <span class="math inline">\(\theta\)</span>. Questo intervallo riflette l’incertezza associata alla stima del parametro: un intervallo più ampio suggerisce una maggiore incertezza. Lo scopo principale dell’intervallo di credibilità è fornire una misura quantitativa dell’incertezza riguardante <span class="math inline">\(\theta\)</span>.</p>
<p>A differenza degli intervalli di confidenza frequentisti, non esiste un unico intervallo di credibilità per un dato livello di confidenza <span class="math inline">\((1 - \alpha) \cdot 100\%\)</span>. In effetti, è possibile costruire un numero infinito di tali intervalli. Per questo motivo, è necessario stabilire criteri aggiuntivi per selezionare l’intervallo di credibilità più appropriato. Tra le opzioni più comuni ci sono l’intervallo di credibilità simmetrico e l’intervallo di massima densità posteriore (HPD).</p>
<section id="intervallo-di-credibilità-simmetrico" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="intervallo-di-credibilità-simmetrico">Intervallo di credibilità simmetrico</h3>
<p>Questo tipo di intervallo è centrato rispetto al punto di stima puntuale. Se <span class="math inline">\(\hat{\theta}\)</span> rappresenta la stima del parametro, l’intervallo simmetrico avrà la forma <span class="math inline">\((\hat{\theta} - a, \hat{\theta} + a)\)</span>, dove <span class="math inline">\(a\)</span> è un valore positivo scelto in modo tale che la massa totale inclusa sia pari a <span class="math inline">\((1 - \alpha)\)</span>. Più formalmente, un intervallo di credibilità simmetrico al livello <span class="math inline">\(\alpha\)</span> può essere espresso come:</p>
<p><span class="math display">\[
I_{\alpha} = [q_{\alpha/2}, q_{1 - \alpha/2}],
\]</span> dove <span class="math inline">\(q_z\)</span> rappresenta il quantile <span class="math inline">\(z\)</span> della distribuzione a posteriori. Ad esempio, un intervallo di credibilità simmetrico al 94% sarà:</p>
<p><span class="math display">\[
I_{0.06} = [q_{0.03}, q_{0.97}],
\]</span> dove il 3% della massa a posteriori si trova in ciascuna delle due code della distribuzione.</p>
</section><section id="intervallo-di-credibilità-più-stretto-intervallo-di-massima-densità-posteriore-hpd" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="intervallo-di-credibilità-più-stretto-intervallo-di-massima-densità-posteriore-hpd">Intervallo di credibilità più stretto (intervallo di massima densità posteriore, HPD)</h3>
<p>L’intervallo di massima densità posteriore (HPD) è l’intervallo più stretto possibile che contiene il <span class="math inline">\((1 - \alpha) \cdot 100\%\)</span> della massa a posteriori. A differenza dell’intervallo simmetrico, l’HPD include tutti i valori di <span class="math inline">\(\theta\)</span> che hanno la maggiore densità a posteriori. Per costruirlo, si disegna una linea orizzontale sulla distribuzione a posteriori e si regola l’altezza della linea in modo che l’area sotto la curva corrisponda a <span class="math inline">\((1 - \alpha)\)</span>. L’HPD risulta essere il più stretto tra tutti gli intervalli possibili per lo stesso livello di confidenza. Nel caso di una distribuzione a posteriori unimodale e simmetrica, l’HPD coincide con l’intervallo di credibilità simmetrico.</p>
</section><section id="interpretazione" class="level3" data-number="7.3.1"><h3 data-number="7.3.1" class="anchored" data-anchor-id="interpretazione">
<span class="header-section-number">7.3.1</span> Interpretazione</h3>
<p>Il calcolo degli <em>intervalli di credibilità</em>—in particolare dell’<em>intervallo di massima densità posteriore</em> (HPD)—richiede quasi sempre l’utilizzo di software statistici specializzati. Questo perché, nei modelli bayesiani con distribuzioni posteriori articolate o che richiedono simulazioni numeriche (ad esempio tramite Markov Chain Monte Carlo), ricavare a mano i confini dell’intervallo può risultare molto laborioso.</p>
<section id="incertezza-nel-paradigma-frequentista" class="level4" data-number="7.3.1.1"><h4 data-number="7.3.1.1" class="anchored" data-anchor-id="incertezza-nel-paradigma-frequentista">
<span class="header-section-number">7.3.1.1</span> Incertezza nel paradigma frequentista</h4>
<ul>
<li>
<em>Parametro fisso</em>: nel contesto frequentista, il parametro di interesse (ad esempio la media di popolazione <span class="math inline">\(\mu\)</span>) è un valore costante ma sconosciuto.<br>
</li>
<li>
<em>Ripetizione ipotetica</em>: immaginiamo di ripetere all’infinito il prelievo di campioni dalla popolazione. Per ciascun campione otteniamo una media <span class="math inline">\(\bar{x}\)</span> e costruendo un intervallo di confidenza al <span class="math inline">\(100(1-\alpha)\%\)</span> avremo che, nel lungo periodo, il <span class="math inline">\(100(1-\alpha)\%\)</span> di questi intervalli conterrà il vero <span class="math inline">\(\mu\)</span>.<br>
</li>
<li>
<em>Interpretazione del singolo intervallo</em>: per un singolo intervallo calcolato, la probabilità che contenga effettivamente <span class="math inline">\(\mu\)</span> è formalmente 0 o 1, perché <span class="math inline">\(\mu\)</span> non è soggetto a variabilità stocastica—siamo semplicemente ignari del suo valore reale.</li>
</ul></section><section id="incertezza-nel-paradigma-bayesiano" class="level4" data-number="7.3.1.2"><h4 data-number="7.3.1.2" class="anchored" data-anchor-id="incertezza-nel-paradigma-bayesiano">
<span class="header-section-number">7.3.1.2</span> Incertezza nel paradigma bayesiano</h4>
<ul>
<li>
<em>Parametro come variabile aleatoria</em>: qui <span class="math inline">\(\mu\)</span> non è più un valore fisso, ma possiede una distribuzione di probabilità che riflette sia l’informazione a priori sia quella fornita dai dati osservati.<br>
</li>
<li>
<em>Campionamento dalla distribuzione a posteriori</em>: grazie a tecniche di simulazione (ad es. MCMC), otteniamo un insieme di possibili valori di <span class="math inline">\(\mu\)</span> che segue la distribuzione posteriore.<br>
</li>
<li>
<em>Costruzione diretta dell’intervallo</em>: scegliendo i quantili al <span class="math inline">\(2.5\%\)</span> e al <span class="math inline">\(97.5\%\)</span> di questa distribuzione, otteniamo un intervallo di credibilità al 95%. In termini intuitivi, possiamo affermare che «c’è una probabilità del 95% che <span class="math inline">\(\mu\)</span> cada all’interno di questo intervallo, dati i dati e le ipotesi a priori».</li>
</ul></section><section id="confronto-e-considerazioni" class="level4" data-number="7.3.1.3"><h4 data-number="7.3.1.3" class="anchored" data-anchor-id="confronto-e-considerazioni">
<span class="header-section-number">7.3.1.3</span> Confronto e considerazioni</h4>
<ul>
<li>
<em>Frequentista</em>: l’intervallo di confidenza è un costrutto legato alla frequenza di lungo periodo di un procedimento ipotetico di campionamento.<br>
</li>
<li>
<em>Bayesiano</em>: l’intervallo di credibilità fornisce una misura puntuale dell’incertezza sul parametro, direttamente comprensibile come probabilità condizionata sui dati osservati.<br>
</li>
<li>
<em>Intuizione</em>: per molti, l’interpretazione bayesiana risulta più aderente al senso comune, perché traduce immediatamente il grado di fiducia che possiamo riporre nei valori ipotizzati per il parametro.</li>
</ul>
<p>In sintesi, mentre la teoria frequentista quantifica l’affidabilità del metodo di stima nel lungo periodo, l’approccio bayesiano esprime senza ambiguità la probabilità attuale che il parametro si trovi in un certo intervallo, alla luce delle evidenze e delle conoscenze pregresse.</p>
</section></section></section><section id="verifica-di-ipotesi-bayesiana" class="level2" data-number="7.4"><h2 data-number="7.4" class="anchored" data-anchor-id="verifica-di-ipotesi-bayesiana">
<span class="header-section-number">7.4</span> Verifica di ipotesi bayesiana</h2>
<p>L’inferenza bayesiana può essere applicata anche nel contesto della verifica di ipotesi, in un approccio noto come <em>verifica di ipotesi bayesiana</em>. In questo tipo di inferenza, l’obiettivo è valutare la plausibilità che un parametro <span class="math inline">\(\theta\)</span> assuma valori all’interno di un determinato intervallo. Ad esempio, possiamo voler sapere quanto è probabile che <span class="math inline">\(\theta\)</span> sia maggiore di 0.5 o che rientri in un intervallo specifico, come [0.5, 1.0].</p>
<p>In questo approccio, si calcola la <em>probabilità a posteriori</em> che <span class="math inline">\(\theta\)</span> si trovi all’interno dell’intervallo di interesse. Questa probabilità viene ottenuta integrando la distribuzione a posteriori su tale intervallo. Quindi, invece di rifiutare o accettare un’ipotesi come nel test di ipotesi frequentista, la verifica di ipotesi bayesiana fornisce una misura diretta della probabilità che un parametro rientri in un intervallo specifico, dato l’evidenza osservata e le informazioni a priori.</p>
<p>In altre parole, questo approccio consente di quantificare la nostra incertezza rispetto all’affermazione che <span class="math inline">\(\theta\)</span> rientri in un certo intervallo, fornendo una probabilità che rappresenta direttamente la plausibilità di quell’ipotesi.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Esempio 7.1</strong></span> Per illustrare l’approccio bayesiano, consideriamo i dati relativi ai punteggi del BDI-II (<em>Beck Depression Inventory - Second Edition</em>) di 30 soggetti clinici, come riportato nello studio condotto da <span class="citation" data-cites="zetsche_2019future">Zetsche et al. (<a href="#ref-zetsche_2019future" role="doc-biblioref">2019</a>)</span>. Il BDI-II è uno strumento per valutare la gravità dei sintomi depressivi.</p>
<p>I punteggi del BDI-II per i 30 soggetti sono:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Dati del BDI-II</span></span>
<span><span class="va">bdi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="fl">26</span>, <span class="fl">35</span>, <span class="fl">30</span>, <span class="fl">25</span>, <span class="fl">44</span>, <span class="fl">30</span>, <span class="fl">33</span>, <span class="fl">43</span>, <span class="fl">22</span>, <span class="fl">43</span>, </span>
<span>  <span class="fl">24</span>, <span class="fl">19</span>, <span class="fl">39</span>, <span class="fl">31</span>, <span class="fl">25</span>, <span class="fl">28</span>, <span class="fl">35</span>, <span class="fl">30</span>, <span class="fl">26</span>, <span class="fl">31</span>, </span>
<span>  <span class="fl">41</span>, <span class="fl">36</span>, <span class="fl">26</span>, <span class="fl">35</span>, <span class="fl">33</span>, <span class="fl">28</span>, <span class="fl">27</span>, <span class="fl">34</span>, <span class="fl">27</span>, <span class="fl">22</span></span>
<span><span class="op">)</span></span>
<span><span class="va">bdi</span></span>
<span><span class="co">#&gt;  [1] 26 35 30 25 44 30 33 43 22 43 24 19 39 31 25 28 35 30 26 31 41 36 26 35 33</span></span>
<span><span class="co">#&gt; [26] 28 27 34 27 22</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Un punteggio BDI-II <span class="math inline">\(\geq 30\)</span> indica un livello grave di depressione. Nel nostro campione, 17 pazienti su 30 manifestano un livello grave:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Conteggio di depressione grave</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">bdi</span> <span class="op">&gt;=</span> <span class="fl">30</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 17</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Stima della distribuzione a posteriori.</p>
<p>Supponiamo di voler stimare la probabilità <span class="math inline">\(\theta\)</span> di depressione grave nei pazienti clinici utilizzando una distribuzione a priori <span class="math inline">\(Beta(8, 2)\)</span>. I dati possono essere visti come una sequenza di prove Bernoulliane indipendenti, dove la presenza di depressione grave è un “successo”. La verosimiglianza è quindi binomiale con parametri <span class="math inline">\(n = 30\)</span> e <span class="math inline">\(y = 17\)</span>.</p>
<p>Con una distribuzione a priori <span class="math inline">\(Beta(8, 2)\)</span>, la distribuzione a posteriori di <span class="math inline">\(\theta\)</span> sarà:</p>
<p><span class="math display">\[
\text{Beta}(\alpha = 8 + 17, \beta = 2 + 30 - 17) = \text{Beta}(25, 15).
\]</span> Tracciamo la distribuzione a posteriori.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Parametri della distribuzione Beta</span></span>
<span><span class="va">alpha</span> <span class="op">&lt;-</span> <span class="fl">25</span></span>
<span><span class="va">beta</span> <span class="op">&lt;-</span> <span class="fl">15</span></span>
<span></span>
<span><span class="co"># Calcolo della densità per valori di theta</span></span>
<span><span class="va">theta</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span>, length.out <span class="op">=</span> <span class="fl">200</span><span class="op">)</span></span>
<span><span class="va">posterior_density</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Beta.html">dbeta</a></span><span class="op">(</span><span class="va">theta</span>, <span class="va">alpha</span>, <span class="va">beta</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Grafico della distribuzione a posteriori</span></span>
<span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">theta</span>, <span class="va">posterior_density</span><span class="op">)</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">theta</span>, y <span class="op">=</span> <span class="va">posterior_density</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_line</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    title <span class="op">=</span> <span class="st">"Distribuzione a Posteriori Beta(25, 15)"</span>,</span>
<span>    x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="va">theta</span><span class="op">)</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Densità di probabilità"</span></span>
<span>  <span class="op">)</span> </span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07_summary_posterior_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Stime puntuali.</strong></p>
<ol type="1">
<li>
<strong>Media a posteriori.</strong> La media della distribuzione a posteriori è calcolata come:</li>
</ol>
<p><span class="math display">\[
\mathbb{E}(\theta | y = 17) = \frac{\alpha}{\alpha + \beta} = \frac{25}{25 + 15} = 0.625.
\]</span> In R:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calcolo della media a posteriori</span></span>
<span><span class="va">posterior_mean</span> <span class="op">&lt;-</span> <span class="va">alpha</span> <span class="op">/</span> <span class="op">(</span><span class="va">alpha</span> <span class="op">+</span> <span class="va">beta</span><span class="op">)</span></span>
<span><span class="va">posterior_mean</span></span>
<span><span class="co">#&gt; [1] 0.625</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>
<strong>Moda a posteriori (MAP).</strong> La moda della distribuzione a posteriori è:</li>
</ol>
<p><span class="math display">\[
Mo(\theta | y = 17) = \frac{\alpha - 1}{\alpha + \beta - 2} = \frac{25 - 1}{25 + 15 - 2} = 0.6316.
\]</span> In R:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calcolo della moda a posteriori</span></span>
<span><span class="va">posterior_mode</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">alpha</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="va">alpha</span> <span class="op">+</span> <span class="va">beta</span> <span class="op">-</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">posterior_mode</span></span>
<span><span class="co">#&gt; [1] 0.632</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li>
<strong>Mediana a posteriori.</strong> La mediana si ottiene utilizzando la funzione di distribuzione cumulativa inversa:</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calcolo della mediana a posteriori</span></span>
<span><span class="va">posterior_median</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Beta.html">qbeta</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="va">alpha</span>, <span class="va">beta</span><span class="op">)</span></span>
<span><span class="va">posterior_median</span></span>
<span><span class="co">#&gt; [1] 0.627</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Intervallo di credibilità.</strong></p>
<ol type="1">
<li>
<strong>Intervallo di credibilità simmetrico.</strong> L’intervallo di credibilità simmetrico al 94% è dato dai percentili 3% e 97%:</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Intervallo di credibilità simmetrico al 94%</span></span>
<span><span class="va">cred_interval</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Beta.html">qbeta</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.03</span>, <span class="fl">0.97</span><span class="op">)</span>, <span class="va">alpha</span>, <span class="va">beta</span><span class="op">)</span></span>
<span><span class="va">cred_interval</span></span>
<span><span class="co">#&gt; [1] 0.478 0.761</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Possiamo interpretare questo intervallo come segue: c’è una certezza soggettiva del 94% che <span class="math inline">\(\theta\)</span> sia compreso tra 0.478 e 0.761.</p>
<p><strong>Verifica di ipotesi bayesiana.</strong> Infine, calcoliamo la probabilità che <span class="math inline">\(\theta &gt; 0.5\)</span>:</p>
<p><span class="math display">\[
P(\theta &gt; 0.5 | y = 17) = \int_{0.5}^1 f(\theta | y = 17) d\theta.
\]</span> In R:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Probabilità P(theta &gt; 0.5)</span></span>
<span><span class="va">prob_theta_greater_0_5</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Beta.html">pbeta</a></span><span class="op">(</span><span class="fl">0.5</span>, <span class="va">alpha</span>, <span class="va">beta</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">prob_theta_greater_0_5</span></span>
<span><span class="co">#&gt; [1] 0.946</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In conclusione, utilizzando un approccio bayesiano, abbiamo stimato la distribuzione a posteriori di <span class="math inline">\(\theta\)</span>, ottenuto stime puntuali e costruito intervalli di credibilità. Abbiamo inoltre calcolato la probabilità che <span class="math inline">\(\theta\)</span> superi una soglia specifica, mostrando la flessibilità e l’interpretabilità delle analisi bayesiane.</p>
</div>
</section><section id="sintesi-della-distribuzione-a-posteriori-in-contesti-multivariati" class="level2" data-number="7.5"><h2 data-number="7.5" class="anchored" data-anchor-id="sintesi-della-distribuzione-a-posteriori-in-contesti-multivariati">
<span class="header-section-number">7.5</span> Sintesi della distribuzione a posteriori in contesti multivariati</h2>
<p>L’estensione dell’analisi bayesiana a modelli con più parametri introduce complessità legate alle interdipendenze tra i parametri stessi. Tali relazioni, se non adeguatamente considerate, possono condurre a sintesi incomplete o fuorvianti della distribuzione a posteriori, con possibili errori interpretativi.</p>
<section id="la-sfida-delle-correlazioni-tra-parametri" class="level3" data-number="7.5.1"><h3 data-number="7.5.1" class="anchored" data-anchor-id="la-sfida-delle-correlazioni-tra-parametri">
<span class="header-section-number">7.5.1</span> La sfida delle correlazioni tra parametri</h3>
<p>Uno degli aspetti critici riguarda la presenza di <em>correlazioni tra i parametri</em>. Le distribuzioni marginali a posteriori — spesso utilizzate nei riassunti statistici — possono risultare ingannevoli se esaminate isolatamente. Parametri fortemente correlati possono dar luogo a marginali apparentemente piatte o poco informative, benché la loro struttura congiunta restringa significativamente lo spazio delle combinazioni plausibili. Ciò implica che, nonostante l’incertezza marginale possa sembrare elevata, l’incertezza congiunta su specifiche relazioni parametriche può essere molto ridotta.</p>
<p>Un’ulteriore complicazione sorge quando le relazioni tra parametri sono <em>non lineari</em>. In tali casi, il massimo della distribuzione congiunta può non coincidere con i massimi delle distribuzioni marginali. Ad esempio, in presenza di strutture a “banana” o altre forme complesse, gli usuali indicatori di tendenza centrale (come la moda o la media) calcolati sui singoli parametri possono non riflettere la regione di massima densità di probabilità nello spazio multivariato.</p>
</section><section id="approcci-per-una-sintesi-efficace" class="level3" data-number="7.5.2"><h3 data-number="7.5.2" class="anchored" data-anchor-id="approcci-per-una-sintesi-efficace">
<span class="header-section-number">7.5.2</span> Approcci per una sintesi efficace</h3>
<p>Per una rappresentazione fedele dell’incertezza in contesti multivariati, è essenziale adottare una prospettiva che vada oltre l’analisi delle marginali:</p>
<ul>
<li><p><strong>Visualizzazione delle relazioni congiunte</strong>: Grafici di dispersione a coppie (<em>pair plots</em>) o contour plot bidimensionali consentono di esplorare visivamente le dipendenze tra parametri, rivelando strutture non catturate dalle marginali.</p></li>
<li><p><strong>Utilizzo di distribuzioni predittive</strong>: Il confronto tra distribuzioni predittive a priori e a posteriori fornisce una visione complessiva dell’incertezza ridotta dall’evidenza dei dati, tenendo conto di tutte le interazioni parametriche.</p></li>
<li><p><strong>Misure di dipendenza avanzate</strong>: In casi di relazioni non lineari, misure come la correlazione di Spearman o l’informazione mutua possono integrare la correlazione lineare, offrendo una descrizione più completa delle dipendenze.</p></li>
<li><p><strong>Analisi di sensibilità</strong>: Valutare come variano le inferenze al variare di gruppi di parametri aiuta a identificare le relazioni più influenti e a comprendere la stabilità delle conclusioni.</p></li>
</ul>
<p>In conclusione, una sintesi appropriata della distribuzione a posteriori in presenza di più parametri richiede un esame congiunto delle relazioni tra di essi. La sola inspezione delle distribuzioni marginali rischia di occultare importanti fonti di informazione circa la struttura parametrica, con possibili conseguenze sulle inferenze tratte. Un approccio integrato — che unisca visualizzazione, misure di dipendenza e analisi di sensibilità — è fondamentale per una comprensione robusta dei risultati bayesiani in contesti multivariati.</p>
</section></section><section id="riflessioni-conclusive" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="riflessioni-conclusive">Riflessioni conclusive</h2>
<p>In questo capitolo abbiamo visto che il cuore dell’approccio bayesiano non è soltanto ottenere una distribuzione a posteriori, ma anche imparare a descriverla in modo utile. Abbiamo distinto tra diversi modi di riassumere un posterior (media, mediana, moda) e tra diverse forme di intervallo credibile, chiarendo come ciascuna offra una prospettiva diversa sull’incertezza.</p>
<p>Queste sintesi non sostituiscono la distribuzione completa, ma la rendono comunicabile. L’intervallo credibile, in particolare, ci permette di dire con chiarezza quali valori del parametro hanno una certa probabilità a posteriori di essere veri, dato il modello e i dati osservati. Questo rappresenta una differenza cruciale rispetto all’approccio frequentista, in cui l’interpretazione degli intervalli di confidenza rimane indiretta e spesso fonte di equivoci.</p>
<p>Dal punto di vista della ricerca psicologica, la capacità di sintetizzare il posterior è indispensabile. Molti risultati sperimentali si basano sulla stima di proporzioni, medie o differenze tra gruppi, e il modo in cui presentiamo l’incertezza può fare la differenza tra una conclusione chiara e una affermazione ambigua. Una sintesi ben costruita non solo comunica meglio, ma rafforza la solidità della conoscenza accumulata, perché rende trasparenti i margini di dubbio.</p>
<p>Questo capitolo chiude così un primo ciclo del nostro percorso: abbiamo imparato a costruire distribuzioni a posteriori e a sintetizzarle. Nei prossimi capitoli vedremo come andare oltre i parametri e usare il posterior per <em>fare previsioni sui dati futuri</em> e per <em>confrontare modelli alternativi</em>. È qui che il pensiero bayesiano mostrerà tutta la sua forza: non solo descrivere ciò che sappiamo, ma anche guidare ciò che possiamo aspettarci.</p>
<div class="callout callout-style-simple callout-important no-icon callout-titled" title="Problemi">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Problemi
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1. Quali sono le principali statistiche utilizzate per la stima puntuale di un parametro nella distribuzione a posteriori?</strong></p>
<ul>
<li>Spiega le differenze tra <strong>moda (MAP)</strong>, <strong>media a posteriori</strong> e <strong>mediana</strong>.</li>
<li>In quali contesti è preferibile utilizzare una di queste statistiche rispetto alle altre?</li>
</ul>
<p><strong>2. Qual è la differenza tra un intervallo di credibilità bayesiano e un intervallo di confidenza frequentista?</strong></p>
<ul>
<li>Spiega le differenze concettuali tra i due approcci.</li>
<li>Quale dei due è più intuitivo in termini di incertezza sui parametri?</li>
</ul>
<p><strong>3. Cos’è un intervallo di massima densità posteriore (HPD) e in cosa si differenzia dall’intervallo di credibilità simmetrico?</strong></p>
<ul>
<li>Spiega il concetto di HPD e perché è più informativo in alcuni casi.</li>
<li>In quali situazioni l’HPD è preferibile rispetto all’intervallo di credibilità simmetrico?</li>
</ul>
<p><strong>4. Quali sono le problematiche associate alla moda (MAP) come stima puntuale?</strong></p>
<ul>
<li>Perché il <strong>MAP</strong> può essere meno affidabile rispetto ad altre statistiche?</li>
<li>Quali problemi si possono incontrare nei modelli bayesiani complessi?</li>
</ul>
<p><strong>5. In che modo la sintesi della distribuzione a posteriori cambia nel caso di più parametri incogniti?</strong></p>
<ul>
<li>Quali sono le principali difficoltà nell’interpretare la distribuzione congiunta di più parametri?</li>
<li>Come si possono visualizzare e sintetizzare distribuzioni posteriori multivariate?</li>
</ul>
<p><strong>Domande applicative in R</strong></p>
<p>Per queste domande, usa il dataset basato sulla <strong>Satisfaction with Life Scale (SWLS)</strong>, supponendo che i dati seguano una distribuzione normale.</p>
<p><strong>1. Calcola la media, la mediana e la moda a posteriori della distribuzione della media SWLS, assumendo una distribuzione a priori gaussiana molto diffusa.</strong> - Usa il metodo delle distribuzioni coniugate per ottenere la distribuzione a posteriori.</p>
<p><strong>2. Costruisci un intervallo di credibilità simmetrico al 94% per la media SWLS.</strong></p>
<ul>
<li>Usa la distribuzione normale a posteriori per calcolare l’intervallo.</li>
</ul>
<p><strong>3. Visualizza la distribuzione a posteriori della media SWLS con un grafico di densità.</strong></p>
<ul>
<li>Genera un campione dalla distribuzione a posteriori e rappresentalo con <strong>ggplot2</strong>.</li>
</ul>
<p><strong>4. Confronta l’intervallo di credibilità simmetrico con l’intervallo di massima densità posteriore (HPD).</strong></p>
<ul>
<li>Usa la funzione <strong>hdi()</strong> del pacchetto <strong>bayestestR</strong> per calcolare l’HPD.</li>
</ul>
<p><strong>5. Calcola la probabilità a posteriori che la media SWLS sia minore di 23.</strong></p>
<ul>
<li>Usa la distribuzione a posteriori per calcolare questa probabilità.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" title="Soluzioni">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soluzioni
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1. Quali sono le principali statistiche utilizzate per la stima puntuale di un parametro nella distribuzione a posteriori?</strong></p>
<p>Le tre principali statistiche usate per ottenere una <strong>stima puntuale</strong> del parametro <span class="math inline">\(\theta\)</span> nella distribuzione a posteriori sono:</p>
<ol type="1">
<li>
<strong>Moda (Massimo a Posteriori, MAP)</strong>
<ul>
<li>È il valore di <span class="math inline">\(\theta\)</span> che massimizza la distribuzione a posteriori <span class="math inline">\(p(\theta \mid y)\)</span>.<br>
</li>
<li>Se la distribuzione è unimodale e simmetrica, il MAP coincide con la media a posteriori.<br>
</li>
<li>Il MAP è spesso simile alla stima di massima verosimiglianza (MLE) quando il prior è uniforme.</li>
</ul>
</li>
<li>
<strong>Media a Posteriori</strong>
<ul>
<li>È il valore atteso della distribuzione a posteriori:<br><span class="math display">\[
E(\theta \mid y) = \int \theta \, p(\theta \mid y) \, d\theta
\]</span>
</li>
<li>È la stima più utile quando si vuole minimizzare l’errore quadratico medio (MSE).<br>
</li>
<li>Risente dell’eventuale asimmetria della distribuzione, spostandosi verso le code.</li>
</ul>
</li>
<li>
<strong>Mediana a Posteriori</strong>
<ul>
<li>È il valore che divide la distribuzione a posteriori in due parti uguali:<br><span class="math display">\[
P(\theta \leq \theta_{\text{mediana}} \mid y) = 0.5
\]</span>
</li>
<li>È più robusta agli outlier rispetto alla media ed è utile quando la distribuzione è fortemente asimmetrica.</li>
</ul>
</li>
</ol>
<p>💡 <strong>Quando usarle?</strong> - Se la distribuzione è <strong>simmetrica</strong>, tutte e tre le statistiche coincidono. - Se la distribuzione è <strong>asimmetrica</strong>, la <strong>mediana</strong> è più robusta, la <strong>media</strong> può essere influenzata dalle code e il <strong>MAP</strong> è utile se si vuole un valore più probabile.</p>
<p><strong>2. Qual è la differenza tra un intervallo di credibilità bayesiano e un intervallo di confidenza frequentista?</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 34%">
<col style="width: 36%">
</colgroup>
<thead><tr class="header">
<th>Caratteristica</th>
<th>Intervallo di Credibilità (Bayesiano)</th>
<th>Intervallo di Confidenza (Frequentista)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Significato</strong></td>
<td>Esprime la probabilità che il parametro sia nell’intervallo, dati i dati osservati.</td>
<td>È una proprietà di un metodo di campionamento: se si ripetesse l’esperimento infinite volte, il <span class="math inline">\((1 - \alpha)100\%\)</span> degli intervalli conterrebbe il vero valore del parametro.</td>
</tr>
<tr class="even">
<td><strong>Approccio</strong></td>
<td>Assume che il parametro sia una variabile casuale con una distribuzione di probabilità.</td>
<td>Assume che il parametro sia fisso e sconosciuto, mentre i dati sono casuali.</td>
</tr>
<tr class="odd">
<td><strong>Interpretazione</strong></td>
<td>“C’è il 95% di probabilità che il parametro sia tra questi valori.”</td>
<td>“Se ripetessimo l’esperimento molte volte, il 95% degli intervalli conterrebbe il vero parametro.”</td>
</tr>
</tbody>
</table>
<p>💡 <strong>Differenza fondamentale:</strong></p>
<ul>
<li>L’intervallo di credibilità è <strong>probabilistico</strong> e più intuitivo: si può direttamente dire che il parametro ha il 95% di probabilità di trovarsi nell’intervallo.<br>
</li>
<li>L’intervallo di confidenza è <strong>basato sulla ripetizione ipotetica</strong> dell’esperimento e non può essere interpretato in termini probabilistici sul singolo intervallo.</li>
</ul>
<p><strong>3. Cos’è un intervallo di massima densità posteriore (HPD) e in cosa si differenzia dall’intervallo di credibilità simmetrico?</strong></p>
<p>L’<strong>intervallo di massima densità posteriore (HPD)</strong> è l’intervallo più stretto che contiene una percentuale fissata (es. 94%) della distribuzione a posteriori. Si distingue dall’intervallo di credibilità simmetrico perché:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 22%">
<col style="width: 54%">
</colgroup>
<thead><tr class="header">
<th>Caratteristica</th>
<th>Intervallo HPD</th>
<th>Intervallo di Credibilità Simmetrico</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Definizione</strong></td>
<td>Contiene il <span class="math inline">\((1 - \alpha)100\%\)</span> della probabilità a posteriori, minimizzando la lunghezza dell’intervallo.</td>
<td>È centrato attorno alla mediana e copre una frazione fissa della distribuzione.</td>
</tr>
<tr class="even">
<td><strong>Forma</strong></td>
<td>Può essere asimmetrico e discontinuo se la distribuzione è multimodale.</td>
<td>È sempre simmetrico.</td>
</tr>
<tr class="odd">
<td><strong>Vantaggio</strong></td>
<td>È più informativo se la distribuzione è asimmetrica o multimodale.</td>
<td>È più facile da calcolare, specialmente per distribuzioni unimodali.</td>
</tr>
</tbody>
</table>
<p>💡 <strong>Quando usarli?</strong></p>
<ul>
<li>Se la distribuzione è <strong>simmetrica</strong>, entrambi gli intervalli danno risultati simili.<br>
</li>
<li>Se la distribuzione è <strong>asimmetrica o multimodale</strong>, l’HPD è più informativo.</li>
</ul>
<p><strong>4. Quali sono le problematiche associate alla moda (MAP) come stima puntuale?</strong></p>
<p>Sebbene il <strong>MAP</strong> sia un concetto intuitivo (il valore più probabile della distribuzione a posteriori), presenta alcune limitazioni:</p>
<ol type="1">
<li>
<strong>Difficoltà computazionale con MCMC</strong>
<ul>
<li>Con metodi di campionamento come <strong>Markov Chain Monte Carlo (MCMC)</strong>, trovare il massimo della distribuzione a posteriori è difficile perché la funzione viene stimata in modo discreto.</li>
<li>Spesso si preferisce stimare <strong>media</strong> o <strong>mediana</strong>, più facili da calcolare con MCMC.</li>
</ul>
</li>
<li>
<strong>Sensibilità ai dati e al prior</strong>
<ul>
<li>Il MAP dipende fortemente dal <strong>prior</strong> scelto.</li>
<li>Se il prior è informativo, il MAP può spostarsi troppo rispetto ai dati.</li>
</ul>
</li>
<li>
<strong>Problemi con distribuzioni multimodali</strong>
<ul>
<li>Se la distribuzione a posteriori ha più di un massimo (moda), il MAP potrebbe non essere una buona rappresentazione della distribuzione.</li>
</ul>
</li>
</ol>
<p>💡 <strong>Quando evitarlo?</strong><br>
- Se la distribuzione a posteriori è <strong>asimmetrica o multimodale</strong>. - Se si usa un <strong>metodo MCMC</strong>, dove la media o la mediana sono più semplici da stimare.</p>
<p><strong>5. In che modo la sintesi della distribuzione a posteriori cambia nel caso di più parametri incogniti?</strong></p>
<p>Quando l’inferenza bayesiana coinvolge più parametri (es. <span class="math inline">\(\mu\)</span> e <span class="math inline">\(\sigma\)</span>), l’analisi diventa più complessa per diversi motivi:</p>
<ol type="1">
<li>
<strong>Interazioni tra parametri</strong>
<ul>
<li>I parametri spesso non sono indipendenti: la distribuzione a posteriori congiunta può mostrare <strong>correlazioni</strong> che non emergono dalle distribuzioni marginali.</li>
</ul>
</li>
<li>
<strong>Difficoltà di visualizzazione</strong>
<ul>
<li>Per un parametro si usa un istogramma o una funzione di densità.</li>
<li>Per due parametri si usa un <strong>contour plot</strong> o un <strong>grafico 3D</strong>.</li>
<li>Con più di due parametri, si ricorre a <strong>pair plots</strong> o <strong>matrici di correlazione</strong>.</li>
</ul>
</li>
<li>
<strong>Stimare margine e congiunta</strong>
<ul>
<li>La distribuzione marginale di un parametro si ottiene integrando la distribuzione congiunta rispetto agli altri parametri: <span class="math display">\[
p(\theta_1) = \int p(\theta_1, \theta_2) d\theta_2
\]</span>
</li>
<li>Se i parametri sono fortemente correlati, le marginali possono <strong>nascondere informazioni importanti</strong>.</li>
</ul>
</li>
<li>
<strong>Rischio di correlazioni non lineari</strong>
<ul>
<li>Le correlazioni non lineari tra i parametri possono portare a distribuzioni con forme complesse (es. a banana), rendendo difficile la sintesi con MAP o media.</li>
</ul>
</li>
</ol>
<p>💡 <strong>Strategie per affrontare il problema:</strong><br>
- <strong>Visualizzare le correlazioni</strong> tra i parametri con scatter plot o heatmap.<br>
- <strong>Usare tecniche di riduzione della dimensionalità</strong> come PCA (Analisi delle Componenti Principali).<br>
- <strong>Utilizzare il MCMC</strong> per campionare direttamente dalla distribuzione congiunta.</p>
<p><strong>Esercizio in R con i dati SWLS</strong></p>
<p>Nell’esercizio, usa i dati della SWLS che sono stati raccolti. Qui useremo i dati seguenti:</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">swls_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  soddisfazione <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4.2</span>, <span class="fl">5.1</span>, <span class="fl">4.7</span>, <span class="fl">4.3</span>, <span class="fl">5.5</span>, <span class="fl">4.9</span>, <span class="fl">4.8</span>, <span class="fl">5.0</span>, <span class="fl">4.6</span>, <span class="fl">4.4</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>1. Calcola la media, la mediana e la moda a posteriori della distribuzione della media SWLS, assumendo una distribuzione a priori gaussiana molto diffusa.</strong></p>
<ul>
<li>Usa il metodo delle distribuzioni coniugate per ottenere la distribuzione a posteriori.</li>
</ul>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tibble.tidyverse.org/">tibble</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Dati</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">swls_data</span><span class="op">)</span></span>
<span><span class="va">mean_x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">swls_data</span><span class="op">$</span><span class="va">soddisfazione</span><span class="op">)</span></span>
<span><span class="va">sigma</span> <span class="op">&lt;-</span> <span class="fl">1</span>  <span class="co"># Deviazione standard nota</span></span>
<span></span>
<span><span class="co"># Prior diffuso</span></span>
<span><span class="va">mu_prior</span> <span class="op">&lt;-</span> <span class="fl">4.5</span>    </span>
<span><span class="va">sigma_prior</span> <span class="op">&lt;-</span> <span class="fl">10</span>  </span>
<span></span>
<span><span class="co"># Media a posteriori</span></span>
<span><span class="va">mu_post</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">sigma_prior</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">mean_x</span> <span class="op">+</span> <span class="va">sigma</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">n</span> <span class="op">*</span> <span class="va">mu_prior</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="va">sigma_prior</span><span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="va">sigma</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">n</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Deviazione standard a posteriori</span></span>
<span><span class="va">sigma_post</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="op">(</span><span class="va">sigma_prior</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">sigma</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="va">sigma_prior</span><span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="va">sigma</span><span class="op">^</span><span class="fl">2</span> <span class="op">*</span> <span class="va">n</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Moda (MAP)</span></span>
<span><span class="va">posterior_mode</span> <span class="op">&lt;-</span> <span class="va">mu_post</span>  <span class="co"># Per una distribuzione normale, MAP coincide con la media</span></span>
<span></span>
<span><span class="co"># Mediana (simile alla media in una distribuzione normale)</span></span>
<span><span class="va">posterior_median</span> <span class="op">&lt;-</span> <span class="va">mu_post</span></span>
<span></span>
<span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span><span class="st">"Media a Posteriori"</span> <span class="op">=</span> <span class="va">mu_post</span>,</span>
<span>       <span class="st">"Moda (MAP)"</span> <span class="op">=</span> <span class="va">posterior_mode</span>,</span>
<span>       <span class="st">"Mediana"</span> <span class="op">=</span> <span class="va">posterior_median</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>2. Costruisci un intervallo di credibilità simmetrico al 94% per la media SWLS.</strong></p>
<ul>
<li>Usa la distribuzione normale a posteriori per calcolare l’intervallo.</li>
</ul>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cred_interval</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.03</span>, <span class="fl">0.97</span><span class="op">)</span>, mean <span class="op">=</span> <span class="va">mu_post</span>, sd <span class="op">=</span> <span class="va">sigma_post</span><span class="op">)</span></span>
<span><span class="va">cred_interval</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>3. Visualizza la distribuzione a posteriori della media SWLS con un grafico di densità.</strong></p>
<ul>
<li>Genera un campione dalla distribuzione a posteriori e rappresentalo con <strong>ggplot2</strong>.</li>
</ul>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Campionamento dalla distribuzione a posteriori</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span><span class="va">samples</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">1000</span>, mean <span class="op">=</span> <span class="va">mu_post</span>, sd <span class="op">=</span> <span class="va">sigma_post</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Creazione del dataframe</span></span>
<span><span class="va">samples_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>media_campionata <span class="op">=</span> <span class="va">samples</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Grafico della distribuzione a posteriori</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">samples_df</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">media_campionata</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_density.html">geom_density</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"blue"</span>, alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Distribuzione a Posteriori della Media SWLS"</span>,</span>
<span>       x <span class="op">=</span> <span class="st">"Media"</span>, y <span class="op">=</span> <span class="st">"Densità"</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>4. Confronta l’intervallo di credibilità simmetrico con l’intervallo di massima densità posteriore (HPD).</strong></p>
<ul>
<li>Usa la funzione <strong>hdi()</strong> del pacchetto <strong>bayestestR</strong> per calcolare l’HPD.</li>
</ul>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://easystats.github.io/bayestestR/">bayestestR</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calcolo intervallo HPD al 94%</span></span>
<span><span class="va">hpd_interval</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://easystats.github.io/bayestestR/reference/hdi.html">hdi</a></span><span class="op">(</span><span class="va">samples</span>, ci <span class="op">=</span> <span class="fl">0.94</span><span class="op">)</span></span>
<span><span class="va">hpd_interval</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>5. Calcola la probabilità a posteriori che la media SWLS sia minore di 23 – per fare un esempio, qui caloleremo per i dati simulati la probabilità a posteriori per la media SWLS maggiore di 4.7.</strong></p>
<ul>
<li>Usa la distribuzione a posteriori per calcolare questa probabilità.</li>
</ul>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">prob_greater_4_7</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fl">4.7</span>, mean <span class="op">=</span> <span class="va">mu_post</span>, sd <span class="op">=</span> <span class="va">sigma_post</span><span class="op">)</span></span>
<span><span class="va">prob_greater_4_7</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Informazioni sull'ambiente di sviluppo">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Informazioni sull’ambiente di sviluppo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.5.1 (2025-06-13)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin20</span></span>
<span><span class="co">#&gt; Running under: macOS Sequoia 15.6.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C/UTF-8/C/C/C/C</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Rome</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] mice_3.18.0           pillar_1.11.0         tinytable_0.13.0     </span></span>
<span><span class="co">#&gt;  [4] patchwork_1.3.2       ggdist_3.3.3          tidybayes_3.0.7      </span></span>
<span><span class="co">#&gt;  [7] bayesplot_1.14.0      ggplot2_3.5.2         reliabilitydiag_0.2.1</span></span>
<span><span class="co">#&gt; [10] priorsense_1.1.1      posterior_1.6.1       loo_2.8.0            </span></span>
<span><span class="co">#&gt; [13] rstan_2.32.7          StanHeaders_2.32.10   brms_2.22.0          </span></span>
<span><span class="co">#&gt; [16] Rcpp_1.1.0            sessioninfo_1.2.3     conflicted_1.2.0     </span></span>
<span><span class="co">#&gt; [19] janitor_2.2.1         matrixStats_1.5.0     modelr_0.1.11        </span></span>
<span><span class="co">#&gt; [22] tibble_3.3.0          dplyr_1.1.4           tidyr_1.3.1          </span></span>
<span><span class="co">#&gt; [25] rio_1.2.3             here_1.0.1           </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;  [1] Rdpack_2.6.4          gridExtra_2.3         inline_0.3.21        </span></span>
<span><span class="co">#&gt;  [4] sandwich_3.1-1        rlang_1.1.6           magrittr_2.0.3       </span></span>
<span><span class="co">#&gt;  [7] multcomp_1.4-28       snakecase_0.11.1      compiler_4.5.1       </span></span>
<span><span class="co">#&gt; [10] systemfonts_1.2.3     vctrs_0.6.5           stringr_1.5.1        </span></span>
<span><span class="co">#&gt; [13] pkgconfig_2.0.3       shape_1.4.6.1         arrayhelpers_1.1-0   </span></span>
<span><span class="co">#&gt; [16] fastmap_1.2.0         backports_1.5.0       labeling_0.4.3       </span></span>
<span><span class="co">#&gt; [19] rmarkdown_2.29        nloptr_2.2.1          ragg_1.5.0           </span></span>
<span><span class="co">#&gt; [22] purrr_1.1.0           jomo_2.7-6            xfun_0.53            </span></span>
<span><span class="co">#&gt; [25] glmnet_4.1-10         cachem_1.1.0          jsonlite_2.0.0       </span></span>
<span><span class="co">#&gt; [28] pan_1.9               broom_1.0.9           parallel_4.5.1       </span></span>
<span><span class="co">#&gt; [31] R6_2.6.1              stringi_1.8.7         RColorBrewer_1.1-3   </span></span>
<span><span class="co">#&gt; [34] rpart_4.1.24          boot_1.3-32           lubridate_1.9.4      </span></span>
<span><span class="co">#&gt; [37] estimability_1.5.1    iterators_1.0.14      knitr_1.50           </span></span>
<span><span class="co">#&gt; [40] zoo_1.8-14            pacman_0.5.1          nnet_7.3-20          </span></span>
<span><span class="co">#&gt; [43] Matrix_1.7-4          splines_4.5.1         timechange_0.3.0     </span></span>
<span><span class="co">#&gt; [46] tidyselect_1.2.1      abind_1.4-8           codetools_0.2-20     </span></span>
<span><span class="co">#&gt; [49] curl_7.0.0            pkgbuild_1.4.8        lattice_0.22-7       </span></span>
<span><span class="co">#&gt; [52] withr_3.0.2           bridgesampling_1.1-2  coda_0.19-4.1        </span></span>
<span><span class="co">#&gt; [55] evaluate_1.0.5        survival_3.8-3        RcppParallel_5.1.11-1</span></span>
<span><span class="co">#&gt; [58] tensorA_0.36.2.1      checkmate_2.3.3       foreach_1.5.2        </span></span>
<span><span class="co">#&gt; [61] stats4_4.5.1          reformulas_0.4.1      distributional_0.5.0 </span></span>
<span><span class="co">#&gt; [64] generics_0.1.4        rprojroot_2.1.1       rstantools_2.5.0     </span></span>
<span><span class="co">#&gt; [67] scales_1.4.0          minqa_1.2.8           xtable_1.8-4         </span></span>
<span><span class="co">#&gt; [70] glue_1.8.0            emmeans_1.11.2-8      tools_4.5.1          </span></span>
<span><span class="co">#&gt; [73] lme4_1.1-37           mvtnorm_1.3-3         grid_4.5.1           </span></span>
<span><span class="co">#&gt; [76] rbibutils_2.3         QuickJSR_1.8.0        colorspace_2.1-1     </span></span>
<span><span class="co">#&gt; [79] nlme_3.1-168          cli_3.6.5             textshaping_1.0.3    </span></span>
<span><span class="co">#&gt; [82] svUnit_1.0.8          Brobdingnag_1.2-9     V8_7.0.0             </span></span>
<span><span class="co">#&gt; [85] gtable_0.3.6          digest_0.6.37         TH.data_1.1-4        </span></span>
<span><span class="co">#&gt; [88] htmlwidgets_1.6.4     farver_2.1.2          memoise_2.0.1        </span></span>
<span><span class="co">#&gt; [91] htmltools_0.5.8.1     lifecycle_1.0.4       mitml_0.4-5          </span></span>
<span><span class="co">#&gt; [94] MASS_7.3-65</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="bibliografia" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="bibliografia">Bibliografia</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Johnson2022bayesrules" class="csl-entry" role="listitem">
Johnson, A. A., Ott, M., &amp; Dogucu, M. (2022). <em><span>Bayes Rules! An Introduction to Bayesian Modeling with R</span></em>. CRC Press.
</div>
<div id="ref-zetsche_2019future" class="csl-entry" role="listitem">
Zetsche, U., Buerkner, P.-C., &amp; Renneberg, B. (2019). Future expectations in clinical depression: biased or realistic? <em>Journal of Abnormal Psychology</em>, <em>128</em>(7), 678–688.
</div>
</div>
</section></main><!-- /main --><script>
document.body.classList.add('classic-book');
document.addEventListener('DOMContentLoaded', function() {
  const paragraphs = document.querySelectorAll('p');
  paragraphs.forEach(p => {
    if (p.textContent.length > 200) {
      p.style.hyphens = 'auto';
      p.style.hyphenateCharacter = '-';
    }
  });
  const headings = document.querySelectorAll('h1, h2, h3, h4, h5, h6');
  headings.forEach(h => {
    h.style.fontFeatureSettings = '"liga" 1, "dlig" 1, "smcp" 1';
  });
});
</script><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiato!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiato!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/psicometria-r\/intro\.html");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/bayesian_inference/06_conjugate_families.html" class="pagination-link" aria-label="Distribuzioni coniugate">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Distribuzioni coniugate</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/bayesian_inference/08_balance_prior_post.html" class="pagination-link" aria-label="L'influenza della distribuzione a priori">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">L’influenza della distribuzione a priori</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Psicometria</strong> è una risorsa didattica creata per il corso di Scienze e Tecniche Psicologiche dell’Università degli Studi di Firenze.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ccaudek/psicometria-r/blob/main/chapters/bayesian_inference/07_summary_posterior.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/psicometria-r/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>