{
  "hash": "b8244c75443f6c3ffbd1778b7cfcb167",
  "result": {
    "engine": "knitr",
    "markdown": "# Distribuzione predittiva a posteriori {#sec-bayesian-inference-post-pred-distr}\n\n::: {.callout-note appearance=\"minimal\"}\n\nQuesto materiale approfondisce il capitolo 14 del manuale e prosegue il percorso iniziato con la distribuzione predittiva a priori.\n\nPrima di osservare i dati, il prior viene trasformato in una distribuzione sui dati possibili. Dopo avere osservato i dati, lo stesso procedimento viene ripetuto usando la distribuzione a posteriori. La distribuzione predittiva a posteriori descrive quindi ciò che il modello prevede per nuove osservazioni, tenendo conto sia della variabilità del processo generativo sia dell'incertezza residua sui parametri.\n\nLa stessa distribuzione è inoltre alla base dei controlli predittivi a posteriori (*posterior predictive checks*): generiamo dati replicati dal modello aggiornato e verifichiamo se riproducono le caratteristiche dei dati osservati [@gelman2020bayesianworkflow; @gabry2019visualization].\n:::\n\n::: {.callout-important appearance=\"minimal\" .chapter-status}\n**Da sapere.** La distribuzione predittiva a posteriori è una media delle distribuzioni dei dati condizionate ai diversi valori del parametro. A differenza della predittiva a priori, i pesi della media sono forniti dalla distribuzione a posteriori $p(\\theta\\mid y)$.\n\n**Da saper fare.** Interpretare la formula della distribuzione predittiva a posteriori; passare dalla versione discreta alla versione continua; distinguere la posterior sui parametri dalla predittiva sui dati; riconoscere le due fonti di incertezza predittiva; interpretare un controllo predittivo a posteriori.\n\n**Approfondimento facoltativo.** La formula Beta-Binomiale, il confronto con la previsione *plug-in*, la verifica mediante simulazione e l'uso di `pp_check()` approfondiscono il calcolo. Nel percorso essenziale è sufficiente comprendere il significato della media ponderata e saper interpretare gli esempi forniti.\n\n[Che cosa significano queste etichette?](../../guida-al-manuale.qmd#sec-percorsi-lettura)\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Prerequisiti\"}\n\n- Sono dati per noti la distribuzione a posteriori del @sec-bayesian-inference-summary-posterior e i controlli predittivi a priori del @sec-prior-predictive-check.\n- È utile comprendere che le previsioni posteriori incorporano sia l’incertezza sui parametri sia la variabilità delle nuove osservazioni.\n- Per l’implementazione si può consultare l'@sec-apx-posterior-predictive; la lettura del codice R e Stan è facoltativa.\n\n:::\n\n::: {.callout-caution collapse=\"true\" title=\"Preparazione del notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |>\n  source()\nconflicts_prefer(base::match)\n```\n:::\n\n:::\n\n## Dalla posterior ai dati futuri\n\nL'aggiornamento bayesiano termina con una distribuzione a posteriori $p(\\theta\\mid y)$, ma spesso la domanda scientifica non riguarda direttamente il parametro. Ci interessa sapere quali osservazioni potremmo incontrare in futuro, oppure quali dati il modello aggiornato sarebbe in grado di riprodurre.\n\nIl passaggio dalla posterior alle previsioni poggia su un'idea semplice: non scegliamo un solo valore di $\\theta$. Consideriamo tutti i valori ancora plausibili dopo i dati e, per ciascuno, ciò che il modello potrebbe generare. La distribuzione predittiva a posteriori combina queste possibilità in un'unica distribuzione sui dati osservabili:\n\n$$\np(\\tilde y\\mid y)\n=\n\\int p(\\tilde y\\mid\\theta)\\,p(\\theta\\mid y)\\,d\\theta,\n$$ {#eq-posterior-predictive-distribution}\n\ndove:\n\n- $\\tilde y$ indica un dato futuro, o un intero insieme di dati futuri;\n- $p(\\theta\\mid y)$ esprime la plausibilità a posteriori dei valori del parametro;\n- $p(\\tilde y\\mid\\theta)$ descrive quali dati verrebbero generati se il parametro avesse il valore $\\theta$;\n- l'integrale combina tutte queste distribuzioni dei dati usando la posterior come sistema di pesi.\n\n::: {.callout-tip title=\"Come leggere la formula\"}\n\nLa formula dice:\n\n1. considera un possibile valore di $\\theta$;\n2. determina quali dati futuri produrrebbe quel valore;\n3. pesa quella previsione in base alla plausibilità a posteriori di $\\theta$;\n4. ripeti per tutti i valori di $\\theta$;\n5. somma i contributi.\n\nL'integrale non seleziona la stima puntuale migliore. **Fa una media di tutte le distribuzioni predittive compatibili con la posterior.**\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Verosimiglianza e distribuzione generativa: stessa formula, letture diverse\"}\n\nNel contesto predittivo, $p(\\tilde y\\mid\\theta)$ è la distribuzione generativa dei dati futuri condizionata al parametro.\n\n- Nella verosimiglianza, i dati osservati sono fissi e la funzione viene esaminata al variare di $\\theta$.\n- Nella predizione, $\\theta$ è fissato e la distribuzione viene esaminata al variare di $\\tilde y$.\n\nLa forma matematica è la stessa, ma cambia la domanda che le rivolgiamo.\n:::\n\n### La media ponderata, prima in forma discreta\n\nQuando il parametro può assumere pochi valori, l'integrale diventa una somma:\n\n$$\np(\\tilde y\\mid y)\n=\n\\sum_j p(\\tilde y\\mid\\theta_j)\\,p(\\theta_j\\mid y).\n$$ {#eq-posterior-predictive-discrete}\n\nSupponiamo che, dopo avere osservato i dati, il parametro possa assumere soltanto i valori $0.2$, $0.5$ e $0.8$, con le seguenti probabilità a posteriori:\n\n| $\\theta_j$ | $p(\\theta_j\\mid y)$ |\n|---:|---:|\n| 0.2 | 0.05 |\n| 0.5 | 0.20 |\n| 0.8 | 0.75 |\n\nVogliamo prevedere il numero $\\tilde y$ di successi in due prove future:\n\n$$\n\\tilde y\\mid\\theta_j\\sim\\operatorname{Binomiale}(2,\\theta_j).\n$$\n\nPer ciascun valore di $\\theta_j$ otteniamo una distribuzione diversa sui risultati $\\tilde y=0,1,2$. La tabella seguente mostra anche il contributo pesato di ciascuna distribuzione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_values <- c(0.2, 0.5, 0.8)\nposterior_weights <- c(0.05, 0.20, 0.75)\n\nposterior_mixture_components <- tidyr::expand_grid(\n  theta = theta_values,\n  y_tilde = 0:2\n) |>\n  mutate(\n    posterior_weight = posterior_weights[match(theta, theta_values)],\n    p_y_given_theta = dbinom(y_tilde, size = 2, prob = theta),\n    weighted_contribution = posterior_weight * p_y_given_theta\n  )\n\nposterior_mixture_components |>\n  mutate(\n    across(\n      c(posterior_weight, p_y_given_theta, weighted_contribution),\n      ~ round(.x, 3)\n    )\n  ) |>\n  knitr::kable(\n    col.names = c(\n      \"$\\\\theta_j$\",\n      \"$\\\\tilde y$\",\n      \"$p(\\\\theta_j\\\\mid y)$\",\n      \"$p(\\\\tilde y\\\\mid\\\\theta_j)$\",\n      \"Contributo pesato\"\n    ),\n    align = c(\"c\", \"c\", \"c\", \"c\", \"c\"),\n    caption = \"Componenti della distribuzione predittiva a posteriori\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Componenti della distribuzione predittiva a posteriori\n\n| $\\theta_j$ | $\\tilde y$ | $p(\\theta_j\\mid y)$ | $p(\\tilde y\\mid\\theta_j)$ | Contributo pesato |\n|:----------:|:----------:|:-------------------:|:-------------------------:|:-----------------:|\n|    0.2     |     0      |        0.05         |           0.64            |       0.032       |\n|    0.2     |     1      |        0.05         |           0.32            |       0.016       |\n|    0.2     |     2      |        0.05         |           0.04            |       0.002       |\n|    0.5     |     0      |        0.20         |           0.25            |       0.050       |\n|    0.5     |     1      |        0.20         |           0.50            |       0.100       |\n|    0.5     |     2      |        0.20         |           0.25            |       0.050       |\n|    0.8     |     0      |        0.75         |           0.04            |       0.030       |\n|    0.8     |     1      |        0.75         |           0.32            |       0.240       |\n|    0.8     |     2      |        0.75         |           0.64            |       0.480       |\n\n\n:::\n:::\n\n\nSommiamo i contributi relativi allo stesso risultato futuro.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nposterior_predictive_discrete <- posterior_mixture_components |>\n  group_by(y_tilde) |>\n  summarise(\n    posterior_predictive_probability = sum(weighted_contribution),\n    .groups = \"drop\"\n  )\n\nposterior_predictive_discrete |>\n  mutate(\n    posterior_predictive_probability = round(\n      posterior_predictive_probability,\n      3\n    )\n  ) |>\n  knitr::kable(\n    col.names = c(\n      \"$\\\\tilde y$\",\n      \"$p(\\\\tilde y\\\\mid y)$\"\n    ),\n    align = c(\"c\", \"c\"),\n    caption = \"Distribuzione predittiva a posteriori\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Distribuzione predittiva a posteriori\n\n| $\\tilde y$ | $p(\\tilde y\\mid y)$ |\n|:----------:|:-------------------:|\n|     0      |        0.112        |\n|     1      |        0.356        |\n|     2      |        0.532        |\n\n\n:::\n:::\n\n\nI calcoli sono:\n\n$$\n\\begin{aligned}\np(\\tilde y=0\\mid y)\n&=0.05(0.64)+0.20(0.25)+0.75(0.04)=0.112,\\\\\np(\\tilde y=1\\mid y)\n&=0.05(0.32)+0.20(0.50)+0.75(0.32)=0.356,\\\\\np(\\tilde y=2\\mid y)\n&=0.05(0.04)+0.20(0.25)+0.75(0.64)=0.532.\n\\end{aligned}\n$$\n\n::: {.callout-important title=\"Il punto essenziale\"}\n\nPer calcolare $p(\\tilde y=2\\mid y)$ non scegliamo tra $\\theta=0.2$, $0.5$ e $0.8$. Calcoliamo la probabilità di due successi sotto **ciascuno** dei tre scenari e poi facciamo una media usando i pesi della posterior.\n\nIl valore $\\theta=0.8$ contribuisce maggiormente perché:\n\n- rende due successi abbastanza probabili;\n- riceve anche il peso a posteriori più elevato.\n:::\n\nLa stessa operazione è visibile nella @fig-post-pred-discrete-mixture: i primi tre pannelli descrivono ciò che accadrebbe sotto ciascun valore possibile di $\\theta$, l'ultimo è la loro media ponderata con le probabilità a posteriori.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nposterior_predictive_plot_data <- bind_rows(\n  posterior_mixture_components |>\n    transmute(\n      y_tilde,\n      probability = p_y_given_theta,\n      distribution = paste0(\"Se theta = \", theta)\n    ),\n  posterior_predictive_discrete |>\n    transmute(\n      y_tilde,\n      probability = posterior_predictive_probability,\n      distribution = \"Media ponderata: predittiva\"\n    )\n)\n\nposterior_predictive_plot_data |>\n  ggplot(aes(x = factor(y_tilde), y = probability)) +\n  geom_col(fill = PRIMARY, alpha = 0.85) +\n  facet_wrap(~distribution, nrow = 1) +\n  labs(\n    x = \"Numero futuro di successi\",\n    y = \"Probabilità\",\n    title = \"La predittiva a posteriori è una media di distribuzioni\",\n    subtitle = \"I pesi sono le probabilità a posteriori dei valori di theta\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzioni binomiali condizionate ai tre valori possibili di theta e loro media ponderata. I pesi della combinazione sono le probabilità a posteriori associate a ciascun valore del parametro.](06_post_pred_distr_files/figure-html/fig-post-pred-discrete-mixture-1.png){#fig-post-pred-discrete-mixture fig-align='center' fig-alt='Quattro grafici a barre affiancati. I primi tre mostrano la distribuzione del numero di successi in due prove per theta uguale a 0.2, 0.5 e 0.8; il quarto mostra la distribuzione predittiva ottenuta come media ponderata.' width=85%}\n:::\n:::\n\n\nLa distribuzione finale non coincide necessariamente con nessuna delle distribuzioni condizionate. È una nuova distribuzione ottenuta combinandole.\n\nQuando $\\theta$ è continuo, non possiamo più elencare uno per uno tutti i valori possibili. La logica, tuttavia, non cambia: la somma dell'esempio discreto diventa un integrale.\n\n$$\n\\underbrace{\n\\sum_j p(\\tilde y\\mid\\theta_j)p(\\theta_j\\mid y)\n}_{\\text{parametro discreto}}\n\\quad\\longrightarrow\\quad\n\\underbrace{\n\\int p(\\tilde y\\mid\\theta)p(\\theta\\mid y)d\\theta\n}_{\\text{parametro continuo}}.\n$$\n\nL'integrale è la versione continua della media ponderata vista nell'esempio discreto.\n\n::: {.callout-warning title=\"Quattro interpretazioni da non confondere\"}\n\nLa formula **non**:\n\n- aggiorna nuovamente la posterior;\n- sostituisce $\\theta$ con la media o con la moda della posterior;\n- seleziona il valore di $\\theta$ più plausibile;\n- descrive la distribuzione del parametro.\n\nDescrive una distribuzione sui **dati futuri**, ottenuta mediando le distribuzioni $p(\\tilde y\\mid\\theta)$ con i pesi $p(\\theta\\mid y)$.\n:::\n\n## Da dove nasce l'incertezza predittiva\n\nLa distribuzione predittiva a posteriori combina due fonti di incertezza che è utile tenere distinte.\n\nLa prima è l'**incertezza residua sul parametro**: la posterior non concentra generalmente tutta la probabilità su un unico valore di $\\theta$, e valori diversi possono implicare previsioni differenti.\n\nLa seconda è la **variabilità dei dati dato il parametro**: anche se conoscessimo esattamente $\\theta$, le osservazioni future non sarebbero deterministiche. Con $\\theta=0.7$, per esempio, non otteniamo sempre sette successi su dieci; la distribuzione binomiale descrive la variabilità intrinseca del processo.\n\n::: {.callout-tip title=\"Perché non basta usare la media della posterior?\"}\n\nLa previsione *plug-in*\n\n$$\np\\!\\left(\\tilde y\\mid E(\\theta\\mid y)\\right)\n$$\n\ntratta la media posterior come se fosse il valore noto del parametro. La predittiva completa, invece, integra anche l'incertezza residua su $\\theta$:\n\n$$\np(\\tilde y\\mid y)\n=\n\\int p(\\tilde y\\mid\\theta)p(\\theta\\mid y)d\\theta.\n$$\n\nLe due distribuzioni possono avere la stessa media, ma la predittiva completa è generalmente più dispersa.\n:::\n\n## Un esempio completo: il modello Beta-Binomiale\n\nSupponiamo di avere osservato 70 successi su 100 prove e di avere specificato il prior\n\n$$\n\\theta\\sim\\operatorname{Beta}(2,2).\n$$\n\nLa distribuzione a posteriori è\n\n$$\n\\theta\\mid y\n\\sim\n\\operatorname{Beta}(2+70,2+30)\n=\n\\operatorname{Beta}(72,32).\n$$\n\nVogliamo prevedere il numero di successi $\\tilde y$ in dieci nuove prove:\n\n$$\n\\tilde y\\mid\\theta\\sim\\operatorname{Binomiale}(10,\\theta).\n$$\n\nLa posterior Beta(72,32) contiene l'incertezza residua su $\\theta$; il modello binomiale descrive invece la variabilità delle dieci nuove prove. Combinandoli otteniamo una distribuzione sul numero futuro di successi.\n\n::: {.callout-note collapse=\"true\" title=\"Approfondimento: la forma Beta-Binomiale e il calcolo esatto\"}\n\nIntegrando $\\theta$ rispetto alla posterior otteniamo\n\n$$\np(\\tilde y=k\\mid y)\n=\n\\binom{10}{k}\n\\frac{B(k+72,10-k+32)}{B(72,32)},\n\\qquad k=0,\\ldots,10.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndbeta_binomial <- function(y, size, alpha, beta) {\n  exp(\n    lchoose(size, y) +\n      lbeta(y + alpha, size - y + beta) -\n      lbeta(alpha, beta)\n  )\n}\n\nalpha_post <- 72\nbeta_post <- 32\nn_new <- 10\n\nposterior_predictive_exact <- tibble(\n  y_tilde = 0:n_new,\n  probability = dbeta_binomial(\n    y = 0:n_new,\n    size = n_new,\n    alpha = alpha_post,\n    beta = beta_post\n  )\n)\n\nposterior_predictive_exact |>\n  ggplot(aes(x = y_tilde, y = probability)) +\n  geom_col(fill = PRIMARY, alpha = 0.85) +\n  scale_x_continuous(breaks = 0:n_new) +\n  labs(\n    x = \"Numero futuro di successi\",\n    y = \"Probabilità\",\n    title = \"Distribuzione predittiva a posteriori\",\n    subtitle = \"theta | y ~ Beta(72, 32); y-tilde | theta ~ Binomiale(10, theta)\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzione predittiva a posteriori Beta-Binomiale per il numero di successi in dieci nuove prove, ottenuta integrando la probabilità binomiale rispetto alla posterior Beta(72, 32).](06_post_pred_distr_files/figure-html/fig-post-pred-beta-binomial-1.png){#fig-post-pred-beta-binomial fig-align='center' fig-alt='Grafico a barre delle probabilità predittive per un numero di successi da zero a dieci. La massa è concentrata soprattutto tra cinque e nove successi, con il massimo intorno a sette.' width=85%}\n:::\n:::\n\n\nLa media predittiva è\n\n$$\nE(\\tilde y\\mid y)\n=\n10\\,E(\\theta\\mid y)\n=\n10\\frac{72}{104}\n\\approx 6.92.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nposterior_predictive_summary <- posterior_predictive_exact |>\n  summarise(\n    media = sum(y_tilde * probability),\n    deviazione_standard = sqrt(\n      sum((y_tilde - sum(y_tilde * probability))^2 * probability)\n    ),\n    prob_5_8 = sum(probability[y_tilde >= 5 & y_tilde <= 8]),\n    prob_9_10 = sum(probability[y_tilde >= 9])\n  )\n\nposterior_predictive_summary |>\n  mutate(across(everything(), ~ round(.x, 3))) |>\n  knitr::kable(\n    col.names = c(\n      \"Media\",\n      \"Deviazione standard\",\n      \"$P(5 \\\\leq \\\\tilde y \\\\leq 8)$\",\n      \"$P(\\\\tilde y \\\\geq 9)$\"\n    ),\n    align = c(\"c\", \"c\", \"c\", \"c\"),\n    caption = \"Sintesi della distribuzione predittiva a posteriori\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Sintesi della distribuzione predittiva a posteriori\n\n| Media | Deviazione standard | $P(5 \\leq \\tilde y \\leq 8)$ | $P(\\tilde y \\geq 9)$ |\n|:-----:|:-------------------:|:---------------------------:|:--------------------:|\n| 6.92  |        1.52         |            0.789            |         0.15         |\n\n\n:::\n:::\n\n\nQueste quantità descrivono **risultati futuri**, non valori plausibili del parametro. La posterior Beta(72,32) è una distribuzione su $\\theta$; la Beta-Binomiale è una distribuzione sul numero di successi $\\tilde y$.\n:::\n\nIl calcolo esatto rende trasparente la struttura della distribuzione. Nelle applicazioni, però, la stessa operazione si esegue quasi sempre per simulazione.\n\n::: {.callout-note collapse=\"true\" title=\"Approfondimento: calcolo esatto e simulazione\"}\n\nLa distribuzione predittiva può essere approssimata con due istruzioni ripetute:\n\n1. estrarre un valore $\\theta^{(s)}$ dalla posterior;\n2. generare un dato futuro $\\tilde y^{(s)}$ condizionato a quel valore.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn_sim <- 20000\n\ntheta_draws <- rbeta(n_sim, alpha_post, beta_post)\ny_tilde_draws <- rbinom(n_sim, size = n_new, prob = theta_draws)\n\nposterior_predictive_simulated <- tibble(\n  y_tilde = 0:n_new,\n  simulated_probability = tabulate(\n    y_tilde_draws + 1,\n    nbins = n_new + 1\n  ) / n_sim\n)\n\nleft_join(\n  posterior_predictive_exact,\n  posterior_predictive_simulated,\n  by = \"y_tilde\"\n) |>\n  tidyr::pivot_longer(\n    cols = c(probability, simulated_probability),\n    names_to = \"method\",\n    values_to = \"probability_value\"\n  ) |>\n  mutate(\n    method = recode(\n      method,\n      probability = \"Calcolo esatto\",\n      simulated_probability = \"Simulazione\"\n    )\n  ) |>\n  ggplot(aes(x = y_tilde, y = probability_value, fill = method)) +\n  geom_col(position = \"dodge\", alpha = 0.85) +\n  scale_fill_qualitative() +\n  scale_x_continuous(breaks = 0:n_new) +\n  labs(\n    x = \"Numero futuro di successi\",\n    y = \"Probabilità\",\n    fill = NULL,\n    title = \"Calcolo esatto e simulazione producono la stessa predittiva\"\n  ) +\n  legenda_in_alto\n```\n\n::: {.cell-output-display}\n![Confronto tra la distribuzione predittiva Beta-Binomiale calcolata esattamente e la sua approssimazione mediante simulazione dalla posterior. La quasi sovrapposizione delle barre mostra che i due procedimenti implementano lo stesso meccanismo predittivo.](06_post_pred_distr_files/figure-html/fig-post-pred-exact-simulation-1.png){#fig-post-pred-exact-simulation fig-align='center' fig-alt='Grafico a barre raggruppate per i possibili successi da zero a dieci. Per ogni valore, le probabilità del calcolo esatto e della simulazione sono quasi identiche.' width=85%}\n:::\n:::\n\n\nLa simulazione non introduce un principio nuovo: è il modo di eseguire la stessa media che l'integrale rappresenta.\n:::\n\nUn secondo confronto mostra che cosa si perde sostituendo la predittiva completa con una previsione costruita su una sola stima del parametro.\n\n::: {.callout-note collapse=\"true\" title=\"Approfondimento: predittiva completa e previsione plug-in\"}\n\nConsideriamo ora una Binomiale con probabilità fissata alla media posterior:\n\n$$\n\\tilde y_{\\text{plug-in}}\n\\sim\n\\operatorname{Binomiale}\n\\left(10,\\frac{72}{104}\\right).\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nposterior_mean <- alpha_post / (alpha_post + beta_post)\n\npredictive_comparison <- bind_rows(\n  posterior_predictive_exact |>\n    transmute(\n      y_tilde,\n      probability,\n      distribution = \"Predittiva completa\"\n    ),\n  tibble(\n    y_tilde = 0:n_new,\n    probability = dbinom(\n      0:n_new,\n      size = n_new,\n      prob = posterior_mean\n    ),\n    distribution = \"Plug-in: theta = media posterior\"\n  )\n)\n\npredictive_comparison |>\n  ggplot(aes(x = y_tilde, y = probability, fill = distribution)) +\n  geom_col(position = \"dodge\", alpha = 0.85) +\n  scale_fill_qualitative() +\n  scale_x_continuous(breaks = 0:n_new) +\n  labs(\n    x = \"Numero futuro di successi\",\n    y = \"Probabilità\",\n    fill = NULL,\n    title = \"La previsione plug-in ignora l'incertezza residua sul parametro\"\n  ) +\n  legenda_in_alto\n```\n\n::: {.cell-output-display}\n![Confronto tra la distribuzione predittiva completa e la previsione plug-in ottenuta fissando theta alla media a posteriori. Le distribuzioni hanno la stessa media, ma la predittiva completa conserva una dispersione leggermente maggiore perché integra l'incertezza residua sul parametro.](06_post_pred_distr_files/figure-html/fig-post-pred-full-vs-plugin-1.png){#fig-post-pred-full-vs-plugin fig-align='center' fig-alt='Grafico a barre raggruppate del numero di successi da zero a dieci. Le barre della predittiva completa e del metodo plug-in hanno centri simili, ma differiscono leggermente nelle code.' width=85%}\n:::\n:::\n\n\nLe due distribuzioni hanno la stessa media, circa 6.92 successi. La predittiva completa ha però una deviazione standard leggermente maggiore, perché include anche l'incertezza su $\\theta$.\n:::\n\n### Come la concentrazione della posterior modifica la previsione\n\nPer isolare l'effetto dell'incertezza sul parametro, confrontiamo due posterior con la stessa media, $0.70$, ma concentrazione diversa:\n\n$$\n\\operatorname{Beta}(70,30)\n\\qquad\\text{e}\\qquad\n\\operatorname{Beta}(7,3).\n$$\n\nLa prima è molto più concentrata; la seconda è più dispersa. Poiché le medie coincidono, entrambe prevedono in media sette successi su dieci. Ciò che cambia è la dispersione della previsione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nposterior_strength_comparison <- bind_rows(\n  tibble(\n    y_tilde = 0:n_new,\n    probability = dbeta_binomial(0:n_new, n_new, 70, 30),\n    posterior = \"Concentrata: Beta(70, 30)\"\n  ),\n  tibble(\n    y_tilde = 0:n_new,\n    probability = dbeta_binomial(0:n_new, n_new, 7, 3),\n    posterior = \"Dispersa: Beta(7, 3)\"\n  )\n)\n\nposterior_strength_comparison |>\n  ggplot(aes(x = y_tilde, y = probability, fill = posterior)) +\n  geom_col(position = \"dodge\", alpha = 0.85) +\n  scale_fill_qualitative() +\n  scale_x_continuous(breaks = 0:n_new) +\n  labs(\n    x = \"Numero futuro di successi\",\n    y = \"Probabilità\",\n    fill = NULL,\n    title = \"Stessa media posterior, diversa incertezza predittiva\",\n    subtitle = \"La posterior più dispersa assegna più probabilità agli esiti estremi\"\n  ) +\n  legenda_in_alto\n```\n\n::: {.cell-output-display}\n![Distribuzioni predittive ottenute da due posterior con la stessa media ma concentrazione diversa. La posterior più dispersa produce una predittiva più larga e assegna maggiore probabilità agli esiti estremi.](06_post_pred_distr_files/figure-html/fig-post-pred-posterior-concentration-1.png){#fig-post-pred-posterior-concentration fig-align='center' fig-alt='Grafico a barre raggruppate che confronta le previsioni derivate da Beta(70, 30) e Beta(7, 3). La seconda distribuzione presenta barre più alte nelle code e più basse vicino al centro.' width=85%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nposterior_strength_summary <- posterior_strength_comparison |>\n  group_by(posterior) |>\n  summarise(\n    media = sum(y_tilde * probability),\n    deviazione_standard = sqrt(\n      sum((y_tilde - sum(y_tilde * probability))^2 * probability)\n    ),\n    prob_0_4 = sum(probability[y_tilde <= 4]),\n    prob_9_10 = sum(probability[y_tilde >= 9]),\n    .groups = \"drop\"\n  )\n\nposterior_strength_summary |>\n  mutate(across(where(is.numeric), ~ round(.x, 3))) |>\n  knitr::kable(\n    col.names = c(\n      \"Posterior\",\n      \"Media\",\n      \"Deviazione standard\",\n      \"$P(\\\\tilde y \\\\leq 4)$\",\n      \"$P(\\\\tilde y \\\\geq 9)$\"\n    ),\n    align = c(\"l\", \"c\", \"c\", \"c\", \"c\"),\n    caption = \"Effetto della concentrazione posterior sulla previsione\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Effetto della concentrazione posterior sulla previsione\n\n|Posterior                 | Media | Deviazione standard | $P(\\tilde y \\leq 4)$ | $P(\\tilde y \\geq 9)$ |\n|:-------------------------|:-----:|:-------------------:|:--------------------:|:--------------------:|\n|Concentrata: Beta(70, 30) |   7   |        1.51         |        0.056         |        0.162         |\n|Dispersa: Beta(7, 3)      |   7   |        1.95         |        0.115         |        0.249         |\n\n\n:::\n:::\n\n\n::: {.callout-important title=\"Interpretazione\"}\n\nUna posterior più concentrata non elimina la variabilità dei dati: anche conoscendo quasi esattamente $\\theta=0.70$, il numero di successi su dieci resta casuale.\n\nUna posterior più dispersa aggiunge ulteriore incertezza, perché combina distribuzioni binomiali centrate su valori di $\\theta$ più differenti. Per questo assegna maggiore probabilità agli esiti lontani dal centro.\n:::\n\n### Dalla predittiva a priori a quella a posteriori\n\nLe due distribuzioni sono costruite con lo stesso modello generativo. Cambiano soltanto i pesi.\n\n| Caratteristica | Predittiva a priori | Predittiva a posteriori |\n|---|---|---|\n| Formula | $p(\\tilde y)=\\int p(\\tilde y\\mid\\theta)p(\\theta)d\\theta$ | $p(\\tilde y\\mid y)=\\int p(\\tilde y\\mid\\theta)p(\\theta\\mid y)d\\theta$ |\n| Pesi | prior $p(\\theta)$ | posterior $p(\\theta\\mid y)$ |\n| Momento | prima dei dati osservati | dopo i dati osservati |\n| Domanda principale | quali dati rende plausibili la specificazione iniziale? | quali dati sono plausibili dopo l'aggiornamento? |\n\nNon è garantito che la predittiva a posteriori sia sempre molto più stretta della predittiva a priori. Dipende da quanto i dati hanno ridotto l'incertezza e dalla struttura del modello. La differenza essenziale è che la seconda incorpora l'informazione contenuta nei dati osservati.\n\n## Dalla previsione al controllo del modello\n\nLa stessa distribuzione può essere usata in due modi. Nel primo, $\\tilde y$ rappresenta un'osservazione che sarà realmente raccolta in seguito. La predittiva risponde allora alla domanda:\n\n> Quali risultati futuri considera plausibili il modello dopo avere osservato i dati disponibili?\n\nNel secondo uso non anticipiamo un'osservazione reale. Generiamo dati replicati $y^{\\mathrm{rep}}$, cioè dataset simulati come se l'esperimento venisse ripetuto sotto il modello aggiornato:\n\n$$\np(y^{\\mathrm{rep}}\\mid y)\n=\n\\int p(y^{\\mathrm{rep}}\\mid\\theta)p(\\theta\\mid y)d\\theta.\n$$\n\nConfrontiamo poi le caratteristiche dei dati osservati con quelle delle repliche:\n\n- centro e dispersione;\n- asimmetria e code;\n- frequenza di valori estremi;\n- relazioni tra variabili;\n- andamenti temporali o differenze fra gruppi.\n\n::: {.callout-note title=\"Che cosa può mostrare un controllo predittivo?\"}\n\nSe il modello genera regolarmente dati con proprietà molto diverse da quelle osservate, abbiamo individuato una specifica inadeguatezza del modello.\n\nSe i dati osservati appaiono compatibili con le repliche, abbiamo soltanto verificato che il modello riesce a riprodurre le caratteristiche esaminate. **Non abbiamo dimostrato che il modello sia vero o unico.**\n:::\n\n### Scegliere che cosa controllare\n\nIn un modello stimato con `brms`, `pp_check()` genera repliche dalla distribuzione predittiva a posteriori e le confronta con i dati osservati.\n\n```r\npp_check(fit, type = \"dens_overlay\", ndraws = 100)\npp_check(fit, type = \"stat\", stat = \"mean\")\npp_check(fit, type = \"stat\", stat = \"sd\")\n```\n\nOgni controllo risponde a una domanda diversa. Un modello può riprodurre bene la media ma non la dispersione, le code o la forma della distribuzione. Per questo la scelta della quantità da controllare deve essere guidata dal fenomeno e dagli obiettivi dell'analisi.\n\n::: {.callout-warning title=\"Limiti dei controlli predittivi a posteriori\"}\n\n- I dati sono usati sia per stimare la posterior sia per effettuare il controllo; i controlli posteriori tendono quindi a essere meno severi di una validazione su dati indipendenti.\n- Un buon risultato dipende dalla caratteristica controllata: nessun grafico singolo può verificare tutti gli aspetti del modello.\n- Il controllo individua una discrepanza, ma non stabilisce automaticamente quale modifica del modello sia appropriata.\n- Un modello può riprodurre i dati osservati e avere comunque scarsa capacità predittiva fuori campione.\n:::\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nLa distribuzione predittiva a posteriori porta l'inferenza dalla scala dei parametri a quella dei dati osservabili. La posterior assegna un peso ai valori ancora plausibili di $\\theta$; ciascuno implica una distribuzione di possibili osservazioni; la predittiva le riunisce in una media ponderata.\n\nLa previsione conserva quindi entrambe le fonti di incertezza: ciò che non sappiamo ancora sul parametro e la variabilità che rimarrebbe anche se il parametro fosse noto. Per questo motivo, una previsione basata su un'unica stima puntuale può risultare troppo sicura.\n\nLa stessa costruzione collega previsione e controllo del modello: serve a descrivere risultati futuri plausibili e a generare repliche da confrontare con i dati osservati. In entrambi i casi, il principio è lo stesso: **non prevediamo da un singolo parametro, ma dall'intera gamma di possibilità rappresentata dalla posterior.**\n\n## Esercizi {.unnumbered .unlisted}\n\n### Esercizio 1 — Comprendere {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 10 minuti*\n\nDopo avere osservato alcuni dati, un parametro può assumere soltanto due valori:\n\n| $\\theta_j$ | $p(\\theta_j\\mid y)$ |\n|---:|---:|\n| 0.25 | 0.30 |\n| 0.75 | 0.70 |\n\nVogliamo prevedere l'esito $\\tilde y$ di una singola prova, dove\n\n$$\n\\tilde y\\mid\\theta_j\\sim\\operatorname{Bernoulli}(\\theta_j).\n$$\n\n1. Calcola $p(\\tilde y=1\\mid y)$.\n2. Indica quale dei due valori di $\\theta$ contribuisce maggiormente alla probabilità finale e spiega perché.\n3. Spiega perché il risultato non si ottiene scegliendo semplicemente $\\theta=0.75$.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\n\nPer ciascun valore di $\\theta$, moltiplica la probabilità di successo condizionata a quel valore per il suo peso a posteriori. Poi somma i contributi.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\n\nLa probabilità predittiva è\n\n$$\n\\begin{aligned}\np(\\tilde y=1\\mid y)\n&=p(\\tilde y=1\\mid\\theta=0.25)p(\\theta=0.25\\mid y)\\\\\n&\\quad+p(\\tilde y=1\\mid\\theta=0.75)p(\\theta=0.75\\mid y)\\\\\n&=0.25(0.30)+0.75(0.70)\\\\\n&=0.075+0.525=0.60.\n\\end{aligned}\n$$\n\nIl secondo valore contribuisce maggiormente perché assegna una probabilità più alta al successo e possiede anche un peso posterior maggiore.\n\nScegliere soltanto $\\theta=0.75$ produrrebbe una probabilità pari a 0.75 e ignorerebbe il 30% di plausibilità ancora assegnato a $\\theta=0.25$. La predittiva rappresenta tutta l'incertezza residua, non soltanto lo scenario più plausibile.\n:::\n\n### Esercizio 2 — Prevedere {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 5–10 minuti*\n\nQuale interpretazione descrive correttamente la formula\n\n$$\np(\\tilde y\\mid y)\n=\n\\int p(\\tilde y\\mid\\theta)p(\\theta\\mid y)d\\theta?\n$$\n\nA. Si sceglie il valore di $\\theta$ con densità posterior più alta e si genera $\\tilde y$ da quel valore.\n\nB. Si aggiorna la posterior una seconda volta usando i dati futuri $\\tilde y$.\n\nC. Si mediano le distribuzioni dei dati futuri condizionate ai diversi valori di $\\theta$, usando come pesi le plausibilità a posteriori.\n\nD. Si calcola la distribuzione dei valori che il parametro $\\theta$ assumerà in futuro.\n\nSpiega inoltre che cosa cambierebbe nella formula della distribuzione predittiva a priori.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\n\nChiediti quale quantità costituisce il sistema di pesi nell'integrale.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\n\nLa risposta corretta è **C**. L'integrale combina tutte le distribuzioni $p(\\tilde y\\mid\\theta)$ usando $p(\\theta\\mid y)$ come peso.\n\nNella predittiva a priori il meccanismo è identico, ma i pesi sono forniti dal prior:\n\n$$\np(\\tilde y)\n=\n\\int p(\\tilde y\\mid\\theta)p(\\theta)d\\theta.\n$$\n\nLa differenza non riguarda il modello dei dati, ma l'informazione usata per pesare i possibili valori del parametro.\n:::\n\n### Esercizio 3 — Modificare {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 10 minuti*\n\nConsidera due distribuzioni posteriori con la stessa media:\n\n$$\n\\theta\\mid y_A\\sim\\operatorname{Beta}(70,30),\n\\qquad\n\\theta\\mid y_B\\sim\\operatorname{Beta}(7,3).\n$$\n\nIn entrambi i casi dobbiamo prevedere il numero di successi in dieci prove future.\n\n1. Quale predittiva avrà la media più alta?\n2. Quale assegnerà più probabilità a risultati estremi, come 3 o 10 successi?\n3. Quale fonte di incertezza rimane presente anche nel primo caso, nonostante la posterior sia molto concentrata?\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\n\nLe due posterior hanno la stessa media, ma concentrazioni rispettivamente pari a 100 e 10.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\n\nLe due distribuzioni predittive hanno la stessa media:\n\n$$\n10\\times 0.70=7.\n$$\n\nLa predittiva derivata da Beta(7,3) è più dispersa e assegna maggiore probabilità agli esiti estremi, perché la posterior lascia plausibili valori di $\\theta$ più lontani da 0.70.\n\nAnche con Beta(70,30) rimane la variabilità binomiale: conoscere quasi esattamente $\\theta$ non determina il numero di successi che si osserverà in dieci prove.\n:::\n\n### Esercizio 4 — Criticare {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 10 minuti*\n\nValuta la seguente affermazione:\n\n> «Per fare una previsione bayesiana basta inserire la media posterior nel modello. Se i dati osservati cadono al centro della distribuzione predittiva così ottenuta, il modello è validato.»\n\nIndividua almeno due problemi e riscrivi l'affermazione in forma corretta.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\n\nConsidera separatamente l'incertezza sul parametro e il significato di un controllo predittivo.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\n\nL'affermazione presenta almeno due problemi.\n\nPrimo, inserire soltanto la media posterior produce una previsione *plug-in* che ignora l'incertezza residua sul parametro. La distribuzione predittiva completa media le previsioni associate a tutti i valori plausibili di $\\theta$.\n\nSecondo, la compatibilità dei dati con una distribuzione predittiva non valida il modello come vero. Mostra soltanto che il modello riesce a riprodurre la particolare caratteristica controllata. Altri aspetti dei dati, oppure dati indipendenti, possono rivelare inadeguatezze.\n\nUna formulazione corretta è:\n\n> «La previsione bayesiana completa integra la distribuzione dei dati condizionata al parametro rispetto alla posterior. I controlli predittivi confrontano caratteristiche dei dati osservati con quelle di dati replicati e possono individuare specifiche carenze del modello, senza dimostrarne la verità.»\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Informazioni sull'ambiente di sviluppo\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.6.1\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.1            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.1           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8         tidyselect_1.2.1     farver_2.1.2        \n#>  [4] S7_0.2.2             fastmap_1.2.0        tensorA_0.36.2.1    \n#>  [7] digest_0.6.39        timechange_0.4.0     estimability_2.0.0  \n#> [10] lifecycle_1.0.5      magrittr_2.0.5       compiler_4.6.1      \n#> [13] rlang_1.3.0          tools_4.6.1          yaml_2.3.12         \n#> [16] knitr_1.51           labeling_0.4.3       bridgesampling_1.2-1\n#> [19] htmlwidgets_1.6.4    pkgbuild_1.4.8       curl_7.1.0          \n#> [22] RColorBrewer_1.1-3   abind_1.4-8          purrr_1.2.2         \n#> [25] grid_4.6.1           stats4_4.6.1         xtable_1.8-8        \n#> [28] inline_0.3.21        emmeans_2.0.4        scales_1.4.0        \n#> [31] cli_3.6.6            mvtnorm_1.4-2        rmarkdown_2.31      \n#> [34] generics_0.1.4       otel_0.2.0           RcppParallel_6.2.0  \n#> [37] cachem_1.1.0         stringr_1.6.0        parallel_4.6.1      \n#> [40] vctrs_0.7.3          V8_8.2.0             Matrix_1.7-6        \n#> [43] jsonlite_2.0.0       arrayhelpers_1.1-2   glue_1.8.1          \n#> [46] codetools_0.2-20     distributional_0.8.1 lubridate_1.9.5     \n#> [49] stringi_1.8.9        gtable_0.3.6         QuickJSR_1.10.0     \n#> [52] pillar_1.11.1        htmltools_0.5.9      Brobdingnag_1.2-9   \n#> [55] R6_2.6.1             textshaping_1.0.5    rprojroot_2.1.1     \n#> [58] evaluate_1.0.5       lattice_0.22-9       backports_1.5.1     \n#> [61] memoise_2.0.1        broom_1.0.13         snakecase_0.11.1    \n#> [64] rstantools_2.7.0     coda_0.19-4.1        gridExtra_2.3.1     \n#> [67] nlme_3.1-170         checkmate_2.3.4      xfun_0.60           \n#> [70] pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "06_post_pred_distr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}