{
  "hash": "31002759cb83e88f408687045ad90199",
  "result": {
    "engine": "knitr",
    "markdown": "# I gradi di libertà del ricercatore {#sec-replication-degrees-of-freedom}\n\n::: {.callout-note appearance=\"minimal\"}\n\nL'oggettività e la riproducibilità sono pilastri fondamentali della conoscenza scientifica: analisi corrette condotte sugli stessi dati da ricercatori indipendenti dovrebbero condurre a conclusioni simili. Questo principio è alla base di un progresso cumulativo, in cui le evidenze si consolidano nel tempo, indipendentemente dal singolo ricercatore o dall’analisi specifica.\n\nNella pratica scientifica, tuttavia, il percorso che porta dai dati alle conclusioni è raramente lineare. In particolare nelle scienze psicologiche e sociali, la progettazione di uno studio, la gestione dei dati e l'analisi statistica richiedono una serie di decisioni metodologicamente legittime, ma potenzialmente arbitrarie: la definizione della variabile di interesse, l'esclusione di alcuni casi, l'applicazione di determinate trasformazioni, l'inclusione di covariate e la scelta del modello statistico.\n\nQuesto insieme di possibilità è stato concettualizzato come \"gradi di libertà del ricercatore\" (*researcher degrees of freedom*). Tale flessibilità non è di per sé problematica, anzi, è spesso necessaria per adattare l'analisi a dati complessi e a domande di ricerca articolate. Tuttavia, il rischio sorge quando queste scelte vengono applicate in modo opportunistico per ottenere un risultato statisticamente significativo. In tali casi, la stessa flessibilità che permette di cogliere la complessità dei fenomeni può distorcere le stime degli effetti, aumentare il tasso di falsi positivi e minare l'integrità delle conclusioni [@gelman2013garden; @wicherts2016degrees; @simmons2011false]. \n\nUn esempio particolarmente eloquente è fornito da @gould2025same:  174 team di ricerca, analizzando gli **stessi dati** per rispondere alla **stessa domanda**, hanno prodotto conclusioni diametralmente opposte, con stime degli effetti che variavano da fortemente negative a positive. Questa eterogeneità non era attribuibile a errori o incompetenza, ma alle **scelte analitiche legittime**, ovvero i \"gradi di libertà\", adottate da ciascun gruppo. In altre parole, percorsi diversi all’interno dello stesso spazio di opzioni metodologiche hanno condotto a esiti divergenti.\n\nIl fenomeno dei \"gradi di libertà del ricercatore\" contribuisce in modo sostanziale alla crisi di replicabilità: quando risultati differenti possono emergere semplicemente in base alle scelte compiute durante l’analisi, la solidità inferenziale del singolo studio sperimentale viene meno. Senza un controllo trasparente di tali “gradi di libertà”, si rischia di produrre un’interpretazione del fenomeno più influenzata dalle decisioni dell’analista che dai dati stessi [@gelman2013garden; @simmons2011false].\n\nIn questo capitolo esploreremo, con un approccio computazionale, l'origine di tali divergenze.  Mediante una **simulazione multiverse**, mostreremo come diverse scelte analitiche (dall'esclusione degli outlier alla selezione delle covariate, dalle trasformazioni delle misure alle strategie di modellazione) possano condurre a stime e interpretazioni sensibilmente diverse a partire dallo stesso dataset. Concluderemo discutendo le principali strategie metodologiche per mitigare gli effetti distortivi dei gradi di libertà, come la pre-registrazione, i piani di analisi Open Science e gli approcci multiverse.\n:::\n\n::: {.callout-important appearance=\"minimal\" .chapter-status}\n**Da sapere.** I gradi di libertà del ricercatore sono le molte scelte, spesso legittime, che collegano i dati alle conclusioni. Quando tali scelte non sono dichiarate o vengono selezionate dopo aver osservato i risultati, possono amplificare i falsi positivi, distorcere le stime e ridurre la replicabilità. La preregistrazione e le analisi multiverso rendono questa variabilità più trasparente.\n\n**Da saper fare.** Capire e sapere interpretare una *multiverse analysis*; confrontare i risultati prodotti da diverse strategie di gestione degli outlier, dei dati mancanti, delle covariate e delle trasformazioni; leggere una *specification curve* e distinguere una conclusione robusta da una dipendente dalle scelte analitiche.\n\n**Approfondimento facoltativo.** L’implementazione completa in R delle combinazioni analitiche, i dettagli della simulazione e la letteratura sui progetti *many analysts* possono essere rimandati in una prima lettura.\n\n[Che cosa significano queste etichette?](../../guida-al-manuale.qmd#sec-percorsi-lettura)\n:::\n\n::: callout-important\n## In questo capitolo imparerai a\n\n- Simulare come diverse scelte analitiche producono risultati diversi sugli stessi dati.\n- Costruire una **multiverse analysis** per mappare lo spazio delle conclusioni possibili.\n- Visualizzare una **specification curve** che mostra la distribuzione degli effetti.\n- Comprendere perché la pre-registrazione riduce (ma non elimina) l'arbitrarietà.\n:::\n\n::: callout-tip\n## Prerequisiti\n\n- Leggere il **Capitolo 3** del manuale sulla crisi della replicabilità.\n- Leggere l'articolo di Science: [Even faced with the same data, ecologists sometimes come to opposite conclusions](https://www.science.org/content/article/even-faced-same-data-ecologists-sometimes-come-opposite-conclusions).\n- Opzionale: @silberzahn2018many per il progetto many-analysts originale in psicologia.\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\nlibrary(broom)\nlibrary(patchwork)\nlibrary(stringr)\n```\n:::\n\n:::\n\n## Il problema: uno spazio analitico immenso\n\nCondurre l'analisi dei dati raramente consiste nell’applicazione di un’unica procedura predeterminata. Ogni studio richiede una sequenza di scelte metodologiche, spesso tutte legittime ma raramente univoche. Consideriamo, a titolo esemplificativo, alcune delle decisioni più comuni che ogni ricercatore deve prendere:\n\n* Come trattare gli **outlier**?\n  (escluderli, winsorizzarli, conservarli)\n* Quali **variabili** includere nel modello?\n  (età, genere, SES, tutte, nessuna)\n* Quale **modello** adottare?\n  (regressione lineare, ANOVA, modelli a effetti misti)\n* In che forma usare la **variabile dipendente**?\n  (valori grezzi, trasformazioni, standardizzazione)\n* Quali **criteri di esclusione** applicare?\n  (gestione dei dati mancanti, trial sospetti)\n\nCiascuna di queste scelte rappresenta un bivio metodologico all'interno del \"giardino dei sentieri che si biforcano\" (*garden of forking paths*) del ricercatore [@McElreath_rethinking]. Anche con un numero limitato di opzioni plausibili per ciascuna decisione, lo spazio complessivo delle possibili strategie analitiche cresce in modo esponenziale.\nAd esempio con tre opzioni per 5 decisioni:\n$$\n3^5 = 243 \\text{ percorsi analitici distinti. }\n$$\nCon tre opzioni per 10 decisioni:\n$$\n3^{10} = 59.049 \\text{ analisi potenzialmente diverse. }\n$$\n\n> Attraversando il \"giardino dei sentieri che si biforcano\", il ricercatore potrebbe potenzialmente generare **decine di migliaia di risultati diversi** a partire da un unico insieme di dati, ognuno giustificato da scelte analitiche formalmente valide. Di conseguenza, ogni articolo scientifico pubblicato rappresenta soltanto una traiettoria selezionata all'interno di uno spazio di possibilità metodologiche vastissimo e che il ricercatore esplora solo in minima parte.\n\nQuesto scenario di \"iperflessibilità\" analitica apre la strada alla possibilità di selezionare, intenzionalmente o inconsapevolmente, solo le combinazioni di scelte che conducono a un risultato statisticamente significativo o in linea con le aspettative. Questa asimmetria tra la vastità dello spazio analitico potenziale e la pubblicazione di un solo percorso, presentato come quello \"corretto\", è una delle cause della crisi di replicabilità.\n\n## Simulazione\n\n**Creare un dataset \"ambiguo\".**\n\nPer illustrare come possono emergere i risultati riportati da @gould2025same, eseguiamo una simulazione. Costruiamo un dataset che riproduce le sfide tipiche della ricerca empirica: un effetto reale di piccola entità, unito alla presenza di valori anomali, dati mancanti e covariate correlate.\n\nL'obiettivo non è padroneggiare i dettagli tecnici dello script R utilizzato per la simulazione, ma comprendere come le scelte analitiche di un ricercatore, pur essendo tutte metodologicamente legittime, possano influenzare i risultati e condurre a conclusioni diverse a partire dallo stesso insieme di dati.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\nn <- 200\n\n# Effetto vero: differenza di 3 punti sulla scala dell'outcome\nTRUE_EFFECT <- 2\n\ndataset <- tibble(\n  id = 1:n,\n  # Età: correlata con la condizione (sbilanciamento)\n  age = round(rnorm(n, 35, 12)),\n  gender = sample(c(\"M\", \"F\", \"Other\"), n, replace = TRUE, prob = c(0.48, 0.48, 0.04)),\n  education = sample(c(\"High school\", \"Bachelor\", \"Master\", \"PhD\"), n, \n                     replace = TRUE, prob = c(0.3, 0.4, 0.2, 0.1))\n) |>\n  mutate(\n    condition = rep(c(\"control\", \"treatment\"), each = n/2),\n    \n    # Sbilanciamento età tra gruppi (confounding)\n    age = age + ifelse(condition == \"treatment\", 3, -3),\n    \n    # L'età è un predittore dell'outcome (confounding)\n    age_effect = 0.15 * (age - 35),\n    \n    # Outcome base con effetto del trattamento e dell'età\n    outcome_base = 50 + \n                   ifelse(condition == \"treatment\", TRUE_EFFECT, 0) + \n                   age_effect +\n                   rnorm(n, 0, 18),\n    \n    # Outlier ASIMMETRICI: nel gruppo control tendono verso il basso,\n    # nel gruppo treatment tendono verso l'alto\n    # Questo crea bias nelle stime quando gli outlier vengono trattati diversamente\n    is_outlier = runif(n) < 0.10,\n    outlier_direction = case_when(\n      is_outlier & condition == \"control\" ~ sample(c(-1, 1), n, replace = TRUE, prob = c(0.8, 0.2)),\n      is_outlier & condition == \"treatment\" ~ sample(c(-1, 1), n, replace = TRUE, prob = c(0.2, 0.8)),\n      TRUE ~ 0\n    ),\n    outlier_magnitude = ifelse(is_outlier, abs(rnorm(n, 20, 5)), 0),\n    outcome_raw = outcome_base + outlier_direction * outlier_magnitude,\n    \n    # Missing: 8% casuali ma leggermente più frequenti per valori estremi\n    missing_prob = 0.05 + 0.05 * (abs(outcome_raw - 50) > 15),\n    outcome = ifelse(runif(n) < missing_prob, NA, outcome_raw)\n  )\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Dataset simulato\n#> ----------------\n#> Campioni totali: 200\n#> Missing outcome: 14 (7.0%)\n#> Outlier simulati: 21 (10.5%)\n#> Effetto vero (differenza tra gruppi): 2.0 punti\n#> \n#> Età media - Control: 32.4, Treatment: 36.9\n```\n:::\n\n\n**Un’analisi multiverso.**\n\nEsaminiamo ora in modo sistematico come diverse scelte analitiche, tutte plausibili, possano modificare le conclusioni di uno studio. Ci concentreremo su quattro scelte metodologiche di base.\n\n1.  **Trattamento degli outlier:**\n    conservarli tutti, escludere quelli oltre 3 deviazioni standard, applicare la winsorizzazione.\n2.  **Gestione dei dati mancanti:**\n    esclusione listwise, imputazione con la media.\n3.  **Selezione delle covariate:**\n    nessuna covariate, solo età, età e genere, tutte le covariate disponibili.\n4.  **Trasformazione della variabile dipendente:**\n    valori grezzi, trasformazione logaritmica, standardizzazione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Definisci lo spazio delle scelte analitiche\nanalytical_choices <- list(\n  # 1. Gestione degli outlier\n  outlier_handling = c(\"keep\", \"remove_2.5sd\", \"winsorize\"),\n  \n  # 2. Gestione dei dati mancanti\n  missing_handling = c(\"listwise\", \"mean_imputation\"),\n  \n  # 3. Covariate da includere nel modello\n  covariates = c(\"none\", \"age\", \"age_gender\", \"all\"),\n  \n  # 4. Trasformazione della variabile dipendente\n  transformation = c(\"raw\", \"log\", \"standardized\")\n)\n```\n:::\n\n\nConsiderando le opzioni per ciascuna delle quattro decisioni da prendere, il numero totale di combinazioni analitiche possibili è:\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Numero totale di analisi possibili: 72\n```\n:::\n\n\n**Implementazione delle scelte.**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Funzione per preparare i dati secondo le scelte\nprepare_data <- function(data, outlier_method, missing_method, transform_method) {\n  df <- data\n  \n  # 1. Gestione missing (prima degli outlier per calcoli corretti)\n  if (missing_method == \"listwise\") {\n    df <- df |> filter(!is.na(outcome))\n  } else if (missing_method == \"mean_imputation\") {\n    m <- mean(df$outcome, na.rm = TRUE)\n    df <- df |> mutate(outcome = ifelse(is.na(outcome), m, outcome))\n  }\n  \n  # 2. Gestione outlier\n  if (outlier_method == \"remove_2.5sd\") {\n    m <- mean(df$outcome, na.rm = TRUE)\n    s <- sd(df$outcome, na.rm = TRUE)\n    df <- df |> \n      filter(outcome > m - 2.5 * s & outcome < m + 2.5 * s)\n  } else if (outlier_method == \"winsorize\") {\n    lower <- quantile(df$outcome, 0.05, na.rm = TRUE)\n    upper <- quantile(df$outcome, 0.95, na.rm = TRUE)\n    df <- df |>\n      mutate(outcome = pmax(pmin(outcome, upper), lower))\n  }\n  \n  # 3. Trasformazione\n  if (transform_method == \"log\") {\n    # Shift per evitare log di valori negativi o zero\n    if (all(is.na(df$outcome))) return(df)  # <- AGGIUNTO\n    min_val <- min(df$outcome, na.rm = TRUE)\n    shift <- ifelse(min_val <= 0, abs(min_val) + 1, 0)\n    df <- df |> mutate(outcome = log(outcome + shift))\n  } else if (transform_method == \"standardized\") {\n    if (all(is.na(df$outcome))) return(df)  # <- AGGIUNTO\n    df <- df |> mutate(outcome = as.numeric(scale(outcome)))\n  }\n  \n  return(df)\n}\n\n# Funzione per eseguire l'analisi\nrun_analysis <- function(data, covariate_set) {\n  # Controlla se ci sono abbastanza dati\n  if (nrow(data) < 20) return(NULL)\n  \n  # Verifica che ci siano entrambe le condizioni\n\n  if (length(unique(data$condition)) < 2) return(NULL)\n  \n  formula <- switch(covariate_set,\n    \"none\" = outcome ~ condition,\n    \"age\" = outcome ~ condition + age,\n    \"age_gender\" = outcome ~ condition + age + gender,\n    \"all\" = outcome ~ condition + age + gender + education\n  )\n  \n  tryCatch({\n    model <- lm(formula, data = data)\n    \n    # Estrai coefficiente del treatment\n    tidy_model <- tidy(model, conf.int = TRUE)\n    treatment_row <- tidy_model |> filter(term == \"conditiontreatment\")\n    \n    if (nrow(treatment_row) == 0) return(NULL)\n    \n    tibble(\n      estimate = treatment_row$estimate,\n      std_error = treatment_row$std.error,\n      p_value = treatment_row$p.value,\n      conf_low = treatment_row$conf.low,\n      conf_high = treatment_row$conf.high,\n      n_used = nrow(data),\n      r_squared = summary(model)$r.squared\n    )\n  }, error = function(e) {\n    return(NULL)\n  })\n}\n```\n:::\n\n\n**Esecuzione dell'analisi multiverse.**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Genera tutte le combinazioni\nmultiverse <- expand_grid(\n  outlier = analytical_choices$outlier_handling,\n  missing = analytical_choices$missing_handling,\n  covariates = analytical_choices$covariates,\n  transformation = analytical_choices$transformation\n)\n\n# Esegui ogni analisi\nmultiverse_results <- multiverse |>\n  rowwise() |>\n  mutate(\n    prepared_data = list(prepare_data(dataset, outlier, missing, transformation)),\n    results = list(run_analysis(prepared_data, covariates))\n  ) |>\n  unnest(results) |>\n  ungroup() |>\n  mutate(\n    analysis_id = row_number(),\n    significant = p_value < 0.05,\n    direction = ifelse(estimate > 0, \"positive\", \"negative\")\n  )\n```\n:::\n\n\nPer ciascuna delle 72 analisi possibili consideriamo la variabile dipendente, operazionalizzata in vari modi, in un modello di regressione lineare che inclue o no covariati, dopo il pre-processing dei dati che affronta il problema degli outlier e dei dati mancanti. \n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Analisi completate: 72\n#> Range stime: [0.103, 7.285]\n#> Significative (p < 0.05): 37 (51.4%)\n#> Sovrastima (stima > 2.0): 24 (33.3%)\n#> Sottostima (stima < 2.0): 48 (66.7%)\n```\n:::\n\n\nSi noti che solo circa la metà delle analisi (51.4%) produce risultati statisticamente significativi ($ p$ < 0.05). Inoltre, le stime dell'effetto mostrano una notevole variabilità, oscillando tra un minimo di 0.10 e un massimo di 7.29 punti. Questo intervallo include sia sovrastime (33% dei casi) che sottostime (67% dei casi) rispetto all'effetto vero, evidenziando come le scelte analitiche possano distorcere sistematicamente i risultati.\n\n**Visualizzazione: curva di specificazione.**\n\nLa **curva di specificazione** (*specification curve*) rappresenta graficamente come le stime di un effetto variano in funzione delle diverse specifiche analitiche applicate agli stessi dati. Ogni punto corrisponde a una combinazione unica di scelte metodologiche.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Ordina per stima\nmultiverse_ordered <- multiverse_results |>\n  arrange(estimate) |>\n  mutate(rank = row_number())\n\n# Panel superiore: stime con CI\np_estimates <- ggplot(multiverse_ordered, aes(x = rank, y = estimate)) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"gray50\") +\n  geom_hline(yintercept = TRUE_EFFECT, linetype = \"dotted\", color = \"red\", alpha = 0.5) +\n  geom_linerange(aes(ymin = conf_low, ymax = conf_high, color = significant), \n                 alpha = 0.4, linewidth = 0.3) +\n  geom_point(aes(color = significant), size = 1.5) +\n  scale_color_manual(values = c(\"TRUE\" = \"forestgreen\", \"FALSE\" = \"gray60\")) +\n  annotate(\"text\", x = max(multiverse_ordered$rank) * 0.95, y = 2.5, \n           label = \"Effetto vero\", color = \"red\", hjust = 1, vjust = -0.5, size = 3) +\n  labs(\n    y = \"Stima dell'effetto\",\n    title = \"Specification Curve: 72 modi di analizzare gli stessi dati\"\n  ) +\n  theme(\n    axis.text.x = element_blank(),\n    axis.ticks.x = element_blank(),\n    axis.title.x = element_blank(),\n    legend.position = \"none\"\n  )\n\n# Panel inferiore: scelte analitiche\nchoices_long <- multiverse_ordered |>\n  select(rank, outlier, missing, covariates, transformation) |>\n  pivot_longer(cols = -rank, names_to = \"choice_type\", values_to = \"choice\") |>\n  mutate(\n    choice_type = factor(choice_type, \n                        levels = c(\"outlier\", \"missing\", \"covariates\", \"transformation\"),\n                        labels = c(\"Outlier\", \"Missing\", \"Covariate\", \"Trasformazione\"))\n  )\n\np_choices <- ggplot(choices_long, aes(x = rank, y = choice_type, fill = choice)) +\n  geom_tile(color = \"white\", linewidth = 0.1) +\n  scale_fill_viridis_d(option = \"turbo\") +\n  labs(x = \"Analisi (ordinate per stima)\", y = \"\", fill = \"Scelta\") +\n  theme(\n    legend.position = \"bottom\",\n    legend.key.size = unit(0.4, \"cm\"),\n    axis.text.y = element_text(size = 9)\n  ) +\n  guides(fill = guide_legend(nrow = 2))\n\n# Combina\np_estimates / p_choices + plot_layout(heights = c(2, 1))\n```\n\n::: {.cell-output-display}\n![Curva di specificazione: ogni punto rappresenta una delle 72 analisi possibili. La linea orizzontale indica l'effetto nullo. Il pannello inferiore mostra quali scelte sono state fatte per ogni analisi.](05_degrees_of_freedom_files/figure-html/fig-specification-curve-1.png){#fig-specification-curve fig-align='center' width=85%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(multiverse_results, aes(x = estimate)) +\n  geom_histogram(bins = 20, fill = \"steelblue\", color = \"white\", alpha = 0.8) +\n  geom_vline(xintercept = TRUE_EFFECT, color = \"red\", linetype = \"dashed\", linewidth = 1.2) +\n  geom_vline(xintercept = 0, color = \"black\", linetype = \"dotted\", linewidth = 1) +\n  geom_vline(xintercept = median(multiverse_results$estimate), \n             color = \"darkblue\", linewidth = 1) +\n  annotate(\"text\", x = TRUE_EFFECT, y = Inf, vjust = 2, hjust = -0.1,\n         label = sprintf(\"Effetto vero = %.1f\", TRUE_EFFECT), color = \"red\") +\n  annotate(\"text\", x = median(multiverse_results$estimate), y = Inf, vjust = 4, hjust = -0.1,\n           label = sprintf(\"Mediana = %.2f\", median(multiverse_results$estimate)), \n           color = \"darkblue\") +\n  labs(\n    x = \"Stima dell'effetto (treatment vs control)\",\n    y = \"Numero di analisi\",\n    title = \"Distribuzione delle stime nel multiverse\",\n    subtitle = sprintf(\"72 analisi: range [%.2f, %.2f]\", \n                      min(multiverse_results$estimate), \n                      max(multiverse_results$estimate))\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzione delle stime attraverso il multiverse. La linea rossa tratteggiata indica l'effetto vero (2.5 punti). La distribuzione delle stime varia considerevolmente a seconda delle scelte analitiche adottate.](05_degrees_of_freedom_files/figure-html/fig-estimate-distribution-1.png){#fig-estimate-distribution fig-align='center' width=85%}\n:::\n:::\n\n\n**Quali scelte contano di più?**\n\nAlcune decisioni analitiche hanno più impatto di altre. Analizziamo la varianza spiegata da ciascuna scelta:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calcola la varianza spiegata da ogni scelta\nvariance_decomposition <- multiverse_results |>\n  summarise(\n    total_var = var(estimate),\n    var_outlier = var(tapply(estimate, outlier, mean)),\n    var_missing = var(tapply(estimate, missing, mean)),\n    var_covariates = var(tapply(estimate, covariates, mean)),\n    var_transformation = var(tapply(estimate, transformation, mean))\n  ) |>\n  pivot_longer(everything(), names_to = \"source\", values_to = \"variance\") |>\n  dplyr::filter(source != \"total_var\") |>\n  mutate(\n    source = str_remove(source, \"var_\"),\n    source = factor(source, \n                   levels = c(\"outlier\", \"missing\", \"covariates\", \"transformation\"),\n                   labels = c(\"Gestione outlier\", \"Gestione missing\", \n                             \"Scelta covariate\", \"Trasformazione\")),\n    pct = variance / sum(variance) * 100\n  )\n\nggplot(variance_decomposition, aes(x = reorder(source, pct), y = pct)) +\n  geom_col(fill = \"steelblue\", alpha = 0.8) +\n  geom_text(aes(label = sprintf(\"%.0f%%\", pct)), hjust = -0.2) +\n  coord_flip() +\n  labs(\n    x = \"\",\n    y = \"% varianza nelle stime\",\n    title = \"Quale scelta analitica conta di più?\",\n    subtitle = \"Decomposizione della variabilità nel multiverse\"\n  ) +\n  scale_y_continuous(limits = c(0, max(variance_decomposition$pct) * 1.2))\n```\n\n::: {.cell-output-display}\n![Impatto di ciascuna scelta analitica sulla variabilità delle stime. La gestione degli outlier e la trasformazione hanno l'impatto maggiore.](05_degrees_of_freedom_files/figure-html/fig-choice-impact-1.png){#fig-choice-impact fig-align='center' width=85%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Tabella dettagliata per scelta\nmultiverse_results |>\n  group_by(outlier) |>\n  summarise(\n    `Media stima` = sprintf(\"%.2f\", mean(estimate)),\n    `SD stima` = sprintf(\"%.2f\", sd(estimate)),\n    `% significativi` = sprintf(\"%.0f%%\", 100 * mean(significant)),\n    .groups = \"drop\"\n  ) |>\n  rename(`Gestione outlier` = outlier) |>\n  knitr::kable(caption = \"Effetto della gestione degli outlier\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Effetto della gestione degli outlier\n\n|Gestione outlier |Media stima |SD stima |% significativi |\n|:----------------|:-----------|:--------|:---------------|\n|keep             |2.35        |3.07     |88%             |\n|remove_2.5sd     |1.83        |2.37     |8%              |\n|winsorize        |1.94        |2.51     |58%             |\n\n\n:::\n:::\n\n\n**Scenario \"Molti analisti\".**\n\nSimuliamo ora la variabilità che emergerebbe se 50 ricercatori indipendenti analizzassero lo stesso dataset, ciascuno adottando scelte metodologiche diverse ma tutte plausibili e giustificabili.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\n# Simula 50 ricercatori con scelte casuali (ma pesate verso opzioni comuni)\nn_researchers <- 50\n\nset.seed(123)\n# Simula 50 ricercatori con scelte casuali\nn_researchers <- 50\n\nresearcher_results <- tibble(researcher_id = 1:n_researchers) |>\n  rowwise() |>\n  mutate(\n    # MODIFICA: probabilità più equilibrate per ottenere più varietà\n    outlier = sample(c(\"keep\", \"remove_2.5sd\", \"winsorize\"), 1,  \n                prob = c(0.4, 0.3, 0.3)),\n    missing = sample(c(\"listwise\", \"mean_imputation\"), 1, \n                    prob = c(0.5, 0.5)),\n    covariates = sample(c(\"none\", \"age\", \"age_gender\", \"all\"), 1,\n                       prob = c(0.25, 0.25, 0.25, 0.25)),\n    transformation = sample(c(\"raw\", \"log\", \"standardized\"), 1,\n                           prob = c(0.34, 0.33, 0.33)),\n    \n    # Esegui l'analisi\n    prepared_data = list(prepare_data(dataset, outlier, missing, transformation)),\n    results = list(run_analysis(prepared_data, covariates))\n  ) |>\n  unnest(results) |>\n  ungroup() |>\n  mutate(\n    significant = p_value < 0.05,\n    conclusion = case_when(\n      p_value < 0.05 & estimate > 0 ~ \"Effetto positivo significativo\",\n      p_value < 0.05 & estimate < 0 ~ \"Effetto negativo significativo\",\n      TRUE ~ \"Non significativo\"\n    )\n  )\n\n# Visualizzazione stile Gould et al.\nggplot(researcher_results, aes(x = reorder(researcher_id, estimate), y = estimate)) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"gray50\") +\n  geom_hline(yintercept = TRUE_EFFECT, linetype = \"dashed\", color = \"red\", alpha = 0.7) +\n  geom_linerange(aes(ymin = conf_low, ymax = conf_high), color = \"gray60\", alpha = 0.5) +\n  geom_point(aes(color = conclusion), size = 3) +\n  scale_color_manual(values = c(\n    \"Effetto positivo significativo\" = \"forestgreen\",\n    \"Non significativo\" = \"gray50\",\n    \"Effetto negativo significativo\" = \"coral\"\n  )) +\n  annotate(\"text\", x = n_researchers * 0.9, y = 2.5, label = \"Effetto vero\",\n           color = \"red\", vjust = -1) +\n  labs(\n    x = \"Ricercatore (ordinato per stima)\",\n    y = \"Stima dell'effetto\",\n    color = \"Conclusione\",\n    title = \"50 ricercatori, 50 risultati diversi\",\n    subtitle = sprintf(\"Stessi dati, stessa domanda, range stime: [%.2f, %.2f]\",\n                      min(researcher_results$estimate), max(researcher_results$estimate))\n  ) +\n  theme(\n    axis.text.x = element_blank(),\n    axis.ticks.x = element_blank(),\n    legend.position = \"bottom\"\n  )\n\n# Statistiche\nconclusion_stats <- researcher_results |>\n  dplyr::count(conclusion) |>\n  mutate(pct = n / sum(n) * 100)\n```\n\n::: {.cell-output-display}\n![Simulazione di 50 ricercatori indipendenti che analizzano gli stessi dati. Ogni ricercatore fa scelte ragionevoli ma diverse.](05_degrees_of_freedom_files/figure-html/fig-many-analysts-1.png){#fig-many-analysts fig-align='center' width=85%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> Effetto positivo significativo: 29 (58%)\n#> Non significativo: 21 (42%)\n```\n:::\n\n\nSe consideriamo le scelte analitiche effettuate da 50 \"ricercatori virtuali\", ognuno con combinazioni diverse ma plausibili di scelte metodologiche, notiamo che i risultati mostrano una marcata variabilità: solo il 58% di essi ottiene stime statisticamente significative ($p$ < 0.05).\n\n## Strategie di mitigazione {#sec-mitigation}\n\nLa simulazione presentata in questo capitolo riproduce, su scala ridotta, quanto documentato da @gould2025same con dati reali in un ambizioso progetto di analisi collaborativa. Nel loro studio, 174 team di ricerca indipendenti hanno ricevuto gli stessi dataset e la stessa domanda di ricerca. Il risultato è stato sorprendente per la sua eterogeneità: le stime degli effetti variavano da fortemente negative a positive, con conclusioni statistiche diametralmente opposte tra i vari gruppi. Questa variabilità non era dovuta a incompetenza o errori, ma alla naturale conseguenza di scelte analitiche tutte ragionevoli e metodologicamente difendibili.\n\nLa nostra simulazione, pur operando su scala molto più ridotta con 72 combinazioni analitiche, cattura la stessa dinamica fondamentale. Partendo da un effetto vero di 2.5 punti, le stime ottenute vanno da valori che sottostimano l'effetto reale a valori che lo sovrastimano. Alcune analisi portano a conclusioni statisticamente significative, altre no, il tutto come conseguenza di decisioni apparentemente tecniche, quali il trattamento dei valori anomali, la gestione dei dati mancanti, l'inclusione di variabili indipendenti e la trasformazione delle variabili.\n\nDi fronte a questa fragilità intrinseca del processo analitico, la comunità scientifica ha sviluppato diverse strategie di mitigazione. La pre-registrazione è forse l'approccio più diffuso: fissando le scelte analitiche prima di osservare i dati, si elimina la possibilità di selezionare, a posteriori, l'analisi che produce i risultati più favorevoli. Tuttavia, la pre-registrazione presenta importanti limiti. Non garantisce che le scelte pre-specificate siano le migliori possibili e la ricerca spesso rivela complessità impreviste che richiedono di deviare dal piano originale. Inoltre, come mostrano i dati di @gould2025same, anche i ricercatori che operano in buona fede e con piani ben definiti possono giungere a conclusioni sostanzialmente diverse.\n\nUn'alternativa complementare è la trasparenza attraverso l'analisi multiverse. Invece di presentare un singolo risultato come se fosse l'unica verità possibile, il ricercatore può esplorare sistematicamente lo spazio delle decisioni analitiche e riportare l'intera distribuzione delle conclusioni possibili. Questo approccio ha il vantaggio di rendere esplicita l'incertezza metodologica, ovvero quella componente di variabilità che non deriva dal campionamento statistico, ma dalle scelte del ricercatore. Quando un lettore vede che il 60% delle analisi ragionevoli produce risultati significativi, mentre il 40% no, acquisisce una comprensione molto più sfumata della robustezza dell'evidenza rispetto a quando legge un singolo valore-$p$.\n\nLo studio di @gould2025same ha rivelato altri aspetti preoccupanti. Né la complessità delle analisi né il processo di revisione tra pari interno ai team hanno mostrato una correlazione con l'accuratezza delle stime. La variabilità osservata tra gli analisti superava quella attribuibile esclusivamente all'errore di campionamento, suggerendo che la componente umana del processo analitico introduce una fonte di incertezza sistematicamente sottovalutata nella pratica scientifica corrente. Ciò non significa che il metodo scientifico sia inaffidabile, ma piuttosto che dovremmo essere più umili riguardo alla precisione delle nostre conclusioni e più trasparenti riguardo alle scelte che le hanno generate.\n\nLe implicazioni pratiche di queste osservazioni sono profonde. Per i ricercatori, suggeriscono l'importanza di esplorare la sensibilità dei risultati derivanti da scelte analitiche alternative, anche quando esiste un piano pre-registrato. Per i lettori della letteratura scientifica, queste implicazioni suggeriscono un atteggiamento critico nei confronti dei risultati presentati come definitivi senza alcuna discussione sulla loro robustezza. Per la comunità scientifica nel suo insieme, indicano la necessità di sviluppare standard di reportistica che includano informazioni sulla variabilità dei risultati derivante dalle scelte metodologiche dei ricercatori, non solo su quella statistica.\n\n## Riflessioni conclusive {#sec-conclusions}\n\nLe simulazioni e le evidenze empiriche presentate in questo capitolo convergono su una conclusione importante, ma spesso trascurata: lo spazio delle analisi possibili per qualsiasi dataset è vasto e le scelte metodologiche ragionevoli possono condurre a conclusioni divergenti. Questo non è un difetto del metodo scientifico, ma una sua caratteristica intrinseca che emerge ogni volta che i dati richiedono un'interpretazione e le procedure non sono completamente automatizzate.\n\nLa lezione fondamentale non è che la ricerca empirica sia inaffidabile, ma che la sua affidabilità dipende crucialmente dalla trasparenza con cui il processo analitico viene documentato e comunicato. Quando leggiamo uno studio che riporta un valore p appena sotto la soglia di significatività, dovremmo chiederci quante altre analisi ragionevoli avrebbero potuto essere condotte e quante di queste avrebbero potuto condurre a conclusioni diverse. La risposta, come mostrano le nostre simulazioni e lo studio di @gould2025same, è quasi sempre \"molte\".\n\n::: {.callout-warning title=\"Implicazione per la lettura critica\"}\nQuando leggete uno studio che riporta $p = 0.03$, chiedetevi: \"Quante altre analisi ragionevoli avrebbero potuto essere fatte? Quante avrebbero dato $p > 0.05$?\" La risposta è quasi sempre: molte.\n:::\n\nAlcune scelte analitiche hanno un impatto maggiore di altre. Nella nostra simulazione, la gestione dei valori anomali e la scelta delle covariate hanno mostrato l'impatto maggiore sulla variabilità delle stime. Ciò suggerisce che è necessario dedicare particolare attenzione alla giustificazione di queste decisioni cruciali e, possibilmente, esplorare alternative.\n\nLa pre-registrazione offre una protezione parziale, ma importante, contro l'esplorazione opportunistica dello spazio analitico. Fissare le scelte prima di vedere i dati elimina la tentazione di selezionare, a posteriori, l'analisi che produce i risultati desiderati. Tuttavia, la pre-registrazione non garantisce che la scelta pre-specificata sia quella corretta né elimina la legittima variabilità che emergerebbe se diversi ricercatori pre-registrassero piani diversi.\n\nL'approccio multiverse rappresenta un complemento prezioso, in quanto permette di quantificare esplicitamente l'incertezza metodologica e di comunicare ai lettori non solo i risultati ottenuti, ma anche la robustezza di tali risultati rispetto a scelte alternative. In un'epoca in cui la riproducibilità della ricerca è sotto scrutinio, la trasparenza diventa un valore scientifico fondamentale.\n\nLa sfida per la psicologia e per le scienze empiriche in generale non è eliminare i gradi di libertà del ricercatore, cosa impossibile data la complessità intrinseca dei fenomeni studiati, ma piuttosto rendere queste scelte visibili, giustificabili e sottoponibili al controllo della comunità scientifica. Solo in questo modo sarà possibile distinguere i risultati robusti, che resistono a molteplici analisi specifiche, da quelli fragili, che dipendono criticamente da decisioni arbitrarie.\n\n## Esercizi {#sec-esercizi}\n\n::: {.callout-important title=\"Esercizio 1: Interpretare un multiverse\" collapse=\"true\"}\n\nUno studio sulla relazione tra uso dei social media e benessere psicologico negli adolescenti riporta i seguenti risultati di un'analisi multiverse con 48 specifiche analitiche diverse:\n\n- Range delle stime: da r = −0.15 a r = +0.08\n- Mediana delle stime: r = −0.04\n- Percentuale di analisi con p < 0.05: 35%\n- Percentuale di analisi con effetto negativo: 73%\n\nGli autori concludono: \"I risultati dimostrano un effetto negativo significativo dei social media sul benessere adolescenziale.\"\n\nRispondete alle seguenti domande:\n\na) La conclusione degli autori è giustificata dai dati del multiverse? Argomentate la vostra risposta.\n\nb) Quali informazioni aggiuntive vorreste avere per valutare meglio la robustezza di questo risultato?\n\nc) Come riformulereste la conclusione per renderla più coerente con i risultati del multiverse?\n:::\n\n::: {.callout-tip title=\"Soluzione Esercizio 1\" collapse=\"true\"}\n\na) La conclusione degli autori non è pienamente giustificata. Sebbene la maggioranza delle analisi (73%) mostri un effetto negativo, solo il 35% raggiunge la significatività statistica. Inoltre, il range delle stime include valori positivi (fino a r = +0.08), indicando che alcune specifiche analitiche ragionevoli portano a conclusioni opposte. La mediana di r = −0.04 suggerisce un effetto molto piccolo, probabilmente di scarsa rilevanza pratica. Affermare un \"effetto negativo significativo\" è una semplificazione eccessiva che ignora la considerevole incertezza metodologica evidenziata dal multiverse.\n\nb) Sarebbe utile conoscere: quali scelte analitiche producono gli effetti più estremi (positivi vs negativi); se esiste una giustificazione teorica per preferire alcune specifiche ad altre; la distribuzione completa delle stime, non solo il range e la mediana; quali combinazioni di scelte portano alla significatività e quali no; e se i risultati cambiano per sottogruppi demografici diversi.\n\nc) Una conclusione più appropriata potrebbe essere: \"L'analisi multiverse suggerisce una possibile associazione negativa di piccola entità tra uso dei social media e benessere adolescenziale (mediana r = −0.04), ma questo risultato mostra considerevole sensibilità alle scelte analitiche. Mentre la maggioranza delle specifiche indica un'associazione negativa, solo un terzo raggiunge la significatività statistica, e alcune analisi plausibili suggeriscono effetti nulli o leggermente positivi. Questi risultati evidenziano l'importanza di non sovrastimare la certezza delle conclusioni in questo ambito di ricerca.\"\n:::\n\n::: {.callout-important title=\"Esercizio 2: Pre-registrazione e gradi di libertà\" collapse=\"true\"}\n\nDue gruppi di ricerca studiano indipendentemente l'efficacia di un nuovo intervento di mindfulness sull'ansia. Entrambi i gruppi pre-registrano il loro piano di analisi prima di raccogliere i dati.\n\n**Gruppo A** pre-registra:\n\n- Misura dell'ansia: State-Trait Anxiety Inventory (STAI)\n- Gestione outlier: rimozione valori oltre 3 SD\n- Analisi: t-test tra gruppi\n\n**Gruppo B** pre-registra:\n\n- Misura dell'ansia: Beck Anxiety Inventory (BAI)  \n- Gestione outlier: winsorizzazione al 95° percentile\n- Analisi: ANCOVA controllando per ansia baseline\n\nI risultati sono:\n\n- Gruppo A: differenza significativa (p = 0.03, d = 0.45)\n- Gruppo B: differenza non significativa (p = 0.12, d = 0.28)\n\nRispondete alle seguenti domande:\n\na) Entrambi i gruppi hanno seguito rigorosamente la pre-registrazione. Perché i risultati divergono?\n\nb) Un revisore suggerisce che uno dei due studi \"deve essere sbagliato\". Questa affermazione è corretta? Perché?\n\nc) Cosa ci insegna questo esempio sui limiti della pre-registrazione come soluzione al problema dei gradi di libertà?\n:::\n\n::: {.callout-tip title=\"Soluzione Esercizio 2\" collapse=\"true\"}\n\na) I risultati divergono perché i due gruppi hanno pre-registrato scelte analitiche diverse, tutte metodologicamente legittime. Le differenze riguardano lo strumento di misura (STAI vs BAI, che misurano costrutti correlati ma non identici), il trattamento degli outlier (rimozione vs winsorizzazione), e il modello statistico (t-test vs ANCOVA). Queste scelte, pur essendo tutte ragionevoli, possono produrre stime e p-value differenti. La pre-registrazione ha eliminato la flessibilità post-hoc all'interno di ciascuno studio, ma non ha eliminato la variabilità tra studi dovuta a scelte iniziali diverse.\n\nb) L'affermazione del revisore non è corretta. Entrambi gli studi potrebbero essere condotti correttamente e produrre comunque risultati diversi. Come dimostrato dallo studio di Gould et al. (2025), ricercatori competenti che analizzano gli stessi dati con approcci diversi ma legittimi arrivano regolarmente a conclusioni divergenti. La divergenza non indica necessariamente un errore, ma riflette l'incertezza metodologica intrinseca alla ricerca empirica. Un effetto reale di dimensione intermedia potrebbe essere rilevato da alcune specifiche analitiche e non da altre, specialmente con campioni di dimensione tipica per la ricerca psicologica.\n\nc) Questo esempio illustra che la pre-registrazione risolve il problema della flessibilità post-hoc (impedisce al singolo ricercatore di esplorare molteplici analisi e riportare solo quella favorevole), ma non elimina il problema della molteplicità a priori. Ricercatori diversi, tutti in buona fede, possono pre-registrare piani diversi che portano a conclusioni diverse. La pre-registrazione garantisce trasparenza e previene il p-hacking, ma non garantisce che le scelte pre-specificate siano quelle \"corrette\" o che producano stime accurate dell'effetto reale. Per questo motivo, la pre-registrazione dovrebbe essere considerata una condizione necessaria ma non sufficiente per la credibilità scientifica, idealmente complementata da analisi di sensibilità o approcci multiverse.\n:::\n\n::: {.callout-important title=\"Esercizio 3: Identificare i gradi di libertà\" collapse=\"true\"}\n\nUno studente di dottorato sta pianificando uno studio sull'effetto della privazione di sonno sulla memoria di lavoro. Descrive così il suo piano:\n\n> \"Recluterò partecipanti e li assegnerò casualmente alla condizione di privazione di sonno (4 ore) o controllo (8 ore). Il giorno dopo misurerò la memoria di lavoro. Analizzerò i dati per vedere se c'è un effetto.\"\n\nQuesta descrizione lascia molte decisioni non specificate che rappresentano potenziali gradi di libertà del ricercatore.\n\na) Identificate almeno 5 decisioni metodologiche o analitiche che lo studente dovrà prendere e che non sono specificate nel piano.\n\nb) Per ciascuna decisione identificata, indicate almeno due alternative ragionevoli che lo studente potrebbe scegliere.\n\nc) Se ciascuna delle 5 decisioni ha 2-3 alternative, quante analisi diverse potrebbe potenzialmente condurre lo studente? Cosa implica questo per l'interpretazione di un singolo risultato \"significativo\"?\n:::\n\n::: {.callout-tip title=\"Soluzione Esercizio 3\" collapse=\"true\"}\n\na) e b) Ecco cinque decisioni non specificate con le relative alternative:\n\n1. **Quale test di memoria di lavoro utilizzare?** Alternative: N-back task, Operation Span, Digit Span, Corsi Block Task. Questi test misurano aspetti correlati ma distinti della memoria di lavoro.\n\n2. **Come gestire i partecipanti che non rispettano il protocollo?** (es. chi dorme più o meno del previsto). Alternative: escluderli dall'analisi, includerli comunque, analizzare per \"intention to treat\", analizzare per \"protocol completers\".\n\n3. **Quali covariate includere nel modello?** Alternative: nessuna (semplice confronto tra gruppi), controllare per età, controllare per qualità abituale del sonno, controllare per livello di caffeina, controllare per ansia da prestazione.\n\n4. **Come definire e gestire gli outlier nelle prestazioni?** Alternative: non escludere nessuno, escludere prestazioni oltre 2 o 3 deviazioni standard, escludere tempi di risposta anomali, winsorizzare i valori estremi.\n\n5. **Quale misura della prestazione usare?** Alternative: accuratezza (% risposte corrette), tempi di reazione medi, tempi di reazione mediani, punteggio composito accuratezza-velocità.\n\nAltre possibili decisioni: dimensione del campione e regola di stop per il reclutamento; come gestire dati mancanti; quale test statistico usare (t-test, ANOVA, regressione, test non parametrici); se e come trasformare i dati.\n\nc) Se ciascuna delle 5 decisioni ha anche solo 2-3 alternative, il numero di combinazioni possibili è almeno $2^5 = 32$ e potenzialmente $3^5 = 243$ o più. Questo implica che lo studente potrebbe condurre decine o centinaia di analisi diverse, tutte legittime. Se riporta solo quella che ha prodotto p < 0.05, sta implicitamente selezionando da un vasto spazio di possibilità. Un singolo risultato \"significativo\" in questo contesto è molto meno informativo di quanto sembri: la probabilità di trovare almeno un risultato significativo per caso (anche senza effetto reale) aumenta considerevolmente con il numero di analisi possibili. Questo esempio illustra perché la trasparenza sulle scelte analitiche e, idealmente, l'esplorazione sistematica delle alternative (multiverse analysis) sono fondamentali per valutare la robustezza dei risultati.\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.5.2\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] stringr_1.6.0         broom_1.0.13          ragg_1.5.2           \n#>  [4] tinytable_0.17.0      withr_3.0.3           systemfonts_1.3.2    \n#>  [7] patchwork_1.3.2       ggdist_3.3.3          tidybayes_3.0.7      \n#> [10] bayesplot_1.15.0      ggplot2_4.0.3         reliabilitydiag_0.2.1\n#> [13] priorsense_1.2.0      posterior_1.7.0       loo_2.10.0           \n#> [16] rstan_2.32.7          StanHeaders_2.32.10   brms_2.23.0          \n#> [19] Rcpp_1.1.2            sessioninfo_1.2.4     conflicted_1.2.0     \n#> [22] janitor_2.2.1         matrixStats_1.5.0     modelr_0.1.11        \n#> [25] tibble_3.3.1          dplyr_1.2.1           tidyr_1.3.2          \n#> [28] rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      viridisLite_0.4.3    \n#>  [4] farver_2.1.2          S7_0.2.2              fastmap_1.2.0        \n#>  [7] tensorA_0.36.2.1      digest_0.6.39         timechange_0.4.0     \n#> [10] estimability_2.0.0    lifecycle_1.0.5       magrittr_2.0.5       \n#> [13] compiler_4.6.1        rlang_1.3.0           tools_4.6.1          \n#> [16] yaml_2.3.12           knitr_1.51            labeling_0.4.3       \n#> [19] bridgesampling_1.2-1  htmlwidgets_1.6.4     pkgbuild_1.4.8       \n#> [22] curl_7.1.0            RColorBrewer_1.1-3    abind_1.4-8          \n#> [25] purrr_1.2.2           grid_4.6.1            stats4_4.6.1         \n#> [28] xtable_1.8-8          inline_0.3.21         emmeans_2.0.3        \n#> [31] scales_1.4.0          cli_3.6.6             mvtnorm_1.4-1        \n#> [34] rmarkdown_2.31        generics_0.1.4        otel_0.2.0           \n#> [37] RcppParallel_5.1.11-2 cachem_1.1.0          parallel_4.6.1       \n#> [40] vctrs_0.7.3           V8_8.2.0              Matrix_1.7-5         \n#> [43] jsonlite_2.0.0        arrayhelpers_1.1-1    glue_1.8.1           \n#> [46] codetools_0.2-20      distributional_0.8.1  lubridate_1.9.5      \n#> [49] stringi_1.8.7         gtable_0.3.6          QuickJSR_1.10.0      \n#> [52] pillar_1.11.1         htmltools_0.5.9       Brobdingnag_1.2-9    \n#> [55] R6_2.6.1              textshaping_1.0.5     rprojroot_2.1.1      \n#> [58] evaluate_1.0.5        lattice_0.22-9        backports_1.5.1      \n#> [61] memoise_2.0.1         snakecase_0.11.1      rstantools_2.6.0     \n#> [64] coda_0.19-4.1         gridExtra_2.3.1       nlme_3.1-169         \n#> [67] checkmate_2.3.4       xfun_0.60             pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "05_degrees_of_freedom_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}