project:
  type: book
  output-dir: docs

book:
  title: "Metodi bayesiani in psicologia"
  # subtitle: "Anno Accademico 2024/2025"
  license: "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)"
  reader-mode: true
  google-analytics: G-QT5S3P9D31

  author: 
    - name: "Corrado Caudek"
      orcid: "0000-0002-1404-0420"
  date: "last-modified"
  search: true
  repo-url: https://github.com/ccaudek/utet-companion/
  repo-actions: [source, issue]
  back-to-top-navigation: true
  site-url: https://ccaudek.github.io/utet-companion/intro.html
  page-footer:
    left: |
      **Metodi bayesiani in psicologia — Companion site**.  
      Materiali di accompagnamento e approfondimento al manuale UTET.
    right: |
      Realizzato con <a href="https://quarto.org/">Quarto</a>.
  favicon: style/gauss.png
  sidebar:
    collapse-level: 1
    # background: whitesmoke

  chapters:
    - index.qmd
    - prefazione.qmd

    - part: "Inferenza"
      chapters:
        - chapters/bayesian_inference/introduction_sec.qmd
        - chapters/bayesian_inference/01_bayes_inference.qmd
        - chapters/bayesian_inference/02_uncertainty.qmd 
        - chapters/bayesian_inference/03_uncertainty_quantification.qmd
        - chapters/bayesian_inference/04_statistical_models.qmd
        - chapters/bayesian_inference/05_subj_prop.qmd
        - chapters/bayesian_inference/06_conjugate_families.qmd
        - chapters/bayesian_inference/07_summary_posterior.qmd
        - chapters/bayesian_inference/08_balance_prior_post.qmd
        - chapters/bayesian_inference/09_prior_pred_check.qmd
        - chapters/bayesian_inference/10_post_pred_distr.qmd
        - chapters/bayesian_inference/conclusions_sec.qmd

    - part: "MCMC"
      chapters:
        - chapters/mcmc/introduction_sec.qmd
        - chapters/mcmc/01_metropolis.qmd
        - chapters/mcmc/02_ppl.qmd
        - chapters/mcmc/03_stan_intro.qmd 
        - chapters/mcmc/04_stan_diagnostics.qmd 
        - chapters/mcmc/05_mcmc_prediction.qmd 
        - chapters/mcmc/06_stan_odds_ratio_stan.qmd 
        - chapters/mcmc/07_stan_two_means.qmd 
        - chapters/mcmc/08_stan_poisson_model_1.qmd 
        - chapters/mcmc/09_stan_gaussian_mixture.qmd 
        - chapters/mcmc/10_stan_nuisance_parameters.qmd 
        - chapters/mcmc/11_stan_hier_beta_binom.qmd 
        - chapters/mcmc/12_stan_parametrization.qmd 
        - chapters/mcmc/13_bayesian_workflow.qmd
        - chapters/mcmc/conclusions_sec.qmd

    - part: "Regressione"
      chapters:
        - chapters/linear_models/introduction_sec.qmd
        - chapters/linear_models/01_reglin_frequentist.qmd
        - chapters/linear_models/02_regr_toward_mean.qmd
        - chapters/linear_models/03_reglin_bayes.qmd
        - chapters/linear_models/04_synt_sugar_sea_ice.qmd
        - chapters/linear_models/05_stan_regression.qmd
        - chapters/linear_models/06_specification_error.qmd
        - chapters/linear_models/07_one_mean.qmd
        - chapters/linear_models/08_two_means.qmd
        - chapters/linear_models/09_effect_size.qmd
        - chapters/linear_models/10_sample_size.qmd 
        - chapters/linear_models/11_anova_1via.qmd
        - chapters/linear_models/conclusions_sec.qmd

    - part: "GLM"
      chapters:
        - chapters/glm/introduction_sec.qmd
        - chapters/glm/01_logistic_regr.qmd
        - chapters/glm/02_one_proportion.qmd
        - chapters/glm/03_two_proportions.qmd
        - chapters/glm/04_poisson_model.qmd
        - chapters/glm/05_logistic_process.qmd
        - chapters/glm/06_missing_values.qmd
        - chapters/glm/conclusions_sec.qmd
    
    - part: "Entropia"
      chapters:
        - chapters/entropy/introduction_sec.qmd
        - chapters/entropy/01_entropy.qmd
        - chapters/entropy/02_kl.qmd
        - chapters/entropy/03_model_comparison.qmd
        - chapters/entropy/conclusions_sec.qmd
        
    - part: "Modelli"
      chapters:
        - chapters/formal_models/introduction_sec.qmd
        - chapters/formal_models/01_dynamic_models.qmd
        - chapters/formal_models/02_dynamic_models.qmd
        - chapters/formal_models/03_rescorla_wagner.qmd
        - chapters/formal_models/04_study_method.qmd
        - chapters/formal_models/conclusions_sec.qmd
        
    - part: "Crisi"
      chapters:
        - chapters/replication_crisis/introduction_replication_crisis.qmd
        - chapters/replication_crisis/01_crisis.qmd
        - chapters/replication_crisis/02_limits_stat_freq.qmd
        - chapters/replication_crisis/03_effect_size.qmd
        - chapters/replication_crisis/04_s_m_errors.qmd
        - chapters/replication_crisis/05_p_values.qmd
        - chapters/replication_crisis/06_changes.qmd
        - chapters/replication_crisis/07_degrees_of_freedom.qmd
        - chapters/replication_crisis/08_integrity.qmd

    - part: "Epilogo"
      chapters:
        - chapters/epiloque/epiloque.qmd

  appendices:
    - chapters/appendix/a01_shell.qmd
    - chapters/appendix/a01a_files.qmd
    - chapters/appendix/a02_math_symbols.qmd
    - chapters/appendix/a03_latex.qmd
    - chapters/appendix/a11_numbers.qmd
    - chapters/appendix/a12_sum_notation.qmd
    - chapters/appendix/a13_sets.qmd
    - chapters/appendix/a14_combinatorics.qmd
    - chapters/appendix/a15_calculus.qmd
    - chapters/appendix/a35_other_conjugate_families.qmd
    - chapters/appendix/a36_gamma_poisson_model.qmd
    - chapters/appendix/a40_metropolis_normal.qmd
    - chapters/appendix/a41_cmdstanr_intro.qmd
    - chapters/appendix/a50_lin_fun.qmd
    - chapters/appendix/a71_install_cmdstan.qmd

crossref:
  appendix-title: "Appendice"

# title-prefix: ""
toc: true
toc-depth: 2

bibliography: ./references.bib
biblio-style: apalike
csl: apa.csl
link-citations: true

format:
  html:
    include-in-header:
      - style/_mathjax-config.html
    include-after-body:
      - style/_after-body.html
    theme: style/mystyle.scss # style/etbook-litera.scss # 
    css:
      - style/_typography-extras.css
      - style/_code-extras.css
      - style/_math-extras.css
      - style/styles.css
    fig-format: png
    dpi: 192
    fig-responsive: true
    smooth-scroll: true
    page-layout: article
    max-width: 72ch
    number-sections: true
    link-external-icon: true
    link-external-newwindow: true
    footnotes-hover: true
    reader-mode: true
    callout-appearance: minimal
    lang: it
    html-math-method: mathjax
    # Metadati aggiuntivi per il look classico
    title-block-banner: false
    toc-title: "Sommario"
    date-format: "D MMMM YYYY"

     # === CODICE ===
    code-copy: hover
    code-link: true
    code-overflow: scroll
    code-line-numbers: false
    code-block-bg: false
    code-block-border-left: false
    # highlight-style: tango

  # pdf:
  #   documentclass: scrreprt  # impaginazione da libro (KOMA-Script)
  #   classoption: [12pt, oneside]
  #   pdf-engine: xelatex
  #   pdf-engine-opt: "-shell-escape"
  #   number-sections: true
  #   toc: true
  #   toc-depth: 2
  #   fig-align: center
  #   fig-width: 6
  #   fig-height: 4
  #   keep-tex: true


execute:
  freeze: auto  # Skip re-executing unchanged code chunks
  echo: true  # Display code in the output document
  warning: false  # Suppress warnings in output
  message: false  # Suppress messages in output
  fig.width: 6  # Set figure width (in inches)
  fig.asp: 0.618  # Set figure aspect ratio (golden ratio for aesthetics)
  fig.retina: 2  # High resolution for retina displays
  fig.align: "center"  # Center-align all figures
  fig.show: "hold"  # Group multiple figures from a chunk
  options:
    width: 120            # allarga la console virtuale
    pillar.width: Inf      # disattiva il riassunto colonne
    tibble.width: Inf      # idem, per sicurezza

website:
  cookie-consent:
    type: express
    style: headline
    anonymize-ip: true
