{
  "hash": "bf3225d3bce757a646a3e7dc078d4125",
  "result": {
    "engine": "knitr",
    "markdown": "# La dimensione dell'effetto: un laboratorio computazionale {#sec-effect-size}\n\n::: {.callout-note appearance=\"minimal\"}\nLa **dimensione dell'effetto** (*effect size*) descrive l'ampiezza di una differenza o di una relazione statistica. Risponde quindi a una domanda diversa da quella affrontata da un test di significatività: non stabilisce se un effetto “esiste”, ma quantifica quanto grande appare nei dati, sulla scala scelta.\n\nÈ essenziale distinguere la dimensione dell'effetto dalla significatività statistica. Un risultato può essere statisticamente significativo pur avendo un effetto molto piccolo, soprattutto in un campione grande; viceversa, un effetto sostanziale può essere stimato con grande incertezza in un campione piccolo. Né il valore-$p$ né la dimensione dell'effetto, considerati isolatamente, esauriscono l'interpretazione di un risultato.\n\nLe linee guida dell'*American Psychological Association* raccomandano di accompagnare i test statistici con misure della dimensione dell'effetto [@apa2010]. Tuttavia, riportare un indice non equivale a comprenderlo. In questo capitolo useremo simulazioni e visualizzazioni per interpretare il $d$ di Cohen, la correlazione $r$ e il coefficiente $r^2$, prestando attenzione alle assunzioni e al contesto applicativo.\n:::\n\n::: {.callout-important appearance=\"minimal\" .chapter-status}\n**Da sapere.** La dimensione dell'effetto descrive quanto è grande una differenza o una relazione, non se essa supera una soglia di significatività. Il $d$ di Cohen, la correlazione $r$ e $r^2$ rispondono a domande diverse e devono essere interpretati nel contesto teorico e applicativo, senza affidarsi automaticamente alle etichette “piccolo”, “medio” e “grande”.\n\n**Da saper fare.** Calcolare e interpretare il $d$ di Cohen e il coefficiente $r$; tradurre, sotto opportune assunzioni, un effetto standardizzato in una probabilità di superiorità; distinguere il significato di $r$ da quello di $r^2$; valutare un effetto mediante confronti empirici e conseguenze pratiche.\n\n**Approfondimento facoltativo.** I dettagli computazionali delle simulazioni, la discussione degli effetti cumulativi e il *piranha problem* approfondiscono gli stessi concetti, ma possono essere rimandati in una prima lettura. Gli esercizi finali consolidano invece gli obiettivi essenziali.\n\n[Che cosa significano queste etichette?](../../guida-al-manuale.qmd#sec-percorsi-lettura)\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Prerequisiti\"}\n\n- Sono dati per noti i limiti dell'inferenza frequentista discussi nel @sec-limits-freq-inference.\n- È utile conoscere media, deviazione standard e correlazione; questi concetti possono essere ripresi nel percorso di *Analisi esplorativa dei dati*.\n- La lettura del codice R è facoltativa per il percorso essenziale.\n\n:::\n\n::: {.callout-caution collapse=\"true\" title=\"Preparazione del notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |>\n  source()\nlibrary(purrr)\n```\n:::\n\n:::\n\n## Il $d$ di Cohen: la differenza tra gruppi\n\n### Definizione e calcolo\n\nIl $d$ di Cohen è la misura più utilizzata per quantificare la differenza tra due gruppi. Esprime la differenza tra le medie in unità di deviazione standard:\n\n$$\nd = \\frac{M_1 - M_2}{S_p},\n$$\ndove $S_p$ è la deviazione standard combinata (*pooled*):\n\n$$\nS_p = \\sqrt{\\frac{(n_1 - 1) S_1^2 + (n_2 - 1) S_2^2}{n_1 + n_2 - 2}}.\n$$\n\nUn $d = 0.5$ significa che le medie dei due gruppi differiscono di mezza deviazione standard combinata. Il segno indica la direzione della differenza, mentre il valore assoluto ne descrive l'ampiezza standardizzata.\n\n::: {.callout-note appearance=\"minimal\" title=\"Stima campionaria e incertezza: il significato prima degli intervalli\"}\nIl $d$ calcolato in un campione è una **stima**, non il valore esatto dell'effetto nella popolazione. La sua interpretazione dovrebbe quindi essere accompagnata da una valutazione dell'incertezza. In questo capitolo ci concentriamo sul significato degli indici; nei capitoli successivi l'incertezza sarà rappresentata esplicitamente mediante distribuzioni e intervalli.\n:::\n\nResta però da chiarire che cosa significhi, concretamente, una differenza di mezza deviazione standard.\n\n### Visualizzare il $d$ di Cohen\n\nLa seguente simulazione mostra come appaiono distribuzioni con diversi valori di $d$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npalette_groups <- setNames(\n  palette_qualitative[c(5, 1)],\n  c(\"Controllo\", \"Trattamento\")\n)\n\n# Funzione per generare dati con un dato Cohen's d\ngenerate_groups <- function(d, n = 1000) {\n  tibble(\n    value = c(\n      rnorm(n, mean = 0, sd = 1),\n      rnorm(n, mean = d, sd = 1)\n    ),\n    group = factor(\n      rep(c(\"Controllo\", \"Trattamento\"), each = n),\n      levels = c(\"Controllo\", \"Trattamento\")\n    )\n  )\n}\n\n# Valori di d e label\nd_values <- c(0.2, 0.5, 0.8, 1.2)\nlabels <- c(\n  \"d = 0.2\",\n  \"d = 0.5\",\n  \"d = 0.8\",\n  \"d = 1.2\"\n)\n\nplots <- map2(d_values, labels, function(d, label) {\n  data <- generate_groups(d)\n  \n  overlap <- 2 * pnorm(-abs(d) / 2) * 100\n  \n  ggplot(data, aes(x = value, fill = group)) +\n    geom_density(alpha = 0.5, color = \"white\") +\n    geom_vline(\n      xintercept = 0,\n      linetype = \"dashed\",\n      color = palette_groups[\"Controllo\"],\n      alpha = 0.7\n    ) +\n    geom_vline(\n      xintercept = d,\n      linetype = \"dashed\",\n      color = palette_groups[\"Trattamento\"],\n      alpha = 0.7\n    ) +\n    scale_fill_manual(values = palette_groups) +\n    labs(\n      title = label,\n      subtitle = sprintf(\"Sovrapposizione: %.0f%%\", overlap),\n      x = \"Valore standardizzato\",\n      y = \"Densità\",\n      fill = \"\"\n    ) +\n    theme(legend.position = \"bottom\") +\n    coord_cartesian(xlim = c(-4, 5))\n})\n\n(plots[[1]] + plots[[2]]) / (plots[[3]] + plots[[4]])\n```\n\n::: {.cell-output-display}\n![Visualizzazione di diversi valori del $d$ di Cohen assumendo distribuzioni normali con uguale deviazione standard. All'aumentare di $d$, la sovrapposizione diminuisce, ma rimane sostanziale anche per $d = 0.8$.](02_effect_size_files/figure-html/fig-cohen-d-visual-1.png){#fig-cohen-d-visual fig-align='center' width=100%}\n:::\n:::\n\n\n### Interpretare il $d$ di Cohen: dalla scala standardizzata a una probabilità\n\nQuando le due popolazioni si possono rappresentare con distribuzioni normali indipendenti e uguale deviazione standard, il $d$ di Cohen si traduce nella probabilità che un'osservazione estratta a caso dal primo gruppo superi un'osservazione estratta dal secondo, mantenendo l'ordine usato nel calcolo $d=(M_1-M_2)/S_p$. Questa quantità è spesso chiamata *Common Language Effect Size* (CLES) o probabilità di superiorità:\n\n$$\n\\text{CLES} = \\Phi\\left(\\frac{d}{\\sqrt{2}}\\right)\n$$\n\ndove $\\Phi$ è la funzione di distribuzione cumulativa della normale standard.\n\nQuesta traduzione può rendere più intuitiva la sovrapposizione tra i gruppi. Non indica però la probabilità che un trattamento “funzioni”, non dimostra un rapporto causale e non stabilisce la rilevanza clinica o pratica dell'effetto. Inoltre, se punteggi più alti rappresentano esiti peggiori, una probabilità di superiorità elevata non costituisce un beneficio.\n\n\n::: {#tbl-cles .cell layout-align=\"center\" tbl-cap='Relazione tra d di Cohen, probabilità di superiorità e sovrapposizione, sotto l\\'ipotesi di normalità e uguale varianza'}\n\n```{.r .cell-code}\ncles <- function(d) {\n  pnorm(d / sqrt(2))\n}\n\noverlap_normal <- function(d) {\n  2 * pnorm(-abs(d) / 2)\n}\n\ncles_table <- tibble(\n  `Cohen's d` = c(0.0, 0.2, 0.5, 0.8, 1.0, 1.5, 2.0)\n) |>\n  mutate(\n    `Probabilità di superiorità` = formato_percentuale_it(\n      accuracy = 0.1\n    )(cles(`Cohen's d`)),\n    `Sovrapposizione tra le distribuzioni` = formato_percentuale_it(\n      accuracy = 0.1\n    )(overlap_normal(`Cohen's d`))\n  )\n\ncles_table |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n| Cohen's d|Probabilità di superiorità |Sovrapposizione tra le distribuzioni |\n|---------:|:--------------------------|:------------------------------------|\n|       0.0|50.0%                      |100.0%                               |\n|       0.2|55.6%                      |92.0%                                |\n|       0.5|63.8%                      |80.3%                                |\n|       0.8|71.4%                      |68.9%                                |\n|       1.0|76.0%                      |61.7%                                |\n|       1.5|85.6%                      |45.3%                                |\n|       2.0|92.1%                      |31.7%                                |\n\n\n:::\n:::\n\n\nPer $d = 0.2$, la probabilità di superiorità è circa il 56%: scegliendo una persona da ciascun gruppo, quella appartenente al gruppo con media maggiore avrà il punteggio più alto poco più spesso del caso. Per $d = 0.8$, la probabilità sale a circa il 71%, ma le due distribuzioni continuano a sovrapporsi ampiamente.\n\nQuesti numeri aiutano a visualizzare l'effetto, ma non sostituiscono il giudizio sostanziale. Per interpretare una differenza è ancora necessario chiedersi che cosa misuri il punteggio, quale variazione sia importante nel dominio considerato, quali siano i costi dell'intervento e quanto sia precisa la stima.\n\n## Il coefficiente di correlazione $r$: comprendere le relazioni lineari\n\nIl coefficiente di correlazione $r$ di Pearson quantifica la forza e la direzione di una relazione lineare tra due variabili continue. La sua scala varia da -1 (correlazione negativa perfetta) a +1 (correlazione positiva perfetta), con lo zero che indica assenza di relazione lineare.\n\nIn un caso particolare, una differenza tra due gruppi può essere espressa anche come correlazione punto-biseriale. Se i gruppi hanno numerosità uguale e si assume una varianza comune, vale la conversione:\n\n$$\nd = \\frac{2r}{\\sqrt{1-r^2}} \\qquad \\text{e} \\qquad r = \\frac{d}{\\sqrt{d^2 + 4}}.\n$$\n\nLa conversione non è una proprietà universale di qualunque $d$ e qualunque $r$: dipende dalla codifica e dalla proporzione dei partecipanti nei due gruppi. Va quindi usata solo quando tali condizioni sono appropriate.\n\n### Visualizzazione di correlazioni di diversa intensità\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Visualizzazione di correlazioni progressivamente più forti. Con $r$ = 0.1 la relazione è quasi impercettibile; con $r$ = 0.7 la relazione lineare è netta.](02_effect_size_files/figure-html/fig-correlations-visual-1.png){#fig-correlations-visual fig-align='center' width=100%}\n:::\n:::\n\n\n## $r$ e $r^2$: due domande diverse\n\n### Che cosa si perde elevando $r$ al quadrato\n\nLa correlazione $r$ descrive la direzione e l'intensità di una relazione lineare su una scala compresa tra -1 e 1. Il coefficiente $r^2$ elimina il segno e, nella regressione lineare semplice con intercetta, coincide con la proporzione della variabilità campionaria dell'esito associata al predittore attraverso il modello lineare.\n\nLe due quantità rispondono quindi a domande diverse. $r^2$ è utile per descrivere l'adattamento di un modello, ma non è una misura della “percentuale di importanza” di una variabile e non autorizza interpretazioni causali. Inoltre, la trasformazione quadratica comprime i valori vicini a zero: un $r = 0.30$ diventa $r^2 = 0.09$, ma questo non significa che la relazione sia diventata più debole; è cambiata la scala con cui la stiamo descrivendo.\n\n\n::: {#tbl-r-r2 .cell layout-align=\"center\" tbl-cap='La trasformazione da r a r² elimina la direzione e cambia la scala dell\\'indice'}\n\n```{.r .cell-code}\nr_examples <- tibble(\n  r = c(-0.70, -0.30, -0.10, 0.10, 0.30, 0.70)\n) |>\n  mutate(\n    `r²` = r^2,\n    Direzione = if_else(r < 0, \"Negativa\", \"Positiva\")\n  )\n\nr_examples |>\n  knitr::kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|    r|   r²|Direzione |\n|----:|----:|:---------|\n| -0.7| 0.49|Negativa  |\n| -0.3| 0.09|Negativa  |\n| -0.1| 0.01|Negativa  |\n|  0.1| 0.01|Positiva  |\n|  0.3| 0.09|Positiva  |\n|  0.7| 0.49|Positiva  |\n\n\n:::\n:::\n\n\nCorrelazioni di segno opposto, come $r=-0.30$ e $r=0.30$, producono lo stesso $r^2=0.09$. Se la direzione della relazione è sostantivamente importante, riportare soltanto $r^2$ nasconde quindi un'informazione essenziale.\n\n### Visualizzare la trasformazione\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![La relazione tra r e r² è quadratica: i valori vicini a zero vengono compressi e il segno scompare.](02_effect_size_files/figure-html/fig-r-vs-r2-1.png){#fig-r-vs-r2 fig-align='center' width=85%}\n:::\n:::\n\n\n### Come interpretare correttamente $r^2$\n\nL'uso di $r^2$ è appropriato quando la domanda riguarda l'adattamento o la capacità descrittiva di un modello lineare. Diventa fuorviante quando viene trasformato in un giudizio automatico sulla rilevanza pratica.\n\nPer esempio, affermare che “$r=0.30$ conta poco perché spiega solo il 9% della varianza” trascura almeno quattro aspetti:\n\n1. $r^2$ non esprime la probabilità che la relazione sia vera;\n2. non indica quale differenza concreta nell'esito corrisponda alla relazione;\n3. non distingue tra effetti causali, associazioni dovute a confondimento e semplici capacità predittive;\n4. non considera se l'effetto si accumuli nel tempo o riguardi una popolazione molto ampia.\n\nÈ quindi utile riportare $r$ insieme a $r^2$, chiarire il modello a cui $r^2$ si riferisce e tradurre, quando possibile, l'associazione nelle unità originali dell'esito. La critica rivolta all'uso indiscriminato di $r^2$ non implica che l'indice sia matematicamente scorretto: implica che non deve essere usato per rispondere a domande che non gli competono [@funder2019evaluating].\n\n## Gli standard di Cohen: utili ma arbitrari\n\nJacob Cohen propose soglie convenzionali per classificare gli effetti [@cohen1988statistical]:\n\n| Misura | Piccolo | Medio | Grande |\n|--------|---------|-------|--------|\n| $d$    | 0.20    | 0.50  | 0.80   |\n| $r$    | 0.10    | 0.30  | 0.50   |\n\nCohen presentò queste soglie come convenzioni da utilizzare soprattutto quando non fosse disponibile una base migliore. Il problema è che “piccolo”, “medio” e “grande” sono privi di significato senza un termine di confronto sostantivo.\n\n### Lo stesso $d$ in contesti diversi\n\nLa standardizzazione rende confrontabili differenze espresse in unità diverse, ma può nascondere ciò che l'effetto rappresenta concretamente. La tabella seguente usa valori puramente illustrativi per mostrare come lo stesso $d=0.30$ corrisponda a differenze grezze diverse.\n\n\n::: {#tbl-context-matters .cell layout-align=\"center\" tbl-cap='Lo stesso effetto standardizzato può corrispondere a differenze molto diverse nelle unità originali'}\n\n```{.r .cell-code}\ncontexts <- tibble(\n  Contesto = c(\n    \"Punteggio cognitivo\",\n    \"Scala di sintomi\",\n    \"Tempo di risposta\"\n  ),\n  `Deviazione standard` = c(15, 10, 80),\n  `Cohen's d` = 0.30,\n  Unità = c(\"punti\", \"punti\", \"millisecondi\")\n) |>\n  mutate(\n    `Differenza grezza` = `Cohen's d` * `Deviazione standard`,\n    `Differenza nelle unità originali` = paste(\n      formato_italiano(accuracy = 0.1)(`Differenza grezza`),\n      Unità\n    )\n  ) |>\n  select(\n    Contesto,\n    `Deviazione standard`,\n    `Cohen's d`,\n    `Differenza nelle unità originali`\n  )\n\ncontexts |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Contesto            | Deviazione standard| Cohen's d|Differenza nelle unità originali |\n|:-------------------|-------------------:|---------:|:--------------------------------|\n|Punteggio cognitivo |                  15|       0.3|4.5 punti                        |\n|Scala di sintomi    |                  10|       0.3|3.0 punti                        |\n|Tempo di risposta   |                  80|       0.3|24.0 millisecondi                |\n\n\n:::\n:::\n\n\nLa tabella non stabilisce quale differenza sia importante. Mostra invece perché il giudizio non possa derivare dal solo valore standardizzato. Per valutarne la rilevanza occorre conoscere l'affidabilità della misura, la variabilità della popolazione, le soglie decisionali, il rapporto fra costi e benefici e le conseguenze dell'effetto nel dominio specifico.\n\n## Benchmark empirici e conseguenze concrete\n\n@funder2019evaluating propongono due strategie complementari per interpretare una dimensione dell'effetto: confrontarla con effetti ben compresi nello stesso dominio e tradurla in conseguenze concrete. Entrambe le strategie sono più informative dell'applicazione automatica di soglie universali.\n\n### Una proposta orientativa per la ricerca psicologica\n\nFunder e Ozer formulano una guida per la correlazione $r$ nella ricerca psicologica. La proposta non è una nuova legge generale: presuppone che la stima sia affidabile e serve soprattutto a ricordare che effetti piccoli sul singolo evento possono diventare importanti quando si accumulano.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfunder_guide <- tibble(\n  r = c(0.05, 0.10, 0.20, 0.30, 0.40),\n  Interpretazione = factor(\n    c(\n      \"Molto piccolo sul singolo evento\",\n      \"Piccolo, potenzialmente cumulativo\",\n      \"Medio\",\n      \"Grande\",\n      \"Molto grande; verificare la stabilità\"\n    ),\n    levels = rev(c(\n      \"Molto piccolo sul singolo evento\",\n      \"Piccolo, potenzialmente cumulativo\",\n      \"Medio\",\n      \"Grande\",\n      \"Molto grande; verificare la stabilità\"\n    ))\n  )\n)\n\nggplot(funder_guide, aes(x = r, y = Interpretazione)) +\n  geom_segment(\n    aes(x = 0, xend = r, yend = Interpretazione),\n    linewidth = 1,\n    colour = modern_palette$grey5\n  ) +\n  geom_point(size = 3.5, colour = PRIMARY) +\n  geom_text(\n    aes(label = sprintf(\"r = %.2f\", r)),\n    nudge_x = 0.015,\n    hjust = 0,\n    colour = modern_palette$text_dark\n  ) +\n  scale_x_continuous(limits = c(0, 0.48), breaks = seq(0, 0.4, 0.1)) +\n  labs(\n    x = \"Correlazione (r)\",\n    y = NULL,\n    title = \"Una guida orientativa, non una classificazione automatica\"\n  ) +\n  nessuna_griglia\n```\n\n::: {.cell-output-display}\n![Guida orientativa proposta da Funder e Ozer (2019) per interpretare correlazioni affidabilmente stimate nella ricerca psicologica. Non si tratta di soglie universali.](02_effect_size_files/figure-html/fig-funder-guide-1.png){#fig-funder-guide fig-align='center' width=85%}\n:::\n:::\n\n\nUn benchmark utile dovrebbe essere scelto prima di conoscere il risultato e dovrebbe provenire, quando possibile, dallo stesso dominio, dalla stessa misura o da una decisione simile. Sono particolarmente informativi:\n\n- la distribuzione degli effetti ottenuti in studi comparabili;\n- l'effetto di un intervento già utilizzato come riferimento;\n- la differenza minima capace di modificare una decisione pratica;\n- il rapporto tra benefici, costi e possibili conseguenze indesiderate.\n\n### Effetti piccoli che si accumulano\n\nUn effetto modesto può produrre conseguenze rilevanti quando interessa molte persone o si ripete nel tempo. La simulazione seguente considera un intervento che sposta di $d=0.20$ una distribuzione normale. Definiamo “successo” il superamento di una soglia che, senza intervento, viene oltrepassata dal 50% della popolazione.\n\n\n::: {#tbl-cumulative-effects .cell layout-align=\"center\" tbl-cap='Conseguenze cumulative di uno spostamento pari a d = 0.20 in uno scenario illustrativo'}\n\n```{.r .cell-code}\nn_people <- c(100, 1000, 10000, 100000, 1000000)\neffect_d <- 0.20\nbaseline_success <- 0.50\nintervention_success <- pnorm(qnorm(baseline_success) + effect_d)\n\ncumulative <- tibble(\n  `Persone coinvolte` = n_people,\n  `Successi senza intervento` = round(n_people * baseline_success),\n  `Successi con intervento` = round(n_people * intervention_success),\n  `Successi aggiuntivi` = round(\n    n_people * (intervention_success - baseline_success)\n  )\n) |>\n  mutate(across(everything(), scales::label_comma(big.mark = \".\")))\n\ncumulative |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Persone coinvolte |Successi senza intervento |Successi con intervento |Successi aggiuntivi |\n|:-----------------|:-------------------------|:-----------------------|:-------------------|\n|100               |50                        |58                      |8                   |\n|1.000             |500                       |579                     |79                  |\n|10.000            |5.000                     |5.793                   |793                 |\n|100.000           |50.000                    |57.926                  |7.926               |\n|1.000.000         |500.000                   |579.260                 |79.260              |\n\n\n:::\n:::\n\n\nNel modello simulato, il tasso di successo passa dal 50% a circa 57.9%. La traduzione dipende interamente dalle assunzioni adottate: normalità, uguale variabilità e soglia fissata. Non è quindi una previsione generale, ma mostra perché l'importanza pratica non possa essere dedotta dal solo aggettivo “piccolo”.\n\n## Il *piranha problem*: verificare la coerenza tra molti effetti\n\nIl *piranha problem* invita a verificare se molti effetti dichiarati grandi possano coesistere nello stesso sistema. Quando numerosi predittori sono associati allo stesso esito, la plausibilità delle stime dipende anche dalle relazioni tra i predittori: molti effetti grandi e indipendenti non possono “consumare” più variabilità di quella disponibile [@tosh2021piranha].\n\nLa figura seguente illustra un caso semplificato. Supponiamo che tutti i predittori siano tra loro indipendenti, standardizzati e correlati con l'esito per $r=0.30$. In una regressione lineare, in queste condizioni ideali, i contributi a $R^2$ si sommano.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn_predictors <- 1:20\nr_each <- 0.30\ncumulative_r2 <- n_predictors * r_each^2\nfirst_impossible <- n_predictors[which(cumulative_r2 > 1)[1]]\n\npiranha_data <- tibble(\n  `Numero di predittori` = n_predictors,\n  `R² cumulativa` = cumulative_r2\n)\n\nggplot(\n  piranha_data,\n  aes(x = `Numero di predittori`, y = `R² cumulativa`)\n) +\n  geom_line(colour = PRIMARY, linewidth = 1.2) +\n  geom_point(colour = PRIMARY, size = 2) +\n  geom_hline(\n    yintercept = 1,\n    colour = modern_palette$grey3,\n    linetype = \"dashed\",\n    linewidth = 1\n  ) +\n  geom_vline(\n    xintercept = first_impossible,\n    colour = palette_qualitative[1],\n    linetype = \"dotted\",\n    linewidth = 1\n  ) +\n  annotate(\n    \"text\",\n    x = first_impossible + 0.4,\n    y = 0.55,\n    label = sprintf(\n      \"Dal predittore %d\\nla somma supera 1\",\n      first_impossible\n    ),\n    hjust = 0,\n    colour = palette_qualitative[1]\n  ) +\n  scale_x_continuous(breaks = seq(0, 20, 2)) +\n  scale_y_continuous(limits = c(0, 1.8), breaks = seq(0, 1.8, 0.2)) +\n  labs(\n    title = \"Un controllo di coerenza tra molti effetti\",\n    subtitle = \"Caso illustrativo: predittori indipendenti con r = 0.30\",\n    x = \"Numero di predittori\",\n    y = \"Somma dei contributi a R²\"\n  )\n```\n\n::: {.cell-output-display}\n![Illustrazione semplificata del piranha problem. Se predittori indipendenti avessero tutti r = 0.30 con lo stesso esito, la somma dei loro contributi supererebbe R² = 1 a partire dal dodicesimo predittore.](02_effect_size_files/figure-html/fig-piranha-problem-1.png){#fig-piranha-problem fig-align='center' width=85%}\n:::\n:::\n\n\nIl grafico non dimostra che ogni insieme di effetti grandi sia impossibile. I predittori reali possono essere correlati tra loro, rappresentare aspetti sovrapposti dello stesso processo o interagire. Proprio queste dipendenze, però, devono essere esplicitate. Il *piranha problem* pone quindi una domanda di coerenza: **quali relazioni tra i predittori rendono compatibili tutti gli effetti dichiarati?**\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nLe dimensioni dell'effetto sono indispensabili perché spostano l'attenzione dalla sola decisione “significativo/non significativo” all'ampiezza delle differenze e delle relazioni. Tuttavia, nessun indice possiede un significato autosufficiente.\n\nIl $d$ di Cohen esprime una differenza tra medie in unità di deviazione standard. Questa standardizzazione facilita alcuni confronti, ma il suo significato dipende dalla variabilità della popolazione e dall'affidabilità della misura. La CLES può rendere più intuitiva la sovrapposizione tra due gruppi, purché siano dichiarate le assunzioni necessarie e non venga confusa con la probabilità di efficacia o con la rilevanza pratica.\n\nLa correlazione $r$ conserva direzione e intensità dell'associazione lineare. Il coefficiente $r^2$ descrive invece, in uno specifico modello lineare, la quota di variabilità associata al predittore. È una quantità utile per l'adattamento del modello, ma non misura automaticamente l'importanza, la causalità o l'utilità dell'effetto.\n\nLe etichette convenzionali di Cohen possono servire come riferimento provvisorio, non come criterio decisionale. Un'interpretazione responsabile richiede di tornare alle unità originali, confrontare la stima con benchmark pertinenti, considerarne l'incertezza e valutarne le conseguenze concrete. Gli effetti piccoli possono accumularsi; quelli molto grandi devono essere sottoposti a controlli di coerenza e replicazione.\n\nLa domanda conclusiva non è quindi soltanto “quanto vale l'indice?”, ma: **che cosa rappresenta, quanto è preciso, rispetto a quale riferimento è grande e quali conseguenze produce nel contesto studiato?**\n\n## Esercizi {.unnumbered .unlisted}\n\n### Esercizio 1 — Comprendere {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 5–10 minuti*\n\nUno studio confronta due gruppi e riporta $d=0.50$. Spiega con parole tue:\n\n1. che cosa significa il valore 0.50;\n2. che cosa indica il segno di $d$;\n3. che cosa **non** possiamo concludere dal solo valore di $d$;\n4. perché la sovrapposizione tra i gruppi rimane importante.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nDistingui l'ampiezza standardizzata della differenza dalla significatività statistica, dall'incertezza e dalla rilevanza pratica.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\nUn valore $d=0.50$ indica che le medie dei due gruppi differiscono di mezza deviazione standard combinata. Il segno dipende dall'ordine con cui sono sottratte le medie e indica quale gruppo ha la media maggiore. Il valore non stabilisce se la differenza sia statisticamente significativa, precisa, causale o praticamente importante. Assumendo distribuzioni normali con uguale varianza, la probabilità di superiorità è circa il 64%, per cui molte osservazioni del gruppo con media minore superano comunque osservazioni dell'altro gruppo.\n:::\n\n### Esercizio 2 — Prevedere {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 5–10 minuti*\n\nConsidera una differenza tra medie pari a 6 punti.\n\n- Scenario A: la deviazione standard combinata è 12;\n- Scenario B: la deviazione standard combinata è 6.\n\nPrima di effettuare il calcolo, prevedi in quale scenario il $d$ di Cohen sarà maggiore. Calcola poi i due valori e spiega perché una stessa differenza grezza può produrre effetti standardizzati diversi.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nRicorda che $d$ è il rapporto tra differenza delle medie e deviazione standard combinata.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\nNello scenario A, $d=6/12=0.50$. Nello scenario B, $d=6/6=1.00$. A parità di differenza tra le medie, una minore variabilità rende i gruppi più separati in termini standardizzati. Questo mostra anche perché due studi con la stessa differenza grezza possono riportare valori di $d$ diversi se le popolazioni o le misure hanno variabilità differente.\n:::\n\n### Esercizio 3 — Modificare {.unnumbered .unlisted}\n\n*Codice: sì · Tempo indicativo: 10–15 minuti*\n\nNella sezione “Visualizzare il $d$ di Cohen”, modifica `d_values` sostituendo uno dei valori con $d=0.10$ e un altro con $d=1.50$.\n\n1. Prima di eseguire il codice, prevedi come cambieranno la sovrapposizione e la probabilità di superiorità.\n2. Esegui il codice.\n3. Calcola la CLES dei due nuovi valori con la funzione `cles()`.\n4. Descrivi il risultato senza usare le etichette “piccolo” o “grande”.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nAll'aumentare del valore assoluto di $d$, la sovrapposizione diminuisce e la probabilità di superiorità si allontana dal 50%.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\nPer $d=0.10$, la CLES è circa il 52.8% e le distribuzioni sono quasi completamente sovrapposte. Per $d=1.50$, la CLES è circa l'85.6% e la separazione è molto più marcata, pur senza diventare perfetta.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nformato_percentuale_it(accuracy = 0.1)(\n  cles(c(0.10, 1.50))\n)\n#> [1] \"52.8%\" \"85.6%\"\n```\n:::\n\n\nUna descrizione appropriata potrebbe essere: “Nel primo caso, una persona del gruppo con media maggiore supera una persona dell'altro gruppo poco più spesso del caso; nel secondo, ciò avviene in circa 86 confronti su 100”. Questa traduzione non stabilisce da sola la rilevanza pratica.\n:::\n\n### Esercizio 4 — Criticare {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 10 minuti*\n\nUn ricercatore scrive:\n\n> La correlazione tra ore di studio e voto è $r=0.40$. Poiché $r^2=0.16$, lo studio spiega soltanto il 16% della varianza e quindi conta poco per il rendimento.\n\nIndividua almeno tre problemi nell'argomentazione e proponi una formulazione più corretta.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nConsidera la differenza tra associazione e causalità, il significato di $r^2$ e la necessità di tradurre l'effetto nelle unità originali.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Elementi per la risposta\"}\nLa conclusione è eccessiva per almeno quattro ragioni. Primo, $r^2=0.16$ descrive l'adattamento di una relazione lineare semplice, non una percentuale di “importanza”. Secondo, una correlazione non dimostra che aumentare le ore di studio causi un aumento del voto. Terzo, senza conoscere le deviazioni standard non possiamo tradurre $r$ in una variazione attesa del voto per ogni ora aggiuntiva. Quarto, la rilevanza dipende dai costi, dalle alternative e dalla stabilità della stima.\n\nUna formulazione più corretta è: “Nel campione, ore di studio e voto mostrano un'associazione lineare positiva pari a $r=0.40$; nel modello lineare semplice, $r^2=0.16$. Per valutarne l'importanza pratica e l'eventuale significato causale sono necessarie ulteriori informazioni sul disegno, sull'incertezza e sulle unità di misura”.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.6.1\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] purrr_1.2.2           ragg_1.5.2            tinytable_0.17.0     \n#>  [4] withr_3.0.3           systemfonts_1.3.2     patchwork_1.3.2      \n#>  [7] ggdist_3.3.3          tidybayes_3.0.7       bayesplot_1.15.0     \n#> [10] ggplot2_4.0.3         reliabilitydiag_0.2.1 priorsense_1.2.0     \n#> [13] posterior_1.7.0       loo_2.10.1            rstan_2.32.7         \n#> [16] StanHeaders_2.32.10   brms_2.23.1           Rcpp_1.1.2           \n#> [19] sessioninfo_1.2.4     conflicted_1.2.0      janitor_2.2.1        \n#> [22] matrixStats_1.5.0     modelr_0.1.11         tibble_3.3.1         \n#> [25] dplyr_1.2.1           tidyr_1.3.2           rio_1.3.0            \n#> [28] here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8         tidyselect_1.2.1     farver_2.1.2        \n#>  [4] S7_0.2.2             fastmap_1.2.0        tensorA_0.36.2.1    \n#>  [7] digest_0.6.39        timechange_0.4.0     estimability_2.0.0  \n#> [10] lifecycle_1.0.5      magrittr_2.0.5       compiler_4.6.1      \n#> [13] rlang_1.3.0          tools_4.6.1          yaml_2.3.12         \n#> [16] knitr_1.51           labeling_0.4.3       bridgesampling_1.2-1\n#> [19] htmlwidgets_1.6.4    pkgbuild_1.4.8       curl_7.1.0          \n#> [22] RColorBrewer_1.1-3   abind_1.4-8          grid_4.6.1          \n#> [25] stats4_4.6.1         xtable_1.8-8         inline_0.3.21       \n#> [28] emmeans_2.0.4        scales_1.4.0         cli_3.6.6           \n#> [31] mvtnorm_1.4-2        rmarkdown_2.31       generics_0.1.4      \n#> [34] otel_0.2.0           RcppParallel_6.2.0   cachem_1.1.0        \n#> [37] stringr_1.6.0        splines_4.6.1        parallel_4.6.1      \n#> [40] vctrs_0.7.3          V8_8.2.0             Matrix_1.7-6        \n#> [43] jsonlite_2.0.0       arrayhelpers_1.1-2   glue_1.8.1          \n#> [46] codetools_0.2-20     distributional_0.8.1 lubridate_1.9.5     \n#> [49] stringi_1.8.9        gtable_0.3.6         QuickJSR_1.10.0     \n#> [52] pillar_1.11.1        htmltools_0.5.9      Brobdingnag_1.2-9   \n#> [55] R6_2.6.1             textshaping_1.0.5    rprojroot_2.1.1     \n#> [58] evaluate_1.0.5       lattice_0.22-9       backports_1.5.1     \n#> [61] memoise_2.0.1        broom_1.0.13         snakecase_0.11.1    \n#> [64] rstantools_2.7.0     coda_0.19-4.1        gridExtra_2.3.1     \n#> [67] nlme_3.1-170         checkmate_2.3.4      mgcv_1.9-4          \n#> [70] xfun_0.60            pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n\n",
    "supporting": [
      "02_effect_size_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}