{
  "hash": "ee793fcb54b363e0a8706d4319937f3f",
  "result": {
    "engine": "knitr",
    "markdown": "# La divergenza di Kullback-Leibler {#sec-kullback-leibler-divergence}\n\n## Introduzione {.unnumbered .unlisted}\n\nNel capitolo precedente abbiamo introdotto l'*entropia* come misura fondamentale dell'incertezza intrinseca a una distribuzione di probabilità. Ora compiamo un passo ulteriore: dall'incertezza di una singola distribuzione, passiamo a misurare *quanto una distribuzione si discosti da un'altra*.\n\nQuesto passaggio è cruciale, poiché tocca il cuore stesso della modellazione statistica. Costruire un modello, infatti, significa sostituire la distribuzione \"vera\" $P$, che ha generato i dati osservati, con un'approssimazione $Q$. Ma quanto è accurata questa sostituzione? E qual è il costo informativo che paghiamo usando $Q$ al posto di $P$?\n\nLa *divergenza di Kullback-Leibler* [@kullback1951information], indicata con $D_{\\text{KL}}$, fornisce una risposta formale a queste domande. Questa misura quantifica lo scarto informativo tra $P$ e $Q$, catturando l'inefficienza media che si verifica quando un modello imperfetto viene usato per rappresentare la realtà. In termini concreti, la divergenza KL risponde a una domanda operativa: \"Quanti bit di informazione perdiamo, in media, se usiamo la distribuzione $Q$ per codificare eventi che in realtà provengono da $P$?\"\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\n- L'entropia incrociata come ponte tra entropia e divergenza KL.\n- La definizione e l'interpretazione della divergenza KL.\n- Perché la KL non è simmetrica e cosa significa.\n- Come usare la KL per confrontare modelli statistici.\n- Il collegamento con gli strumenti pratici (LOO, ELPD) che vedremo nel prossimo capitolo.\n\n::: {.callout-tip collapse=true title=\"Prerequisiti\"}\n- Per comprendere appieno questo capitolo, dovresti aver già appreso i concetti di *entropia e informazione di Shannon* ([@sec-entropy-shannon-information]).\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n\n# Funzione per il calcolo dei termini della divergenza KL\nkl_terms <- function(p, q) {\n  stopifnot(length(p) == length(q))\n  non_zero <- p > 0 & q > 0\n  p <- p[non_zero]\n  q <- q[non_zero]\n  term <- p * log2(p / q)\n  data.frame(x = seq_along(p), p = p, q = q, term = term)\n}\n\n# Funzione compatta per il valore totale\nkl_divergence <- function(p, q) {\n  sum(kl_terms(p, q)$term)\n}\n\n# Entropia vera (in bit)\nentropy <- function(p) {\n  p <- p[p > 0]\n  -sum(p * log2(p))\n}\n\n# Entropia incrociata (in bit)\ncross_entropy <- function(p, q) {\n  non_zero <- p > 0 & q > 0\n  p <- p[non_zero]\n  q <- q[non_zero]\n  -sum(p * log2(q))\n}\n```\n:::\n\n:::\n\n## Il problema della generalizzabilità\n\nPrima di approfondire la definizione formale, è necessario comprendere il problema epistemologico che ha portato all'introduzione della divergenza KL. Uno degli scopi fondamentali del metodo scientifico è la *generalizzabilità*: un modello valido non solo deve spiegare i dati già osservati, ma deve anche possedere una solida capacità predittiva rispetto ai dati futuri.\n\nQuesto obiettivo genera una tensione metodologica ineludibile:\n\n- un modello **troppo semplice** tende a *sotto-adattarsi* ai dati (*underfitting*), fallendo nel cogliere le relazioni sistematiche e i pattern importanti presenti nei dati, e producendo previsioni inaffidabili e con scarso potere esplicativo.\n\n- un modello **troppo complesso** tende a *sovra-adattarsi* (*overfitting*), aderendo così perfettamente ai dati osservati da incorporare non solo le regolarità autentiche, ma anche il rumore statistico e le idiosincrasie del campione, compromettendo del tutto la sua capacità di generalizzare.\n\nCome quantificare questo compromesso? Come stabilire se un modello coglie la struttura genuina dei dati senza cadere nella trappola dell'adattamento al rumore campionario? La risposta risiede nel concetto di *distanza informativa* tra la rappresentazione del modello e la realtà del fenomeno, una distanza che la divergenza di Kullback-Leibler cattura in modo rigoroso.\n\n## Dall'entropia all'entropia incrociata\n\nPer comprendere la divergenza KL, dobbiamo prima introdurre un concetto intermedio fondamentale: l'*entropia incrociata* (*cross-entropy*).\n\n### Ricapitolazione: l'entropia come lunghezza di codifica ottimale\n\nCome stabilito in precedenza, l'entropia $H(P)$ di una distribuzione $P$ rappresenta la lunghezza media minima, in bit, richiesta per codificare in modo efficiente messaggi generati da $P$. Con una distribuzione nota, possiamo progettare un codice ottimale (ad esempio, mediante la codifica di Huffman) che si avvicina asintoticamente a questo limite teorico.\n\nFormalmente:\n$$\nH(P) = -\\sum_x p(x) \\log_2 p(x).\n$$\n\n### Il problema pratico: l'utilizzo di un codice subottimale\n\nNella pratica della ricerca, però, la distribuzione vera $P$ che genera i dati è spesso sconosciuta. Possediamo soltanto un modello approssimato $Q$ che riteniamo essere una sua ragionevole rappresentazione. Cosa succede, allora, se costruiamo un codice ottimizzato per $Q$ e lo usiamo per codificare messaggi che in realtà provengono da $P$?\n\nConsideriamo un esempio concreto. Immaginiamo che la distribuzione vera dei dati sia:\n\n- Evento A: probabilità 0.9 (estremamente frequente);\n- Evento B: probabilità 0.1 (relativamente raro).\n\nConoscendo $P$, costruiremmo un codice efficiente: un codice breve per A (es. `0`, 1 bit) e uno più lungo per B (es. `110`, 3 bit). Tuttavia, se operiamo sotto l'erronea convinzione che gli eventi siano equiprobabili ($Q$: A=0.5, B=0.5), assegneremmo codici di lunghezza simile a entrambi. Il risultato è uno spreco di risorse: assegniamo un codice eccessivamente lungo all'evento A, che invece si presenta molto frequentemente.\n\n### Definizione formale di entropia incrociata\n\nL'*entropia incrociata* $H(P, Q)$ quantifica proprio questa inefficienza. Essa rappresenta la lunghezza media del codice quando i messaggi sono generati dalla distribuzione vera $P$, ma il codice è ottimizzato per la distribuzione (potenzialmente errata) $Q$.\n\n$$\nH(P, Q) = -\\sum_x p(x) \\log_2 q(x).\n$$ {#eq-cross-entropy-def}\n\nSi osservi la struttura della formula: le probabilità sono pesate secondo $P$ (poiché i messaggi seguono effettivamente quella distribuzione), ma i logaritmi sono calcolati su $Q$ (poiché il codice è costruito in base a questa distribuzione).\n\n### Proprietà fondamentale dell'entropia incrociata\n\nUna proprietà matematica cruciale dell'entropia incrociata è la sua relazione con l'entropia della distribuzione vera:\n$$\nH(P, Q) \\geq H(P),\n$$\ndove l'uguaglianza vale se e solo se $P = Q$.\n\n**Interpretazione operativa:**\n\n- quando $Q = P$, utilizziamo il codice ottimale e e non stiamo sprecando alcun bit: $H(P, P) = H(P)$;\n- quando $Q \\neq P$, stiamo utilizzando un codice subottimale che assegna lunghezze non ideali agli eventi: $H(P, Q) > H(P)$;\n- la differenza $H(P, Q) - H(P)$ quantifica quindi lo *spreco informativo* imputabile all'uso di un modello imperfetto.\n\nQuesta proprietà fissa un limite inferiore prestazionale: nessuna strategia di codifica può superare l'efficienza del codice ottimale basato sulla piena conoscenza di $P$. In definitiva, l'entropia incrociata misura il *costo della nostra ignoranza*, ovvero il prezzo in bit aggiuntivi che paghiamo a causa di una comprensione imperfetta del processo sottostante.\n\n::: {#example-cross-entropy .callout .exercise collapse=\"true\" collapsed=\"true\"}\n#### Esempio numerico: entropia incrociata\n\nConsideriamo la distribuzione vera $P = [0.9, 0.1]$ e il modello errato $Q = [0.5, 0.5]$.\n\n**Entropia vera:**\n$$\nH(P) = -0.9 \\log_2(0.9) - 0.1 \\log_2(0.1) \\approx 0.469 \\text{ bit}\n$$\n\n**Entropia incrociata:**\n$$\nH(P, Q) = -0.9 \\log_2(0.5) - 0.1 \\log_2(0.5) = -\\log_2(0.5) = 1 \\text{ bit}\n$$\n\n**Interpretazione:** con il codice ottimale per $P$, servirebbe in media 0.469 bit per messaggio. Usando il codice (sbagliato) ottimizzato per $Q$, ne servono 1 bit, ovvero più del doppio. La differenza, $1 - 0.469 = 0.531$ bit, è lo \"spreco informativo\" dovuto all'uso di un modello imperfetto.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nP <- c(0.9, 0.1)\nQ <- c(0.5, 0.5)\n\ncat(\"Entropia H(P):\", round(entropy(P), 3), \"bit\\n\")\n#> Entropia H(P): 0.469 bit\ncat(\"Entropia incrociata H(P,Q):\", round(cross_entropy(P, Q), 3), \"bit\\n\")\n#> Entropia incrociata H(P,Q): 1 bit\ncat(\"Spreco informativo:\", round(cross_entropy(P, Q) - entropy(P), 3), \"bit\\n\")\n#> Spreco informativo: 0.531 bit\n```\n:::\n\n:::\n\n## La divergenza di Kullback-Leibler\n\n### Definizione formale\n\nLa *divergenza di Kullback-Leibler* (KL) quantifica precisamente la perdita informativa che abbiamo identificato: essa rappresenta la differenza tra il costo della nostra approssimazione (ovvero, l'entropia incrociata) e il costo della verità (ovvero, l'entropia vera della distribuzione).\n\n$$\nD_{\\text{KL}}(P \\parallel Q) = H(P, Q) - H(P).\n$$ {#eq-kl-as-difference}\n\nSviluppando le definizioni di entropia incrociata ed entropia, otteniamo:\n\n$$\nD_{\\text{KL}}(P \\parallel Q) = -\\sum_x p(x) \\log_2 q(x) - \\left( -\\sum_x p(x) \\log_2 p(x) \\right).\n$$\n\nCombinando i due termini, arriviamo alla forma canonica, che rivela il cuore del confronto tra le due distribuzioni:\n\n$$\nD_{\\text{KL}}(P \\parallel Q) = \\sum_x p(x) \\log_2 \\frac{p(x)}{q(x)}.\n$$ {#eq-kl-div-def}\n\n### Tre prospettive interpretative\n\nLa divergenza KL può essere interpretata in tre modi complementari, ciascuno dei quali illustra un aspetto diverso del suo significato:\n\n**1. Inefficienza di codifica.** \nLa $D_{\\text{KL}}$ quantifica il numero medio di bit *aggiuntivi* necessari per codificare messaggi provenienti da $P$ quando si utilizza un codice ottimizzato per $Q$. Questa interpretazione operativa collega direttamente la teoria dell'informazione alla pratica della compressione dati.\n\n**2. Eccesso di sorpresa.** \nQuesta prospettiva misura il disallineamento tra la sorpresa che effettivamente proviamo osservando il mondo (governato da $P$) e la sorpresa che il nostro modello $Q$ si aspetterebbe. Se $Q$ è un'approssimazione imperfetta, rimarremo sistematicamente più sorpresi (o meno sorpresi) di quanto previsto. La $D_{\\text{KL}}$ quantifica proprio il valore atteso di questo \"eccesso di sorpresa\n\n**3. Perdita informativa.** \nLa $D_{\\text{KL}}$ quantifica l'informazione che viene persa quando tentiamo di descrivere la realtà $P$ attraverso l'approssimazione $Q$. Questa prospettiva è particolarmente rilevante nella modellizzazione statistica, poiché misura direttamente l'inadeguatezza di un modello nel rappresentare la struttura essenziale del fenomeno studiato.\n\n### Proprietà matematiche fondamentali\n\nLa $D_{\\text{KL}}$ possiede un insieme di proprietà matematiche che ne definiscono il comportamento e ne guidano l'applicazione pratica.\n\n**Non-negatività.** \nPer ogni coppia di distribuzioni $P$ e $Q$, vale $D_{\\text{KL}}(P \\parallel Q) \\geq 0$. L'uguaglianza $D_{\\text{KL}}(P \\parallel Q) = 0$ si verifica se e solo se $P = Q$. Questa proprietà conferma un'intuizione fondamentale: non esiste un \"modello sbagliato\" che sia più efficiente della verità. Qualsiasi approssimazione della distribuzione reale introduce inevitabilmente un costo informativo.\n\n**Asimmetria.** \nLa $D_{\\text{KL}}$ è intrinsecamente asimmetrica: $D_{\\text{KL}}(P \\parallel Q) \\neq D_{\\text{KL}}(Q \\parallel P)$. Questa non commutatività non è un semplice dettaglio tecnico, ma riflette una differenza sostanziale nel modo in cui valutiamo l'errore del modello:\n\n- $D_{\\text{KL}}(P \\parallel Q)$ (la \"divergenza in avanti\") penalizza severamente il modello $Q$ quando assegna una bassa probabilità a un evento che, secondo $P$, è invece frequente. Si tratta di una misura dell'\"orrore per gli errori su ciò che è importante\";\n- al contrario, la \"divergenza all'indietro\" ($D_{\\text{KL}}(Q \\parallel P)$) penalizza il modello $Q$ quando prevede come possibile un evento che, secondo $P$, è impossibile. È una misura dell'\"orrore per l'invenzione di fatti inesistenti\".\n\n**Invarianza per trasformazioni invertibili.** \nLa $D_{\\text{KL}}$ rimane invariata quando applichiamo trasformazioni reversibili ai dati. Per esempio, se trasformiamo i dati da centimetri a pollici (una conversione reversibile), il valore della $D_{\\text{KL}}$ non cambia. Questa proprietà garantisce che la misura sia intrinseca alla relazione tra le distribuzioni e non dipenda dalla rappresentazione specifica dei dati.\n\n**Dipendenza dalla base logaritmica.** \nIl valore numerico della divergenza KL dipende dalla base del logaritmo utilizzato nella sua definizione. L'uso del logaritmo in base 2 restituisce un valore in *bit*, interpretabile come un costo di codifica. L'uso del logaritmo naturale, invece, fornisce un risultato in *nat*. Sebbene il valore assoluto cambi, la scelta della base è inessenziale per le comparazioni qualitative, poiché le due misure differiscono solo per un fattore di scala costante.\n\n**Non è una metrica.** \nNonostante il nome \"divergenza\" possa suggerire il contrario, la $D_{\\text{KL}}$ non è una distanza matematica (una metrica). Essa infatti viola due proprietà fondamentali: non è simmetrica e non soddisfa la disuguaglianza triangolare (secondo cui la distanza diretta tra due punti non può essere maggiore della somma delle distanze attraverso un punto intermedio). Per questo motivo, va interpretata non come una \"distanza\" tra $P$ e $Q$, ma piuttosto come una misura *direzionale* di disaccordo, che quantifica il costo di usare $Q$ per approssimare $P$.\n\n## Perché la KL non è simmetrica\n\nL'asimmetria della divergenza KL è una delle sue caratteristiche più profonde e, a prima vista, sorprendenti. Tuttavia, lungi dall'essere una stranezza matematica, essa coglie una verità fondamentale della modellazione statistica: la direzione dell'errore è importante. Confrontare un modello con la realtà non è come confrontare due punti su una mappa: si tratta di un'operazione intrinsecamente direzionale che riflette il costo asimmetrico dei nostri errori.\n\n### Due domande fondamentali, due risposte diverse\n\nLa scelta dell'ordine degli argomenti in $D_{\\text{KL}}(P \\parallel Q)$ corrisponde a porre due domande radicalmente diverse:\n\n- **$D_{\\text{KL}}(P \\parallel Q)$** chiede: \"Qual è il costo di *agire* nella realtà $P$ credendo che sia $Q$?\"\n- **$D_{\\text{KL}}(Q \\parallel P)$** chiede: \"Qual è il costo di *agire* nella realtà $Q$ credendo che sia $P$?\"\n\nNella ricerca scientifica, solo la prima domanda è pertinente. Noi operiamo in un universo governato dalla distribuzione vera $P$ (anche se ignota) e abbiamo a disposizione solo un modello approssimato $Q$. Il nostro obiettivo è quantificare il prezzo di questa comprensione imperfetta.\n\n### Un caso di studio: il modello troppo semplice\n\nConsideriamo uno scenario emblematico:\n\n- **$P = [0.9, 0.1]$** — La realtà: un evento comune e uno raro;\n- **$Q = [0.5, 0.5]$** — Il nostro modello: un'ipotesi ingenua di equiprobabilità.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nP <- c(0.9, 0.1)\nQ <- c(0.5, 0.5)\n\nkl_PQ <- kl_divergence(P, Q)\nkl_QP <- kl_divergence(Q, P)\n\ncat(\"D_KL(P || Q) =\", round(kl_PQ, 3), \"bit\\n\")\n#> D_KL(P || Q) = 0.531 bit\ncat(\"D_KL(Q || P) =\", round(kl_QP, 3), \"bit\\n\")\n#> D_KL(Q || P) = 0.737 bit\n```\n:::\n\n\n**Interpretazione dei risultati:**\n\n- **$D_{\\text{KL}}(P \\parallel Q) \\approx 0.531$ bit**: questo è il costo reale del nostro errore. Poiché il modello $Q$ assegna una probabilità inadeguatamente bassa (0.5) all'evento più frequente (che in realtà ha probabilità 0.9), siamo costretti a utilizzare un codice inefficiente e a sprecare risorse per un evento che si verifica spesso. È il costo della *sottostima*.\n\n- **$D_{\\text{KL}}(Q \\parallel P) \\approx 0.368$ bit**: questo valore descrive uno scenario controfattuale. Se il mondo fosse realmente equiprobabile ($Q$) ma noi usassimo il modello $P$, l'inefficienza sarebbe minore. Il modello $P$, sebbene errato, assegna comunque un'alta probabilità a un evento che in questo scenario ipotetico si verifica nel 50% dei casi. È il costo della *sovrastima*.\n\n### La regola asimmetrica degli errori\n\nLa discrepanza quantitativa svela un principio generale: **sottostimare un evento frequente è un errore più grave che sovrastimarlo**.\n\nNel nostro esempio, il modello $Q$ commette l'errore fondamentale di considerare un evento comune (90%) come se fosse solo moderatamente probabile (50%). Questo fraintendimento fondamentale ha un costo elevato perché si paga ripetutamente. Al contrario, sovrastimare un evento frequente ha un costo minore, perché un modello che assegna un'alta probabilità a eventi che si verificano effettivamente spesso non può essere totalmente fuori strada.\n\n### Visualizzazione dell'asimmetria\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndf <- data.frame(\n  evento = c(\"Evento 1\", \"Evento 2\"),\n  P = c(0.9, 0.1),\n  Q = c(0.5, 0.5)\n)\n\ndf_long <- pivot_longer(df, cols = c(P, Q), names_to = \"Distribuzione\", values_to = \"Probabilità\")\n\nggplot(df_long, aes(x = evento, y = Probabilità, fill = Distribuzione)) +\n  geom_col(position = \"dodge\", width = 0.6) +\n  labs(\n    title = \"Asimmetria della divergenza KL\",\n    subtitle = sprintf(\"D_KL(P||Q) = %.3f bit   |   D_KL(Q||P) = %.3f bit\", kl_PQ, kl_QP),\n    x = \"Evento\", \n    y = \"Probabilità\",\n    caption = \"Sottostimare eventi frequenti (P→Q) costa più che sovrastimarli (Q→P)\"\n  ) +\n  scale_fill_manual(values = c(\"P\" = \"#2c7bb6\", \"Q\" = \"#d7191c\")) +\n  theme_minimal() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![Confronto tra la distribuzione vera $P$ e il modello $Q$. La differenza tra $D_{\\text{KL}}(P \\parallel Q)$ e $D_{\\text{KL}}(Q \\parallel P)$ evidenzia la natura direzionale della divergenza KL: il costo di una ipotesi semplificata $Q$ sulla realtà complessa $P$ è maggiore del costo inverso.](02_kl_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nL'asimmetria della KL non è un'imperfezione da correggere, ma una caratteristica che la rende particolarmente adatta a misurare la qualità dei modelli statistici: nel confronto tra modello e realtà, infatti, la direzione dell'errore determina la gravità delle sue conseguenze. È proprio questa sensibilità al contesto che rende la divergenza KL uno strumento così potente e appropriato per valutare l'adeguatezza dei modelli scientifici.\n\n## Calcolo dettagliato della divergenza KL\n\nPer consolidare la comprensione, esaminiamo il calcolo della divergenza KL attraverso due esempi articolati. Questa analisi passo dopo passo rivela come i singoli contributi degli eventi si combinano per quantificare il costo complessivo di un modello imperfetto.\n\n::: {.callout-note collapse=\"true\" title=\"Esempio 1: scomposizione dei contributi eventi-specifici\"}\nConsideriamo una variabile categoriale con tre possibili esiti:\n\n| Esito | $P$ (distribuzione vera) | $Q$ (modello) |\n|-------|------------|---------------|\n| A     | 0.5        | 0.4           |\n| B     | 0.3        | 0.4           |\n| C     | 0.2        | 0.2           |\n\n**Passo 1: Calcolo dei rapporti di verosimiglianza**\n\nCalcoliamo per ogni esito il rapporto $\\frac{p(x)}{q(x)}$, che misura quanto la realtà \"supera\" la previsione del modello:\n\n- A: $\\frac{0.5}{0.4} = 1.25$ (sottostima del modello);\n- B: $\\frac{0.3}{0.4} = 0.75$ (sovrastima del modello);\n- C: $\\frac{0.2}{0.2} = 1.00$ (perfetta calibrazione).\n\n**Passo 2: Conversione in \"sorpresa relativa\"**\n\nApplichiamo il logaritmo in base 2 per trasformare i rapporti in una misura additiva (bit):\n\n- A: $\\log_2(1.25) \\approx 0.322$ bit (sorpresa aggiuntiva);\n- B: $\\log_2(0.75) \\approx -0.415$ bit (sorpresa ridotta);\n- C: $\\log_2(1.00) = 0$ bit (nessuna discrepanza).\n\n**Passo 3: Ponderazione per la frequenza reale**\n\nMoltiplichiamo ciascun valore per la probabilità effettiva in $P$, ottenendo il contributo medio di ogni evento:\n\n- A: $0.5 \\times 0.322 = 0.161$ bit (contributo positivo significativo);\n- B: $0.3 \\times (-0.415) = -0.125$ bit (contributo negativo modesto);\n- C: $0.2 \\times 0 = 0$ bit (nessun contributo).\n\n**Passo 4: Somma algebrica dei contributi**\n\n$$\nD_{\\text{KL}}(P \\parallel Q) = 0.161 - 0.125 + 0 = 0.036 \\text{ bit}.\n$$\n\n**Interpretazione dei singoli contributi:**\n\n- **Esito A**: il modello sottostima drasticamente un evento frequente (50% di occorrenze). Questo produce un costo informativo sostanziale, poiché l'inefficienza di codifica si manifesta molto spesso.\n- **Esito B**: il modello sovrastima un evento meno frequente (30%). Sebbene questo produca un apparente \"risparmio\" di sorpresa, il beneficio è limitato dalla minore frequenza dell'evento.\n- **Esito C**: calibrazione perfetta: nessun costo aggiuntivo.\n\nIl valore complessivo di 0.036 bit indica una discrepanza informativa molto contenuta, coerente con il fatto che le due distribuzioni sono qualitativamente simili.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nP <- c(0.5, 0.3, 0.2)\nQ <- c(0.4, 0.4, 0.2)\n\n# Calcolo dettagliato\ndf <- data.frame(\n  esito = c(\"A\", \"B\", \"C\"),\n  p = P,\n  q = Q,\n  rapporto = P / Q,\n  log_rapporto = log2(P / Q),\n  contributo = P * log2(P / Q)\n)\n\nprint(df)\n#>   esito   p   q rapporto log_rapporto contributo\n#> 1     A 0.5 0.4     1.25        0.322      0.161\n#> 2     B 0.3 0.4     0.75       -0.415     -0.125\n#> 3     C 0.2 0.2     1.00        0.000      0.000\ncat(\"\\nDivergenza KL totale:\", round(sum(df$contributo), 4), \"bit\\n\")\n#> \n#> Divergenza KL totale: 0.0365 bit\n```\n:::\n\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Esempio 2: verifica della coerenza matematica\"}\nEsaminiamo ora un secondo caso con $P = [0.1, 0.6, 0.3]$ e $Q = [0.2, 0.5, 0.3]$ per verificare la coerenza tra le diverse definizioni della divergenza KL.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nP <- c(0.1, 0.6, 0.3)\nQ <- c(0.2, 0.5, 0.3)\n\n# Calcolo dei singoli termini della divergenza KL\ndf_kl <- data.frame(\n  esito = c(\"A\", \"B\", \"C\"),\n  p = P,\n  q = Q,\n  rapporto = P / Q,\n  log_rapporto = log2(P / Q),\n  contributo = P * log2(P / Q)\n)\n\nprint(df_kl)\n#>   esito   p   q rapporto log_rapporto contributo\n#> 1     A 0.1 0.2      0.5       -1.000     -0.100\n#> 2     B 0.6 0.5      1.2        0.263      0.158\n#> 3     C 0.3 0.3      1.0        0.000      0.000\n\n# Divergenza totale\ncat(\"\\nDivergenza KL calcolata direttamente:\", \n    round(sum(df_kl$contributo), 4), \"bit\\n\")\n#> \n#> Divergenza KL calcolata direttamente: 0.0578 bit\n\n# Verifica attraverso la relazione D_KL = H(P,Q) - H(P)\nH_cross <- -sum(P * log2(Q))  # Entropia incrociata\nH_P <- -sum(P * log2(P))      # Entropia di P\n\ncat(\"Verifica (H(P,Q) - H(P)):\", \n    round(H_cross - H_P, 4), \"bit\\n\")\n#> Verifica (H(P,Q) - H(P)): 0.0578 bit\n```\n:::\n\n\nLa perfetta uguaglianza dei due risultati conferma la relazione fondamentale $D_{\\text{KL}}(P \\parallel Q) = H(P,Q) - H(P)$, dimostrando la coerenza matematica tra la definizione della divergenza KL e il suo significato operativo in termini di codifica.\n:::\n\n**Osservazione fondamentale**: Sebbene singoli eventi possano generare contributi negativi alla divergenza (quando il modello sovrastima la loro probabilità), la somma totale è sempre non negativa. Questo principio matematico riflette una verità profonda: nessun modello imperfetto può produrre, nel complesso, un guadagno di efficienza rispetto alla conoscenza perfetta della distribuzione generatrice. I \"risparmi\" locali sono sempre superati dai costi globali degli errori di modellazione.\n\n## La divergenza KL nella selezione dei modelli\n\n### Il principio fondamentale: la ricerca dell'approssimazione più fedele\n\nPossiamo ora formulare il principio cardinale per la selezione dei modelli statistici: **tra tutti i modelli candidati, quello migliore è quello che minimizza la divergenza KL dalla distribuzione vera dei dati**:\n\n$$\nQ_{\\text{ottimale}} = \\arg\\min_{Q} D_{\\text{KL}}(P \\parallel Q).\n$$\n\nQuesto principio ha un profondo significato epistemologico: stiamo cercando il modello che, tra tutte le approssimazioni possibili, spreca meno informazione, genera meno sorpresa inattesa e cattura più fedelmente la struttura sottostante della realtà che stiamo studiando.\n\n### Il paradosso pratico\n\nTuttavia, questo principio ci pone di fronte a un paradosso apparentemente insormontabile: **come possiamo minimizzare la distanza da $P$ se $P$ è proprio ciò che non conosciamo?** La distribuzione vera che ha generato i dati è l'incognita fondamentale che il nostro modello cerca di stimare. Sembrerebbe un circolo vizioso: per trovare il miglior modello dobbiamo conoscere la realtà, ma per conoscere la realtà abbiamo bisogno di un buon modello.\n\n### La soluzione elegante: eliminare l'incognita\n\nLa via d'uscita da questo paradosso risiede in un'osservazione matematica cruciale. Scomponiamo la divergenza KL:\n\n$$\nD_{\\text{KL}}(P \\parallel Q) = H(P, Q) - H(P).\n$$\n\nIl termine $H(P)$, ovvero l'entropia della distribuzione vera, rappresenta l'incertezza intrinseca e irriducibile dei dati. È un valore fisso del mondo, che nessun modello potrà mai eliminare.\n\nQuando confrontiamo due modelli $Q_1$ e $Q_2$, calcoliamo:\n\n$$\n\\begin{aligned}\n&D_{\\text{KL}}(P \\parallel Q_1) - D_{\\text{KL}}(P \\parallel Q_2) \\\\\n&= [H(P, Q_1) - H(P)] - [H(P, Q_2) - H(P)] \\\\\n&= H(P, Q_1) - H(P, Q_2).\n\\end{aligned}\n$$\n\n**Il termine costante $H(P)$ si cancella completamente.** Questo risultato cruciale significa che **per confrontare i modelli tra loro, non è necessario conoscere la distribuzione vera $P$**: è sufficiente confrontare le loro entropie incrociate.\n\n### Dalla teoria alla pratica: la stima empirica\n\nL'entropia incrociata $H(P, Q) = -\\mathbb{E}_P[\\log_2 q(X)]$ può essere stimata empiricamente dai dati osservati. Dato un campione $(x_1, x_2, \\ldots, x_n)$ proveniente da $P$, abbiamo:\n\n$$\nH(P, Q) \\approx -\\frac{1}{n} \\sum_{i=1}^n \\log_2 q(x_i).\n$$\n\nQuesto principio fondamentale è alla base degli strumenti più potenti della statistica moderna:\n\n- **Log-score**: misura la performance predittiva di un modello quantificando la sorpresa (o log-verosimiglianza) associata a ciascuna osservazione sulla base delle probabilità previste dal modello. Un log-score più alto (meno negativo) indica previsioni meglio calibrate;\n- **ELPD** (*Expected Log Predictive Density*): stima la performance predittiva attesa del modello su nuovi dati;\n- **LOO-CV** (*Leave-One-Out Cross-Validation*): approssima efficientemente l'ELPD utilizzando i dati disponibili.\n\nNel prossimo capitolo esploreremo come questi strumenti implementino concretamente il principio della minimizzazione della divergenza KL.\n\n### Visualizzazione: confronto tra modelli candidati\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Distribuzione vera (ignota in pratica)\nP <- c(0.1, 0.3, 0.4, 0.2)\n\n# Due modelli candidati\nQ1 <- c(0.15, 0.25, 0.40, 0.20)  # buona approssimazione\nQ2 <- c(0.25, 0.25, 0.25, 0.25)  # distribuzione uniforme (modello naive)\n\n# Calcolo delle divergenze KL\nkl_1 <- kl_divergence(P, Q1)\nkl_2 <- kl_divergence(P, Q2)\n\n# Preparazione dati per la visualizzazione\ndf <- data.frame(\n  esito = rep(c(\"A\", \"B\", \"C\", \"D\"), 3),\n  distribuzione = rep(c(\"P (vera)\", \"Q1 (buona approssimazione)\", \"Q2 (modello uniforme)\"), each = 4),\n  probabilità = c(P, Q1, Q2)\n)\n\nggplot(df, aes(x = esito, y = probabilità, fill = distribuzione)) +\n  geom_col(position = \"dodge\", width = 0.7) +\n  labs(\n    title = \"Selezione del modello basata sulla divergenza KL\",\n    subtitle = sprintf(\"D_KL(P||Q1) = %.3f bit   |   D_KL(P||Q2) = %.3f bit\", kl_1, kl_2),\n    x = \"Esito\", \n    y = \"Probabilità\", \n    fill = \"Distribuzione\",\n    caption = \"Il modello Q1 minimizza la divergenza KL, catturando meglio la struttura di P\"\n  ) +\n  scale_fill_manual(values = c(\"P (vera)\" = \"#2c7bb6\", \n                               \"Q1 (buona approssimazione)\" = \"#1a9641\", \n                               \"Q2 (modello uniforme)\" = \"#d7191c\")) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Confronto tra due modelli candidati rispetto alla distribuzione vera $P$. Il modello $Q1$, con divergenza KL minore, dimostra una capacità superiore di aderire alla struttura sottostante dei dati.](02_kl_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nIl modello $Q_1$, con la sua minore divergenza KL, dimostra di aver colto le principali regolarità della distribuzione vera $P$. Assegna probabilità più elevate agli eventi effettivamente frequenti e riduce quelle degli eventi rari. Al contrario, il modello uniforme $Q_2$ fallisce nel riconoscere le asimmetrie fondamentali dei dati, pagando un prezzo informativo notevolmente più alto a causa della sua ingenua semplicità.\n\n## Esempio psicologico: modelli per l'ansia\n\nPer ancorare questi concetti astratti alla pratica della ricerca, consideriamo un tipico scenario di modellazione in psicologia clinica.\n\n### Il contesto di ricerca\n\nUno psicologo clinico vuole sviluppare un modello per prevedere il livello di ansia settimanale degli studenti universitari durante il periodo degli esami. Dopo aver raccolto dati osservativi, intende confrontare due modelli concorrenti:\n\n- **Modello A** (parsimonioso): utilizza esclusivamente il punteggio di *coping* come predittore;\n- **Modello B** (complessivo): integra sia il *coping* che il *supporto sociale percepito*.\n\n### Simulazione dei risultati\n\nSupponiamo che la distribuzione vera dell'ansia (categorizzata in bassa, media, alta) nella popolazione target sia:\n$$\nP = [0.30, 0.45, 0.25]\n$$\n\nIl Modello A, basato unicamente sul coping, produce le seguenti previsioni:\n$$\nQ_A = [0.35, 0.40, 0.25]\n$$\n\nIl Modello B, che incorpora anche il supporto sociale, genera:\n$$\nQ_B = [0.32, 0.43, 0.25]\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nP  <- c(0.30, 0.45, 0.25)\nQA <- c(0.35, 0.40, 0.25)\nQB <- c(0.32, 0.43, 0.25)\n\nkl_A <- kl_divergence(P, QA)\nkl_B <- kl_divergence(P, QB)\n\ncat(\"Divergenza KL - Modello A (solo coping):\", round(kl_A, 4), \"bit\\n\")\n#> Divergenza KL - Modello A (solo coping): 0.0097 bit\ncat(\"Divergenza KL - Modello B (coping + supporto):\", round(kl_B, 4), \"bit\\n\")\n#> Divergenza KL - Modello B (coping + supporto): 0.0016 bit\ncat(\"\\nDifferenza:\", round(kl_A - kl_B, 4), \"bit a favore del Modello B\\n\")\n#> \n#> Differenza: 0.0082 bit a favore del Modello B\n```\n:::\n\n\n### Interpretazione dei risultati\n\nIl Modello B presenta una divergenza KL leggermente inferiore (0.0033 bit), indicando che le sue previsioni si avvicinano di più alla distribuzione vera osservata nei dati. Tuttavia, il miglioramento è quantitativamente modesto (circa 0.003 bit per osservazione).\n\nQuesto risultato solleva una questione metodologica cruciale: **il marginale guadagno predittivo giustifica l'aggiunta di complessità al modello?**\n\n**Considerazioni a favore del Modello B:**\n\n- maggiore accuratezza predittiva, seppur minima;\n- fondamento teorico più ricco, includendo un costrutto psicosociale consolidato;\n- potenziale di performance superiore in sottogruppi specifici.\n\n**Considerazioni a favore del Modello A:**\n\n- maggiore parsimonia e trasparenza interpretativa;\n- minore rischio di sovradattamento, specialmente con campioni di dimensioni limitate;\n- più agevole implementazione in contesti applicativi con risorse limitate.\n\n### Visualizzazione del confronto\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndf <- data.frame(\n  livello_ansia = rep(c(\"Bassa\", \"Media\", \"Alta\"), 3),\n  modello = rep(c(\"Distribuzione Vera P\", \"Modello A (coping)\", \"Modello B (coping + supporto)\"), each = 3),\n  probabilita = c(P, QA, QB)\n)\n\nggplot(df, aes(x = livello_ansia, y = probabilita, fill = modello)) +\n  geom_col(position = \"dodge\", width = 0.7) +\n  labs(\n    title = \"Confronto di modelli predittivi per l'ansia\",\n    subtitle = sprintf(\"D_KL(P||A) = %.4f bit vs D_KL(P||B) = %.4f bit\", kl_A, kl_B),\n    x = \"Livello di Ansia\", \n    y = \"Probabilità\",\n    caption = \"Il Modello B mostra un leggero vantaggio predittivo, ma il guadagno è modesto\"\n  ) +\n  scale_fill_manual(values = c(\"Distribuzione Vera P\" = \"#2c7bb6\", \n                               \"Modello A (coping)\" = \"#fdae61\", \n                               \"Modello B (coping + supporto)\" = \"#1a9641\")) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Confronto tra i due modelli predittivi dell'ansia. Entrambi i modelli approssimano ragionevolmente la distribuzione vera, con il Modello B che mostra un vantaggio marginale.](02_kl_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n### Il dilemma fondamentale: complessità versus parsimonia\n\nQuesto esempio illustra il *trade-off* che i ricercatori devono affrontare costantemente: il principio di parsimonia (il \"rasoio di Occam\") suggerisce di preferire il modello più semplice a parità di prestazioni predittive. Tuttavia, stabilire quando un miglioramento predittivo, per quanto modesto, sia \"sufficientemente sostanziale\" da giustificare una maggiore complessità rimane una delle sfide più delicate nella scienza dei dati.\n\nNel prossimo capitolo esploreremo come gli strumenti statistici avanzati, quali la validazione incrociata *leave-one-out* (LOO-CV) e l'*Expected Log Predictive Density* (ELPD), permettano di quantificare sistematicamente questo compromesso, considerando non solo la performance media, ma anche l'incertezza delle stime. Ciò consente di effettuare scelte metodologicamente fondate nella selezione dei modelli.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIn questo capitolo abbiamo sviluppato la *divergenza di Kullback-Leibler* come strumento fondamentale per quantificare il divario tra rappresentazione e realtà nella modellazione statistica.\n\n### Concetti chiave {.unnumbered .unlisted}\n\nL'**entropia incrociata** $H(P,Q)$ misura la lunghezza media del codice quando si utilizza un modello $Q$ per rappresentare dati provenienti da $P$. Poiché questa quantità è sempre maggiore o uguale all'entropia $H(P)$, essa stabilisce che nessuna strategia basata su $Q$ può superare l'efficienza del codice ottimale per $P$.\n\nLa **divergenza KL** quantifica la differenza $H(P,Q) - H(P)$, rappresentando lo spreco informativo dovuto all'uso di un modello imperfetto. Le sue tre interpretazioni, come inefficienza di codifica, eccesso di sorpresa e perdita informativa, convergono nello stesso principio fondamentale: ogni approssimazione della realtà ha un costo e la divergenza KL lo quantifica precisamente.\n\nL'**asimmetria** della divergenza KL riflette la natura direzionale del processo di modellazione: siamo interessati a misurare quanto il modello $Q$ approssimi la realtà $P$, non il contrario. \n\nNel **confronto tra modelli alternativi** non è necessario conoscere la distribuzione vera $P$: il termine costante $H(P)$, che rappresenta l'incertezza intrinseca del fenomeno, si annulla nel confronto tra entropie incrociate.\n\n### Il ponte verso il prossimo capitolo {.unnumbered .unlisted}\n\nLa divergenza KL fornisce un criterio teorico elegante per la selezione dei modelli: il modello migliore è quello che minimizza $D_{\\text{KL}}(P \\parallel Q)$. Come abbiamo visto, per confrontare modelli tra loro non è necessario conoscere la distribuzione vera $P$, poiché basta confrontare le loro entropie incrociate. Tuttavia, l'applicazione pratica di questo principio deve affrontare tre sfide fondamentali.\n\n* In primo luogo, sebbene il termine $H(P)$ si annulli nei confronti, dobbiamo comunque stimare l'entropia incrociata $H(P,Q)$ in modo affidabile a partire da un insieme di dati finiti e potenzialmente rumorosi.\n* In secondo luogo, la stima basata sullo stesso campione utilizzato per adattare il modello è tendenzialmente troppo ottimistica: un modello più complesso apparirà sempre migliore se valutato sui dati che già \"conosce\".\n* Infine, dobbiamo quantificare l'incertezza delle nostre stime per distinguere i miglioramenti predittivi sostanziali dalle fluttuazioni campionarie.\n\nNel prossimo capitolo esploreremo come la **LOO-CV** (*Leave-One-Out Cross-Validation*) e l'**ELPD** (*Expected Log Predictive Density*) affrontino queste sfide, trasformando il principio astratto della minimizzazione della $D_{\\text{KL}}$ in uno strumento operativo per la selezione dei modelli nella ricerca psicologica.\n\n::: {.callout-important title=\"Esercizi\" collapse=\"true\"}\n1. Consideriamo due distribuzioni discrete:\n\n```\np <- c(0.2, 0.5, 0.3)\nq <- c(0.1, 0.2, 0.7)\n```\n\nCalcolare: (a) l'entropia di $p$, (b) l'entropia incrociata $H(p,q)$, (c) la divergenza KL da $p$ a $q$.\n\nRipetere con `q = c(0.2, 0.55, 0.25)` e confrontare i risultati.\n\n2. Sia $p$ la distribuzione binomiale con $\\theta = 0.2$ e $n = 5$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np <- dbinom(0:5, size = 5, prob = 0.2)\nround(p, 3)\n#> [1] 0.328 0.410 0.205 0.051 0.006 0.000\n```\n:::\n\n\nConfrontare due approssimazioni:\n\n- `q1 = c(0.328, 0.410, 0.205, 0.051, 0.006, 0.000)` (approssimazione ragionevole)\n- `q2 = rep(1/6, 6)` (distribuzione uniforme)\n\nQuale approssimazione è migliore secondo la divergenza KL?\n\n3. Dimostrare numericamente l'asimmetria della KL calcolando $D_{\\text{KL}}(P \\parallel Q)$ e $D_{\\text{KL}}(Q \\parallel P)$ per $P = [0.7, 0.2, 0.1]$ e $Q = [0.4, 0.3, 0.3]$.\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.5.2 (2025-10-31)\n#> Platform: aarch64-apple-darwin20\n#> Running under: macOS Tahoe 26.1\n#> \n#> Matrix products: default\n#> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.0            tinytable_0.15.1      withr_3.0.2          \n#>  [4] systemfonts_1.3.1     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.14.0      ggplot2_4.0.1        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.6.1      \n#> [13] loo_2.8.0             rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.0           Rcpp_1.1.0            sessioninfo_1.2.3    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.0          dplyr_1.1.4          \n#> [25] tidyr_1.3.1           rio_1.2.4             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.1              fastmap_1.2.0         TH.data_1.1-5        \n#>  [7] tensorA_0.36.2.1      digest_0.6.39         timechange_0.3.0     \n#> [10] estimability_1.5.1    lifecycle_1.0.4       survival_3.8-3       \n#> [13] magrittr_2.0.4        compiler_4.5.2        rlang_1.1.6          \n#> [16] tools_4.5.2           yaml_2.3.10           knitr_1.50           \n#> [19] labeling_0.4.3        bridgesampling_1.2-1  htmlwidgets_1.6.4    \n#> [22] curl_7.0.0            pkgbuild_1.4.8        RColorBrewer_1.1-3   \n#> [25] abind_1.4-8           multcomp_1.4-29       purrr_1.2.0          \n#> [28] grid_4.5.2            stats4_4.5.2          colorspace_2.1-2     \n#> [31] xtable_1.8-4          inline_0.3.21         emmeans_2.0.0        \n#> [34] scales_1.4.0          MASS_7.3-65           cli_3.6.5            \n#> [37] mvtnorm_1.3-3         rmarkdown_2.30        generics_0.1.4       \n#> [40] RcppParallel_5.1.11-1 cachem_1.1.0          stringr_1.6.0        \n#> [43] splines_4.5.2         parallel_4.5.2        vctrs_0.6.5          \n#> [46] V8_8.0.1              Matrix_1.7-4          sandwich_3.1-1       \n#> [49] jsonlite_2.0.0        arrayhelpers_1.1-0    glue_1.8.0           \n#> [52] codetools_0.2-20      distributional_0.5.0  lubridate_1.9.4      \n#> [55] stringi_1.8.7         gtable_0.3.6          QuickJSR_1.8.1       \n#> [58] pillar_1.11.1         htmltools_0.5.8.1     Brobdingnag_1.2-9    \n#> [61] R6_2.6.1              textshaping_1.0.4     rprojroot_2.1.1      \n#> [64] evaluate_1.0.5        lattice_0.22-7        backports_1.5.0      \n#> [67] memoise_2.0.1         broom_1.0.10          snakecase_0.11.1     \n#> [70] rstantools_2.5.0      gridExtra_2.3         coda_0.19-4.1        \n#> [73] nlme_3.1-168          checkmate_2.3.3       xfun_0.54            \n#> [76] zoo_1.8-14            pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted} \n",
    "supporting": [
      "02_kl_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}