{
  "hash": "926622c62fe044134a91f64ac2b35bb1",
  "result": {
    "engine": "knitr",
    "markdown": "# L'equilibrio tra prior e verosimiglianza {#sec-bayes-inference-prior}\n\n::: {.callout-note appearance=\"minimal\"}\nNei due capitoli precedenti abbiamo visto come costruire una distribuzione a posteriori e come riassumerla. Ora, spostiamo l'attenzione su una domanda diversa: **che cosa determina la posizione e la forma della distribuzione a posteriori quando le informazioni fornite dal prior e dai dati sono più o meno concordanti e precise?**\n\nNon riprenderemo la coniugazione Beta-Binomiale né le sintesi della posterior. Useremo invece quei risultati come una lente per leggere l'equilibrio informativo che si produce durante l'aggiornamento. La distribuzione a posteriori non decreta un vincitore fra il prior e la verosimiglianza: registra il contributo relativo di entrambi all'interno del modello scelto.\n:::\n\n::: {.callout-important appearance=\"minimal\" .chapter-status}\n**Da sapere.** La posizione della posterior dipende sia dai valori indicati dal prior e dai dati, sia dalla precisione relativa con cui ciascuna fonte li sostiene. Una distribuzione più concentrata è più influente nel calcolo, ma non per questo più corretta.\n\n**Da saper fare.** Prevedere verso quale fonte si sposterà la posterior; distinguere lo spostamento del centro dall'aumento di precisione; riconoscere accordo e conflitto tra prior e dati; interpretare lo shrinkage; valutare il prior mediante controlli predittivi e analisi di sensibilità.\n\n**Approfondimento facoltativo.** I prior empirici calibrati su collezioni di studi, i prior scalati mediante l'errore standard e le miscele robuste possono essere rimandati in una prima lettura.\n\n[Che cosa significano queste etichette?](../../guida-al-manuale.qmd#sec-percorsi-lettura)\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Prerequisiti\"}\n\n- Sono dati per noti il modello Beta-Binomiale del @sec-conjugate-families e le sintesi della posterior del @sec-bayesian-inference-summary-posterior.\n- È utile conoscere media, varianza e deviazione standard; il concetto di precisione viene richiamato nel capitolo.\n- La lettura del codice R è facoltativa per il percorso essenziale.\n\n:::\n\n::: {.callout-caution collapse=\"true\" title=\"Preparazione del notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |>\n  source()\n```\n:::\n\n:::\n\n## Due dimensioni dell'informazione: posizione e forza\n\nNel capitolo sul modello Beta-Binomiale abbiamo già separato due proprietà del prior: la media $m$, che ne descrive la posizione, e la concentrazione $\\kappa$, che ne descrive la forza informativa. Per comprendere l'equilibrio con i dati dobbiamo applicare la stessa distinzione anche alla verosimiglianza.\n\nNel caso binomiale, le quattro quantità da confrontare sono:\n\n| Fonte | Posizione | Forza informativa |\n|---|---:|---:|\n| Prior Beta | media $m$ | concentrazione $\\kappa$ |\n| Dati binomiali | proporzione osservata $y/n$ | numero di prove $n$ |\n\nLa posizione risponde alla domanda **“verso quali valori punta questa fonte?”**. La forza risponde invece a **“quanto nettamente li sostiene, rispetto all'altra fonte?”**. Due fonti possono indicare lo stesso valore con precisioni diverse, oppure valori molto lontani con pesi fortemente sbilanciati.\n\nNel modello Beta-Binomiale questa relazione è visibile nella media a posteriori, già incontrata nel @sec-conjugate-families:\n\n$$\n\\mathbb{E}(\\theta\\mid y)\n=\n\\frac{\\kappa}{\\kappa+n}m\n+\n\\frac{n}{\\kappa+n}\\frac{y}{n}.\n$$\n\nQuesta formula non serve qui come nuova regola di calcolo, ma come strumento di lettura. Mostra che la media posterior si colloca tra il centro del prior e la proporzione osservata, con pesi determinati dal rapporto tra $\\kappa$ e $n$:\n\n$$\nw_{\\text{prior}}=\\frac{\\kappa}{\\kappa+n},\n\\qquad\nw_{\\text{dati}}=\\frac{n}{\\kappa+n}.\n$$\n\nDire che la posterior si trova “tra prior e dati” è quindi corretto ma incompleto. Non è necessariamente equidistante dai due centri: si avvicina maggiormente alla fonte che, nel modello, contiene più informazione.\n\n::: {.callout-tip title=\"Forza non significa affidabilità\"}\nLa concentrazione o la precisione descrivono quanto una fonte è netta **all'interno del modello**. Non garantiscono che il prior sia ben calibrato, che i dati siano di buona qualità o che la verosimiglianza rappresenti adeguatamente il processo generativo. Una fonte può essere molto precisa e, nello stesso tempo, sistematicamente fuorviante.\n:::\n\n::: {.callout-note title=\"Il ruolo di $n$ va interpretato nel modello\"}\nNel modello binomiale, a parità di condizioni, un numero maggiore di prove rende la verosimiglianza più concentrata. Questo non significa che ogni campione grande sia automaticamente informativo o affidabile: dipendenze tra osservazioni, errori di misurazione, selezione del campione o una verosimiglianza inadeguata possono rendere ingannevole il peso attribuito a $n$.\n:::\n\n## Vedere l'equilibrio in azione\n\nConsideriamo una proporzione osservata pari a\n\n$$\n\\frac{y}{n}=\\frac{6}{9}=0.667.\n$$\n\nCostruiamo tre scenari. Il primo fa da riferimento; nel secondo aumentiamo solo la concentrazione del prior; nel terzo solo la quantità di dati, lasciando invariati il prior e la proporzione osservata. Cambiando una cosa alla volta, ogni differenza è attribuibile a una sola fonte.\n\n**Scenario 1: prior moderato e pochi dati**\n\nPartiamo da\n\n$$\n\\theta\\sim\\operatorname{Beta}(2,2),\n$$\n\nun prior centrato su 0.50 con concentrazione $\\kappa=4$. Dopo 6 successi e 3 insuccessi, la posterior è\n\n$$\n\\theta\\mid y\\sim\\operatorname{Beta}(8,5),\n$$\n\ncon media\n\n$$\n\\frac{8}{13}=0.615.\n$$\n\nIl prior pesa $4/13=0.308$, mentre i dati pesano $9/13=0.692$. La posterior si sposta quindi verso 0.667, pur conservando l'attrazione del prior verso 0.50.\n\n**Scenario 2: stesso centro, prior più concentrato**\n\nManteniamo la media a priori a 0.50, ma aumentiamo la concentrazione:\n\n$$\n\\theta\\sim\\operatorname{Beta}(20,20),\n\\qquad \\kappa=40.\n$$\n\nCon gli stessi 6 successi su 9 prove otteniamo\n\n$$\n\\theta\\mid y\\sim\\operatorname{Beta}(26,23),\n$$\n\nla cui media è\n\n$$\n\\frac{26}{49}=0.531.\n$$\n\nLa direzione indicata dai dati non è cambiata. È cambiato il rapporto di forza: il prior pesa $40/49=0.816$ e i dati $9/49=0.184$. Per questo la posterior rimane molto più vicina a 0.50.\n\n**Scenario 3: stesso prior, molti più dati**\n\nTorniamo al prior $\\operatorname{Beta}(2,2)$, ma osserviamo 60 successi su 90 prove. La proporzione campionaria resta 0.667, mentre la quantità di informazione fornita dai dati aumenta:\n\n$$\n\\theta\\mid y\\sim\\operatorname{Beta}(62,32).\n$$\n\nLa media posterior è\n\n$$\n\\frac{62}{94}=0.660,\n$$\n\ncon pesi $4/94=0.043$ per il prior e $90/94=0.957$ per i dati. La posterior è ora quasi centrata sulla proporzione osservata. Il prior non è stato cancellato: il suo contributo è diventato piccolo rispetto a quello della verosimiglianza.\n\n| Scenario | Prior | Dati | Peso del prior | Peso dei dati | Media posterior |\n|---|---:|---:|---:|---:|---:|\n| Prior moderato, pochi dati | Beta(2,2) | 6/9 | 0.308 | 0.692 | 0.615 |\n| Prior concentrato, pochi dati | Beta(20,20) | 6/9 | 0.816 | 0.184 | 0.531 |\n| Prior moderato, molti dati | Beta(2,2) | 60/90 | 0.043 | 0.957 | 0.660 |\n\nLa distanza tra i centri è identica nei tre scenari: il prior punta a 0.50 e i dati a 0.667. Le diverse posterior dipendono quindi esclusivamente dalla forza relativa delle due fonti.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_grid <- seq(0.001, 0.999, length.out = 600)\n\nscenarios <- tibble::tribble(\n  ~scenario, ~alpha, ~beta, ~y, ~n,\n  \"Prior moderato, pochi dati\", 2, 2, 6, 9,\n  \"Prior concentrato, pochi dati\", 20, 20, 6, 9,\n  \"Prior moderato, molti dati\", 2, 2, 60, 90\n)\n\ndensity_list <- lapply(seq_len(nrow(scenarios)), function(i) {\n  row <- scenarios[i, ]\n\n  bind_rows(\n    tibble(\n      theta = theta_grid,\n      densita = dbeta(theta_grid, row$alpha, row$beta),\n      distribuzione = \"Prior\"\n    ),\n    tibble(\n      theta = theta_grid,\n      densita = dbeta(\n        theta_grid,\n        row$alpha + row$y,\n        row$beta + row$n - row$y\n      ),\n      distribuzione = \"Posterior\"\n    )\n  ) |>\n    mutate(scenario = row$scenario)\n})\n\ndensities <- bind_rows(density_list)\n\nggplot(\n  densities,\n  aes(x = theta, y = densita, colour = distribuzione)\n) +\n  geom_line(linewidth = 1.1) +\n  facet_wrap(\n    ~scenario,\n    scales = \"free_y\",\n    ncol = 1,\n    labeller = ggplot2::label_wrap_gen(width = 32)\n  ) +\n  scale_x_continuous(\n    breaks = seq(0, 1, by = 0.2),\n    limits = c(0, 1),\n    expand = expansion(mult = c(0.01, 0.01))\n  ) +\n  scale_colour_manual(\n    values = c(\n      \"Prior\" = palette_qualitative[8],\n      \"Posterior\" = palette_qualitative[5]\n    )\n  ) +\n  labs(\n    title = \"Il peso relativo di prior e dati\",\n    subtitle = \"La stessa proporzione osservata può produrre posterior diverse\",\n    x = expression(theta),\n    y = \"Densità\",\n    colour = NULL\n  ) +\n  legenda_in_alto +\n  theme(\n    panel.spacing.y = grid::unit(1.2, \"lines\"),\n    strip.text = element_text(face = \"bold\", size = 10),\n    plot.title.position = \"plot\"\n  )\n```\n\n::: {.cell-output-display}\n![Confronto tra distribuzioni a priori e a posteriori in tre scenari Beta-Binomiali. A parità di proporzione osservata, un prior più concentrato mantiene la posterior più vicina al proprio centro; aumentando il numero di osservazioni, invece, la posterior si avvicina maggiormente alla proporzione indicata dai dati. Le scale verticali sono adattate separatamente per rendere leggibile la forma delle distribuzioni in ciascun pannello.](04_balance_prior_post_files/figure-html/fig-balance-prior-posterior-scenarios-1.png){#fig-balance-prior-posterior-scenarios fig-align='center' fig-alt='Tre pannelli disposti verticalmente confrontano, mediante due curve, la distribuzione a priori e quella a posteriori. Nel primo scenario il prior moderato e pochi dati producono una posterior intermedia; nel secondo il prior più concentrato domina maggiormente; nel terzo, con molti dati, la posterior si concentra vicino alla proporzione osservata.' width=85%}\n:::\n:::\n\n\nIl grafico mostra due cambiamenti distinti. Il primo riguarda **la posizione**: la posterior si avvicina maggiormente al prior o ai dati in funzione dei pesi relativi. Il secondo riguarda **la concentrazione**: incorporare informazione riduce l'incertezza e rende la posterior più stretta. Questi due effetti non devono essere confusi.\n\n### Quando prior e dati concordano\n\nSe prior e dati indicano lo stesso valore, l'aggiornamento può aumentare la precisione senza spostare il centro. Consideriamo\n\n$$\n\\theta\\sim\\operatorname{Beta}(8,4),\n\\qquad\n\\frac{y}{n}=\\frac{6}{9}=0.667.\n$$\n\nIl prior e i dati sono entrambi centrati su 0.667. La posterior è\n\n$$\n\\theta\\mid y\\sim\\operatorname{Beta}(14,7),\n$$\n\nancora centrata su 0.667, ma più concentrata. In questo caso l'apprendimento non consiste in una correzione della posizione: consiste soprattutto in una riduzione dell'incertezza.\n\n### Quando prior e dati sono in conflitto\n\nConsideriamo invece un prior $\\operatorname{Beta}(2,8)$, con media 0.20 e concentrazione 10. Gli stessi 6 successi su 9 prove producono\n\n$$\n\\theta\\mid y\\sim\\operatorname{Beta}(8,11),\n$$\n\ncon media\n\n$$\n\\frac{8}{19}=0.421.\n$$\n\nLa posterior si colloca tra 0.20 e 0.667, ma non nel loro punto medio aritmetico. Poiché $\\kappa=10$ e $n=9$, le due fonti hanno forza simile e nessuna delle due prevale nettamente. La distanza tra prior e dati rende il conflitto visibile; il rapporto tra le loro precisioni stabilisce dove si risolve, provvisoriamente, l'equilibrio.\n\n::: {.callout-warning title=\"Il conflitto è un segnale diagnostico, non un verdetto\"}\nUn forte disaccordo tra prior e dati non identifica automaticamente quale componente sia inadeguata. Può riflettere un prior mal calibrato, dati insoliti ma genuini, errori di misurazione, differenze tra popolazioni, dipendenze non modellate o una verosimiglianza poco plausibile. Prima di modificare il prior occorre quindi controllare dati, modello e comparabilità delle informazioni iniziali.\n:::\n\n## Un principio generale: precisione, media ponderata e shrinkage\n\nIl modello Beta-Binomiale rende l'equilibrio particolarmente trasparente, ma il principio non dipende dagli pseudo-conteggi. Il modello Normale-Normale, incontrato nel @sec-conjugate-families, mostra la stessa struttura in un'altra veste.\n\nSupponiamo che una stima $b$ abbia distribuzione di campionamento approssimativamente normale:\n\n$$\nb\\mid\\beta\\sim\\operatorname{Normal}(\\beta,s^2),\n$$\n\ne assegniamo al parametro il prior\n\n$$\n\\beta\\sim\\operatorname{Normal}(\\mu_0,\\tau_0^2).\n$$\n\nLa forza delle due fonti è espressa dalle rispettive precisioni, cioè dagli inversi delle varianze:\n\n$$\n\\lambda_0=\\frac{1}{\\tau_0^2},\n\\qquad\n\\lambda_D=\\frac{1}{s^2}.\n$$\n\nLa media posterior è\n\n$$\n\\mu_1\n=\n\\frac{\\lambda_0}{\\lambda_0+\\lambda_D}\\mu_0\n+\n\\frac{\\lambda_D}{\\lambda_0+\\lambda_D}b,\n$$\n\nmentre la varianza posterior è\n\n$$\n\\tau_1^2=\\frac{1}{\\lambda_0+\\lambda_D}.\n$$\n\nRitroviamo quindi la stessa geometria: il centro posterior è una media ponderata e la precisione posterior nasce dalla somma dell'informazione disponibile.\n\nConsideriamo il prior\n\n$$\n\\beta\\sim\\operatorname{Normal}(0,0.2^2)\n$$\n\ne la stessa stima puntuale $b=-0.40$ osservata con due errori standard diversi.\n\n| Errore standard | Peso del prior | Peso dei dati | Media posterior | DS posterior |\n|---:|---:|---:|---:|---:|\n| $s=0.30$ | 0.692 | 0.308 | -0.123 | 0.166 |\n| $s=0.04$ | 0.038 | 0.962 | -0.385 | 0.039 |\n\nNel primo caso la stima è rumorosa: il prior riceve più peso e la posterior si sposta sensibilmente verso 0. Nel secondo la stima è molto precisa: la posterior rimane quasi centrata su $-0.40$. La forza dei dati non coincide dunque con la grandezza dell'effetto osservato; dipende da quanto precisamente l'effetto è stimato.\n\nQuesto spostamento verso il centro del prior è chiamato **shrinkage**. Il termine può suggerire un movimento sempre diretto verso zero, ma non è così: la stima viene attratta verso **il centro del prior**, qualunque esso sia. Se il prior fosse centrato su un valore positivo, lo shrinkage avverrebbe verso quel valore.\n\nLo shrinkage non modifica arbitrariamente i dati. È la conseguenza dell'aver combinato una stima incerta con un'informazione iniziale più stabile. La sua intensità dipende da tre elementi:\n\n- la distanza tra il centro del prior e quello della verosimiglianza;\n- la precisione del prior;\n- la precisione della verosimiglianza.\n\nPrior debolmente informativi possono così regolarizzare stime ottenute da dati scarsi o rumorosi, attenuando valori estremi sostenuti da poca informazione. Questa proprietà può ridurre gli errori di tipo M in alcuni contesti, ma non costituisce una garanzia generale e non corregge automaticamente problemi di selezione, misurazione o specificazione del modello [@gelman2014beyond].\n\n::: {.callout-tip title=\"Tre configurazioni da riconoscere\"}\n1. **Centri simili e fonti entrambe precise:** la posterior conserva il centro comune e diventa più precisa.\n2. **Centri diversi e prior più preciso:** la posterior rimane più vicina al prior.\n3. **Centri diversi e dati più precisi:** la posterior rimane più vicina alla verosimiglianza.\n:::\n\n## Scegliere e controllare il prior\n\nFinora il prior è stato un dato di partenza. Ma se la sua forza determina quanto pesa nel risultato, diventa decisivo chiedersi **da dove venga e quali conseguenze produca**.\n\n### La forza dipende dalla scala\n\nUna distribuzione $\\operatorname{Normal}(0,1)$ può essere molto vaga per un parametro che varia plausibilmente tra $-100$ e $100$, ma estremamente restrittiva per un parametro che assume normalmente valori compresi tra $-0.05$ e $0.05$. Non esistono quindi prior “forti” o “deboli” in assoluto: la valutazione dipende dalla scala, dall'unità di misura e dal significato sostantivo del parametro.\n\nPrima di scegliere una distribuzione è utile esplicitare quattro livelli:\n\n- il valore che rappresenta assenza, neutralità o riferimento;\n- i valori ordinari nel contesto studiato;\n- i valori sorprendenti ma ancora possibili;\n- i valori incompatibili con le conoscenze disponibili.\n\nAnche un prior uniforme non è automaticamente neutrale. La $\\operatorname{Beta}(1,1)$ assegna la stessa densità a tutti i valori di $\\theta$ su $[0,1]$, ma nel modello Beta-Binomiale ha comunque concentrazione $\\kappa=2$. Inoltre, una distribuzione uniforme su una scala non rimane uniforme dopo una trasformazione non lineare. La neutralità, quindi, non può essere stabilita osservando soltanto la forma della densità su una particolare parametrizzazione.\n\n| Tipo di prior | Funzione principale | Domanda sostantiva |\n|---|---|---|\n| Di riferimento o molto vaga | Lasciare ai dati gran parte dell'influenza esplicita | Quali conseguenze ha affidarsi quasi interamente alla verosimiglianza? |\n| Debolmente informativa | Escludere valori implausibili e stabilizzare le stime | Quali valori sono ordinari e quali eccezionali? |\n| Informativa | Integrare conoscenze teoriche o empiriche specifiche | Che cosa sappiamo già in questo preciso contesto? |\n\nLe etichette restano relative: lo stesso prior può essere debole in uno studio e forte in un altro, perché cambia il rapporto con la scala del parametro e con l'informazione contenuta nei dati.\n\n::: {.callout-note collapse=\"true\" title=\"Approfondimento: prior scalati mediante l'errore standard\"}\n@zwet2022proposal discutono prior empirici calibrati sulla distribuzione degli effetti standardizzati rispetto al loro errore standard. La strategia è utile per costruire prior di default a partire da collezioni di studi comparabili e per regolarizzare stime rumorose.\n\nNon è però una regola universale per la scelta dei prior sostantivi. L'errore standard dipende dal disegno, dalla numerosità campionaria e dal modello: un prior scalato mediante $s$ va presentato come una strategia empirica con un ambito di applicazione dichiarato, non come una soluzione neutrale o invariante.\n:::\n\n### Controllare il prior prima dei dati\n\nLa forma del prior sul parametro può essere difficile da valutare direttamente. Un **controllo predittivo a priori** traduce invece il prior nello spazio delle osservazioni e mostra quali dati il modello considera plausibili prima di vedere il campione reale.\n\nSupponiamo\n\n$$\n\\mu\\sim\\operatorname{Normal}(0,1),\n$$\n\n$$\ny_i\\mid\\mu\\sim\\operatorname{Normal}(\\mu,1),\n\\qquad n=30.\n$$\n\nPrima di osservare i dati, la media campionaria ha distribuzione\n\n$$\n\\bar y\\sim\n\\operatorname{Normal}\\left(\n0,\n1^2+\\frac{1^2}{30}\n\\right).\n$$\n\nLa deviazione standard predittiva è circa 1.016 e l'intervallo centrale al 95% è approssimativamente $[-1.99,1.99]$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsd_prior_predictive <- sqrt(1^2 + 1^2 / 30)\nqnorm(\n  c(0.025, 0.50, 0.975),\n  mean = 0,\n  sd = sd_prior_predictive\n)\n#> [1] -1.99  0.00  1.99\n```\n:::\n\n\nIl controllo non dichiara automaticamente che il prior sia adeguato. Rende però concreta la domanda: **medie campionarie vicine a $-2$ o $2$ sono plausibili sulla scala dell'outcome?** Se la risposta è chiaramente negativa o se il modello genera frequentemente osservazioni impossibili, occorre rivedere il prior, la verosimiglianza o entrambi.\n\n### Valutare la dipendenza dal prior dopo l'analisi\n\nDopo avere osservato i dati, l'**analisi di sensibilità** verifica quanto le conclusioni dipendano da scelte a priori ragionevoli. Non basta confrontare le sole medie posteriori: è preferibile esaminare le quantità che rispondono alla domanda scientifica, come intervalli di credibilità, probabilità di superare una soglia o previsioni per nuove osservazioni.\n\nSe prior alternativi ugualmente plausibili conducono a conclusioni simili, i dati sono abbastanza informativi rispetto alle differenze considerate. Se conducono a conclusioni sostantive diverse, la dipendenza dal prior è parte del risultato e deve essere comunicata:\n\n> Con i dati disponibili, alcune conclusioni dipendono ancora in misura rilevante dalle ipotesi iniziali considerate plausibili.\n\nLa sensibilità non dimostra che il modello sia sbagliato: indica che l'informazione disponibile non basta a rendere trascurabili le differenze fra prior ragionevoli. L'analisi di sensibilità non consiste, inoltre, nel provare distribuzioni diverse finché compare il risultato desiderato: le alternative devono essere motivate prima di essere confrontate e interpretate tutte con lo stesso criterio.\n\n### In sintesi: un percorso per il prior\n\nMettendo insieme i controlli delle tre sottosezioni precedenti, un percorso prudente ha sei passaggi:\n\n1. **Dichiarare la scala.** Specificare unità di misura, trasformazioni e vincoli del parametro.\n2. **Descrivere posizione e forza.** Esplicitare quali valori il prior favorisce e quanto nettamente li sostiene.\n3. **Giustificare la fonte.** Verificare che teoria, studi precedenti o giudizi esperti siano pertinenti alla popolazione e al disegno attuali.\n4. **Controllare le conseguenze predittive.** Esaminare quali dati il prior genera insieme alla verosimiglianza.\n5. **Diagnosticare il conflitto.** Controllare dati, modello e comparabilità prima di attribuire il disaccordo a una sola componente.\n6. **Condurre un'analisi di sensibilità.** Confrontare poche alternative plausibili sulle quantità sostantive rilevanti e documentare ciò che cambia.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nLa posterior non è un compromesso generico tra due opinioni e non si trova necessariamente a metà tra prior e dati. La sua posizione dipende dai centri indicati dalle due fonti e dalla precisione relativa con cui ciascuna li sostiene; la sua concentrazione riflette invece quanta informazione complessiva è stata incorporata.\n\nNel modello Beta-Binomiale questo equilibrio è leggibile attraverso $m$, $\\kappa$, $y/n$ e $n$. Nel modello Normale-Normale la stessa struttura viene espressa mediante le precisioni. In entrambi i casi, lo shrinkage è il movimento della stima verso il centro del prior quando la verosimiglianza non è sufficientemente precisa da prevalere.\n\nLa forza informativa non coincide con la correttezza. Per questo la scelta del prior deve essere accompagnata da controlli predittivi, mentre il risultato deve essere sottoposto ad analisi di sensibilità. Rendere visibile quanto le conclusioni dipendano da prior, dati e modello non è un limite dell'inferenza bayesiana: è una delle sue principali risorse diagnostiche.\n\n## Esercizi {.unnumbered .unlisted}\n\n### Esercizio 1 — Comprendere {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 15 minuti*\n\nRiconsidera i tre scenari principali del capitolo:\n\n| Scenario | Prior | Dati | Media posterior |\n|---|---:|---:|---:|\n| A | Beta(2,2) | 6 successi su 9 | 0.615 |\n| B | Beta(20,20) | 6 successi su 9 | 0.531 |\n| C | Beta(2,2) | 60 successi su 90 | 0.660 |\n\nPer ciascuno scenario:\n\n1. identifica la posizione e la forza del prior;\n2. identifica la posizione e la forza dei dati;\n3. spiega la posizione della media posterior;\n4. descrivi come cambia l'incertezza rispetto al prior;\n5. chiarisci quale confronto isola la forza del prior e quale isola la forza dei dati.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nIn A e B la proporzione osservata è identica e cambia soltanto $\\kappa$. In A e C il prior e la proporzione osservata sono identici e cambia soltanto $n$. Oltre al centro, considera la concentrazione delle distribuzioni posteriori.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\nNel caso A il prior è centrato su 0.50 con concentrazione 4, mentre i dati sono centrati su 0.667 con peso 9. La posterior, 0.615, è più vicina ai dati e più concentrata del prior.\n\nNel caso B il centro del prior non cambia, ma la concentrazione sale a 40. Il prior è ora molto più forte dei nove dati e la posterior rimane vicina a 0.50. Anche qui l'incertezza diminuisce rispetto al prior, ma lo spostamento del centro è ridotto.\n\nNel caso C il prior torna a Beta(2,2), mentre i dati hanno peso 90. La posterior, 0.660, è quasi centrata sulla proporzione osservata ed è molto più concentrata.\n\nIl confronto A-B isola la forza del prior. Il confronto A-C isola la forza della verosimiglianza. In tutti i casi l'aggiornamento aumenta la concentrazione; il centro si sposta soltanto quando prior e dati indicano valori differenti.\n:::\n\n### Esercizio 2 — Prevedere {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 12 minuti*\n\nPrima di calcolare, prevedi il comportamento della posterior nei quattro casi seguenti:\n\n| Caso | Media prior | Concentrazione prior | Proporzione osservata | Numero di prove |\n|---|---:|---:|---:|---:|\n| A | 0.50 | 4 | 0.70 | 10 |\n| B | 0.50 | 40 | 0.70 | 10 |\n| C | 0.70 | 40 | 0.70 | 10 |\n| D | 0.20 | 10 | 0.80 | 100 |\n\nPer ogni caso:\n\n1. indica se la media posterior sarà più vicina al prior, ai dati o al centro comune;\n2. specifica se l'aggiornamento produrrà soprattutto uno spostamento del centro, un aumento di precisione o entrambi;\n3. individua il caso con il maggiore spostamento rispetto alla media a priori.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nConfronta $\\kappa$ e $n$. Se prior e dati hanno lo stesso centro, la media non si sposta, ma la distribuzione diventa più concentrata.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\nNel caso A i dati hanno peso 10 e il prior peso 4: la media posterior è 0.643, quindi più vicina a 0.70. Cambiano sia il centro sia la precisione.\n\nNel caso B il prior ha peso 40 e i dati peso 10: la media è 0.540 e rimane vicina a 0.50. La precisione aumenta, ma lo spostamento è contenuto.\n\nNel caso C prior e dati sono entrambi centrati su 0.70. La media posterior resta 0.70; l'apprendimento riguarda soprattutto l'aumento di precisione.\n\nNel caso D i dati hanno peso 100 e il prior peso 10. Nonostante il forte conflitto, la media posterior è 0.745 e rimane vicina a 0.80. È il caso con il maggiore spostamento rispetto al centro del prior.\n:::\n\n### Esercizio 3 — Analizzare la sensibilità {.unnumbered .unlisted}\n\n*Codice: facoltativo · Tempo indicativo: 20 minuti*\n\nMantieni fissi i dati a 6 successi su 9 prove e confronta tre prior con la stessa media 0.50:\n\n- Beta(2,2), con concentrazione 4;\n- Beta(10,10), con concentrazione 20;\n- Beta(50,50), con concentrazione 100.\n\nPer ciascun prior:\n\n1. scrivi i parametri della posterior;\n2. calcola la media posterior;\n3. valuta la probabilità $P(\\theta>0.60\\mid y)$;\n4. stabilisci se la conclusione “$\\theta$ supera 0.60” è robusta rispetto alle tre scelte a priori;\n5. spiega perché confrontare una probabilità sostantiva è più informativo che confrontare soltanto le medie.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nLe posterior sono Beta(8,5), Beta(16,13) e Beta(56,53). In R puoi calcolare la probabilità con `pbeta(0.60, alpha, beta, lower.tail = FALSE)`.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\nLe medie posteriori sono rispettivamente 0.615, 0.552 e 0.514. Le probabilità che $\\theta$ superi 0.60 sono circa 0.562, 0.305 e 0.035.\n\nLa conclusione sostantiva non è robusta: con il prior meno concentrato, valori superiori a 0.60 restano plausibili; con il prior più concentrato, la probabilità diventa molto bassa. I nove dati non sono quindi sufficienti a rendere trascurabili le differenze tra le tre forze a priori.\n\nLe sole medie mostrano uno spostamento graduale, ma non dicono direttamente quanto sia sostenuta l'affermazione di interesse. La probabilità a posteriori collega invece l'analisi di sensibilità alla domanda sostantiva, come discusso nel @sec-bayesian-inference-summary-posterior.\n:::\n\n### Esercizio 4 — Criticare {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 15 minuti*\n\nValuta la seguente affermazione:\n\n> “Una prior più forte è più affidabile. La posterior è sempre a metà tra prior e dati. Quando il campione è grande, il prior scompare. Se prior e dati sono in conflitto, basta sostituire il prior; se un'analisi di sensibilità produce risultati diversi, significa che il ricercatore ha scelto male il modello.”\n\nIndividua almeno cinque problemi e riscrivi l'affermazione in forma corretta.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nDistingui forza e correttezza, media aritmetica e media ponderata, peso nullo e peso relativamente piccolo, diagnosi del conflitto e dipendenza informativa.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Elementi per la risposta\"}\nUna prior più concentrata è più influente, ma non necessariamente più accurata. La posterior non è sempre a metà: si colloca secondo la precisione relativa delle due fonti. Con molti dati il peso relativo del prior può diventare molto piccolo, ma il prior rimane una componente del modello. Un conflitto richiede controlli su prior, dati e verosimiglianza, non la sostituzione automatica del prior. Infine, risultati sensibili a prior alternative plausibili non dimostrano necessariamente un errore: possono indicare che i dati non sono abbastanza informativi per discriminare tra ipotesi iniziali ragionevoli.\n\nUna formulazione corretta potrebbe essere:\n\n> “La forza del prior descrive la sua precisione all'interno del modello, non la sua verità. La posterior combina prior e dati secondo la loro informazione relativa. Quando la verosimiglianza è molto precisa, l'influenza relativa del prior diminuisce. Un conflitto tra prior e dati deve essere diagnosticato controllando tutte le componenti del modello. Se prior plausibili conducono a conclusioni diverse, questa dipendenza deve essere comunicata come parte dell'incertezza dell'analisi.”\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Informazioni sull'ambiente di sviluppo\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.6.1\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.1            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.1           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8         tidyselect_1.2.1     farver_2.1.2        \n#>  [4] S7_0.2.2             fastmap_1.2.0        tensorA_0.36.2.1    \n#>  [7] digest_0.6.39        timechange_0.4.0     estimability_2.0.0  \n#> [10] lifecycle_1.0.5      magrittr_2.0.5       compiler_4.6.1      \n#> [13] rlang_1.3.0          tools_4.6.1          yaml_2.3.12         \n#> [16] knitr_1.51           labeling_0.4.3       bridgesampling_1.2-1\n#> [19] htmlwidgets_1.6.4    pkgbuild_1.4.8       curl_7.1.0          \n#> [22] RColorBrewer_1.1-3   abind_1.4-8          purrr_1.2.2         \n#> [25] grid_4.6.1           stats4_4.6.1         xtable_1.8-8        \n#> [28] inline_0.3.21        emmeans_2.0.4        scales_1.4.0        \n#> [31] cli_3.6.6            mvtnorm_1.4-2        rmarkdown_2.31      \n#> [34] generics_0.1.4       otel_0.2.0           RcppParallel_6.2.0  \n#> [37] cachem_1.1.0         stringr_1.6.0        parallel_4.6.1      \n#> [40] vctrs_0.7.3          V8_8.2.0             Matrix_1.7-6        \n#> [43] jsonlite_2.0.0       arrayhelpers_1.1-2   glue_1.8.1          \n#> [46] codetools_0.2-20     distributional_0.8.1 lubridate_1.9.5     \n#> [49] stringi_1.8.9        gtable_0.3.6         QuickJSR_1.10.0     \n#> [52] pillar_1.11.1        htmltools_0.5.9      Brobdingnag_1.2-9   \n#> [55] R6_2.6.1             textshaping_1.0.5    rprojroot_2.1.1     \n#> [58] evaluate_1.0.5       lattice_0.22-9       backports_1.5.1     \n#> [61] memoise_2.0.1        broom_1.0.13         snakecase_0.11.1    \n#> [64] rstantools_2.7.0     coda_0.19-4.1        gridExtra_2.3.1     \n#> [67] nlme_3.1-170         checkmate_2.3.4      xfun_0.60           \n#> [70] pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "04_balance_prior_post_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}