<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.34">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>31&nbsp; Confronto tra le medie di due gruppi – Psicometria</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/linear_models/09_effect_size.html" rel="next">
<link href="../../chapters/linear_models/07_one_mean.html" rel="prev">
<link href="../../style/gauss.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-0a72236910a44089af39cd28873f322e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9908c7b05874059c2106d454ac00f1d0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QT5S3P9D31"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QT5S3P9D31', { 'anonymize_ip': true});
</script><style>html{ scroll-behavior: smooth; }</style>
<script>
window.MathJax = {
  tex: { inlineMath: [['$', '$'], ['\\(', '\\)']] },
  svg: { scale: 1, mtextInheritFont: true, fontCache: 'none', minScale: 1 },
  options: { renderActions: { addMenu: [0, '', ''] } },
  loader: { load: ['input/tex','output/svg'] }
};
</script><script>
window.MathJax = {
  tex: { inlineMath: [['$', '$'], ['\\(', '\\)']] },
  svg: { scale: 1, mtextInheritFont: true, fontCache: 'none', minScale: 1 },
  options: { renderActions: { addMenu: [0, '', ''] } },
  loader: { load: ['input/tex','output/svg'] }
};
// Suggerimento CSS: vedi sezione 3 per gli spazi attorno a display math
</script><script>
window.MathJax = {
  tex: {
    packages: {'[+]': ['boldsymbol']},
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  },
  svg: { fontCache: 'global' }
};
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../../style/_typography-extras.css">
<link rel="stylesheet" href="../../style/_code-extras.css">
<link rel="stylesheet" href="../../style/_math-extras.css">
<link rel="stylesheet" href="../../style/styles.css">
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/linear_models/introduction_sec.html">Regressione</a></li><li class="breadcrumb-item"><a href="../../chapters/linear_models/08_two_means.html"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Confronto tra le medie di due gruppi</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Psicometria</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/psicometria-r/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Attiva/disattiva la modalità lettore">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Informazioni generali</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Inferenza</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/01_bayes_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Inferenza bayesiana</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/02_uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Abbracciare l’incertezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/03_uncertainty_quantification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">La quantificazione dell’incertezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/04_statistical_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modelli statistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/05_subj_prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Aggiornare le credenze su un parametro: dal prior alla posterior</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/06_conjugate_families.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Distribuzioni coniugate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/07_summary_posterior.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sintesi a posteriori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/08_balance_prior_post.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">L’influenza della distribuzione a priori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/09_prior_pred_check.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Controllo predittivo a priori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/10_post_pred_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Distribuzione predittiva a posteriori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">MCMC</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/01_metropolis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">L’algoritmo di Metropolis-Hastings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/02_ppl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linguaggi di programmazione probabilistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/03_stan_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Introduzione pratica a Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/04_stan_diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Diagnostica delle catene markoviane</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/05_mcmc_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Controlli predittivi bayesiani (a priori e a posteriori) con <code>cmdstanr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/06_stan_odds_ratio_stan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Analisi bayesiana dell’odds ratio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/07_stan_two_means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Confrontare due medie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/08_stan_poisson_model_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Modello di Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/09_stan_gaussian_mixture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Modelli Mistura Gaussiani</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/10_stan_nuisance_parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Modelli con più di un parametro</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/11_stan_hier_beta_binom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Modello gerarchico beta-binomiale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/12_stan_parametrization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Parametrizzazioni centered e non-centered</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/13_bayesian_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Flusso di lavoro bayesiano</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive sulla sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Regressione</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/01_reglin_frequentist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">La regressione lineare bivariata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/02_regr_toward_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">La regressione verso la media</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/03_reglin_bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Modello bayesiano di regressione lineare bivariata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/04_synt_sugar_sea_ice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Zucchero sintattico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/05_stan_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Regressione lineare in Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/06_specification_error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Errore di specificazione e bias da variabile omessa</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/07_one_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Inferenza bayesiana su una media</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/08_two_means.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Confronto tra le medie di due gruppi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/09_effect_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">La grandezza dell’effetto: valutare la rilevanza pratica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/10_sample_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Pianificazione della dimensione campionaria</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/11_anova_1via.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">ANOVA ad una via</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">GLM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/01_logistic_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Regressione logistica con Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/02_one_proportion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Inferenza sulle proporzioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/03_two_proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Confronto tra due proporzioni con la regressione logistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/04_poisson_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Modello di Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/05_logistic_process.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Dal GLM a un modello processuale per dati binari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/06_missing_values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Dati mancanti in psicologia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive sulla sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Entropia</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/01_entropy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Entropia e informazione di Shannon</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/02_kl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">La divergenza di Kullback-Leibler</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/03_model_comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Valutare i modelli bayesiani</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Modelli</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/01_dynamic_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Il modello di revisione degli obiettivi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/02_dynamic_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Estensioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/03_rescorla_wagner.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Il modello di Rescorla–Wagner</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/04_study_method.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Decisione ottimale e utilità attesa: l’approccio bayesiano</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Crisi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/introduction_replication_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/01_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">La crisi della replicazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/02_limits_stat_freq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Limiti dell’inferenza frequentista</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/03_effect_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">La grandezza dell’effetto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/04_s_m_errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Errori di segno e errori di grandezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/05_p_values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">La fragilità del <em>p</em>-valore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/06_changes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Riforma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/07_degrees_of_freedom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">I gradi di libertà del ricercatore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/08_integrity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Integrità della ricerca</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Epilogo</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epiloque/epiloque.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Considerazioni Conclusive</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a01_shell.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">La Shell</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a01a_files.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Cartelle e documenti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a02_math_symbols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Simbologia di base</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a03_latex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Equazioni Matematiche in LaTeX</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a11_numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Numeri e intervalli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a12_sum_notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Sommatorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a13_sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">Insiemi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a14_combinatorics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">Calcolo combinatorio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a15_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">I</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a35_other_conjugate_families.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">J</span>&nbsp; <span class="chapter-title">Altre famiglie coniugate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a36_gamma_poisson_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">K</span>&nbsp; <span class="chapter-title">Modello coniugato Gamma-Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a40_metropolis_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">L</span>&nbsp; <span class="chapter-title">Metropolis: esempio Normale–Normale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a41_cmdstanr_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">M</span>&nbsp; <span class="chapter-title">Implementazione di modelli Bayesiani con Stan tramite <code>cmdstanr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a47_first_order_markov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">N</span>&nbsp; <span class="chapter-title">Catene di Markov</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a50_lin_fun.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">O</span>&nbsp; <span class="chapter-title">La funzione lineare</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a71_install_cmdstan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">P</span>&nbsp; <span class="chapter-title">Come installare CmdStan</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Sommario</h2>
   
  <ul class="collapse">
<li><a href="#il-modello-a-indicatore-e-le-quantit%C3%A0-di-interesse" id="toc-il-modello-a-indicatore-e-le-quantità-di-interesse" class="nav-link active" data-scroll-target="#il-modello-a-indicatore-e-le-quantit%C3%A0-di-interesse"><span class="header-section-number">31.1</span> Il modello a indicatore e le quantità di interesse</a></li>
  <li><a href="#la-codifica-centrata-dellindicatore" id="toc-la-codifica-centrata-dellindicatore" class="nav-link" data-scroll-target="#la-codifica-centrata-dellindicatore"><span class="header-section-number">31.2</span> La codifica centrata dell’indicatore</a></li>
  <li><a href="#stima-con-brms" id="toc-stima-con-brms" class="nav-link" data-scroll-target="#stima-con-brms"><span class="header-section-number">31.3</span> Stima con <code>brms</code></a></li>
  <li><a href="#confronto-tra-approcci-frequentista-e-bayesiano" id="toc-confronto-tra-approcci-frequentista-e-bayesiano" class="nav-link" data-scroll-target="#confronto-tra-approcci-frequentista-e-bayesiano"><span class="header-section-number">31.4</span> Confronto tra approcci: frequentista e bayesiano</a></li>
  <li><a href="#esempio-istruzione-materna-e-qi" id="toc-esempio-istruzione-materna-e-qi" class="nav-link" data-scroll-target="#esempio-istruzione-materna-e-qi"><span class="header-section-number">31.5</span> Esempio: istruzione materna e QI</a></li>
  <li><a href="#approfondimenti-bayesiani" id="toc-approfondimenti-bayesiani" class="nav-link" data-scroll-target="#approfondimenti-bayesiani"><span class="header-section-number">31.6</span> Approfondimenti bayesiani</a></li>
  </ul><div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ccaudek/psicometria-r/blob/main/chapters/linear_models/08_two_means.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/psicometria-r/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/linear_models/introduction_sec.html">Regressione</a></li><li class="breadcrumb-item"><a href="../../chapters/linear_models/08_two_means.html"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Confronto tra le medie di due gruppi</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-linear-models-two-groups" class="quarto-section-identifier"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Confronto tra le medie di due gruppi</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="epigraph">
<blockquote class="blockquote">
<p>“La domanda non è”è la differenza reale?“, ma piuttosto”quanto è grande la differenza, e di quanto siamo certi?”</p>
<p>– <strong>Jeffrey Rouder</strong>, Psicologo e Statistico, esperto di statistica bayesiana</p>
</blockquote>
</div>
<section id="introduzione" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="introduzione">Introduzione</h2>
<p>Uno dei problemi di ricerca più frequenti in psicologia riguarda il <em>confronto tra due gruppi o condizioni</em>. Ci chiediamo, ad esempio, se un gruppo di trattamento ottenga risultati migliori di un gruppo di controllo, o se un campione clinico differisca da un campione non clinico in una certa misura psicologica. In questi casi, la questione cruciale non è soltanto <em>se</em> esista una differenza, ma anche <em>quanto grande</em> essa sia e con quale grado di <em>incertezza</em> possiamo descriverla.</p>
<p>In questo capitolo affrontiamo il problema con un approccio <em>bayesiano</em>. Immaginiamo di avere una variabile continua di esito, indicata con <span class="math inline">\(y_{ig}\)</span>, che misura l’osservazione <span class="math inline">\(i\)</span> nel gruppo <span class="math inline">\(g\)</span> (dove <span class="math inline">\(g\)</span> può assumere valore 0 oppure 1). Un modello semplice e naturale assume che i punteggi in ciascun gruppo seguano una distribuzione normale con la propria media:</p>
<p><span class="math display">\[
y_{ig}\sim\mathcal N(\mu_g,\ \sigma),
\qquad \Delta=\mu_1-\mu_0 .
\]</span></p>
<p>La quantità di interesse centrale è <span class="math inline">\(\Delta\)</span>, la <strong>differenza tra le due medie</strong>.</p>
<p>Questo stesso modello può essere scritto in forma equivalente come un <em>modello di regressione lineare</em> semplice, utilizzando una variabile indicatrice <span class="math inline">\(x_i\)</span> che codifica l’appartenenza al gruppo (0 = gruppo di riferimento, 1 = gruppo sperimentale):</p>
<p><span class="math display">\[
y_i \sim \mathcal N(\alpha+\beta x_i,\ \sigma).
\]</span></p>
<p>In questa formulazione, l’intercetta <span class="math inline">\(\alpha\)</span> rappresenta la media del gruppo di riferimento (<span class="math inline">\(\mu_0\)</span>), mentre il coefficiente <span class="math inline">\(\beta\)</span> coincide con la differenza tra le due medie (<span class="math inline">\(\Delta\)</span>). Quando necessario, considereremo anche la versione <em>standardizzata</em> di questo effetto, definita come <span class="math inline">\(d = \Delta / \sigma\)</span>, che fornisce una misura della <em>dimensione dell’effetto</em> indipendente dalla scala di misura utilizzata.</p>
<p>Rispetto all’approccio frequentista tradizionale, che si concentra principalmente sul calcolo di un <em>p</em>-value per l’ipotesi nulla di uguaglianza delle medie, l’inferenza bayesiana offre una prospettiva più ricca e informativa. Essa fornisce una <em>distribuzione a posteriori</em> completa per <span class="math inline">\(\Delta\)</span>, che quantifica direttamente la nostra incertezza sulla differenza dopo aver osservato i dati. Da questa distribuzione possiamo calcolare probabilità con un significato immediato, come:</p>
<ul>
<li>la probabilità che la differenza sia positiva, <span class="math inline">\(\Pr(\Delta&gt;0 \mid \text{dati})\)</span>;</li>
<li>la probabilità che l’effetto superi una soglia di rilevanza pratica predefinita, <span class="math inline">\(\Pr(|\Delta|&gt;\text{SESOI}\mid\text{dati})\)</span>.</li>
</ul>
<p>Inoltre, il quadro bayesiano rende trasparente l’integrazione di conoscenze pregresse tramite le distribuzioni a priori e obbliga a esplicitare tutte le assunzioni su cui il modello si basa. Questo rende il processo inferenziale non solo più flessibile, ma anche più rigoroso e interpretabile dal punto di vista scientifico.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Le assunzioni del modello base
</div>
</div>
<div class="callout-body-container callout-body">
<p>Come ogni modello statistico, anche questo semplice confronto tra medie si basa su alcune assunzioni fondamentali che è importante tenere a mente. Le osservazioni sono assumed to be indipendenti tra loro, una volta tenuto conto dell’effetto del gruppo. I residui del modello, cioè la parte di variabilità non spiegata dalla gruppo appartenenza, dovrebbero seguire una distribuzione approssimativamente normale. Il modello presentato qui assume anche che la variabilità dei dati (la <span class="math inline">\(\sigma\)</span>) sia la stessa nei due gruppi; si tratta di un’ipotesi semplificatrice, ma il modello può essere esteso per accomodare il caso più generale in cui le varianze siano diverse (eteroscedasticità).</p>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
L’importanza di una Soglia di Rilevanza (SESOI)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Per evitare di sovrainterpretare differenze statisticamente significative ma trivialmente piccole, è una buona pratica metodologica definire <em>a priori</em> una Soglia di Rilevanza Scientificamente Significativa (SESOI). Stabilire, ad esempio, che una differenza di almeno 5 punti in un test cognitivo abbia un reale significato pratico, permette di ancorare le conclusioni alla sostanza del fenomeno studiato, andando oltre la semplice significatività statistica. È quindi utile riportare non solo la probabilità che l’effetto sia diverso da zero, ma anche la probabilità che superi questa soglia di rilevanza.</p>
</div>
</div>
<p>Il percorso che seguiremo in questo capitolo è semplice e strutturato. Inizieremo specificando il modello bayesiano per il confronto tra due medie, esplorandone anche varianti più robuste nel caso in cui l’assunzione di normalità risulti troppo restrittiva. Sceglieremo poi delle <em>prior debolmente informative</em>, che siano coerenti con la scala di misura della nostra variabile risultato e che permettano ai dati di “parlare” in modo predominante. Una volta stimato il modello, il focus sarà sul riportare le quantità di interesse—la differenza <span class="math inline">\(\Delta\)</span> e l’eventuale dimensione dell’effetto standardizzata <span class="math inline">\(d\)</span>—accompagnate dalle loro distribuzioni a posteriori e dalle probabilità rilevanti. Infine, valuteremo l’adeguatezza del nostro modello attraverso <em>verifiche predittive</em>, per assicurarci che sia in grado di generare dati simili a quelli osservati, e, se necessario, confronteremo modelli con assunzioni diverse per scegliere quello che meglio cattura la struttura dei nostri dati.</p>
<section id="panoramica-del-capitolo" class="level3 unnumbered unlisted"><h3 class="unnumbered unlisted anchored" data-anchor-id="panoramica-del-capitolo">Panoramica del capitolo</h3>
<ul>
<li>Le basi concettuali e statistiche che sottendono la modellazione della differenza tra medie nell’ambito del modello di regressione lineare bayesiana.</li>
<li>Le diverse strategie di codifica del predittore categoriale (dummy, centrata, a medie di cella).</li>
<li>Le strategie più efficaci per comunicare i risultati attraverso intervalli credibili e previsioni probabilistiche.</li>
</ul>
<div class="callout callout-style-simple callout-tip no-icon callout-titled" title="Prerequisiti">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prerequisiti
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Consultare l’articolo “Bayesian estimation supersedes the t test” <span class="citation" data-cites="kruschke2013bayesian">(<a href="#ref-kruschke2013bayesian" role="doc-biblioref">Kruschke, 2013</a>)</span>.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-caution no-icon callout-titled" title="Preparazione del Notebook">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Preparazione del Notebook
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Load packages</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html">requireNamespace</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">cmdstanr</span>, <span class="va">posterior</span>, <span class="va">brms</span>, <span class="va">bayestestR</span>, <span class="va">insight</span><span class="op">)</span></span>
<span><span class="fu">conflicts_prefer</span><span class="op">(</span><span class="fu">loo</span><span class="fu">::</span><span class="va"><a href="https://mc-stan.org/loo/reference/loo.html">loo</a></span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section></section><section id="il-modello-a-indicatore-e-le-quantità-di-interesse" class="level2" data-number="31.1"><h2 data-number="31.1" class="anchored" data-anchor-id="il-modello-a-indicatore-e-le-quantità-di-interesse">
<span class="header-section-number">31.1</span> Il modello a indicatore e le quantità di interesse</h2>
<p>Per confrontare due gruppi in modo rigoroso, utilizziamo un modello statistico che incorpora un predittore binario, <span class="math inline">\(x_i\)</span>, il cui valore (0 o 1) indica l’appartenenza a uno dei due gruppi. Il modello lineare che proponiamo è il seguente:</p>
<p><span class="math display">\[
y_i = \alpha + \beta x_i + \varepsilon_i, \qquad \varepsilon_i \sim \mathcal{N}(0, \sigma),
\]</span></p>
<p>dove il termine <span class="math inline">\(\varepsilon_i\)</span> rappresenta l’errore residuo, la parte di variabilità del punteggio <span class="math inline">\(y_i\)</span> che il modello non riesce a spiegare. Un’assunzione fondamentale di questo modello base è che la dispersione di questi residui, misurata dalla deviazione standard <span class="math inline">\(\sigma\)</span>, sia la stessa per entrambi i gruppi. Questa condizione è nota come ipotesi di <em>omoschedasticità</em>.</p>
<p>Le quantità centrali che vogliamo stimare—le medie dei due gruppi—sono ricavabili direttamente dai parametri del modello. Sostituendo i valori dell’indicatore, otteniamo:</p>
<ul>
<li>L’attesa per il <em>gruppo di riferimento</em> (quando <span class="math inline">\(x_i = 0\)</span>) è: <span class="math inline">\(\mathbb{E}[y \mid x=0] = \alpha\)</span>. Chiamiamo questo valore <span class="math inline">\(\mu_0\)</span>.</li>
<li>L’attesa per il <em>gruppo di confronto</em> (quando <span class="math inline">\(x_i = 1\)</span>) è: <span class="math inline">\(\mathbb{E}[y \mid x=1] = \alpha + \beta\)</span>. Chiamiamo questo valore <span class="math inline">\(\mu_1\)</span>.</li>
</ul>
<p>La differenza tra le due medie, che è la quantità di interesse primaria, risulta quindi essere esattamente il coefficiente <span class="math inline">\(\beta\)</span>:</p>
<p><span class="math display">\[
\Delta = \mu_1 - \mu_0 = (\alpha + \beta) - \alpha = \beta.
\]</span></p>
<p><em>In sintesi, l’interpretazione dei parametri è molto intuitiva:</em></p>
<ul>
<li>Il parametro <span class="math inline">\(\alpha\)</span> (l’<em>intercetta</em>) rappresenta la <em>media del gruppo di riferimento</em>.</li>
<li>Il parametro <span class="math inline">\(\beta\)</span> (la <em>pendenza</em>) rappresenta la <em>differenza media</em> tra il gruppo di confronto e il gruppo di riferimento.</li>
<li>Il parametro <span class="math inline">\(\sigma\)</span> rappresenta la <em>variabilità residua comune</em> all’interno di ciascun gruppo, assumendo che sia omogenea.</li>
</ul>
<p><strong>Una prospettiva alternativa: il modello a medie di cella</strong></p>
<p>Lo stesso modello può essere formulato in un modo che rende ancora più esplicite le medie di gruppo. Invece di esprimerlo come una funzione lineare, possiamo scriverlo direttamente specificando la media per ogni cella:</p>
<p><span class="math display">\[
y_i \sim \mathcal{N}(\mu_{x_i},\, \sigma),
\]</span></p>
<p>dove <span class="math inline">\(\mu_{x_i}\)</span> è semplicemente la media del gruppo a cui l’osservazione <span class="math inline">\(i\)</span>-esima appartiene. In pratica, questo significa che se <span class="math inline">\(x_i = 0\)</span>, allora <span class="math inline">\(y_i \sim \mathcal{N}(\mu_0, \sigma)\)</span>, e se <span class="math inline">\(x_i = 1\)</span>, allora <span class="math inline">\(y_i \sim \mathcal{N}(\mu_1, \sigma)\)</span>.</p>
<p>Questa parametrizzazione è del tutto equivalente a quella con <span class="math inline">\(\alpha\)</span> e <span class="math inline">\(\beta\)</span>, con la semplice corrispondenza <span class="math inline">\(\mu_0 = \alpha\)</span> e <span class="math inline">\(\mu_1 = \alpha + \beta\)</span>. La sua utilità risiede nel fatto che rende immediatamente visibili i parametri di interesse diretto (<span class="math inline">\(\mu_0\)</span> e <span class="math inline">\(\mu_1\)</span>) ed è spesso più semplice da comprendere concettualmente.</p>
</section><section id="la-codifica-centrata-dellindicatore" class="level2" data-number="31.2"><h2 data-number="31.2" class="anchored" data-anchor-id="la-codifica-centrata-dellindicatore">
<span class="header-section-number">31.2</span> La codifica centrata dell’indicatore</h2>
<p>Un’accortezza tecnica ma molto utile nella modellazione consiste nel <em>centrare</em> la variabile indicatrice. Invece di usare i valori 0 e 1, possiamo ridefinirla sottraendo 0.5, ottenendo così:</p>
<p><span class="math display">\[
x_c = x - \tfrac12 \in \left\{-\tfrac12,\ +\tfrac12\right\}.
\]</span></p>
<p>Il modello di regressione viene quindi riscritto utilizzando questo predittore centrato:</p>
<p><span class="math display">\[
y_i = \alpha_c + \beta_c \, x_{c,i} + \varepsilon_i.
\]</span></p>
<p>Questa piccola modifica altera in modo vantaggioso l’interpretazione dei coefficienti:</p>
<ul>
<li>Il parametro <em><span class="math inline">\(\alpha_c\)</span> (l’intercetta)</em> non è più la media del gruppo di riferimento, bensì la <em>media generale</em> (o <em>grand mean</em>) dei due gruppi, calcolata come <span class="math inline">\((\mu_0 + \mu_1)/2\)</span>.</li>
<li>Il parametro <em><span class="math inline">\(\beta_c\)</span> (la pendenza)</em> rimane invece <em>esattamente la differenza tra le due medie</em> (<span class="math inline">\(\mu_1 - \mu_0\)</span>), proprio come nel caso della codifica non centrata.</li>
</ul>
<section id="vantaggi-pratici-della-codifica-centrata" class="level3" data-number="31.2.1"><h3 data-number="31.2.1" class="anchored" data-anchor-id="vantaggi-pratici-della-codifica-centrata">
<span class="header-section-number">31.2.1</span> Vantaggi pratici della codifica centrata</h3>
<p>Questa parametrizzazione alternativa offre diversi vantaggi pratici:</p>
<ol type="1">
<li>
<em>Interpretazione immediata dell’intercetta</em>: L’intercetta <span class="math inline">\(\alpha_c\)</span> rappresenta direttamente la media complessiva del campione, una quantità spesso utile da riportare.</li>
<li>
<em>Semplicità nella specifica delle prior</em>: Risulta più intuitivo e diretto specificare distribuzioni a priori per i parametri. Possiamo scegliere una prior per <span class="math inline">\(\alpha_c\)</span> basata sulla nostra conoscenza del livello medio generale della variabile <span class="math inline">\(y\)</span> nella popolazione, e una prior separata per <span class="math inline">\(\beta_c\)</span> basata sull’ampiezza dell’effetto che ci aspettiamo o che riteniamo rilevante.</li>
<li>
<em>Stima più efficiente in modelli complessi</em>: Nei modelli gerarchici più avanzati, la centratura può spesso ridurre la correlazione tra le stime dei parametri, migliorando l’efficienza del campionatore MCMC e facilitando la convergenza.</li>
</ol>
<p><strong>Suggerimento operativo:</strong> La scelta tra la codifica standard (0/1) e quella centrata dipende dagli obiettivi dell’analisi.</p>
<ul>
<li>Utilizza la <em>codifica centrata</em> quando l’attenzione è primariamente sulla <em>differenza</em> <span class="math inline">\(\beta\)</span> e quando vuoi riportare in modo trasparente la media complessiva.</li>
<li>Utilizza la forma a <em>“medie di cella”</em> (o la codifica 0/1) quando è più conveniente o interpretabile stimare direttamente i livelli medi <span class="math inline">\(\mu_0\)</span> e <span class="math inline">\(\mu_1\)</span> per ciascun gruppo.</li>
</ul></section></section><section id="stima-con-brms" class="level2" data-number="31.3"><h2 data-number="31.3" class="anchored" data-anchor-id="stima-con-brms">
<span class="header-section-number">31.3</span> Stima con <code>brms</code>
</h2>
<p>Di seguito mostriamo <em>tre modi equivalenti</em> per stimare la differenza tra due gruppi con <code>brms</code>. Per ogni blocco indichiamo: <em>cosa fa il modello</em>, <em>come leggere i coefficienti</em>, <em>quali quantità riportare</em>.</p>
<section id="codifica-dummy-xin01-modello-standard" class="level3" data-number="31.3.1"><h3 data-number="31.3.1" class="anchored" data-anchor-id="codifica-dummy-xin01-modello-standard">
<span class="header-section-number">31.3.1</span> 1) Codifica dummy <span class="math inline">\(x\in\{0,1\}\)</span> (modello “standard”)</h3>
<p><strong>Idea.</strong> Stimiamo <span class="math inline">\(\alpha\)</span> (media del gruppo <span class="math inline">\(x=0\)</span>) e <span class="math inline">\(\beta\)</span> (differenza <span class="math inline">\(\mu_1-\mu_0\)</span>). Le <em>prior</em> <code>student_t(3, 0, 10)</code> sono <em>debolmente informative</em>: centrano i parametri a 0 e consentono ampia variabilità (code più pesanti della normale).</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#| message: false</span></span>
<span><span class="co"># install.packages(c("brms","posterior","tidyverse","bayestestR","loo","cmdstanr"))</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/paul-buerkner/brms">brms</a></span><span class="op">)</span>; <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mc-stan.org/posterior/">posterior</a></span><span class="op">)</span>; <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>; <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://easystats.github.io/bayestestR/">bayestestR</a></span><span class="op">)</span>; <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mc-stan.org/loo/">loo</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://paulbuerkner.com/brms/reference/brm.html">brm</a></span><span class="op">(</span></span>
<span>  <span class="va">y</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> <span class="va">x</span>,                 <span class="co"># Intercetta + indicatrice (0/1)</span></span>
<span>  data <span class="op">=</span> <span class="va">df</span>,</span>
<span>  family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">gaussian</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  prior <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://paulbuerkner.com/brms/reference/set_prior.html">prior</a></span><span class="op">(</span><span class="fu">student_t</span><span class="op">(</span><span class="fl">3</span>, <span class="fl">0</span>, <span class="fl">10</span><span class="op">)</span>, class <span class="op">=</span> <span class="st">"Intercept"</span><span class="op">)</span>,  <span class="co"># prior su α (media gruppo 0)</span></span>
<span>    <span class="fu"><a href="https://paulbuerkner.com/brms/reference/set_prior.html">prior</a></span><span class="op">(</span><span class="fu">student_t</span><span class="op">(</span><span class="fl">3</span>, <span class="fl">0</span>, <span class="fl">10</span><span class="op">)</span>, class <span class="op">=</span> <span class="st">"b"</span><span class="op">)</span>,          <span class="co"># prior su β (differenza)</span></span>
<span>    <span class="fu"><a href="https://paulbuerkner.com/brms/reference/set_prior.html">prior</a></span><span class="op">(</span><span class="fu">student_t</span><span class="op">(</span><span class="fl">3</span>, <span class="fl">0</span>, <span class="fl">10</span><span class="op">)</span>, class <span class="op">=</span> <span class="st">"sigma"</span><span class="op">)</span>       <span class="co"># prior su σ (half-t implicita)</span></span>
<span>  <span class="op">)</span>,</span>
<span>  backend <span class="op">=</span> <span class="st">"cmdstanr"</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">4</span>, iter <span class="op">=</span> <span class="fl">2000</span>, seed <span class="op">=</span> <span class="fl">123</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Come leggere i risultati.</strong></p>
<ul>
<li>
<code>b_Intercept</code> stima <span class="math inline">\(\mu_0\)</span>.</li>
<li>
<code>b_x</code> stima <span class="math inline">\(\Delta=\mu_1-\mu_0\)</span>.</li>
<li>
<code>sigma</code> è la deviazione standard comune. Calcoliamo anche <span class="math inline">\(d=\Delta/\sigma\)</span> e due probabilità a posteriori utili: <span class="math inline">\(\Pr(\Delta&gt;0)\)</span> e <span class="math inline">\(\Pr(|\Delta|&gt;\text{SESOI})\)</span>.</li>
</ul>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">draws</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/posterior/reference/draws_df.html">as_draws_df</a></span><span class="op">(</span><span class="va">fit</span><span class="op">)</span></span>
<span><span class="va">post</span> <span class="op">&lt;-</span> <span class="va">draws</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/transmute.html">transmute</a></span><span class="op">(</span></span>
<span>    mu0   <span class="op">=</span> <span class="va">b_Intercept</span>,          <span class="co"># = α</span></span>
<span>    mu1   <span class="op">=</span> <span class="va">b_Intercept</span> <span class="op">+</span> <span class="va">b_x</span>,    <span class="co"># = α + β</span></span>
<span>    delta <span class="op">=</span> <span class="va">b_x</span>,                  <span class="co"># = β</span></span>
<span>    sigma <span class="op">=</span> <span class="va">sigma</span>,</span>
<span>    d     <span class="op">=</span> <span class="va">delta</span> <span class="op">/</span> <span class="va">sigma</span>         <span class="co"># effetto standardizzato (pooled)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="fu">posterior</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/posterior/reference/draws_summary.html">summarise_draws</a></span><span class="op">(</span><span class="va">post</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"mu0"</span>,<span class="st">"mu1"</span>,<span class="st">"delta"</span>,<span class="st">"d"</span>,<span class="st">"sigma"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span></span>
<span></span>
<span><span class="va">SESOI</span> <span class="op">&lt;-</span> <span class="fl">5</span>  <span class="co"># definita a priori in base al contesto applicativo</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  P_delta_gt0  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">post</span><span class="op">$</span><span class="va">delta</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span>,</span>
<span>  P_delta_gtS  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">post</span><span class="op">$</span><span class="va">delta</span><span class="op">)</span> <span class="op">&gt;</span> <span class="va">SESOI</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Cosa riportare nel testo:</strong> media e intervallo credibile per <span class="math inline">\(\mu_0,\mu_1,\Delta,d\)</span>; <span class="math inline">\(\Pr(\Delta&gt;0)\)</span>; <span class="math inline">\(\Pr(|\Delta|&gt;\text{SESOI})\)</span>.</p>
</section><section id="codifica-centrata-x_cx-tfrac12" class="level3" data-number="31.3.2"><h3 data-number="31.3.2" class="anchored" data-anchor-id="codifica-centrata-x_cx-tfrac12">
<span class="header-section-number">31.3.2</span> 2) Codifica <em>centrata</em> <span class="math inline">\(x_c=x-\tfrac12\)</span>
</h3>
<p><strong>Idea.</strong> L’intercetta diventa la <em>grand mean</em> <span class="math inline">\((\mu_0+\mu_1)/2\)</span>; il coefficiente su <span class="math inline">\(x_c\)</span> è <em>direttamente</em> <span class="math inline">\(\Delta\)</span>. Le <em>prior</em> sono normali (comode quando interpretiamo <span class="math inline">\(\alpha\)</span> come media complessiva).</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df</span> <span class="op">&lt;-</span> <span class="va">df</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>xc <span class="op">=</span> <span class="va">x</span> <span class="op">-</span> <span class="fl">0.5</span><span class="op">)</span>  <span class="co"># xc ∈ {-0.5, +0.5}</span></span>
<span></span>
<span><span class="va">fit_c</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://paulbuerkner.com/brms/reference/brm.html">brm</a></span><span class="op">(</span></span>
<span>  <span class="va">y</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> <span class="va">xc</span>,</span>
<span>  data <span class="op">=</span> <span class="va">df</span>,</span>
<span>  family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">gaussian</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  prior <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://paulbuerkner.com/brms/reference/set_prior.html">prior</a></span><span class="op">(</span><span class="fu">normal</span><span class="op">(</span><span class="fl">0</span>, <span class="fl">10</span><span class="op">)</span>, class <span class="op">=</span> <span class="st">"Intercept"</span><span class="op">)</span>,   <span class="co"># prior su grand mean</span></span>
<span>    <span class="fu"><a href="https://paulbuerkner.com/brms/reference/set_prior.html">prior</a></span><span class="op">(</span><span class="fu">normal</span><span class="op">(</span><span class="fl">0</span>, <span class="fl">10</span><span class="op">)</span>, class <span class="op">=</span> <span class="st">"b"</span><span class="op">)</span>,           <span class="co"># prior sulla differenza</span></span>
<span>    <span class="fu"><a href="https://paulbuerkner.com/brms/reference/set_prior.html">prior</a></span><span class="op">(</span><span class="fu">student_t</span><span class="op">(</span><span class="fl">3</span>, <span class="fl">0</span>, <span class="fl">10</span><span class="op">)</span>, class <span class="op">=</span> <span class="st">"sigma"</span><span class="op">)</span></span>
<span>  <span class="op">)</span>,</span>
<span>  backend <span class="op">=</span> <span class="st">"cmdstanr"</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">4</span>, iter <span class="op">=</span> <span class="fl">2000</span>, seed <span class="op">=</span> <span class="fl">123</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">draws_c</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/posterior/reference/draws_df.html">as_draws_df</a></span><span class="op">(</span><span class="va">fit_c</span><span class="op">)</span></span>
<span><span class="va">post_c</span> <span class="op">&lt;-</span> <span class="va">draws_c</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/transmute.html">transmute</a></span><span class="op">(</span></span>
<span>    grand_mean <span class="op">=</span> <span class="va">b_Intercept</span>,            <span class="co"># = (μ0+μ1)/2</span></span>
<span>    delta      <span class="op">=</span> <span class="va">b_xc</span>,                   <span class="co"># = μ1 - μ0</span></span>
<span>    mu0        <span class="op">=</span> <span class="va">b_Intercept</span> <span class="op">-</span> <span class="fl">0.5</span><span class="op">*</span><span class="va">b_xc</span>, <span class="co"># ricostruzione</span></span>
<span>    mu1        <span class="op">=</span> <span class="va">b_Intercept</span> <span class="op">+</span> <span class="fl">0.5</span><span class="op">*</span><span class="va">b_xc</span>,</span>
<span>    sigma      <span class="op">=</span> <span class="va">sigma</span>,</span>
<span>    d          <span class="op">=</span> <span class="va">delta</span> <span class="op">/</span> <span class="va">sigma</span></span>
<span>  <span class="op">)</span></span>
<span><span class="fu">posterior</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/posterior/reference/draws_summary.html">summarise_draws</a></span><span class="op">(</span><span class="va">post_c</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"grand_mean"</span>,<span class="st">"mu0"</span>,<span class="st">"mu1"</span>,<span class="st">"delta"</span>,<span class="st">"d"</span>,<span class="st">"sigma"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Quando usarla:</strong> quando vuoi dare <em>prior</em> separate e intuitive su <em>media complessiva</em> e <em>differenza</em>.</p>
</section><section id="medie-di-cella-senza-intercetta" class="level3" data-number="31.3.3"><h3 data-number="31.3.3" class="anchored" data-anchor-id="medie-di-cella-senza-intercetta">
<span class="header-section-number">31.3.3</span> 3) <em>Medie di cella</em> (senza intercetta)</h3>
<p><strong>Idea.</strong> Stimiamo <em>direttamente</em> <span class="math inline">\(\mu_0\)</span> e <span class="math inline">\(\mu_1\)</span>. Vantaggio: puoi assegnare <em>prior</em> <em>indipendenti</em> sulle due medie.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df</span> <span class="op">&lt;-</span> <span class="va">df</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>group <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">x</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"G0"</span>,<span class="st">"G1"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_cells</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://paulbuerkner.com/brms/reference/brm.html">brm</a></span><span class="op">(</span></span>
<span>  <span class="va">y</span> <span class="op">~</span> <span class="fl">0</span> <span class="op">+</span> <span class="va">group</span>,              <span class="co"># niente intercetta: i coefficienti SONO le medie</span></span>
<span>  data <span class="op">=</span> <span class="va">df</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">gaussian</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  prior <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://paulbuerkner.com/brms/reference/set_prior.html">prior</a></span><span class="op">(</span><span class="fu">normal</span><span class="op">(</span><span class="fl">0</span>, <span class="fl">10</span><span class="op">)</span>, class <span class="op">=</span> <span class="st">"b"</span>, coef <span class="op">=</span> <span class="st">"groupG0"</span><span class="op">)</span>,  <span class="co"># prior su μ0</span></span>
<span>    <span class="fu"><a href="https://paulbuerkner.com/brms/reference/set_prior.html">prior</a></span><span class="op">(</span><span class="fu">normal</span><span class="op">(</span><span class="fl">0</span>, <span class="fl">10</span><span class="op">)</span>, class <span class="op">=</span> <span class="st">"b"</span>, coef <span class="op">=</span> <span class="st">"groupG1"</span><span class="op">)</span>,  <span class="co"># prior su μ1</span></span>
<span>    <span class="fu"><a href="https://paulbuerkner.com/brms/reference/set_prior.html">prior</a></span><span class="op">(</span><span class="fu">student_t</span><span class="op">(</span><span class="fl">3</span>, <span class="fl">0</span>, <span class="fl">10</span><span class="op">)</span>, class <span class="op">=</span> <span class="st">"sigma"</span><span class="op">)</span></span>
<span>  <span class="op">)</span>,</span>
<span>  backend <span class="op">=</span> <span class="st">"cmdstanr"</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">4</span>, iter <span class="op">=</span> <span class="fl">2000</span>, seed <span class="op">=</span> <span class="fl">123</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">draws_cells</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/posterior/reference/draws_df.html">as_draws_df</a></span><span class="op">(</span><span class="va">fit_cells</span><span class="op">)</span></span>
<span><span class="va">post_cells</span> <span class="op">&lt;-</span> <span class="va">draws_cells</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/transmute.html">transmute</a></span><span class="op">(</span></span>
<span>    mu0   <span class="op">=</span> <span class="va">b_groupG0</span>,</span>
<span>    mu1   <span class="op">=</span> <span class="va">b_groupG1</span>,</span>
<span>    delta <span class="op">=</span> <span class="va">b_groupG1</span> <span class="op">-</span> <span class="va">b_groupG0</span>,</span>
<span>    sigma <span class="op">=</span> <span class="va">sigma</span>,</span>
<span>    d     <span class="op">=</span> <span class="va">delta</span> <span class="op">/</span> <span class="va">sigma</span></span>
<span>  <span class="op">)</span></span>
<span><span class="fu">posterior</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/posterior/reference/draws_summary.html">summarise_draws</a></span><span class="op">(</span><span class="va">post_cells</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"mu0"</span>,<span class="st">"mu1"</span>,<span class="st">"delta"</span>,<span class="st">"d"</span>,<span class="st">"sigma"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Quando usarla:</strong> quando vuoi controllare in modo esplicito le <em>prior</em> sulle due medie (e.g., vincoli diversi per ciascun gruppo).</p>
<div class="callout callout-style-simple callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota sulle <em>prior</em> indotte
</div>
</div>
<div class="callout-body-container callout-body">
<p>Con la forma “intercetta + differenza”, <em>prior</em> indipendenti su <span class="math inline">\(\alpha\)</span> e <span class="math inline">\(\beta\)</span> <em>inducono</em> correlazione tra <span class="math inline">\(\mu_0\)</span> e <span class="math inline">\(\mu_1\)</span> (<span class="math inline">\(\mu_0=\alpha,\ \mu_1=\alpha+\beta\)</span>). Se desideri <em>indipendenza a priori</em> tra <span class="math inline">\(\mu_0\)</span> e <span class="math inline">\(\mu_1\)</span>, usa la parametrizzazione <em>a medie di cella</em>.</p>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nomi dei coefficienti: attenzione alla codifica
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Se <code>x</code> è <em>numerica</em> (0/1): il coefficiente si chiama tipicamente <code>b_x</code>.</li>
<li>Se <code>x</code> è <em>fattore</em> (due livelli): il coefficiente sarà <code>b_x1</code> o <code>b_x&lt;nomeLivello&gt;</code>.</li>
<li>Con <code>0 + group</code>: i coefficienti si chiamano <code>b_groupG0</code>, <code>b_groupG1</code> (le etichette dipendono dai livelli della variabile). Controlla sempre i <em>nomi esatti</em> in <code>names(as_draws_df(fit))</code> prima di costruire le trasformazioni.</li>
</ul>
</div>
</div>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Diagnostica minima da riportare
</div>
</div>
<div class="callout-body-container callout-body">
<p>Verifica <code>Rhat</code> (~1.00), <code>ESS</code>, assenza di <em>divergenze</em> e PPC coerenti. Se necessario aumenta <code>adapt_delta</code> (0.95–0.99) e <code>max_treedepth</code> (es. 15).</p>
</div>
</div>
<blockquote class="blockquote">
<p><em>Riassunto operativo.</em> Qualunque parametrizzazione tu scelga, riporta sempre: <span class="math inline">\(\mu_0,\mu_1,\Delta,d\)</span> con intervalli credibili e le probabilità <span class="math inline">\(\Pr(\Delta&gt;0)\)</span> e <span class="math inline">\(\Pr(|\Delta|&gt;\text{SESOI})\)</span>.</p>
</blockquote>
</section><section id="interpretazione-operativa-cosa-leggere-nelle-posteriori" class="level3" data-number="31.3.4"><h3 data-number="31.3.4" class="anchored" data-anchor-id="interpretazione-operativa-cosa-leggere-nelle-posteriori">
<span class="header-section-number">31.3.4</span> Interpretazione operativa (cosa leggere nelle posteriori)</h3>
<p>Di seguito come <em>leggere e riportare</em> i risultati a seconda della codifica usata per il predittore binario.</p>
<p><em>1) Codifica dummy <span class="math inline">\(D\in\{0,1\}\)</span></em></p>
<ul>
<li>
<code>Intercept</code> <span class="math inline">\(\Rightarrow\)</span> <em><span class="math inline">\(\mu_0\)</span></em> (media del gruppo <span class="math inline">\(D=0\)</span>).</li>
<li>Coefficiente su <code>D</code> <span class="math inline">\(\Rightarrow\)</span> <em><span class="math inline">\(\Delta=\mu_1-\mu_0\)</span></em> (differenza tra medie).</li>
<li>Da riportare sempre: <span class="math inline">\(\mu_1=\mu_0+\Delta\)</span>, <span class="math inline">\(\sigma\)</span>, <span class="math inline">\(d=\Delta/\sigma\)</span>, <span class="math inline">\(\Pr(\Delta&gt;0)\)</span>, <span class="math inline">\(\Pr(|\Delta|&gt;\text{SESOI})\)</span>.</li>
</ul>
<p><em>2) Codifica centrata <span class="math inline">\(D_c=D-\tfrac12\in\{-\tfrac12,+\tfrac12\}\)</span></em></p>
<ul>
<li>
<code>Intercept</code> <span class="math inline">\(\Rightarrow\)</span> <em>grand mean</em> <span class="math inline">\(\displaystyle \alpha=\tfrac{\mu_0+\mu_1}{2}\)</span>.</li>
<li>Coefficiente su <code>D_c</code> <span class="math inline">\(\Rightarrow\)</span> <em><span class="math inline">\(\Delta=\mu_1-\mu_0\)</span></em>.</li>
<li>Ricostruzioni utili: <span class="math inline">\(\mu_0=\alpha-\tfrac12\Delta\)</span>, <span class="math inline">\(\mu_1=\alpha+\tfrac12\Delta\)</span>.</li>
<li>Da riportare come sopra: <span class="math inline">\(\Delta\)</span>, <span class="math inline">\(d\)</span>, <span class="math inline">\(\Pr(\Delta&gt;0)\)</span>, <span class="math inline">\(\Pr(|\Delta|&gt;\text{SESOI})\)</span>.</li>
</ul>
<p><em>3) Parametrizzazione a “medie di cella” (senza intercetta)</em></p>
<ul>
<li>I coefficienti <em>sono direttamente</em> <span class="math inline">\(\mu_0\)</span> e <span class="math inline">\(\mu_1\)</span>.</li>
<li>La differenza si ottiene come <em>combinazione lineare a posteriori</em>: <span class="math inline">\(\Delta=\mu_1-\mu_0\)</span>.</li>
<li>Da riportare: <span class="math inline">\(\mu_0,\mu_1,\Delta,\sigma,d,\Pr(\Delta&gt;0),\Pr(|\Delta|&gt;\text{SESOI})\)</span>.</li>
</ul>
<div class="callout callout-style-simple callout-tip no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><em>Promemoria pratico.</em> Indipendentemente dalla codifica, l’<em>oggetto sostantivo</em> è sempre <span class="math inline">\(\Delta\)</span> (e, quando serve, <span class="math inline">\(d=\Delta/\sigma\)</span>). Per la discussione applicativa affianca sempre:</p>
<ul>
<li>un <em>intervallo credibile</em> per <span class="math inline">\(\Delta\)</span>;</li>
<li>
<span class="math inline">\(\Pr(\Delta&gt;0\mid\text{dati})\)</span>;</li>
<li>
<span class="math inline">\(\Pr(|\Delta|&gt;\text{SESOI}\mid\text{dati})\)</span> con una SESOI definita <em>prima</em> dell’analisi.</li>
</ul>
</div>
</div>
</div>
<p><em>Esempio di lettura sintetica.</em> Se la posteriore di <span class="math inline">\(\Delta\)</span> ha media 4.8, intervallo credibile 95% <span class="math inline">\([2.1,\ 7.4]\)</span>, <span class="math inline">\(\Pr(\Delta&gt;0)=0.99\)</span> e <span class="math inline">\(\Pr(|\Delta|&gt;5)=0.46\)</span> (SESOI = 5), allora: la differenza media è plausibilmente positiva, ma la probabilità di superare la soglia di rilevanza scelta è circa <em>46%</em> (informazione utile per l’interpretazione sostantiva).</p>
</section></section><section id="confronto-tra-approcci-frequentista-e-bayesiano" class="level2" data-number="31.4"><h2 data-number="31.4" class="anchored" data-anchor-id="confronto-tra-approcci-frequentista-e-bayesiano">
<span class="header-section-number">31.4</span> Confronto tra approcci: frequentista e bayesiano</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 37%">
<col style="width: 50%">
</colgroup>
<thead><tr class="header">
<th>Aspetto</th>
<th>Frequentista</th>
<th>Bayesiano</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Rappresentazione</td>
<td>Intervallo di confidenza</td>
<td>Intervallo di credibilità</td>
</tr>
<tr class="even">
<td>Unità di analisi</td>
<td>Compatibilità dei dati con <span class="math inline">\(H_0\)</span>
</td>
<td>Distribuzione a posteriori su <span class="math inline">\(\Delta\)</span> e probabilità su regioni di interesse (SESOI/ROPE)</td>
</tr>
<tr class="odd">
<td>Ipotesi di partenza</td>
<td>Ipotesi nulla puntuale come riferimento</td>
<td>Modello + prior; non richiede un <span class="math inline">\(H_0\)</span> puntuale, ma consente ipotesi su regioni parametriche</td>
</tr>
<tr class="even">
<td>Uso di informazione pregressa</td>
<td>Non previsto</td>
<td>Integrabile tramite prior</td>
</tr>
<tr class="odd">
<td>Domanda tipica</td>
<td>“Quanto sono rari i dati se <span class="math inline">\(\Delta=0\)</span>?”</td>
<td>“Quanto è plausibile che <span class="math inline">\(\Delta\)</span> superi una soglia definita (SESOI)?”</td>
</tr>
</tbody>
</table></section><section id="esempio-istruzione-materna-e-qi" class="level2" data-number="31.5"><h2 data-number="31.5" class="anchored" data-anchor-id="esempio-istruzione-materna-e-qi">
<span class="header-section-number">31.5</span> Esempio: istruzione materna e QI</h2>
<p>Usiamo il dataset <code>kidiq</code> (sviluppo cognitivo): per ogni bambino abbiamo il <em>QI</em> (<code>kid_score</code>) e se la <em>madre ha il diploma</em> (<code>mom_hs</code>: 0 = non diplomata; 1 = diplomata).</p>
<p><strong>Domanda:</strong> <em>i figli di madri diplomate hanno, in media, un QI diverso?</em> Inoltre, fissiamo a titolo esemplificativo una <em>SESOI = 5 punti</em> di QI (soglia di rilevanza pratica da motivare nel contesto).</p>
<section id="esplorazione-iniziale-dei-dati" class="level3" data-number="31.5.1"><h3 data-number="31.5.1" class="anchored" data-anchor-id="esplorazione-iniziale-dei-dati">
<span class="header-section-number">31.5.1</span> Esplorazione iniziale dei dati</h3>
<p><strong>1) Import, pulizia minima e etichette chiare.</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">kidiq</span> <span class="op">&lt;-</span> <span class="fu">rio</span><span class="fu">::</span><span class="fu"><a href="http://gesistsa.github.io/rio/reference/import.html">import</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"data"</span>, <span class="st">"kidiq.dta"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Ricodifica esplicita per leggibilità nei grafici e nelle tabelle</span></span>
<span><span class="va">kidiq</span> <span class="op">&lt;-</span> <span class="va">kidiq</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    mom_hs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">mom_hs</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span>,</span>
<span>                    labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Non diplomata"</span>, <span class="st">"Diplomata"</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="co"># Controllo veloce: struttura e eventuali missing</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">kidiq</span><span class="op">)</span></span>
<span><span class="co">#&gt; Rows: 434</span></span>
<span><span class="co">#&gt; Columns: 5</span></span>
<span><span class="co">#&gt; $ kid_score &lt;dbl&gt; 65, 98, 85, 83, 115, 98, 69, 106, 102, 95, 91, 58, 84, 78, 1…</span></span>
<span><span class="co">#&gt; $ mom_hs    &lt;fct&gt; Diplomata, Diplomata, Diplomata, Diplomata, Diplomata, Non d…</span></span>
<span><span class="co">#&gt; $ mom_iq    &lt;dbl&gt; 121.1, 89.4, 115.4, 99.4, 92.7, 107.9, 138.9, 125.1, 81.6, 9…</span></span>
<span><span class="co">#&gt; $ mom_work  &lt;dbl&gt; 4, 4, 4, 3, 4, 1, 4, 3, 1, 1, 1, 4, 4, 4, 2, 1, 3, 3, 4, 3, …</span></span>
<span><span class="co">#&gt; $ mom_age   &lt;dbl&gt; 27, 25, 27, 25, 27, 18, 20, 23, 24, 19, 23, 24, 27, 26, 24, …</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">kidiq</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"kid_score"</span>, <span class="st">"mom_hs"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; kid_score    mom_hs </span></span>
<span><span class="co">#&gt;         0         0</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>2) Statistiche descrittive per gruppo.</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">kidiq</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">mom_hs</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>    n        <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>    media_QI <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">kid_score</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>    sd_QI    <span class="op">=</span> <span class="fu">sd</span><span class="op">(</span><span class="va">kid_score</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>    mediana  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">kid_score</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>    IQR      <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/IQR.html">IQR</a></span><span class="op">(</span><span class="va">kid_score</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 6</span></span>
<span><span class="co">#&gt;   mom_hs            n media_QI sd_QI mediana   IQR</span></span>
<span><span class="co">#&gt;   &lt;fct&gt;         &lt;int&gt;    &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 Non diplomata    93     77.5  22.6      80    37</span></span>
<span><span class="co">#&gt; 2 Diplomata       341     89.3  19.0      92    26</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Lettura rapida: riportiamo numerosità, media e deviazione standard (oltre a mediana e IQR per un controllo di robustezza). Nel nostro campione tipicamente i gruppi sono <em>sbilanciati</em> (ad es., ~93 vs ~341): è un’informazione utile per interpretare precisione e incertezza delle stime.</p>
</blockquote>
<p><strong>3) Visualizzazione della distribuzione nei due gruppi.</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">kidiq</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">mom_hs</span>, y <span class="op">=</span> <span class="va">kid_score</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_violin.html">geom_violin</a></span><span class="op">(</span>trim <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.12</span>, outlier.shape <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.08</span>, alpha <span class="op">=</span> <span class="fl">0.25</span>, size <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="st">"Istruzione materna"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"QI del bambino"</span></span>
<span>  <span class="op">)</span> </span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="08_two_means_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Cosa mostra il grafico: le <em>medie</em> sembrano diverse, ma le <em>distribuzioni</em> si sovrappongono in modo consistente. È un pattern tipico in psicologia: la differenza media non esaurisce l’informazione: servono <em>stima dell’ampiezza</em>, <em>incertezza</em> e, se possibile, <em>rilevanza pratica</em> (SESOI).</p>
</blockquote>
<p><strong>Domanda guida per l’analisi inferenziale</strong></p>
<p>La differenza osservata è compatibile con la sola variabilità campionaria oppure suggerisce <em>una tendenza nella popolazione</em>?</p>
<p>Per rispondere, nel seguito stimiamo la <em>differenza tra le medie</em> con approccio <em>frequentista</em> (t-test) e con approccio <em>bayesiano</em> (modello gaussiano con <code>brms</code>), riportando anche le <em>probabilità a posteriori</em> rispetto alla SESOI.</p>
<section id="approccio-frequentista" class="level4" data-number="31.5.1.1"><h4 data-number="31.5.1.1" class="anchored" data-anchor-id="approccio-frequentista">
<span class="header-section-number">31.5.1.1</span> Approccio frequentista</h4>
<p>Per verificare se la <em>differenza media</em> osservata può essere attribuita alla sola variabilità campionaria, applichiamo un <em>t-test per campioni indipendenti</em> (versione con <em>varianze uguali</em>):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span></span>
<span>  <span class="va">kid_score</span> <span class="op">~</span> <span class="va">mom_hs</span>, </span>
<span>  data <span class="op">=</span> <span class="va">kidiq</span>, </span>
<span>  var.equal <span class="op">=</span> <span class="cn">TRUE</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Two Sample t-test</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; data:  kid_score by mom_hs</span></span>
<span><span class="co">#&gt; t = -5, df = 432, p-value = 0.0000006</span></span>
<span><span class="co">#&gt; alternative hypothesis: true difference in means between group Non diplomata and group Diplomata is not equal to 0</span></span>
<span><span class="co">#&gt; 95 percent confidence interval:</span></span>
<span><span class="co">#&gt;  -16.34  -7.21</span></span>
<span><span class="co">#&gt; sample estimates:</span></span>
<span><span class="co">#&gt; mean in group Non diplomata     mean in group Diplomata </span></span>
<span><span class="co">#&gt;                        77.5                        89.3</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Interpretazione.</strong></p>
<ul>
<li>Le <em>medie campionarie</em> sono circa 77.6 (madri non diplomate) e 89.3 (madri diplomate).</li>
<li>La <em>differenza</em> (gruppo 1 − gruppo 0) è ~ <em>+11.8 punti QI</em>.</li>
<li>L’IC al 95% stampato da R si riferisce a (gruppo 0 − gruppo 1) ed è <span class="math inline">\([-16.34,\ -7.21]\)</span>; quindi, per (gruppo 1 − gruppo 0) l’IC corrispondente è <em>[+7.21, +16.34]</em>.</li>
<li>Il <em>p</em>-value <span class="math inline">\(= 6\times 10^{-7}\)</span> indica che, <em>se</em> nella popolazione non ci fosse differenza (<span class="math inline">\(\mu_1=\mu_0\)</span>), sarebbe molto raro osservare una differenza almeno così grande. <em>(Non è la probabilità che <span class="math inline">\(H_0\)</span> sia vera.)</em>
</li>
</ul>
<p><strong>Assunzioni e note pratiche.</strong></p>
<ul>
<li>Il test qui usa <em>varianze uguali</em> (<code>var.equal=TRUE</code>). In pratica è spesso preferibile la versione <em>di Welch</em> (default di <code>t.test</code>, cioè senza <code>var.equal=TRUE</code>), più robusta a varianze diverse e sbilanciamento tra gruppi.</li>
<li>L’inferenza frequentista fornisce una decisione rispetto a <span class="math inline">\(H_0\)</span> e un IC; <em>non</em> restituisce la probabilità che l’effetto superi una soglia di interesse applicativo.</li>
</ul>
<p>Nel paragrafo successivo stimiamo la stessa differenza con l’<em>approccio bayesiano</em>, ottenendo una <em>distribuzione a posteriori</em> per <span class="math inline">\(\Delta\)</span> e quantità direttamente interpretabili come <span class="math inline">\(\Pr(\Delta&gt;0)\)</span> e <span class="math inline">\(\Pr(|\Delta|&gt;\text{SESOI})\)</span>.</p>
</section><section id="approccio-bayesiano" class="level4" data-number="31.5.1.2"><h4 data-number="31.5.1.2" class="anchored" data-anchor-id="approccio-bayesiano">
<span class="header-section-number">31.5.1.2</span> Approccio bayesiano</h4>
<p>Con <code>mom_hs</code> codificata come <em>0 = non diplomata</em> e <em>1 = diplomata</em>, il modello</p>
<p><span class="math display">\[
y_i \sim \mathcal N(\alpha+\beta\,\text{mom\_hs}_i,\ \sigma)
\]</span></p>
<p>si interpreta così:</p>
<ul>
<li>
<span class="math inline">\(\alpha\)</span> = media del gruppo <em>mom_hs = 0</em>;</li>
<li>
<span class="math inline">\(\beta = \Delta\)</span> = <em>differenza tra medie</em> (gruppo 1 − gruppo 0);</li>
<li>
<span class="math inline">\(\sigma\)</span> = deviazione standard residua (assunta uguale nei due gruppi).</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Assicuriamoci che la referenza sia "Non diplomata"</span></span>
<span><span class="va">kidiq</span><span class="op">$</span><span class="va">mom_hs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/relevel.html">relevel</a></span><span class="op">(</span><span class="va">kidiq</span><span class="op">$</span><span class="va">mom_hs</span>, ref <span class="op">=</span> <span class="st">"Non diplomata"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://paulbuerkner.com/brms/reference/brm.html">brm</a></span><span class="op">(</span></span>
<span>  <span class="va">kid_score</span> <span class="op">~</span> <span class="va">mom_hs</span>,</span>
<span>  data   <span class="op">=</span> <span class="va">kidiq</span>,</span>
<span>  family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">gaussian</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  backend <span class="op">=</span> <span class="st">"cmdstanr"</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">4</span>, iter <span class="op">=</span> <span class="fl">2000</span>, seed <span class="op">=</span> <span class="fl">123</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># ===== Ponte sicuro tra nomi "umani" e nomi dei draw =====</span></span>
<span><span class="co"># Termini dei coefficienti a livello fissato (esclude l'intercetta)</span></span>
<span><span class="va">term_names</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://generics.r-lib.org/reference/setops.html">setdiff</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/fixed.effects.html">fixef</a></span><span class="op">(</span><span class="va">fit_1</span><span class="op">)</span><span class="op">)</span>, <span class="st">"Intercept"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/stopifnot.html">stopifnot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">term_names</span><span class="op">)</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span>         <span class="co"># qui ci aspettiamo un solo coefficiente: "mom_hsDiplomata"</span></span>
<span></span>
<span><span class="va">b_name</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"b_"</span>, <span class="va">term_names</span><span class="op">)</span>         <span class="co"># es. "b_mom_hsDiplomata"</span></span>
<span></span>
<span><span class="va">dr</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/posterior/reference/draws_df.html">as_draws_df</a></span><span class="op">(</span><span class="va">fit_1</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Quantità di interesse</span></span>
<span><span class="va">post</span> <span class="op">&lt;-</span> <span class="va">dr</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/transmute.html">transmute</a></span><span class="op">(</span></span>
<span>    mu0   <span class="op">=</span> <span class="va">b_Intercept</span>,         <span class="co"># media del gruppo di riferimento (Non diplomata)</span></span>
<span>    delta <span class="op">=</span> <span class="va">.data</span><span class="op">[[</span><span class="va">b_name</span><span class="op">]</span><span class="op">]</span>,     <span class="co"># differenza vs referenza: (Diplomata - Non diplomata)</span></span>
<span>    mu1   <span class="op">=</span> <span class="va">b_Intercept</span> <span class="op">+</span> <span class="va">delta</span>, <span class="co"># media del gruppo "Diplomata"</span></span>
<span>    sigma <span class="op">=</span> <span class="va">sigma</span>,</span>
<span>    d     <span class="op">=</span> <span class="va">delta</span> <span class="op">/</span> <span class="va">sigma</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">SESOI</span> <span class="op">&lt;-</span> <span class="fl">5</span></span>
<span><span class="fu">posterior</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/posterior/reference/draws_summary.html">summarise_draws</a></span><span class="op">(</span><span class="va">post</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"mu0"</span>,<span class="st">"mu1"</span>,<span class="st">"delta"</span>,<span class="st">"d"</span>,<span class="st">"sigma"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 5 × 10</span></span>
<span><span class="co">#&gt;   variable   mean median    sd   mad     q5    q95  rhat ess_bulk ess_tail</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;     &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 mu0      77.570 77.559 2.030 2.016 74.205 80.885 1.000 3811.388 2972.604</span></span>
<span><span class="co">#&gt; 2 mu1      89.308 89.307 1.063 1.066 87.602 91.079 1.000 3931.890 2780.415</span></span>
<span><span class="co">#&gt; 3 delta    11.737 11.787 2.309 2.309  7.911 15.506 1.000 4154.701 3119.643</span></span>
<span><span class="co">#&gt; 4 d         0.591  0.593 0.118 0.120  0.395  0.783 1.000 4130.593 3034.413</span></span>
<span><span class="co">#&gt; 5 sigma    19.894 19.868 0.702 0.709 18.780 21.073 1.000 3713.284 3095.218</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  P_delta_gt0    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">post</span><span class="op">$</span><span class="va">delta</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span>,          <span class="co"># Pr(Δ &gt; 0 | dati)</span></span>
<span>  P_absDelta_gtS <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">post</span><span class="op">$</span><span class="va">delta</span><span class="op">)</span> <span class="op">&gt;</span> <span class="va">SESOI</span><span class="op">)</span>  <span class="co"># Pr(|Δ| &gt; 5 | dati)</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt;    P_delta_gt0 P_absDelta_gtS </span></span>
<span><span class="co">#&gt;          1.000          0.999</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Come leggere i risultati:</strong></p>
<ul>
<li><p><code>mu0</code> e <code>mu1</code> sono le medie di gruppo stimate (con incertezza).</p></li>
<li><p><code>delta</code> è la differenza media <span class="math inline">\((\mu_1-\mu_0)\)</span>; <code>d</code> è la versione standardizzata.</p></li>
<li>
<p>Le due probabilità a posteriori rispondono a domande pratiche:</p>
<ul>
<li>
<span class="math inline">\(\Pr(\Delta&gt;0\mid\text{dati})\)</span>: quanto è plausibile che i figli di madri diplomate abbiano un QI medio <em>maggiore</em>?</li>
<li>
<span class="math inline">\(\Pr(|\Delta|&gt;\text{SESOI}\mid\text{dati})\)</span>: quanto è plausibile che la differenza <em>superi 5 punti</em> (soglia di rilevanza scelta)?</li>
</ul>
</li>
</ul></section></section></section><section id="approfondimenti-bayesiani" class="level2" data-number="31.6"><h2 data-number="31.6" class="anchored" data-anchor-id="approfondimenti-bayesiani">
<span class="header-section-number">31.6</span> Approfondimenti bayesiani</h2>
<p>Finora abbiamo stimato la differenza tra i gruppi e le relative probabilità a posteriori. Qui vediamo come <em>controllare l’adeguatezza del modello</em> e, se serve, <em>raffinarlo</em>. Usiamo tre strumenti: (1) verifiche predittive a posteriori (<em>PPC</em>), (2) verifiche a priori, (3) confronto predittivo tra modelli.</p>
<section id="posterior-predictive-checks-ppc" class="level3" data-number="31.6.1"><h3 data-number="31.6.1" class="anchored" data-anchor-id="posterior-predictive-checks-ppc">
<span class="header-section-number">31.6.1</span> 1) Posterior predictive checks (PPC)</h3>
<p>L’idea è semplice: il modello dovrebbe essere in grado di <em>rigenerare</em> dati simili a quelli osservati.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Verifica globale (densità osservata vs replicata dal modello)</span></span>
<span><span class="fu"><a href="https://mc-stan.org/bayesplot/reference/pp_check.html">pp_check</a></span><span class="op">(</span><span class="va">fit_1</span><span class="op">)</span>   <span class="co"># default: dens_overlay</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="08_two_means_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Cosa guardare.</strong></p>
<ul>
<li>
<em>Forma</em>: la distribuzione simulata copre quella osservata? Ci sono code o asimmetrie non riprodotte?</li>
</ul></section><section id="verifica-predittiva-a-priori" class="level3" data-number="31.6.2"><h3 data-number="31.6.2" class="anchored" data-anchor-id="verifica-predittiva-a-priori">
<span class="header-section-number">31.6.2</span> 2) Verifica predittiva <em>a priori</em>
</h3>
<p>Serve a controllare se le <em>prior</em> producono dati <em>plausibili</em> prima di vedere i dati.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pri</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="fu"><a href="https://paulbuerkner.com/brms/reference/set_prior.html">prior</a></span><span class="op">(</span><span class="fu">normal</span><span class="op">(</span><span class="fl">90</span>, <span class="fl">20</span><span class="op">)</span>, class <span class="op">=</span> <span class="st">"Intercept"</span><span class="op">)</span>,  <span class="co"># scala QI</span></span>
<span>  <span class="fu"><a href="https://paulbuerkner.com/brms/reference/set_prior.html">prior</a></span><span class="op">(</span><span class="fu">normal</span><span class="op">(</span><span class="fl">0</span>, <span class="fl">15</span><span class="op">)</span>,  class <span class="op">=</span> <span class="st">"b"</span><span class="op">)</span>,          <span class="co"># differenza attesa moderata</span></span>
<span>  <span class="fu"><a href="https://paulbuerkner.com/brms/reference/set_prior.html">prior</a></span><span class="op">(</span><span class="fu">student_t</span><span class="op">(</span><span class="fl">3</span>, <span class="fl">0</span>, <span class="fl">20</span><span class="op">)</span>, class <span class="op">=</span> <span class="st">"sigma"</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_prior</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://paulbuerkner.com/brms/reference/brm.html">brm</a></span><span class="op">(</span></span>
<span>  <span class="va">kid_score</span> <span class="op">~</span> <span class="va">mom_hs</span>,</span>
<span>  data <span class="op">=</span> <span class="va">kidiq</span>,</span>
<span>  family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">gaussian</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  prior <span class="op">=</span> <span class="va">pri</span>,</span>
<span>  sample_prior <span class="op">=</span> <span class="st">"only"</span>,       <span class="co"># ignora i dati: simula dai prior</span></span>
<span>  backend <span class="op">=</span> <span class="st">"cmdstanr"</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">2</span>, iter <span class="op">=</span> <span class="fl">1000</span>, seed <span class="op">=</span> <span class="fl">123</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://mc-stan.org/bayesplot/reference/pp_check.html">pp_check</a></span><span class="op">(</span><span class="va">fit_prior</span>, ndraws <span class="op">=</span> <span class="fl">100</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="08_two_means_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretazione</strong>: se i dati simulati <em>a priori</em> cadono in range irrealistici (es. molti QI &lt; 30 o &gt; 180), le prior vanno <em>allineate</em> alla conoscenza di dominio.</p>
</section><section id="varianti-del-modello-quando-i-ppc-suggeriscono-limiti" class="level3" data-number="31.6.3"><h3 data-number="31.6.3" class="anchored" data-anchor-id="varianti-del-modello-quando-i-ppc-suggeriscono-limiti">
<span class="header-section-number">31.6.3</span> 3) Varianti del modello (quando i PPC suggeriscono limiti)</h3>
<p><em>Code pesanti / outlier</em> → <em>t di Student</em>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_t</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://paulbuerkner.com/brms/reference/brm.html">brm</a></span><span class="op">(</span><span class="va">kid_score</span> <span class="op">~</span> <span class="va">mom_hs</span>, family <span class="op">=</span> <span class="fu"><a href="https://paulbuerkner.com/brms/reference/brmsfamily.html">student</a></span><span class="op">(</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">kidiq</span>,</span>
<span>               backend <span class="op">=</span> <span class="st">"cmdstanr"</span>, chains <span class="op">=</span> <span class="fl">4</span>, iter <span class="op">=</span> <span class="fl">2000</span>, seed <span class="op">=</span> <span class="fl">123</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Varianze diverse per gruppo</em> → eteroscedastico:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_het</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://paulbuerkner.com/brms/reference/brm.html">brm</a></span><span class="op">(</span><span class="fu"><a href="https://paulbuerkner.com/brms/reference/brmsformula.html">bf</a></span><span class="op">(</span><span class="va">kid_score</span> <span class="op">~</span> <span class="va">mom_hs</span>, <span class="va">sigma</span> <span class="op">~</span> <span class="va">mom_hs</span><span class="op">)</span>,</span>
<span>                 family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">gaussian</a></span><span class="op">(</span><span class="op">)</span>,  data <span class="op">=</span> <span class="va">kidiq</span>,</span>
<span>                 backend <span class="op">=</span> <span class="st">"cmdstanr"</span>, chains <span class="op">=</span> <span class="fl">4</span>, iter <span class="op">=</span> <span class="fl">2000</span>, seed <span class="op">=</span> <span class="fl">123</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Asimmetria</em> → skew-normal:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_sn</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://paulbuerkner.com/brms/reference/brm.html">brm</a></span><span class="op">(</span><span class="va">kid_score</span> <span class="op">~</span> <span class="va">mom_hs</span>, family <span class="op">=</span> <span class="fu"><a href="https://paulbuerkner.com/brms/reference/brmsfamily.html">skew_normal</a></span><span class="op">(</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">kidiq</span>,</span>
<span>              backend <span class="op">=</span> <span class="st">"cmdstanr"</span>, chains <span class="op">=</span> <span class="fl">4</span>, iter <span class="op">=</span> <span class="fl">2000</span>, seed <span class="op">=</span> <span class="fl">123</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dopo l’eventuale rifit, ripeti i <em>PPC</em> (globali e per gruppo).</p>
</section><section id="confronto-predittivo-tra-modelli-looelpd" class="level3" data-number="31.6.4"><h3 data-number="31.6.4" class="anchored" data-anchor-id="confronto-predittivo-tra-modelli-looelpd">
<span class="header-section-number">31.6.4</span> 4) Confronto predittivo tra modelli (LOO/ELPD)</h3>
<p>Scegliamo il modello che <em>predice meglio</em> nuovi dati simili a quelli osservati.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">loo_fit1</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/loo/reference/loo.html">loo</a></span><span class="op">(</span><span class="va">fit_1</span><span class="op">)</span></span>
<span><span class="va">loo_fit_t</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/loo/reference/loo.html">loo</a></span><span class="op">(</span><span class="va">fit_t</span><span class="op">)</span></span>
<span><span class="va">loo_fit_het</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/loo/reference/loo.html">loo</a></span><span class="op">(</span><span class="va">fit_het</span><span class="op">)</span></span>
<span><span class="va">loo_fit_sn</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/loo/reference/loo.html">loo</a></span><span class="op">(</span><span class="va">fit_sn</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://mc-stan.org/loo/reference/loo_compare.html">loo_compare</a></span><span class="op">(</span><span class="va">loo_fit1</span>, <span class="va">loo_fit_t</span>, <span class="va">loo_fit_het</span>, <span class="va">loo_fit_sn</span><span class="op">)</span></span>
<span><span class="co">#&gt;         elpd_diff se_diff</span></span>
<span><span class="co">#&gt; fit_sn   0.0       0.0   </span></span>
<span><span class="co">#&gt; fit_het -6.0       5.9   </span></span>
<span><span class="co">#&gt; fit_1   -7.4       5.3   </span></span>
<span><span class="co">#&gt; fit_t   -8.8       5.5</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nel confronto tra modelli, un modello migliore è caratterizzato da un valore di ELPD più elevato. Quando la differenza nell’ELPD è paragonabile al suo errore standard (se_diff), il vantaggio predittivo può considerarsi modesto; in tali circostanze, è preferibile adottare il modello più semplice che superi le posterior predictive checks. È inoltre opportuno verificare i parametri di forma Pareto <span class="math inline">\(k\)</span>: qualora numerosi valori superino la soglia di 0.7, si raccomanda di impiegare la procedura di reloo o di ricorrere alla validazione incrociata k-fold.</p>
<p>Nel caso in esame, il confronto mediante LOO indica un lieve vantaggio predittivo del modello basato sulla distribuzione skew-normal rispetto alle alternative gaussiane, sia omoscedastiche che eteroscedastiche, nonché rispetto al modello con distribuzione t di Student. Tuttavia, le differenze nell’ELPD sono dell’ordine di grandezza dell’errore standard, pertanto l’evidenza a favore della skew-normal risulta moderata. Le posterior predictive checks mostrano un migliore allineamento delle code e della struttura di asimmetria nel caso della skew-normal; per questo motivo, tale modello viene adottato come specificazione principale, affiancandolo da un’analisi di sensibilità delle stime di <span class="math inline">\(\Delta\)</span> rispetto alle diverse assunzioni di likelihood. Il modesto vantaggio del modello eteroscedastico rispetto all’omoscedastico suggerisce la presenza di differenze nella variabilità tra gruppi, sebbene l’impatto predittivo di tale eterogeneità sia contenuto.</p>
<p>In sintesi, il criterio dell’ELPD favorisce il modello skew-normal, sebbene con differenze esigue rispetto alle alternative. La scelta del modello deve essere giustificata congiuntamente in base a: (i) compatibilità predittiva mediante LOO, (ii) esito delle posterior predictive checks, e (iii) robustezza delle quantità sostantive di interesse, quali <span class="math inline">\(\Delta\)</span>, <span class="math inline">\(\Pr(\Delta &gt; 0)\)</span> e <span class="math inline">\(\Pr(|\Delta| &gt; \text{SESOI})\)</span>. Quando le differenze predittive sono esigue, la stabilità di <span class="math inline">\(\Delta\)</span> tra diverse specificazioni diventa un elemento cruciale per l’interpretazione sostantiva dei risultati.</p>
<p>Questo approccio consente di mantenere l’analisi trasparente e riproducibile, collegando le stime ottenute a domande di ricerca concrete—attraverso l’uso di smallest effect sizes of interest (SESOI)—senza introdurre soglie arbitrarie di significatività.</p>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Diagnostica MCMC (workflow minimo)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Controllare sistematicamente: <code>Rhat</code> ≈ 1.00, ESS adeguati, assenza di divergenze e <em>E-BFMI</em> bassi; ispezionare <code><a href="https://rdrr.io/r/graphics/pairs.html">pairs()</a></code> per funnel. Se necessario, aumentare <code>adapt_delta</code> (es. 0.95–0.99) e <code>max_treedepth</code> (es. 15).</p>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Approfondimento statistico (opzionale)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Consideriamo ora le basi statistiche su cui si basa l’approccio frequentista. Nel paradigma frequentista, l’inferenza sulla differenza tra due gruppi si basa sulla <em>distribuzione campionaria</em> della differenza tra le medie. L’idea di fondo è che, se ripetessimo il campionamento molte volte, otterremmo valori diversi per la differenza tra le medie campionarie, e questa variabilità può essere descritta attraverso una distribuzione probabilistica.</p>
<p>Supponiamo di avere due popolazioni normali e indipendenti:</p>
<p><span class="math display">\[
Y_1 \sim \mathcal{N}(\mu_1, \sigma_1^2) \quad \text{e} \quad Y_2 \sim \mathcal{N}(\mu_2, \sigma_2^2)
\]</span></p>
<p>e di osservare due campioni indipendenti, rispettivamente di dimensione <span class="math inline">\(n_1\)</span> e <span class="math inline">\(n_2\)</span>.</p>
<p>Se assumiamo inoltre che le varianze siano uguali (<span class="math inline">\(\sigma_1^2 = \sigma_2^2 = \sigma^2\)</span>), possiamo utilizzare una versione semplificata del modello.</p>
<p><strong>Statistica di interesse.</strong> Il nostro obiettivo è stimare la <em>differenza tra le medie</em> delle due popolazioni, ovvero:</p>
<p><span class="math display">\[
\mu_1 - \mu_2.
\]</span></p>
<p>La stima di questa quantità è data dalla <em>differenza tra le medie campionarie</em>:</p>
<p><span class="math display">\[
\bar{Y}_1 - \bar{Y}_2.
\]</span></p>
<p><strong>Proprietà della statistica campionaria.</strong></p>
<p><strong>Valore atteso.</strong> Nel caso di due campioni indipendenti:</p>
<p><span class="math display">\[
E(\bar{Y}_1 - \bar{Y}_2) = \mu_1 - \mu_2.
\]</span></p>
<div class="callout callout-style-simple callout-important no-icon callout-titled" title="Dimostrazione">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Dimostrazione
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Si parte dalla definizione di media campionaria per ciascun gruppo e si applica la linearità dell’operatore valore atteso:</p>
<p><span class="math display">\[
E(\bar{Y}_1 - \bar{Y}_2) = E(\bar{Y}_1) - E(\bar{Y}_2) = \mu_1 - \mu_2.
\]</span></p>
</div>
</div>
</div>
<p><strong>Varianza.</strong> La varianza della differenza tra le medie campionarie è:</p>
<p><span class="math display">\[
\operatorname{Var}(\bar{Y}_1 - \bar{Y}_2) = \frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}.
\]</span></p>
<div class="callout callout-style-simple callout-important no-icon callout-titled" title="Dimostrazione">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Dimostrazione
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Poiché i due campioni sono indipendenti, la varianza della differenza si ottiene sommando le varianze delle due medie:</p>
<p><span class="math display">\[
\operatorname{Var}(\bar{Y}_1) = \frac{\sigma_1^2}{n_1}, \quad \operatorname{Var}(\bar{Y}_2) = \frac{\sigma_2^2}{n_2}
\]</span></p>
<p>quindi:</p>
<p><span class="math display">\[
\operatorname{Var}(\bar{Y}_1 - \bar{Y}_2) = \frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}.
\]</span></p>
</div>
</div>
</div>
<p>Se assumiamo varianze uguali (<span class="math inline">\(\sigma_1 = \sigma_2 = \sigma\)</span>), possiamo scrivere:</p>
<p><span class="math display">\[
\operatorname{Var}(\bar{Y}_1 - \bar{Y}_2) = \sigma^2 \left( \frac{1}{n_1} + \frac{1}{n_2} \right).
\]</span></p>
<p>Poiché <span class="math inline">\(\sigma^2\)</span> è sconosciuta, la si stima tramite la <em>varianza pooled</em>:</p>
<p><span class="math display">\[
s_p^2 = \frac{(n_1 - 1)s_1^2 + (n_2 - 1)s_2^2}{n_1 + n_2 - 2},
\]</span></p>
<p>dove <span class="math inline">\(s_1^2\)</span> e <span class="math inline">\(s_2^2\)</span> sono le varianze campionarie:</p>
<p><span class="math display">\[
s_j^2 = \frac{1}{n_j - 1} \sum_{i=1}^{n_j} (y_{j,i} - \bar{y}_j)^2, \quad j = 1,2.
\]</span></p>
<p><strong>Distribuzione della statistica.</strong> Sotto l’ipotesi di normalità e indipendenza, e assumendo varianze uguali, la statistica <span class="math inline">\(\bar{Y}_1 - \bar{Y}_2\)</span> segue (almeno approssimativamente) una distribuzione normale:</p>
<p><span class="math display">\[
\bar{Y}_1 - \bar{Y}_2 \sim \mathcal{N} \left( \mu_1 - \mu_2,\ \sigma \sqrt{ \frac{1}{n_1} + \frac{1}{n_2} } \right).
\]</span></p>
<p>Questa proprietà permette di costruire un <em>intervallo di confidenza al 95%</em> per la differenza tra le medie, oppure di effettuare un <em>test t di Student per due campioni indipendenti</em>, basato sulla seguente statistica:</p>
<p><span class="math display">\[
t = \frac{(\bar{Y}_1 - \bar{Y}_2) - (\mu_1 - \mu_2)}{s_p \sqrt{ \frac{1}{n_1} + \frac{1}{n_2} }}.
\]</span></p>
<p>Questa statistica segue, sotto l’ipotesi nulla <span class="math inline">\(\mu_1 = \mu_2\)</span>, una distribuzione t di Student con <span class="math inline">\(n_1 + n_2 - 2\)</span> gradi di libertà.</p>
</div>
</div>
</div>
</section></section><section id="riflessioni-conclusive" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="riflessioni-conclusive">Riflessioni conclusive</h2>
<p>In questo capitolo abbiamo riformulato il classico problema del confronto tra due medie in chiave bayesiana. Abbiamo visto come il modello possa essere espresso sia come differenza diretta tra le medie di due distribuzioni normali (<span class="math inline">\(\Delta = \mu_1 - \mu_0\)</span>), sia come un semplice modello di regressione con variabile indicatrice. Entrambe le formulazioni portano alla stessa conclusione: ciò che ci interessa non è un verdetto dicotomico sull’esistenza o meno di una differenza, ma la <strong>distribuzione delle nostre credenze</strong> sulla sua ampiezza.</p>
<p>L’approccio bayesiano ci fornisce esattamente questo: una distribuzione a posteriori per <span class="math inline">\(\Delta\)</span>, da cui possiamo derivare probabilità direttamente interpretabili, come la probabilità che la differenza sia positiva o che superi una soglia di rilevanza pratica. Questo rappresenta un cambiamento radicale rispetto al frequentismo, dove la risposta si riduce a un <em>p</em>-value, senza informazioni sulla magnitudine dell’effetto né sulla sua plausibilità relativa.</p>
<p>Il confronto tra due gruppi è un esempio paradigmatico perché mostra con chiarezza i punti di forza dell’inferenza bayesiana: trasparenza, flessibilità e possibilità di collegare l’analisi statistica a domande scientifiche sostantive. Ma rappresenta anche un punto di partenza. Nella ricerca psicologica, infatti, non basta sapere che due medie differiscono: dobbiamo anche chiederci <em>quanto</em> questa differenza sia grande e se abbia una reale rilevanza pratica.</p>
<p>Per questo, nel capitolo successivo introdurremo il tema della <em>grandezza dell’effetto</em>, collegando la differenza tra medie alla variabilità dei dati e discutendo strumenti per valutare non solo la presenza di un effetto, ma anche la sua importanza scientifica.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Informazioni sull'ambiente di sviluppo">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Informazioni sull’ambiente di sviluppo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.5.1 (2025-06-13)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin20</span></span>
<span><span class="co">#&gt; Running under: macOS Sequoia 15.6.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C/UTF-8/C/C/C/C</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Rome</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] insight_1.4.2         bayestestR_0.17.0     cmdstanr_0.9.0       </span></span>
<span><span class="co">#&gt;  [4] pillar_1.11.0         tinytable_0.13.0      patchwork_1.3.2      </span></span>
<span><span class="co">#&gt;  [7] ggdist_3.3.3          tidybayes_3.0.7       bayesplot_1.14.0     </span></span>
<span><span class="co">#&gt; [10] ggplot2_3.5.2         reliabilitydiag_0.2.1 priorsense_1.1.1     </span></span>
<span><span class="co">#&gt; [13] posterior_1.6.1       loo_2.8.0             rstan_2.32.7         </span></span>
<span><span class="co">#&gt; [16] StanHeaders_2.32.10   brms_2.22.0           Rcpp_1.1.0           </span></span>
<span><span class="co">#&gt; [19] sessioninfo_1.2.3     conflicted_1.2.0      janitor_2.2.1        </span></span>
<span><span class="co">#&gt; [22] matrixStats_1.5.0     modelr_0.1.11         tibble_3.3.0         </span></span>
<span><span class="co">#&gt; [25] dplyr_1.1.4           tidyr_1.3.1           rio_1.2.3            </span></span>
<span><span class="co">#&gt; [28] here_1.0.1           </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;  [1] gridExtra_2.3         inline_0.3.21         sandwich_3.1-1       </span></span>
<span><span class="co">#&gt;  [4] rlang_1.1.6           magrittr_2.0.3        multcomp_1.4-28      </span></span>
<span><span class="co">#&gt;  [7] snakecase_0.11.1      compiler_4.5.1        reshape2_1.4.4       </span></span>
<span><span class="co">#&gt; [10] systemfonts_1.2.3     vctrs_0.6.5           stringr_1.5.1        </span></span>
<span><span class="co">#&gt; [13] pkgconfig_2.0.3       arrayhelpers_1.1-0    fastmap_1.2.0        </span></span>
<span><span class="co">#&gt; [16] backports_1.5.0       labeling_0.4.3        utf8_1.2.6           </span></span>
<span><span class="co">#&gt; [19] rmarkdown_2.29        tzdb_0.5.0            haven_2.5.5          </span></span>
<span><span class="co">#&gt; [22] ps_1.9.1              ragg_1.5.0            purrr_1.1.0          </span></span>
<span><span class="co">#&gt; [25] xfun_0.53             cachem_1.1.0          jsonlite_2.0.0       </span></span>
<span><span class="co">#&gt; [28] broom_1.0.9           parallel_4.5.1        R6_2.6.1             </span></span>
<span><span class="co">#&gt; [31] stringi_1.8.7         RColorBrewer_1.1-3    lubridate_1.9.4      </span></span>
<span><span class="co">#&gt; [34] estimability_1.5.1    knitr_1.50            zoo_1.8-14           </span></span>
<span><span class="co">#&gt; [37] R.utils_2.13.0        pacman_0.5.1          readr_2.1.5          </span></span>
<span><span class="co">#&gt; [40] Matrix_1.7-4          splines_4.5.1         timechange_0.3.0     </span></span>
<span><span class="co">#&gt; [43] tidyselect_1.2.1      abind_1.4-8           yaml_2.3.10          </span></span>
<span><span class="co">#&gt; [46] codetools_0.2-20      curl_7.0.0            processx_3.8.6       </span></span>
<span><span class="co">#&gt; [49] pkgbuild_1.4.8        plyr_1.8.9            lattice_0.22-7       </span></span>
<span><span class="co">#&gt; [52] withr_3.0.2           bridgesampling_1.1-2  coda_0.19-4.1        </span></span>
<span><span class="co">#&gt; [55] evaluate_1.0.5        survival_3.8-3        RcppParallel_5.1.11-1</span></span>
<span><span class="co">#&gt; [58] tensorA_0.36.2.1      checkmate_2.3.3       stats4_4.5.1         </span></span>
<span><span class="co">#&gt; [61] distributional_0.5.0  generics_0.1.4        rprojroot_2.1.1      </span></span>
<span><span class="co">#&gt; [64] hms_1.1.3             rstantools_2.5.0      scales_1.4.0         </span></span>
<span><span class="co">#&gt; [67] xtable_1.8-4          glue_1.8.0            emmeans_1.11.2-8     </span></span>
<span><span class="co">#&gt; [70] tools_4.5.1           data.table_1.17.8     forcats_1.0.0        </span></span>
<span><span class="co">#&gt; [73] mvtnorm_1.3-3         grid_4.5.1            QuickJSR_1.8.0       </span></span>
<span><span class="co">#&gt; [76] colorspace_2.1-1      nlme_3.1-168          cli_3.6.5            </span></span>
<span><span class="co">#&gt; [79] textshaping_1.0.3     svUnit_1.0.8          Brobdingnag_1.2-9    </span></span>
<span><span class="co">#&gt; [82] V8_7.0.0              gtable_0.3.6          R.methodsS3_1.8.2    </span></span>
<span><span class="co">#&gt; [85] digest_0.6.37         TH.data_1.1-4         htmlwidgets_1.6.4    </span></span>
<span><span class="co">#&gt; [88] farver_2.1.2          R.oo_1.27.1           memoise_2.0.1        </span></span>
<span><span class="co">#&gt; [91] htmltools_0.5.8.1     lifecycle_1.0.4       MASS_7.3-65</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="bibliografia" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="bibliografia">Bibliografia</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-kruschke2013bayesian" class="csl-entry" role="listitem">
Kruschke, J. K. (2013). Bayesian estimation supersedes the t test. <em>Journal of Experimental Psychology: General</em>, <em>142</em>(2), 573–603.
</div>
</div>
</section></main><!-- /main --><script>
document.body.classList.add('classic-book');
document.addEventListener('DOMContentLoaded', function() {
  const paragraphs = document.querySelectorAll('p');
  paragraphs.forEach(p => {
    if (p.textContent.length > 200) {
      p.style.hyphens = 'auto';
      p.style.hyphenateCharacter = '-';
    }
  });
  const headings = document.querySelectorAll('h1, h2, h3, h4, h5, h6');
  headings.forEach(h => {
    h.style.fontFeatureSettings = '"liga" 1, "dlig" 1, "smcp" 1';
  });
});
</script><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiato!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiato!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/psicometria-r\/intro\.html");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/linear_models/07_one_mean.html" class="pagination-link" aria-label="Inferenza bayesiana su una media">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Inferenza bayesiana su una media</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/linear_models/09_effect_size.html" class="pagination-link" aria-label="La grandezza dell’effetto: valutare la rilevanza pratica">
        <span class="nav-page-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">La grandezza dell’effetto: valutare la rilevanza pratica</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Psicometria</strong> è una risorsa didattica creata per il corso di Scienze e Tecniche Psicologiche dell’Università degli Studi di Firenze.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ccaudek/psicometria-r/blob/main/chapters/linear_models/08_two_means.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/psicometria-r/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>