<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>28&nbsp; Modelli multilivello – Metodi bayesiani in psicologia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/linear_models/13_meas_error.html" rel="next">
<link href="../../chapters/linear_models/11_anova_1via.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-f54fa83ccd8f86fe7238c9291c42d766.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-0bdde917e76f8bcae6a47464f3bc36c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QT5S3P9D31"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QT5S3P9D31', { 'anonymize_ip': true});
</script><style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/linear_models/introduction_sec.html">Regressione</a></li><li class="breadcrumb-item"><a href="../../chapters/linear_models/12_multilevel.html"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Modelli multilivello</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../../index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Metodi bayesiani in psicologia</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/utet-companion/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Attiva/disattiva la modalità lettore">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Struttura dei contenuti</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefazione</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guida-al-manuale.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Guida al manuale</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Inferenza Bayesiana Operativa</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/cap_15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Quantificare e aggiornare l’incertezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/cap_16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Famiglie coniugate classiche</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/05_summary_posterior.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Sintesi a posteriori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/06_balance_prior_post.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">L’influenza della distribuzione a priori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/cap_18a_prior_pred_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Controllo predittivo a priori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/cap_18b_post_pred_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Distribuzione predittiva a posteriori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Stan</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/02_ppl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linguaggi di programmazione probabilistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/03_stan_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Stan: concetti di base</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/04_stan_odds_ratio_stan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analisi bayesiana dell’odds ratio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/05_stan_two_means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Confrontare due medie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/06_stan_poisson_model_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Modello di Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/07_stan_gaussian_mixture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Modelli di mistura gaussiani</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/08_prior_from_corpus_gaussian_mixture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Costruzione di prior informativi da corpora di studi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/10_stan_hier_beta_binom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Modello gerarchico beta-binomiale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/11_stan_parametrization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Parametrizzazioni centered e non-centered</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/12_bayesian_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Flusso di lavoro bayesiano</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive sulla sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Regressione</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/01_reglin_frequentist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">La regressione lineare bivariata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/02_regr_toward_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">La regressione verso la media</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/03_reglin_bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Modello bayesiano di regressione lineare bivariata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/04_synt_sugar_sea_ice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Zucchero sintattico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/05_stan_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Regressione lineare in Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/06_specification_error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Errore di specificazione e bias da variabile omessa</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/07_one_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Inferenza bayesiana su una media</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/08_two_means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Confronto tra le medie di due gruppi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/09_effect_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">La grandezza dell’effetto: valutare la rilevanza pratica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/10_sample_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Pianificazione della dimensione campionaria</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/11_anova_1via.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">ANOVA ad una via</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/12_multilevel.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Modelli multilivello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/13_meas_error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Errore di misurazione e attenuazione: una soluzione bayesiana</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">GLM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/01_logistic_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Regressione logistica con Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/02_one_proportion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Inferenza sulle proporzioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/03_two_proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Confronto tra due proporzioni con la regressione logistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/04_poisson_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Modello di Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/05_logistic_process.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Dal GLM a un modello processuale per dati binari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/06_missing_values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Dati mancanti in psicologia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/07_auc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Valutare la capacità predittiva: AUC e generalizzazione del modello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive sulla sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Modelli</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/01_statistical_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Modelli statistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/02_goal_revision_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Il modello di revisione degli obiettivi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/03_modeling_heterogeneity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Modellazione dell’eterogeneità: soggetti, popolazione e condizioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/04_rescorla_wagner.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Il modello di Rescorla–Wagner</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/05_study_method.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Decisione ottimale e utilità attesa: l’approccio bayesiano</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Entropia</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/01_entropy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Entropia e informazione di Shannon</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/02_kl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">La divergenza di Kullback-Leibler</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/03_model_comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Valutare i modelli bayesiani</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/04_emotional_reactivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Lo stress d’esame e la fragilità psicologica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/05_bf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Valutare e confrontare i modelli bayesiani: dal Bayes Factor alla LOO/ELPD</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Crisi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/introduction_replication_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/01_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">La crisi della replicazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/02_limits_stat_freq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Limiti dell’inferenza frequentista</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/03_effect_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">La grandezza dell’effetto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/04_s_m_errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Errori di segno e errori di grandezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/05_p_values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">La fragilità del <em>p</em>-valore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/06_changes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Riforma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/07_degrees_of_freedom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">I gradi di libertà del ricercatore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/08_integrity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Integrità della ricerca</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Epilogo</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epiloque/epiloque.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Considerazioni conclusive</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a01_shell.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">La Shell</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a01a_files.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Cartelle e documenti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a02_math_symbols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Simbologia di base</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a03_latex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Equazioni Matematiche in LaTeX</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a11_numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Numeri e intervalli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a12_sum_notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Sommatorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a13_sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">Insiemi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a14_combinatorics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">Calcolo combinatorio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a15_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">I</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a35_other_conjugate_families.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">J</span>&nbsp; <span class="chapter-title">Altre famiglie coniugate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a36_gamma_poisson_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">K</span>&nbsp; <span class="chapter-title">Modello coniugato Gamma-Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a40_metropolis_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">L</span>&nbsp; <span class="chapter-title">Metropolis: esempio Normale–Normale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a41_install_cmdstan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">M</span>&nbsp; <span class="chapter-title">Come installare CmdStan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a42_cmdstanr_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">N</span>&nbsp; <span class="chapter-title">Implementazione di modelli Bayesiani con Stan tramite <code>cmdstanr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a43_stan_lang.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">O</span>&nbsp; <span class="chapter-title">Linguaggio Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a44_stan_diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">P</span>&nbsp; <span class="chapter-title">Diagnostica delle catene markoviane</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a45_stan_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">Q</span>&nbsp; <span class="chapter-title">Controlli predittivi bayesiani (a priori e a posteriori) con <code>cmdstanr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a46_prior_pred_check.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">R</span>&nbsp; <span class="chapter-title">Controllo predittivo a priori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a50_lin_fun.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">S</span>&nbsp; <span class="chapter-title">La funzione lineare</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2"><h2 id="toc-title">Sommario</h2>
   
  <ul class="collapse">
<li><a href="#lapproccio-idiografico-e-lanalisi-personalizzata" id="toc-lapproccio-idiografico-e-lanalisi-personalizzata" class="nav-link active" data-scroll-target="#lapproccio-idiografico-e-lanalisi-personalizzata"><span class="header-section-number">28.1</span> L’approccio idiografico e l’analisi personalizzata</a></li>
  <li><a href="#i-tre-approcci-complete-pooling-no-pooling-e-partial-pooling" id="toc-i-tre-approcci-complete-pooling-no-pooling-e-partial-pooling" class="nav-link" data-scroll-target="#i-tre-approcci-complete-pooling-no-pooling-e-partial-pooling"><span class="header-section-number">28.2</span> I tre approcci: <em>complete pooling</em>, <em>no pooling</em>, e <em>partial pooling</em></a></li>
  <li><a href="#complete-pooling-un-modello-unico-per-tutti" id="toc-complete-pooling-un-modello-unico-per-tutti" class="nav-link" data-scroll-target="#complete-pooling-un-modello-unico-per-tutti"><span class="header-section-number">28.3</span> <em>Complete pooling</em>: un modello unico per tutti</a></li>
  <li><a href="#no-pooling-un-modello-per-ciascun-partecipante" id="toc-no-pooling-un-modello-per-ciascun-partecipante" class="nav-link" data-scroll-target="#no-pooling-un-modello-per-ciascun-partecipante"><span class="header-section-number">28.4</span> <em>No Pooling</em>: un modello per ciascun partecipante</a></li>
  <li><a href="#partial-pooling-un-compromesso-tra-individuo-e-gruppo" id="toc-partial-pooling-un-compromesso-tra-individuo-e-gruppo" class="nav-link" data-scroll-target="#partial-pooling-un-compromesso-tra-individuo-e-gruppo"><span class="header-section-number">28.5</span> <em>Partial pooling</em>: un compromesso tra individuo e gruppo</a></li>
  <li><a href="#il-ruolo-dei-modelli-multilivello-in-psicologia" id="toc-il-ruolo-dei-modelli-multilivello-in-psicologia" class="nav-link" data-scroll-target="#il-ruolo-dei-modelli-multilivello-in-psicologia"><span class="header-section-number">28.6</span> Il ruolo dei modelli multilivello in psicologia</a></li>
  <li><a href="#interpretazione-del-modello" id="toc-interpretazione-del-modello" class="nav-link" data-scroll-target="#interpretazione-del-modello"><span class="header-section-number">28.7</span> Interpretazione del modello</a></li>
  </ul><div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ccaudek/utet-companion/blob/main/chapters/linear_models/12_multilevel.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/utet-companion/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/linear_models/introduction_sec.html">Regressione</a></li><li class="breadcrumb-item"><a href="../../chapters/linear_models/12_multilevel.html"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Modelli multilivello</span></a></li></ol></nav><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-multilevel" class="quarto-section-identifier"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Modelli multilivello</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Codice</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="introduzione" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="introduzione">Introduzione</h2>
<p>Questo capitolo approfondisce gli aspetti implementativi dell’esempio presentato nel capitolo 23 del manuale didattico, dedicato ai modelli multilivello.</p>
<p>Nei capitoli precedenti abbiamo esaminato il confronto tra le medie di gruppi indipendenti, assumendo che ogni osservazione fosse statisticamente indipendente dalle altre. Tuttavia, questa ipotesi è spesso irrealistica nel contesto della ricerca psicologica. Infatti, una parte essenziale del lavoro dello psicologo consiste nel comprendere sia le differenze tra le persone (differenze <em>interindividuali</em>), sia le variazioni all’interno della stessa persona nel tempo o nelle diverse situazioni (differenze <em>intraindividuali</em>).</p>
<p>Le analisi tradizionali, come l’ANOVA o la regressione lineare classica, tendono però a trascurare la struttura multilivello dei dati, trattando tutte le osservazioni come indipendenti. In presenza di misurazioni ripetute o di gruppi naturalmente nidificati (per esempio, studenti all’interno di classi, pazienti all’interno di centri clinici o momenti di osservazione all’interno della stessa persona), tale assunzione viene violata, compromettendo la validità delle inferenze.</p>
<p>Questa semplificazione può condurre a conclusioni fuorvianti. Si consideri, ad esempio, uno studio sull’umore giornaliero: in media, le persone potrebbero sembrare più felici durante il fine settimana, ma alcune potrebbero invece sperimentare maggiore solitudine o disagio proprio in quei giorni. Ignorare queste differenze individuali significa trascurare un’informazione psicologica cruciale, ovvero il modo in cui ogni individuo si discosta dal comportamento medio della popolazione.</p>
</section><section id="lapproccio-idiografico-e-lanalisi-personalizzata" class="level2" data-number="28.1"><h2 data-number="28.1" class="anchored" data-anchor-id="lapproccio-idiografico-e-lanalisi-personalizzata">
<span class="header-section-number">28.1</span> L’approccio idiografico e l’analisi personalizzata</h2>
<p>Negli ultimi anni è cresciuta la consapevolezza che ogni individuo è un caso a sé. L’approccio idiografico cerca di modellare le caratteristiche di ogni persona singolarmente. Tuttavia, le analisi idiografiche pure richiedono un gran numero di dati per ciascun soggetto e spesso non sono praticabili negli studi reali.</p>
<p>I <em>modelli multilivello bayesiani</em> offrono un compromesso elegante. Questi modelli permettono di stimare gli effetti specifici per ogni individuo, ma sfruttano anche l’informazione condivisa all’interno del gruppo. Ciò è possibile grazie al meccanismo di <em>shrinkage</em>, che “bilancia” le stime individuali con la tendenza generale. Ne vedremo il funzionamento più avanti.</p>
</section><section id="i-tre-approcci-complete-pooling-no-pooling-e-partial-pooling" class="level2" data-number="28.2"><h2 data-number="28.2" class="anchored" data-anchor-id="i-tre-approcci-complete-pooling-no-pooling-e-partial-pooling">
<span class="header-section-number">28.2</span> I tre approcci: <em>complete pooling</em>, <em>no pooling</em>, e <em>partial pooling</em>
</h2>
<p>Quando analizziamo i dati gerarchici, come le misurazioni ripetute sullo stesso individuo o i dati delle persone in gruppi, possiamo scegliere diverse strategie. Per fare un esempio, consideriamo uno studio sugli effetti della deprivazione del sonno su dieci partecipanti, valutati più volte ciascuno.</p>
<p>Il primo approccio è il <em>complete pooling</em>. In questo caso, trattiamo tutti i dati come se fossero stati raccolti da un’unica entità, ignorando completamente la struttura gerarchica. È come se tutti e dieci i partecipanti fossero, in realtà, la stessa persona.</p>
<p>All’estremo opposto, troviamo il <em>no pooling</em>. In questo caso, si stima un effetto completamente separato per ogni partecipante, come se non ci fosse alcuna informazione comune o relazione tra loro. Ogni individuo è considerato un’entità unica e indipendente.</p>
<p>Infine, il <em>partial pooling</em>, noto anche come <em>modello multilivello</em>, rappresenta una via di mezzo e spesso è la soluzione più equilibrata. In questo approccio, stimiamo comunque effetti individuali per ciascun partecipante, ma li “regolarizziamo”, ovvero li avviciniamo alla media complessiva del gruppo. Ciò significa che le stime per ciascun partecipante sono influenzate sia dai dati specifici di ciascun partecipante, sia dalla tendenza generale osservata nell’intero gruppo.</p>
<p>Nelle prossime sezioni, esploreremo come implementare ciascuno di questi tre modelli utilizzando il pacchetto <code>brms</code> in R, fornendo un’applicazione pratica di questi concetti teorici.</p>
<section id="un-esempio-guidato-leffetto-della-deprivazione-del-sonno-sulle-prestazioni-psicomotorie" class="level3" data-number="28.2.1"><h3 data-number="28.2.1" class="anchored" data-anchor-id="un-esempio-guidato-leffetto-della-deprivazione-del-sonno-sulle-prestazioni-psicomotorie">
<span class="header-section-number">28.2.1</span> Un esempio guidato: l’effetto della deprivazione del sonno sulle prestazioni psicomotorie</h3>
<p>Per illustrare l’utilità dei modelli multilivello nell’analisi di dati longitudinali, utilizzeremo un dataset derivato dallo studio di <span class="citation" data-cites="belenky2003patterns">Belenky et al. (<a href="#ref-belenky2003patterns" role="doc-biblioref">2003</a>)</span>, il quale ha esaminato l’effetto cumulativo della restrizione del sonno sulla vigilanza psicomotoria. In questo studio, i partecipanti hanno svolto per dieci giorni un compito di reazione agli stimoli visivi ripetuto più volte, dopo aver dormito solo tre ore per notte. La variabile di interesse è il tempo medio di reazione (in millisecondi), registrato ogni giorno per ciascun partecipante.</p>
<p>Il dataset ha una struttura tipicamente multilivello: ogni soggetto ha fornito osservazioni ripetute nel tempo, pertanto ci si aspetta una forte correlazione intraindividuale. L’analisi mira a quantificare sia l’effetto medio della deprivazione del sonno sia le differenze individuali nella traiettoria del tempo di reazione.</p>
<p>Per semplicità, caricheremo direttamente il file già elaborato <code>sleep2.csv</code>, in cui sono stati rimossi i primi due giorni (fase di adattamento e addestramento). Inoltre, è stata creata una nuova variabile, <code>days_deprived</code>, che parte da 0 (baseline) e aumenta nei giorni successivi di deprivazione del sonno.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="12_multilevel_files/figure-html/unnamed-chunk-2-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="12_multilevel_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>Questa visualizzazione evidenzia sia la tendenza generale all’aumento del tempo di reazione sia la variabilità tra i soggetti riguardo al modo in cui le prestazioni si degradano nel tempo. I modelli multilivello ci permetteranno di formalizzare queste osservazioni, stimando congiuntamente l’effetto medio della deprivazione del sonno e le differenze tra i partecipanti in termini di velocità e intensità di tale effetto.</p>
</section><section id="relazione-tra-tempo-di-reazione-e-deprivazione-del-sonno" class="level3" data-number="28.2.2"><h3 data-number="28.2.2" class="anchored" data-anchor-id="relazione-tra-tempo-di-reazione-e-deprivazione-del-sonno">
<span class="header-section-number">28.2.2</span> Relazione tra tempo di reazione e deprivazione del sonno</h3>
<p>L’analisi dei dati relativi alla deprivazione del sonno ha rivelato che, con l’unica eccezione del soggetto 335, il tempo medio di reazione tende ad aumentare progressivamente con l’aumentare di ogni giorno deprivazione aggiuntivo. Questo suggerisce che un modello di regressione lineare potrebbe essere utile per descrivere le prestazioni di ciascun partecipante.</p>
<p>La regressione lineare è definita dalla seguente equazione:</p>
<p><span class="math display">\[
E(Y) = \beta_0 + \beta_1 X,
\]</span> dove:</p>
<ul>
<li>
<span class="math inline">\(Y\)</span> rappresenta la variabile dipendente (il tempo di reazione medio);</li>
<li>
<span class="math inline">\(\beta_0\)</span> è l’intercetta, ovvero il tempo di reazione stimato il primo giorno (baseline, senza deprivazione del sonno);</li>
<li>
<span class="math inline">\(\beta_1\)</span> è il coefficiente di pendenza che rappresenta la variazione stimata del tempo di reazione per ogni giorno di deprivazione aggiuntivo;</li>
<li>
<span class="math inline">\(X\)</span> indica il numero di giorni di deprivazione del sonno.</li>
</ul>
<p>I parametri <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span> vengono stimati dai dati e la loro interpretazione fornisce informazioni chiave sulle dinamiche delle prestazioni psicomotorie.</p>
</section><section id="scelta-del-modello-di-regressione" class="level3" data-number="28.2.3"><h3 data-number="28.2.3" class="anchored" data-anchor-id="scelta-del-modello-di-regressione">
<span class="header-section-number">28.2.3</span> Scelta del modello di regressione</h3>
<p>Un aspetto cruciale dell’analisi è la scelta della struttura modellistica da adottare per descrivere i dati. Bisogna considerare le seguenti opzioni.</p>
<ol type="1">
<li><p><em>Complete Pooling:</em> questo approccio utilizza un unico modello di regressione lineare per tutti i partecipanti, assumendo che la relazione tra deprivazione del sonno e tempo di reazione sia identica per tutti. In pratica, si stima una singola intercetta (<span class="math inline">\(\beta_0\)</span>) e una singola pendenza (<span class="math inline">\(\beta_1\)</span>) comuni a tutti i soggetti. Sebbene sia semplice, questo metodo ignora completamente le differenze individuali.</p></li>
<li><p><em>No Pooling:</em> in questo caso, si stima un modello di regressione lineare separato per ciascun partecipante, consentendo a ogni soggetto di avere la propria intercetta e la propria pendenza. Questo approccio riconosce pienamente le variazioni individuali, ma potrebbe risultare eccessivamente complesso e sensibile al rumore nei dati, soprattutto quando il numero di punti di osservazione per soggetto è ridotto.</p></li>
<li><p><em>Partial Pooling:</em> questo approccio intermedio, spesso implementato attraverso i modelli multilivello, bilancia i due estremi descritti in precedenza. Si assume una relazione media condivisa tra i soggetti (ad esempio, una pendenza media), ma si consente una variazione individuale attorno a questa media. Il <em>partial pooling</em> sfrutta le informazioni condivise tra i partecipanti, migliorando la robustezza delle stime, soprattutto in presenza di un numero ridotto di dati per ciascun soggetto.</p></li>
</ol></section></section><section id="complete-pooling-un-modello-unico-per-tutti" class="level2" data-number="28.3"><h2 data-number="28.3" class="anchored" data-anchor-id="complete-pooling-un-modello-unico-per-tutti">
<span class="header-section-number">28.3</span> <em>Complete pooling</em>: un modello unico per tutti</h2>
<p>L’approccio del complete pooling presuppone che tutti i partecipanti seguano la stessa relazione tra la variabile indipendente (ad esempio, giorni di deprivazione del sonno) e quella dipendente (ad esempio, tempo di reazione). In altre parole, si stima un’unica intercetta e un’unica pendenza per l’intero campione, ignorando le differenze individuali. Questo approccio può essere utile come modello di partenza, ma è spesso irrealistico in psicologia, dove i soggetti tendono a mostrare andamenti diversi.</p>
<p>Per adattare questo modello in R, utilizziamo la funzione <code>brm()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cp_model</span> <span class="op">&lt;-</span> <span class="fu">brm</span><span class="op">(</span></span>
<span>  <span class="va">Reaction</span> <span class="op">~</span> <span class="va">days_deprived</span>,</span>
<span>  data <span class="op">=</span> <span class="va">sleep2</span>,</span>
<span>  family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">gaussian</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">2</span>, iter <span class="op">=</span> <span class="fl">1000</span>, </span>
<span>  backend <span class="op">=</span> <span class="st">"cmdstanr"</span>,</span>
<span>  refresh <span class="op">=</span> <span class="fl">0</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">fixef</span><span class="op">(</span><span class="va">cp_model</span><span class="op">)</span></span>
<span><span class="co">#&gt;               Estimate Est.Error   Q2.5 Q97.5</span></span>
<span><span class="co">#&gt; Intercept        268.0      7.60 253.47 282.4</span></span>
<span><span class="co">#&gt; days_deprived     11.4      1.87   7.93  15.3</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Il modello stima che il tempo di reazione iniziale (al giorno 0) sia di circa 268 ms e che aumenti di circa 11 ms per ogni giorno di deprivazione del sonno.</p>
<section id="limiti-dellapproccio" class="level3" data-number="28.3.1"><h3 data-number="28.3.1" class="anchored" data-anchor-id="limiti-dellapproccio">
<span class="header-section-number">28.3.1</span> Limiti dell’approccio</h3>
<p>Questo approccio presenta diverse criticità. In primo luogo, ignora il fatto che lo stesso soggetto viene misurato più volte, il che significa che l’indipendenza delle osservazioni non viene rispettata. Di conseguenza, gli errori standard dei coefficienti potrebbero risultare irrealistici, portando a una sottostima dell’incertezza. Inoltre, il modello non considera la perdita di informazione individuale, in quanto ogni soggetto potrebbe avere la propria intercetta e la propria pendenza, aspetti che non vengono presi in considerazione in questa analisi.</p>
<p>Per visualizzare meglio questi risultati, possiamo aggiungere le previsioni del modello al grafico che abbiamo già creato.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="12_multilevel_files/figure-html/unnamed-chunk-5-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="12_multilevel_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>Il grafico mostra che il modello attuale non si adatta in modo ottimale ai dati raccolti. Ciò evidenzia la necessità di adottare un approccio diverso per modellare in modo più accurato le relazioni presenti nei dati.</p>
</section></section><section id="no-pooling-un-modello-per-ciascun-partecipante" class="level2" data-number="28.4"><h2 data-number="28.4" class="anchored" data-anchor-id="no-pooling-un-modello-per-ciascun-partecipante">
<span class="header-section-number">28.4</span> <em>No Pooling</em>: un modello per ciascun partecipante</h2>
<p>L’approccio del no pooling stima una retta di regressione distinta per ogni soggetto, trattando ciascuno di essi come un caso indipendente. Questo approccio consente di cogliere al meglio le differenze individuali, ma ignora completamente l’informazione condivisa tra i soggetti. Si tratta del metodo più vicino a un’analisi idiografica pura. In questo modo, ogni partecipante ha la propria intercetta e la propria pendenza. Tuttavia, le stime non sono regolarizzate, pertanto i soggetti con pochi dati possono produrre stime molto rumorose.</p>
<section id="implementazione-con-brm-mediante-un-loop" class="level3" data-number="28.4.1"><h3 data-number="28.4.1" class="anchored" data-anchor-id="implementazione-con-brm-mediante-un-loop">
<span class="header-section-number">28.4.1</span> Implementazione con <code>brm()</code> mediante un <em>loop</em>
</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Otteniamo i livelli unici dei soggetti</span></span>
<span><span class="va">subjects</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">sleep2</span><span class="op">$</span><span class="va">Subject</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Inizializziamo una lista per salvare i modelli</span></span>
<span><span class="va">subject_models</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">subject_coefs</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Loop sui soggetti</span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">id</span> <span class="kw">in</span> <span class="va">subjects</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">data_i</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">sleep2</span>, <span class="va">Subject</span> <span class="op">==</span> <span class="va">id</span><span class="op">)</span></span>
<span>  <span class="va">fit</span> <span class="op">&lt;-</span> <span class="fu">brm</span><span class="op">(</span></span>
<span>    <span class="va">Reaction</span> <span class="op">~</span> <span class="va">days_deprived</span>,</span>
<span>    data <span class="op">=</span> <span class="va">data_i</span>,</span>
<span>    family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">gaussian</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>    chains <span class="op">=</span> <span class="fl">2</span>, iter <span class="op">=</span> <span class="fl">1000</span>, refresh <span class="op">=</span> <span class="fl">0</span>,</span>
<span>    backend <span class="op">=</span> <span class="st">"cmdstanr"</span>,</span>
<span>    silent <span class="op">=</span> <span class="cn">TRUE</span></span>
<span>  <span class="op">)</span></span>
<span>  <span class="va">subject_models</span><span class="op">[[</span><span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="va">id</span><span class="op">)</span><span class="op">]</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">fit</span></span>
<span>  </span>
<span>  <span class="va">coef_i</span> <span class="op">&lt;-</span> <span class="fu">fixef</span><span class="op">(</span><span class="va">fit</span><span class="op">)</span><span class="op">[</span>, <span class="st">"Estimate"</span><span class="op">]</span></span>
<span>  <span class="va">subject_coefs</span> <span class="op">&lt;-</span> <span class="fu">bind_rows</span><span class="op">(</span><span class="va">subject_coefs</span>, <span class="fu">tibble</span><span class="op">(</span></span>
<span>    Subject <span class="op">=</span> <span class="va">id</span>,</span>
<span>    intercept <span class="op">=</span> <span class="va">coef_i</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>,</span>
<span>    slope <span class="op">=</span> <span class="va">coef_i</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span></span>
<span>  <span class="op">)</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="12_multilevel_files/figure-html/unnamed-chunk-7-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="12_multilevel_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>Questo approccio evidenzia efficacemente le differenze individuali sia nella pendenza, che riflette il tasso di peggioramento, sia nell’intercetta, corrispondente al livello basale di reazione. Tuttavia, questo approccio non sfrutta l’informazione condivisa all’interno del gruppo, limitando così la sua efficacia inferenziale. Inoltre, le stime risultano particolarmente instabili per i soggetti con un numero limitato di osservazioni.</p>
<p>Nel prossimo passo, vedremo un compromesso tra il <em>no pooling</em> e il <em>complete pooling</em>: il <em>partial pooling</em>, tipico dei modelli multilivello bayesiani.</p>
</section></section><section id="partial-pooling-un-compromesso-tra-individuo-e-gruppo" class="level2" data-number="28.5"><h2 data-number="28.5" class="anchored" data-anchor-id="partial-pooling-un-compromesso-tra-individuo-e-gruppo">
<span class="header-section-number">28.5</span> <em>Partial pooling</em>: un compromesso tra individuo e gruppo</h2>
<p>Nel modellare i dati psicologici, dobbiamo scegliere se trattare ogni partecipante come un caso a sé stante (<em>no pooling</em>) o considerare tutti i dati come provenienti da un unico gruppo omogeneo (<em>complete pooling</em>). Il <em>partial pooling</em> è un approccio intermedio: ogni soggetto ha le proprie stime, ma queste sono influenzate anche dai dati degli altri soggetti. Ciò si realizza con i modelli multilivello o a effetti misti.</p>
<section id="il-concetto-di-shrinkage" class="level3" data-number="28.5.1"><h3 data-number="28.5.1" class="anchored" data-anchor-id="il-concetto-di-shrinkage">
<span class="header-section-number">28.5.1</span> Il concetto di <em>shrinkage</em>
</h3>
<p>Nel <em>partial pooling</em>, le stime individuali subiscono un fenomeno di contrazione verso la media del gruppo noto come <em>shrinkage</em>. Questo meccanismo opera come una sorta di regolarizzazione statistica che stabilizza le stime, particolarmente utile quando i dati individuali sono limitati o affetti da rumore. Operativamente, il modello bilancia dinamicamente le fonti di informazione: per i partecipanti con un numero limitato di osservazioni, privilegia l’informazione di gruppo; quando invece sono disponibili numerosi dati individuali, attribuisce maggiore peso all’evidenza specifica del soggetto.</p>
</section><section id="implementazione-con-brm" class="level3" data-number="28.5.2"><h3 data-number="28.5.2" class="anchored" data-anchor-id="implementazione-con-brm">
<span class="header-section-number">28.5.2</span> Implementazione con <code>brm()</code>
</h3>
<p>L’obiettivo consiste nello specificare un modello che accomodi <em>eterogeneità individuale sia nel livello basale (intercetta) che nel tasso di cambiamento (pendenza)</em>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Modello multilivello (partial pooling)</span></span>
<span><span class="va">pp_model</span> <span class="op">&lt;-</span> <span class="fu">brm</span><span class="op">(</span></span>
<span>  <span class="va">Reaction</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> <span class="va">days_deprived</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">+</span> <span class="va">days_deprived</span> <span class="op">|</span> <span class="va">Subject</span><span class="op">)</span>,</span>
<span>  data <span class="op">=</span> <span class="va">sleep2</span>,</span>
<span>  family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">gaussian</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">2</span>, iter <span class="op">=</span> <span class="fl">2000</span>, seed <span class="op">=</span> <span class="fl">123</span>,</span>
<span>  backend <span class="op">=</span> <span class="st">"cmdstanr"</span>,</span>
<span>  refresh <span class="op">=</span> <span class="fl">0</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Qui la sintassi <code>1 + days_deprived | Subject</code> specifica che a ciascun soggetto viene associata un’intercetta unica e una pendenza specifica per la variabile <code>days_deprived</code>.</p>
<p>Costruiamo le predizioni del modello per ciascun soggetto, considerando l’intero range di giorni di deprivazione, e procediamo alla visualizzazione dei risultati:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="12_multilevel_files/figure-html/unnamed-chunk-10-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="12_multilevel_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a></p>
</figure>
</div>
</div>
</div>
</section></section><section id="il-ruolo-dei-modelli-multilivello-in-psicologia" class="level2" data-number="28.6"><h2 data-number="28.6" class="anchored" data-anchor-id="il-ruolo-dei-modelli-multilivello-in-psicologia">
<span class="header-section-number">28.6</span> Il ruolo dei modelli multilivello in psicologia</h2>
<section id="una-sintesi-tra-nomotetico-e-idiografico" class="level3" data-number="28.6.1"><h3 data-number="28.6.1" class="anchored" data-anchor-id="una-sintesi-tra-nomotetico-e-idiografico">
<span class="header-section-number">28.6.1</span> Una sintesi tra nomotetico e idiografico</h3>
<p>La ricerca psicologica si è tradizionalmente articolata in due prospettive epistemologiche distinte: l’approccio nomotetico, volto all’identificazione di principi generali applicabili a tutta la popolazione, e l’approccio idiografico, focalizzato sull’indagine delle caratteristiche distintive di ciascun individuo. I modelli multilivello rappresentano una sintesi metodologica che supera questa dicotomia, riconoscendo che le traiettorie individuali (dimensione idiografica) si sviluppano all’interno di contesti collettivi che ne influenzano l’andamento (dimensione nomotetica).</p>
<p>Questa integrazione consente di indagare sistematicamente le differenze individuali, preservando al contempo la capacità di generalizzazione a livello di popolazione e offrendo un contributo metodologicamente robusto alla comprensione del comportamento umano.</p>
<p>Tuttavia, l’applicazione di questi modelli richiede una riflessione critica sulle assunzioni teoriche su cui si basano. Come evidenziato da <span class="citation" data-cites="richters2021incredible">(<a href="#ref-richters2021incredible" role="doc-biblioref"><strong>richters2021incredible?</strong></a>)</span>, gran parte della ricerca psicologica adotta implicitamente un’«assunzione ergonomica» che presuppone un’omogeneità psicologica fondamentale tra gli individui. Questa premessa, sebbene sia funzionale all’aggregazione dei dati e alla stima degli effetti medi, rischia di mascherare le sostanziali eterogeneità, producendo quello che l’autore chiama “causal debris”: una proliferazione di risultati significativi, ma teoricamente frammentari e difficili da replicare.</p>
<p>La capacità dei modelli multilivello di stimare simultaneamente effetti medi e variazioni individuali non garantisce che tali effetti riflettano processi causali omogenei tra i partecipanti. In assenza di una solida base teorica che specifichi quali meccanismi siano plausibilmente condivisi e in che modo possano variare, si rischia di interpretare le differenze qualitative come semplici deviazioni quantitative da un effetto medio.</p>
<p>Pertanto, l’implementazione di modelli multilivello in psicologia richiede un’attenzione critica alla plausibilità teorica dell’omogeneità assunta, affiancando all’analisi statistica l’esplorazione di approcci complementari, quali la modellizzazione idiografica pura o l’identificazione di sottogruppi teoricamente fondati. Solo attraverso questa integrazione metodologica è possibile cogliere appieno la complessità e la variabilità che caratterizzano i fenomeni psicologici.</p>
</section></section><section id="interpretazione-del-modello" class="level2" data-number="28.7"><h2 data-number="28.7" class="anchored" data-anchor-id="interpretazione-del-modello">
<span class="header-section-number">28.7</span> Interpretazione del modello</h2>
<p>Dopo aver stimato un modello multilivello, è importante saperlo leggere e interpretare. In particolare, analizzeremo tre componenti fondamentali: gli <em>effetti fissi</em> (la media del gruppo), gli <em>effetti casuali</em> (le deviazioni individuali) e la varianza tra soggetti.</p>
<section id="effetti-fissi-la-media-del-gruppo" class="level3" data-number="28.7.1"><h3 data-number="28.7.1" class="anchored" data-anchor-id="effetti-fissi-la-media-del-gruppo">
<span class="header-section-number">28.7.1</span> Effetti fissi: la media del gruppo</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">fixef</span><span class="op">(</span><span class="va">pp_model</span><span class="op">)</span></span>
<span><span class="co">#&gt;               Estimate Est.Error   Q2.5 Q97.5</span></span>
<span><span class="co">#&gt; Intercept        267.9      9.09 250.20 286.4</span></span>
<span><span class="co">#&gt; days_deprived     11.5      1.95   7.72  15.5</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Questo comando restituisce le stime degli effetti fissi a livello di popolazione:</p>
<ul>
<li>l’<em>intercetta</em> corrisponde al tempo di reazione medio stimato in condizioni basali (giorno 0, senza deprivazione di sonno);</li>
<li>il <em>coefficiente di <code>days_deprived</code></em> indica l’incremento medio del tempo di reazione associato a ogni giorno aggiuntivo di deprivazione di sonno.</li>
</ul>
<p>Questi parametri rappresentano gli effetti “nomotetici” del modello, descrivendo le relazioni medie che caratterizzano l’intera popolazione di riferimento.</p>
</section><section id="effetti-casuali-le-deviazioni-individuali" class="level3" data-number="28.7.2"><h3 data-number="28.7.2" class="anchored" data-anchor-id="effetti-casuali-le-deviazioni-individuali">
<span class="header-section-number">28.7.2</span> Effetti casuali: le deviazioni individuali</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ranef</span><span class="op">(</span><span class="va">pp_model</span><span class="op">)</span><span class="op">$</span><span class="va">Subject</span></span>
<span><span class="co">#&gt; , , Intercept</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;     Estimate Est.Error    Q2.5  Q97.5</span></span>
<span><span class="co">#&gt; 308   24.754      15.8  -4.113  57.02</span></span>
<span><span class="co">#&gt; 309  -59.221      16.6 -92.099 -28.59</span></span>
<span><span class="co">#&gt; 310  -39.815      14.9 -69.778 -11.60</span></span>
<span><span class="co">#&gt; 330    0.919      15.1 -28.436  30.08</span></span>
<span><span class="co">#&gt; 331   17.447      15.7 -13.441  48.88</span></span>
<span><span class="co">#&gt; 332   29.633      16.2  -0.272  61.70</span></span>
<span><span class="co">#&gt; 333   12.871      15.5 -17.235  44.26</span></span>
<span><span class="co">#&gt; 334  -17.473      15.6 -49.469  12.81</span></span>
<span><span class="co">#&gt; 335  -17.245      15.6 -47.889  13.58</span></span>
<span><span class="co">#&gt; 337   44.654      16.4  13.507  75.40</span></span>
<span><span class="co">#&gt; 349  -26.089      15.6 -57.449   4.23</span></span>
<span><span class="co">#&gt; 350   -5.884      16.1 -37.797  25.12</span></span>
<span><span class="co">#&gt; 351   -5.946      15.3 -38.501  24.12</span></span>
<span><span class="co">#&gt; 352   45.968      16.2  16.817  80.10</span></span>
<span><span class="co">#&gt; 369    1.058      15.0 -29.863  31.03</span></span>
<span><span class="co">#&gt; 370  -18.069      16.0 -50.287  12.79</span></span>
<span><span class="co">#&gt; 371   -7.354      15.3 -38.538  23.03</span></span>
<span><span class="co">#&gt; 372   17.499      15.4 -12.578  48.52</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; , , days_deprived</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;     Estimate Est.Error   Q2.5  Q97.5</span></span>
<span><span class="co">#&gt; 308    8.515      3.66   1.53 16.011</span></span>
<span><span class="co">#&gt; 309   -8.107      3.77 -15.67 -0.825</span></span>
<span><span class="co">#&gt; 310   -7.341      3.64 -14.75 -0.281</span></span>
<span><span class="co">#&gt; 330   -2.292      3.52  -9.40  4.382</span></span>
<span><span class="co">#&gt; 331   -3.679      3.64 -11.18  3.478</span></span>
<span><span class="co">#&gt; 332   -4.763      3.82 -12.66  2.419</span></span>
<span><span class="co">#&gt; 333    0.295      3.60  -6.88  7.094</span></span>
<span><span class="co">#&gt; 334    3.671      3.69  -3.37 11.171</span></span>
<span><span class="co">#&gt; 335  -12.075      3.69 -19.45 -5.105</span></span>
<span><span class="co">#&gt; 337   10.078      3.74   2.82 17.293</span></span>
<span><span class="co">#&gt; 349    2.029      3.60  -4.52  9.120</span></span>
<span><span class="co">#&gt; 350    8.047      3.63   1.09 15.468</span></span>
<span><span class="co">#&gt; 351   -2.300      3.51  -9.38  4.388</span></span>
<span><span class="co">#&gt; 352   -0.494      3.79  -7.76  6.682</span></span>
<span><span class="co">#&gt; 369    1.726      3.51  -4.89  8.820</span></span>
<span><span class="co">#&gt; 370    5.431      3.66  -1.54 13.243</span></span>
<span><span class="co">#&gt; 371    0.250      3.43  -6.18  7.081</span></span>
<span><span class="co">#&gt; 372    0.641      3.54  -6.50  7.390</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Questo comando restituisce, per ciascun partecipante, l’entità con cui i suoi parametri si discostano dalla media di popolazione.</p>
<p>In particolare, vengono riportati:</p>
<ul>
<li>gli <em>scostamenti dell’intercetta</em>, che riflettono differenze nei tempi di reazione di base tra i soggetti;</li>
<li>gli <em>scostamenti della pendenza</em>, che mostrano quanto ciascun individuo sia più o meno sensibile, rispetto alla media del gruppo, all’effetto della deprivazione di sonno.</li>
</ul>
<p>Queste <em>deviazioni individuali</em>, note come <em>effetti casuali stimati</em>, quantificano la componente specifica di ciascun partecipante che non è spiegata dagli effetti fissi del modello. Esse consentono di osservare come ogni individuo si discosti sistematicamente dal comportamento medio del gruppo.</p>
</section><section id="varianza-tra-soggetti-quanta-differenza-cè-nel-campione" class="level3" data-number="28.7.3"><h3 data-number="28.7.3" class="anchored" data-anchor-id="varianza-tra-soggetti-quanta-differenza-cè-nel-campione">
<span class="header-section-number">28.7.3</span> Varianza tra soggetti: quanta differenza c’è nel campione</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">VarCorr</span><span class="op">(</span><span class="va">pp_model</span><span class="op">)</span><span class="op">$</span><span class="va">Subject</span></span>
<span><span class="co">#&gt; $sd</span></span>
<span><span class="co">#&gt;               Estimate Est.Error  Q2.5 Q97.5</span></span>
<span><span class="co">#&gt; Intercept         33.6      8.04 20.85  53.5</span></span>
<span><span class="co">#&gt; days_deprived      7.4      1.83  4.39  11.6</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $cor</span></span>
<span><span class="co">#&gt; , , Intercept</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;               Estimate Est.Error   Q2.5 Q97.5</span></span>
<span><span class="co">#&gt; Intercept        1.000     0.000  1.000 1.000</span></span>
<span><span class="co">#&gt; days_deprived    0.185     0.302 -0.408 0.764</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; , , days_deprived</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;               Estimate Est.Error   Q2.5 Q97.5</span></span>
<span><span class="co">#&gt; Intercept        0.185     0.302 -0.408 0.764</span></span>
<span><span class="co">#&gt; days_deprived    1.000     0.000  1.000 1.000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $cov</span></span>
<span><span class="co">#&gt; , , Intercept</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;               Estimate Est.Error Q2.5 Q97.5</span></span>
<span><span class="co">#&gt; Intercept         1194     605.2  435  2857</span></span>
<span><span class="co">#&gt; days_deprived       39      83.6 -137   205</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; , , days_deprived</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;               Estimate Est.Error   Q2.5 Q97.5</span></span>
<span><span class="co">#&gt; Intercept         39.0      83.6 -137.2   205</span></span>
<span><span class="co">#&gt; days_deprived     58.1      30.5   19.3   134</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>L’output riporta la <em>dispersione</em> (deviazioni standard, varianze e covarianze) e la <em>correlazione</em> tra gli effetti casuali dell’intercetta e della pendenza. Queste informazioni descrivono l’eterogeneità tra i partecipanti e il modo in cui le loro differenze nei tempi di reazione si associano all’effetto della deprivazione di sonno.</p>
<ul>
<li><p>La <em>deviazione standard dell’intercetta</em> è di circa <em>33.6 ms</em> (<em>IC 95%: 20.9 – 53.5</em>), indicando una notevole variabilità nei <em>tempi di reazione di base</em>: alcuni soggetti sono sistematicamente più rapidi, altri più lenti, anche prima dell’intervento della manipolazione sperimentale.</p></li>
<li><p>La <em>deviazione standard della pendenza</em> è pari a <em>7.4 ms</em> (<em>IC 95%: 4.4 – 11.6</em>), suggerendo che esistono differenze di rilievo anche nella sensibilità individuale alla deprivazione di sonno. In altre parole, i soggetti non reagiscono tutti allo stesso modo: alcuni mostrano un rallentamento marcato, altri quasi nullo.</p></li>
<li><p>La <em>correlazione tra intercetta e pendenza</em> è stimata a <em>0.18</em>, ma con un intervallo di credibilità ampio (<em>–0.41, 0.76</em>). Questa incertezza indica che non vi è una prova consistente di un legame tra i tempi di reazione di base e l’entità dell’effetto della deprivazione: non possiamo affermare con certezza che chi parte più lento tenda anche ad aumentare di più i tempi con il sonno ridotto.</p></li>
</ul>
<p>La <em>matrice di covarianza</em>, anch’essa presente nell’output, completa il quadro informativo: la <em>covarianza</em> tra intercetta e pendenza è stimata attorno a <em>39</em>, sebbene con un ampio intervallo di credibilità (<em>–137, 205</em>). Questo parametro quantifica la <em>relazione sistematica</em> tra i due effetti casuali: un valore positivo indicherebbe che soggetti con tempi di reazione basali più elevati tendono a mostrare incrementi più marcati in condizioni di deprivazione, mentre la sostanziale sovrapposizione dello zero nell’intervallo di credibilità suggerisce che, nei nostri dati, le due dimensioni potrebbero variare in modo indipendente.</p>
<p>Nel complesso, il modello rivela una <em>marcata eterogeneità tra gli individui</em>, sia nei livelli di prestazione iniziale sia nella risposta alla manipolazione. Questa diversità rappresenta la variabilità idiografica del campione: ciascun individuo presenta un proprio profilo di funzionamento, distinguibile ma connesso a un quadro di gruppo condiviso.</p>
<p><strong>In sintesi:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 38%">
<col style="width: 40%">
</colgroup>
<thead><tr class="header">
<th><strong>Comando</strong></th>
<th><strong>Cosa restituisce</strong></th>
<th><strong>Significato</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>fixef(pp_model)</code></td>
<td>Effetti fissi (intercetta e pendenza medie)</td>
<td>Relazioni medie a livello di popolazione</td>
</tr>
<tr class="even">
<td><code>ranef(pp_model)$Subject</code></td>
<td>Deviazioni individuali dagli effetti fissi</td>
<td>Specificità di ciascun soggetto rispetto alla media</td>
</tr>
<tr class="odd">
<td><code>VarCorr(pp_model)</code></td>
<td>Varianza e correlazione degli effetti casuali</td>
<td>Entità e struttura della variabilità individuale</td>
</tr>
</tbody>
</table>
<p>Queste funzioni consentono di <em>interpretare il modello multilivello</em> in modo esaustivo: non solo identificano <em>le tendenze centrali</em>, ma anche <em>l’entità delle differenze individuali</em> rispetto a tali tendenze. Questa duplice lettura costituisce l’essenza del <em>partial pooling</em>.</p>
</section></section><section id="riflessioni-conclusive" class="level2 unlisted unnumbered"><h2 class="unlisted unnumbered anchored" data-anchor-id="riflessioni-conclusive">Riflessioni conclusive</h2>
<p>I modelli multilivello costituiscono uno strumento metodologico fondamentale per la ricerca psicologica, particolarmente adatto all’analisi di dati con struttura gerarchica, come quelli derivanti da misurazioni ripetute sugli stessi individui. Il loro principale vantaggio risiede nella capacità di integrare informazioni provenienti da diversi livelli di analisi, consentendo di stimare congiuntamente le tendenze generali a livello di popolazione e le variazioni specifiche a livello individuale.</p>
<p>In questo capitolo è stato introdotto il concetto di “partial pooling”, che si colloca a metà strada tra due approcci estremi: il “complete pooling”, che presuppone l’omogeneità totale tra i soggetti, e il “no pooling”, che analizza ogni individuo in modo completamente isolato. Il partial pooling rappresenta un compromesso ottimale tra queste due prospettive, consentendo, da un lato, di modellare sistematicamente la variabilità interindividuale e, dall’altro, di sfruttare strategicamente l’informazione condivisa nel campione per ottenere stime più robuste.</p>
<p>Il fenomeno dello <em>shrinkage</em>, ovvero la contrazione delle stime individuali verso la media di gruppo, rappresenta una caratteristica essenziale di questo approccio. Questo meccanismo di regolarizzazione statistica non rappresenta un limite metodologico, ma un elemento funzionale che previene il sovradattamento e riduce l’incertezza delle stime, risultando particolarmente vantaggioso quando i dati individuali sono limitati o rumorosi.</p>
<p>Dal punto di vista epistemologico, i modelli multilivello superano la tradizionale dicotomia tra approccio nomotetico e idiografico. Questi modelli, infatti, permettono di rispondere simultaneamente a domande relative alle relazioni medie a livello di popolazione e all’identificazione delle specifiche caratteristiche individuali, riconoscendo la coesistenza di pattern generali e di differenze sistematiche tra i soggetti.</p>
<p>L’applicazione al dataset <code>sleepstudy</code> ha mostrato in modo concreto come modellare gli effetti della deprivazione di sonno sui tempi di reazione, distinguendo chiaramente l’effetto medio nella popolazione dalla variabilità interindividuale nella risposta alla deprivazione. L’analisi ha dimostrato che è possibile stimare i parametri specifici per ciascun partecipante, mantenendo al contempo la coerenza con il principio del partial pooling.</p>
<p>Questi modelli trovano ampia applicazione in vari ambiti della psicologia, dalla psicometria allo studio delle traiettorie di sviluppo, e costituiscono la base concettuale per i successivi modelli di crescita latente. Rappresentano inoltre il quadro metodologico di riferimento per affrontare il tema dell’affidabilità tra osservatori, che verrà approfondito in seguito.</p>
<p>In sintesi, i modelli multilivello offrono un approccio rigoroso e sofisticato per l’analisi dei dati psicologici, che coniuga il rigore metodologico con l’attenzione necessaria alla complessità dei fenomeni umani. La loro adozione contribuisce significativamente allo sviluppo di una psicologia scientifica che sia in grado di cogliere sia le regolarità generali sia le specificità individuali che caratterizzano il comportamento umano.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Informazioni sull'ambiente di sviluppo">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Informazioni sull’ambiente di sviluppo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.5.1 (2025-06-13)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin20</span></span>
<span><span class="co">#&gt; Running under: macOS Tahoe 26.0.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Zagreb</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] kableExtra_1.4.0      cmdstanr_0.9.0        lme4_1.1-37          </span></span>
<span><span class="co">#&gt;  [4] Matrix_1.7-4          car_3.1-3             carData_3.0-5        </span></span>
<span><span class="co">#&gt;  [7] ragg_1.5.0            tinytable_0.13.0      withr_3.0.2          </span></span>
<span><span class="co">#&gt; [10] systemfonts_1.3.1     patchwork_1.3.2       ggdist_3.3.3         </span></span>
<span><span class="co">#&gt; [13] tidybayes_3.0.7       bayesplot_1.14.0      ggplot2_4.0.0        </span></span>
<span><span class="co">#&gt; [16] reliabilitydiag_0.2.1 priorsense_1.1.1      posterior_1.6.1      </span></span>
<span><span class="co">#&gt; [19] loo_2.8.0             rstan_2.32.7          StanHeaders_2.32.10  </span></span>
<span><span class="co">#&gt; [22] brms_2.23.0           Rcpp_1.1.0            sessioninfo_1.2.3    </span></span>
<span><span class="co">#&gt; [25] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    </span></span>
<span><span class="co">#&gt; [28] modelr_0.1.11         tibble_3.3.0          dplyr_1.1.4          </span></span>
<span><span class="co">#&gt; [31] tidyr_1.3.1           rio_1.2.4             here_1.0.2           </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;  [1] RColorBrewer_1.1-3    tensorA_0.36.2.1      rstudioapi_0.17.1    </span></span>
<span><span class="co">#&gt;  [4] jsonlite_2.0.0        magrittr_2.0.4        TH.data_1.1-4        </span></span>
<span><span class="co">#&gt;  [7] estimability_1.5.1    farver_2.1.2          nloptr_2.2.1         </span></span>
<span><span class="co">#&gt; [10] rmarkdown_2.30        vctrs_0.6.5           memoise_2.0.1        </span></span>
<span><span class="co">#&gt; [13] minqa_1.2.8           htmltools_0.5.8.1     distributional_0.5.0 </span></span>
<span><span class="co">#&gt; [16] curl_7.0.0            broom_1.0.10          Formula_1.2-5        </span></span>
<span><span class="co">#&gt; [19] htmlwidgets_1.6.4     sandwich_3.1-1        emmeans_1.11.2-8     </span></span>
<span><span class="co">#&gt; [22] zoo_1.8-14            lubridate_1.9.4       cachem_1.1.0         </span></span>
<span><span class="co">#&gt; [25] lifecycle_1.0.4       pkgconfig_2.0.3       R6_2.6.1             </span></span>
<span><span class="co">#&gt; [28] fastmap_1.2.0         rbibutils_2.3         snakecase_0.11.1     </span></span>
<span><span class="co">#&gt; [31] digest_0.6.37         colorspace_2.1-2      ps_1.9.1             </span></span>
<span><span class="co">#&gt; [34] rprojroot_2.1.1       textshaping_1.0.4     labeling_0.4.3       </span></span>
<span><span class="co">#&gt; [37] timechange_0.3.0      abind_1.4-8           compiler_4.5.1       </span></span>
<span><span class="co">#&gt; [40] S7_0.2.0              backports_1.5.0       inline_0.3.21        </span></span>
<span><span class="co">#&gt; [43] QuickJSR_1.8.1        pkgbuild_1.4.8        R.utils_2.13.0       </span></span>
<span><span class="co">#&gt; [46] MASS_7.3-65           tools_4.5.1           R.oo_1.27.1          </span></span>
<span><span class="co">#&gt; [49] glue_1.8.0            nlme_3.1-168          grid_4.5.1           </span></span>
<span><span class="co">#&gt; [52] checkmate_2.3.3       generics_0.1.4        gtable_0.3.6         </span></span>
<span><span class="co">#&gt; [55] R.methodsS3_1.8.2     data.table_1.17.8     xml2_1.4.0           </span></span>
<span><span class="co">#&gt; [58] pillar_1.11.1         stringr_1.5.2         splines_4.5.1        </span></span>
<span><span class="co">#&gt; [61] lattice_0.22-7        survival_3.8-3        tidyselect_1.2.1     </span></span>
<span><span class="co">#&gt; [64] knitr_1.50            reformulas_0.4.1      arrayhelpers_1.1-0   </span></span>
<span><span class="co">#&gt; [67] gridExtra_2.3         V8_8.0.1              svglite_2.2.1        </span></span>
<span><span class="co">#&gt; [70] stats4_4.5.1          xfun_0.53             bridgesampling_1.1-2 </span></span>
<span><span class="co">#&gt; [73] stringi_1.8.7         yaml_2.3.10           pacman_0.5.1         </span></span>
<span><span class="co">#&gt; [76] boot_1.3-32           evaluate_1.0.5        codetools_0.2-20     </span></span>
<span><span class="co">#&gt; [79] cli_3.6.5             RcppParallel_5.1.11-1 xtable_1.8-4         </span></span>
<span><span class="co">#&gt; [82] Rdpack_2.6.4          processx_3.8.6        coda_0.19-4.1        </span></span>
<span><span class="co">#&gt; [85] svUnit_1.0.8          parallel_4.5.1        rstantools_2.5.0     </span></span>
<span><span class="co">#&gt; [88] Brobdingnag_1.2-9     viridisLite_0.4.2     mvtnorm_1.3-3        </span></span>
<span><span class="co">#&gt; [91] scales_1.4.0          purrr_1.1.0           rlang_1.1.6          </span></span>
<span><span class="co">#&gt; [94] multcomp_1.4-28</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section><section id="bibliografia" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="bibliografia">Bibliografia</h2>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-belenky2003patterns" class="csl-entry" role="listitem">
Belenky, G., Wesensten, N. J., Thorne, D. R., Thomas, M. L., Sing, H. C., Redmond, D. P., Russo, M. B., &amp; Balkin, T. J. (2003). Patterns of performance degradation and restoration during sleep restriction and subsequent recovery: A sleep dose-response study. <em>Journal of Sleep Research</em>, <em>12</em>(1), 1–12.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiato!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiato!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/utet-companion\/intro\.html");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/linear_models/11_anova_1via.html" class="pagination-link" aria-label="ANOVA ad una via">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">ANOVA ad una via</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/linear_models/13_meas_error.html" class="pagination-link" aria-label="Errore di misurazione e attenuazione: una soluzione bayesiana">
        <span class="nav-page-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Errore di misurazione e attenuazione: una soluzione bayesiana</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Eseguire il codice</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Modelli multilivello {#sec-multilevel}</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"code"</span>, <span class="st">"_common.R"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">source</span>()</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"pacman"</span>)) <span class="fu">install.packages</span>(<span class="st">"pacman"</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(car, lme4, cmdstanr, brms, kableExtra)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduzione {.unnumbered .unlisted}</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>Questo capitolo approfondisce gli aspetti implementativi dell'esempio presentato nel capitolo 23 del manuale didattico, dedicato ai modelli multilivello.</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>Nei capitoli precedenti abbiamo esaminato il confronto tra le medie di gruppi indipendenti, assumendo che ogni osservazione fosse statisticamente indipendente dalle altre. Tuttavia, questa ipotesi è spesso irrealistica nel contesto della ricerca psicologica. Infatti, una parte essenziale del lavoro dello psicologo consiste nel comprendere sia le differenze tra le persone (differenze *interindividuali*), sia le variazioni all'interno della stessa persona nel tempo o nelle diverse situazioni (differenze *intraindividuali*).</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>Le analisi tradizionali, come l'ANOVA o la regressione lineare classica, tendono però a trascurare la struttura multilivello dei dati, trattando tutte le osservazioni come indipendenti. In presenza di misurazioni ripetute o di gruppi naturalmente nidificati (per esempio, studenti all’interno di classi, pazienti all’interno di centri clinici o momenti di osservazione all’interno della stessa persona), tale assunzione viene violata, compromettendo la validità delle inferenze.</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>Questa semplificazione può condurre a conclusioni fuorvianti. Si consideri, ad esempio, uno studio sull'umore giornaliero: in media, le persone potrebbero sembrare più felici durante il fine settimana, ma alcune potrebbero invece sperimentare maggiore solitudine o disagio proprio in quei giorni. Ignorare queste differenze individuali significa trascurare un'informazione psicologica cruciale, ovvero il modo in cui ogni individuo si discosta dal comportamento medio della popolazione.</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a><span class="fu">## L'approccio idiografico e l'analisi personalizzata</span></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>Negli ultimi anni è cresciuta la consapevolezza che ogni individuo è un caso a sé. L’approccio idiografico cerca di modellare le caratteristiche di ogni persona singolarmente. Tuttavia, le analisi idiografiche pure richiedono un gran numero di dati per ciascun soggetto e spesso non sono praticabili negli studi reali.</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>I *modelli multilivello bayesiani* offrono un compromesso elegante. Questi modelli permettono di stimare gli effetti specifici per ogni individuo, ma sfruttano anche l'informazione condivisa all'interno del gruppo. Ciò è possibile grazie al meccanismo di *shrinkage*, che "bilancia" le stime individuali con la tendenza generale. Ne vedremo il funzionamento più avanti.</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a><span class="fu">## I tre approcci: *complete pooling*, *no pooling*, e *partial pooling*</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>Quando analizziamo i dati gerarchici, come le misurazioni ripetute sullo stesso individuo o i dati delle persone in gruppi, possiamo scegliere diverse strategie. Per fare un esempio, consideriamo uno studio sugli effetti della deprivazione del sonno su dieci partecipanti, valutati più volte ciascuno.</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>Il primo approccio è il *complete pooling*. In questo caso, trattiamo tutti i dati come se fossero stati raccolti da un'unica entità, ignorando completamente la struttura gerarchica. È come se tutti e dieci i partecipanti fossero, in realtà, la stessa persona.</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>All'estremo opposto, troviamo il *no pooling*. In questo caso, si stima un effetto completamente separato per ogni partecipante, come se non ci fosse alcuna informazione comune o relazione tra loro. Ogni individuo è considerato un'entità unica e indipendente.</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>Infine, il *partial pooling*, noto anche come *modello multilivello*, rappresenta una via di mezzo e spesso è la soluzione più equilibrata. In questo approccio, stimiamo comunque effetti individuali per ciascun partecipante, ma li "regolarizziamo", ovvero li avviciniamo alla media complessiva del gruppo. Ciò significa che le stime per ciascun partecipante sono influenzate sia dai dati specifici di ciascun partecipante, sia dalla tendenza generale osservata nell'intero gruppo.</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>Nelle prossime sezioni, esploreremo come implementare ciascuno di questi tre modelli utilizzando il pacchetto <span class="in">`brms`</span> in R, fornendo un'applicazione pratica di questi concetti teorici.</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a><span class="fu">### Un esempio guidato: l’effetto della deprivazione del sonno sulle prestazioni psicomotorie</span></span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>Per illustrare l’utilità dei modelli multilivello nell’analisi di dati longitudinali, utilizzeremo un dataset derivato dallo studio di @belenky2003patterns, il quale ha esaminato l’effetto cumulativo della restrizione del sonno sulla vigilanza psicomotoria. In questo studio, i partecipanti hanno svolto per dieci giorni un compito di reazione agli stimoli visivi ripetuto più volte, dopo aver dormito solo tre ore per notte. La variabile di interesse è il tempo medio di reazione (in millisecondi), registrato ogni giorno per ciascun partecipante.</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>Il dataset ha una struttura tipicamente multilivello: ogni soggetto ha fornito osservazioni ripetute nel tempo, pertanto ci si aspetta una forte correlazione intraindividuale. L’analisi mira a quantificare sia l’effetto medio della deprivazione del sonno sia le differenze individuali nella traiettoria del tempo di reazione.</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>Per semplicità, caricheremo direttamente il file già elaborato <span class="in">`sleep2.csv`</span>, in cui sono stati rimossi i primi due giorni (fase di adattamento e addestramento). Inoltre, è stata creata una nuova variabile, <span class="in">`days_deprived`</span>, che parte da 0 (baseline) e aumenta nei giorni successivi di deprivazione del sonno. </span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a>sleep2 <span class="ot">&lt;-</span> rio<span class="sc">::</span><span class="fu">import</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"sleep2.csv"</span>))</span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleep2, <span class="fu">aes</span>(<span class="at">x =</span> days_deprived, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Subject) <span class="sc">+</span></span>
<span id="cb9-60"><a href="#cb9-60" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-61"><a href="#cb9-61" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Giorni di deprivazione del sonno (0 = baseline)"</span>,</span>
<span id="cb9-62"><a href="#cb9-62" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Tempo medio di reazione (ms)"</span>,</span>
<span id="cb9-63"><a href="#cb9-63" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Andamento del tempo di reazione durante la deprivazione del sonno"</span></span>
<span id="cb9-64"><a href="#cb9-64" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-65"><a href="#cb9-65" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-66"><a href="#cb9-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-67"><a href="#cb9-67" aria-hidden="true" tabindex="-1"></a>Questa visualizzazione evidenzia sia la tendenza generale all'aumento del tempo di reazione sia la variabilità tra i soggetti riguardo al modo in cui le prestazioni si degradano nel tempo. I modelli multilivello ci permetteranno di formalizzare queste osservazioni, stimando congiuntamente l'effetto medio della deprivazione del sonno e le differenze tra i partecipanti in termini di velocità e intensità di tale effetto.</span>
<span id="cb9-68"><a href="#cb9-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-69"><a href="#cb9-69" aria-hidden="true" tabindex="-1"></a><span class="fu">### Relazione tra tempo di reazione e deprivazione del sonno</span></span>
<span id="cb9-70"><a href="#cb9-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-71"><a href="#cb9-71" aria-hidden="true" tabindex="-1"></a>L'analisi dei dati relativi alla deprivazione del sonno ha rivelato che, con l'unica eccezione del soggetto 335, il tempo medio di reazione tende ad aumentare progressivamente con l'aumentare di ogni giorno deprivazione aggiuntivo. Questo suggerisce che un modello di regressione lineare potrebbe essere utile per descrivere le prestazioni di ciascun partecipante.</span>
<span id="cb9-72"><a href="#cb9-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-73"><a href="#cb9-73" aria-hidden="true" tabindex="-1"></a>La regressione lineare è definita dalla seguente equazione:</span>
<span id="cb9-74"><a href="#cb9-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-75"><a href="#cb9-75" aria-hidden="true" tabindex="-1"></a>$$ </span>
<span id="cb9-76"><a href="#cb9-76" aria-hidden="true" tabindex="-1"></a>E(Y) = \beta_0 + \beta_1 X,</span>
<span id="cb9-77"><a href="#cb9-77" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb9-78"><a href="#cb9-78" aria-hidden="true" tabindex="-1"></a>dove:</span>
<span id="cb9-79"><a href="#cb9-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-80"><a href="#cb9-80" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$Y$ rappresenta la variabile dipendente (il tempo di reazione medio);</span>
<span id="cb9-81"><a href="#cb9-81" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\beta_0$ è l'intercetta, ovvero il tempo di reazione stimato il primo giorno (baseline, senza deprivazione del sonno);</span>
<span id="cb9-82"><a href="#cb9-82" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\beta_1$ è il coefficiente di pendenza che rappresenta la variazione stimata del tempo di reazione per ogni giorno di deprivazione aggiuntivo;</span>
<span id="cb9-83"><a href="#cb9-83" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$X$ indica il numero di giorni di deprivazione del sonno.</span>
<span id="cb9-84"><a href="#cb9-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-85"><a href="#cb9-85" aria-hidden="true" tabindex="-1"></a>I parametri $\beta_0$ e $\beta_1$ vengono stimati dai dati e la loro interpretazione fornisce informazioni chiave sulle dinamiche delle prestazioni psicomotorie.</span>
<span id="cb9-86"><a href="#cb9-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-87"><a href="#cb9-87" aria-hidden="true" tabindex="-1"></a><span class="fu">### Scelta del modello di regressione</span></span>
<span id="cb9-88"><a href="#cb9-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-89"><a href="#cb9-89" aria-hidden="true" tabindex="-1"></a>Un aspetto cruciale dell'analisi è la scelta della struttura modellistica da adottare per descrivere i dati. Bisogna considerare le seguenti opzioni.</span>
<span id="cb9-90"><a href="#cb9-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-91"><a href="#cb9-91" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>*Complete Pooling:* questo approccio utilizza un unico modello di regressione lineare per tutti i partecipanti, assumendo che la relazione tra deprivazione del sonno e tempo di reazione sia identica per tutti. In pratica, si stima una singola intercetta ($\beta_0$) e una singola pendenza ($\beta_1$) comuni a tutti i soggetti. Sebbene sia semplice, questo metodo ignora completamente le differenze individuali.</span>
<span id="cb9-92"><a href="#cb9-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-93"><a href="#cb9-93" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>*No Pooling:* in questo caso, si stima un modello di regressione lineare separato per ciascun partecipante, consentendo a ogni soggetto di avere la propria intercetta e la propria pendenza. Questo approccio riconosce pienamente le variazioni individuali, ma potrebbe risultare eccessivamente complesso e sensibile al rumore nei dati, soprattutto quando il numero di punti di osservazione per soggetto è ridotto.</span>
<span id="cb9-94"><a href="#cb9-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-95"><a href="#cb9-95" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>*Partial Pooling:* questo approccio intermedio, spesso implementato attraverso i modelli multilivello, bilancia i due estremi descritti in precedenza. Si assume una relazione media condivisa tra i soggetti (ad esempio, una pendenza media), ma si consente una variazione individuale attorno a questa media. Il *partial pooling* sfrutta le informazioni condivise tra i partecipanti, migliorando la robustezza delle stime, soprattutto in presenza di un numero ridotto di dati per ciascun soggetto.</span>
<span id="cb9-96"><a href="#cb9-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-97"><a href="#cb9-97" aria-hidden="true" tabindex="-1"></a><span class="fu">## *Complete pooling*: un modello unico per tutti</span></span>
<span id="cb9-98"><a href="#cb9-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-99"><a href="#cb9-99" aria-hidden="true" tabindex="-1"></a>L’approccio del complete pooling presuppone che tutti i partecipanti seguano la stessa relazione tra la variabile indipendente (ad esempio, giorni di deprivazione del sonno) e quella dipendente (ad esempio, tempo di reazione). In altre parole, si stima un'unica intercetta e un'unica pendenza per l'intero campione, ignorando le differenze individuali. Questo approccio può essere utile come modello di partenza, ma è spesso irrealistico in psicologia, dove i soggetti tendono a mostrare andamenti diversi.</span>
<span id="cb9-100"><a href="#cb9-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-101"><a href="#cb9-101" aria-hidden="true" tabindex="-1"></a>Per adattare questo modello in R, utilizziamo la funzione <span class="in">`brm()`</span>:</span>
<span id="cb9-102"><a href="#cb9-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-105"><a href="#cb9-105" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-106"><a href="#cb9-106" aria-hidden="true" tabindex="-1"></a><span class="co">#| output: false</span></span>
<span id="cb9-107"><a href="#cb9-107" aria-hidden="true" tabindex="-1"></a>cp_model <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb9-108"><a href="#cb9-108" aria-hidden="true" tabindex="-1"></a>  Reaction <span class="sc">~</span> days_deprived,</span>
<span id="cb9-109"><a href="#cb9-109" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> sleep2,</span>
<span id="cb9-110"><a href="#cb9-110" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">gaussian</span>(),</span>
<span id="cb9-111"><a href="#cb9-111" aria-hidden="true" tabindex="-1"></a>  <span class="at">chains =</span> <span class="dv">2</span>, <span class="at">iter =</span> <span class="dv">1000</span>, </span>
<span id="cb9-112"><a href="#cb9-112" aria-hidden="true" tabindex="-1"></a>  <span class="at">backend =</span> <span class="st">"cmdstanr"</span>,</span>
<span id="cb9-113"><a href="#cb9-113" aria-hidden="true" tabindex="-1"></a>  <span class="at">refresh =</span> <span class="dv">0</span></span>
<span id="cb9-114"><a href="#cb9-114" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-115"><a href="#cb9-115" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-116"><a href="#cb9-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-119"><a href="#cb9-119" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-120"><a href="#cb9-120" aria-hidden="true" tabindex="-1"></a><span class="fu">fixef</span>(cp_model)</span>
<span id="cb9-121"><a href="#cb9-121" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-122"><a href="#cb9-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-123"><a href="#cb9-123" aria-hidden="true" tabindex="-1"></a>Il modello stima che il tempo di reazione iniziale (al giorno 0) sia di circa 268 ms e che aumenti di circa 11 ms per ogni giorno di deprivazione del sonno.</span>
<span id="cb9-124"><a href="#cb9-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-125"><a href="#cb9-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-126"><a href="#cb9-126" aria-hidden="true" tabindex="-1"></a><span class="fu">###  Limiti dell’approccio</span></span>
<span id="cb9-127"><a href="#cb9-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-128"><a href="#cb9-128" aria-hidden="true" tabindex="-1"></a>Questo approccio presenta diverse criticità. In primo luogo, ignora il fatto che lo stesso soggetto viene misurato più volte, il che significa che l'indipendenza delle osservazioni non viene rispettata. Di conseguenza, gli errori standard dei coefficienti potrebbero risultare irrealistici, portando a una sottostima dell'incertezza. Inoltre, il modello non considera la perdita di informazione individuale, in quanto ogni soggetto potrebbe avere la propria intercetta e la propria pendenza, aspetti che non vengono presi in considerazione in questa analisi.</span>
<span id="cb9-129"><a href="#cb9-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-130"><a href="#cb9-130" aria-hidden="true" tabindex="-1"></a>Per visualizzare meglio questi risultati, possiamo aggiungere le previsioni del modello al grafico che abbiamo già creato. </span>
<span id="cb9-131"><a href="#cb9-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-134"><a href="#cb9-134" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-135"><a href="#cb9-135" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb9-136"><a href="#cb9-136" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleep2, <span class="fu">aes</span>(<span class="at">x =</span> days_deprived, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb9-137"><a href="#cb9-137" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(</span>
<span id="cb9-138"><a href="#cb9-138" aria-hidden="true" tabindex="-1"></a>    <span class="at">intercept =</span> <span class="fu">fixef</span>(cp_model)[<span class="dv">1</span>, <span class="st">"Estimate"</span>],</span>
<span id="cb9-139"><a href="#cb9-139" aria-hidden="true" tabindex="-1"></a>    <span class="at">slope =</span> <span class="fu">fixef</span>(cp_model)[<span class="dv">2</span>, <span class="st">"Estimate"</span>],</span>
<span id="cb9-140"><a href="#cb9-140" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"blue"</span></span>
<span id="cb9-141"><a href="#cb9-141" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-142"><a href="#cb9-142" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb9-143"><a href="#cb9-143" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb9-144"><a href="#cb9-144" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Subject) <span class="sc">+</span></span>
<span id="cb9-145"><a href="#cb9-145" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Tempo di reazione"</span>, <span class="at">x =</span> <span class="st">"Giorni di deprivazione del sonno"</span>)</span>
<span id="cb9-146"><a href="#cb9-146" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-147"><a href="#cb9-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-148"><a href="#cb9-148" aria-hidden="true" tabindex="-1"></a>Il grafico mostra che il modello attuale non si adatta in modo ottimale ai dati raccolti. Ciò evidenzia la necessità di adottare un approccio diverso per modellare in modo più accurato le relazioni presenti nei dati.</span>
<span id="cb9-149"><a href="#cb9-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-150"><a href="#cb9-150" aria-hidden="true" tabindex="-1"></a><span class="fu">## *No Pooling*: un modello per ciascun partecipante</span></span>
<span id="cb9-151"><a href="#cb9-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-152"><a href="#cb9-152" aria-hidden="true" tabindex="-1"></a>L'approccio del no pooling stima una retta di regressione distinta per ogni soggetto, trattando ciascuno di essi come un caso indipendente. Questo approccio consente di cogliere al meglio le differenze individuali, ma ignora completamente l'informazione condivisa tra i soggetti. Si tratta del metodo più vicino a un'analisi idiografica pura. In questo modo, ogni partecipante ha la propria intercetta e la propria pendenza. Tuttavia, le stime non sono regolarizzate, pertanto i soggetti con pochi dati possono produrre stime molto rumorose.</span>
<span id="cb9-153"><a href="#cb9-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-154"><a href="#cb9-154" aria-hidden="true" tabindex="-1"></a><span class="fu">### Implementazione con `brm()` mediante un *loop*</span></span>
<span id="cb9-155"><a href="#cb9-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-158"><a href="#cb9-158" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-159"><a href="#cb9-159" aria-hidden="true" tabindex="-1"></a><span class="co">#| output: false</span></span>
<span id="cb9-160"><a href="#cb9-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-161"><a href="#cb9-161" aria-hidden="true" tabindex="-1"></a><span class="co"># Otteniamo i livelli unici dei soggetti</span></span>
<span id="cb9-162"><a href="#cb9-162" aria-hidden="true" tabindex="-1"></a>subjects <span class="ot">&lt;-</span> <span class="fu">unique</span>(sleep2<span class="sc">$</span>Subject)</span>
<span id="cb9-163"><a href="#cb9-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-164"><a href="#cb9-164" aria-hidden="true" tabindex="-1"></a><span class="co"># Inizializziamo una lista per salvare i modelli</span></span>
<span id="cb9-165"><a href="#cb9-165" aria-hidden="true" tabindex="-1"></a>subject_models <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb9-166"><a href="#cb9-166" aria-hidden="true" tabindex="-1"></a>subject_coefs <span class="ot">&lt;-</span> <span class="fu">tibble</span>()</span>
<span id="cb9-167"><a href="#cb9-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-168"><a href="#cb9-168" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop sui soggetti</span></span>
<span id="cb9-169"><a href="#cb9-169" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (id <span class="cf">in</span> subjects) {</span>
<span id="cb9-170"><a href="#cb9-170" aria-hidden="true" tabindex="-1"></a>  data_i <span class="ot">&lt;-</span> <span class="fu">filter</span>(sleep2, Subject <span class="sc">==</span> id)</span>
<span id="cb9-171"><a href="#cb9-171" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb9-172"><a href="#cb9-172" aria-hidden="true" tabindex="-1"></a>    Reaction <span class="sc">~</span> days_deprived,</span>
<span id="cb9-173"><a href="#cb9-173" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> data_i,</span>
<span id="cb9-174"><a href="#cb9-174" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">gaussian</span>(),</span>
<span id="cb9-175"><a href="#cb9-175" aria-hidden="true" tabindex="-1"></a>    <span class="at">chains =</span> <span class="dv">2</span>, <span class="at">iter =</span> <span class="dv">1000</span>, <span class="at">refresh =</span> <span class="dv">0</span>,</span>
<span id="cb9-176"><a href="#cb9-176" aria-hidden="true" tabindex="-1"></a>    <span class="at">backend =</span> <span class="st">"cmdstanr"</span>,</span>
<span id="cb9-177"><a href="#cb9-177" aria-hidden="true" tabindex="-1"></a>    <span class="at">silent =</span> <span class="cn">TRUE</span></span>
<span id="cb9-178"><a href="#cb9-178" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-179"><a href="#cb9-179" aria-hidden="true" tabindex="-1"></a>  subject_models[[<span class="fu">as.character</span>(id)]] <span class="ot">&lt;-</span> fit</span>
<span id="cb9-180"><a href="#cb9-180" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-181"><a href="#cb9-181" aria-hidden="true" tabindex="-1"></a>  coef_i <span class="ot">&lt;-</span> <span class="fu">fixef</span>(fit)[, <span class="st">"Estimate"</span>]</span>
<span id="cb9-182"><a href="#cb9-182" aria-hidden="true" tabindex="-1"></a>  subject_coefs <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(subject_coefs, <span class="fu">tibble</span>(</span>
<span id="cb9-183"><a href="#cb9-183" aria-hidden="true" tabindex="-1"></a>    <span class="at">Subject =</span> id,</span>
<span id="cb9-184"><a href="#cb9-184" aria-hidden="true" tabindex="-1"></a>    <span class="at">intercept =</span> coef_i[<span class="dv">1</span>],</span>
<span id="cb9-185"><a href="#cb9-185" aria-hidden="true" tabindex="-1"></a>    <span class="at">slope =</span> coef_i[<span class="dv">2</span>]</span>
<span id="cb9-186"><a href="#cb9-186" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb9-187"><a href="#cb9-187" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-188"><a href="#cb9-188" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-189"><a href="#cb9-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-190"><a href="#cb9-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-193"><a href="#cb9-193" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-194"><a href="#cb9-194" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb9-195"><a href="#cb9-195" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleep2, <span class="fu">aes</span>(<span class="at">x =</span> days_deprived, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb9-196"><a href="#cb9-196" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(</span>
<span id="cb9-197"><a href="#cb9-197" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> subject_coefs,</span>
<span id="cb9-198"><a href="#cb9-198" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">intercept =</span> intercept, <span class="at">slope =</span> slope, <span class="at">color =</span> Subject),</span>
<span id="cb9-199"><a href="#cb9-199" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">0.8</span></span>
<span id="cb9-200"><a href="#cb9-200" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-201"><a href="#cb9-201" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb9-202"><a href="#cb9-202" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb9-203"><a href="#cb9-203" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Subject) <span class="sc">+</span></span>
<span id="cb9-204"><a href="#cb9-204" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Tempo di reazione"</span>, <span class="at">x =</span> <span class="st">"Giorni di deprivazione del sonno"</span>) <span class="sc">+</span></span>
<span id="cb9-205"><a href="#cb9-205" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb9-206"><a href="#cb9-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-207"><a href="#cb9-207" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-208"><a href="#cb9-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-209"><a href="#cb9-209" aria-hidden="true" tabindex="-1"></a>Questo approccio evidenzia efficacemente le differenze individuali sia nella pendenza, che riflette il tasso di peggioramento, sia nell'intercetta, corrispondente al livello basale di reazione. Tuttavia, questo approccio non sfrutta l'informazione condivisa all'interno del gruppo, limitando così la sua efficacia inferenziale. Inoltre, le stime risultano particolarmente instabili per i soggetti con un numero limitato di osservazioni.</span>
<span id="cb9-210"><a href="#cb9-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-211"><a href="#cb9-211" aria-hidden="true" tabindex="-1"></a>Nel prossimo passo, vedremo un compromesso tra il *no pooling* e il *complete pooling*: il *partial pooling*, tipico dei modelli multilivello bayesiani.</span>
<span id="cb9-212"><a href="#cb9-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-213"><a href="#cb9-213" aria-hidden="true" tabindex="-1"></a><span class="fu">## *Partial pooling*: un compromesso tra individuo e gruppo</span></span>
<span id="cb9-214"><a href="#cb9-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-215"><a href="#cb9-215" aria-hidden="true" tabindex="-1"></a>Nel modellare i dati psicologici, dobbiamo scegliere se trattare ogni partecipante come un caso a sé stante (*no pooling*) o considerare tutti i dati come provenienti da un unico gruppo omogeneo (*complete pooling*). Il *partial pooling* è un approccio intermedio: ogni soggetto ha le proprie stime, ma queste sono influenzate anche dai dati degli altri soggetti. Ciò si realizza con i modelli multilivello o a effetti misti.</span>
<span id="cb9-216"><a href="#cb9-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-217"><a href="#cb9-217" aria-hidden="true" tabindex="-1"></a><span class="fu">### Il concetto di *shrinkage*</span></span>
<span id="cb9-218"><a href="#cb9-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-219"><a href="#cb9-219" aria-hidden="true" tabindex="-1"></a>Nel *partial pooling*, le stime individuali subiscono un fenomeno di contrazione verso la media del gruppo noto come *shrinkage*. Questo meccanismo opera come una sorta di regolarizzazione statistica che stabilizza le stime, particolarmente utile quando i dati individuali sono limitati o affetti da rumore. Operativamente, il modello bilancia dinamicamente le fonti di informazione: per i partecipanti con un numero limitato di osservazioni, privilegia l'informazione di gruppo; quando invece sono disponibili numerosi dati individuali, attribuisce maggiore peso all'evidenza specifica del soggetto.</span>
<span id="cb9-220"><a href="#cb9-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-221"><a href="#cb9-221" aria-hidden="true" tabindex="-1"></a><span class="fu">### Implementazione con `brm()`</span></span>
<span id="cb9-222"><a href="#cb9-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-223"><a href="#cb9-223" aria-hidden="true" tabindex="-1"></a>L'obiettivo consiste nello specificare un modello che accomodi *eterogeneità individuale sia nel livello basale (intercetta) che nel tasso di cambiamento (pendenza)*.</span>
<span id="cb9-224"><a href="#cb9-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-227"><a href="#cb9-227" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-228"><a href="#cb9-228" aria-hidden="true" tabindex="-1"></a><span class="co">#| output: false</span></span>
<span id="cb9-229"><a href="#cb9-229" aria-hidden="true" tabindex="-1"></a><span class="co"># Modello multilivello (partial pooling)</span></span>
<span id="cb9-230"><a href="#cb9-230" aria-hidden="true" tabindex="-1"></a>pp_model <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb9-231"><a href="#cb9-231" aria-hidden="true" tabindex="-1"></a>  Reaction <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> days_deprived <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> days_deprived <span class="sc">|</span> Subject),</span>
<span id="cb9-232"><a href="#cb9-232" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> sleep2,</span>
<span id="cb9-233"><a href="#cb9-233" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">gaussian</span>(),</span>
<span id="cb9-234"><a href="#cb9-234" aria-hidden="true" tabindex="-1"></a>  <span class="at">chains =</span> <span class="dv">2</span>, <span class="at">iter =</span> <span class="dv">2000</span>, <span class="at">seed =</span> <span class="dv">123</span>,</span>
<span id="cb9-235"><a href="#cb9-235" aria-hidden="true" tabindex="-1"></a>  <span class="at">backend =</span> <span class="st">"cmdstanr"</span>,</span>
<span id="cb9-236"><a href="#cb9-236" aria-hidden="true" tabindex="-1"></a>  <span class="at">refresh =</span> <span class="dv">0</span></span>
<span id="cb9-237"><a href="#cb9-237" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-238"><a href="#cb9-238" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-239"><a href="#cb9-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-240"><a href="#cb9-240" aria-hidden="true" tabindex="-1"></a>Qui la sintassi <span class="in">`1 + days_deprived | Subject`</span> specifica che a ciascun soggetto viene associata un'intercetta unica e una pendenza specifica per la variabile <span class="in">`days_deprived`</span>.</span>
<span id="cb9-241"><a href="#cb9-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-242"><a href="#cb9-242" aria-hidden="true" tabindex="-1"></a>Costruiamo le predizioni del modello per ciascun soggetto, considerando l'intero range di giorni di deprivazione, e procediamo alla visualizzazione dei risultati:</span>
<span id="cb9-243"><a href="#cb9-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-246"><a href="#cb9-246" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-247"><a href="#cb9-247" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb9-248"><a href="#cb9-248" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">crossing</span>(</span>
<span id="cb9-249"><a href="#cb9-249" aria-hidden="true" tabindex="-1"></a>  <span class="at">Subject =</span> <span class="fu">unique</span>(sleep2<span class="sc">$</span>Subject),</span>
<span id="cb9-250"><a href="#cb9-250" aria-hidden="true" tabindex="-1"></a>  <span class="at">days_deprived =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">7</span></span>
<span id="cb9-251"><a href="#cb9-251" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-252"><a href="#cb9-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-253"><a href="#cb9-253" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> newdata <span class="sc">|&gt;</span> <span class="fu">mutate</span>(</span>
<span id="cb9-254"><a href="#cb9-254" aria-hidden="true" tabindex="-1"></a>  <span class="at">Reaction =</span> <span class="fu">fitted</span>(pp_model, <span class="at">newdata =</span> newdata)[, <span class="st">"Estimate"</span>]</span>
<span id="cb9-255"><a href="#cb9-255" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-256"><a href="#cb9-256" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-257"><a href="#cb9-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-260"><a href="#cb9-260" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-261"><a href="#cb9-261" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb9-262"><a href="#cb9-262" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleep2, <span class="fu">aes</span>(<span class="at">x =</span> days_deprived, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb9-263"><a href="#cb9-263" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> newdata, <span class="fu">aes</span>(<span class="at">group =</span> Subject), <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb9-264"><a href="#cb9-264" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb9-265"><a href="#cb9-265" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Subject) <span class="sc">+</span></span>
<span id="cb9-266"><a href="#cb9-266" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-267"><a href="#cb9-267" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Giorni di deprivazione del sonno"</span>,</span>
<span id="cb9-268"><a href="#cb9-268" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Tempo di reazione (ms)"</span>,</span>
<span id="cb9-269"><a href="#cb9-269" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Modello con partial pooling"</span></span>
<span id="cb9-270"><a href="#cb9-270" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-271"><a href="#cb9-271" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-272"><a href="#cb9-272" aria-hidden="true" tabindex="-1"></a><span class="fu">## Il ruolo dei modelli multilivello in psicologia</span></span>
<span id="cb9-273"><a href="#cb9-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-274"><a href="#cb9-274" aria-hidden="true" tabindex="-1"></a><span class="fu">### Una sintesi tra nomotetico e idiografico</span></span>
<span id="cb9-275"><a href="#cb9-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-276"><a href="#cb9-276" aria-hidden="true" tabindex="-1"></a>La ricerca psicologica si è tradizionalmente articolata in due prospettive epistemologiche distinte: l'approccio nomotetico, volto all'identificazione di principi generali applicabili a tutta la popolazione, e l'approccio idiografico, focalizzato sull'indagine delle caratteristiche distintive di ciascun individuo. I modelli multilivello rappresentano una sintesi metodologica che supera questa dicotomia, riconoscendo che le traiettorie individuali (dimensione idiografica) si sviluppano all'interno di contesti collettivi che ne influenzano l'andamento (dimensione nomotetica).</span>
<span id="cb9-277"><a href="#cb9-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-278"><a href="#cb9-278" aria-hidden="true" tabindex="-1"></a>Questa integrazione consente di indagare sistematicamente le differenze individuali, preservando al contempo la capacità di generalizzazione a livello di popolazione e offrendo un contributo metodologicamente robusto alla comprensione del comportamento umano.</span>
<span id="cb9-279"><a href="#cb9-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-280"><a href="#cb9-280" aria-hidden="true" tabindex="-1"></a>Tuttavia, l'applicazione di questi modelli richiede una riflessione critica sulle assunzioni teoriche su cui si basano. Come evidenziato da @richters2021incredible, gran parte della ricerca psicologica adotta implicitamente un'«assunzione ergonomica» che presuppone un'omogeneità psicologica fondamentale tra gli individui. Questa premessa, sebbene sia funzionale all'aggregazione dei dati e alla stima degli effetti medi, rischia di mascherare le sostanziali eterogeneità, producendo quello che l'autore chiama "causal debris": una proliferazione di risultati significativi, ma teoricamente frammentari e difficili da replicare.</span>
<span id="cb9-281"><a href="#cb9-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-282"><a href="#cb9-282" aria-hidden="true" tabindex="-1"></a>La capacità dei modelli multilivello di stimare simultaneamente effetti medi e variazioni individuali non garantisce che tali effetti riflettano processi causali omogenei tra i partecipanti. In assenza di una solida base teorica che specifichi quali meccanismi siano plausibilmente condivisi e in che modo possano variare, si rischia di interpretare le differenze qualitative come semplici deviazioni quantitative da un effetto medio.</span>
<span id="cb9-283"><a href="#cb9-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-284"><a href="#cb9-284" aria-hidden="true" tabindex="-1"></a>Pertanto, l'implementazione di modelli multilivello in psicologia richiede un'attenzione critica alla plausibilità teorica dell'omogeneità assunta, affiancando all'analisi statistica l'esplorazione di approcci complementari, quali la modellizzazione idiografica pura o l'identificazione di sottogruppi teoricamente fondati. Solo attraverso questa integrazione metodologica è possibile cogliere appieno la complessità e la variabilità che caratterizzano i fenomeni psicologici.</span>
<span id="cb9-285"><a href="#cb9-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-286"><a href="#cb9-286" aria-hidden="true" tabindex="-1"></a><span class="fu">## Interpretazione del modello</span></span>
<span id="cb9-287"><a href="#cb9-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-288"><a href="#cb9-288" aria-hidden="true" tabindex="-1"></a>Dopo aver stimato un modello multilivello, è importante saperlo leggere e interpretare. In particolare, analizzeremo tre componenti fondamentali: gli *effetti fissi* (la media del gruppo), gli *effetti casuali* (le deviazioni individuali) e la varianza tra soggetti.</span>
<span id="cb9-289"><a href="#cb9-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-290"><a href="#cb9-290" aria-hidden="true" tabindex="-1"></a><span class="fu">### Effetti fissi: la media del gruppo</span></span>
<span id="cb9-291"><a href="#cb9-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-294"><a href="#cb9-294" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-295"><a href="#cb9-295" aria-hidden="true" tabindex="-1"></a><span class="fu">fixef</span>(pp_model)</span>
<span id="cb9-296"><a href="#cb9-296" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-297"><a href="#cb9-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-298"><a href="#cb9-298" aria-hidden="true" tabindex="-1"></a>Questo comando restituisce le stime degli effetti fissi a livello di popolazione:</span>
<span id="cb9-299"><a href="#cb9-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-300"><a href="#cb9-300" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>l'*intercetta* corrisponde al tempo di reazione medio stimato in condizioni basali (giorno 0, senza deprivazione di sonno);</span>
<span id="cb9-301"><a href="#cb9-301" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>il *coefficiente di `days_deprived`* indica l'incremento medio del tempo di reazione associato a ogni giorno aggiuntivo di deprivazione di sonno.</span>
<span id="cb9-302"><a href="#cb9-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-303"><a href="#cb9-303" aria-hidden="true" tabindex="-1"></a>Questi parametri rappresentano gli effetti "nomotetici" del modello, descrivendo le relazioni medie che caratterizzano l'intera popolazione di riferimento.</span>
<span id="cb9-304"><a href="#cb9-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-305"><a href="#cb9-305" aria-hidden="true" tabindex="-1"></a><span class="fu">### Effetti casuali: le deviazioni individuali</span></span>
<span id="cb9-306"><a href="#cb9-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-309"><a href="#cb9-309" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-310"><a href="#cb9-310" aria-hidden="true" tabindex="-1"></a><span class="fu">ranef</span>(pp_model)<span class="sc">$</span>Subject</span>
<span id="cb9-311"><a href="#cb9-311" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-312"><a href="#cb9-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-313"><a href="#cb9-313" aria-hidden="true" tabindex="-1"></a>Questo comando restituisce, per ciascun partecipante, l’entità con cui i suoi parametri si discostano dalla media di popolazione.</span>
<span id="cb9-314"><a href="#cb9-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-315"><a href="#cb9-315" aria-hidden="true" tabindex="-1"></a>In particolare, vengono riportati:</span>
<span id="cb9-316"><a href="#cb9-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-317"><a href="#cb9-317" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>gli *scostamenti dell’intercetta*, che riflettono differenze nei tempi di reazione di base tra i soggetti;</span>
<span id="cb9-318"><a href="#cb9-318" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>gli *scostamenti della pendenza*, che mostrano quanto ciascun individuo sia più o meno sensibile, rispetto alla media del gruppo, all’effetto della deprivazione di sonno.</span>
<span id="cb9-319"><a href="#cb9-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-320"><a href="#cb9-320" aria-hidden="true" tabindex="-1"></a>Queste *deviazioni individuali*, note come *effetti casuali stimati*, quantificano la componente specifica di ciascun partecipante che non è spiegata dagli effetti fissi del modello. Esse consentono di osservare come ogni individuo si discosti sistematicamente dal comportamento medio del gruppo.</span>
<span id="cb9-321"><a href="#cb9-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-322"><a href="#cb9-322" aria-hidden="true" tabindex="-1"></a><span class="fu">### Varianza tra soggetti: quanta differenza c’è nel campione</span></span>
<span id="cb9-323"><a href="#cb9-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-326"><a href="#cb9-326" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-327"><a href="#cb9-327" aria-hidden="true" tabindex="-1"></a><span class="fu">VarCorr</span>(pp_model)<span class="sc">$</span>Subject</span>
<span id="cb9-328"><a href="#cb9-328" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-329"><a href="#cb9-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-330"><a href="#cb9-330" aria-hidden="true" tabindex="-1"></a>L’output riporta la *dispersione* (deviazioni standard, varianze e covarianze) e la *correlazione* tra gli effetti casuali dell’intercetta e della pendenza. Queste informazioni descrivono l'eterogeneità tra i partecipanti e il modo in cui le loro differenze nei tempi di reazione si associano all'effetto della deprivazione di sonno.</span>
<span id="cb9-331"><a href="#cb9-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-332"><a href="#cb9-332" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>La *deviazione standard dell’intercetta* è di circa *33.6 ms* (*IC 95%: 20.9 – 53.5*), indicando una notevole variabilità nei *tempi di reazione di base*: alcuni soggetti sono sistematicamente più rapidi, altri più lenti, anche prima dell'intervento della manipolazione sperimentale.</span>
<span id="cb9-333"><a href="#cb9-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-334"><a href="#cb9-334" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>La *deviazione standard della pendenza* è pari a *7.4 ms* (*IC 95%: 4.4 – 11.6*), suggerendo che esistono differenze di rilievo anche nella sensibilità individuale alla deprivazione di sonno. In altre parole, i soggetti non reagiscono tutti allo stesso modo: alcuni mostrano un rallentamento marcato, altri quasi nullo.</span>
<span id="cb9-335"><a href="#cb9-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-336"><a href="#cb9-336" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>La *correlazione tra intercetta e pendenza* è stimata a *0.18*, ma con un intervallo di credibilità ampio (*–0.41, 0.76*). Questa incertezza indica che non vi è una prova consistente di un legame tra i tempi di reazione di base e l'entità dell'effetto della deprivazione: non possiamo affermare con certezza che chi parte più lento tenda anche ad aumentare di più i tempi con il sonno ridotto.</span>
<span id="cb9-337"><a href="#cb9-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-338"><a href="#cb9-338" aria-hidden="true" tabindex="-1"></a>La *matrice di covarianza*, anch'essa presente nell'output, completa il quadro informativo:</span>
<span id="cb9-339"><a href="#cb9-339" aria-hidden="true" tabindex="-1"></a>la *covarianza* tra intercetta e pendenza è stimata attorno a *39*, sebbene con un ampio intervallo di credibilità (*–137, 205*). Questo parametro quantifica la *relazione sistematica* tra i due effetti casuali: un valore positivo indicherebbe che soggetti con tempi di reazione basali più elevati tendono a mostrare incrementi più marcati in condizioni di deprivazione, mentre la sostanziale sovrapposizione dello zero nell'intervallo di credibilità suggerisce che, nei nostri dati, le due dimensioni potrebbero variare in modo indipendente.</span>
<span id="cb9-340"><a href="#cb9-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-341"><a href="#cb9-341" aria-hidden="true" tabindex="-1"></a>Nel complesso, il modello rivela una *marcata eterogeneità tra gli individui*, sia nei livelli di prestazione iniziale sia nella risposta alla manipolazione. Questa diversità rappresenta la variabilità idiografica del campione: ciascun individuo presenta un proprio profilo di funzionamento, distinguibile ma connesso a un quadro di gruppo condiviso.</span>
<span id="cb9-342"><a href="#cb9-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-343"><a href="#cb9-343" aria-hidden="true" tabindex="-1"></a>**In sintesi:**</span>
<span id="cb9-344"><a href="#cb9-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-345"><a href="#cb9-345" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Comando**               | **Cosa restituisce**                          | **Significato**                                 <span class="pp">|</span></span>
<span id="cb9-346"><a href="#cb9-346" aria-hidden="true" tabindex="-1"></a><span class="pp">| -------------------------</span> <span class="pp">| ---------------------------------------------</span> <span class="pp">| -----------------------------------------------</span> <span class="pp">|</span></span>
<span id="cb9-347"><a href="#cb9-347" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`fixef(pp_model)`</span>         <span class="pp">|</span> Effetti fissi (intercetta e pendenza medie)   <span class="pp">|</span> Relazioni medie a livello di popolazione        <span class="pp">|</span></span>
<span id="cb9-348"><a href="#cb9-348" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`ranef(pp_model)$Subject`</span> <span class="pp">|</span> Deviazioni individuali dagli effetti fissi    <span class="pp">|</span> Specificità di ciascun soggetto rispetto alla media <span class="pp">|</span></span>
<span id="cb9-349"><a href="#cb9-349" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`VarCorr(pp_model)`</span>       <span class="pp">|</span> Varianza e correlazione degli effetti casuali <span class="pp">|</span> Entità e struttura della variabilità individuale <span class="pp">|</span></span>
<span id="cb9-350"><a href="#cb9-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-351"><a href="#cb9-351" aria-hidden="true" tabindex="-1"></a>Queste funzioni consentono di *interpretare il modello multilivello* in modo esaustivo: non solo identificano *le tendenze centrali*, ma anche *l'entità delle differenze individuali* rispetto a tali tendenze. Questa duplice lettura costituisce l'essenza del *partial pooling*.</span>
<span id="cb9-352"><a href="#cb9-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-353"><a href="#cb9-353" aria-hidden="true" tabindex="-1"></a><span class="fu">## Riflessioni conclusive {.unlisted .unnumbered}</span></span>
<span id="cb9-354"><a href="#cb9-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-355"><a href="#cb9-355" aria-hidden="true" tabindex="-1"></a>I modelli multilivello costituiscono uno strumento metodologico fondamentale per la ricerca psicologica, particolarmente adatto all'analisi di dati con struttura gerarchica, come quelli derivanti da misurazioni ripetute sugli stessi individui. Il loro principale vantaggio risiede nella capacità di integrare informazioni provenienti da diversi livelli di analisi, consentendo di stimare congiuntamente le tendenze generali a livello di popolazione e le variazioni specifiche a livello individuale.</span>
<span id="cb9-356"><a href="#cb9-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-357"><a href="#cb9-357" aria-hidden="true" tabindex="-1"></a>In questo capitolo è stato introdotto il concetto di "partial pooling", che si colloca a metà strada tra due approcci estremi: il "complete pooling", che presuppone l'omogeneità totale tra i soggetti, e il "no pooling", che analizza ogni individuo in modo completamente isolato. Il partial pooling rappresenta un compromesso ottimale tra queste due prospettive, consentendo, da un lato, di modellare sistematicamente la variabilità interindividuale e, dall'altro, di sfruttare strategicamente l'informazione condivisa nel campione per ottenere stime più robuste.</span>
<span id="cb9-358"><a href="#cb9-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-359"><a href="#cb9-359" aria-hidden="true" tabindex="-1"></a>Il fenomeno dello *shrinkage*, ovvero la contrazione delle stime individuali verso la media di gruppo, rappresenta una caratteristica essenziale di questo approccio. Questo meccanismo di regolarizzazione statistica non rappresenta un limite metodologico, ma un elemento funzionale che previene il sovradattamento e riduce l'incertezza delle stime, risultando particolarmente vantaggioso quando i dati individuali sono limitati o rumorosi.</span>
<span id="cb9-360"><a href="#cb9-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-361"><a href="#cb9-361" aria-hidden="true" tabindex="-1"></a>Dal punto di vista epistemologico, i modelli multilivello superano la tradizionale dicotomia tra approccio nomotetico e idiografico. Questi modelli, infatti, permettono di rispondere simultaneamente a domande relative alle relazioni medie a livello di popolazione e all'identificazione delle specifiche caratteristiche individuali, riconoscendo la coesistenza di pattern generali e di differenze sistematiche tra i soggetti.</span>
<span id="cb9-362"><a href="#cb9-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-363"><a href="#cb9-363" aria-hidden="true" tabindex="-1"></a>L'applicazione al dataset <span class="in">`sleepstudy`</span> ha mostrato in modo concreto come modellare gli effetti della deprivazione di sonno sui tempi di reazione, distinguendo chiaramente l'effetto medio nella popolazione dalla variabilità interindividuale nella risposta alla deprivazione. L'analisi ha dimostrato che è possibile stimare i parametri specifici per ciascun partecipante, mantenendo al contempo la coerenza con il principio del partial pooling.</span>
<span id="cb9-364"><a href="#cb9-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-365"><a href="#cb9-365" aria-hidden="true" tabindex="-1"></a>Questi modelli trovano ampia applicazione in vari ambiti della psicologia, dalla psicometria allo studio delle traiettorie di sviluppo, e costituiscono la base concettuale per i successivi modelli di crescita latente. Rappresentano inoltre il quadro metodologico di riferimento per affrontare il tema dell'affidabilità tra osservatori, che verrà approfondito in seguito.</span>
<span id="cb9-366"><a href="#cb9-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-367"><a href="#cb9-367" aria-hidden="true" tabindex="-1"></a>In sintesi, i modelli multilivello offrono un approccio rigoroso e sofisticato per l'analisi dei dati psicologici, che coniuga il rigore metodologico con l'attenzione necessaria alla complessità dei fenomeni umani. La loro adozione contribuisce significativamente allo sviluppo di una psicologia scientifica che sia in grado di cogliere sia le regolarità generali sia le specificità individuali che caratterizzano il comportamento umano.</span>
<span id="cb9-368"><a href="#cb9-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-369"><a href="#cb9-369" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse=true title="Informazioni sull'ambiente di sviluppo"}</span>
<span id="cb9-372"><a href="#cb9-372" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-373"><a href="#cb9-373" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span>
<span id="cb9-374"><a href="#cb9-374" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-375"><a href="#cb9-375" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-376"><a href="#cb9-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-377"><a href="#cb9-377" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bibliografia {.unnumbered .unlisted}</span></span>
<span id="cb9-378"><a href="#cb9-378" aria-hidden="true" tabindex="-1"></a></span>
</code></pre></div><button title="Copia negli appunti" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Metodi bayesiani in psicologia — Companion site</strong>.<br>
Materiali di accompagnamento e approfondimento al manuale UTET.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ccaudek/utet-companion/blob/main/chapters/linear_models/12_multilevel.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/utet-companion/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>