<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>13&nbsp; Introduzione pratica a Stan – Metodi bayesiani in psicologia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/mcmc/04_stan_odds_ratio_stan.html" rel="next">
<link href="../../chapters/mcmc/02_ppl.html" rel="prev">
<link href="../../style/gauss.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-af5d064118ae80f4bafc3d843c3c3870.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QT5S3P9D31"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QT5S3P9D31', { 'anonymize_ip': true});
</script><style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/mcmc/introduction_sec.html">MCMC</a></li><li class="breadcrumb-item"><a href="../../chapters/mcmc/03_stan_intro.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Introduzione pratica a Stan</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../../index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Metodi bayesiani in psicologia</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/utet-companion/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Attiva/disattiva la modalità lettore">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Struttura del companion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Prefazione</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Inferenza</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/02_uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Abbracciare l’incertezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/03_uncertainty_quantification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">La quantificazione dell’incertezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/04_statistical_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modelli statistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/05_subj_prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Aggiornare le credenze su un parametro: dal prior alla posterior</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/06_conjugate_families.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Distribuzioni coniugate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/07_summary_posterior.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sintesi a posteriori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/08_balance_prior_post.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">L’influenza della distribuzione a priori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/09_prior_pred_check.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Controllo predittivo a priori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/10_post_pred_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Distribuzione predittiva a posteriori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">MCMC</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/01_metropolis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">L’algoritmo di Metropolis-Hastings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/02_ppl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linguaggi di programmazione probabilistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/03_stan_intro.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Introduzione pratica a Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/04_stan_odds_ratio_stan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Analisi bayesiana dell’odds ratio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/05_stan_two_means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Confrontare due medie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/06_stan_poisson_model_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Modello di Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/07_stan_gaussian_mixture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Modelli Mistura Gaussiani</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/08_stan_nuisance_parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Modelli con più di un parametro</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/09_stan_hier_beta_binom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Modello gerarchico beta-binomiale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/10_stan_parametrization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Parametrizzazioni centered e non-centered</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/11_bayesian_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Flusso di lavoro bayesiano</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive sulla sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Regressione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/01_reglin_frequentist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">La regressione lineare bivariata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/02_regr_toward_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">La regressione verso la media</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/03_reglin_bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Modello bayesiano di regressione lineare bivariata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/04_synt_sugar_sea_ice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Zucchero sintattico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/05_stan_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Regressione lineare in Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/06_specification_error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Errore di specificazione e bias da variabile omessa</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/07_one_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Inferenza bayesiana su una media</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/08_two_means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Confronto tra le medie di due gruppi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/09_effect_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">La grandezza dell’effetto: valutare la rilevanza pratica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/10_sample_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Pianificazione della dimensione campionaria</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/11_anova_1via.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">ANOVA ad una via</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/12_meas_error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Errore di misurazione e attenuazione: una soluzione bayesiana</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">GLM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/01_logistic_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Regressione logistica con Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/02_one_proportion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Inferenza sulle proporzioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/03_two_proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Confronto tra due proporzioni con la regressione logistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/04_poisson_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Modello di Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/05_logistic_process.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Dal GLM a un modello processuale per dati binari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/06_missing_values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Dati mancanti in psicologia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive sulla sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Entropia</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/01_entropy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Entropia e informazione di Shannon</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/02_kl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">La divergenza di Kullback-Leibler</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/03_model_comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Valutare i modelli bayesiani</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Modelli</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/01_dynamic_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Il modello di revisione degli obiettivi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/02_dynamic_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Estensioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/03_rescorla_wagner.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Il modello di Rescorla–Wagner</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/04_study_method.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Decisione ottimale e utilità attesa: l’approccio bayesiano</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Crisi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/introduction_replication_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/01_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">La crisi della replicazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/02_limits_stat_freq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Limiti dell’inferenza frequentista</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/03_effect_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">La grandezza dell’effetto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/04_s_m_errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Errori di segno e errori di grandezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/05_p_values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">La fragilità del <em>p</em>-valore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/06_changes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Riforma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/07_degrees_of_freedom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">I gradi di libertà del ricercatore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/08_integrity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Integrità della ricerca</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Epilogo</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epiloque/epiloque.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Considerazioni Conclusive</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a01_shell.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">La Shell</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a01a_files.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Cartelle e documenti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a02_math_symbols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Simbologia di base</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a03_latex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Equazioni Matematiche in LaTeX</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a11_numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Numeri e intervalli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a12_sum_notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Sommatorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a13_sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">Insiemi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a14_combinatorics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">Calcolo combinatorio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a15_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">I</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a35_other_conjugate_families.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">J</span>&nbsp; <span class="chapter-title">Altre famiglie coniugate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a36_gamma_poisson_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">K</span>&nbsp; <span class="chapter-title">Modello coniugato Gamma-Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a40_metropolis_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">L</span>&nbsp; <span class="chapter-title">Metropolis: esempio Normale–Normale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a41_install_cmdstan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">M</span>&nbsp; <span class="chapter-title">Come installare CmdStan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a42_cmdstanr_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">N</span>&nbsp; <span class="chapter-title">Implementazione di modelli Bayesiani con Stan tramite <code>cmdstanr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a43_stan_lang.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">O</span>&nbsp; <span class="chapter-title">Linguaggio Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a44_stan_diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">P</span>&nbsp; <span class="chapter-title">Diagnostica delle catene markoviane</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a45_stan_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">Q</span>&nbsp; <span class="chapter-title">Controlli predittivi bayesiani (a priori e a posteriori) con <code>cmdstanr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a50_lin_fun.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">R</span>&nbsp; <span class="chapter-title">La funzione lineare</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Sommario</h2>
   
  <ul class="collapse">
<li><a href="#programmazione-probabilistica-con-stan" id="toc-programmazione-probabilistica-con-stan" class="nav-link active" data-scroll-target="#programmazione-probabilistica-con-stan"><span class="header-section-number">13.1</span> Programmazione probabilistica con Stan</a></li>
  <li><a href="#modello-betabinomiale" id="toc-modello-betabinomiale" class="nav-link" data-scroll-target="#modello-betabinomiale"><span class="header-section-number">13.2</span> Modello Beta–Binomiale</a></li>
  <li><a href="#dati-continui-stima-della-media-con-varianza-nota" id="toc-dati-continui-stima-della-media-con-varianza-nota" class="nav-link" data-scroll-target="#dati-continui-stima-della-media-con-varianza-nota"><span class="header-section-number">13.3</span> Dati continui: stima della media con varianza nota</a></li>
  <li><a href="#test-di-ipotesi-in-prospettiva-bayesiana" id="toc-test-di-ipotesi-in-prospettiva-bayesiana" class="nav-link" data-scroll-target="#test-di-ipotesi-in-prospettiva-bayesiana"><span class="header-section-number">13.4</span> Test di ipotesi in prospettiva bayesiana</a></li>
  <li><a href="#diagnostiche-di-campionamento" id="toc-diagnostiche-di-campionamento" class="nav-link" data-scroll-target="#diagnostiche-di-campionamento"><span class="header-section-number">13.5</span> Diagnostiche di campionamento</a></li>
  <li><a href="#prior-e-posterior-predictive-check" id="toc-prior-e-posterior-predictive-check" class="nav-link" data-scroll-target="#prior-e-posterior-predictive-check"><span class="header-section-number">13.6</span> Prior e Posterior Predictive Check</a></li>
  </ul><div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ccaudek/utet-companion/blob/main/chapters/mcmc/03_stan_intro.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/utet-companion/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/mcmc/introduction_sec.html">MCMC</a></li><li class="breadcrumb-item"><a href="../../chapters/mcmc/03_stan_intro.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Introduzione pratica a Stan</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-mcmc-stan-intro" class="quarto-section-identifier"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Introduzione pratica a Stan</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="introduzione" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="introduzione">Introduzione</h2>
<p>Nei capitoli precedenti abbiamo visto come l’algoritmo di Metropolis fornisca una soluzione generale al problema dell’inferenza bayesiana e come i linguaggi di programmazione probabilistica abbiano reso questa soluzione praticabile nella ricerca quotidiana. Ora è il momento di incontrare lo strumento che utilizzeremo concretamente nel nostro percorso: <em>Stan</em>.</p>
<p>Stan non è semplicemente un altro software statistico. È un linguaggio di programmazione probabilistica progettato per esprimere modelli bayesiani in modo chiaro e flessibile e per eseguire l’inferenza con algoritmi di campionamento allo stato dell’arte. In particolare, Stan utilizza varianti avanzate dell’Hamiltonian Monte Carlo (HMC), come l’algoritmo NUTS, che offrono efficienza e affidabilità molto superiori rispetto al semplice Metropolis.</p>
<p>Dal punto di vista concettuale, però, nulla cambia: la logica rimane la stessa che abbiamo già compreso. Stan non fa “magia”, ma implementa con grande efficacia ciò che Metropolis aveva già reso possibile. Per questo è importante vederlo come la <em>naturale evoluzione pratica</em> del percorso che abbiamo seguito fin qui.</p>
<p>Per la ricerca psicologica, Stan ha un vantaggio particolare. Molti dei modelli che ci interessano – modelli gerarchici, modelli di apprendimento, modelli dinamici – richiedono più parametri e strutture complesse. Implementarli a mano sarebbe quasi impossibile. Con Stan, invece, possiamo concentrarci sul modello teorico e tradurlo in codice relativamente semplice, lasciando al software la gestione dei dettagli computazionali.</p>
<p>Nei prossimi capitoli vedremo come iniziare a scrivere modelli in Stan, partendo da esempi elementari per arrivare a strutture più articolate. L’obiettivo non è soltanto imparare un nuovo linguaggio, ma acquisire la capacità di formalizzare i modelli psicologici come processi generativi, traducendoli in analisi statistiche riproducibili e trasparenti.</p>
<section id="panoramica-del-capitolo" class="level3 unnumbered unlisted"><h3 class="unnumbered unlisted anchored" data-anchor-id="panoramica-del-capitolo">Panoramica del capitolo</h3>
<ul>
<li>I blocchi del codice Stan.<br>
</li>
<li>Scrivere e stimare modelli semplici con <code>cmdstanr</code>.<br>
</li>
<li>Interpretare i risultati MCMC tramite riassunti e diagnostiche.<br>
</li>
<li>Valutare la coerenza del modello con prior e posterior predictive check.</li>
</ul>
<div class="callout callout-style-simple callout-caution no-icon callout-titled" title="Preparazione del Notebook">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Attenzione</span>Preparazione del Notebook
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html">requireNamespace</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">cmdstanr</span>, <span class="va">posterior</span>, <span class="va">insight</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section></section><section id="programmazione-probabilistica-con-stan" class="level2" data-number="13.1"><h2 data-number="13.1" class="anchored" data-anchor-id="programmazione-probabilistica-con-stan">
<span class="header-section-number">13.1</span> Programmazione probabilistica con Stan</h2>
<p>Ogni programma Stan è organizzato in blocchi distinti, che corrispondono a funzioni precise <span class="citation" data-cites="nicenboim2025introduction">(<a href="#ref-nicenboim2025introduction" role="doc-biblioref">Nicenboim et al., 2025</a>)</span>.</p>
<ul>
<li>Nel blocco <code>data</code> dichiariamo le variabili osservate che passiamo dall’esterno;</li>
<li>in <code>parameters</code> indichiamo le quantità ignote che vogliamo stimare;</li>
<li>nel blocco <code>model</code> specifichiamo le assunzioni probabilistiche — cioè le distribuzioni a priori e la verosimiglianza;</li>
<li>in <code>generated quantities</code> possiamo calcolare misure derivate, come predizioni o log-likelihood, che non influiscono sulla stima ma sono utili per l’analisi successiva.</li>
</ul>
<p>Possiamo pensare a un programma Stan come a una “ricetta”. Nel blocco <code>data</code> mettiamo gli ingredienti che già conosciamo (i dati osservati), in <code>parameters</code> dichiariamo gli ingredienti mancanti (i parametri da stimare), in <code>model</code> scriviamo le regole della preparazione (le distribuzioni a priori e la verosimiglianza) e in <code>generated quantities</code> prepariamo i contorni (diagnostiche, predizioni) che non cambiano la ricetta principale, ma la rendono più completa.</p>
<p>Questa architettura modulare rende Stan intuitivo e adattabile a un’ampia gamma di applicazioni statistiche.</p>
<section id="lavorare-con-stan-in-r" class="level3" data-number="13.1.1"><h3 data-number="13.1.1" class="anchored" data-anchor-id="lavorare-con-stan-in-r">
<span class="header-section-number">13.1.1</span> Lavorare con Stan in R</h3>
<p>L’interfaccia <code>cmdstanr</code> per R segue un workflow ben definito:</p>
<ol type="1">
<li>scrittura del modello in un file <code>.stan</code>,<br>
</li>
<li>compilazione del modello,<br>
</li>
<li>passaggio dei dati come lista R,</li>
<li>esecuzione del campionamento con <code><a href="https://rdrr.io/r/base/sample.html">sample()</a></code>,<br>
</li>
<li>analisi dei risultati mediante pacchetti specializzati (<code>posterior</code>, <code>bayesplot</code>).</li>
</ol>
<p>In pratica, lavorare con Stan da R segue sempre lo stesso schema. Prima si scrive il modello in un file <code>.stan</code>; poi lo si compila, cioè lo si traduce in un eseguibile; quindi si preparano i dati in una lista R con gli stessi nomi dichiarati nel modello; infine si lancia il campionamento con la funzione <code><a href="https://rdrr.io/r/base/sample.html">sample()</a></code>. Una volta ottenuti i campioni a posteriori, possiamo analizzarli con pacchetti come <code>posterior</code> o <code>bayesplot</code>, che facilitano sia i riassunti numerici sia le visualizzazioni.</p>
<p>Stan utilizza un sistema di tipizzazione statica: tutte le variabili devono essere dichiarate con tipi specifici (<code>int</code> per interi, <code>real</code> per valori reali, <code>vector</code> per vettori) e possono includere vincoli (es. <code>lower=0</code> per valori positivi). Questo approccio aumenta la robustezza del codice e previene errori comuni nella specificazione dei modelli.</p>
</section></section><section id="modello-betabinomiale" class="level2" data-number="13.2"><h2 data-number="13.2" class="anchored" data-anchor-id="modello-betabinomiale">
<span class="header-section-number">13.2</span> Modello Beta–Binomiale</h2>
<p>Come primo esempio costruiamo un modello molto semplice, ma già sufficiente per illustrare i principi fondamentali della programmazione in Stan. L’obiettivo è stimare la probabilità di successo <span class="math inline">\(\theta\)</span> in una sequenza di prove Bernoulliane indipendenti.</p>
<p>Per rendere l’idea concreta, immaginiamo di lanciare un dado mille volte e di registrare il risultato come variabile dicotomica: assegniamo il valore <code>1</code> se esce il numero 6 (considerato “successo”), e <code>0</code> in tutti gli altri casi (“fallimento”). Se il dado fosse perfettamente equilibrato, la probabilità di successo sarebbe <span class="math inline">\(\theta = 1/6 \approx 0.167\)</span>. Tuttavia, nell’approccio bayesiano non assumiamo a priori che il dado sia equo: lasciamo che siano i dati, in combinazione con una distribuzione <em>a priori</em> esplicita, a informare il valore di <span class="math inline">\(\theta\)</span>.</p>
<p>Ecco un esempio di generazione dei dati in R:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">1000</span></span>
<span><span class="va">dice_df</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>res <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">6</span>, size <span class="op">=</span> <span class="va">n</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/integer.html">as.integer</a></span><span class="op">(</span><span class="va">dice_df</span><span class="op">$</span><span class="va">res</span> <span class="op">==</span> <span class="fl">6</span><span class="op">)</span>    <span class="co"># 1 se esce “6”, 0 altrimenti</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span>                              <span class="co"># frequenza relativa di “6”</span></span>
<span><span class="co">#&gt; [1] 0.164</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Il modello statistico che proponiamo per rappresentare questa situazione è molto semplice:</p>
<ul>
<li>ogni osservazione segue una distribuzione Bernoulliana, <span class="math inline">\(y_i \sim \text{Bernoulli}(\theta)\)</span> per <span class="math inline">\(i = 1, \dots, N\)</span>;</li>
<li>ciò è equivalente a dire che il numero totale di successi <span class="math inline">\(k = \sum_i y_i\)</span> segue una distribuzione Binomiale, <span class="math inline">\(k \sim \text{Binomiale}(N,\theta)\)</span>;</li>
<li>come prior adottiamo una distribuzione uniforme su <span class="math inline">\([0,1]\)</span>, cioè <span class="math inline">\(\theta \sim \text{Beta}(1,1)\)</span><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</li>
</ul>
<section id="prima-versione-modello-bernoulliano-vettoriale" class="level3" data-number="13.2.1"><h3 data-number="13.2.1" class="anchored" data-anchor-id="prima-versione-modello-bernoulliano-vettoriale">
<span class="header-section-number">13.2.1</span> Prima versione: modello Bernoulliano vettoriale</h3>
<p>Il modo più diretto di tradurre il modello in Stan è scrivere la verosimiglianza come sequenza di esiti Bernoulliani. Questo approccio ha anche un valore didattico, perché mostra chiaramente la corrispondenza tra i dati osservati e il modello probabilistico. Stan, inoltre, vettorializza automaticamente le operazioni sugli array, rendendo il codice conciso:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stancode</span> <span class="op">&lt;-</span> <span class="st">"</span></span>
<span><span class="st">data {</span></span>
<span><span class="st">  int&lt;lower=1&gt; N;                    // numero di prove</span></span>
<span><span class="st">  array[N] int&lt;lower=0, upper=1&gt; y;  // esiti (0/1)</span></span>
<span><span class="st">}</span></span>
<span><span class="st">parameters {</span></span>
<span><span class="st">  real&lt;lower=0, upper=1&gt; theta;      // probabilità di successo</span></span>
<span><span class="st">}</span></span>
<span><span class="st">model {</span></span>
<span><span class="st">  theta ~ beta(1, 1);                // prior uniforme su [0,1]</span></span>
<span><span class="st">  y ~ bernoulli(theta);              // verosimiglianza</span></span>
<span><span class="st">}</span></span>
<span><span class="st">"</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Nel blocco <code>data</code> dichiariamo le variabili osservate (<code>N</code> e il vettore binario <code>y</code>); nel blocco <code>parameters</code> indichiamo il parametro da stimare, <span class="math inline">\(\theta\)</span>; infine, nel blocco <code>model</code> specifichiamo sia la distribuzione a priori sia la verosimiglianza.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<section id="perché-array-e-non-vector" class="level4" data-number="13.2.1.1"><h4 data-number="13.2.1.1" class="anchored" data-anchor-id="perché-array-e-non-vector">
<span class="header-section-number">13.2.1.1</span> Perché <code>array</code> e non <code>vector</code>?</h4>
<ul>
<li>In Stan, <em><code>vector</code> è usato solo per numeri reali</em> (variabili continue a virgola mobile).</li>
<li>Nel nostro caso gli esiti <span class="math inline">\(y\_i\)</span> sono <em>variabili discrete</em> che assumono solo i valori 0 o 1. Per questo dobbiamo dichiararli come <em>interi (<code>int</code>)</em>, e la struttura che raccoglie più interi in Stan è un <em><code>array</code> di interi</em>.</li>
<li>La sintassi <code>array[N] int y;</code> significa quindi “crea un array di lunghezza N, i cui elementi sono interi”.</li>
<li>Non potremmo scrivere <code>vector[N] y;</code> perché un <code>vector</code> in Stan può contenere solo <code>real</code>, e non accetterebbe valori binari discreti come <code>0</code> o <code>1</code>.</li>
</ul>
<p>In altre parole, usiamo <code>array</code> ogni volta che i dati osservati sono <em>categorici o interi</em> (conteggi, esiti Bernoulli, ecc.), mentre <code>vector</code> è riservato a quantità <em>continue</em> come parametri, covariate normalizzate o variabili latenti.</p>
</section></section><section id="seconda-versione-modello-binomiale-sui-successi-totali" class="level3" data-number="13.2.2"><h3 data-number="13.2.2" class="anchored" data-anchor-id="seconda-versione-modello-binomiale-sui-successi-totali">
<span class="header-section-number">13.2.2</span> Seconda versione: modello binomiale sui successi totali</h3>
<p>L’approccio Bernoulliano visto in precedenza ha il pregio della chiarezza, ma può risultare ridondante: stiamo in realtà scrivendo la stessa formula mille volte, una per ciascun lancio del dado. In termini statistici, però, sappiamo che non è necessario conservare l’intera sequenza di zeri e uno: ai fini della stima di <span class="math inline">\(\theta\)</span> conta solo il numero totale di successi osservati. Questa proprietà prende il nome di <em>sufficienza</em> della statistica <span class="math inline">\(k = \sum_i y_i\)</span> per la distribuzione binomiale.</p>
<p>Se dunque nei mille lanci abbiamo osservato, ad esempio, 164 “6”, tutta l’informazione rilevante per stimare <span class="math inline">\(\theta\)</span> è contenuta in quel singolo numero, non nella sequenza dettagliata dei lanci. La distribuzione binomiale ci permette di formalizzare questa idea in modo compatto, portando a una specificazione del modello più efficiente, ma del tutto equivalente sul piano inferenziale.</p>
<p>Ecco la traduzione in Stan:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stancode</span> <span class="op">&lt;-</span> <span class="st">"</span></span>
<span><span class="st">data {</span></span>
<span><span class="st">  int&lt;lower=1&gt; N;                      // numero di prove</span></span>
<span><span class="st">  array[N] int&lt;lower=0, upper=1&gt; y;    // sequenza di esiti (usata solo per calcolare k)</span></span>
<span><span class="st">}</span></span>
<span><span class="st">transformed data {</span></span>
<span><span class="st">  int&lt;lower=0, upper=N&gt; k = sum(y);    // numero totale di successi</span></span>
<span><span class="st">}</span></span>
<span><span class="st">parameters {</span></span>
<span><span class="st">  real&lt;lower=0, upper=1&gt; theta;        // probabilità di successo</span></span>
<span><span class="st">}</span></span>
<span><span class="st">model {</span></span>
<span><span class="st">  theta ~ beta(1, 1);                  // prior uniforme</span></span>
<span><span class="st">  k ~ binomial(N, theta);              // verosimiglianza sui successi totali</span></span>
<span><span class="st">}</span></span>
<span><span class="st">"</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Questa versione concentra la verosimiglianza in un’unica riga, calcolata direttamente sul numero complessivo di successi. Le catene MCMC che otteniamo da questo modello coincidono, entro il rumore Monte Carlo, con quelle prodotte dalla versione Bernoulliana, ma richiedono meno operazioni e risultano quindi più efficienti dal punto di vista computazionale.</p>
<p>Come per la prima versione, possiamo arricchire il modello con un blocco <code>generated quantities</code> per ottenere log-likelihood o repliche predittive. Queste quantità derivate non modificano l’inferenza su <span class="math inline">\(\theta\)</span>, ma ci consentono di eseguire controlli diagnostici, confrontare modelli alternativi o visualizzare come il modello riproduce i dati osservati.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Perché “Beta–Binomiale”?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Ricordiamo che, con prior <span class="math inline">\(\theta \sim \text{Beta}(a,b)\)</span> e <span class="math inline">\(k \sim \text{Binomiale}(N,\theta)\)</span>, la posterior è</p>
<p><span class="math display">\[
\theta \mid y \sim \text{Beta}\big(a+k,\; b+N-k\big),
\]</span> con <span class="math inline">\(a=b=1\)</span>: <span class="math inline">\(\text{Beta}(1+k,\; 1+N-k)\)</span>.</p>
<p>Questo ci consente un <em>controllo didattico</em>: possiamo confrontare media e IC ottenuti da Stan con quelli della Beta a posteriori.</p>
<p>Esempio in R:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">k</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span></span>
<span><span class="va">a</span> <span class="op">&lt;-</span> <span class="fl">1</span></span>
<span><span class="va">b</span> <span class="op">&lt;-</span> <span class="fl">1</span></span>
<span><span class="va">post_mean_closed</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">a</span> <span class="op">+</span> <span class="va">k</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="va">a</span> <span class="op">+</span> <span class="va">b</span> <span class="op">+</span> <span class="va">n</span><span class="op">)</span></span>
<span><span class="va">post_ci95_closed</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Beta.html">qbeta</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">0.975</span><span class="op">)</span>, <span class="va">a</span> <span class="op">+</span> <span class="va">k</span>, <span class="va">b</span> <span class="op">+</span> <span class="va">n</span> <span class="op">-</span> <span class="va">k</span><span class="op">)</span></span>
<span><span class="va">post_mean_closed</span>; </span>
<span><span class="co">#&gt; [1] 0.165</span></span>
<span><span class="va">post_ci95_closed</span></span>
<span><span class="co">#&gt; [1] 0.142 0.188</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Le stime via Stan (campioni MCMC della <code>theta</code>) devono coincidere (entro il rumore Monte Carlo) con queste quantità analitiche.</p>
</div>
</div>
</div>
<p>Una volta scritto il modello, il passo successivo è la <em>compilazione</em>. Stan traduce il codice in linguaggio C++ e lo trasforma in un piccolo eseguibile che potrà essere richiamato ogni volta che lanceremo le stime. Questo passaggio richiede qualche secondo solo la prima volta; in seguito, il modello compilato può essere riutilizzato con dataset diversi senza dover ricompilare da capo, con un notevole risparmio di tempo.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mod</span> <span class="op">&lt;-</span> <span class="fu">cmdstan_model</span><span class="op">(</span></span>
<span>  <span class="fu">write_stan_file</span><span class="op">(</span><span class="va">stancode</span><span class="op">)</span>,</span>
<span>  compile <span class="op">=</span> <span class="cn">TRUE</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Preparato l’eseguibile, dobbiamo passare a Stan i dati necessari. In questo caso servono due elementi: il numero totale di prove e il vettore con gli esiti dei lanci. È importante che i nomi e i tipi corrispondano esattamente a quanto dichiarato nel blocco <code>data</code> del modello Stan, altrimenti il programma restituirà un errore.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stan_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>  N <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span>,</span>
<span>  y <span class="op">=</span> <span class="va">y</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">stan_data</span><span class="op">)</span></span>
<span><span class="co">#&gt; List of 2</span></span>
<span><span class="co">#&gt;  $ N: int 1000</span></span>
<span><span class="co">#&gt;  $ y: int [1:1000] 0 1 0 0 0 1 0 0 0 1 ...</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>A questo punto siamo pronti per il <em>campionamento MCMC</em>. Nella chiamata a <code><a href="https://rdrr.io/r/base/sample.html">sample()</a></code> specifichiamo quante iterazioni dedicare alla fase di warmup (che serve per adattare l’algoritmo), quante iterazioni utilizzare effettivamente per l’inferenza, e quante catene indipendenti far partire in parallelo.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit1</span> <span class="op">&lt;-</span> <span class="va">mod</span><span class="op">$</span><span class="fu">sample</span><span class="op">(</span></span>
<span>  data <span class="op">=</span> <span class="va">stan_data</span>,</span>
<span>  iter_warmup <span class="op">=</span> <span class="fl">1000</span>,</span>
<span>  iter_sampling <span class="op">=</span> <span class="fl">2000</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  parallel_chains <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  seed <span class="op">=</span> <span class="fl">4790</span>,</span>
<span>  refresh <span class="op">=</span> <span class="fl">0</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt; Running MCMC with 4 parallel chains...</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Chain 1 finished in 0.0 seconds.</span></span>
<span><span class="co">#&gt; Chain 2 finished in 0.0 seconds.</span></span>
<span><span class="co">#&gt; Chain 3 finished in 0.0 seconds.</span></span>
<span><span class="co">#&gt; Chain 4 finished in 0.0 seconds.</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; All 4 chains finished successfully.</span></span>
<span><span class="co">#&gt; Mean chain execution time: 0.0 seconds.</span></span>
<span><span class="co">#&gt; Total execution time: 0.2 seconds.</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Con il modello stimato, possiamo generare un <em>riepilogo sintetico</em> delle stime a posteriori. La funzione <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> di Stan mostra media, deviazione standard, quantili e diagnostiche come <span class="math inline">\(\hat R\)</span> ed ESS.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit1</span><span class="op">$</span><span class="fu">summary</span><span class="op">(</span>variables <span class="op">=</span> <span class="st">"theta"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 10</span></span>
<span><span class="co">#&gt;   variable  mean median    sd   mad    q5   q95  rhat ess_bulk ess_tail</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 theta    0.164  0.164 0.012 0.012 0.145 0.184 1.000 2443.381 3636.368</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In alternativa, il pacchetto <em>posterior</em> permette di estrarre i campioni e calcolare con maggiore flessibilità le statistiche che ci interessano:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">draws</span> <span class="op">&lt;-</span> <span class="va">fit1</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span>variables <span class="op">=</span> <span class="st">"theta"</span>, format <span class="op">=</span> <span class="st">"draws_matrix"</span><span class="op">)</span></span>
<span><span class="fu">posterior</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/posterior/reference/draws_summary.html">summarise_draws</a></span><span class="op">(</span></span>
<span>  <span class="va">draws</span>,</span>
<span>  <span class="va">mean</span>, <span class="va">sd</span>, <span class="op">~</span><span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">.x</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span><span class="op">)</span><span class="op">)</span>, <span class="va">rhat</span>, <span class="va">ess_bulk</span>, <span class="va">ess_tail</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 9</span></span>
<span><span class="co">#&gt;   variable  mean    sd `2.5%` `50%` `97.5%`  rhat ess_bulk ess_tail</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 theta    0.164 0.012  0.142 0.164   0.188 1.000 2443.381 3636.368</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Come regola generale, valori di <span class="math inline">\(\hat R\)</span> molto vicini a 1 (idealmente &lt; 1.01) e un numero elevato di campioni effettivi (ESS) indicano che le catene hanno esplorato bene la distribuzione a posteriori.</p>
<p>Oltre alle statistiche numeriche, le <em>diagnostiche grafiche</em> aiutano a valutare a colpo d’occhio la qualità del campionamento.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">bayesplot</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/bayesplot/reference/MCMC-traces.html">mcmc_trace</a></span><span class="op">(</span><span class="va">fit1</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span><span class="st">"theta"</span><span class="op">)</span>, n_warmup <span class="op">=</span> <span class="fl">1000</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="03_stan_intro_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<p>Nel traceplot, le catene dovrebbero mescolarsi bene senza mostrare trend persistenti; nel grafico delle densità, le distribuzioni delle diverse catene dovrebbero risultare sovrapposte.</p>
<p>In sintesi: la media a posteriori di <span class="math inline">\(\theta\)</span> fornisce una stima puntuale della probabilità di ottenere un “6”, l’intervallo di credibilità quantifica l’incertezza residua, e le diagnostiche (R-hat vicino a 1, ESS alto, catene ben mescolate) garantiscono che i campioni siano affidabili per trarre conclusioni.</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Confronto con la frequenza relativa</strong></p>
<p>La frequenza <code>mean(y)</code> è <em>solo una stima puntuale</em>. L’analisi bayesiana restituisce <em>un’intera distribuzione</em> per <span class="math inline">\(\theta\)</span>, utile per <em>propagare l’incertezza</em> in previsioni e decisioni.</p>
</div>
</div>
</div>
</section><section id="distribuzione-predittiva-posteriore" class="level3" data-number="13.2.3"><h3 data-number="13.2.3" class="anchored" data-anchor-id="distribuzione-predittiva-posteriore">
<span class="header-section-number">13.2.3</span> Distribuzione predittiva posteriore</h3>
<p>Stimare <span class="math inline">\(\theta\)</span> non è sufficiente: ciò che spesso ci interessa davvero è capire quali <em>conseguenze pratiche</em> derivano dai risultati. In altre parole, vogliamo sapere cosa il modello predice su <em>dati futuri</em>. Ad esempio: se rilanciassimo il dado altre 1000 volte, quanti “6” potremmo attenderci?</p>
<p>La risposta si ottiene tramite la <em>distribuzione predittiva posteriore</em>. Condizionatamente a un valore fissato di <span class="math inline">\(\theta\)</span>, il numero di successi nei nuovi lanci segue una distribuzione binomiale:</p>
<p><span class="math display">\[
y_{\text{rep}} \mid \theta \sim \text{Binomiale}(n_{\text{new}}, \theta).
\]</span></p>
<p>Poiché non conosciamo <span class="math inline">\(\theta\)</span> con certezza, ma solo la sua distribuzione a posteriori, la distribuzione predittiva si ottiene integrando la probabilità condizionata <span class="math inline">\(p(y\_{\text{rep}} \mid \theta)\)</span> rispetto a <span class="math inline">\(p(\theta \mid y)\)</span>:</p>
<p><span class="math display">\[
p(y_{\text{rep}} \mid y) \;=\; \int p(y_{\text{rep}} \mid \theta)\, p(\theta \mid y)\, d\theta.
\]</span></p>
<section id="procedura-operativa" class="level4" data-number="13.2.3.1"><h4 data-number="13.2.3.1" class="anchored" data-anchor-id="procedura-operativa">
<span class="header-section-number">13.2.3.1</span> Procedura operativa</h4>
<p>Il procedimento pratico è semplice e si articola in due passaggi:</p>
<ol type="1">
<li><p><strong>Estrarre un valore da <span class="math inline">\(p(\theta \mid y)\)</span></strong>. Supponiamo di ottenere <span class="math inline">\(\theta = 0.15\)</span>.</p></li>
<li>
<p><strong>Simulare un dato replicato</strong>. Con quel valore generiamo un nuovo conteggio <span class="math inline">\(y\_{\text{rep}}\)</span> da una binomiale, ad esempio con <span class="math inline">\(n\_{\text{new}}=1000\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">1</span>, size <span class="op">=</span> <span class="fl">1000</span>, prob <span class="op">=</span> <span class="fl">0.15</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 160</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</li>
</ol>
<p>Ripetendo il processo per molti valori di <span class="math inline">\(\theta\)</span> estratti dalla distribuzione a posteriori, otteniamo un campione dalla distribuzione predittiva posteriore.</p>
</section><section id="codice-r" class="level4" data-number="13.2.3.2"><h4 data-number="13.2.3.2" class="anchored" data-anchor-id="codice-r">
<span class="header-section-number">13.2.3.2</span> Codice R</h4>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Numero di futuri lanci</span></span>
<span><span class="va">n_new</span> <span class="op">&lt;-</span> <span class="fl">1000</span></span>
<span></span>
<span><span class="co"># Campioni da p(theta | y)</span></span>
<span><span class="va">posterior_theta</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">fit1</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span><span class="st">"theta"</span>, format <span class="op">=</span> <span class="st">"matrix"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">posterior_theta</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">20</span><span class="op">]</span></span>
<span><span class="co">#&gt;  [1] 0.154 0.154 0.154 0.163 0.163 0.181 0.179 0.159 0.168 0.177 0.177 0.172</span></span>
<span><span class="co">#&gt; [13] 0.157 0.170 0.171 0.174 0.196 0.181 0.157 0.159</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Simulazione della distribuzione predittiva</span></span>
<span><span class="va">yrep_count</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span></span>
<span>  n    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">posterior_theta</span><span class="op">)</span>, </span>
<span>  size <span class="op">=</span> <span class="va">n_new</span>, </span>
<span>  prob <span class="op">=</span> <span class="va">posterior_theta</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Dimensioni e prime osservazioni</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">yrep_count</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 8000</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">yrep_count</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 161 172 153 161 172 193</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Riassunti predittivi</span></span>
<span><span class="va">mean_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">yrep_count</span><span class="op">)</span>  </span>
<span><span class="va">ci_pred</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">yrep_count</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">mean_pred</span></span>
<span><span class="co">#&gt; [1] 165</span></span>
<span><span class="va">ci_pred</span></span>
<span><span class="co">#&gt;  2.5%   50% 97.5% </span></span>
<span><span class="co">#&gt;   134   164   197</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="visualizzazione" class="level4" data-number="13.2.3.3"><h4 data-number="13.2.3.3" class="anchored" data-anchor-id="visualizzazione">
<span class="header-section-number">13.2.3.3</span> Visualizzazione</h4>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">p025</span> <span class="op">&lt;-</span> <span class="va">ci_pred</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>; <span class="va">p50</span> <span class="op">&lt;-</span> <span class="va">ci_pred</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>; <span class="va">p975</span> <span class="op">&lt;-</span> <span class="va">ci_pred</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span></span>
<span></span>
<span><span class="fu">tibble</span><span class="op">(</span>count <span class="op">=</span> <span class="va">yrep_count</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">count</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">30</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">mean_pred</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">p025</span>, <span class="va">p975</span><span class="op">)</span>, linetype <span class="op">=</span> <span class="st">"dotted"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="st">"Numero di successi su n_new prove"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Frequenza"</span>,</span>
<span>    title <span class="op">=</span> <span class="st">"Distribuzione predittiva posteriore"</span>,</span>
<span>    subtitle <span class="op">=</span> <span class="st">"Linea tratteggiata = media predittiva; puntinate = intervallo al 95%"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="03_stan_intro_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
</section><section id="interpretazione" class="level4" data-number="13.2.3.4"><h4 data-number="13.2.3.4" class="anchored" data-anchor-id="interpretazione">
<span class="header-section-number">13.2.3.4</span> Interpretazione</h4>
<p>L’istogramma mostra la variabilità attesa del numero di “6” su mille lanci futuri. La distribuzione è centrata intorno al valore atteso <span class="math inline">\(n\_{\text{new}} \cdot \mathbb{E}[\theta \mid y]\)</span>, cioè il numero medio di successi secondo la stima a posteriori.</p>
<p>Se il dado fosse perfettamente equo (<span class="math inline">\(\theta = 1/6\)</span>), ci aspetteremmo circa 167 successi su 1000, con un intervallo predittivo attorno a 133–198. Un forte scostamento da questo scenario indicherebbe che il modello suggerisce un dado non equilibrato.</p>
</section></section></section><section id="dati-continui-stima-della-media-con-varianza-nota" class="level2" data-number="13.3"><h2 data-number="13.3" class="anchored" data-anchor-id="dati-continui-stima-della-media-con-varianza-nota">
<span class="header-section-number">13.3</span> Dati continui: stima della media con varianza nota</h2>
<p>Un problema molto comune nelle scienze psicologiche è la stima della <em>media di popolazione</em> di una variabile continua. Pensiamo, ad esempio, ai punteggi ottenuti a un test di intelligenza (QI). Per semplificare l’esposizione assumiamo che la deviazione standard della popolazione sia nota e pari a <span class="math inline">\(\sigma = 15\)</span>. Nella pratica questa informazione non è quasi mai disponibile, ma l’ipotesi ci permette di concentrare l’attenzione su un unico parametro incognito: la media <span class="math inline">\(\mu\)</span>. Ciò rende il modello più semplice e facilita il confronto tra l’impostazione classica e quella bayesiana.</p>
<p>Immaginiamo quindi di raccogliere i punteggi di <span class="math inline">\(n = 30\)</span> persone, ipotizzando che la vera media sia 105:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span><span class="va">n</span>     <span class="op">&lt;-</span> <span class="fl">30</span></span>
<span><span class="va">sigma</span> <span class="op">&lt;-</span> <span class="fl">15</span></span>
<span><span class="va">y_cont</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span>, mean <span class="op">=</span> <span class="fl">105</span>, sd <span class="op">=</span> <span class="va">sigma</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">tibble</span><span class="op">(</span>y <span class="op">=</span> <span class="va">y_cont</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">y</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_histogram</span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">15</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Punteggio"</span>, y <span class="op">=</span> <span class="st">"Frequenza"</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="03_stan_intro_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<p>Il modello statistico che adottiamo ha due componenti fondamentali. La <em>verosimiglianza</em> descrive come si generano i dati: ogni osservazione <span class="math inline">\(y_i\)</span> è distribuita secondo una Normale con media incognita <span class="math inline">\(\mu\)</span> e deviazione standard nota <span class="math inline">\(\sigma\)</span>:</p>
<p><span class="math display">\[
y_i \sim \mathcal{N}(\mu, \sigma).
\]</span></p>
<p>A questo si affianca il <em>prior</em> su <span class="math inline">\(\mu\)</span>, che formalizza le conoscenze disponibili prima di raccogliere i dati. Supponiamo che <span class="math inline">\(\mu\)</span> sia distribuita normalmente attorno a <span class="math inline">\(\mu_0 = 100\)</span>, con deviazione standard <span class="math inline">\(\tau = 30\)</span>. Un prior così ampio riflette un’incertezza iniziale elevata, lasciando spazio ai dati per aggiornare in modo sostanziale le nostre convinzioni:</p>
<p><span class="math display">\[
\mu \sim \mathcal{N}(\mu_0, \tau).
\]</span></p>
<p>Il modello combina dunque le informazioni fornite dai dati con quelle incorporate nel prior, producendo una distribuzione a posteriori per <span class="math inline">\(\mu\)</span> che sintetizza entrambe le fonti di conoscenza.</p>
<p>La traduzione in Stan è la seguente:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stancode_norm</span> <span class="op">&lt;-</span> <span class="st">"</span></span>
<span><span class="st">data {</span></span>
<span><span class="st">  int&lt;lower=1&gt; N;</span></span>
<span><span class="st">  vector[N] y;             // dati osservati</span></span>
<span><span class="st">  real&lt;lower=0&gt; sigma;     // deviazione standard nota</span></span>
<span><span class="st">  real mu0;                // media del prior su mu</span></span>
<span><span class="st">  real&lt;lower=0&gt; tau;       // sd del prior su mu</span></span>
<span><span class="st">}</span></span>
<span><span class="st">parameters {</span></span>
<span><span class="st">  real mu;                 // media: parametro da stimare</span></span>
<span><span class="st">}</span></span>
<span><span class="st">model {</span></span>
<span><span class="st">  mu ~ normal(mu0, tau);   // prior su mu</span></span>
<span><span class="st">  y  ~ normal(mu, sigma);  // verosimiglianza</span></span>
<span><span class="st">}</span></span>
<span><span class="st">"</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>I dati devono essere preparati in R in un oggetto coerente con quanto richiesto dal blocco <code>data</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stan_data2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>  N     <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">y_cont</span><span class="op">)</span>,</span>
<span>  y     <span class="op">=</span> <span class="va">y_cont</span>,</span>
<span>  sigma <span class="op">=</span> <span class="va">sigma</span>,</span>
<span>  mu0   <span class="op">=</span> <span class="fl">100</span>,</span>
<span>  tau   <span class="op">=</span> <span class="fl">30</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Dopo aver compilato il modello, si può avviare il campionamento MCMC:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mod2</span> <span class="op">&lt;-</span> <span class="fu">cmdstanr</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/cmdstanr/reference/cmdstan_model.html">cmdstan_model</a></span><span class="op">(</span><span class="fu">write_stan_file</span><span class="op">(</span><span class="va">stancode_norm</span><span class="op">)</span>, compile <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit2</span> <span class="op">&lt;-</span> <span class="va">mod2</span><span class="op">$</span><span class="fu">sample</span><span class="op">(</span></span>
<span>  data <span class="op">=</span> <span class="va">stan_data2</span>,</span>
<span>  iter_warmup     <span class="op">=</span> <span class="fl">1000</span>,</span>
<span>  iter_sampling   <span class="op">=</span> <span class="fl">4000</span>,</span>
<span>  chains          <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  parallel_chains <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  seed            <span class="op">=</span> <span class="fl">4790</span>,</span>
<span>  refresh         <span class="op">=</span> <span class="fl">0</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>I risultati possono essere riassunti in forma compatta:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">fit2</span><span class="op">$</span><span class="fu">summary</span><span class="op">(</span>variables <span class="op">=</span> <span class="st">"mu"</span><span class="op">)</span>, n <span class="op">=</span> <span class="cn">Inf</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 10</span></span>
<span><span class="co">#&gt;   variable    mean  median    sd   mad     q5     q95  rhat ess_bulk ess_tail</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 mu       104.240 104.236 2.721 2.740 99.751 108.710 1.001 5499.842 7540.041</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>oppure, con il pacchetto <code>posterior</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">draws2</span> <span class="op">&lt;-</span> <span class="va">fit2</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span>variables <span class="op">=</span> <span class="st">"mu"</span>, format <span class="op">=</span> <span class="st">"draws_matrix"</span><span class="op">)</span></span>
<span><span class="fu">posterior</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/posterior/reference/draws_summary.html">summarise_draws</a></span><span class="op">(</span></span>
<span>  <span class="va">draws2</span>, <span class="va">mean</span>, <span class="va">sd</span>, <span class="op">~</span><span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">.x</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span><span class="op">)</span><span class="op">)</span>, <span class="va">rhat</span>, <span class="va">ess_bulk</span>, <span class="va">ess_tail</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 9</span></span>
<span><span class="co">#&gt;   variable    mean    sd `2.5%`   `50%` `97.5%`  rhat ess_bulk ess_tail</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 mu       104.240 2.721 98.916 104.236 109.627 1.001 5499.842 7540.041</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>L’interpretazione è diretta. Valori di <span class="math inline">\(\hat R\)</span> vicini a 1 e un <em>effective sample size</em> elevato indicano che le catene sono ben miscelate e le stime affidabili. La <em>media a posteriori</em> di <span class="math inline">\(\mu\)</span> rappresenta la miglior stima puntuale della media di popolazione. L’<em>intervallo di credibilità</em> quantifica l’incertezza residua: nel nostro caso esso risulta piuttosto ampio, e ciò riflette la limitata numerosità campionaria (<span class="math inline">\(n = 30\)</span>). Con un campione più grande l’intervallo si restringerebbe, perché disporremmo di maggiore informazione empirica.</p>
<p>In conclusione, l’analisi bayesiana non fornisce soltanto una stima centrale, ma restituisce l’intera distribuzione di plausibilità dei valori possibili per la media della popolazione, offrendo così un quadro completo dell’incertezza associata ai dati raccolti.</p>
<section id="controllo-analitico-della-coniugatezza" class="level3" data-number="13.3.1"><h3 data-number="13.3.1" class="anchored" data-anchor-id="controllo-analitico-della-coniugatezza">
<span class="header-section-number">13.3.1</span> Controllo analitico della coniugatezza</h3>
<p>Il modello che abbiamo specificato ha una proprietà molto comoda: la <em>coniugatezza</em>. Quando usiamo un prior normale per la media <span class="math inline">\(\mu\)</span> e assumiamo nota la varianza <span class="math inline">\(\sigma^2\)</span>, anche la distribuzione <em>a posteriori</em> di <span class="math inline">\(\mu\)</span> rimane normale. Questo ci permette di calcolare media e varianza della posterior in forma chiusa, senza bisogno di simulazioni MCMC. In particolare, la varianza e la media della distribuzione a posteriori si ottengono come:</p>
<p><span class="math display">\[
\text{Var}(\mu \mid y) \;=\; \left(\frac{n}{\sigma^2} + \frac{1}{\tau^2}\right)^{-1},
\quad
\mathbb{E}[\mu \mid y] \;=\; \text{Var}(\mu \mid y)\,\left(\frac{n\bar y}{\sigma^2} + \frac{\mu_0}{\tau^2}\right).
\]</span></p>
<p>Con i nostri dati possiamo calcolare questi valori direttamente:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ybar</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">y_cont</span><span class="op">)</span></span>
<span><span class="va">tau2</span>    <span class="op">&lt;-</span> <span class="fl">30</span><span class="op">^</span><span class="fl">2</span></span>
<span><span class="va">sigma2</span>  <span class="op">&lt;-</span> <span class="va">sigma</span><span class="op">^</span><span class="fl">2</span></span>
<span><span class="va">post_var</span>  <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">/</span> <span class="op">(</span><span class="va">n</span> <span class="op">/</span> <span class="va">sigma2</span> <span class="op">+</span> <span class="fl">1</span> <span class="op">/</span> <span class="va">tau2</span><span class="op">)</span></span>
<span><span class="va">post_sd</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">post_var</span><span class="op">)</span></span>
<span><span class="va">post_mean</span> <span class="op">&lt;-</span> <span class="va">post_var</span> <span class="op">*</span> <span class="op">(</span><span class="va">n</span> <span class="op">*</span> <span class="va">ybar</span> <span class="op">/</span> <span class="va">sigma2</span> <span class="op">+</span> <span class="fl">100</span> <span class="op">/</span> <span class="va">tau2</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>post_mean_closed <span class="op">=</span> <span class="va">post_mean</span>, post_sd_closed <span class="op">=</span> <span class="va">post_sd</span><span class="op">)</span></span>
<span><span class="co">#&gt; post_mean_closed   post_sd_closed </span></span>
<span><span class="co">#&gt;           104.26             2.73</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Ora possiamo confrontare questi risultati analitici con quanto ottenuto tramite campionamento MCMC:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mu_draws</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">draws2</span><span class="op">[</span>, <span class="st">"mu"</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>mean_mcmc <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mu_draws</span><span class="op">)</span>, sd_mcmc <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">mu_draws</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; mean_mcmc   sd_mcmc </span></span>
<span><span class="co">#&gt;    104.24      2.72</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Le due soluzioni dovrebbero concordare molto bene: la formula chiusa ci dà il risultato “esatto”, mentre l’MCMC lo approssima tramite simulazione. Le piccole discrepanze sono attribuibili al normale <em>rumore Monte Carlo</em>, che diminuisce all’aumentare del numero di campioni.</p>
</section><section id="visualizzazione-1" class="level3" data-number="13.3.2"><h3 data-number="13.3.2" class="anchored" data-anchor-id="visualizzazione-1">
<span class="header-section-number">13.3.2</span> Visualizzazione</h3>
<p>Una volta stimato il modello, è utile osservare graficamente i campioni MCMC per verificare sia la qualità del campionamento sia la forma della distribuzione a posteriori. Il pacchetto <code>bayesplot</code> fornisce strumenti immediati per questo scopo. Un primo passo è guardare l’<em>istogramma dei campioni</em>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">bayesplot</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/bayesplot/reference/MCMC-distributions.html">mcmc_hist</a></span><span class="op">(</span><span class="va">fit2</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span><span class="st">"mu"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="03_stan_intro_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<p>Questo grafico mostra la distribuzione stimata della media <span class="math inline">\(\mu\)</span>: non un singolo numero, ma un ventaglio di valori plausibili con le loro frequenze relative.</p>
<p>In sintesi, questo esempio rappresenta una sorta di <em>“test bayesiano della media”</em> con deviazione standard nota e un prior normale ampio su <span class="math inline">\(\mu\)</span>. A differenza dell’approccio frequentista, non otteniamo soltanto una stima puntuale o un intervallo, ma un’intera <em>distribuzione a posteriori</em> della media. Questo è un vantaggio importante: l’incertezza stimata può essere comunicata in modo trasparente e, soprattutto, può essere <em>propagata</em> nelle fasi successive dell’analisi, ad esempio in previsioni o decisioni basate sul modello.</p>
</section><section id="intervalli-di-credibilità" class="level3" data-number="13.3.3"><h3 data-number="13.3.3" class="anchored" data-anchor-id="intervalli-di-credibilità">
<span class="header-section-number">13.3.3</span> Intervalli di credibilità</h3>
<p>Nell’inferenza bayesiana non otteniamo un singolo numero come stima del parametro, ma un’intera <em>distribuzione a posteriori</em> che descrive l’incertezza residua. Per riassumere questa distribuzione in modo interpretabile si ricorre agli <em>intervalli di credibilità</em>, che indicano con quale probabilità il parametro cade in un certo intervallo dato il modello e i dati osservati. Dire che l’intervallo di credibilità al 94% per <span class="math inline">\(\mu\)</span> va, ad esempio, da 101 a 110 significa che, condizionatamente alle assunzioni del modello e ai dati raccolti, c’è una probabilità del 94% che la media si trovi in quell’intervallo. Questa interpretazione è immediata e naturale, molto diversa da quella degli intervalli di confidenza frequentisti, che si riferiscono invece alla frequenza di copertura in ipotetiche ripetizioni del campione.</p>
<p>Gli intervalli di credibilità possono essere definiti in modi diversi. L’<em>Equal-Tailed Interval (ETI)</em> corrisponde all’intervallo che lascia la stessa probabilità nelle due code della distribuzione: ad esempio, in un intervallo al 94%, il 3% delle probabilità rimane sotto il limite inferiore e il 3% sopra quello superiore. Questo intervallo ha il pregio di essere stabile rispetto a trasformazioni monotone del parametro, ma può risultare inefficiente se la distribuzione è fortemente asimmetrica, perché finisce per includere regioni a bassa densità. L’<em>Highest Density Interval (HDI)</em>, invece, è definito come l’intervallo più corto che contiene la probabilità prefissata. L’HDI si adatta meglio a distribuzioni asimmetriche, perché si concentra nelle zone di maggiore densità, ma ha lo svantaggio di non essere invariante a trasformazioni monotone e, in distribuzioni multimodali, può addirittura frammentarsi in più sotto-intervalli. Nei casi più semplici, quando la distribuzione a posteriori è simmetrica e unimodale, come per una Normale, ETI e HDI coincidono.</p>
<section id="esempio-pratico-con-i-campioni-di-mu" class="level4" data-number="13.3.3.1"><h4 data-number="13.3.3.1" class="anchored" data-anchor-id="esempio-pratico-con-i-campioni-di-mu">
<span class="header-section-number">13.3.3.1</span> Esempio pratico con i campioni di <span class="math inline">\(\mu\)</span>
</h4>
<p>Per chiarire l’uso di questi strumenti possiamo considerare i campioni MCMC della media <span class="math inline">\(\mu\)</span> ottenuti dal modello normale con varianza nota. Calcolando sia l’ETI sia l’HDI al 94% si osserva che i due intervalli risultano praticamente identici, perché la distribuzione è simmetrica.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mu_draws</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">fit2</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span><span class="st">"mu"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Calcoliamo sia ETI che HDI al 94% con il pacchetto <code>bayestestR</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">eti94</span> <span class="op">&lt;-</span> <span class="fu">bayestestR</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/bayestestR/reference/eti.html">eti</a></span><span class="op">(</span><span class="va">mu_draws</span>, ci <span class="op">=</span> <span class="fl">0.94</span><span class="op">)</span></span>
<span><span class="va">hdi94</span> <span class="op">&lt;-</span> <span class="fu">bayestestR</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/bayestestR/reference/hdi.html">hdi</a></span><span class="op">(</span><span class="va">mu_draws</span>, ci <span class="op">=</span> <span class="fl">0.94</span><span class="op">)</span></span>
<span></span>
<span><span class="va">eti94</span></span>
<span><span class="co">#&gt; 94% ETI: [99.12, 109.43]</span></span>
<span><span class="va">hdi94</span></span>
<span><span class="co">#&gt; 94% HDI: [99.22, 109.48]</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="visualizzazione-2" class="level4" data-number="13.3.3.2"><h4 data-number="13.3.3.2" class="anchored" data-anchor-id="visualizzazione-2">
<span class="header-section-number">13.3.3.2</span> Visualizzazione</h4>
<p>Con <code><a href="https://mc-stan.org/bayesplot/reference/MCMC-intervals.html">bayesplot::mcmc_areas()</a></code> possiamo visualizzare gli intervalli centrali (ETI) e aggiungere i limiti HDI come linee verticali:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fu">bayesplot</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/bayesplot/reference/MCMC-intervals.html">mcmc_areas</a></span><span class="op">(</span><span class="va">fit2</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span><span class="st">"mu"</span><span class="op">)</span>, prob <span class="op">=</span> <span class="fl">0.94</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">xlab</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="va">mu</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu">ylab</span><span class="op">(</span><span class="st">"Densità"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">hdi94</span><span class="op">$</span><span class="va">CI_low</span>,  linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">hdi94</span><span class="op">$</span><span class="va">CI_high</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="03_stan_intro_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
</section><section id="posterior-asimmetrica-esempio-beta" class="level4" data-number="13.3.3.3"><h4 data-number="13.3.3.3" class="anchored" data-anchor-id="posterior-asimmetrica-esempio-beta">
<span class="header-section-number">13.3.3.3</span> Posterior asimmetrica: esempio Beta</h4>
<p>In distribuzioni asimmetriche, invece, le differenze emergono chiaramente. Un esempio utile è la distribuzione Beta(6,2), che mostra una coda a sinistra: in questo caso l’HDI risulta più corto e aderente alla parte densa della distribuzione, mentre l’ETI si estende ulteriormente verso la coda meno informativa.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span></span>
<span><span class="va">theta_draws</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Beta.html">rbeta</a></span><span class="op">(</span><span class="fl">5000</span>, shape1 <span class="op">=</span> <span class="fl">6</span>, shape2 <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="va">eti_beta</span> <span class="op">&lt;-</span> <span class="fu">bayestestR</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/bayestestR/reference/eti.html">eti</a></span><span class="op">(</span><span class="va">theta_draws</span>, ci <span class="op">=</span> <span class="fl">0.94</span><span class="op">)</span></span>
<span><span class="va">hdi_beta</span> <span class="op">&lt;-</span> <span class="fu">bayestestR</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/bayestestR/reference/hdi.html">hdi</a></span><span class="op">(</span><span class="va">theta_draws</span>, ci <span class="op">=</span> <span class="fl">0.94</span><span class="op">)</span></span>
<span></span>
<span><span class="va">eti_beta</span></span>
<span><span class="co">#&gt; 94% ETI: [0.43, 0.96]</span></span>
<span><span class="va">hdi_beta</span></span>
<span><span class="co">#&gt; 94% HDI: [0.49, 0.98]</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>theta <span class="op">=</span> <span class="va">theta_draws</span><span class="op">)</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">theta</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_density</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">eti_beta</span><span class="op">$</span><span class="va">CI_low</span>, <span class="va">eti_beta</span><span class="op">$</span><span class="va">CI_high</span><span class="op">)</span>, linewidth <span class="op">=</span> <span class="fl">0.7</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">hdi_beta</span><span class="op">$</span><span class="va">CI_low</span>, <span class="va">hdi_beta</span><span class="op">$</span><span class="va">CI_high</span><span class="op">)</span>, </span>
<span>             linewidth <span class="op">=</span> <span class="fl">1.2</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="va">theta</span><span class="op">)</span>, y <span class="op">=</span> <span class="st">"Densità"</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="03_stan_intro_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
</section><section id="quale-livello-utilizzare-89-94-o-95" class="level4" data-number="13.3.3.4"><h4 data-number="13.3.3.4" class="anchored" data-anchor-id="quale-livello-utilizzare-89-94-o-95">
<span class="header-section-number">13.3.3.4</span> Quale livello utilizzare? 89%, 94% o 95%?</h4>
<p>Rimane infine la questione di quale livello di probabilità utilizzare. La tradizione frequentista ha reso familiare il 95%, e molti analisti continuano a preferirlo per ragioni di continuità. Altri autori, come McElreath, suggeriscono il 94%, mentre Kruschke propone l’89% come scelta più stabile con campioni ridotti. In realtà non esiste una soglia “corretta” in senso assoluto: ciò che conta è la coerenza interna dell’analisi e la chiarezza nel riportare sia il livello scelto sia la definizione di intervallo adottata. In presenza di distribuzioni asimmetriche può essere particolarmente istruttivo mostrare sia l’ETI sia l’HDI, perché offrono prospettive complementari sulla distribuzione a posteriori del parametro.</p>
</section></section></section><section id="test-di-ipotesi-in-prospettiva-bayesiana" class="level2" data-number="13.4"><h2 data-number="13.4" class="anchored" data-anchor-id="test-di-ipotesi-in-prospettiva-bayesiana">
<span class="header-section-number">13.4</span> Test di ipotesi in prospettiva bayesiana</h2>
<p>L’approccio bayesiano consente di formulare domande in termini diretti e intuitivi, ad esempio:</p>
<blockquote class="blockquote">
<p><em>“Qual è la probabilità che la media superi una determinata soglia?”</em></p>
</blockquote>
<p>Questa impostazione si discosta da quella frequentista, che restituisce soltanto un esito dicotomico di rifiuto o non rifiuto dell’ipotesi nulla. In ambito bayesiano, al contrario, si ottiene una misura continua della plausibilità di ciascuna ipotesi, che rende l’incertezza più trasparente e consente di esprimere giudizi graduati.</p>
<section id="probabilità-a-posteriori-sopra-una-soglia" class="level3" data-number="13.4.1"><h3 data-number="13.4.1" class="anchored" data-anchor-id="probabilità-a-posteriori-sopra-una-soglia">
<span class="header-section-number">13.4.1</span> Probabilità a posteriori sopra una soglia</h3>
<p>Riprendiamo l’esempio dei punteggi QI con modello normale a varianza nota. Una prima domanda semplice è calcolare</p>
<p><span class="math display">\[
P(\mu &gt; 110 \mid y),
\]</span></p>
<p>cioè la probabilità che la media di popolazione superi il valore 110.</p>
<p>Questa quantità si ricava facilmente dai campioni MCMC della distribuzione a posteriori di <span class="math inline">\(\mu\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Estraiamo i campioni MCMC per mu</span></span>
<span><span class="va">mu_draws</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">fit2</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span><span class="st">"mu"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Calcoliamo la probabilità che mu superi la soglia 110</span></span>
<span><span class="va">p_gt_110</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mu_draws</span> <span class="op">&gt;</span> <span class="fl">110</span><span class="op">)</span></span>
<span><span class="va">p_gt_110</span></span>
<span><span class="co">#&gt; [1] 0.0193</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Il risultato rappresenta la probabilità, condizionatamente a modello e dati, che <span class="math inline">\(\mu\)</span> sia superiore a 110. Non si tratta dunque di un’affermazione sì/no, ma di una misura graduata della plausibilità.</p>
<p>Il valore può essere verificato anche in forma analitica, sfruttando la coniugatezza del modello normale-normale:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calcolo analitico con distribuzione normale coniugata</span></span>
<span><span class="va">p_gt_110_closed</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fl">110</span>, mean <span class="op">=</span> <span class="va">post_mean</span>, sd <span class="op">=</span> <span class="va">post_sd</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>MCMC <span class="op">=</span> <span class="va">p_gt_110</span>, ClosedForm <span class="op">=</span> <span class="va">p_gt_110_closed</span><span class="op">)</span></span>
<span><span class="co">#&gt;       MCMC ClosedForm </span></span>
<span><span class="co">#&gt;     0.0193     0.0176</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>I due risultati dovrebbero coincidere, salvo piccole discrepanze dovute al rumore Monte Carlo.</p>
</section><section id="decisione-pratica-e-rope" class="level3" data-number="13.4.2"><h3 data-number="13.4.2" class="anchored" data-anchor-id="decisione-pratica-e-rope">
<span class="header-section-number">13.4.2</span> Decisione pratica e ROPE</h3>
<p>La valutazione delle ipotesi acquista senso compiuto solo quando si traduce in una decisione. Una regola semplice consiste nell’agire come se <span class="math inline">\(\mu &gt; 110\)</span> qualora la probabilità a posteriori superi una soglia prefissata <span class="math inline">\(p^\*\)</span>, scelta in base al bilancio tra costi e benefici. Ad esempio, con <span class="math inline">\(p^\* = 0.90\)</span> si decide di agire solo se <span class="math inline">\(P(\mu &gt; 110 \mid y) \geq 0.90\)</span>, altrimenti si rinvia o si raccolgono nuovi dati. La soglia <span class="math inline">\(p^\*\)</span> non è arbitraria: un valore troppo basso aumenta il rischio di un’azione ingiustificata, mentre un valore troppo alto espone al rischio di trascurare un’azione necessaria. L’approccio bayesiano ha il merito di rendere esplicito questo nesso tra evidenza statistica e conseguenze pratiche, permettendo di calibrare la decisione sulla base delle priorità del contesto.</p>
<p>Spesso, tuttavia, l’interesse non è stabilire se la media sia <em>esattamente</em> pari a un certo valore, ma se possa essere considerata <em>praticamente equivalente</em> a esso entro un margine di tolleranza ritenuto accettabile. Per questo si introduce la <em>ROPE</em> (<em>Region of Practical Equivalence</em>), che definisce un intervallo attorno al valore soglia. Nel nostro esempio poniamo:</p>
<p><span class="math display">\[
\text{ROPE} = [108,\,112].
\]</span> L’idea non è più chiedersi se <span class="math inline">\(\mu = 110\)</span>, ma se <span class="math inline">\(\mu\)</span> appartenga a un intervallo che, per il problema in esame, può essere considerato equivalente a 110.</p>
</section><section id="calcolo-e-interpretazione" class="level3" data-number="13.4.3"><h3 data-number="13.4.3" class="anchored" data-anchor-id="calcolo-e-interpretazione">
<span class="header-section-number">13.4.3</span> Calcolo e interpretazione</h3>
<p>A partire dai campioni MCMC possiamo stimare la probabilità che <span class="math inline">\(\mu\)</span> cada al di sotto, all’interno o al di sopra della ROPE:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">rope</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">108</span>, <span class="fl">112</span><span class="op">)</span></span>
<span></span>
<span><span class="va">P_below</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mu_draws</span> <span class="op">&lt;</span>  <span class="va">rope</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span>                       <span class="co"># Probabilità sotto ROPE</span></span>
<span><span class="va">P_in</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mu_draws</span> <span class="op">&gt;=</span> <span class="va">rope</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">&amp;</span> <span class="va">mu_draws</span> <span class="op">&lt;=</span> <span class="va">rope</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span> <span class="co"># Probabilità dentro ROPE</span></span>
<span><span class="va">P_above</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mu_draws</span> <span class="op">&gt;</span>  <span class="va">rope</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span>                       <span class="co"># Probabilità sopra ROPE</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>P_below <span class="op">=</span> <span class="va">P_below</span>, P_in <span class="op">=</span> <span class="va">P_in</span>, P_above <span class="op">=</span> <span class="va">P_above</span><span class="op">)</span></span>
<span><span class="co">#&gt; P_below    P_in P_above </span></span>
<span><span class="co">#&gt; 0.91463 0.08250 0.00287</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Se la distribuzione a posteriori è ben approssimata da una Normale, gli stessi valori possono essere calcolati anche in forma chiusa:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">P_below_cf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="va">rope</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, mean <span class="op">=</span> <span class="va">post_mean</span>, sd <span class="op">=</span> <span class="va">post_sd</span><span class="op">)</span></span>
<span><span class="va">P_in_cf</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="va">rope</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>, mean <span class="op">=</span> <span class="va">post_mean</span>, sd <span class="op">=</span> <span class="va">post_sd</span><span class="op">)</span> <span class="op">-</span></span>
<span>              <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="va">rope</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, mean <span class="op">=</span> <span class="va">post_mean</span>, sd <span class="op">=</span> <span class="va">post_sd</span><span class="op">)</span></span>
<span><span class="va">P_above_cf</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="va">rope</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>, mean <span class="op">=</span> <span class="va">post_mean</span>, sd <span class="op">=</span> <span class="va">post_sd</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>P_below_cf <span class="op">=</span> <span class="va">P_below_cf</span>, P_in_cf <span class="op">=</span> <span class="va">P_in_cf</span>, P_above_cf <span class="op">=</span> <span class="va">P_above_cf</span><span class="op">)</span></span>
<span><span class="co">#&gt; P_below_cf    P_in_cf P_above_cf </span></span>
<span><span class="co">#&gt;    0.91498    0.08275    0.00226</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Se la probabilità che <span class="math inline">\(\mu\)</span> cada all’interno della ROPE è elevata, si conclude che la media è praticamente equivalente al valore soglia. Se invece la probabilità si concentra al di sopra o al di sotto dell’intervallo, si parla rispettivamente di un’evidenza che <span class="math inline">\(\mu\)</span> sia superiore o inferiore in senso rilevante. Nel caso in cui nessuna delle tre categorie prevalga nettamente, l’esito è quello di incertezza: in tale situazione è opportuno raccogliere ulteriori dati o riconsiderare l’ampiezza della ROPE adottata.</p>
</section><section id="esempio-di-report" class="level3" data-number="13.4.4"><h3 data-number="13.4.4" class="anchored" data-anchor-id="esempio-di-report">
<span class="header-section-number">13.4.4</span> Esempio di report</h3>
<blockquote class="blockquote">
<p>Con ROPE = <span class="math inline">\([108,112]\)</span>, si ottiene: <span class="math inline">\(P(\mu &lt; 108) = 0.92\)</span>, <span class="math inline">\(P(108 \leq \mu \leq 112) = 0.08\)</span>, <span class="math inline">\(P(\mu &gt; 112) = 0.003\)</span>. Questi risultati indicano che la media <span class="math inline">\(\mu\)</span> è con alta probabilità <em>inferiore</em> a 110, nel senso pratico definito dalla ROPE.</p>
</blockquote>
</section></section><section id="diagnostiche-di-campionamento" class="level2" data-number="13.5"><h2 data-number="13.5" class="anchored" data-anchor-id="diagnostiche-di-campionamento">
<span class="header-section-number">13.5</span> Diagnostiche di campionamento</h2>
<p>Dopo aver ottenuto i campioni dalla distribuzione a posteriori, il passo successivo è verificare la loro qualità. Un modello ben specificato e un campionamento MCMC efficiente producono catene che esplorano in modo completo e bilanciato lo spazio dei parametri. Per questo, nei riepiloghi forniti da Stan e dai pacchetti associati compaiono alcune statistiche diagnostiche fondamentali, che meritano attenzione. La quantità <code>lp__</code> compare in ogni output: non è un parametro del modello, ma la log-densità a posteriori, utile come strumento di controllo.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit2</span><span class="op">$</span><span class="fu">summary</span><span class="op">(</span>variables <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"mu"</span>,<span class="st">"lp__"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 10</span></span>
<span><span class="co">#&gt;   variable    mean  median    sd   mad      q5     q95  rhat ess_bulk ess_tail</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;      &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 mu       104.240 104.236 2.721 2.740  99.751 108.710 1.001 5499.842 7540.041</span></span>
<span><span class="co">#&gt; 2 lp__     -14.463 -14.195 0.705 0.313 -15.896 -13.967 1.001 7356.664 9175.822</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Un primo indicatore chiave è la statistica di convergenza <span class="math inline">\(\hat{R}\)</span> (o <em>R-hat</em>). Essa confronta la variabilità <em>intra-catena</em> con quella <em>inter-catena</em>: quando le catene hanno raggiunto lo stesso equilibrio, oscillano nelle stesse regioni della distribuzione e <span class="math inline">\(\hat{R}\)</span> tende a 1. Nel nostro esempio, i valori sono 1.001 per <code>mu</code> e 1.001 per <code>lp__</code>, praticamente indistinguibili da 1. In generale, valori inferiori a 1.01 sono considerati ottimali, mentre valori superiori a 1.05 segnalano possibili problemi di convergenza.</p>
<p>Un secondo gruppo di statistiche riguarda la dimensione del campione effettivo (ESS, <em>effective sample size</em>). Poiché i campioni MCMC sono correlati, l’ESS misura a quanti campioni indipendenti essi siano “equivalenti”. Nel nostro caso, per <code>mu</code> l’ESS è pari a 5500 (bulk) e 7540 (tail), mentre per <code>lp__</code> è rispettivamente 7357 e 9176. Si tratta di valori elevati, che assicurano stime stabili anche per i quantili estremi. A titolo illustrativo, l’errore Monte Carlo sulla media di <code>mu</code>, calcolato come <span class="math inline">\(\text{sd}/\sqrt{\text{ESS}}\)</span>, è circa 0.04: un valore trascurabile rispetto alla deviazione standard della posterior, pari a 2.72.</p>
<p>Oltre agli indici numerici, è utile considerare la forma della distribuzione stimata. Nel riepilogo, la media (104.24) e la mediana (104.24) coincidono quasi perfettamente, segnalando una distribuzione sostanzialmente simmetrica. La deviazione standard (2.72) e la MAD (2.74) risultano molto vicine, confermando che la variabilità è ben catturata. I quantili dal 5° al 95° definiscono un intervallo credibile al 90% compreso tra circa e : ne consegue che la soglia 110 si colloca al di sopra di questo intervallo, con bassa probabilità di essere superata.</p>
<p>Per un riscontro visivo della dinamica delle catene, il <em>traceplot</em> deve mostrare linee ben mescolate, senza trend o stazionamenti anomali:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">bayesplot</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/bayesplot/reference/MCMC-traces.html">mcmc_trace</a></span><span class="op">(</span><span class="va">fit2</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span><span class="st">"mu"</span><span class="op">)</span>, n_warmup <span class="op">=</span> <span class="fl">1000</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="03_stan_intro_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<p>Un’ulteriore verifica consiste nel confronto delle densità tra catene:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">bayesplot</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/bayesplot/reference/MCMC-distributions.html">mcmc_dens_overlay</a></span><span class="op">(</span><span class="va">fit2</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span><span class="st">"mu"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="03_stan_intro_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<p>La buona sovrapposizione delle curve indica che le catene hanno raggiunto la stessa distribuzione stazionaria.</p>
<p>Infine, <code>lp__</code> — la log-densità a posteriori — non è un parametro di interesse sostantivo ma uno strumento diagnostico: anche per <code>lp__</code> gli indici <span class="math inline">\(\hat{R}\)</span> e ESS risultano eccellenti (1.001, 7357/9176), confermando un’esplorazione regolare dello spazio dei parametri.</p>
<p>In sintesi, tutti gli indici diagnostici — <span class="math inline">\(\hat{R}\)</span> prossimo a 1, ESS elevati, coerenza tra media, mediana e misure di dispersione, oltre a traceplot e densità sovrapposte — convergono verso la stessa conclusione: il campionamento MCMC è stato stabile ed efficiente. Possiamo quindi considerare le stime ottenute come una rappresentazione affidabile della distribuzione a posteriori prevista dal nostro modello.</p>
</section><section id="prior-e-posterior-predictive-check" class="level2" data-number="13.6"><h2 data-number="13.6" class="anchored" data-anchor-id="prior-e-posterior-predictive-check">
<span class="header-section-number">13.6</span> Prior e Posterior Predictive Check</h2>
<p>Un passaggio cruciale nell’analisi bayesiana consiste nel verificare la capacità del modello di generare dati plausibili. Questo controllo può avvenire in due momenti distinti.</p>
<p>Prima dell’osservazione dei dati si esegue il <em>prior predictive check</em>, che serve a valutare se il prior scelto sia compatibile con valori ragionevoli. Se, ad esempio, i priors producono simulazioni di punteggi di QI del tutto inverosimili, è segno che occorre rivederne la specificazione.</p>
<p>Dopo l’aggiornamento con i dati osservati, si procede al <em>posterior predictive check</em>. In questa fase l’attenzione si sposta sulla capacità del modello stimato di riprodurre l’evidenza empirica: i dati simulati a posteriori dovrebbero assomigliare ai dati reali, sia nelle tendenze centrali sia nella variabilità. Se emergono scostamenti sistematici, ciò indica che il modello non riesce a catturare adeguatamente il fenomeno e richiede un perfezionamento.</p>
<p>Questi concetti sono già stati introdotti in precedenza; qui ci concentreremo sulla loro implementazione pratica utilizzando l’ecosistema di Stan.</p>
<section id="prior-predictive-check" class="level3" data-number="13.6.1"><h3 data-number="13.6.1" class="anchored" data-anchor-id="prior-predictive-check">
<span class="header-section-number">13.6.1</span> Prior Predictive Check</h3>
<p>Il primo passo, prima ancora di osservare i dati, è verificare se le nostre assunzioni a priori producono valori plausibili. In termini concreti: il prior scelto per <span class="math inline">\(\mu\)</span> genera punteggi di QI che hanno senso rispetto al dominio del problema?</p>
<p>Il modello è definito come</p>
<p><span class="math display">\[
y_i \mid \mu \sim \mathcal{N}(\mu, \sigma),
\qquad
\mu \sim \mathcal{N}(\mu_0, \tau).
\]</span></p>
<p>Combinando la verosimiglianza con il prior, otteniamo la <em>distribuzione predittiva a priori</em> per una singola osservazione:</p>
<p><span class="math display">\[
y_i \sim \mathcal{N}\!\Big(\mu_0,\; \sqrt{\sigma^2 + \tau^2}\Big).
\]</span> Questa distribuzione descrive quali valori ci aspetteremmo <em>prima di osservare alcun dato</em>. Se produce valori estremamente inverosimili (ad esempio QI &lt; 40 o &gt; 160), significa che il prior è troppo <em>ampio</em> o mal centrato. Se invece concentra quasi tutta la massa in un intervallo ristretto, rischia di essere <em>eccessivamente informativo</em>, lasciando poco spazio ai dati.</p>
<section id="implementazione-in-stan" class="level4" data-number="13.6.1.1"><h4 data-number="13.6.1.1" class="anchored" data-anchor-id="implementazione-in-stan">
<span class="header-section-number">13.6.1.1</span> Implementazione in Stan</h4>
<p>Per eseguire un <em>prior predictive check</em> possiamo utilizzare lo stesso modello Stan destinato all’inferenza, con una piccola modifica. Introduciamo una variabile booleana <code>compute_likelihood</code> che decide se attivare o meno la riga <code>y ~ normal(mu, sigma);</code>. In questo modo possiamo “spegnere” la verosimiglianza e simulare esclusivamente dal prior. Inoltre, nel blocco <code>generated quantities</code> generiamo delle repliche <span class="math inline">\(y_{\text{rep}}\)</span> da confrontare con i dati osservati.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stancode_norm_ppc</span> <span class="op">&lt;-</span> <span class="st">"</span></span>
<span><span class="st">data {</span></span>
<span><span class="st">  int&lt;lower=0&gt; N;</span></span>
<span><span class="st">  vector[N] y;                 // usato solo se compute_likelihood=1</span></span>
<span><span class="st">  real&lt;lower=0&gt; sigma;         // sd nota</span></span>
<span><span class="st">  real mu0;                    // media del prior su mu</span></span>
<span><span class="st">  real&lt;lower=0&gt; mu_prior_sd;   // sd del prior</span></span>
<span><span class="st">  int&lt;lower=0, upper=1&gt; compute_likelihood; // 1 = attiva likelihood</span></span>
<span><span class="st">}</span></span>
<span><span class="st">parameters {</span></span>
<span><span class="st">  real mu;</span></span>
<span><span class="st">}</span></span>
<span><span class="st">model {</span></span>
<span><span class="st">  mu ~ normal(mu0, mu_prior_sd);</span></span>
<span><span class="st">  if (compute_likelihood == 1) {</span></span>
<span><span class="st">    y ~ normal(mu, sigma);</span></span>
<span><span class="st">  }</span></span>
<span><span class="st">}</span></span>
<span><span class="st">generated quantities {</span></span>
<span><span class="st">  vector[N] y_rep;</span></span>
<span><span class="st">  vector[N] log_lik; </span></span>
<span><span class="st"></span></span>
<span><span class="st">  for (n in 1:N) {</span></span>
<span><span class="st">    y_rep[n] = normal_rng(mu, sigma); </span></span>
<span><span class="st">    log_lik[n] = normal_lpdf(y[n] | mu, sigma); </span></span>
<span><span class="st">  }</span></span>
<span><span class="st">}</span></span>
<span><span class="st">"</span></span>
<span><span class="va">stanmod_ppc</span> <span class="op">&lt;-</span> <span class="fu">cmdstan_model</span><span class="op">(</span><span class="fu">write_stan_file</span><span class="op">(</span><span class="va">stancode_norm_ppc</span><span class="op">)</span>, compile <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Per un controllo <em>puro</em> del prior impostiamo <code>compute_likelihood = 0</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">N_ppc</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">y_cont</span><span class="op">)</span></span>
<span></span>
<span><span class="va">stan_data_prior</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>  N <span class="op">=</span> <span class="va">N_ppc</span>,</span>
<span>  y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>, <span class="va">N_ppc</span><span class="op">)</span>,   <span class="co"># placeholder, ignorato se compute_likelihood=0</span></span>
<span>  sigma <span class="op">=</span> <span class="va">sigma</span>,</span>
<span>  mu0 <span class="op">=</span> <span class="fl">100</span>,</span>
<span>  mu_prior_sd <span class="op">=</span> <span class="fl">30</span>,</span>
<span>  compute_likelihood <span class="op">=</span> <span class="fl">0</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_prior</span> <span class="op">&lt;-</span> <span class="va">stanmod_ppc</span><span class="op">$</span><span class="fu">sample</span><span class="op">(</span></span>
<span>  data <span class="op">=</span> <span class="va">stan_data_prior</span>,</span>
<span>  iter_warmup <span class="op">=</span> <span class="fl">500</span>,</span>
<span>  iter_sampling <span class="op">=</span> <span class="fl">2000</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  parallel_chains <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  seed <span class="op">=</span> <span class="fl">4790</span>,</span>
<span>  refresh <span class="op">=</span> <span class="fl">500</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Dopo il campionamento estraiamo le repliche <span class="math inline">\(y_{\text{rep}}\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Estrazione delle repliche</span></span>
<span><span class="va">yrep_mat_prior</span> <span class="op">&lt;-</span> <span class="fu">posterior</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/posterior/reference/draws_matrix.html">as_draws_matrix</a></span><span class="op">(</span><span class="va">fit_prior</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span><span class="st">"y_rep"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Selezione delle colonne y_rep[1],...,y_rep[N]</span></span>
<span><span class="va">yrep_mat_prior</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span><span class="op">(</span></span>
<span>  <span class="va">yrep_mat_prior</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"y_rep["</span>, <span class="fl">1</span><span class="op">:</span><span class="va">N_ppc</span>, <span class="st">"]"</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Possiamo ora confrontare i dati osservati con alcune repliche simulate:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">idx</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">yrep_mat_prior</span><span class="op">)</span><span class="op">)</span>, <span class="fl">100</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">bayesplot</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/bayesplot/reference/PPC-distributions.html">ppc_dens_overlay</a></span><span class="op">(</span></span>
<span>  y <span class="op">=</span> <span class="va">y_cont</span>,</span>
<span>  yrep <span class="op">=</span> <span class="va">yrep_mat_prior</span><span class="op">[</span><span class="va">idx</span>, , drop <span class="op">=</span> <span class="cn">FALSE</span><span class="op">]</span></span>
<span><span class="op">)</span> </span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="03_stan_intro_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
</section><section id="interpretazione-1" class="level4" data-number="13.6.1.2"><h4 data-number="13.6.1.2" class="anchored" data-anchor-id="interpretazione-1">
<span class="header-section-number">13.6.1.2</span> Interpretazione</h4>
<p>Se le distribuzioni simulate dal prior coprono la gamma dei dati reali, le nostre assunzioni iniziali sono plausibili. Se invece risultano troppo ampie o troppo strette, occorre ripensare la scelta di <code>mu_prior_sd</code> o la posizione del prior. In questo senso, il <em>prior predictive check</em> rappresenta un primo banco di prova fondamentale: ci permette di verificare se il modello, ancora prima di vedere i dati, è coerente con le conoscenze di base sul fenomeno studiato.</p>
<p>Nel grafico vediamo la distribuzione osservata dei punteggi (linea scura) confrontata con un insieme di repliche simulate dal prior (linee chiare). L’insieme delle simulazioni copre bene la variabilità dei dati reali: i punteggi osservati cadono in una regione ampiamente compatibile con quanto previsto a priori. Questo indica che il prior scelto è sufficientemente ampio da includere valori plausibili, senza però generare in prevalenza esiti palesemente irrealistici.</p>
<p>L’esercizio conferma quindi che le assunzioni iniziali sul parametro <span class="math inline">\(\mu\)</span> non introducono vincoli eccessivi né distorsioni forti. Il modello, ancora prima di essere aggiornato con i dati, è coerente con la conoscenza di base sul fenomeno considerato (i punteggi di QI), e può essere usato come punto di partenza per l’inferenza bayesiana.</p>
</section></section><section id="posterior-predictive-check" class="level3" data-number="13.6.2"><h3 data-number="13.6.2" class="anchored" data-anchor-id="posterior-predictive-check">
<span class="header-section-number">13.6.2</span> Posterior Predictive Check</h3>
<p>Dopo aver verificato la plausibilità del <em>prior</em>, il passo successivo è valutare se il modello, una volta aggiornato con i dati, riesca a riprodurre in modo realistico l’evidenza empirica. Questo è lo scopo del <em>posterior predictive check</em>. Abbiamo già incontrato questo strumento nel caso del modello beta-binomiale; qui lo applichiamo al modello normale con prior normale, sfruttando le funzioni di Stan.</p>
<p>Per procedere, riattiviamo la verosimiglianza (<code>compute_likelihood = 1</code>) e stimiamo la distribuzione a posteriori di <span class="math inline">\(\mu\)</span>. Nel blocco <code>generated quantities</code> Stan genera repliche <span class="math inline">\(y_{\text{rep}}\)</span>, ossia nuovi dataset simulati sotto l’ipotesi che il modello e i parametri stimati siano corretti. Il confronto fra i dati osservati e queste repliche permette di valutare direttamente la capacità predittiva del modello.</p>
<p>Il principio è semplice: il <em>prior predictive check</em> serve a valutare le assunzioni prima di vedere i dati, mentre il <em>posterior predictive check</em> indaga se, dopo l’aggiornamento, il modello sia effettivamente in grado di riprodurre il fenomeno osservato.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stan_data_post</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>  N <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">y_cont</span><span class="op">)</span>,</span>
<span>  y <span class="op">=</span> <span class="va">y_cont</span>,</span>
<span>  sigma <span class="op">=</span> <span class="va">sigma</span>,</span>
<span>  mu0 <span class="op">=</span> <span class="fl">100</span>,</span>
<span>  mu_prior_sd <span class="op">=</span> <span class="fl">30</span>,</span>
<span>  compute_likelihood <span class="op">=</span> <span class="fl">1</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Il campionamento da Stan:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_post</span> <span class="op">&lt;-</span> <span class="va">stanmod_ppc</span><span class="op">$</span><span class="fu">sample</span><span class="op">(</span></span>
<span>  data <span class="op">=</span> <span class="va">stan_data_post</span>,</span>
<span>  iter_warmup <span class="op">=</span> <span class="fl">1000</span>,</span>
<span>  iter_sampling <span class="op">=</span> <span class="fl">10000</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  parallel_chains <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  seed <span class="op">=</span> <span class="fl">4790</span>,</span>
<span>  refresh <span class="op">=</span> <span class="fl">1000</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Una volta estratte le repliche, possiamo confrontarle con i dati reali:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">y_rep</span> <span class="op">&lt;-</span> <span class="va">fit_post</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span><span class="st">"y_rep"</span>, format <span class="op">=</span> <span class="st">"matrix"</span><span class="op">)</span></span>
<span><span class="fu">ppc_dens_overlay</span><span class="op">(</span>y <span class="op">=</span> <span class="va">stan_data_post</span><span class="op">$</span><span class="va">y</span>, yrep <span class="op">=</span> <span class="va">y_rep</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">100</span>, <span class="op">]</span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="03_stan_intro_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<p>Se le distribuzioni simulate coprono bene quella dei dati osservati, il modello descrive adeguatamente il fenomeno. Al contrario, scostamenti sistematici — ad esempio repliche con media troppo bassa o varianza troppo elevata — segnalano che il modello non cattura pienamente la realtà e dovrebbe essere rivisto.</p>
<p>Il collegamento con la fase di verifica dei <em>prior</em> è immediato: un prior troppo vago può generare simulazioni poco credibili già in fase predittiva a priori, mentre un prior troppo rigido rischia di imporre vincoli eccessivi. Nel <em>posterior predictive check</em>, tuttavia, ciò che conta è il risultato finale: dopo l’aggiornamento con i dati, le simulazioni devono riflettere con realismo l’evidenza empirica.</p>
<p>Nel grafico osserviamo la distribuzione empirica dei punteggi (linea scura) affiancata a un insieme di repliche simulate dalla distribuzione a posteriori (linee chiare). A differenza del controllo sul <em>prior</em>, qui il modello è stato aggiornato con i dati, e le simulazioni riflettono sia le assunzioni iniziali sia l’informazione empirica raccolta.</p>
<p>Il confronto mostra una buona corrispondenza: le repliche coprono con realismo la forma della distribuzione osservata, senza evidenziare scostamenti sistematici. In particolare, la media delle repliche si allinea bene a quella dei dati reali, e la variabilità simulata risulta compatibile con quella empirica. Questo conferma quanto già emerso dall’analisi numerica: la stima a posteriori della media <span class="math inline">\(\mu\)</span> (circa 104) è coerente con il campione osservato e attribuisce bassa probabilità all’ipotesi che <span class="math inline">\(\mu\)</span> superi la soglia di 110.</p>
<p>Nel complesso, il <em>posterior predictive check</em> suggerisce che il modello normale con prior scelto descrive adeguatamente il fenomeno considerato (i punteggi QI in questo esempio). Si tratta quindi di una base affidabile per trarre conclusioni inferenziali e, se necessario, collegare i risultati a decisioni pratiche.</p>
</section></section><section id="riflessioni-conclusive" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="riflessioni-conclusive">Riflessioni conclusive</h2>
<p>Stan rappresenta il punto di approdo naturale del percorso seguito fin qui. Dopo aver introdotto la logica dell’inferenza bayesiana con algoritmi semplici come Metropolis e aver visto come i linguaggi probabilistici abbiano reso più accessibile questa logica, Stan ci mette ora a disposizione uno strumento maturo, capace di tradurre queste idee in pratica su modelli reali e complessi.</p>
<p>Il suo valore non risiede soltanto nella potenza computazionale, ma soprattutto nella possibilità di <em>spostare l’attenzione dal calcolo all’idea scientifica</em>. Con Stan possiamo formulare ipotesi psicologiche in termini formali, esplicitarne le assunzioni e sottoporle a verifica empirica in modo trasparente e riproducibile. Il ricercatore non è più costretto a concentrarsi sui dettagli algoritmici, ma può dedicarsi a ciò che conta davvero: la sostanza teorica del modello e la sua capacità di descrivere i dati.</p>
<p>In questo senso, Stan non è semplicemente un software, ma un vero e proprio ambiente di ricerca che promuove chiarezza, rigore e cumulatività. Nei capitoli che seguono impareremo a utilizzarlo prima con esempi semplici, per poi estendere gradualmente l’analisi a modelli più articolati. L’obiettivo non è solo acquisire familiarità con la sintassi, ma soprattutto interiorizzare un <em>modo di pensare</em>: quello che fa della modellazione bayesiana uno strumento essenziale della psicologia scientifica contemporanea.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Informazioni sull'ambiente di sviluppo">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Informazioni sull’ambiente di sviluppo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.5.1 (2025-06-13)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin20</span></span>
<span><span class="co">#&gt; Running under: macOS Tahoe 26.0</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Rome</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] insight_1.4.2         cmdstanr_0.9.0        pillar_1.11.1        </span></span>
<span><span class="co">#&gt;  [4] tinytable_0.13.0      patchwork_1.3.2       ggdist_3.3.3         </span></span>
<span><span class="co">#&gt;  [7] tidybayes_3.0.7       bayesplot_1.14.0      ggplot2_4.0.0        </span></span>
<span><span class="co">#&gt; [10] reliabilitydiag_0.2.1 priorsense_1.1.1      posterior_1.6.1      </span></span>
<span><span class="co">#&gt; [13] loo_2.8.0             rstan_2.32.7          StanHeaders_2.32.10  </span></span>
<span><span class="co">#&gt; [16] brms_2.23.0           Rcpp_1.1.0            sessioninfo_1.2.3    </span></span>
<span><span class="co">#&gt; [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    </span></span>
<span><span class="co">#&gt; [22] modelr_0.1.11         tibble_3.3.0          dplyr_1.1.4          </span></span>
<span><span class="co">#&gt; [25] tidyr_1.3.1           rio_1.2.3             here_1.0.2           </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;  [1] gridExtra_2.3         inline_0.3.21         sandwich_3.1-1       </span></span>
<span><span class="co">#&gt;  [4] rlang_1.1.6           magrittr_2.0.4        multcomp_1.4-28      </span></span>
<span><span class="co">#&gt;  [7] snakecase_0.11.1      ggridges_0.5.7        compiler_4.5.1       </span></span>
<span><span class="co">#&gt; [10] reshape2_1.4.4        systemfonts_1.2.3     vctrs_0.6.5          </span></span>
<span><span class="co">#&gt; [13] stringr_1.5.2         pkgconfig_2.0.3       arrayhelpers_1.1-0   </span></span>
<span><span class="co">#&gt; [16] fastmap_1.2.0         backports_1.5.0       labeling_0.4.3       </span></span>
<span><span class="co">#&gt; [19] utf8_1.2.6            rmarkdown_2.29        ps_1.9.1             </span></span>
<span><span class="co">#&gt; [22] ragg_1.5.0            purrr_1.1.0           xfun_0.53            </span></span>
<span><span class="co">#&gt; [25] cachem_1.1.0          jsonlite_2.0.0        broom_1.0.10         </span></span>
<span><span class="co">#&gt; [28] parallel_4.5.1        R6_2.6.1              stringi_1.8.7        </span></span>
<span><span class="co">#&gt; [31] RColorBrewer_1.1-3    lubridate_1.9.4       estimability_1.5.1   </span></span>
<span><span class="co">#&gt; [34] knitr_1.50            zoo_1.8-14            pacman_0.5.1         </span></span>
<span><span class="co">#&gt; [37] Matrix_1.7-4          splines_4.5.1         timechange_0.3.0     </span></span>
<span><span class="co">#&gt; [40] tidyselect_1.2.1      abind_1.4-8           yaml_2.3.10          </span></span>
<span><span class="co">#&gt; [43] codetools_0.2-20      curl_7.0.0            processx_3.8.6       </span></span>
<span><span class="co">#&gt; [46] pkgbuild_1.4.8        plyr_1.8.9            lattice_0.22-7       </span></span>
<span><span class="co">#&gt; [49] bayestestR_0.17.0     withr_3.0.2           bridgesampling_1.1-2 </span></span>
<span><span class="co">#&gt; [52] S7_0.2.0              coda_0.19-4.1         evaluate_1.0.5       </span></span>
<span><span class="co">#&gt; [55] survival_3.8-3        RcppParallel_5.1.11-1 tensorA_0.36.2.1     </span></span>
<span><span class="co">#&gt; [58] checkmate_2.3.3       stats4_4.5.1          distributional_0.5.0 </span></span>
<span><span class="co">#&gt; [61] generics_0.1.4        rprojroot_2.1.1       rstantools_2.5.0     </span></span>
<span><span class="co">#&gt; [64] scales_1.4.0          xtable_1.8-4          glue_1.8.0           </span></span>
<span><span class="co">#&gt; [67] emmeans_1.11.2-8      tools_4.5.1           data.table_1.17.8    </span></span>
<span><span class="co">#&gt; [70] mvtnorm_1.3-3         grid_4.5.1            QuickJSR_1.8.0       </span></span>
<span><span class="co">#&gt; [73] colorspace_2.1-1      nlme_3.1-168          cli_3.6.5            </span></span>
<span><span class="co">#&gt; [76] textshaping_1.0.3     svUnit_1.0.8          Brobdingnag_1.2-9    </span></span>
<span><span class="co">#&gt; [79] V8_7.0.0              gtable_0.3.6          digest_0.6.37        </span></span>
<span><span class="co">#&gt; [82] TH.data_1.1-4         htmlwidgets_1.6.4     farver_2.1.2         </span></span>
<span><span class="co">#&gt; [85] memoise_2.0.1         htmltools_0.5.8.1     lifecycle_1.0.4      </span></span>
<span><span class="co">#&gt; [88] MASS_7.3-65</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
</section><section id="bibliografia" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="bibliografia">Bibliografia</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-nicenboim2025introduction" class="csl-entry" role="listitem">
Nicenboim, B., Schad, D. J., &amp; Vasishth, S. (2025). <em>Introduction to Bayesian data analysis for cognitive science</em>. CRC Press.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>Vale la pena notare che, se in Stan dichiariamo un parametro vincolato all’intervallo <span class="math inline">\([0,1]\)</span> ma non specifichiamo alcun prior, il linguaggio assegna automaticamente proprio questa distribuzione uniforme, che corrisponde a una Beta(1,1).<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2">
<p>Dal punto di vista interno, ogni riga del tipo <code>x ~ distribuzione(...)</code> aggiunge la log-densità (o log-massa) alla quantità interna <code>target</code>, che rappresenta la log-posterior. Se vogliamo essere più espliciti, possiamo scrivere il codice in forma equivalente:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode stan code-with-copy"><code class="sourceCode stan"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">target +=</span> beta_lpdf(theta | <span class="dv">1</span>, <span class="dv">1</span>);</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="kw">target +=</span> bernoulli_lpmf(y | theta);</span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<p>Questa seconda scrittura, sebbene meno compatta, è particolarmente utile quando vogliamo costruire verosimiglianze personalizzate o introdurre modifiche non standard.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p>
</li>
<li id="fn3"><p>La funzione <code><a href="https://rdrr.io/r/base/sample.html">sample()</a></code> ha anche altri parametri importanti per ottimizzare il campionamento. Tra questi, <code>adapt_delta</code> aumenta la precisione dell’algoritmo di campionamento, riducendo gli errori di divergenza, mentre <code>max_treedepth</code> controlla la profondità massima dell’albero di campionamento. Utilizzarli è fondamentale per ottenere risultati stabili e affidabili, specialmente quando si lavora con modelli complessi o con dati problematici.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiato!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiato!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/utet-companion\/intro\.html");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/mcmc/02_ppl.html" class="pagination-link" aria-label="Linguaggi di programmazione probabilistici">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linguaggi di programmazione probabilistici</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/mcmc/04_stan_odds_ratio_stan.html" class="pagination-link" aria-label="Analisi bayesiana dell'odds ratio">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Analisi bayesiana dell’odds ratio</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Metodi bayesiani in psicologia — Companion site</strong>.<br>
Materiali di accompagnamento e approfondimento al manuale UTET.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ccaudek/utet-companion/blob/main/chapters/mcmc/03_stan_intro.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/utet-companion/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>