<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.34">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>18&nbsp; Confrontare due medie – Metodi bayesiani in psicologia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/mcmc/08_stan_poisson_model_1.html" rel="next">
<link href="../../chapters/mcmc/06_stan_odds_ratio_stan.html" rel="prev">
<link href="../../style/gauss.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-0a72236910a44089af39cd28873f322e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9908c7b05874059c2106d454ac00f1d0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QT5S3P9D31"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QT5S3P9D31', { 'anonymize_ip': true});
</script><style>html{ scroll-behavior: smooth; }</style>
<script>
window.MathJax = {
  tex: { inlineMath: [['$', '$'], ['\\(', '\\)']] },
  svg: { scale: 1, mtextInheritFont: true, fontCache: 'none', minScale: 1 },
  options: { renderActions: { addMenu: [0, '', ''] } },
  loader: { load: ['input/tex','output/svg'] }
};
</script><script>
window.MathJax = {
  tex: { inlineMath: [['$', '$'], ['\\(', '\\)']] },
  svg: { scale: 1, mtextInheritFont: true, fontCache: 'none', minScale: 1 },
  options: { renderActions: { addMenu: [0, '', ''] } },
  loader: { load: ['input/tex','output/svg'] }
};
// Suggerimento CSS: vedi sezione 3 per gli spazi attorno a display math
</script><script>
window.MathJax = {
  tex: {
    packages: {'[+]': ['boldsymbol']},
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  },
  svg: { fontCache: 'global' }
};
</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../../style/_typography-extras.css">
<link rel="stylesheet" href="../../style/_code-extras.css">
<link rel="stylesheet" href="../../style/_math-extras.css">
<link rel="stylesheet" href="../../style/styles.css">
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/mcmc/introduction_sec.html">MCMC</a></li><li class="breadcrumb-item"><a href="../../chapters/mcmc/07_stan_two_means.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Confrontare due medie</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Metodi bayesiani in psicologia</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ccaudek/utet-companion/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Attiva/disattiva la modalità lettore">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Ricerca"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Struttura del companion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../prefazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Prefazione</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Inferenza</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/01_bayes_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Inferenza bayesiana</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/02_uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Abbracciare l’incertezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/03_uncertainty_quantification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">La quantificazione dell’incertezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/04_statistical_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelli statistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/05_subj_prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Aggiornare le credenze su un parametro: dal prior alla posterior</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/06_conjugate_families.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Distribuzioni coniugate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/07_summary_posterior.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Sintesi a posteriori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/08_balance_prior_post.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">L’influenza della distribuzione a priori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/09_prior_pred_check.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Controllo predittivo a priori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/10_post_pred_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Distribuzione predittiva a posteriori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/bayesian_inference/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">MCMC</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/01_metropolis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">L’algoritmo di Metropolis-Hastings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/02_ppl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Linguaggi di programmazione probabilistici</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/03_stan_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Introduzione pratica a Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/04_stan_diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Diagnostica delle catene markoviane</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/05_mcmc_prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Controlli predittivi bayesiani (a priori e a posteriori) con <code>cmdstanr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/06_stan_odds_ratio_stan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Analisi bayesiana dell’odds ratio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/07_stan_two_means.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Confrontare due medie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/08_stan_poisson_model_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Modello di Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/09_stan_gaussian_mixture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Modelli Mistura Gaussiani</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/10_stan_nuisance_parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Modelli con più di un parametro</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/11_stan_hier_beta_binom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Modello gerarchico beta-binomiale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/12_stan_parametrization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Parametrizzazioni centered e non-centered</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/13_bayesian_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Flusso di lavoro bayesiano</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/mcmc/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive sulla sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Regressione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/01_reglin_frequentist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">La regressione lineare bivariata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/02_regr_toward_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">La regressione verso la media</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/03_reglin_bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Modello bayesiano di regressione lineare bivariata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/04_synt_sugar_sea_ice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Zucchero sintattico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/05_stan_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Regressione lineare in Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/06_specification_error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Errore di specificazione e bias da variabile omessa</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/07_one_mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Inferenza bayesiana su una media</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/08_two_means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Confronto tra le medie di due gruppi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/09_effect_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">La grandezza dell’effetto: valutare la rilevanza pratica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/10_sample_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Pianificazione della dimensione campionaria</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/11_anova_1via.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">ANOVA ad una via</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/linear_models/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">GLM</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/01_logistic_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Regressione logistica con Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/02_one_proportion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Inferenza sulle proporzioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/03_two_proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Confronto tra due proporzioni con la regressione logistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/04_poisson_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Modello di Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/05_logistic_process.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Dal GLM a un modello processuale per dati binari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/06_missing_values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Dati mancanti in psicologia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/glm/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive sulla sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Entropia</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/01_entropy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Entropia e informazione di Shannon</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/02_kl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">La divergenza di Kullback-Leibler</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/03_model_comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Valutare i modelli bayesiani</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/entropy/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Modelli</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/introduction_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione alla sezione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/01_dynamic_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Il modello di revisione degli obiettivi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/02_dynamic_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Estensioni</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/03_rescorla_wagner.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Il modello di Rescorla–Wagner</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/04_study_method.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Decisione ottimale e utilità attesa: l’approccio bayesiano</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/formal_models/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della sezione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Crisi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/introduction_replication_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduzione</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/01_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">La crisi della replicazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/02_limits_stat_freq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Limiti dell’inferenza frequentista</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/03_effect_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">La grandezza dell’effetto</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/04_s_m_errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Errori di segno e errori di grandezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/05_p_values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">La fragilità del <em>p</em>-valore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/06_changes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Riforma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/07_degrees_of_freedom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">I gradi di libertà del ricercatore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/replication_crisis/08_integrity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Integrità della ricerca</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Epilogo</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/epiloque/epiloque.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Considerazioni Conclusive</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a01_shell.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">La Shell</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a01a_files.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Cartelle e documenti</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a02_math_symbols.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Simbologia di base</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a03_latex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Equazioni Matematiche in LaTeX</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a11_numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Numeri e intervalli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a12_sum_notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Sommatorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a13_sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">Insiemi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a14_combinatorics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">Calcolo combinatorio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a15_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">I</span>&nbsp; <span class="chapter-title">Per liberarvi dai terrori preliminari</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a35_other_conjugate_families.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">J</span>&nbsp; <span class="chapter-title">Altre famiglie coniugate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a36_gamma_poisson_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">K</span>&nbsp; <span class="chapter-title">Modello coniugato Gamma-Poisson</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a40_metropolis_normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">L</span>&nbsp; <span class="chapter-title">Metropolis: esempio Normale–Normale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a41_cmdstanr_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">M</span>&nbsp; <span class="chapter-title">Implementazione di modelli Bayesiani con Stan tramite <code>cmdstanr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a50_lin_fun.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">N</span>&nbsp; <span class="chapter-title">La funzione lineare</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a71_install_cmdstan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">O</span>&nbsp; <span class="chapter-title">Come installare CmdStan</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Sommario</h2>
   
  <ul class="collapse">
<li><a href="#codice-r" id="toc-codice-r" class="nav-link active" data-scroll-target="#codice-r"><span class="header-section-number">18.1</span> Codice R</a></li>
  <li><a href="#modello-a-varianza-comune" id="toc-modello-a-varianza-comune" class="nav-link" data-scroll-target="#modello-a-varianza-comune"><span class="header-section-number">18.2</span> Modello a varianza comune</a></li>
  <li><a href="#modello-a-varianze-distinte" id="toc-modello-a-varianze-distinte" class="nav-link" data-scroll-target="#modello-a-varianze-distinte"><span class="header-section-number">18.3</span> Modello a varianze distinte</a></li>
  <li><a href="#cosa-impariamo" id="toc-cosa-impariamo" class="nav-link" data-scroll-target="#cosa-impariamo"><span class="header-section-number">18.4</span> Cosa impariamo</a></li>
  <li><a href="#dalle-medie-di-gruppo-allanalisi-idiografica" id="toc-dalle-medie-di-gruppo-allanalisi-idiografica" class="nav-link" data-scroll-target="#dalle-medie-di-gruppo-allanalisi-idiografica"><span class="header-section-number">18.5</span> Dalle medie di gruppo all’analisi idiografica</a></li>
  </ul><div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ccaudek/utet-companion/blob/main/chapters/mcmc/07_stan_two_means.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/utet-companion/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/mcmc/introduction_sec.html">MCMC</a></li><li class="breadcrumb-item"><a href="../../chapters/mcmc/07_stan_two_means.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Confrontare due medie</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-mcmc-two-means" class="quarto-section-identifier"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Confrontare due medie</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="introduzione" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="introduzione">Introduzione</h2>
<p>Immagina uno studio in cui confrontiamo il punteggio medio di <em>affetto negativo</em> settimanale tra un gruppo che segue un breve training di mindfulness e un gruppo di controllo. La domanda sostantiva non è “c’è <em>qualche</em> differenza?” ma “<em>di quanto</em> differiscono i gruppi e <em>quanto siamo incerti</em> su questa differenza?”. È questa la prospettiva che adottiamo qui: invece di ridurre il problema a un verdetto sì/no, stimiamo l’intera <em>distribuzione a posteriori</em> della differenza tra le medie e traduciamo tale distribuzione in affermazioni pratiche rilevanti per la psicologia.</p>
<p>In un confronto tra due gruppi, c’è anche un aspetto spesso trascurato ma cruciale: <em>la variabilità</em>. I due gruppi possono avere la stessa dispersione oppure no. Se, per esempio, il training riduce l’affetto negativo medio ma produce anche risposte più eterogenee (alcuni migliorano molto, altri poco), allora la differenza tra <em>deviazioni standard</em> è informativa tanto quanto la differenza tra medie. L’approccio bayesiano rende naturale stimare congiuntamente entrambe le quantità e la loro incertezza, offrendo un quadro più ricco di quello fornito dal t-test tradizionale <span class="citation" data-cites="kruschke2013bayesian">(<a href="#ref-kruschke2013bayesian" role="doc-biblioref">Kruschke, 2013</a>)</span>.</p>
<p>Per stabilizzare le stime e semplificare le scelte di prior, <em>standardizziamo</em> la variabile di esito <span class="math inline">\(y\)</span> sull’intero campione (media 0, deviazione standard 1). La standardizzazione non altera le relazioni tra i gruppi, ma rende più trasparenti le ipotesi: a priori è ragionevole attendersi medie di gruppo non lontane da 0 e dispersioni dell’ordine dell’unità. Lavoreremo con due modelli semplici e didatticamente utili: un modello con <em>varianza comune</em> ai gruppi e un modello con <em>varianze distinte</em>. In entrambi useremo <em>prior</em> debolmente informative sulle medie (normali centrate in 0) e sulle deviazioni standard (esponenziali), coerenti con la variabile standardizzata.</p>
<p>La domanda metodologica non è quale ipotesi sia “vera”, ma <em>quale modello predice meglio</em> dati simili a quelli osservati mantenendo la massima parsimonia. Useremo quindi la <em>densità predittiva logaritmica attesa</em> (ELPD) stimata con PSIS-LOO per confrontare i due modelli: se il guadagno predittivo del modello più complesso (varianze distinte) è minimo rispetto alla sua incertezza, conviene preferire il modello con varianza comune; se invece il vantaggio è chiaro e stabile, scegliamo il modello più flessibile.</p>
<p>Il cuore dell’analisi rimane comunque <em>la distribuzione a posteriori della differenza tra le medie</em>. È questa distribuzione che risponde alla domanda scientifica, ed è su di essa che riportiamo intervalli di credibilità e probabilità a posteriori di scenari di interesse (per esempio, la probabilità che la differenza sia inferiore a −0.2 SD, una soglia che potremmo considerare rilevante in termini clinici).</p>
<p>Rispetto al <em>t-test di Student</em>, l’approccio bayesiano offre tre vantaggi pratici per la ricerca psicologica. Primo, fornisce <em>stima e incertezza</em> di tutte le quantità rilevanti (differenza di medie, differenza di varianze, grandezza dell’effetto), invece di un unico p-value. Secondo, consente di <em>valutare l’equivalenza pratica</em> attraverso una <em>region of practical equivalence</em> (<em>ROPE</em>): se quasi tutta la posteriore ricade entro una piccola regione attorno a zero, possiamo <em>accettare l’irrilevanza pratica</em> dell’effetto, cosa che il t-test non permette in modo diretto. Terzo, l’impostazione è <em>robusta ed estendibile</em>: quando i dati mostrano code pesanti o outlier, possiamo descriverli con una distribuzione <em>t</em> e stimarne anche il grado di “normalità”, mantenendo una lettura sostantiva chiara delle differenze tra gruppi <span class="citation" data-cites="kruschke2013bayesian">(<a href="#ref-kruschke2013bayesian" role="doc-biblioref">Kruschke, 2013</a>)</span>.</p>
<p>In sintesi, in questo capitolo useremo <em>Stan</em> per stimare due modelli semplici e confrontarli sul piano predittivo, ma terremo sempre lo sguardo sulle <em>conclusioni sostantive</em>: nel nostro esempio, “di quanto” il training modifica l’affetto negativo medio, “quanto” è plausibile una differenza nulla o trascurabile, e “come” cambia l’eterogeneità delle risposte tra i partecipanti.</p>
<section id="transizione-al-codice" class="level3 unnumbered unlisted"><h3 class="unnumbered unlisted anchored" data-anchor-id="transizione-al-codice">Transizione al codice</h3>
<p>Nei prossimi paragrafi genereremo un piccolo dataset simulato per il caso mindfulness vs controllo, <em>standardizzeremo</em> l’esito, specificheremo in <em>Stan</em> un modello con <em>varianza comune</em> e uno con <em>varianze distinte</em>, quindi confronteremo le due specificazioni con <em>PSIS-LOO</em> e riporteremo la <em>posteriore della differenza tra le medie</em> con intervallo di credibilità e, dove appropriato, una <em>valutazione ROPE</em> per l’equivalenza pratica. L’obiettivo didattico è duplice: dare un codice leggibile a chi non è esperto e mostrare come le scelte modellistiche si traducano in <em>interpretazioni psicologiche</em> chiare.</p>
</section><section id="panoramica-del-capitolo" class="level3 unnumbered unlisted"><h3 class="unnumbered unlisted anchored" data-anchor-id="panoramica-del-capitolo">Panoramica del capitolo</h3>
<ul>
<li>Comprendere il problema del confronto tra due medie in un’ottica bayesiana.</li>
<li>Motivare la standardizzazione dei dati e la scelta di priors debolmente informative.</li>
<li>Implementare in <em>Stan</em> un modello con varianza comune e uno con varianze distinte.</li>
<li>Valutare la capacità predittiva dei modelli attraverso PSIS-LOO.</li>
<li>Interpretare la distribuzione a posteriori della differenza tra le medie e le verifiche predittive.</li>
</ul>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prerequisiti
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Nozioni di base su Bernoulli/Binomiale, odds e odds ratio.</li>
<li>Concetto di prior e posteriore.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-caution no-icon callout-titled" title="Preparazione del Notebook">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Preparazione del Notebook
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"code"</span>, <span class="st">"_common.R"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html">requireNamespace</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">cmdstanr</span>, <span class="va">posterior</span>, <span class="va">bayesplot</span>, <span class="va">ggplot2</span>, <span class="va">dplyr</span>, <span class="va">tibble</span>, <span class="va">forcats</span><span class="op">)</span></span>
<span><span class="fu">conflicts_prefer</span><span class="op">(</span><span class="fu">posterior</span><span class="fu">::</span><span class="va"><a href="https://mc-stan.org/posterior/reference/ess_bulk.html">ess_bulk</a></span><span class="op">)</span></span>
<span><span class="fu">conflicts_prefer</span><span class="op">(</span><span class="fu">posterior</span><span class="fu">::</span><span class="va"><a href="https://mc-stan.org/posterior/reference/ess_tail.html">ess_tail</a></span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section></section><section id="codice-r" class="level2" data-number="18.1"><h2 data-number="18.1" class="anchored" data-anchor-id="codice-r">
<span class="header-section-number">18.1</span> Codice R</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Simuliamo i dati di un piccolo studio psicologico</span></span>
<span><span class="co"># Gruppo A = controllo, Gruppo B = training mindfulness</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span>  <span class="co"># per rendere i risultati riproducibili</span></span>
<span></span>
<span><span class="va">n_A</span> <span class="op">&lt;-</span> <span class="fl">80</span>   <span class="co"># numero partecipanti controllo</span></span>
<span><span class="va">n_B</span> <span class="op">&lt;-</span> <span class="fl">90</span>   <span class="co"># numero partecipanti training</span></span>
<span></span>
<span><span class="co"># Medie "vere" dei gruppi (in SD standardizzate)</span></span>
<span><span class="va">true_mean_A</span> <span class="op">&lt;-</span> <span class="fl">0.2</span>   <span class="co"># controllo con affetto negativo leggermente più alto</span></span>
<span><span class="va">true_mean_B</span> <span class="op">&lt;-</span> <span class="op">-</span><span class="fl">0.3</span>   <span class="co"># training mindfulness riduce affetto negativo</span></span>
<span></span>
<span><span class="co"># Deviazioni standard "vere"</span></span>
<span><span class="va">true_sd_A</span> <span class="op">&lt;-</span> <span class="fl">1.0</span></span>
<span><span class="va">true_sd_B</span> <span class="op">&lt;-</span> <span class="fl">1.0</span>   <span class="co"># prova a cambiare in 1.4 per simulare varianze diverse</span></span>
<span></span>
<span><span class="co"># Creiamo un data frame con le osservazioni</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span></span>
<span>  score  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n_A</span>, <span class="va">true_mean_A</span>, <span class="va">true_sd_A</span><span class="op">)</span>,</span>
<span>             <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n_B</span>, <span class="va">true_mean_B</span>, <span class="va">true_sd_B</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  group  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"Controllo"</span>, <span class="va">n_A</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"Mindfulness"</span>, <span class="va">n_B</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Standardizziamo la variabile di esito</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="va">df</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span></span>
<span>    score_std <span class="op">=</span> <span class="op">(</span><span class="va">score</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">score</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">score</span><span class="op">)</span>,</span>
<span>    g <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/integer.html">as.integer</a></span><span class="op">(</span><span class="va">group</span><span class="op">)</span>   <span class="co"># Stan richiede indici numerici dei gruppi</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="co"># Prepariamo la lista di dati per Stan</span></span>
<span><span class="va">stan_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>  N <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span>,             <span class="co"># numero totale osservazioni</span></span>
<span>  J <span class="op">=</span> <span class="fl">2L</span>,                   <span class="co"># numero di gruppi</span></span>
<span>  y <span class="op">=</span> <span class="va">df</span><span class="op">$</span><span class="va">score_std</span>,         <span class="co"># variabile risposta standardizzata</span></span>
<span>  g <span class="op">=</span> <span class="va">df</span><span class="op">$</span><span class="va">g</span>                  <span class="co"># indice di gruppo</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu">glimpse</span><span class="op">(</span><span class="va">stan_data</span><span class="op">)</span></span>
<span><span class="co">#&gt; List of 4</span></span>
<span><span class="co">#&gt;  $ N: int 170</span></span>
<span><span class="co">#&gt;  $ J: int 2</span></span>
<span><span class="co">#&gt;  $ y: num [1:170] -0.3016 0.0317 1.8369 0.3352 0.3945 ...</span></span>
<span><span class="co">#&gt;  $ g: int [1:170] 1 1 1 1 1 1 1 1 1 1 ...</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="nota-didattica" class="level3" data-number="18.1.1"><h3 data-number="18.1.1" class="anchored" data-anchor-id="nota-didattica">
<span class="header-section-number">18.1.1</span> Nota didattica</h3>
<p>In questo esempio, la variabile <code>score</code> rappresenta il livello di affetto negativo. Abbiamo simulato una piccola differenza: in media, il gruppo mindfulness ha punteggi più bassi (cioè minore affetto negativo) rispetto al gruppo controllo. Standardizzando la variabile, lavoriamo sempre in “unità di deviazione standard”, semplificando l’interpretazione delle priors e delle stime.</p>
</section><section id="differenza-di-medie-e-rope" class="level3" data-number="18.1.2"><h3 data-number="18.1.2" class="anchored" data-anchor-id="differenza-di-medie-e-rope">
<span class="header-section-number">18.1.2</span> Differenza di medie e ROPE</h3>
<p>Prima ancora di stimare i modelli in <em>Stan</em>, possiamo calcolare la differenza empirica tra le medie e confrontarla con una <em>regione di irrilevanza pratica (ROPE)</em>. Per esempio, supponiamo che differenze inferiori a 0.1 SD non abbiano rilevanza psicologica. Questo ci permette di introdurre un confronto diretto con il test t: il t-test risponde solo alla domanda “la differenza è zero?”, mentre l’approccio bayesiano ci consente di valutare “la differenza è psicologicamente importante?”.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Differenza empirica tra le medie</span></span>
<span><span class="va">mean_diff</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">score_std</span><span class="op">[</span><span class="va">df</span><span class="op">$</span><span class="va">group</span> <span class="op">==</span> <span class="st">"Mindfulness"</span><span class="op">]</span><span class="op">)</span> <span class="op">-</span></span>
<span>             <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">score_std</span><span class="op">[</span><span class="va">df</span><span class="op">$</span><span class="va">group</span> <span class="op">==</span> <span class="st">"Controllo"</span><span class="op">]</span><span class="op">)</span></span>
<span></span>
<span><span class="va">mean_diff</span></span>
<span><span class="co">#&gt; [1] -0.535</span></span>
<span></span>
<span><span class="co"># Definiamo una ROPE di ±0.1 SD</span></span>
<span><span class="va">rope_lower</span> <span class="op">&lt;-</span> <span class="op">-</span><span class="fl">0.1</span></span>
<span><span class="va">rope_upper</span> <span class="op">&lt;-</span>  <span class="fl">0.1</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="st">"Differenza osservata ="</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">mean_diff</span>, <span class="fl">3</span><span class="op">)</span>, </span>
<span>    <span class="st">" | ROPE = ["</span>, <span class="va">rope_lower</span>, <span class="st">","</span>, <span class="va">rope_upper</span>, <span class="st">"]\n"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Differenza osservata = -0.535  | ROPE = [ -0.1 , 0.1 ]</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Naturalmente, la vera potenza del metodo bayesiano emergerà quando stimiamo la distribuzione a posteriori della differenza di medie. Allora potremo calcolare direttamente la <em>probabilità a posteriori che la differenza ricada dentro o fuori dalla ROPE</em>, ottenendo un’informazione più ricca e interpretabile rispetto al semplice p-value.</p>
</section></section><section id="modello-a-varianza-comune" class="level2" data-number="18.2"><h2 data-number="18.2" class="anchored" data-anchor-id="modello-a-varianza-comune">
<span class="header-section-number">18.2</span> Modello a varianza comune</h2>
<p>L’ipotesi è che i due gruppi condividano la stessa dispersione attorno alle loro medie. Questa è spesso una buona approssimazione iniziale, riduce il numero di parametri e permette stime più stabili con campioni piccoli o moderati. Il punto centrale resta la differenza tra le medie: se il training mindfulness riduce l’affetto negativo, la media del gruppo “Mindfulness” sarà più bassa e la differenza “Mindfulness − Controllo” sarà negativa in unità di deviazione standard.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Salviamo il modello Stan con varianza comune</span></span>
<span><span class="va">stan_equal_var</span> <span class="op">&lt;-</span> <span class="st">"</span></span>
<span><span class="st">data {</span></span>
<span><span class="st">  int&lt;lower=1&gt; N;                      // numero di osservazioni</span></span>
<span><span class="st">  int&lt;lower=2&gt; J;                      // numero di gruppi (qui: 2)</span></span>
<span><span class="st">  vector[N] y;                         // esito standardizzato</span></span>
<span><span class="st">  array[N] int&lt;lower=1, upper=J&gt; g;    // indice di gruppo per ogni osservazione</span></span>
<span><span class="st">}</span></span>
<span><span class="st">parameters {</span></span>
<span><span class="st">  vector[J] mu;                        // medie dei due gruppi</span></span>
<span><span class="st">  real&lt;lower=0&gt; sigma;                 // deviazione standard comune</span></span>
<span><span class="st">}</span></span>
<span><span class="st">model {</span></span>
<span><span class="st">  // Priors debolmente informative, coerenti con y standardizzata</span></span>
<span><span class="st">  mu    ~ normal(0, 1.5);</span></span>
<span><span class="st">  sigma ~ exponential(1);</span></span>
<span><span class="st"></span></span>
<span><span class="st">  // Likelihood: ogni y appartiene al suo gruppo g[i]</span></span>
<span><span class="st">  for (i in 1:N)</span></span>
<span><span class="st">    y[i] ~ normal(mu[g[i]], sigma);</span></span>
<span><span class="st">}</span></span>
<span><span class="st">generated quantities {</span></span>
<span><span class="st">  vector[N] log_lik;                   // log-verosimiglianze per PSIS-LOO</span></span>
<span><span class="st">  vector[N] y_rep;                     // repliche per posterior predictive checks</span></span>
<span><span class="st">  real diff_mu;                        // differenza tra le medie (Gruppo 2 - Gruppo 1)</span></span>
<span><span class="st"></span></span>
<span><span class="st">  // calcolo log_lik e repliche</span></span>
<span><span class="st">  for (i in 1:N) {</span></span>
<span><span class="st">    log_lik[i] = normal_lpdf(y[i] | mu[g[i]], sigma);</span></span>
<span><span class="st">    y_rep[i]   = normal_rng(mu[g[i]], sigma);</span></span>
<span><span class="st">  }</span></span>
<span><span class="st"></span></span>
<span><span class="st">  // differenza di interesse sostantivo:</span></span>
<span><span class="st">  // attenzione: per coerenza didattica, assumiamo g=1 -&gt; Controllo, g=2 -&gt; Mindfulness</span></span>
<span><span class="st">  diff_mu = mu[2] - mu[1];</span></span>
<span><span class="st">}</span></span>
<span><span class="st">"</span></span>
<span></span>
<span><span class="co"># Scrittura su disco e compilazione</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/files2.html">dir.exists</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"stan"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/files2.html">dir.create</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"stan"</span><span class="op">)</span>, recursive <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/writeLines.html">writeLines</a></span><span class="op">(</span><span class="va">stan_equal_var</span>, <span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"stan"</span>, <span class="st">"two_means_equal_var.stan"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">mod_eq</span> <span class="op">&lt;-</span> <span class="fu">cmdstan_model</span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"stan"</span>, <span class="st">"two_means_equal_var.stan"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Campionamento dalla posteriore</span></span>
<span><span class="va">fit_eq</span> <span class="op">&lt;-</span> <span class="va">mod_eq</span><span class="op">$</span><span class="fu">sample</span><span class="op">(</span></span>
<span>  data <span class="op">=</span> <span class="va">stan_data</span>,                    <span class="co"># creato nella sezione precedente</span></span>
<span>  seed <span class="op">=</span> <span class="fl">2025</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">4</span>, parallel_chains <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  iter_warmup <span class="op">=</span> <span class="fl">1000</span>, iter_sampling <span class="op">=</span> <span class="fl">1000</span>,</span>
<span>  refresh <span class="op">=</span> <span class="fl">0</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dopo l’esecuzione, verifichiamo a colpo d’occhio che i diagnostici principali siano buoni. Se R-hat è vicino a 1 e gli effective sample size sono adeguati, passiamo all’interpretazione. Usiamo direttamente le quantità generate nel blocco <code>generated quantities</code>, così lo studente vede continuità tra il modello e l’analisi a valle.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Differenza tra medie: estraiamo il vettore 'diff_mu'</span></span>
<span><span class="va">diff_draws</span> <span class="op">&lt;-</span> <span class="va">fit_eq</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span>variables <span class="op">=</span> <span class="st">"diff_mu"</span>, format <span class="op">=</span> <span class="st">"draws_matrix"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Riassunto compatto della posteriore: media, sd e intervallo di credibilità al 95%</span></span>
<span><span class="va">q025</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu">posterior</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/posterior/reference/quantile2.html">quantile2</a></span><span class="op">(</span><span class="va">x</span>, probs <span class="op">=</span> <span class="fl">0.025</span><span class="op">)</span></span>
<span><span class="va">q975</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu">posterior</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/posterior/reference/quantile2.html">quantile2</a></span><span class="op">(</span><span class="va">x</span>, probs <span class="op">=</span> <span class="fl">0.975</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">posterior</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/posterior/reference/draws_summary.html">summarize_draws</a></span><span class="op">(</span><span class="va">diff_draws</span>, <span class="va">mean</span>, <span class="va">sd</span>, <span class="va">q025</span>, <span class="va">q975</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 5</span></span>
<span><span class="co">#&gt;   variable   mean    sd   q2.5  q97.5</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 diff_mu  -0.536 0.148 -0.817 -0.243</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>L’oggetto <code>diff_mu</code> è la quantità sostantiva principale. Se nel nostro esempio è negativo, indica che il gruppo mindfulness ha, in media, affetto negativo più basso del controllo. Per rendere più esplicito il legame con l’interpretazione psicologica, calcoliamo la <em>probabilità a posteriori</em> che la differenza sia clinicamente rilevante secondo una ROPE scelta dal ricercatore. Per esemplificare, usiamo ±0.1 SD come regione di irrilevanza pratica; adattare questa soglia al contesto è parte del lavoro scientifico.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calcolo ROPE: probabilità a posteriori dentro/fuori la regione</span></span>
<span><span class="va">rope_lower</span> <span class="op">&lt;-</span> <span class="op">-</span><span class="fl">0.1</span></span>
<span><span class="va">rope_upper</span> <span class="op">&lt;-</span>  <span class="fl">0.1</span></span>
<span></span>
<span><span class="va">diff_vec</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">diff_draws</span><span class="op">[</span>, <span class="st">"diff_mu"</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="va">p_in_rope</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">diff_vec</span> <span class="op">&gt;</span> <span class="va">rope_lower</span> <span class="op">&amp;</span> <span class="va">diff_vec</span> <span class="op">&lt;</span> <span class="va">rope_upper</span><span class="op">)</span></span>
<span><span class="va">p_below</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">diff_vec</span> <span class="op">&lt;</span> <span class="va">rope_lower</span><span class="op">)</span></span>
<span><span class="va">p_above</span>    <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">diff_vec</span> <span class="op">&gt;</span> <span class="va">rope_upper</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">tibble</span><span class="op">(</span></span>
<span>  `P(diff in ROPE)`  <span class="op">=</span> <span class="va">p_in_rope</span>,</span>
<span>  `P(diff &lt; lower)`  <span class="op">=</span> <span class="va">p_below</span>,</span>
<span>  `P(diff &gt; upper)`  <span class="op">=</span> <span class="va">p_above</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 3</span></span>
<span><span class="co">#&gt;   `P(diff in ROPE)` `P(diff &lt; lower)` `P(diff &gt; upper)`</span></span>
<span><span class="co">#&gt;               &lt;dbl&gt;             &lt;dbl&gt;             &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1            0.0025             0.998                 0</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Queste probabilità mostrano qualcosa che il t-test non fornisce: non solo se la differenza è “diversa da zero”, ma se è <em>trascurabile</em>, <em>peggiorativa</em> o <em>migliorativa</em> oltre una soglia ritenuta rilevante. In un report didattico, affiancherei a queste quantità un confronto predittivo e una verifica grafica della coerenza del modello con i dati.</p>
<p>A questo punto abbiamo tutto ciò che serve per la lettura sostantiva: una <em>distribuzione a posteriori</em> della differenza tra le medie con intervallo di credibilità, una <em>probabilità a posteriori</em> di effetti rilevanti o trascurabili e un <em>controllo predittivo</em> che ci dice se il modello è in grado di generare dati verosimili. Nel passaggio successivo introdurremo il modello con <em>varianze distinte</em> e useremo PSIS-LOO per verificare se l’aumento di complessità offre un miglioramento predittivo stabile; se non lo offre, resteremo sul modello parsimonioso a varianza comune, senza perdere nulla sul piano interpretativo centrale.</p>
</section><section id="modello-a-varianze-distinte" class="level2" data-number="18.3"><h2 data-number="18.3" class="anchored" data-anchor-id="modello-a-varianze-distinte">
<span class="header-section-number">18.3</span> Modello a varianze distinte</h2>
<p>L’ipotesi qui è che i due gruppi possano avere <em>eterogeneità diversa</em>: ad esempio, il training di mindfulness potrebbe ridurre l’affetto negativo in media, ma con risposte più variabili tra i partecipanti rispetto al controllo. Stimiamo quindi <span class="math inline">\(\mu_1,\mu_2\)</span> e <em><span class="math inline">\(\sigma_1,\sigma_2\)</span></em>. Come prima, lavoriamo su dati standardizzati: priors <em>mu ~ Normal(0, 1.5)</em> e <em>sigma ~ Exponential(1)</em>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Modello Stan: varianze distinte</span></span>
<span><span class="va">stan_unequal_var</span> <span class="op">&lt;-</span> <span class="st">"</span></span>
<span><span class="st">data {</span></span>
<span><span class="st">  int&lt;lower=1&gt; N;                      // numero di osservazioni</span></span>
<span><span class="st">  int&lt;lower=2&gt; J;                      // numero di gruppi (qui: 2)</span></span>
<span><span class="st">  vector[N] y;                         // esito standardizzato</span></span>
<span><span class="st">  array[N] int&lt;lower=1, upper=J&gt; g;    // indice di gruppo</span></span>
<span><span class="st">}</span></span>
<span><span class="st">parameters {</span></span>
<span><span class="st">  vector[J] mu;                        // medie per gruppo</span></span>
<span><span class="st">  vector&lt;lower=0&gt;[J] sigma;            // sd specifica di gruppo</span></span>
<span><span class="st">}</span></span>
<span><span class="st">model {</span></span>
<span><span class="st">  // Priors debolmente informative</span></span>
<span><span class="st">  mu    ~ normal(0, 1.5);</span></span>
<span><span class="st">  sigma ~ exponential(1);</span></span>
<span><span class="st"></span></span>
<span><span class="st">  // Likelihood con sd per gruppo</span></span>
<span><span class="st">  for (i in 1:N)</span></span>
<span><span class="st">    y[i] ~ normal(mu[g[i]], sigma[g[i]]);</span></span>
<span><span class="st">}</span></span>
<span><span class="st">generated quantities {</span></span>
<span><span class="st">  vector[N] log_lik;                   // per PSIS-LOO</span></span>
<span><span class="st">  vector[N] y_rep;                     // posterior predictive checks</span></span>
<span><span class="st">  real diff_mu;                        // mu[2] - mu[1], Mindfulness - Controllo</span></span>
<span><span class="st">  real diff_sigma;                     // sigma[2] - sigma[1]</span></span>
<span><span class="st"></span></span>
<span><span class="st">  for (i in 1:N) {</span></span>
<span><span class="st">    log_lik[i] = normal_lpdf(y[i] | mu[g[i]], sigma[g[i]]);</span></span>
<span><span class="st">    y_rep[i]   = normal_rng(mu[g[i]], sigma[g[i]]);</span></span>
<span><span class="st">  }</span></span>
<span><span class="st"></span></span>
<span><span class="st">  diff_mu    = mu[2]    - mu[1];</span></span>
<span><span class="st">  diff_sigma = sigma[2] - sigma[1];</span></span>
<span><span class="st">}</span></span>
<span><span class="st">"</span></span>
<span></span>
<span><span class="co"># Scrittura su disco e compilazione</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/files2.html">dir.exists</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"stan"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/files2.html">dir.create</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"stan"</span><span class="op">)</span>, recursive <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/writeLines.html">writeLines</a></span><span class="op">(</span><span class="va">stan_unequal_var</span>, <span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"stan"</span>, <span class="st">"two_means_unequal_var.stan"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">mod_neq</span> <span class="op">&lt;-</span> <span class="fu">cmdstan_model</span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"stan"</span>, <span class="st">"two_means_unequal_var.stan"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Campionamento</span></span>
<span><span class="va">fit_neq</span> <span class="op">&lt;-</span> <span class="va">mod_neq</span><span class="op">$</span><span class="fu">sample</span><span class="op">(</span></span>
<span>  data <span class="op">=</span> <span class="va">stan_data</span>,    <span class="co"># come definito nella sezione precedente</span></span>
<span>  seed <span class="op">=</span> <span class="fl">2025</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">4</span>, parallel_chains <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  iter_warmup <span class="op">=</span> <span class="fl">1000</span>, iter_sampling <span class="op">=</span> <span class="fl">1000</span>,</span>
<span>  refresh <span class="op">=</span> <span class="fl">0</span></span>
<span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="lettura-sostantiva-dei-parametri" class="level3" data-number="18.3.1"><h3 data-number="18.3.1" class="anchored" data-anchor-id="lettura-sostantiva-dei-parametri">
<span class="header-section-number">18.3.1</span> Lettura sostantiva dei parametri</h3>
<p>Come prima, l’oggetto chiave è <em>diff_mu = mu[2] − mu[1]</em> (Mindfulness − Controllo). Qui però abbiamo anche <em>diff_sigma = sigma[2] − sigma[1]</em>, utile per capire se il training modifica l’eterogeneità delle risposte.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Estraiamo le quantità principali</span></span>
<span><span class="va">neq_draws_mu</span>     <span class="op">&lt;-</span> <span class="va">fit_neq</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span>variables <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"mu[1]"</span>, <span class="st">"mu[2]"</span>, <span class="st">"diff_mu"</span><span class="op">)</span>, format <span class="op">=</span> <span class="st">"draws_matrix"</span><span class="op">)</span></span>
<span><span class="va">neq_draws_sigma</span>  <span class="op">&lt;-</span> <span class="va">fit_neq</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span>variables <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"sigma[1]"</span>, <span class="st">"sigma[2]"</span>, <span class="st">"diff_sigma"</span><span class="op">)</span>, format <span class="op">=</span> <span class="st">"draws_matrix"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">q025</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu">posterior</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/posterior/reference/quantile2.html">quantile2</a></span><span class="op">(</span><span class="va">x</span>, probs <span class="op">=</span> <span class="fl">0.025</span><span class="op">)</span></span>
<span><span class="va">q975</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu">posterior</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/posterior/reference/quantile2.html">quantile2</a></span><span class="op">(</span><span class="va">x</span>, probs <span class="op">=</span> <span class="fl">0.975</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Riassunti posteriori</span></span>
<span><span class="fu">posterior</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/posterior/reference/draws_summary.html">summarize_draws</a></span><span class="op">(</span><span class="va">neq_draws_mu</span>,    <span class="va">mean</span>, <span class="va">sd</span>, <span class="va">q025</span>, <span class="va">q975</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 3 × 5</span></span>
<span><span class="co">#&gt;   variable   mean    sd   q2.5  q97.5</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 mu[1]     0.282 0.102  0.082  0.483</span></span>
<span><span class="co">#&gt; 2 mu[2]    -0.254 0.108 -0.461 -0.041</span></span>
<span><span class="co">#&gt; 3 diff_mu  -0.536 0.148 -0.826 -0.249</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">posterior</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/posterior/reference/draws_summary.html">summarize_draws</a></span><span class="op">(</span><span class="va">neq_draws_sigma</span>, <span class="va">mean</span>, <span class="va">sd</span>, <span class="va">q025</span>, <span class="va">q975</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 3 × 5</span></span>
<span><span class="co">#&gt;   variable    mean    sd   q2.5 q97.5</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 sigma[1]   0.940 0.076  0.804 1.105</span></span>
<span><span class="co">#&gt; 2 sigma[2]   1.003 0.076  0.871 1.165</span></span>
<span><span class="co">#&gt; 3 diff_sigma 0.063 0.107 -0.144 0.274</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Se <em>diff_mu</em> è negativo, il gruppo mindfulness ha in media affetto negativo più basso del controllo. Se <em>diff_sigma</em> è positivo, il gruppo mindfulness è più eterogeneo; se negativo, è più omogeneo. Questo secondo aspetto è spesso ignorato dal t-test, ma è scientificamente rilevante: un intervento può ridurre la media <em>e</em> cambiare la <em>variabilità</em> delle risposte.</p>
<p>Per continuità con la sezione precedente, calcoliamo anche la <em>ROPE</em> sulla differenza di medie. La ROPE serve a rispondere alla domanda: l’effetto è <em>praticamente</em> trascurabile?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># ROPE su diff_mu (stessa soglia di prima)</span></span>
<span><span class="va">rope_lower</span> <span class="op">&lt;-</span> <span class="op">-</span><span class="fl">0.1</span></span>
<span><span class="va">rope_upper</span> <span class="op">&lt;-</span>  <span class="fl">0.1</span></span>
<span></span>
<span><span class="va">diff_mu_vec</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">neq_draws_mu</span><span class="op">[</span>, <span class="st">"diff_mu"</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="va">p_in_rope_neq</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">diff_mu_vec</span> <span class="op">&gt;</span> <span class="va">rope_lower</span> <span class="op">&amp;</span> <span class="va">diff_mu_vec</span> <span class="op">&lt;</span> <span class="va">rope_upper</span><span class="op">)</span></span>
<span><span class="va">p_below_neq</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">diff_mu_vec</span> <span class="op">&lt;</span> <span class="va">rope_lower</span><span class="op">)</span></span>
<span><span class="va">p_above_neq</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">diff_mu_vec</span> <span class="op">&gt;</span> <span class="va">rope_upper</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">tibble</span><span class="op">(</span></span>
<span>  Model <span class="op">=</span> <span class="st">"Varianze distinte"</span>,</span>
<span>  `P(diff in ROPE)` <span class="op">=</span> <span class="va">p_in_rope_neq</span>,</span>
<span>  `P(diff &lt; lower)` <span class="op">=</span> <span class="va">p_below_neq</span>,</span>
<span>  `P(diff &gt; upper)` <span class="op">=</span> <span class="va">p_above_neq</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 4</span></span>
<span><span class="co">#&gt;   Model             `P(diff in ROPE)` `P(diff &lt; lower)` `P(diff &gt; upper)`</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;                         &lt;dbl&gt;             &lt;dbl&gt;             &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 Varianze distinte            0.0005             1.000                 0</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="confronto-predittivo-con-psis-loo" class="level3" data-number="18.3.2"><h3 data-number="18.3.2" class="anchored" data-anchor-id="confronto-predittivo-con-psis-loo">
<span class="header-section-number">18.3.2</span> Confronto predittivo con PSIS-LOO</h3>
<p>Ora confrontiamo <em>modello a varianza comune</em> (<code>fit_eq</code>) e <em>modello a varianze distinte</em> (<code>fit_neq</code>) usando ELPD (più alto è meglio). Guardiamo anche i <em>diagnostici Pareto-k</em>: idealmente &lt; 0.7. Se il vantaggio del modello più complesso è <em>piccolo e incerto</em>, restiamo sul modello parsimonioso; se è <em>chiaro e stabile</em>, accettiamo la maggiore complessità.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># LOO per entrambi i modelli</span></span>
<span><span class="va">loo_eq</span>  <span class="op">&lt;-</span> <span class="va">fit_eq</span><span class="op">$</span><span class="fu">loo</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">loo_neq</span> <span class="op">&lt;-</span> <span class="va">fit_neq</span><span class="op">$</span><span class="fu">loo</span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">loo_eq</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Computed from 4000 by 170 log-likelihood matrix.</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;          Estimate   SE</span></span>
<span><span class="co">#&gt; elpd_loo   -237.5  9.8</span></span>
<span><span class="co">#&gt; p_loo         3.1  0.5</span></span>
<span><span class="co">#&gt; looic       474.9 19.5</span></span>
<span><span class="co">#&gt; ------</span></span>
<span><span class="co">#&gt; MCSE of elpd_loo is 0.0.</span></span>
<span><span class="co">#&gt; MCSE and ESS estimates assume MCMC draws (r_eff in [0.8, 1.1]).</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; All Pareto k estimates are good (k &lt; 0.7).</span></span>
<span><span class="co">#&gt; See help('pareto-k-diagnostic') for details.</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">loo_neq</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Computed from 4000 by 170 log-likelihood matrix.</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;          Estimate   SE</span></span>
<span><span class="co">#&gt; elpd_loo   -238.3  9.8</span></span>
<span><span class="co">#&gt; p_loo         4.1  0.8</span></span>
<span><span class="co">#&gt; looic       476.6 19.6</span></span>
<span><span class="co">#&gt; ------</span></span>
<span><span class="co">#&gt; MCSE of elpd_loo is 0.0.</span></span>
<span><span class="co">#&gt; MCSE and ESS estimates assume MCMC draws (r_eff in [1.0, 1.3]).</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; All Pareto k estimates are good (k &lt; 0.7).</span></span>
<span><span class="co">#&gt; See help('pareto-k-diagnostic') for details.</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Confronto</span></span>
<span><span class="va">comp</span> <span class="op">&lt;-</span> <span class="fu">loo</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/loo/reference/loo_compare.html">loo_compare</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>equal_var <span class="op">=</span> <span class="va">loo_eq</span>, unequal_var <span class="op">=</span> <span class="va">loo_neq</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">comp_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="va">comp</span><span class="op">)</span></span>
<span><span class="va">comp_df</span></span>
<span><span class="co">#&gt;             elpd_diff se_diff elpd_loo se_elpd_loo p_loo se_p_loo looic</span></span>
<span><span class="co">#&gt; equal_var       0.000    0.00     -237        9.76  3.05    0.539   475</span></span>
<span><span class="co">#&gt; unequal_var    -0.856    0.61     -238        9.81  4.06    0.780   477</span></span>
<span><span class="co">#&gt;             se_looic</span></span>
<span><span class="co">#&gt; equal_var       19.5</span></span>
<span><span class="co">#&gt; unequal_var     19.6</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Per una decisione didatticamente “manuale”, possiamo usare una regola semplice: se |ΔELPD| &lt; 2 × SE(Δ), consideriamo i modelli <em>sostanzialmente equivalenti</em>; in tal caso scegliamo il <em>modello più semplice</em>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Piccolo helper decisionale</span></span>
<span><span class="va">delta_elpd</span> <span class="op">&lt;-</span> <span class="va">comp_df</span><span class="op">$</span><span class="va">elpd_diff</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>     <span class="co"># per la riga in cima</span></span>
<span><span class="va">se_delta</span>   <span class="op">&lt;-</span> <span class="va">comp_df</span><span class="op">$</span><span class="va">se_diff</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span>
<span></span>
<span><span class="va">decision</span> <span class="op">&lt;-</span> <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">delta_elpd</span><span class="op">)</span> <span class="op">&lt;</span> <span class="fl">2</span> <span class="op">*</span> <span class="va">se_delta</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="st">"Modelli predittivamente equivalenti: preferire la varianza comune per parsimonia."</span></span>
<span><span class="op">}</span> <span class="kw">else</span> <span class="kw">if</span> <span class="op">(</span><span class="va">delta_elpd</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="st">"Il modello a varianze distinte offre un vantaggio predittivo credibile: preferirlo."</span></span>
<span><span class="op">}</span> <span class="kw">else</span> <span class="op">{</span></span>
<span>  <span class="st">"Il modello a varianza comune è migliore: preferirlo."</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu">tibble</span><span class="op">(</span>Delta_ELPD <span class="op">=</span> <span class="va">delta_elpd</span>, SE_Delta <span class="op">=</span> <span class="va">se_delta</span>, Decisione <span class="op">=</span> <span class="va">decision</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 3</span></span>
<span><span class="co">#&gt;   Delta_ELPD SE_Delta Decisione                                           </span></span>
<span><span class="co">#&gt;        &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;                                               </span></span>
<span><span class="co">#&gt; 1          0        0 Il modello a varianza comune è migliore: preferirlo.</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="posterior-predictive-checks" class="level3" data-number="18.3.3"><h3 data-number="18.3.3" class="anchored" data-anchor-id="posterior-predictive-checks">
<span class="header-section-number">18.3.3</span> Posterior predictive checks</h3>
<p>Verifichiamo che i due modelli riproducano la forma della distribuzione osservata. Se <em>entrambi</em> vanno bene, la scelta si gioca sull’ELPD; se uno mostra discrepanze sistematiche, quello è il segnale più forte.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Equal variance</span></span>
<span><span class="va">yrep_eq</span> <span class="op">&lt;-</span> <span class="va">fit_eq</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span><span class="st">"y_rep"</span>, format <span class="op">=</span> <span class="st">"matrix"</span><span class="op">)</span></span>
<span><span class="fu">bayesplot</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/bayesplot/reference/PPC-distributions.html">ppc_dens_overlay</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">stan_data</span><span class="op">$</span><span class="va">y</span>, yrep <span class="op">=</span> <span class="va">yrep_eq</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">50</span>, <span class="op">]</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07_stan_two_means_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Unequal variances</span></span>
<span><span class="va">yrep_neq</span> <span class="op">&lt;-</span> <span class="va">fit_neq</span><span class="op">$</span><span class="fu">draws</span><span class="op">(</span><span class="st">"y_rep"</span>, format <span class="op">=</span> <span class="st">"matrix"</span><span class="op">)</span></span>
<span><span class="fu">bayesplot</span><span class="fu">::</span><span class="fu"><a href="https://mc-stan.org/bayesplot/reference/PPC-distributions.html">ppc_dens_overlay</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">stan_data</span><span class="op">$</span><span class="va">y</span>, yrep <span class="op">=</span> <span class="va">yrep_neq</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">50</span>, <span class="op">]</span><span class="op">)</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="07_stan_two_means_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
</section></section><section id="cosa-impariamo" class="level2" data-number="18.4"><h2 data-number="18.4" class="anchored" data-anchor-id="cosa-impariamo">
<span class="header-section-number">18.4</span> Cosa impariamo</h2>
<ol type="1">
<li><p><strong>Differenza tra le medie</strong>. La posteriore di <em>diff_mu</em> dice <em>di quanto</em> il training modifica l’affetto negativo medio, con <em>intervallo di credibilità</em>; la <em>ROPE</em> ci dice se l’effetto è <em>praticamente</em> trascurabile o rilevante. Questo è un vantaggio diretto rispetto al t-test, che non fornisce probabilità di “effetto rilevante” né gestisce l’equivalenza pratica in modo naturale.</p></li>
<li><p><strong>Differenza tra varianze</strong>. La posteriore di <em>diff_sigma</em> chiarisce se l’intervento modifica l’eterogeneità delle risposte: informazione spesso ignorata, ma importante in psicologia applicata.</p></li>
<li><p><strong>Capacità predittiva</strong>. Il <em>confronto PSIS-LOO</em> ci guida nella scelta del livello di complessità. Se ΔELPD è <em>piccolo e incerto</em>, preferiamo la <em>parsimonia</em> (varianza comune); se il vantaggio è <em>stabile e sostanziale</em>, ha senso adottare il modello con varianze distinte.</p></li>
</ol></section><section id="dalle-medie-di-gruppo-allanalisi-idiografica" class="level2" data-number="18.5"><h2 data-number="18.5" class="anchored" data-anchor-id="dalle-medie-di-gruppo-allanalisi-idiografica">
<span class="header-section-number">18.5</span> Dalle medie di gruppo all’analisi idiografica</h2>
<p>Finora ci siamo concentrati sulle <em>medie</em> di gruppo, chiedendoci quanto l’intervento mindfulness modifichi, in media, l’affetto negativo. Ma due gruppi con medie simili possono nascondere storie individuali molto diverse: c’è chi migliora nettamente, chi peggiora, chi non cambia. Per restituire queste differenze, spostiamo l’attenzione sul <em>singolo partecipante</em>.</p>
<p>In psicologia clinica, uno strumento tradizionale per valutare il cambiamento individuale è il <em>Reliable Change Index (RCI)</em>: si guarda la differenza tra post e pre e la si rapporta all’errore atteso della differenza. Se la differenza “supera la soglia”, il cambiamento è detto affidabile <span class="citation" data-cites="jacobson1991clinical">(<a href="#ref-jacobson1991clinical" role="doc-biblioref">Jacobson &amp; Truax, 1991</a>)</span>. È un’idea semplice e utile, ma lascia fuori due elementi che per noi sono centrali: <em>l’incertezza</em> e la <em>rilevanza pratica</em> del cambiamento. In termini bayesiani, invece di un verdetto sì/no, vogliamo stimare <em>quanto è plausibile</em> che il cambiamento di un individuo sia nullo, trascurabile, o clinicamente rilevante.</p>
<p>Lavoreremo quindi con una piccola estensione bayesiana dell’RCI: per un singolo soggetto, consideriamo la differenza <span class="math inline">\(\Delta = \text{post} - \text{pre}\)</span> e, nota l’incertezza di misura del test (che riassumiamo tramite lo <em>standard error of measurement</em>, <em>SEM</em>), costruiamo la <em>distribuzione a posteriori</em> di <span class="math inline">\(\Delta\)</span>. Da quella distribuzione potremo leggere quantità davvero utili: la probabilità che <span class="math inline">\(\Delta\)</span> sia <em>trascurabile</em> (dentro una <em>ROPE</em>) oppure <em>rilevante</em> (oltre una soglia clinica <span class="math inline">\(\tau\)</span>).</p>
<p>La logica è la stessa usata a livello di gruppo con la differenza tra medie: là guardavamo <span class="math inline">\(\mu_2 - \mu_1\)</span> e una ROPE attorno a zero; qui guardiamo <span class="math inline">\(\Delta\)</span> per una persona, con una ROPE e una soglia <span class="math inline">\(\tau\)</span> espresse nella <em>stessa metrica</em> che abbiamo usato in precedenza in questo capitolo (unità di deviazione standard).</p>
<section id="un-modello-bayesiano-minimale-per-la-stima-del-cambiamento-individuale-rci-bayesiano" class="level3" data-number="18.5.1"><h3 data-number="18.5.1" class="anchored" data-anchor-id="un-modello-bayesiano-minimale-per-la-stima-del-cambiamento-individuale-rci-bayesiano">
<span class="header-section-number">18.5.1</span> Un modello bayesiano minimale per la stima del cambiamento individuale (RCI bayesiano)</h3>
<p>Il modello che presentiamo rappresenta una versione volutamente semplificata del <em>reliable change index</em> (RCI) in chiave bayesiana. L’obiettivo è introdurre lo studente a questi concetti attraverso un esempio trasparente e computazionalmente immediato. La scelta di un modello Normale–Normale in forma chiusa permette infatti di preservare la chiarezza espositiva senza rinunciare alla completezza concettuale.</p>
<section id="struttura-del-modello" class="level4" data-number="18.5.1.1"><h4 data-number="18.5.1.1" class="anchored" data-anchor-id="struttura-del-modello">
<span class="header-section-number">18.5.1.1</span> Struttura del modello</h4>
<p>L’input del modello è costituito dai punteggi pre-test e post-test del singolo partecipante, insieme alla deviazione standard e all’affidabilità dello strumento. L’output è la distribuzione a posteriori del cambiamento individuale Δ, dalla quale possiamo derivare tre probabilità clinicamente rilevanti. Tutti i calcoli vengono condotti nella stessa metrica standardizzata (unità di deviazione standard) adottata per le analisi di gruppo.</p>
<p>La specificazione è la seguente:</p>
<ul>
<li>
<p><em>Verosimiglianza</em>: la differenza osservata tra post e pre (D) è distribuita come</p>
<p><span class="math display">\[
D \sim \mathcal{N}(\Delta, \text{SEdiff}^2)
\]</span> dove SEdiff è l’errore standard della differenza.</p>
</li>
<li>
<p><em>Prior</em>: il vero cambiamento Δ segue una distribuzione Normale centrata in 0 con deviazione standard pari a <code>prior_sd_delta</code>, a esprimere l’incertezza iniziale sulla sua entità:</p>
<p><span class="math display">\[
\Delta \sim \mathcal{N}(0, \text{prior\_sd\_delta}^2).
\]</span> Per combinazione coniugata, la distribuzione a posteriori di Δ risulta ancora Normale, con parametri calcolabili tramite le formule standard di aggiornamento bayesiano.</p>
</li>
</ul></section><section id="lo-standard-error-della-differenza" class="level4" data-number="18.5.1.2"><h4 data-number="18.5.1.2" class="anchored" data-anchor-id="lo-standard-error-della-differenza">
<span class="header-section-number">18.5.1.2</span> Lo standard error della differenza</h4>
<p>Elemento centrale del modello è il calcolo dello <em>standard error della differenza (SEdiff)</em>, che riflette l’incertezza nella stima del cambiamento individuale tenendo conto dell’affidabilità del test. Si procede così:</p>
<ol type="1">
<li>
<p>si calcola l’errore standard di misura (SEM) come</p>
<p><span class="math display">\[
\text{SEM} = SD \times \sqrt{1 - \text{reliability}},
\]</span> dove <em>SD</em> è la deviazione standard del test;</p>
</li>
<li>
<p>si ottiene quindi</p>
<p><span class="math display">\[
\text{SEdiff} = \sqrt{2} \times \text{SEM},
\]</span> assumendo che pre e post abbiano la stessa metrica e affidabilità.</p>
</li>
</ol></section><section id="probabilità-di-interesse-clinico" class="level4" data-number="18.5.1.3"><h4 data-number="18.5.1.3" class="anchored" data-anchor-id="probabilità-di-interesse-clinico">
<span class="header-section-number">18.5.1.3</span> Probabilità di interesse clinico</h4>
<p>Dalla distribuzione a posteriori di Δ si ricavano tre probabilità sostantive:</p>
<ul>
<li>la probabilità che Δ cada nella <em>ROPE</em> (es. ±0.10 SD), cioè che il cambiamento sia trascurabile;</li>
<li>la probabilità che Δ superi una soglia positiva τ (es. +0.30 SD), indicativa di un miglioramento clinicamente rilevante;</li>
<li>la probabilità che Δ sia minore di –τ, indicativa di un peggioramento rilevante.</li>
</ul>
<p>Queste probabilità si ottengono integrando la distribuzione a posteriori sugli intervalli corrispondenti.</p>
</section><section id="esempio-numerico" class="level4" data-number="18.5.1.4"><h4 data-number="18.5.1.4" class="anchored" data-anchor-id="esempio-numerico">
<span class="header-section-number">18.5.1.4</span> Esempio numerico</h4>
<p>Applichiamo il modello a un soggetto del gruppo sperimentale in uno studio sull’intervento mindfulness. I suoi punteggi sono: pre = 0.40, post = 0.05 (espressi in SD). Assumiamo SD = valore campionario dell’intero dataset e un’affidabilità del test pari a 0.85.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># ------------------------------------------------------------</span></span>
<span><span class="co"># RCI bayesiano (versione semplice, chiusa-forma)</span></span>
<span><span class="co"># ------------------------------------------------------------</span></span>
<span><span class="co"># Likelihood:  D = post - pre  ~ Normal(Delta, SEdiff^2)</span></span>
<span><span class="co"># Prior:       Delta ~ Normal(0, prior_sd_delta^2)</span></span>
<span><span class="co"># Posterior:   Delta | D ~ Normal(m_post, s_post^2)</span></span>
<span><span class="co"># ------------------------------------------------------------</span></span>
<span></span>
<span><span class="va">rci_bayes</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">pre</span>, <span class="va">post</span>,</span>
<span>                      <span class="va">test_sd</span>, <span class="va">reliability</span>,</span>
<span>                      <span class="va">rope_width</span> <span class="op">=</span> <span class="fl">0.10</span>,   <span class="co"># ROPE ±0.10 SD (coerente con capitolo)</span></span>
<span>                      <span class="va">tau_clin</span>   <span class="op">=</span> <span class="fl">0.30</span>,   <span class="co"># soglia clinica 0.30 SD (esempio)</span></span>
<span>                      <span class="va">prior_sd_delta</span> <span class="op">=</span> <span class="fl">0.60</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="co"># 1) Differenza osservata</span></span>
<span>  <span class="va">D</span> <span class="op">&lt;-</span> <span class="va">post</span> <span class="op">-</span> <span class="va">pre</span></span>
<span>  </span>
<span>  <span class="co"># 2) SEM e SE della differenza</span></span>
<span>  <span class="co">#    SEM = SD * sqrt(1 - reliability)</span></span>
<span>  <span class="va">SEM</span>    <span class="op">&lt;-</span> <span class="va">test_sd</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span> <span class="op">-</span> <span class="va">reliability</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">SEdiff</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">SEM</span><span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="va">SEM</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span>  <span class="co"># ipotesi: stessa metrica/affidabilità a pre e post</span></span>
<span>  </span>
<span>  <span class="co"># 3) Prior e posteriori (Normale–Normale)</span></span>
<span>  <span class="va">s0</span> <span class="op">&lt;-</span> <span class="va">prior_sd_delta</span></span>
<span>  <span class="va">s</span>  <span class="op">&lt;-</span> <span class="va">SEdiff</span></span>
<span>  </span>
<span>  <span class="va">s2_post</span> <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">/</span> <span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="va">s0</span><span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fl">1</span><span class="op">/</span><span class="va">s</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span></span>
<span>  <span class="va">s_post</span>  <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">s2_post</span><span class="op">)</span></span>
<span>  <span class="va">m_post</span>  <span class="op">&lt;-</span> <span class="op">(</span><span class="va">s2_post</span> <span class="op">/</span> <span class="va">s</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">*</span> <span class="va">D</span></span>
<span>  </span>
<span>  <span class="co"># 4) Probabilità di interesse</span></span>
<span>  <span class="va">p_in_rope</span>   <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span> <span class="va">rope_width</span>, mean <span class="op">=</span> <span class="va">m_post</span>, sd <span class="op">=</span> <span class="va">s_post</span><span class="op">)</span> <span class="op">-</span></span>
<span>                 <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="op">-</span><span class="va">rope_width</span>, mean <span class="op">=</span> <span class="va">m_post</span>, sd <span class="op">=</span> <span class="va">s_post</span><span class="op">)</span></span>
<span>  <span class="va">p_gt_tau</span>    <span class="op">&lt;-</span> <span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="va">tau_clin</span>,  mean <span class="op">=</span> <span class="va">m_post</span>, sd <span class="op">=</span> <span class="va">s_post</span><span class="op">)</span></span>
<span>  <span class="va">p_lt_neg_tau</span><span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="op">-</span><span class="va">tau_clin</span>,     mean <span class="op">=</span> <span class="va">m_post</span>, sd <span class="op">=</span> <span class="va">s_post</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>    observed_diff   <span class="op">=</span> <span class="va">D</span>,</span>
<span>    SEM             <span class="op">=</span> <span class="va">SEM</span>,</span>
<span>    SEdiff          <span class="op">=</span> <span class="va">SEdiff</span>,</span>
<span>    prior_sd_delta  <span class="op">=</span> <span class="va">s0</span>,</span>
<span>    post_mean       <span class="op">=</span> <span class="va">m_post</span>,</span>
<span>    post_sd         <span class="op">=</span> <span class="va">s_post</span>,</span>
<span>    rope            <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="va">rope_width</span>, <span class="va">rope_width</span><span class="op">)</span>,</span>
<span>    tau_clin        <span class="op">=</span> <span class="va">tau_clin</span>,</span>
<span>    probs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>      P_in_ROPE         <span class="op">=</span> <span class="va">p_in_rope</span>,</span>
<span>      P_diff_gt_tau     <span class="op">=</span> <span class="va">p_gt_tau</span>,</span>
<span>      P_diff_lt_neg_tau <span class="op">=</span> <span class="va">p_lt_neg_tau</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">}</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># 'df' proviene dalle sezioni precedenti del capitolo (score in SD naturali)</span></span>
<span><span class="va">test_sd</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">score</span><span class="op">)</span></span>
<span></span>
<span><span class="va">res_demo</span> <span class="op">&lt;-</span> <span class="fu">rci_bayes</span><span class="op">(</span></span>
<span>  pre  <span class="op">=</span> <span class="fl">0.40</span>,</span>
<span>  post <span class="op">=</span> <span class="fl">0.05</span>,</span>
<span>  test_sd     <span class="op">=</span> <span class="va">test_sd</span>,</span>
<span>  reliability <span class="op">=</span> <span class="fl">0.85</span>,</span>
<span>  rope_width  <span class="op">=</span> <span class="fl">0.10</span>,  <span class="co"># ROPE ±0.10 SD (trascurabile)</span></span>
<span>  tau_clin    <span class="op">=</span> <span class="fl">0.30</span>,  <span class="co"># soglia clinica 0.30 SD (rilevante)</span></span>
<span>  prior_sd_delta <span class="op">=</span> <span class="fl">0.60</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sprintf.html">sprintf</a></span><span class="op">(</span></span>
<span>  <span class="st">"\nRCI bayesiano (soggetto esempio)\n---------------------------------\nDiff. osservata (post-pre): %.3f\nSEM: %.3f | SE diff: %.3f\nPosterior Delta ~ Normal(%.3f, %.3f^2)\nROPE: [%.2f, %.2f] | tau_clin: ±%.2f\nP(Delta in ROPE)      = %.3f\nP(Delta &gt;  tau_clin)  = %.3f\nP(Delta &lt; -tau_clin)  = %.3f\n"</span>,</span>
<span>  <span class="va">res_demo</span><span class="op">$</span><span class="va">observed_diff</span>, <span class="va">res_demo</span><span class="op">$</span><span class="va">SEM</span>, <span class="va">res_demo</span><span class="op">$</span><span class="va">SEdiff</span>,</span>
<span>  <span class="va">res_demo</span><span class="op">$</span><span class="va">post_mean</span>, <span class="va">res_demo</span><span class="op">$</span><span class="va">post_sd</span>,</span>
<span>  <span class="va">res_demo</span><span class="op">$</span><span class="va">rope</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="va">res_demo</span><span class="op">$</span><span class="va">rope</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>, <span class="va">res_demo</span><span class="op">$</span><span class="va">tau_clin</span>,</span>
<span>  <span class="va">res_demo</span><span class="op">$</span><span class="va">probs</span><span class="op">[</span><span class="st">"P_in_ROPE"</span><span class="op">]</span>, <span class="va">res_demo</span><span class="op">$</span><span class="va">probs</span><span class="op">[</span><span class="st">"P_diff_gt_tau"</span><span class="op">]</span>, <span class="va">res_demo</span><span class="op">$</span><span class="va">probs</span><span class="op">[</span><span class="st">"P_diff_lt_neg_tau"</span><span class="op">]</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; RCI bayesiano (soggetto esempio)</span></span>
<span><span class="co">#&gt; ---------------------------------</span></span>
<span><span class="co">#&gt; Diff. osservata (post-pre): -0.350</span></span>
<span><span class="co">#&gt; SEM: 0.384 | SE diff: 0.543</span></span>
<span><span class="co">#&gt; Posterior Delta ~ Normal(-0.192, 0.403^2)</span></span>
<span><span class="co">#&gt; ROPE: [-0.10, 0.10] | tau_clin: ±0.30</span></span>
<span><span class="co">#&gt; P(Delta in ROPE)      = 0.175</span></span>
<span><span class="co">#&gt; P(Delta &gt;  tau_clin)  = 0.111</span></span>
<span><span class="co">#&gt; P(Delta &lt; -tau_clin)  = 0.395</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Il modello produce:</p>
<ul>
<li>differenza osservata: –0.350 SD;</li>
<li>SEM = 0.384, SEdiff = 0.543;</li>
<li>distribuzione a posteriori di Δ ~ Normal(–0.192, 0.403²).</li>
</ul>
<p>In termini clinici:</p>
<ul>
<li>P(Δ in ROPE) = 0.175 → cambiamento probabilmente non trascurabile;</li>
<li>P(Δ &gt; 0.30) = 0.111 → miglioramento poco plausibile;</li>
<li>P(Δ &lt; –0.30) = 0.395 → peggioramento moderato plausibile.</li>
</ul></section><section id="interpretazione" class="level4" data-number="18.5.1.5"><h4 data-number="18.5.1.5" class="anchored" data-anchor-id="interpretazione">
<span class="header-section-number">18.5.1.5</span> Interpretazione</h4>
<p>La stima bayesiana attenua la differenza osservata, portandola da –0.350 a –0.192 SD: un effetto di regolarizzazione tipico dell’approccio bayesiano, che combina dati e informazione a priori. Le probabilità a posteriori rendono chiaro che il cambiamento del soggetto non è facilmente classificabile come miglioramento o stabilità: la possibilità di un peggioramento moderato risulta la più consistente, ma non esclusiva.</p>
<p>Questo esempio mette in evidenza il valore dell’approccio bayesiano: non un singolo verdetto, ma una mappa probabilistica delle ipotesi clinicamente rilevanti. La trasparenza del modello consente anche di riflettere criticamente sulla scelta dei parametri (affidabilità, SD, ampiezza della ROPE e soglia τ), che devono essere motivati in base a evidenze empiriche e convenzioni cliniche. In questo modo, lo stesso schema logico che abbiamo applicato ai gruppi diventa disponibile anche per l’analisi del singolo: non un verdetto dicotomico, ma una distribuzione di probabilità che rende esplicita l’incertezza e la rilevanza clinica del cambiamento.</p>
</section><section id="prospettive" class="level4" data-number="18.5.1.6"><h4 data-number="18.5.1.6" class="anchored" data-anchor-id="prospettive">
<span class="header-section-number">18.5.1.6</span> Prospettive</h4>
<p>La versione proposta ha finalità introduttive. In un contesto di ricerca avanzato, il modello in forma chiusa può essere sostituito da implementazioni in linguaggio <em>Stan</em>, che consentono di modellare esplicitamente gli errori di misura e di passare a modelli gerarchici capaci di integrare stime individuali e differenze di gruppo. La coerenza concettuale dell’approccio bayesiano si manifesta così su più livelli: stimare differenze tra gruppi e stimare cambiamenti individuali seguono lo stesso schema logico, garantendo un quadro inferenziale unificato e potente per la ricerca psicologica.</p>
</section></section></section><section id="riflessioni-conclusive" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="riflessioni-conclusive">Riflessioni conclusive</h2>
<p>L’analisi sviluppata in questo capitolo mette in evidenza i punti di forza dell’approccio bayesiano al confronto tra gruppi e, più in generale, alla valutazione del cambiamento psicologico. La quantità centrale non è più un singolo numero o un p-value, ma l’intera <em>distribuzione a posteriori</em> delle differenze che ci interessano. È questa distribuzione che racconta la storia sostantiva: nel nostro esempio, di quanto il gruppo mindfulness differisce, in media, dal gruppo di controllo. Non otteniamo soltanto una stima puntuale, ma anche l’incertezza che accompagna ogni possibile valore della differenza. Questo ci consente di andare oltre il verdetto dicotomico “c’è / non c’è differenza” e di ragionare invece in termini di <em>gradazioni di plausibilità</em>.</p>
<p>Un secondo aspetto riguarda la possibilità di valutare la <em>rilevanza pratica</em> degli effetti. Introdurre una <em>region of practical equivalence</em> (ROPE) ci permette di distinguere tra differenze che, pur statisticamente rilevabili, sono trascurabili dal punto di vista psicologico e differenze che invece hanno un impatto sostantivo. In questo modo possiamo rispondere a domande clinicamente significative, come “quanto è probabile che l’effetto sia non solo diverso da zero, ma anche sufficientemente grande da essere rilevante?”.</p>
<p>Il confronto tra modelli con varianza comune e modelli con varianze distinte ci ha mostrato inoltre come ogni assunzione statistica vada valutata <em>in termini predittivi</em>. Grazie al criterio ELPD stimato con PSIS-LOO abbiamo potuto verificare se la maggiore complessità introdotta dal modello con varianze distinte migliorasse davvero la capacità di predire dati simili ai nostri. Quando il guadagno è minimo, la parsimonia suggerisce di mantenere il modello più semplice; quando invece il vantaggio predittivo è chiaro, si giustifica la maggiore complessità. Questo modo di ragionare è più trasparente e più vicino alla logica scientifica rispetto all’alternativa frequentista, in cui le scelte modellistiche sono spesso delegate a test poco interpretabili.</p>
<p>Il passaggio all’analisi ideografica, con la versione bayesiana del <em>Reliable Change Index</em>, amplia ulteriormente la prospettiva. Se l’analisi di gruppo ci dice cosa accade <em>in media</em>, l’analisi del cambiamento individuale ci mostra quanto un intervento sia stato efficace per ciascun partecipante. Qui il vantaggio del ragionamento bayesiano è evidente: invece di un verdetto rigido (“cambiamento affidabile sì/no”), possiamo stimare la probabilità che un miglioramento sia trascurabile o clinicamente rilevante per il singolo individuo. In questo modo, i due livelli di analisi — collettivo e individuale — non sono più separati, ma si integrano in un quadro unitario.</p>
<p>In sintesi, l’approccio bayesiano ci insegna che l’inferenza non riguarda tanto il respingere o meno un’ipotesi nulla, quanto il descrivere la <em>plausibilità di diversi scenari</em> e collegarla al significato psicologico dei dati. Ciò vale tanto per le differenze tra gruppi quanto per i cambiamenti nei singoli individui. Questa prospettiva porta la statistica più vicina alle domande reali della psicologia: non solo “esiste un effetto?”, ma “quanto è grande?”, “quanto è incerto?”, “quanto è rilevante per la pratica clinica o applicativa?”, e perfino “quanto è plausibile che questo singolo paziente abbia beneficiato dell’intervento?”. È qui che l’approccio bayesiano mostra il suo valore aggiunto, trasformando l’analisi dei dati in uno strumento flessibile, trasparente e sostantivamente informativo.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Informazioni sull'ambiente di sviluppo">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Informazioni sull’ambiente di sviluppo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.5.1 (2025-06-13)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin20</span></span>
<span><span class="co">#&gt; Running under: macOS Sequoia 15.6.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C/UTF-8/C/C/C/C</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Rome</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] forcats_1.0.0         cmdstanr_0.9.0        pillar_1.11.0        </span></span>
<span><span class="co">#&gt;  [4] tinytable_0.13.0      patchwork_1.3.2       ggdist_3.3.3         </span></span>
<span><span class="co">#&gt;  [7] tidybayes_3.0.7       bayesplot_1.14.0      ggplot2_3.5.2        </span></span>
<span><span class="co">#&gt; [10] reliabilitydiag_0.2.1 priorsense_1.1.1      posterior_1.6.1      </span></span>
<span><span class="co">#&gt; [13] loo_2.8.0             rstan_2.32.7          StanHeaders_2.32.10  </span></span>
<span><span class="co">#&gt; [16] brms_2.22.0           Rcpp_1.1.0            sessioninfo_1.2.3    </span></span>
<span><span class="co">#&gt; [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    </span></span>
<span><span class="co">#&gt; [22] modelr_0.1.11         tibble_3.3.0          dplyr_1.1.4          </span></span>
<span><span class="co">#&gt; [25] tidyr_1.3.1           rio_1.2.3             here_1.0.1           </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;  [1] gridExtra_2.3         inline_0.3.21         sandwich_3.1-1       </span></span>
<span><span class="co">#&gt;  [4] rlang_1.1.6           magrittr_2.0.3        multcomp_1.4-28      </span></span>
<span><span class="co">#&gt;  [7] snakecase_0.11.1      compiler_4.5.1        reshape2_1.4.4       </span></span>
<span><span class="co">#&gt; [10] systemfonts_1.2.3     vctrs_0.6.5           stringr_1.5.1        </span></span>
<span><span class="co">#&gt; [13] pkgconfig_2.0.3       arrayhelpers_1.1-0    fastmap_1.2.0        </span></span>
<span><span class="co">#&gt; [16] backports_1.5.0       labeling_0.4.3        utf8_1.2.6           </span></span>
<span><span class="co">#&gt; [19] rmarkdown_2.29        ps_1.9.1              ragg_1.5.0           </span></span>
<span><span class="co">#&gt; [22] purrr_1.1.0           xfun_0.53             cachem_1.1.0         </span></span>
<span><span class="co">#&gt; [25] jsonlite_2.0.0        broom_1.0.9           parallel_4.5.1       </span></span>
<span><span class="co">#&gt; [28] R6_2.6.1              stringi_1.8.7         RColorBrewer_1.1-3   </span></span>
<span><span class="co">#&gt; [31] lubridate_1.9.4       estimability_1.5.1    knitr_1.50           </span></span>
<span><span class="co">#&gt; [34] zoo_1.8-14            pacman_0.5.1          Matrix_1.7-4         </span></span>
<span><span class="co">#&gt; [37] splines_4.5.1         timechange_0.3.0      tidyselect_1.2.1     </span></span>
<span><span class="co">#&gt; [40] abind_1.4-8           yaml_2.3.10           codetools_0.2-20     </span></span>
<span><span class="co">#&gt; [43] curl_7.0.0            processx_3.8.6        pkgbuild_1.4.8       </span></span>
<span><span class="co">#&gt; [46] plyr_1.8.9            lattice_0.22-7        withr_3.0.2          </span></span>
<span><span class="co">#&gt; [49] bridgesampling_1.1-2  coda_0.19-4.1         evaluate_1.0.5       </span></span>
<span><span class="co">#&gt; [52] survival_3.8-3        RcppParallel_5.1.11-1 tensorA_0.36.2.1     </span></span>
<span><span class="co">#&gt; [55] checkmate_2.3.3       stats4_4.5.1          distributional_0.5.0 </span></span>
<span><span class="co">#&gt; [58] generics_0.1.4        rprojroot_2.1.1       rstantools_2.5.0     </span></span>
<span><span class="co">#&gt; [61] scales_1.4.0          xtable_1.8-4          glue_1.8.0           </span></span>
<span><span class="co">#&gt; [64] emmeans_1.11.2-8      tools_4.5.1           data.table_1.17.8    </span></span>
<span><span class="co">#&gt; [67] mvtnorm_1.3-3         grid_4.5.1            QuickJSR_1.8.0       </span></span>
<span><span class="co">#&gt; [70] colorspace_2.1-1      nlme_3.1-168          cli_3.6.5            </span></span>
<span><span class="co">#&gt; [73] textshaping_1.0.3     svUnit_1.0.8          Brobdingnag_1.2-9    </span></span>
<span><span class="co">#&gt; [76] V8_7.0.0              gtable_0.3.6          digest_0.6.37        </span></span>
<span><span class="co">#&gt; [79] TH.data_1.1-4         htmlwidgets_1.6.4     farver_2.1.2         </span></span>
<span><span class="co">#&gt; [82] memoise_2.0.1         htmltools_0.5.8.1     lifecycle_1.0.4      </span></span>
<span><span class="co">#&gt; [85] MASS_7.3-65</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="bibliografia" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="bibliografia">Bibliografia</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-jacobson1991clinical" class="csl-entry" role="listitem">
Jacobson, N. S., &amp; Truax, P. (1991). Clinical significance: A statistical approach to defining meaningful change in psychotherapy research. <em>Journal of Consulting and Clinical Psychology</em>, <em>59</em>(1), 12–19. <a href="https://doi.org/10.1037/0022-006X.59.1.12">https://doi.org/10.1037/0022-006X.59.1.12</a>
</div>
<div id="ref-kruschke2013bayesian" class="csl-entry" role="listitem">
Kruschke, J. K. (2013). Bayesian estimation supersedes the t test. <em>Journal of Experimental Psychology: General</em>, <em>142</em>(2), 573–603.
</div>
</div>
</section></main><!-- /main --><script>
document.body.classList.add('classic-book');
document.addEventListener('DOMContentLoaded', function() {
  const paragraphs = document.querySelectorAll('p');
  paragraphs.forEach(p => {
    if (p.textContent.length > 200) {
      p.style.hyphens = 'auto';
      p.style.hyphenateCharacter = '-';
    }
  });
  const headings = document.querySelectorAll('h1, h2, h3, h4, h5, h6');
  headings.forEach(h => {
    h.style.fontFeatureSettings = '"liga" 1, "dlig" 1, "smcp" 1';
  });
});
</script><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiato!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiato!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ccaudek\.github\.io\/utet-companion\/intro\.html");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/mcmc/06_stan_odds_ratio_stan.html" class="pagination-link" aria-label="Analisi bayesiana dell'odds ratio">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Analisi bayesiana dell’odds ratio</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/mcmc/08_stan_poisson_model_1.html" class="pagination-link" aria-label="Modello di Poisson">
        <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Modello di Poisson</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Metodi bayesiani in psicologia — Companion site</strong>.<br>
Materiali di accompagnamento e approfondimento al manuale UTET.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ccaudek/utet-companion/blob/main/chapters/mcmc/07_stan_two_means.qmd" class="toc-action"><i class="bi bi-github"></i>Mostra il codice</a></li><li><a href="https://github.com/ccaudek/utet-companion/issues/new" class="toc-action"><i class="bi empty"></i>Segnala un problema</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>