{
  "hash": "037cc573511c84551abeb1fc55a6ce0b",
  "result": {
    "engine": "knitr",
    "markdown": "# Inferenza su una media: il modello a sola intercetta {#sec-mcmc-one-mean}\n\nNei capitoli precedenti abbiamo definito il modello lineare mediante una media condizionata che varia in funzione di uno o più predittori. Il caso più semplice si ottiene eliminando tutti i predittori:\n\n$$\nY_i \\sim \\operatorname{Normal}(\\mu, \\sigma).\n$$\n\nIl parametro $\\mu$ rappresenta il valore medio della popolazione descritta dal modello, mentre lo scalare positivo $\\sigma$ misura la variabilità delle osservazioni individuali attorno a tale media. In termini di regressione, questo è un *modello a sola intercetta*:\n\n$$\nY_i = \\alpha + \\varepsilon_i, \\qquad \\varepsilon_i \\sim \\operatorname{Normal}(0, \\sigma)\n$$\nin cui il coefficiente $\\alpha$ coincide con la media $\\mu$. Nella sintassi di `brms`, questa componente sistematica si esprime con la formula `y ~ 1`.\n\nSebbene minimale, il modello contiene già tutti gli elementi del workflow bayesiano: una funzione di verosimiglianza, prior espliciti, una distribuzione a posteriori, quantità predittive e controlli di adeguatezza. Isolare questa struttura elementare aiuta a distinguere tre quantità che vengono spesso confuse:\n\n* **La media della popolazione ($\\mu$ o $\\alpha$):** il baricentro teorico stimato dal modello;\n* **La variabilità tra individui ($\\sigma$):** l'eterogeneità biologica o psicometrica del campione;\n* **La stima di una nuova osservazione ($y_{\\text{new}}$):** la previsione su un singolo soggetto futuro, che deve incorporare sia l'incertezza sulla media sia la dispersione residua.\n\n::: {.callout-important appearance=\"minimal\" .chapter-status}\n**Da sapere.** L'inferenza su una media è un modello lineare a sola intercetta. Il parametro $\\mu$ descrive il centro della popolazione modellata, mentre $\\sigma$ descrive la dispersione delle osservazioni individuali. La posterior di $\\mu$ e la distribuzione predittiva di una nuova osservazione rispondono a domande diverse.\n\n**Da saper fare.** Tradurre una domanda descrittiva in un modello `y ~ 1`; formulare prior sulla scala osservata; eseguire controlli predittivi a priori e a posteriori; adattare il modello con `brms`; interpretare $\\mu$, $\\sigma$, probabilità rispetto a soglie sostantive e previsioni per nuove osservazioni; comunicare risultati e limiti di generalizzazione.\n\n**Approfondimento facoltativo.** Il confronto tra verosimiglianza normale e Student-$t$, l'analisi di sensibilità ai prior e la valutazione mirata delle code possono essere rimandati in una prima lettura. Nel percorso essenziale è sufficiente comprendere il modello a sola intercetta, distinguere parametro medio e variabilità individuale e seguire il workflow completo.\n\n[Che cosa significano queste etichette?](../../guida-al-manuale.qmd#sec-percorsi-lettura)\n:::\n\n::: {.callout-note title=\"Obiettivi del capitolo\"}\nAl termine del capitolo dovresti essere in grado di:\n\n- riconoscere la stima di una media come un modello lineare a sola intercetta;\n- distinguere il parametro di posizione $\\mu$ dal parametro di dispersione $\\sigma$;\n- formulare prior plausibili sulla scala originale della variabile;\n- calibrare tali prior mediante simulazioni predittive a priori;\n- interpretare la distribuzione a posteriori della media;\n- distinguere l'incertezza sulla media dalla distribuzione predittiva di una nuova osservazione;\n- valutare quando una verosimiglianza Student-$t$ possa essere preferibile a una normale;\n- formulare conclusioni probabilistiche coerenti con il modello e con la popolazione campionata.\n:::\n\n::: {.callout-tip collapse=true title=\"Percorsi di lettura\"}\nIl capitolo appartiene al **percorso essenziale** e al **percorso concettuale**. Chi segue il percorso essenziale dovrebbe concentrarsi sulla formulazione del modello, sui prior, sulle quantità posteriori e sulle previsioni. Le sezioni dedicate al confronto tra verosimiglianza normale e Student-$t$ costituiscono un primo approfondimento sulla revisione della specificazione.\n:::\n\n::: {.callout-tip collapse=true title=\"Prerequisiti e approfondimenti\"}\n- Il modello lineare come modello generativo è introdotto nell'@sec-linear-generative.\n- Il workflow bayesiano completo con `brms` è sviluppato nell'@sec-linmod-bayesian-reg.\n- La relazione tra formule R, matrice del modello e programma Stan è discussa nell'@sec-linar-models-brms.\n- Per il trattamento frequentista della media campionaria, del test $t$ e dell'intervallo di confidenza si veda il modulo [utet-frequentista](https://ccaudek.github.io/utet-frequentista).\n- L'esempio sulle altezze degli adulti !Kung San è tratto da @McElreath_rethinking.\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del notebook\"}\n\n\n:::\n\n## Dalla domanda scientifica alla quantità di interesse\n\nConsideriamo le altezze rilevate da Nancy Howell tra gli adulti !Kung San del Kalahari [@McElreath_rethinking]. La domanda descrittiva è:\n\n> Qual è l'altezza media degli adulti nella popolazione rappresentata dal campione e quanta variabilità individuale esiste attorno a tale media?\n\nLe quantità di interesse principali sono:\n\n* $\\mu$: l'altezza media della popolazione stimata dal modello;\n* $\\sigma$: la deviazione standard delle altezze individuali;\n* $\\Pr(\\mu>c\\mid y)$: la probabilità a posteriori che la media superi una specifica soglia teorica $c$;\n* $p(\\widetilde{y}\\mid y)$: la distribuzione predittiva a posteriori per l'altezza $\\widetilde{y}$ di un nuovo individuo.\n\n::: {.callout-important title=\"Limiti di generalizzazione della popolazione\"}\nLa distribuzione a posteriori non descrive l'altezza media degli esseri umani in generale. Definisce il parametro $\\mu$ strettamente all'interno del modello e in relazione alla specifica popolazione da cui il campione è stato estratto. La validità esterna delle conclusioni dipende dal disegno di ricerca, non dall'ampiezza dell'intervallo di credibilità.\n:::\n\n## Come impostare l'analisi\n\nUn'analisi bayesiana di una media può essere organizzata attraverso una sequenza di domande:\n\n1. **Qual è la popolazione target?** Definire chi o che cosa è rappresentato dal campione.\n2. **Qual è l'outcome e in quale unità è misurato?** La scala determina l'interpretazione dei parametri e la calibrazione dei prior.\n3. **Qual è il modello generativo minimo?** Nel caso più semplice, `height ~ 1` con likelihood normale.\n4. **Quali quantità rispondono alla domanda?** Per esempio $\\mu$, $\\sigma$, $\\Pr(\\mu>c\\mid y)$ o una previsione per una nuova osservazione.\n5. **Le assunzioni a priori producono dati plausibili?** Verificarlo con la distribuzione predittiva a priori.\n6. **Il calcolo è affidabile e il modello riproduce le caratteristiche rilevanti?** Distinguere diagnostica MCMC e controlli predittivi.\n7. **Come devono essere comunicati i risultati?** Riportare popolazione, modello, prior, stime posteriori, previsioni e limiti.\n\nQuesta sequenza evita di ridurre l'analisi alla sola esecuzione di `brm()`: la funzione adatta un modello già specificato, ma non decide quale popolazione, quale likelihood o quale quantità di interesse siano scientificamente appropriate.\n\n## Esplorazione dei dati\n\nCarichiamo il dataset ed esaminiamo la struttura delle variabili:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheight_raw <- rio::import(\n  here::here(\"data\", \"Howell_18.csv\")\n)\n\nheight_data <- height_raw |>\n  dplyr::filter(!is.na(height))\n\ndplyr::glimpse(height_raw)\n#> Rows: 352\n#> Columns: 4\n#> $ height <dbl> 152, 140, 137, 157, 145, 164, 149, 169, 148, 165, 154, 151, 145…\n#> $ weight <dbl> 47.8, 36.5, 31.9, 53.0, 41.3, 63.0, 38.2, 55.5, 34.9, 54.5, 49.…\n#> $ age    <dbl> 63.0, 63.0, 65.0, 41.0, 51.0, 35.0, 32.0, 27.0, 19.0, 54.0, 47.…\n#> $ male   <int> 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, …\n```\n:::\n\n\nIl file include già gli individui adulti selezionati per l'analisi. Prima di specificare il modello, verifichiamo la numerosità del campione, la presenza di valori mancanti e le caratteristiche principali della distribuzione (posizione, dispersione e forma):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheight_summary <- height_raw |>\n  summarise(\n    n       = sum(!is.na(height)),\n    missing = sum(is.na(height)),\n    mean    = mean(height, na.rm = TRUE),\n    sd      = sd(height, na.rm = TRUE),\n    min     = min(height, na.rm = TRUE),\n    max     = max(height, na.rm = TRUE)\n  )\n\nheight_summary\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"n\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"missing\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"mean\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sd\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"min\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"max\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"352\",\"2\":\"0\",\"3\":\"155\",\"4\":\"7.74\",\"5\":\"137\",\"6\":\"179\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nVisualizziamo la forma della distribuzione empirica tramite un istogramma:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheight_data |>\n  ggplot(aes(x = height)) +\n  geom_histogram(\n    binwidth = 3,\n    boundary = 0,\n    color = \"white\",\n    fill = modern_palette$grey3\n  ) +\n  labs(\n    x = \"Altezza (cm)\",\n    y = \"Frequenza\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzione osservata delle altezze nel campione di adulti !Kung San.](05_inferenza_su_una_media_files/figure-html/plot-howell-height-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nL'analisi grafica non serve a decidere in modo meccanico se i dati seguano perfettamente una distribuzione normale. Il suo scopo è identificare le proprietà geometriche fondamentali che il modello statistico dovrà essere in grado di riprodurre: la centralità, la dispersione, l'eventuale asimmetria e la presenza di osservazioni anomale o outliers.\n\n## Il modello a sola intercetta\n\nLa specificazione formale del modello lineare semplice senza predittori è:\n\n$$\n\\begin{aligned} \nY_i \\mid \\mu,\\sigma &\\sim \\operatorname{Normal}(\\mu,\\sigma),\\\\ \\mu &= \\alpha. \n\\end{aligned}\n$$\n\nIn notazione matriciale, la struttura si esprime come:\n\n$$\n\\mathbf{y}=\\mathbf{1}\\alpha+\\boldsymbol{\\varepsilon},\n$$\nin cui la matrice del modello $\\mathbf{X}$ si riduce a un unico vettore colonna composto da valori pari a $1$ [@caudek2001statistica]. La formula R:\n\n```r\nheight ~ 1\n```\n\nistruisce il software a stimare un solo parametro a livello di popolazione (*population-level*): l'intercetta.\n\n::: {.callout-note title=\"Significato dell'intercetta\"}\nNei modelli con predittori, l'intercetta rappresenta la media condizionata calcolata quando tutte le variabili esplicative sono poste a zero. Nel modello `height ~ 1`, data l'assenza di predittori, l'intercetta coincide direttamente con la media globale $\\mu$ della distribuzione.\n:::\n\n## Calibrazione dei prior sulla scala osservata\n\nI *prior* devono essere valutati in base alle conseguenze che producono sulla scala originaria delle misure. Per l'altezza di una popolazione adulta espressa in centimetri, definiamo la seguente struttura probabilistica:\n\n$$\n\\begin{aligned} \n\\mu &\\sim \\operatorname{Normal}(160,20),\\\\ \\sigma &\\sim \\operatorname{LogNormal}\\!\\left(\\log 15, 0.5\\right). \n\\end{aligned}\n$$\n\nLa distribuzione assegnata a $\\mu$ concentra la massa di probabilità attorno a valori biologicamente compatibili con la statura umana adulta, pur mantenendo un'incertezza sufficientemente ampia. Il *prior* su $\\sigma$ garantisce matematicamente la positività del parametro e ammette una gamma plausibile di variabilità interindividuale.\n\nDefiniamo questi vincoli in `brms`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheight_priors <- c(\n  prior(normal(160, 20), class = \"Intercept\"),\n  prior(lognormal(log(15), 0.5), class = \"sigma\")\n)\n\nheight_priors\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"prior\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"class\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"coef\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"group\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"resp\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"dpar\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"nlpar\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"lb\"],\"name\":[8],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"ub\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"tag\"],\"name\":[10],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"source\"],\"name\":[11],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"normal(160, 20)\",\"2\":\"Intercept\",\"3\":\"\",\"4\":\"\",\"5\":\"\",\"6\":\"\",\"7\":\"\",\"8\":\"NA\",\"9\":\"NA\",\"10\":\"\",\"11\":\"user\"},{\"1\":\"lognormal(log(15), 0.5)\",\"2\":\"sigma\",\"3\":\"\",\"4\":\"\",\"5\":\"\",\"6\":\"\",\"7\":\"\",\"8\":\"NA\",\"9\":\"NA\",\"10\":\"\",\"11\":\"user\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n> Le etichette \"informativo\" o \"debolmente informativo\" non esprimono proprietà assolute di una distribuzione. Il grado di restrittività di un *prior* va sempre ponderato in relazione alla scala metrica della variabile osservata e agli obiettivi dell'analisi.\n\n## Controllo predittivo a priori\n\nPrima di utilizzare le altezze osservate, simuliamo i dati implicati esclusivamente dalle nostre assunzioni a priori (*prior predictive check*). Questo passaggio permette di verificare la plausibilità biologica del modello prima che venga condizionato dall'evidenza empirica.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_height_prior <- brm(\n  formula = height ~ 1,\n  data = height_data,\n  family = gaussian(),\n  prior = height_priors,\n  sample_prior = \"only\", # Campiona esclusivamente dalle distribuzioni a priori\n  chains = 4,\n  iter = 1000,\n  seed = 1234,\n  backend = \"cmdstanr\",\n  refresh = 0\n)\n```\n:::\n\n\nVisualizziamo le distribuzioni simulate generando un grafico di sovrapposizione delle densità:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp_check(\n  fit_height_prior,\n  type = \"dens_overlay\",\n  ndraws = 50\n)\n```\n\n::: {.cell-output-display}\n![Distribuzioni delle altezze simulate dai prior, prima di utilizzare i valori osservati.](05_inferenza_su_una_media_files/figure-html/prior-predictive-one-mean-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nL'ispezione visiva del grafico serve a rispondere a domande diagnostiche precise:\n\n* Il modello genera altezze fisicamente impossibili (es. valori negativi o superiori a tre metri) con frequenze rilevanti?\n* Vi sono simulazioni quasi prive di variabilità individuale o, al contrario, talmente disperse da non poter descrivere una popolazione umana?\n* La gamma delle medie simulate riflette correttamente l'incertezza teorica che intendiamo dichiarare?\n\nSe il controllo predittivo a priori evidenzia scenari implausibili o assurdi, allora è necessario ricalibrare i *prior* prima di procedere all'adattamento sui dati reali.\n\n## Adattare il modello normale\n\nProcediamo al campionamento della distribuzione a posteriori integrando i dati osservati:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_height_normal <- brm(\n  formula = height ~ 1,\n  data = height_data,\n  family = gaussian(),\n  prior = height_priors,\n  chains = 4,\n  iter = 2000,\n  warmup = 1000,\n  seed = 1234,\n  backend = \"cmdstanr\",\n  refresh = 0\n)\n```\n:::\n\n\nPrima di interpretare i parametri, verifichiamo la qualità e la convergenza del campionamento MCMC:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(fit_height_normal)\n#>  Family: gaussian \n#>   Links: mu = identity \n#> Formula: height ~ 1 \n#>    Data: height_data (Number of observations: 352) \n#>   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n#>          total post-warmup draws = 4000\n#> \n#> Regression Coefficients:\n#>           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\n#> Intercept   154.59      0.42   153.79   155.39 1.00     3661     2417\n#> \n#> Further Distributional Parameters:\n#>       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\n#> sigma     7.78      0.29     7.23     8.37 1.00     3403     2376\n#> \n#> Draws were sampled using sample(hmc). For each parameter, Bulk_ESS\n#> and Tail_ESS are effective sample size measures, and Rhat is the potential\n#> scale reduction factor on split chains (at convergence, Rhat = 1).\n```\n:::\n\n\nEstraiamo le metriche diagnostiche formali e i quantili della posterior:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_height_normal |>\n  as_draws_df() |>\n  summarise_draws(\n    mean,\n    sd,\n    ~quantile2(.x, probs = c(0.025, 0.5, 0.975)),\n    rhat,\n    ess_bulk,\n    ess_tail\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"variable\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"mean\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sd\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"q2.5\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"q50\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"q97.5\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"rhat\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"ess_bulk\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"ess_tail\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"b_Intercept\",\"2\":\"154.59\",\"3\":\"0.4172\",\"4\":\"153.79\",\"5\":\"154.60\",\"6\":\"155.39\",\"7\":\"1\",\"8\":\"3661\",\"9\":\"2417\"},{\"1\":\"sigma\",\"2\":\"7.78\",\"3\":\"0.2948\",\"4\":\"7.23\",\"5\":\"7.77\",\"6\":\"8.37\",\"7\":\"1\",\"8\":\"3403\",\"9\":\"2376\"},{\"1\":\"Intercept\",\"2\":\"154.59\",\"3\":\"0.4172\",\"4\":\"153.79\",\"5\":\"154.60\",\"6\":\"155.39\",\"7\":\"1\",\"8\":\"3661\",\"9\":\"2417\"},{\"1\":\"lprior\",\"2\":\"-7.09\",\"3\":\"0.0615\",\"4\":\"-7.22\",\"5\":\"-7.09\",\"6\":\"-6.98\",\"7\":\"1\",\"8\":\"3465\",\"9\":\"2379\"},{\"1\":\"lp__\",\"2\":\"-1225.46\",\"3\":\"0.9929\",\"4\":\"-1228.03\",\"5\":\"-1225.17\",\"6\":\"-1224.48\",\"7\":\"1\",\"8\":\"1891\",\"9\":\"2402\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nVisualizziamo il comportamento delle catene nel tempo per esaminare l'efficienza di campionamento  (*mixing*):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmcmc_plot(\n  fit_height_normal,\n  type = \"trace\",\n  variable = c(\"b_Intercept\", \"sigma\")\n)\n```\n\n::: {.cell-output-display}\n![Trace plot dei parametri del modello a sola intercetta.](05_inferenza_su_una_media_files/figure-html/trace-one-mean-fit-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n> **Nota di diagnosi:** Il superamento di questi controlli (valori di $\\widehat{R} \\approx 1$ e un numero adeguato di campioni effettivi $ESS$) attesta esclusivamente la stabilità e la qualità dell'approssimazione numerica. Non dimostrano che la distribuzione normale rappresenti una specificazione teorica corretta o ottimale per descrivere le altezze.\n\n## Interpretazione della distribuzione a posteriori\n\nEstraiamo i campioni dalla distribuzione a posteriori per sintetizzare la stima dei parametri:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheight_draws <- as_draws_df(fit_height_normal)\n\nheight_posterior_summary <- height_draws |>\n  transmute(\n    mu = b_Intercept,\n    sigma = sigma\n  ) |>\n  summarise(\n    mu_median    = median(mu),\n    mu_lower     = quantile(mu, 0.025),\n    mu_upper     = quantile(mu, 0.975),\n    sigma_median = median(sigma),\n    sigma_lower  = quantile(sigma, 0.025),\n    sigma_upper  = quantile(sigma, 0.975)\n  )\n\nheight_posterior_summary\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"mu_median\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mu_lower\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mu_upper\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sigma_median\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sigma_lower\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sigma_upper\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"155\",\"2\":\"154\",\"3\":\"155\",\"4\":\"7.77\",\"5\":\"7.23\",\"6\":\"8.37\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nNel modello a sola intercetta i due parametri assumono un preciso significato strutturale:\n\n* `b_Intercept` esprime la media globale $\\mu$ della popolazione;\n* `sigma` esprime la deviazione standard delle altezze individuali attorno a tale media.\n\nL'intervallo di credibilità di $\\mu$ quantifica l'incertezza legata alla stima del valore medio centrale, mentre l'intervallo di `sigma` definisce l'incertezza sulla variabilità interindividuale. Si tratta di due obiettivi inferenziali distinti che non vanno confusi.\n\nVisualizziamo le densità a posteriori dei due parametri:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmcmc_plot(\n  fit_height_normal,\n  type = \"areas\",\n  variable = c(\"b_Intercept\", \"sigma\"),\n  prob = 0.95\n)\n```\n\n::: {.cell-output-display}\n![Distribuzioni a posteriori della media e della deviazione standard.](05_inferenza_su_una_media_files/figure-html/plot-one-mean-posterior-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n### Probabilità condizionate a soglie sostantive\n\nI campioni della posterior consentono di calcolare la probabilità che un parametro superi una determinata soglia critica rilevante per la domanda di ricerca:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nthreshold_cm <- 155\n\nmean(height_draws$b_Intercept > threshold_cm)\n#> [1] 0.17\n```\n:::\n\n\nSul piano formale, questo calcolo determina la probabilità:\n\n$$\n\\Pr(\\mu > 155 \\mid y, \\mathcal{M}),\n$$\ndove $\\mathcal{M}$ rappresenta l'insieme delle assunzioni del modello (verosimiglianza, prior e disegno di campionamento). La soglia di confronto dovrebbe essere motivata da ragioni teoriche, cliniche o decisionali indipendenti dal risultato numerico. Una soglia definita dopo avere esaminato la posterior può essere comunque esplorata, ma deve essere dichiarata come scelta post hoc e non presentata come criterio confermativo prestabilito.\n\n## Media della popolazione e nuova osservazione\n\nUn intervallo di credibilità molto stretto attorno alla media $\\mu$ non indica che i soggetti della popolazione abbiano tutti altezze simili tra loro. Per prevedere il valore di un nuovo individuo futuro ($y_{\\text{new}}$), l'inferenza deve combinare tre distinte fonti di variazione:\n\n1. L'incertezza sulla posizione della media della popolazione ($\\mu$);\n2. L'incertezza sull'entità della dispersione residua ($\\sigma$);\n3. La variabilità stocastica individuale definita dalla funzione di verosimiglianza.\n\nGeneriamo la distribuzione predittiva a posteriori (*posterior predictive distribution*) integrando queste componenti:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Nel modello a sola intercetta tutte le righe hanno la stessa distribuzione\n# predittiva condizionata. La prima colonna rappresenta quindi un possibile\n# nuovo individuo con il medesimo profilo di predittori (qui assenti).\nnew_height_draws <- posterior_predict(fit_height_normal)[, 1]\n\nprediction_summary <- tibble(\n  quantity = c(\"Media mu\", \"Nuova altezza\"),\n  median = c(\n    median(height_draws$b_Intercept),\n    median(new_height_draws)\n  ),\n  lower = c(\n    quantile(height_draws$b_Intercept, 0.025),\n    quantile(new_height_draws, 0.025)\n  ),\n  upper = c(\n    quantile(height_draws$b_Intercept, 0.975),\n    quantile(new_height_draws, 0.975)\n  )\n)\n\nprediction_summary\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"quantity\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"median\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"lower\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"upper\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Media mu\",\"2\":\"155\",\"3\":\"154\",\"4\":\"155\"},{\"1\":\"Nuova altezza\",\"2\":\"154\",\"3\":\"139\",\"4\":\"170\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nConfrontiamo graficamente l'incertezza legata al parametro medio con la dispersione della distribuzione predittiva:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbind_rows(\n  tibble(value = height_draws$b_Intercept, quantity = \"Media mu\"),\n  tibble(value = new_height_draws, quantity = \"Nuova altezza\")\n) |>\n  ggplot(aes(x = value, fill = quantity)) +\n  geom_density(alpha = 0.35) +\n  scale_fill_qualitative() +\n  labs(\n    x = \"Altezza (cm)\",\n    y = \"Densità\",\n    fill = NULL\n  )\n```\n\n::: {.cell-output-display}\n![Confronto tra incertezza sulla media e distribuzione predittiva di una nuova altezza.](05_inferenza_su_una_media_files/figure-html/compare-mean-and-new-height-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nMentre l'aumento delle osservazioni campionarie restringe progressivamente la distribuzione a posteriori di $\\mu$ (poiché disponiamo di maggiore informazione sul baricentro del fenomeno), la distribuzione predittiva di una nuova altezza rimane strutturalmente ampia. Questo accade perché l'eterogeneità biologica tra gli individui non si riduce raccogliendo più dati.\n\n::: {.callout-important title=\"Distinzione tra precisione della stima e omogeneità dei dati\"}\nUn campione di grandi dimensioni consente di isolare la media $\\mu$ con estrema precisione anche in presenza di una forte variabilità individuale. Di conseguenza, la ridotta ampiezza dell'intervallo di credibilità di un parametro non deve mai essere interpretata come un indice di omogeneità o uniformità della popolazione.\n:::\n\n## Controlli predittivi a posteriori\n\nPer valutare l’adeguatezza del modello normale adattato alle altezze, eseguiamo i controlli predittivi a posteriori (*posterior predictive checks*, PPC). Il confronto diretto tra le densità evidenzia la capacità del modello di riprodurre il profilo complessivo dei dati:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp_check(\n  fit_height_normal,\n  type = \"dens_overlay\",\n  ndraws = 50\n)\n```\n\n::: {.cell-output-display}\n![Confronto tra distribuzione osservata e repliche generate dal modello normale.](05_inferenza_su_una_media_files/figure-html/posterior-predictive-density-height-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nOltre alla forma marginale complessiva, possiamo isolare specifiche statistiche di sintesi (in questo caso, la deviazione standard) per valutare se la dispersione teorica stimata sia coerente con la variabilità effettiva del campione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp_check(\n  fit_height_normal,\n  type = \"stat\",\n  stat = \"sd\",\n  ndraws = 200\n)\n```\n\n::: {.cell-output-display}\n![Controllo predittivo a posteriori della deviazione standard osservata.](05_inferenza_su_una_media_files/figure-html/posterior-predictive-stat-height-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n> **Nota metodologica:** Il superamento di queste verifiche non equivale a una convalida assoluta del modello. Ciascun grafico valuta la bontà di adattamento solo rispetto alla metrica o alla caratteristica selezionata. Un modello può riprodurre fedelmente la deviazione standard o la forma marginale di $Y$ pur fallendo su altre proprietà statistiche non esaminate, come l'assenza di asimmetria o la presenza di code pesanti nei dati reali.\n\n## Modello robusto con la distribuzione $t$ di Student\n\nLa verosimiglianza normale attribuisce una probabilità estremamente bassa alle osservazioni molto distanti dalla media. Di conseguenza, in presenza di valori anomali (*outliers*) o di code pesanti, pochi dati estremi possono distorcere in modo significativo le stime di $\\mu$ e $\\sigma$.\n\nPer mitigare questo problema, possiamo adottare una specificazione robusta basata sulla distribuzione $t$ di Student:\n\n$$\nY_i \\sim \\operatorname{StudentT}(\\nu, \\mu, \\sigma).\n$$\n\nIl parametro aggiuntivo $\\nu$ (gradi di libertà) regola lo spessore delle code: per valori elevati di $\\nu$ la distribuzione approssima la normale, mentre per valori ridotti aumenta la probabilità di osservare dati lontani dal centro, riducendo l'impatto dei valori estremi sulla stima del baricentro.\n\nAdattiamo il modello in `brms` introducendo un *prior* specifico (di tipo Gamma) per regolare i gradi di libertà:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_height_student <- brm(\n  formula = height ~ 1,\n  data = height_data,\n  family = student(),\n  prior = c(\n    prior(normal(160, 20), class = \"Intercept\"),\n    prior(lognormal(log(15), 0.5), class = \"sigma\"),\n    prior(gamma(2, 0.1), class = \"nu\")\n  ),\n  chains = 4,\n  iter = 2000,\n  warmup = 1000,\n  seed = 1234,\n  backend = \"cmdstanr\",\n  refresh = 0\n)\n```\n:::\n\n\nConfrontiamo graficamente le distribuzioni a posteriori di $\\mu$ ottenute con le due verosimiglianze:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbind_rows(\n  as_draws_df(fit_height_normal)  |> transmute(mu = b_Intercept, model = \"Normale\"),\n  as_draws_df(fit_height_student) |> transmute(mu = b_Intercept, model = \"Student-t\")\n) |>\n  ggplot(aes(x = mu, fill = model)) +\n  geom_density(alpha = 0.35) +\n  scale_fill_qualitative() +\n  labs(\n    x = expression(mu),\n    y = \"Densità\",\n    fill = \"Modello\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzione a posteriori della media sotto verosimiglianza normale e t di Student.](05_inferenza_su_una_media_files/figure-html/compare-normal-student-mu-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nEseguiamo ora un controllo predittivo a posteriori (*PPC*) focalizzato sul valore minimo osservato, utile per testare la capacità dei due modelli di gestire il comportamento delle code:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Controllo per il modello normale\npp_check(fit_height_normal, type = \"stat\", stat = \"min\", ndraws = 200)\n\n# Controllo per il modello Student-t\npp_check(fit_height_student, type = \"stat\", stat = \"min\", ndraws = 200)\n```\n\n::: {.cell-output-display}\n![Controllo predittivo del valore minimo per i modelli normale e t di Student.](05_inferenza_su_una_media_files/figure-html/compare-normal-student-tails-1.png){fig-align='center' width=85%}\n:::\n\n::: {.cell-output-display}\n![Controllo predittivo del valore minimo per i modelli normale e t di Student.](05_inferenza_su_una_media_files/figure-html/compare-normal-student-tails-2.png){fig-align='center' width=85%}\n:::\n:::\n\n\n> **Nota metodologica:** L'uso della distribuzione $t$ di Student non va automatizzato in nome di una generica \"maggiore robustezza\". L'introduzione del parametro $\\nu$ aumenta la flessibilità del modello ma ne incrementa anche la complessità computazionale. Inoltre, la robustezza geometrica verso le code pesanti non corregge altre forme di distorsione o errori sistematici nel disegno di campionamento. La scelta deve quindi poggiare sulla plausibilità del processo generativo dei dati e sugli obiettivi specifici dell'inferenza.\n\n## Analisi di sensibilità ai prior\n\nQuando il campione è numeroso e informativo, specificazioni a priori differenti ma ragionevoli producono spesso distribuzioni a posteriori quasi identiche. Questo fenomeno non rende i *prior* irrilevanti: indica semplicemente che la funzione di verosimiglianza ha dominato il processo di aggiornamento bayesiano.\n\nPer verificare la robustezza delle nostre stime, confrontiamo il *prior* calibrato in precedenza con una variante molto più ampia e meno informativa:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_height_wide <- brm(\n  formula = height ~ 1,\n  data = height_data,\n  family = gaussian(),\n  prior = c(\n    prior(normal(160, 50), class = \"Intercept\"),\n    prior(lognormal(log(20), 1), class = \"sigma\")\n  ),\n  chains = 4,\n  iter = 2000,\n  warmup = 1000,\n  seed = 1234,\n  backend = \"cmdstanr\",\n  refresh = 0\n)\n```\n:::\n\n\nConfrontiamo graficamente l'impatto dei due approcci sulla posterior di $\\mu$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbind_rows(\n  as_draws_df(fit_height_normal) |> transmute(mu = b_Intercept, prior = \"Calibrato\"),\n  as_draws_df(fit_height_wide)   |> transmute(mu = b_Intercept, prior = \"Più ampio\")\n) |>\n  ggplot(aes(x = mu, fill = prior)) +\n  geom_density(alpha = 0.35) +\n  scale_fill_qualitative() +\n  labs(\n    x = expression(mu),\n    y = \"Densità\",\n    fill = \"Prior\"\n  )\n```\n\n::: {.cell-output-display}\n![Sensibilità della posterior della media a due specificazioni a priori.](05_inferenza_su_una_media_files/figure-html/compare-one-mean-priors-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nL'esito di un'analisi di sensibilità va sempre valutato in base alla sua rilevanza scientifica o applicativa. Lievi scostamenti nelle cifre decimali dei parametri sono trascurabili; al contrario, variazioni marginali che modificano le decisioni teoriche o alterano significativamente le probabilità condizionate a soglie critiche richiedono una discussione esplicita e trasparente all'interno della ricerca.\n\n## Comunicazione dei risultati\n\nUn resoconto sintetico può assumere questa forma:\n\n> Abbiamo modellato le altezze degli adulti !Kung San mediante una distribuzione normale con media $\\mu$ e deviazione standard $\\sigma$ ignote. I prior sono stati formulati in centimetri e controllati attraverso simulazioni predittive a priori. La mediana a posteriori della media è 154.6 cm, con intervallo di credibilità al 95% [153.8, 155.4]. La deviazione standard individuale è stimata in 7.8 cm, con intervallo al 95% [7.2, 8.4]. L'intervallo predittivo per una nuova osservazione è molto più ampio dell'intervallo per $\\mu$, perché incorpora la variabilità tra individui. Nei controlli predittivi sono state esaminate la forma marginale e la deviazione standard dei dati replicati. Il resoconto deve segnalare le eventuali discrepanze osservate; anche in loro assenza, il controllo riguarda soltanto le caratteristiche considerate e non dimostra che il modello sia vero né che il campione rappresenti popolazioni diverse da quella studiata.\n\nNel testo del rapporto di ricerca, la sintesi numerica deve sempre includere:\n\n* **Contesto e validità:** la definizione esplicita della popolazione target e l'unità di misura;\n* **Trasparenza del modello:** la specifica della verosimiglianza e dei *prior* adottati;\n* **Stime puntuali e intervallari:** la media o la mediana a posteriori dei parametri accompagnata da un intervallo di credibilità (es. al 95%);\n* **Quantità di interesse:** le eventuali probabilità a posteriori associate a soglie critiche stabilite *a priori*;\n* **Diagnostica:** l'esito dei controlli predittivi (*PPC*) giudicati rilevanti per la domanda scientifica.\n\n## Errori frequenti\n\n::: {.callout-caution}\n1. **Confondere la media campionaria con la media della popolazione.** La prima è una statistica osservata; la seconda è un parametro del modello la cui interpretazione dipende dal campionamento.\n2. **Interpretare $\\sigma$ come incertezza su $\\mu$.** $\\sigma$ descrive la dispersione individuale; l'incertezza su $\\mu$ è descritta dalla sua posterior.\n3. **Usare l'intervallo di $\\mu$ come intervallo per una nuova persona.** La distribuzione predittiva individuale è normalmente molto più ampia.\n4. **Scegliere prior senza considerarne le conseguenze osservabili.** Parametri apparentemente ragionevoli possono generare dataset implausibili.\n5. **Dichiarare la normalità sulla base del solo istogramma.** L'adeguatezza dipende dalle caratteristiche rilevanti per l'inferenza e va valutata predittivamente.\n6. **Usare automaticamente la Student-$t$ per ogni dataset.** Una verosimiglianza robusta rappresenta code pesanti, ma non corregge asimmetria, multimodalità, dipendenza o errori di campionamento.\n7. **Generalizzare oltre la popolazione rappresentata.** Un intervallo stretto non compensa un campionamento selettivo o non rappresentativo.\n:::\n\n## Riflessioni conclusive\n\nLa stima di una media coincide con l'adattamento del più elementare dei modelli lineari: il modello a sola intercetta. Questa struttura evidenzia come, in ambito statistico, una media non esista mai in isolamento, ma sia sempre definita in funzione di una distribuzione delle osservazioni e di un parametro di dispersione.\n\nIl workflow bayesiano applicato a questo framework permette di:\n\n* esprimere le conoscenze iniziali direttamente sulla scala metrica dei dati;\n* verificare la plausibilità di tali assunzioni tramite simulazioni predittive a priori;\n* ottenere una distribuzione a posteriori congiunta per $\\mu$ e $\\sigma$;\n* calcolare in modo diretto le probabilità associate a soglie teoriche o cliniche;\n* distinguere nettamente l'incertezza sulla stima della media dalla variabilità legata alla previsione di un nuovo punteggio individuale;\n* valutare verosimiglianze alternative (come la $t$ di Student) qualora la distribuzione normale non gestisca adeguatamente le code pesanti.\n\nIl modello a sola intercetta rappresenta la base logica e matematica per gli sviluppi successivi. L'introduzione di un predittore categoriale, ad esempio, permetterà all'intercetta e al nuovo coefficiente di esprimere le medie di due gruppi e la loro differenza. Di conseguenza, il passaggio dalla stima di una singola media al confronto tra gruppi non richiede un cambio di paradigma teorico, ma semplicemente una diversa matrice del modello e la definizione di nuove quantità di interesse.\n\n## Concetti da ricordare\n\n1. La stima di una media è un modello lineare `y ~ 1`.\n2. Nel modello a sola intercetta, `b_Intercept` coincide con $\\mu$.\n3. $\\mu$ descrive il centro della popolazione modellata; $\\sigma$ descrive la dispersione individuale.\n4. I prior devono essere controllati attraverso le distribuzioni dei dati che implicano.\n5. La posterior di $\\mu$ e la distribuzione predittiva di una nuova osservazione rispondono a domande diverse.\n6. Un intervallo stretto per la media non implica bassa variabilità individuale.\n7. I posterior predictive checks valutano caratteristiche specifiche, non la validità globale del modello.\n8. La Student-$t$ può rappresentare code più pesanti, ma non è una soluzione generale a ogni errore di specificazione.\n9. La sensibilità ai prior va valutata rispetto alle conclusioni sostantive.\n10. La possibilità di generalizzare dipende dal disegno di campionamento, non soltanto dalla precisione della posterior.\n\n## Esercizi {.unnumbered .unlisted}\n\n### Esercizio 1 — Comprendere e impostare l'analisi {.unnumbered .unlisted}\n\nUn gruppo di ricerca dispone dei punteggi di ansia di un campione di studenti universitari e vuole stimare il livello medio nella popolazione rappresentata dal campione.\n\n1. Definisci outcome, popolazione target e unità di misura.\n2. Scrivi la formula di Wilkinson e l'equazione generativa del modello normale a sola intercetta.\n3. Indica il significato sostantivo di $\\mu$ e $\\sigma$.\n4. Proponi una quantità di interesse relativa alla media e una relativa a un nuovo studente.\n5. Spiega quali informazioni aggiuntive servirebbero per generalizzare i risultati a tutti gli studenti universitari italiani.\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nLa formula non contiene predittori. Distingui una domanda sul parametro medio da una domanda su una futura osservazione individuale.\n:::\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\nL'outcome è il punteggio di ansia nella scala utilizzata; la popolazione target deve essere definita dal disegno di campionamento. La formula è `anxiety ~ 1` e il modello è\n\n$$\nY_i\\sim\\operatorname{Normal}(\\mu,\\sigma).\n$$\n\n$\\mu$ è la media della popolazione modellata e $\\sigma$ la dispersione dei punteggi individuali. Una quantità sulla media può essere $\\Pr(\\mu>c\\mid y)$; una quantità individuale è la distribuzione $p(\\widetilde y\\mid y)$. La generalizzazione nazionale richiede informazioni su procedura di campionamento, copertura delle università e composizione del campione: la precisione della posterior non sostituisce la rappresentatività.\n:::\n\n### Esercizio 2 — Prevedere e interpretare {.unnumbered .unlisted}\n\nUn modello a sola intercetta produce il seguente riassunto:\n\n- mediana di $\\mu$: 154,8;\n- intervallo di credibilità al 95% per $\\mu$: [154,1; 155,5];\n- mediana di $\\sigma$: 7,6;\n- intervallo predittivo al 95% per una nuova osservazione: [139,7; 169,9];\n- $\\Pr(\\mu>155\\mid y)=0,29$.\n\nInterpreta ciascuna quantità. Spiega inoltre:\n\n1. perché l'intervallo predittivo è molto più ampio dell'intervallo per $\\mu$;\n2. se si può affermare che il 95% delle persone abbia un'altezza compresa tra 154,1 e 155,5;\n3. che cosa cambierebbe raccogliendo un campione molto più grande dalla stessa popolazione.\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nL'intervallo di $\\mu$ descrive l'incertezza sul centro della popolazione; la previsione individuale incorpora anche $\\sigma$.\n:::\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\nLa posterior colloca la media della popolazione intorno a 154,8 cm e attribuisce il 29% di probabilità, condizionatamente al modello, a valori superiori a 155 cm. $\\sigma=7,6$ cm descrive la dispersione individuale, non l'incertezza sulla media. L'intervallo [154,1; 155,5] riguarda $\\mu$ e non le singole persone; l'intervallo [139,7; 169,9] è più ampio perché include la variabilità tra individui. Un campione più grande restringerebbe in genere la posterior di $\\mu$, ma non eliminerebbe l'eterogeneità individuale rappresentata da $\\sigma$.\n:::\n\n### Esercizio 3 — Modificare ed eseguire il workflow {.unnumbered .unlisted}\n\nUsa il codice già fornito nel capitolo per svolgere queste modifiche guidate:\n\n1. sostituisci la soglia `threshold_cm <- 155` con una soglia motivata prima di osservare il risultato e calcola $\\Pr(\\mu>c\\mid y)$;\n2. usa `posterior_predict()` per ottenere la distribuzione di una nuova osservazione e confrontala con la posterior di `b_Intercept`;\n3. esegui un controllo predittivo mirato alla mediana e uno al minimo;\n4. stabilisci quale risultato useresti per rispondere a ciascuna domanda:\n   - qual è l'altezza media della popolazione modellata?\n   - quanto variano gli individui?\n   - quale altezza potrebbe avere una nuova persona?\n   - il modello riproduce adeguatamente le code inferiori?\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nLe quattro domande richiedono rispettivamente la posterior di `b_Intercept`, la posterior di `sigma`, `posterior_predict()` e un controllo predittivo mirato.\n:::\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\nLa probabilità rispetto alla soglia si calcola sulla posterior di `b_Intercept`; la previsione individuale deve invece essere ottenuta da `posterior_predict()`. Il controllo della mediana valuta il centro in modo robusto, mentre quello del minimo è sensibile alla coda inferiore. Nessun singolo output risponde a tutte le domande: la corretta esecuzione richiede di scegliere una quantità coerente con l'obiettivo sostantivo.\n:::\n\n### Esercizio 4 — Criticare e comunicare {.unnumbered .unlisted}\n\nUn ricercatore scrive:\n\n> L'altezza media è 154,8 cm, con un intervallo al 95% tra 154,1 e 155,5 cm. Ciò significa che il 95% degli adulti ha un'altezza in questo intervallo. Poiché $\\widehat R=1$ e il controllo predittivo della deviazione standard è buono, il modello normale è vero e il risultato vale per tutti gli esseri umani. Inoltre, dato che la Student-$t$ produce una stima simile, gli outlier non possono influenzare l'analisi.\n\nIndividua almeno cinque problemi e riscrivi il resoconto in forma appropriata. La versione corretta deve distinguere:\n\n- parametro medio e osservazioni individuali;\n- diagnostica del calcolo e adeguatezza del modello;\n- controllo di una caratteristica e validità globale;\n- sensibilità della stima e assenza di outlier;\n- popolazione campionata e popolazioni esterne.\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nUn intervallo di credibilità per $\\mu$ non è un intervallo predittivo. Né le diagnostiche MCMC né un singolo PPC stabiliscono la verità o la generalizzabilità del modello.\n:::\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\nIl resoconto dovrebbe affermare che la posterior della media è concentrata intorno a 154,8 cm, con intervallo di credibilità [154,1; 155,5], condizionatamente al modello e ai prior. La variabilità degli individui va comunicata attraverso $\\sigma$ o la distribuzione predittiva, non attraverso l'intervallo di $\\mu$. $\\widehat R$ ed ESS riguardano la qualità del campionamento; un PPC valuta soltanto la caratteristica scelta. La somiglianza tra i modelli normale e Student-$t$ indica che la conclusione sulla media è poco sensibile a quella modifica nelle condizioni esaminate, non che gli outlier siano assenti o irrilevanti in generale. Infine, l'inferenza riguarda la popolazione rappresentata dal campione e non tutti gli esseri umani.\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.5.2\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.0            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.0           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] gridExtra_2.3.1       inline_0.3.21         rlang_1.3.0          \n#>  [4] magrittr_2.0.5        snakecase_0.11.1      otel_0.2.0           \n#>  [7] ggridges_0.5.7        compiler_4.6.1        reshape2_1.4.5       \n#> [10] vctrs_0.7.3           stringr_1.6.0         pkgconfig_2.0.3      \n#> [13] arrayhelpers_1.1-1    fastmap_1.2.0         backports_1.5.1      \n#> [16] labeling_0.4.3        cmdstanr_0.9.0        rmarkdown_2.31       \n#> [19] ps_1.9.3              purrr_1.2.2           xfun_0.60            \n#> [22] cachem_1.1.0          jsonlite_2.0.0        broom_1.0.13         \n#> [25] parallel_4.6.1        R6_2.6.1              stringi_1.8.7        \n#> [28] RColorBrewer_1.1-3    lubridate_1.9.5       estimability_2.0.0   \n#> [31] knitr_1.51            R.utils_2.13.0        Matrix_1.7-5         \n#> [34] timechange_0.4.0      tidyselect_1.2.1      abind_1.4-8          \n#> [37] yaml_2.3.12           codetools_0.2-20      curl_7.1.0           \n#> [40] processx_3.9.0        pkgbuild_1.4.8        plyr_1.8.9           \n#> [43] lattice_0.22-9        bridgesampling_1.2-1  S7_0.2.2             \n#> [46] coda_0.19-4.1         evaluate_1.0.5        RcppParallel_5.1.11-2\n#> [49] pillar_1.11.1         tensorA_0.36.2.1      checkmate_2.3.4      \n#> [52] stats4_4.6.1          distributional_0.8.1  generics_0.1.4       \n#> [55] rprojroot_2.1.1       rstantools_2.6.0      scales_1.4.0         \n#> [58] xtable_1.8-8          glue_1.8.1            emmeans_2.0.4        \n#> [61] tools_4.6.1           data.table_1.18.4     mvtnorm_1.4-2        \n#> [64] grid_4.6.1            QuickJSR_1.10.0       nlme_3.1-170         \n#> [67] cli_3.6.6             textshaping_1.0.5     svUnit_1.0.8         \n#> [70] Brobdingnag_1.2-9     V8_8.2.0              gtable_0.3.6         \n#> [73] R.methodsS3_1.8.2     digest_0.6.39         htmlwidgets_1.6.4    \n#> [76] farver_2.1.2          memoise_2.0.1         htmltools_0.5.9      \n#> [79] R.oo_1.27.1           lifecycle_1.0.5\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n\n",
    "supporting": [
      "05_inferenza_su_una_media_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}