{
  "hash": "01610e4d48446bb2d61c7e5a419c1af6",
  "result": {
    "engine": "knitr",
    "markdown": "# Quantificare e aggiornare l'incertezza con l'approssimazione su griglia {#sec-grid-approx}\n\n::: {.callout-note appearance=\"minimal\"}\nNel capitolo del manuale dedicato alla quantificazione e all'aggiornamento dell'incertezza, il teorema di Bayes è stato presentato come una regola per combinare conoscenze iniziali e dati osservati. In forma simbolica,\n\n$$\np(\\theta \\mid y) \\propto p(y \\mid \\theta)\\,p(\\theta).\n$$\n\nLa formula è compatta, ma l'operazione che descrive può rimanere astratta. L'approssimazione su griglia elimina questa difficoltà: scegliamo un insieme finito di valori possibili per $\\theta$ e, **per ciascun valore**, moltiplichiamo il peso assegnato dal prior per la compatibilità espressa dalla verosimiglianza. La normalizzazione finale trasforma questi prodotti in probabilità a posteriori.\n\nL'obiettivo principale del capitolo è quindi rendere completamente trasparente la sequenza:\n\n$$\n\\text{prior} \\times \\text{verosimiglianza}\n\\longrightarrow\n\\text{pesi posteriori non normalizzati}\n\\longrightarrow\n\\text{posterior}.\n$$\n:::\n\n::: {.callout-important appearance=\"minimal\" .chapter-status}\n**Da sapere.** Nell'approssimazione su griglia, prior e verosimiglianza vengono valutati sugli stessi valori del parametro. Il loro prodotto punto per punto assegna un peso elevato ai valori che sono sostenuti sia dalle conoscenze iniziali sia dai dati. Questi prodotti devono essere normalizzati prima di poter essere interpretati come probabilità a posteriori.\n\n**Da saper fare.** Costruire una griglia; assegnare e normalizzare i pesi a priori; calcolare la verosimiglianza; moltiplicare prior e verosimiglianza punto per punto; normalizzare i prodotti; interpretare la distribuzione a posteriori e confrontare l'approssimazione discreta con la soluzione Beta-Binomiale.\n\n**Approfondimento facoltativo.** La soluzione analitica Beta-Binomiale, il confronto tra griglie di diversa risoluzione e la seconda applicazione possono essere rimandati in una prima lettura.\n\n[Che cosa significano queste etichette?](../../guida-al-manuale.qmd#sec-percorsi-lettura)\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Prerequisiti\"}\n\n- Sono dati per noti il teorema di Bayes, la verosimiglianza e la distinzione tra prior e posterior, presentati nel capitolo 7 del Companion.\n- È utile conoscere la distribuzione binomiale e le regole elementari della probabilità.\n- Per richiami su intervalli e sommatorie si possono consultare l'@sec-apx-numbers e l'@sec-apx-sums; la lettura del codice R è facoltativa.\n\n:::\n\n::: {.callout-caution collapse=\"true\" title=\"Preparazione del notebook\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |>\n  source()\n```\n:::\n\n:::\n\n## Il dilemma del carrello ferroviario\n\nIl dilemma del carrello ferroviario [@foot1967; @thomson1976] è uno scenario classico della psicologia morale. Nella versione considerata, un treno fuori controllo sta per investire cinque persone. Il partecipante può deviarlo su un binario alternativo, salvando le cinque persone ma causando la morte di una persona.\n\nIndichiamo con $\\theta$ la proporzione della popolazione che giudica moralmente accettabile deviare il treno. Ogni risposta è binaria e, nel modello più semplice, il numero di risposte positive in un campione di ampiezza $n$ segue una distribuzione binomiale.\n\nSupponiamo di osservare 22 risposte positive in un campione di 30 persone:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsuccessi <- 22\nprove <- 30\nproporzione_osservata <- successi / prove\nproporzione_osservata\n#> [1] 0.733\n```\n:::\n\n\nVogliamo usare questi dati per aggiornare le nostre credenze sui possibili valori di $\\theta$.\n\n## L'approssimazione su griglia\n\n### Passo 1: scegliere i valori possibili\n\nPoiché $\\theta$ è una proporzione, può assumere valori tra 0 e 1. Per rendere ogni calcolo visibile, utilizziamo inizialmente una griglia grossolana di undici punti:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_griglia <- seq(0, 1, by = 0.1)\ntheta_griglia\n#>  [1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0\n```\n:::\n\n\nLa griglia non afferma che $\\theta$ possa assumere soltanto questi valori. È uno strumento computazionale: sostituisce temporaneamente un intervallo continuo con un insieme finito di possibilità.\n\n### Passo 2: assegnare i pesi a priori\n\nPer costruire un prior discreto, valutiamo una distribuzione Beta(2, 2) nei punti della griglia e normalizziamo i valori ottenuti. Il prior è simmetrico intorno a 0.5 e assegna poco peso ai valori estremi.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npesi_prior <- dbeta(theta_griglia, shape1 = 2, shape2 = 2)\nprior <- pesi_prior / sum(pesi_prior)\n\nsum(prior)\n#> [1] 1\n```\n:::\n\n\nDopo la normalizzazione, `prior` è una distribuzione di probabilità discreta: a ogni valore della griglia corrisponde una probabilità e la somma è uguale a uno.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndati_prior <- tibble(\n  theta = theta_griglia,\n  prior = prior\n)\n\nggplot(dati_prior, aes(theta, prior)) +\n  geom_col(width = 0.075, fill = palette_qualitative[8], alpha = 0.8) +\n  scale_x_continuous(breaks = theta_griglia) +\n  labs(\n    title = \"Distribuzione a priori sulla griglia\",\n    subtitle = \"Prior discreto ottenuto da una Beta(2, 2)\",\n    x = expression(theta),\n    y = \"Probabilità a priori\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzione a priori discreta sui valori della griglia. I pesi, ottenuti valutando una Beta(2, 2) e normalizzandola, sono simmetrici rispetto a θ = 0.5 e attribuiscono poca probabilità ai valori estremi.](01_grid_approx_files/figure-html/fig-grid-prior-beta22-1.png){#fig-grid-prior-beta22 fig-align='center' fig-alt='Grafico a barre della distribuzione a priori su undici valori di theta compresi tra zero e uno. Le barre crescono fino al centro della griglia e poi diminuiscono simmetricamente.' width=85%}\n:::\n:::\n\n\n::: {.callout-note title=\"Densità continua e probabilità discreta\"}\n`dbeta()` restituisce una **densità**, non una probabilità puntuale. Nell'approssimazione su griglia usiamo tali densità come pesi relativi e le dividiamo per la loro somma. Otteniamo così probabilità discrete associate ai punti della griglia.\n:::\n\n### Passo 3: calcolare la verosimiglianza\n\nPer ogni valore candidato di $\\theta$, calcoliamo la probabilità di osservare esattamente 22 successi su 30 prove:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nverosimiglianza <- dbinom(\n  x = successi,\n  size = prove,\n  prob = theta_griglia\n)\n\nverosimiglianza\n#>  [1] 0.00e+00 2.52e-16 4.12e-10 1.06e-06 1.73e-04 5.45e-03 5.05e-02 1.50e-01\n#>  [9] 1.11e-01 5.76e-03 0.00e+00\n```\n:::\n\n\nLa verosimiglianza risponde alla domanda:\n\n> Se un determinato valore di $\\theta$ fosse quello usato dal modello generativo, quanto sarebbero compatibili con esso i dati osservati?\n\nLa verosimiglianza è massima vicino alla proporzione campionaria $22/30 \\approx 0.73$. Sulla griglia scelta, il massimo cade in $\\theta=0.7$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_massima_verosimiglianza <- theta_griglia[which.max(verosimiglianza)]\ntheta_massima_verosimiglianza\n#> [1] 0.7\n```\n:::\n\n\nÈ essenziale non confondere la verosimiglianza con una distribuzione di probabilità su $\\theta$. In questa fase non stiamo ancora assegnando probabilità ai valori del parametro; stiamo confrontando quanto bene ciascun valore rende conto degli stessi dati.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndati_likelihood <- tibble(\n  theta = theta_griglia,\n  verosimiglianza = verosimiglianza\n)\n\nggplot(dati_likelihood, aes(theta, verosimiglianza)) +\n  geom_col(width = 0.075, fill = palette_qualitative[1], alpha = 0.8) +\n  scale_x_continuous(breaks = theta_griglia) +\n  labs(\n    title = \"Verosimiglianza dei dati\",\n    subtitle = paste0(successi, \" risposte positive su \", prove),\n    x = expression(theta),\n    y = expression(p(y == 22 ~ \"|\" ~ theta))\n  )\n```\n\n::: {.cell-output-display}\n![Verosimiglianza di 22 risposte positive su 30 per ciascun valore candidato di θ. Sulla griglia grossolana la compatibilità con i dati è massima in θ = 0.7, vicino alla proporzione osservata 22/30.](01_grid_approx_files/figure-html/fig-grid-likelihood-trolley-1.png){#fig-grid-likelihood-trolley fig-align='center' fig-alt='Grafico a barre della verosimiglianza su valori di theta da zero a uno. Le barre sono quasi nulle agli estremi, aumentano rapidamente e raggiungono il massimo intorno a zero virgola sette.' width=85%}\n:::\n:::\n\n\n### Passo 4: moltiplicare punto per punto\n\nOra eseguiamo l'operazione centrale. Per ogni riga della griglia moltiplichiamo:\n\n$$\n\\text{peso non normalizzato}(\\theta_i)\n=\np(\\theta_i)\\,p(y\\mid\\theta_i).\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npeso_non_normalizzato <- prior * verosimiglianza\n```\n:::\n\n\nLa moltiplicazione è **punto per punto**:\n\n- il prior in $\\theta=0.5$ viene moltiplicato per la verosimiglianza in $\\theta=0.5$;\n- il prior in $\\theta=0.6$ viene moltiplicato per la verosimiglianza in $\\theta=0.6$;\n- e così via.\n\nNon si moltiplica il prior in un punto per la verosimiglianza in un altro punto. Ogni valore candidato viene valutato separatamente.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntabella_aggiornamento <- tibble(\n  theta = theta_griglia,\n  prior = prior,\n  verosimiglianza = verosimiglianza,\n  prodotto = peso_non_normalizzato\n)\n\ntabella_aggiornamento |>\n  mutate(\n    across(\n      c(prior, verosimiglianza, prodotto),\n      \\(x) formatC(x, format = \"fg\", digits = 4)\n    )\n  ) |>\n  knitr::kable(\n    align = c(\"c\", \"c\", \"c\", \"c\"),\n    caption = \"Moltiplicazione punto per punto di prior e verosimiglianza\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Moltiplicazione punto per punto di prior e verosimiglianza\n\n| theta |  prior  |    verosimiglianza    |        prodotto        |\n|:-----:|:-------:|:---------------------:|:----------------------:|\n|  0.0  |    0    |           0           |           0            |\n|  0.1  | 0.05455 | 0.0000000000000002519 | 0.00000000000000001374 |\n|  0.2  | 0.09697 |    0.0000000004119    |    0.00000000003994    |\n|  0.3  | 0.1273  |      0.000001059      |      0.0000001348      |\n|  0.4  | 0.1455  |       0.0001729       |       0.00002516       |\n|  0.5  | 0.1515  |       0.005451        |       0.0008259        |\n|  0.6  | 0.1455  |        0.05049        |        0.007344        |\n|  0.7  | 0.1273  |        0.1501         |        0.01911         |\n|  0.8  | 0.09697 |        0.1106         |        0.01072         |\n|  0.9  | 0.05455 |       0.005764        |       0.0003144        |\n|  1.0  |    0    |           0           |           0            |\n\n\n:::\n:::\n\n\nConsideriamo due righe della tabella. Per $\\theta=0.5$ il prior attribuisce un peso relativamente alto, ma i dati sono poco compatibili con quel valore. Per $\\theta=0.7$, invece, il prior assegna ancora un peso apprezzabile e la verosimiglianza è elevata. Il prodotto è quindi molto più grande in $\\theta=0.7$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nriga_05 <- tabella_aggiornamento |>\n  filter(theta == 0.5)\n\nriga_07 <- tabella_aggiornamento |>\n  filter(abs(theta - 0.7) < 1e-10)\n```\n:::\n\n\nPer $\\theta=0.5$:\n\n$$\n0.152\n\\times\n0.005\n=\n0.001.\n$$\n\nPer $\\theta=0.7$:\n\n$$\n0.127\n\\times\n0.15\n=\n0.019.\n$$\n\n::: {.callout-important title=\"Il significato pratico della moltiplicazione\"}\nIl prodotto è grande soltanto quando **entrambi** i fattori sono sufficientemente grandi.\n\n- Un valore favorito dal prior ma incompatibile con i dati riceve poco peso.\n- Un valore compatibile con i dati ma quasi escluso dal prior riceve poco peso.\n- Un valore sostenuto sia dal prior sia dai dati riceve molto peso.\n\nLa moltiplicazione funziona quindi come un'intersezione quantitativa tra le due fonti di informazione.\n:::\n\n### Passo 5: normalizzare\n\nI prodotti ottenuti non sommano a uno e non sono ancora probabilità a posteriori:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncostante_normalizzazione <- sum(peso_non_normalizzato)\ncostante_normalizzazione\n#> [1] 0.0383\n```\n:::\n\n\nNel modello discreto definito dalla griglia, questa somma è anche la probabilità marginale dei dati:\n\n$$\np(y)=\\sum_i p(y\\mid\\theta_i)p(\\theta_i).\n$$\n\nLa costante risponde quindi alla domanda: quanto erano complessivamente prevedibili i dati prima di conoscere quale valore di $\\theta$ fosse più plausibile?\n\nDividiamo ogni prodotto per la somma di tutti i prodotti:\n\n$$\np(\\theta_i\\mid y)\n=\n\\frac{\np(\\theta_i)\\,p(y\\mid\\theta_i)\n}{\n\\sum_j p(\\theta_j)\\,p(y\\mid\\theta_j)\n}.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nposterior <- peso_non_normalizzato / costante_normalizzazione\nsum(posterior)\n#> [1] 1\n```\n:::\n\n\nLa normalizzazione non cambia l'ordine o i rapporti relativi tra i valori: moltiplica tutti i pesi per la stessa costante. Il suo scopo è trasformare i pesi relativi in una distribuzione di probabilità valida.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntabella_aggiornamento <- tabella_aggiornamento |>\n  mutate(posterior = posterior)\n\ntabella_aggiornamento |>\n  mutate(\n    across(\n      c(prior, verosimiglianza, prodotto, posterior),\n      \\(x) formatC(x, format = \"fg\", digits = 4)\n    )\n  ) |>\n  knitr::kable(\n    align = c(\"c\", \"c\", \"c\", \"c\", \"c\"),\n    caption = \"Dal prodotto non normalizzato alla distribuzione a posteriori\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Dal prodotto non normalizzato alla distribuzione a posteriori\n\n| theta |  prior  |    verosimiglianza    |        prodotto        |       posterior       |\n|:-----:|:-------:|:---------------------:|:----------------------:|:---------------------:|\n|  0.0  |    0    |           0           |           0            |           0           |\n|  0.1  | 0.05455 | 0.0000000000000002519 | 0.00000000000000001374 | 0.0000000000000003585 |\n|  0.2  | 0.09697 |    0.0000000004119    |    0.00000000003994    |    0.000000001042     |\n|  0.3  | 0.1273  |      0.000001059      |      0.0000001348      |      0.000003515      |\n|  0.4  | 0.1455  |       0.0001729       |       0.00002516       |       0.0006561       |\n|  0.5  | 0.1515  |       0.005451        |       0.0008259        |        0.02154        |\n|  0.6  | 0.1455  |        0.05049        |        0.007344        |        0.1915         |\n|  0.7  | 0.1273  |        0.1501         |        0.01911         |        0.4984         |\n|  0.8  | 0.09697 |        0.1106         |        0.01072         |        0.2796         |\n|  0.9  | 0.05455 |       0.005764        |       0.0003144        |        0.0082         |\n|  1.0  |    0    |           0           |           0            |           0           |\n\n\n:::\n:::\n\n\n### I quattro passaggi in un'unica figura\n\nLa figura seguente mantiene separate le scale verticali. Questo evita di confondere probabilità a priori, verosimiglianze, prodotti non normalizzati e probabilità a posteriori, che hanno significati e scale differenti.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndati_passaggi <- bind_rows(\n  tibble(\n    theta = theta_griglia,\n    valore = prior,\n    passaggio = \"1. Prior\"\n  ),\n  tibble(\n    theta = theta_griglia,\n    valore = verosimiglianza,\n    passaggio = \"2. Verosimiglianza\"\n  ),\n  tibble(\n    theta = theta_griglia,\n    valore = peso_non_normalizzato,\n    passaggio = \"3. Prodotto non normalizzato\"\n  ),\n  tibble(\n    theta = theta_griglia,\n    valore = posterior,\n    passaggio = \"4. Posterior\"\n  )\n) |>\n  mutate(\n    passaggio = factor(\n      passaggio,\n      levels = c(\n        \"1. Prior\",\n        \"2. Verosimiglianza\",\n        \"3. Prodotto non normalizzato\",\n        \"4. Posterior\"\n      )\n    )\n  )\n\nggplot(dati_passaggi, aes(theta, valore)) +\n  geom_col(width = 0.075, fill = PRIMARY, alpha = 0.8) +\n  facet_wrap(vars(passaggio), scales = \"free_y\", ncol = 2) +\n  scale_x_continuous(breaks = theta_griglia) +\n  labs(\n    title = \"Aggiornamento bayesiano reso visibile\",\n    subtitle = \"Moltiplicazione punto per punto e successiva normalizzazione\",\n    x = expression(theta),\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![I quattro passaggi dell'aggiornamento bayesiano sulla griglia: prior, verosimiglianza, prodotto non normalizzato e distribuzione a posteriori. Le scale verticali sono separate perché le quattro quantità hanno significati e ordini di grandezza differenti.](01_grid_approx_files/figure-html/fig-grid-update-steps-1.png){#fig-grid-update-steps fig-align='center' fig-alt='Quattro pannelli di grafici a barre mostrano, nell\\'ordine, prior, verosimiglianza, prodotto non normalizzato e posterior sugli stessi valori di theta. Gli ultimi due pannelli hanno la stessa forma ma scale verticali diverse.' width=85%}\n:::\n:::\n\n\nLa terza e la quarta figura hanno la stessa forma. La normalizzazione cambia la scala verticale, non la plausibilità relativa dei diversi valori di $\\theta$.\n\n## Riassumere la distribuzione a posteriori\n\nUna volta ottenuta la distribuzione a posteriori, possiamo calcolare quantità che descrivono la posizione e l'incertezza residua.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia_posterior <- sum(theta_griglia * posterior)\n\nvarianza_posterior <- sum(\n  (theta_griglia - media_posterior)^2 * posterior\n)\n\nsd_posterior <- sqrt(varianza_posterior)\nmoda_posterior <- theta_griglia[which.max(posterior)]\n\nmedia_posterior\n#> [1] 0.706\nsd_posterior\n#> [1] 0.077\nmoda_posterior\n#> [1] 0.7\n```\n:::\n\n\nLa media a posteriori è 0.706, la deviazione standard è 0.077 e la moda è 0.7. Questi valori sono proprietà della distribuzione discreta costruita sulla griglia scelta.\n\nPossiamo anche calcolare direttamente la probabilità a posteriori di un evento, per esempio $\\theta>0.5$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_theta_maggiore_05 <- sum(posterior[theta_griglia > 0.5])\nprob_theta_maggiore_05\n#> [1] 0.978\n```\n:::\n\n\nNel modello discreto adottato,\n\n$$\nP(\\theta>0.5\\mid y)\n=\n0.978.\n$$\n\nQuesta probabilità è condizionata ai dati, al modello binomiale, al prior e alla griglia utilizzata.\n\n## La soluzione Beta-Binomiale\n\nL'approssimazione su griglia non è una procedura diversa dal teorema di Bayes. È un modo esplicito di eseguire lo stesso calcolo. Nel nostro esempio, il prior continuo è Beta(2, 2) e la verosimiglianza è binomiale. La coniugazione produce:\n\n$$\n\\theta \\mid y\n\\sim\n\\operatorname{Beta}(2+22,\\;2+8)\n=\n\\operatorname{Beta}(24,10).\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalpha_prior <- 2\nbeta_prior <- 2\n\nalpha_posterior <- alpha_prior + successi\nbeta_posterior <- beta_prior + prove - successi\n```\n:::\n\n\nLa media e l'intervallo di credibilità centrale al 95% sono:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia_beta <- alpha_posterior / (alpha_posterior + beta_posterior)\n\nintervallo_beta <- qbeta(\n  c(0.025, 0.975),\n  shape1 = alpha_posterior,\n  shape2 = beta_posterior\n)\n\nprob_beta_maggiore_05 <- pbeta(\n  0.5,\n  shape1 = alpha_posterior,\n  shape2 = beta_posterior,\n  lower.tail = FALSE\n)\n\nmedia_beta\n#> [1] 0.706\nintervallo_beta\n#> [1] 0.545 0.844\nprob_beta_maggiore_05\n#> [1] 0.993\n```\n:::\n\n\nCondizionatamente al modello e al prior scelti, la distribuzione a posteriori continua ha media 0.706, intervallo centrale al 95% da 0.545 a 0.844 e probabilità 0.993 di valori superiori a 0.5.\n\n### Griglia e soluzione analitica sono lo stesso aggiornamento\n\nValutiamo la densità Beta(24, 10) negli stessi punti della griglia e normalizziamola. I pesi ottenuti coincidono, a precisione numerica, con quelli prodotti dalla moltiplicazione del prior discreto per la verosimiglianza.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nposterior_beta_sulla_griglia <- dbeta(\n  theta_griglia,\n  shape1 = alpha_posterior,\n  shape2 = beta_posterior\n)\n\nposterior_beta_sulla_griglia <-\n  posterior_beta_sulla_griglia / sum(posterior_beta_sulla_griglia)\n\ndifferenza_massima <- max(\n  abs(posterior - posterior_beta_sulla_griglia)\n)\n\ndifferenza_massima\n#> [1] 3.33e-16\n```\n:::\n\n\nLa differenza massima è 3.3e-16. Non si tratta di due logiche inferenziali diverse: la soluzione Beta-Binomiale comprime in una formula analitica la stessa moltiplicazione resa visibile dalla griglia.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nconfronto_griglia <- tibble(\n  theta = rep(theta_griglia, 2),\n  probabilita = c(posterior, posterior_beta_sulla_griglia),\n  metodo = rep(\n    c(\"Prodotto su griglia\", \"Beta(24, 10) valutata sulla griglia\"),\n    each = length(theta_griglia)\n  )\n)\n\nggplot(confronto_griglia, aes(theta, probabilita, color = metodo)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 2) +\n  scale_color_manual(\n    values = c(\n      \"Prodotto su griglia\" = palette_qualitative[5],\n      \"Beta(24, 10) valutata sulla griglia\" = palette_qualitative[1]\n    )\n  ) +\n  scale_x_continuous(breaks = theta_griglia) +\n  labs(\n    title = \"Due rappresentazioni dello stesso aggiornamento\",\n    x = expression(theta),\n    y = \"Probabilità normalizzata sulla griglia\",\n    color = NULL\n  ) +\n  legenda_in_alto\n```\n\n::: {.cell-output-display}\n![Confronto tra la distribuzione a posteriori ottenuta mediante il prodotto sulla griglia e la Beta(24, 10) valutata e normalizzata sugli stessi punti. La sovrapposizione mostra che le due rappresentazioni esprimono il medesimo aggiornamento bayesiano.](01_grid_approx_files/figure-html/fig-grid-beta-binomial-comparison-1.png){#fig-grid-beta-binomial-comparison fig-align='center' fig-alt='Due linee con punti, quasi perfettamente sovrapposte, rappresentano la posterior calcolata sulla griglia e la densità Beta ventiquattro dieci normalizzata sugli stessi valori di theta.' width=85%}\n:::\n:::\n\n\n### Una griglia più fine\n\nUna griglia grossolana è utile per seguire i calcoli a mano. Una griglia più fine approssima meglio la distribuzione continua:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_fine <- seq(0, 1, length.out = 1001)\n\nprior_fine <- dbeta(theta_fine, 2, 2)\nprior_fine <- prior_fine / sum(prior_fine)\n\nlikelihood_fine <- dbinom(successi, prove, theta_fine)\n\nposterior_fine <- prior_fine * likelihood_fine\nposterior_fine <- posterior_fine / sum(posterior_fine)\n\nmedia_fine <- sum(theta_fine * posterior_fine)\nmedia_fine\n#> [1] 0.706\n```\n:::\n\n\nLa media ottenuta con la griglia fine è 0.706, praticamente coincidente con la media analitica 0.706.\n\n## Seconda applicazione: riconoscimento di un'emozione\n\nConsideriamo ora un compito binario ipotetico. Un partecipante osserva dieci volti e identifica correttamente la rabbia in sette prove. Per fini didattici, adottiamo un prior Beta(4, 6), con media 0.4. Questo prior non viene presentato come una proprietà generale della letteratura: rappresenta semplicemente un'aspettativa iniziale esplicita per l'esempio.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncorrette <- 7\nprove_emozioni <- 10\ntheta_emozioni <- seq(0, 1, length.out = 1001)\n\nprior_emozioni <- dbeta(theta_emozioni, 4, 6)\nprior_emozioni <- prior_emozioni / sum(prior_emozioni)\n\nlikelihood_emozioni <- dbinom(\n  corrette,\n  prove_emozioni,\n  theta_emozioni\n)\n\npeso_emozioni <- prior_emozioni * likelihood_emozioni\nposterior_emozioni <- peso_emozioni / sum(peso_emozioni)\n```\n:::\n\n\nAnche in questo caso l'intero aggiornamento è contenuto in due operazioni:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npeso_emozioni <- prior_emozioni * likelihood_emozioni\nposterior_emozioni <- peso_emozioni / sum(peso_emozioni)\n```\n:::\n\n\nIl primo comando combina, punto per punto, aspettative iniziali e compatibilità con i dati. Il secondo trasforma i prodotti in probabilità.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia_emozioni <- sum(theta_emozioni * posterior_emozioni)\nmoda_emozioni <- theta_emozioni[which.max(posterior_emozioni)]\n\ncdf_emozioni <- cumsum(posterior_emozioni)\nlimite_inf_94 <- theta_emozioni[which(cdf_emozioni >= 0.03)[1]]\nlimite_sup_94 <- theta_emozioni[which(cdf_emozioni >= 0.97)[1]]\n\nmedia_emozioni\n#> [1] 0.55\nmoda_emozioni\n#> [1] 0.556\nc(limite_inf_94, limite_sup_94)\n#> [1] 0.343 0.748\n```\n:::\n\n\nLa media a posteriori è 0.55, la moda è 0.556 e l'intervallo centrale al 94% va approssimativamente da 0.343 a 0.748. Con sole dieci prove, l'incertezza rimane ampia.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndati_emozioni <- bind_rows(\n  tibble(\n    theta = theta_emozioni,\n    valore = prior_emozioni,\n    componente = \"Prior Beta(4, 6)\"\n  ),\n  tibble(\n    theta = theta_emozioni,\n    valore = likelihood_emozioni / sum(likelihood_emozioni),\n    componente = \"Verosimiglianza normalizzata per il grafico\"\n  ),\n  tibble(\n    theta = theta_emozioni,\n    valore = posterior_emozioni,\n    componente = \"Posterior\"\n  )\n) |>\n  mutate(\n    componente = factor(\n      componente,\n      levels = c(\n        \"Prior Beta(4, 6)\",\n        \"Verosimiglianza normalizzata per il grafico\",\n        \"Posterior\"\n      )\n    )\n  )\n\nggplot(dati_emozioni, aes(theta, valore, color = componente)) +\n  geom_line(linewidth = 1.1) +\n  scale_color_manual(\n    values = c(\n      \"Prior Beta(4, 6)\" = palette_qualitative[8],\n      \"Verosimiglianza normalizzata per il grafico\" =\n        palette_qualitative[1],\n      \"Posterior\" = palette_qualitative[5]\n    )\n  ) +\n  labs(\n    title = \"Aggiornamento nel compito di riconoscimento\",\n    subtitle = paste0(corrette, \" risposte corrette su \", prove_emozioni),\n    x = expression(theta),\n    y = \"Peso normalizzato\",\n    color = NULL\n  ) +\n  legenda_in_alto\n```\n\n::: {.cell-output-display}\n![Aggiornamento bayesiano per il compito di riconoscimento delle emozioni con 7 risposte corrette su 10. Il grafico confronta il prior Beta(4, 6), la verosimiglianza normalizzata a fini grafici e la distribuzione a posteriori.](01_grid_approx_files/figure-html/fig-grid-emotion-update-1.png){#fig-grid-emotion-update fig-align='center' fig-alt='Tre curve mostrano il prior, la verosimiglianza normalizzata e la posterior per una proporzione di risposte corrette. La posterior è spostata verso valori più alti rispetto al prior, ma conserva una dispersione ampia.' width=85%}\n:::\n:::\n\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nL'approssimazione su griglia rende concreto il passaggio più importante dell'inferenza bayesiana.\n\n1. **Prior e verosimiglianza devono essere valutati sugli stessi valori del parametro.** Ogni riga della griglia rappresenta una possibilità distinta.\n2. **La moltiplicazione è punto per punto.** Un valore riceve un peso elevato soltanto se è sostenuto sia dal prior sia dai dati.\n3. **Il prodotto non è ancora una distribuzione di probabilità.** La divisione per la somma dei prodotti è necessaria per ottenere la posterior.\n4. **La normalizzazione non modifica i rapporti relativi.** Cambia la scala, non la forma dell'informazione combinata.\n5. **La soluzione analitica e la griglia applicano la stessa logica.** Nel modello Beta-Binomiale, la coniugazione rende disponibile una formula chiusa; la griglia mostra ciò che quella formula sta facendo.\n6. **La posterior è condizionata alle assunzioni adottate.** Un calcolo corretto non elimina le scelte relative al modello, al prior, ai dati e alla risoluzione numerica.\n\nIl valore pedagogico della griglia non consiste principalmente nella sua efficienza. Consiste nel fatto che nessun passaggio rimane nascosto: per ogni valore di $\\theta$ possiamo vedere il prior, la verosimiglianza, il prodotto e la probabilità a posteriori.\n\n## Esercizi {.unnumbered .unlisted}\n\n### Esercizio 1 — Comprendere {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 15 minuti*\n\nConsidera una griglia ridotta con tre valori:\n\n| $\\theta$ | Prior | Verosimiglianza |\n|---:|---:|---:|\n| 0.3 | 0.20 | 0.05 |\n| 0.5 | 0.50 | 0.25 |\n| 0.7 | 0.30 | 0.50 |\n\n1. Calcola il prodotto `prior × verosimiglianza` per ciascuna riga.\n2. Somma i tre prodotti.\n3. Dividi ogni prodotto per la somma e ottieni la distribuzione a posteriori.\n4. Spiega perché $\\theta=0.7$ riceve la probabilità a posteriori più alta, anche se il prior era massimo in $\\theta=0.5$.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nI prodotti sono 0.010, 0.125 e 0.150. La loro somma è 0.285.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\nLe probabilità a posteriori sono:\n\n$$\n\\begin{aligned}\nP(\\theta=0.3\\mid y) &= 0.010/0.285 \\approx 0.035,\\\\\nP(\\theta=0.5\\mid y) &= 0.125/0.285 \\approx 0.439,\\\\\nP(\\theta=0.7\\mid y) &= 0.150/0.285 \\approx 0.526.\n\\end{aligned}\n$$\n\nIl prior favoriva $\\theta=0.5$, ma i dati sono due volte più compatibili con $\\theta=0.7$ che con $\\theta=0.5$. Il prodotto combina le due informazioni. Il valore 0.7 non vince perché ha il prior più alto o la verosimiglianza più alta considerati separatamente, ma perché ottiene il prodotto più alto.\n:::\n\n### Esercizio 2 — Prevedere {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 10 minuti*\n\nSenza eseguire calcoli completi, prevedi che cosa accadrà nei seguenti casi.\n\n1. Il prior assegna probabilità zero a $\\theta=0.7$, mentre la verosimiglianza è massima in quel punto.\n2. Il prior è quasi uniforme e la verosimiglianza è molto concentrata intorno a 0.7.\n3. Il prior è molto concentrato intorno a 0.4, ma un campione molto grande produce una verosimiglianza concentrata intorno a 0.7.\n4. Tutti i prodotti `prior × verosimiglianza` vengono moltiplicati per 100 prima della normalizzazione.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nRicorda che il prodotto con zero è zero e che la normalizzazione divide tutti i valori per la stessa somma.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\n1. La probabilità a posteriori di $\\theta=0.7$ rimane zero. Un prior discreto che assegna probabilità esattamente zero esclude quel valore dall'aggiornamento.\n2. La posterior avrà una forma molto simile alla verosimiglianza, perché il prior modifica poco i rapporti relativi.\n3. La posterior sarà spostata verso 0.7. Quanto il prior continuerà a influire dipende dalla sua concentrazione e dall'informazione contenuta nei dati; con molti dati, la verosimiglianza tende a dominare salvo conflitti estremi o valori esclusi dal prior.\n4. La posterior non cambia. Il fattore 100 compare sia al numeratore sia nella somma usata per normalizzare e quindi si cancella.\n:::\n\n### Esercizio 3 — Modificare {.unnumbered .unlisted}\n\n*Codice: sì · Tempo indicativo: 20 minuti*\n\nMantieni invariati i dati del dilemma del carrello ferroviario, ma sostituisci il prior Beta(2, 2) con:\n\n1. un prior Beta(8, 4), che favorisce valori relativamente alti di $\\theta$;\n2. un prior Beta(4, 8), che favorisce valori relativamente bassi di $\\theta$.\n\nPer ciascun prior:\n\n- calcola i pesi a priori sulla stessa griglia;\n- moltiplicali per la stessa verosimiglianza;\n- normalizza;\n- confronta media e moda a posteriori;\n- osserva, nella tabella, come cambia il prodotto per $\\theta=0.5$ e $\\theta=0.7$.\n\nPrima di eseguire il codice, scrivi quale delle due posteriori prevedi sarà più spostata verso destra.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nÈ sufficiente modificare i parametri in `dbeta()`:\n\n```r\npesi_prior <- dbeta(theta_griglia, shape1 = 8, shape2 = 4)\n```\n\noppure:\n\n```r\npesi_prior <- dbeta(theta_griglia, shape1 = 4, shape2 = 8)\n```\n\nPoi ripeti normalizzazione, moltiplicazione e normalizzazione finale.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\nLa verosimiglianza è identica nei due casi, perché i dati non cambiano. Cambia invece il primo fattore del prodotto. Il prior Beta(8, 4) assegna più peso iniziale ai valori alti e produce una posterior più spostata verso destra; il prior Beta(4, 8) penalizza maggiormente tali valori e produce una posterior più spostata verso sinistra.\n\nIl confronto rende visibile che la posterior non deriva dai dati soltanto. Per ogni valore della griglia, la stessa verosimiglianza viene moltiplicata per un peso a priori diverso. Con un campione di 30 persone i dati esercitano comunque un'influenza importante, quindi la posterior non coincide semplicemente con nessuno dei due prior.\n:::\n\n### Esercizio 4 — Criticare {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 10 minuti*\n\nValuta criticamente la seguente affermazione:\n\n> “Il prior e la verosimiglianza sono due distribuzioni di probabilità su $\\theta$. Basta moltiplicarle e il prodotto è già la distribuzione a posteriori.”\n\nIndividua almeno tre problemi e riscrivi l'affermazione in forma corretta.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nChiediti: la verosimiglianza deve sommare a uno sui valori di $\\theta$? Il prodotto deve sommare a uno? Che cosa viene moltiplicato esattamente?\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Elementi per la risposta\"}\nIl prior è una distribuzione sul parametro; la verosimiglianza, invece, è una funzione del parametro con i dati mantenuti fissi e non deve essere normalizzata rispetto a $\\theta$. La moltiplicazione viene eseguita punto per punto sugli stessi valori della griglia. I prodotti risultanti sono pesi posteriori **non normalizzati** e, in generale, non sommano a uno. Solo dopo averli divisi per la loro somma si ottiene la distribuzione a posteriori.\n\nUna formulazione corretta è: “Per ciascun valore candidato di $\\theta$, moltiplichiamo il peso a priori per la verosimiglianza dei dati. Normalizziamo poi tutti i prodotti dividendo per la loro somma; i valori ottenuti sono le probabilità a posteriori sulla griglia.”\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.5.2\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.0            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.0           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.2              fastmap_1.2.0         tensorA_0.36.2.1     \n#>  [7] digest_0.6.39         timechange_0.4.0      estimability_2.0.0   \n#> [10] lifecycle_1.0.5       magrittr_2.0.5        compiler_4.6.1       \n#> [13] rlang_1.3.0           tools_4.6.1           yaml_2.3.12          \n#> [16] knitr_1.51            labeling_0.4.3        bridgesampling_1.2-1 \n#> [19] htmlwidgets_1.6.4     pkgbuild_1.4.8        curl_7.1.0           \n#> [22] RColorBrewer_1.1-3    abind_1.4-8           purrr_1.2.2          \n#> [25] grid_4.6.1            stats4_4.6.1          xtable_1.8-8         \n#> [28] inline_0.3.21         emmeans_2.0.4         scales_1.4.0         \n#> [31] cli_3.6.6             mvtnorm_1.4-2         rmarkdown_2.31       \n#> [34] generics_0.1.4        otel_0.2.0            RcppParallel_5.1.11-2\n#> [37] cachem_1.1.0          stringr_1.6.0         parallel_4.6.1       \n#> [40] vctrs_0.7.3           V8_8.2.0              Matrix_1.7-5         \n#> [43] jsonlite_2.0.0        arrayhelpers_1.1-1    glue_1.8.1           \n#> [46] codetools_0.2-20      distributional_0.8.1  lubridate_1.9.5      \n#> [49] stringi_1.8.7         gtable_0.3.6          QuickJSR_1.10.0      \n#> [52] pillar_1.11.1         htmltools_0.5.9       Brobdingnag_1.2-9    \n#> [55] R6_2.6.1              textshaping_1.0.5     rprojroot_2.1.1      \n#> [58] evaluate_1.0.5        lattice_0.22-9        backports_1.5.1      \n#> [61] memoise_2.0.1         broom_1.0.13          snakecase_0.11.1     \n#> [64] rstantools_2.6.0      coda_0.19-4.1         gridExtra_2.3.1      \n#> [67] nlme_3.1-170          checkmate_2.3.4       xfun_0.60            \n#> [70] pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "01_grid_approx_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}