{
  "hash": "ab7a33c301472e5a8e61cb87b1cb3fcf",
  "result": {
    "engine": "knitr",
    "markdown": "# La decisione sul singolo paziente: dal punteggio osservato alla probabilità clinica {#sec-bayesian-inference-single-patient-cutoff}\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n```\n:::\n\n:::\n\n::: {.callout-important appearance=\"minimal\" .chapter-status}\n**Da sapere.** Un punteggio osservato non coincide con il punteggio vero, perché contiene errore di misura. L’attendibilità determina quanto la stima debba essere corretta verso la media normativa. Nel modello Normale-Normale, la media a posteriori coincide con la stima di Kelley, ma la distribuzione a posteriori consente anche di quantificare direttamente la probabilità che il punteggio vero superi una soglia clinica.\n\n**Da saper fare.** Calcolare la stima di Kelley e la distribuzione a posteriori del punteggio vero; ricavare e interpretare $P(\\theta > c \\mid X)$ e il relativo intervallo di credibilità; distinguere la posterior del punteggio vero dalla distribuzione predittiva di una nuova misurazione; formulare una conclusione clinica che renda esplicita l’incertezza e non trasformi il cut-off in una diagnosi automatica.\n\n**Approfondimento facoltativo.** La derivazione algebrica dell’equivalenza tra Kelley e la media a posteriori, l’analisi di sensibilità rispetto all’attendibilità, la distribuzione predittiva completa e la formulazione delle decisioni mediante funzioni di perdita possono essere rimandate in una prima lettura.\n\n[Che cosa significano queste etichette?](../../guida-al-manuale.qmd#sec-percorsi-lettura)\n:::\n\n## Una vignetta clinica: quando due punti fanno la differenza {#sec-vignetta-clinica}\n\nImmaginiamo una situazione molto comune nella pratica psicologica. Un clinico somministra a un paziente un test standardizzato per la depressione. Il manuale indica un *cut-off* clinico pari a 70. Il paziente ottiene un punteggio osservato di 72.\n\nLa lettura ingenua sembra immediata:\n\n$$\n72 > 70.\n$$\n\nIl paziente è dunque sopra soglia? La risposta corretta è: *probabilmente sì, ma non con certezza*. Due punti sopra il cut-off non autorizzano, da soli, una conclusione diagnostica netta, perché ogni punteggio psicometrico contiene un errore di misura.\n\nQuesto capitolo mostra come riformulare la domanda clinica in modo più rigoroso. Non ci limiteremo a chiedere se il punteggio osservato supera la soglia, ma chiederemo:\n\n::: {.callout-note title=\"La domanda clinica\" icon=false}\nDato il punteggio osservato $X = 72$, qual è la probabilità che il **punteggio vero** del paziente, indicato con $\\theta$, superi effettivamente il cut-off clinico di 70?\n\n$$\nP(\\theta > 70 \\mid X = 72).\n$$\n:::\n\nQuesta formulazione è più vicina al problema reale del clinico: prendere decisioni in condizioni di incertezza, senza trasformare un risultato psicometrico in una certezza artificiale.\n\n## Il punteggio osservato non è il punteggio vero {#sec-punteggio-osservato-vero}\n\nNella teoria classica dei test, il punteggio osservato $X$ viene rappresentato come la somma di due componenti:\n$$\nX = \\theta + \\varepsilon,\n$$\ndove:\n\n- $\\theta$ è il **punteggio vero**, ovvero la componente stabile del costrutto misurato secondo il modello psicometrico;\n- $\\varepsilon$ è l'**errore di misura**, ovvero la componente accidentale della misurazione.\n\nÈ importante non attribuire al termine *punteggio vero* un significato ontologico troppo forte. Nel nostro esempio, $\\theta$ non è \"la depressione reale\" del paziente in senso assoluto. Si tratta piuttosto del valore latente che il test mira a stimare, ovvero la parte stabile e sistematica del punteggio, separata dalle fluttuazioni casuali della somministrazione.\n\nL'errore di misura non è un dettaglio marginale. Stanchezza, ansia momentanea, distrazione, comprensione di alcuni item, desiderabilità sociale, condizioni ambientali e variabilità giornaliera possono modificare il punteggio osservato senza riflettere un cambiamento reale nel costrutto psicologico.\n\nLa qualità dello strumento è riassunta dall'**attendibilità** $\\rho$, definita come la proporzione della varianza osservata attribuibile al punteggio vero:\n$$\n\\rho = \\frac{\\sigma^2_\\theta}{\\sigma^2_X}.\n$$\nSe l'attendibilità è pari a $\\rho = 0.85$, l'85% della varianza osservata riflette differenze nel punteggio vero, mentre il 15% riflette l'errore di misura.\n\n## Il contesto numerico dell'esempio {#sec-contesto-numerico}\n\nIn tutto il capitolo useremo lo stesso scenario numerico:\n\n- media normativa osservata: $\\mu_X = 70$;\n- deviazione standard normativa osservata: $\\sigma_X = 15$;\n- attendibilità del test: $\\rho = 0.85$;\n- punteggio osservato del paziente: $X = 72$;\n- cut-off clinico: $c = 70$.\n\nDa questi valori derivano due quantità fondamentali:\n\n$$\n\\sigma^2_\\theta = \\rho \\sigma^2_X,\n\\qquad\n\\sigma^2_e = (1 - \\rho) \\sigma^2_X.\n$$\n\nLa prima è la varianza dei punteggi veri nella popolazione. La seconda è la varianza dell'errore di misura. La radice quadrata di $\\sigma^2_e$ è l'**errore standard della misura** (*standard error of measurement*, SEM):\n\n$$\n\\sigma_e = \\sigma_X \\sqrt{1 - \\rho}.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parametri del test\nmu_pop    <- 70      # media normativa osservata\nsigma_X   <- 15      # deviazione standard normativa osservata\nrho       <- 0.85    # attendibilita'\nX_obs     <- 72      # punteggio osservato\ncut_off   <- 70      # cut-off clinico\n\n# Componenti della varianza secondo la teoria classica dei test\nsigma_theta <- sqrt(rho) * sigma_X\nsigma_e     <- sigma_X * sqrt(1 - rho)\n\ncat(\"DS dei punteggi veri:\", round(sigma_theta, 2), \"\\n\")\n#> DS dei punteggi veri: 13.8\ncat(\"Errore standard della misura (SEM):\", round(sigma_e, 2), \"\\n\")\n#> Errore standard della misura (SEM): 5.81\n```\n:::\n\n\nNel nostro esempio, il SEM è circa 5.81. Ciò significa che il punteggio osservato di un singolo paziente può oscillare di diversi punti rispetto al punteggio effettivo. Un punteggio di 72, quindi, non deve essere interpretato come una misurazione perfetta, ma come un'informazione utile, seppur incerta.\n\n## Kelley: la risposta classica come shrinkage verso la media {#sec-kelley-shrinkage}\n\nUna prima risposta al problema della stima del punteggio vero è fornita dalla formula di @Kelley1923:\n\n$$\n\\hat{\\theta}_{\\text{Kelley}} = \\rho X + (1 - \\rho)\\mu_X.\n$$\n\nLa formula ha una struttura molto semplice: combina il punteggio osservato del paziente con la media della popolazione di riferimento. Il peso del punteggio osservato corrisponde all'attendibilità del test.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_kelley <- rho * X_obs + (1 - rho) * mu_pop\n\ncat(\"Stima di Kelley:\", round(theta_kelley, 2), \"\\n\")\n#> Stima di Kelley: 71.7\n```\n:::\n\n\nLa stima corretta è 71.7 e non 72. La differenza è minima, perché il test ha un'elevata attendibilità, ma il principio è importante: quando il test non è perfettamente attendibile, la stima migliore del punteggio effettivo si sposta verso la media della popolazione. Questo fenomeno è un esempio di *shrinkage* o regressione verso la media.\n\nL'intuizione è la seguente: se una parte del punteggio osservato dipende dall'errore casuale, allora un valore superiore alla media può essere in parte dovuto a una fluttuazione accidentale. Per questo motivo, la stima del punteggio vero non coincide con il punteggio osservato, ma si colloca tra il punteggio individuale e la media del gruppo.\n\n### L'incertezza della stima di Kelley\n\nLa stima puntuale non basta. È necessario quantificare l'incertezza della stima del punteggio vero. Nel modello classico, tale incertezza è descritta dall'**errore standard dell'errore di stima** (*standard error of estimate*, SEE):\n\n$$\n\\text{SEE} = \\sigma_X \\sqrt{\\rho(1 - \\rho)}.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSEE <- sigma_X * sqrt(rho * (1 - rho))\nIC_kelley <- theta_kelley + qnorm(c(.025, .975)) * SEE\n\ncat(\"SEE:\", round(SEE, 2), \"\\n\")\n#> SEE: 5.36\ncat(\"Intervallo al 95% secondo Kelley: [\",\n    round(IC_kelley[1], 1), \", \", round(IC_kelley[2], 1), \"]\\n\", sep = \"\")\n#> Intervallo al 95% secondo Kelley: [61.2, 82.2]\n```\n:::\n\n\nL'intervallo ottenuto è ampio: include valori sensibilmente inferiori e superiori alla soglia clinica. Questo è il primo messaggio sostanziale del capitolo. Anche se il punteggio osservato supera il cut-off, l'incertezza di misura non consente un'interpretazione dicotomica ingenua.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Stima di Kelley del punteggio vero. La curva rappresenta l'incertezza residua attorno alla stima; la linea tratteggiata indica il cut-off clinico.](07_singolo_paziente_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n### Cosa significa l'intervallo classico?\n\nL'intervallo costruito attorno alla stima di Kelley non deve essere interpretato come la probabilità che il punteggio vero di questo specifico paziente cada nell'intervallo. Secondo l'interpretazione frequentista, il punteggio vero è un valore fisso, ma sconosciuto. La probabilità riguarda la procedura: in condizioni ideali di ripetizione del processo di campionamento e costruzione dell'intervallo, il 95% degli intervalli conterrebbe il valore vero, sotto le assunzioni del modello.\n\nQuesta interpretazione è corretta, ma non risponde direttamente alla domanda che interessa al clinico. Il clinico non deve decidere in base a una procedura ripetuta infinite volte, ma deve decidere cosa pensare del paziente che ha di fronte, in base al punteggio osservato.\n\n## La riformulazione bayesiana {#sec-riformulazione-bayesiana}\n\nIl modello bayesiano riformula il problema in modo diretto. Prima di osservare il paziente, descriviamo la distribuzione dei punteggi reali nella popolazione. Dopo aver osservato il punteggio del paziente, aggiorniamo tale distribuzione.\n\nIl modello è:\n\n$$\n\\begin{aligned}\n\\theta &\\sim \\mathcal{N}(\\mu_X, \\sigma^2_\\theta), \\\\\nX \\mid \\theta &\\sim \\mathcal{N}(\\theta, \\sigma^2_e).\n\\end{aligned}\n$$\n\nNel nostro esempio:\n\n$$\n\\sigma^2_\\theta = \\rho \\sigma^2_X,\n\\qquad\n\\sigma^2_e = (1 - \\rho)\\sigma^2_X.\n$$\n\nQuesta specificazione è importante. Se $\\sigma_X$ è la deviazione standard osservata nel campione normativo, essa include sia la variabilità vera sia l'errore di misura. La prior su $\\theta$ deve quindi usare la varianza dei punteggi veri, $\\sigma^2_\\theta$, non l'intera varianza osservata $\\sigma^2_X$.\n\nPoiché la prior e la verosimiglianza sono entrambe distribuzioni normali, anche la distribuzione a posteriori è normale:\n\n$$\n\\theta \\mid X \\sim \\mathcal{N}(\\mu_{\\text{post}}, \\sigma^2_{\\text{post}}).\n$$\n\nI parametri della posterior sono:\n\n$$\n\\sigma^2_{\\text{post}} = \\left(\\frac{1}{\\sigma^2_\\theta} + \\frac{1}{\\sigma^2_e}\\right)^{-1},\n\\qquad\n\\mu_{\\text{post}} = \\sigma^2_{\\text{post}}\n\\left(\\frac{\\mu_X}{\\sigma^2_\\theta} + \\frac{X}{\\sigma^2_e}\\right).\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsigma_theta2 <- sigma_theta^2\nsigma_e2     <- sigma_e^2\n\nsigma_post2 <- 1 / (1 / sigma_theta2 + 1 / sigma_e2)\nsigma_post  <- sqrt(sigma_post2)\n\nmu_post <- sigma_post2 * (mu_pop / sigma_theta2 + X_obs / sigma_e2)\n\ncat(\"Media a posteriori:\", round(mu_post, 2), \"\\n\")\n#> Media a posteriori: 71.7\ncat(\"DS a posteriori:\", round(sigma_post, 2), \"\\n\")\n#> DS a posteriori: 5.36\n```\n:::\n\n\n::: {.callout-tip title=\"Perché Kelley e Bayes coincidono qui?\" icon=false}\nNel modello Normale-Normale specificato sopra, la media a posteriori coincide con la stima di @Kelley1923:\n\n$$\n\\mu_{\\text{post}} = \\rho X + (1 - \\rho)\\mu_X.\n$$\n\nQuesta equivalenza non significa che i due approcci siano identici. Significa che, sotto queste assunzioni, producono la stessa stima puntuale. La differenza sta nel fatto che il modello bayesiano restituisce l'intera distribuzione a posteriori di $\\theta$.\n\nPoiché la posterior è normale, media, mediana e moda coincidono. In questo caso la stima di Kelley coincide anche con la moda a posteriori, spesso indicata come MAP. Non è però corretto chiamarla \"massima verosimiglianza a posteriori\": la denominazione appropriata è **massimo a posteriori** (*maximum a posteriori*, MAP).\n:::\n\n## La domanda clinica diretta {#sec-domanda-clinica-diretta}\n\nOra possiamo rispondere alla domanda che ha motivato il capitolo:\n\n$$\nP(\\theta > 70 \\mid X = 72).\n$$\n\nNel modello bayesiano, tale quantità si calcola direttamente dalla distribuzione a posteriori:\n\n$$\nP(\\theta > c \\mid X) = 1 - \\Phi\\left(\\frac{c - \\mu_{\\text{post}}}{\\sigma_{\\text{post}}}\\right),\n$$\ndove $\\Phi$ è la funzione di ripartizione della normale standard.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_sopra_cutoff <- 1 - pnorm(cut_off, mean = mu_post, sd = sigma_post)\nIC_post <- qnorm(c(.025, .975), mean = mu_post, sd = sigma_post)\n\ncat(\"P(theta > 70 | X = 72):\",\n    round(prob_sopra_cutoff * 100, 1), \"%\\n\")\n#> P(theta > 70 | X = 72): 62.5 %\ncat(\"Intervallo di credibilita' al 95%: [\",\n    round(IC_post[1], 1), \", \", round(IC_post[2], 1), \"]\\n\", sep = \"\")\n#> Intervallo di credibilita' al 95%: [61.2, 82.2]\n```\n:::\n\n\nNel nostro esempio, la probabilità che il punteggio vero del paziente superi la soglia clinica è di circa il **62%**. Questo valore è informativo proprio perché non impone una decisione binaria. Ci dice che il superamento della soglia è più plausibile del non superamento, ma anche che l'incertezza rimane sostanziale.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Distribuzione a priori e a posteriori del punteggio vero. L'area evidenziata rappresenta la probabilità che il punteggio vero superi il cut-off clinico.](07_singolo_paziente_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nL'intervallo di credibilità al 95% ha un'interpretazione diretta: dati il modello, i parametri normativi e il punteggio osservato, c'è il 95% di probabilità che il punteggio vero del paziente ricada in quell'intervallo. Questa affermazione è legittima nel paradigma bayesiano, in quanto la probabilità viene utilizzata per descrivere l'incertezza epistemica su $\\theta$.\n\n## Posterior e predittiva: due domande diverse {#sec-posterior-predittiva}\n\nLa posterior sul punteggio vero risponde alla domanda:\n\n> Qual è il livello latente del paziente nel costrutto misurato?\n\nTuttavia, il clinico potrebbe avere un'altra domanda:\n\n> Se ripetessimo il test, quale nuovo punteggio osservato potremmo ottenere?\n\nQuesta seconda domanda riguarda la **distribuzione predittiva a posteriori**. Per il modello Normale-Normale:\n\n$$\n\\tilde{X} \\mid X \\sim \\mathcal{N}\\left(\\mu_{\\text{post}},\\; \\sigma^2_{\\text{post}} + \\sigma^2_e\\right).\n$$\n\nLa varianza predittiva è maggiore della varianza a posteriori perché include due fonti di incertezza:\n\n1. l'incertezza residua sul punteggio vero $\\theta$;\n2. il nuovo errore di misura che si avrebbe in una seconda somministrazione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsigma_pred <- sqrt(sigma_post2 + sigma_e2)\nIC_pred <- qnorm(c(.025, .975), mean = mu_post, sd = sigma_pred)\nprob_pred_sopra <- 1 - pnorm(cut_off, mean = mu_post, sd = sigma_pred)\n\ncat(\"DS predittiva:\", round(sigma_pred, 2), \"\\n\")\n#> DS predittiva: 7.9\ncat(\"Intervallo predittivo al 95%: [\",\n    round(IC_pred[1], 1), \", \", round(IC_pred[2], 1), \"]\\n\", sep = \"\")\n#> Intervallo predittivo al 95%: [56.2, 87.2]\ncat(\"P(X_nuovo > 70 | X = 72):\",\n    round(prob_pred_sopra * 100, 1), \"%\\n\")\n#> P(X_nuovo > 70 | X = 72): 58.5 %\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Confronto tra distribuzione a priori, posterior del punteggio vero e distribuzione predittiva per una nuova somministrazione.](07_singolo_paziente_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n::: {.callout-important title=\"Quale distribuzione usare per la decisione clinica?\" icon=false}\nPer stabilire se il paziente si trovi verosimilmente sopra la soglia del costrutto misurato, la distribuzione rilevante è la **posterior del punteggio vero** $p(\\theta \\mid X)$.\n\nLa distribuzione predittiva $p(\\tilde{X} \\mid X)$ è invece utile per pianificare una rivalutazione o per capire quale variabilità potremmo osservare se il test venisse ripetuto. Non risponde alla stessa domanda della posterior: descrive un futuro punteggio osservato, non il punteggio vero del paziente.\n:::\n\n## Dalla probabilità alla decisione clinica {#sec-decisione-clinica}\n\nIl risultato bayesiano non produce automaticamente una diagnosi. Produce una quantità interpretabile:\n\n$$\nP(\\theta > 70 \\mid X = 72) \\approx 0.62.\n$$\n\nTale probabilità deve essere integrata con il contesto clinico: colloquio, anamnesi, funzionamento quotidiano, osservazioni comportamentali, altri strumenti diagnostici e costi degli errori decisionali.\n\nUna lettura ragionevole del nostro esempio è la seguente:\n\n::: {.callout-note title=\"Una formulazione clinica possibile\" icon=false}\nDato il punteggio osservato di 72, la probabilità che il punteggio vero del paziente superi la soglia clinica di 70 è di circa 62%. Il risultato suggerisce un'attenzione clinica, ma non è abbastanza forte da poter sostenere una conclusione diagnostica basata esclusivamente su questo test. È opportuno integrare il dato psicometrico con altre informazioni cliniche e, se necessario, pianificare una rivalutazione.\n:::\n\nLa forza dell'approccio bayesiano non è dunque quella di rendere la decisione automatica. È quella di rendere esplicita l'incertezza che una decisione automatica nasconderebbe.\n\n::: {.callout-tip collapse=true title=\"Decisioni e funzioni di perdita\"}\nIn un'applicazione più completa, la decisione potrebbe essere formulata in termini di costi e benefici. Un falso negativo può avere conseguenze diverse rispetto a un falso positivo. In alcune situazioni cliniche, una probabilità del 62% potrebbe giustificare un approfondimento, mentre in altre potrebbe non essere sufficiente per avviare un intervento. La probabilità a posteriori non sostituisce il giudizio clinico, ma lo rende più trasparente.\n:::\n\n## Perché l'attendibilità cambia la conclusione {#sec-sensibilita-attendibilita}\n\nLa probabilità che il paziente superi la soglia dipende non solo dal punteggio osservato, ma anche dall'attendibilità dello strumento utilizzato. A parità di $X = 72$, un test molto attendibile produce una posterior più concentrata vicino al punteggio osservato, mentre un test poco attendibile produce una posterior più incerta e più vicina alla media normativa.\n\nIl codice seguente mostra come varia $P(\\theta > 70 \\mid X = 72)$ al variare di $\\rho$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_true_above <- function(rho_value, x_obs, threshold, mu, sigma_X) {\n  sigma_theta_value <- sqrt(rho_value) * sigma_X\n  sigma_e_value     <- sqrt(1 - rho_value) * sigma_X\n\n  sigma_post2_value <- 1 / (1 / sigma_theta_value^2 +\n                              1 / sigma_e_value^2)\n  mu_post_value <- sigma_post2_value *\n    (mu / sigma_theta_value^2 + x_obs / sigma_e_value^2)\n\n  1 - pnorm(threshold, mean = mu_post_value, sd = sqrt(sigma_post2_value))\n}\n\nrho_seq <- seq(0.50, 0.99, by = 0.01)\nprobs <- sapply(\n  rho_seq,\n  prob_true_above,\n  x_obs = X_obs,\n  threshold = cut_off,\n  mu = mu_pop,\n  sigma_X = sigma_X\n)\n\ndf_sens <- data.frame(rho = rho_seq, prob = probs)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Probabilità che il punteggio vero superi il cut-off al variare dell'attendibilità del test.](07_singolo_paziente_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nIl grafico rende evidente un aspetto spesso sottovalutato: l'attendibilità non è un dettaglio tecnico da consultare solo nel manuale del test. Si tratta di un'informazione clinicamente rilevante. Due test con lo stesso cut-off e lo stesso punteggio osservato possono condurre a conclusioni diverse se hanno un'attendibilità differente.\n\n## Sintesi operativa {#sec-sintesi-operativa}\n\nIl percorso seguito nel capitolo può essere riassunto in quattro passaggi.\n\n1. **Non leggere il cut-off in modo meccanico.** Un punteggio osservato appena sopra soglia non equivale a una certezza clinica.\n2. **Correggere il punteggio osservato per l'errore di misura.** La formula di Kelley mostra lo shrinkage verso la media normativa.\n3. **Riformulare la stima come posterior bayesiana.** Nel modello Normale-Normale, Kelley coincide con la media posterior, ma la posterior offre un'informazione più ricca.\n4. **Calcolare la probabilità clinica di interesse.** La domanda rilevante diventa $P(\\theta > c \\mid X)$, non semplicemente $X > c$.\n\n| Domanda | Quantità rilevante | Interpretazione |\n|---|---|---|\n| Qual è la miglior stima del punteggio vero? | $\\mu_{\\text{post}}$ / Kelley | Stima corretta verso la media |\n| Quanto resta incerta la stima? | Intervallo di credibilità | Incertezza sul punteggio vero |\n| Il paziente è probabilmente sopra soglia? | $P(\\theta > c \\mid X)$ | Probabilità clinica diretta |\n| Cosa potrei osservare a una nuova somministrazione? | $p(\\tilde{X} \\mid X)$ | Variabilità attesa del nuovo punteggio osservato |\n| Quanto conta la qualità del test? | Analisi al variare di $\\rho$ | Sensibilità all'attendibilità |\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIl capitolo parte da una situazione apparentemente semplice: un paziente ottiene 72, il cut-off è 70. Una lettura dicotomica trasformerebbe questo confronto in una conclusione automatica. L'inferenza bayesiana mostra perché questa conclusione è troppo semplicistica.\n\nIl punto centrale è che ogni punteggio osservato è una misura imperfetta. Il numero registrato dal test non corrisponde al costrutto psicologico di interesse, ma ne rappresenta una manifestazione osservabile, soggetta all'errore di misurazione. La formula di @Kelley1923 offre già una risposta elegante a questo problema: corregge il punteggio osservato verso la media normativa in funzione dell'attendibilità del test.\n\nLa prospettiva bayesiana non cancella questa tradizione psicometrica. Al contrario, la rende più esplicita. Nel modello Normale-Normale, la stima di Kelley emerge come media della distribuzione a posteriori del punteggio vero. Tuttavia, il vantaggio decisivo è che la distribuzione a posteriori permette di rispondere alla domanda clinica nella forma in cui essa si presenta realmente: qual è la probabilità che questo paziente superi la soglia?\n\nNel nostro esempio, questa probabilità è di circa il 62%. Non si tratta di una certezza, ma neanche di un'informazione vaga. Si tratta di una quantificazione trasparente dell'incertezza. Ciò indica che il risultato merita attenzione, ma che il test non dovrebbe essere l'unica base per la decisione clinica.\n\nQuesto è il contributo più importante dell'approccio bayesiano alla psicometria applicata: non sostituire il giudizio clinico con un algoritmo, ma fornire al giudizio clinico una rappresentazione più onesta dell'incertezza. Il passaggio dalle medie di gruppo al singolo paziente richiede proprio questo: non eliminare l'incertezza, ma renderla visibile, quantificabile e comunicabile.\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.5.2\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.0            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.0           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.2              fastmap_1.2.0         tensorA_0.36.2.1     \n#>  [7] digest_0.6.39         timechange_0.4.0      estimability_2.0.0   \n#> [10] lifecycle_1.0.5       magrittr_2.0.5        compiler_4.6.1       \n#> [13] rlang_1.3.0           tools_4.6.1           yaml_2.3.12          \n#> [16] knitr_1.51            labeling_0.4.3        bridgesampling_1.2-1 \n#> [19] htmlwidgets_1.6.4     pkgbuild_1.4.8        curl_7.1.0           \n#> [22] RColorBrewer_1.1-3    abind_1.4-8           purrr_1.2.2          \n#> [25] grid_4.6.1            stats4_4.6.1          xtable_1.8-8         \n#> [28] inline_0.3.21         emmeans_2.0.3         scales_1.4.0         \n#> [31] cli_3.6.6             mvtnorm_1.4-1         rmarkdown_2.31       \n#> [34] generics_0.1.4        otel_0.2.0            RcppParallel_5.1.11-2\n#> [37] cachem_1.1.0          stringr_1.6.0         parallel_4.6.1       \n#> [40] vctrs_0.7.3           V8_8.2.0              Matrix_1.7-5         \n#> [43] jsonlite_2.0.0        arrayhelpers_1.1-1    glue_1.8.1           \n#> [46] codetools_0.2-20      distributional_0.8.1  lubridate_1.9.5      \n#> [49] stringi_1.8.7         gtable_0.3.6          QuickJSR_1.10.0      \n#> [52] pillar_1.11.1         htmltools_0.5.9       Brobdingnag_1.2-9    \n#> [55] R6_2.6.1              textshaping_1.0.5     rprojroot_2.1.1      \n#> [58] evaluate_1.0.5        lattice_0.22-9        backports_1.5.1      \n#> [61] memoise_2.0.1         broom_1.0.13          snakecase_0.11.1     \n#> [64] rstantools_2.6.0      coda_0.19-4.1         gridExtra_2.3.1      \n#> [67] nlme_3.1-169          checkmate_2.3.4       xfun_0.60            \n#> [70] pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "07_singolo_paziente_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}