{
  "hash": "ab2f34aea2a3c36d3837875e0443bb24",
  "result": {
    "engine": "knitr",
    "markdown": "# Due gruppi: codifiche, differenze e rilevanza pratica {#sec-linear-models-two-groups}\n\n::: {.callout-note appearance=\"minimal\"}\nNel capitolo precedente abbiamo visto che stimare una sola media equivale ad adattare il modello lineare più semplice, `y ~ 1`. Il confronto tra due gruppi costituisce il passo successivo: aggiungiamo un predittore categoriale che indica a quale gruppo appartiene ciascuna osservazione.\n\nLa logica del modello non cambia. Cambia la struttura della media condizionata. Invece di una sola media, il modello deve rappresentarne due e, soprattutto, la loro differenza:\n\n$$\n\\Delta = \\mu_1 - \\mu_0.\n$$\n\nQuesto passaggio è importante perché mostra una proprietà generale del modello lineare: **le procedure tradizionalmente presentate come analisi distinte possono essere ricondotte alla stessa grammatica di formule, matrici del modello e quantità derivate**. Con due gruppi, la codifica determina il significato immediato dei coefficienti, mentre le quantità sostantive, ovvero le due medie e il loro contrasto, rimangono il vero oggetto dell'inferenza.\n\nL'obiettivo del capitolo non è quindi imparare un nuovo \"test\", ma capire come rappresentare un confronto tra gruppi, come tradurre i coefficienti in quantità scientificamente rilevanti e come distinguere una differenza statisticamente plausibile da una differenza importante dal punto di vista sostantivo.\n:::\n\n::: {.callout-important appearance=\"minimal\" .chapter-status}\n**Da sapere.** Il confronto tra due gruppi è un modello lineare con un predittore categoriale a due livelli. Codifiche diverse possono attribuire significati diversi ai coefficienti, ma descrivono le stesse medie di gruppo e lo stesso contrasto quando il modello e i prior sono specificati in modo coerente. La differenza grezza $\\Delta$ è la quantità principale; la differenza standardizzata $d$ è una quantità derivata utile soprattutto per confronti tra studi. Una differenza osservazionale non identifica, da sola, un effetto causale.\n\n**Da saper fare.** Passare da `y ~ 1` a `y ~ gruppo`; leggere la matrice del modello per una variabile categoriale; ricostruire le medie dei gruppi e il contrasto indipendentemente dalla parametrizzazione; specificare e adattare con `brms` un modello gaussiano per due gruppi; calcolare probabilità a posteriori sulla direzione e su una soglia sostantiva; distinguere differenza grezza, differenza standardizzata e variabilità individuale; eseguire un controllo predittivo separato per gruppo.\n\n**Approfondimento facoltativo.** La codifica centrata, i modelli con dispersioni diverse, le verosimiglianze robuste e i disegni appaiati possono essere rimandati. Nel percorso essenziale è sufficiente comprendere la relazione tra codifica, medie e contrasto e saper interpretare l'incertezza sulla differenza.\n:::\n\n[Che cosa significano queste etichette?](../../guida-al-manuale.qmd#sec-percorsi-lettura)\n\n::: {.callout-tip collapse=true title=\"Prerequisiti\"}\n- Il modello a sola intercetta è discusso nell'@sec-mcmc-one-mean.\n- La relazione tra formula R e matrice del modello è introdotta nell'@sec-linar-models-brms.\n- Il workflow bayesiano completo con `brms` è presentato nell'@sec-linmod-bayesian-reg.\n- Per la trattazione frequentista del test $t$ per campioni indipendenti si veda il modulo [utet-frequentista](https://ccaudek.github.io/utet-frequentista).\n- L'esempio sul QI è tratto da @gelman2021regression.\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del notebook\"}\n\n\n:::\n\n## Dalla domanda scientifica alle quantità di interesse\n\nUtilizziamo il dataset `kidiq`, che contiene informazioni sullo sviluppo cognitivo di un campione di bambini e su alcune caratteristiche familiari [@gelman2021regression]. Ci concentriamo su:\n\n- `kid_score`: il punteggio del bambino in un test di sviluppo cognitivo;\n- `mom_hs`: un indicatore del conseguimento del diploma di scuola superiore da parte della madre.\n\nLa domanda è descrittiva:\n\n> Di quanto differiscono, in media, i punteggi cognitivi dei bambini nei due gruppi definiti dal livello di istruzione della madre?\n\nIndichiamo con $\\mu_0$ la media del gruppo \"Non diplomata\" e con $\\mu_1$ la media del gruppo \"Diplomata\". La quantità principale è il contrasto\n\n$$\n\\Delta = \\mu_1 - \\mu_0.\n$$\n\nIl segno di $\\Delta$ indica la direzione della differenza, mentre il suo valore assoluto conserva l'unità di misura originaria del punteggio. Possiamo inoltre considerare, come quantità secondaria,\n\n$$\nd = \\frac{\\Delta}{\\sigma},\n$$\n\ndove $\\sigma$ è la deviazione standard residua comune assunta dal modello.\n\n::: {.callout-important title=\"Prima la quantità scientifica, poi la codifica\"}\nLa domanda sostantiva riguarda $\\mu_0$, $\\mu_1$ e soprattutto $\\Delta$. I coefficienti prodotti dal software sono coordinate utili per rappresentare queste quantità, ma il loro significato dipende dalla codifica scelta. Separare le **quantità di interesse** dai **coefficienti della parametrizzazione** evita molte confusioni quando il modello diventa più complesso.\n:::\n\n::: {.callout-warning title=\"Una differenza tra gruppi non è automaticamente causale\"}\nIl livello di istruzione materna è osservato, non assegnato sperimentalmente. Il contrasto $\\Delta$ descrive quindi una differenza tra gruppi all'interno della popolazione rappresentata dal campione. Interpretarlo come effetto causale del diploma richiederebbe un disegno e assunzioni di identificazione che questo modello, da solo, non fornisce.\n:::\n\n## Esplorare i due gruppi\n\nCarichiamo i dati e rendiamo esplicito l'ordine dei livelli del fattore. Il primo livello sarà il riferimento nella codifica standard di R.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nkidiq <- rio::import(\n  here::here(\"data\", \"kidiq.dta\")\n) |>\n  transmute(\n    kid_score,\n    mom_hs = factor(\n      mom_hs,\n      levels = c(0, 1),\n      labels = c(\"Non diplomata\", \"Diplomata\")\n    )\n  ) |>\n  drop_na()\n\nkidiq |>\n  group_by(mom_hs) |>\n  summarise(\n    n        = n(),\n    media_QI = mean(kid_score),\n    sd_QI    = sd(kid_score),\n    .groups  = \"drop\"\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"mom_hs\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"media_QI\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sd_QI\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Non diplomata\",\"2\":\"93\",\"3\":\"77.5\",\"4\":\"22.6\"},{\"1\":\"Diplomata\",\"2\":\"341\",\"3\":\"89.3\",\"4\":\"19.0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nLe statistiche descrittive suggeriscono la posizione dei due gruppi, ma non mostrano da sole la variabilità interna e la sovrapposizione tra le distribuzioni.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nkidiq |>\n  ggplot(aes(x = mom_hs, y = kid_score)) +\n  geom_violin(trim = FALSE, alpha = 0.4, fill = \"grey80\", color = \"grey50\") +\n  geom_boxplot(width = 0.12, outlier.shape = NA, alpha = 0.7) +\n  geom_jitter(width = 0.08, alpha = 0.25, size = 1.2, color = \"grey30\") +\n  labs(\n    x = \"Istruzione materna\",\n    y = \"Punteggio cognitivo del bambino\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzione dei punteggi cognitivi nei due gruppi definiti dall'istruzione materna. Una differenza tra le medie può coesistere con una considerevole sovrapposizione tra le osservazioni individuali.](06_due_gruppi_rilevanza_pratica_files/figure-html/fig-kidiq-two-groups-1.png){#fig-kidiq-two-groups fig-align='center' width=85%}\n:::\n:::\n\n\nIl grafico anticipa una distinzione che accompagnerà tutto il capitolo: **differenza tra le medie** e **variabilità tra individui** sono aspetti diversi. Il modello deve rappresentarli separatamente.\n\n## Da una media a due medie\n\nNel capitolo precedente la formula\n\n```r\nkid_score ~ 1\n```\n\ncorrispondeva a una sola colonna di $1$ nella matrice del modello e quindi a una sola media. Aggiungendo il fattore `mom_hs`,\n\n```r\nkid_score ~ mom_hs\n```\n\nR costruisce una seconda colonna che indica l'appartenenza al gruppo non di riferimento.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nX_dummy <- model.matrix(\n  ~ mom_hs,\n  data = kidiq\n)\n\nhead(X_dummy)\n#>   (Intercept) mom_hsDiplomata\n#> 1           1               1\n#> 2           1               1\n#> 3           1               1\n#> 4           1               1\n#> 5           1               1\n#> 6           1               0\n```\n:::\n\n\nCon la codifica di riferimento predefinita, le righe della matrice hanno schematicamente la forma\n\n$$\n\\begin{array}{c|cc}\n& (Intercept) & mom\\_hs_{\\text{Diplomata}}\\\\\n\\hline\n\\text{Non diplomata} & 1 & 0\\\\\n\\text{Diplomata} & 1 & 1\n\\end{array}\n$$\n\ne il modello gaussiano diventa\n\n$$\n\\begin{aligned}\nY_i \\mid x_i,\\alpha,\\beta,\\sigma\n&\\sim \\operatorname{Normal}(\\mu_i,\\sigma),\\\\\n\\mu_i &= \\alpha + \\beta x_i.\n\\end{aligned}\n$$ {#eq-two-groups-dummy}\n\nSostituendo i due valori possibili di $x_i$:\n\n$$\n\\mu_0 = \\alpha,\n\\qquad\n\\mu_1 = \\alpha + \\beta.\n$$\n\nDi conseguenza,\n\n$$\n\\Delta = \\mu_1-\\mu_0=\\beta.\n$$\n\nCon questa parametrizzazione l'intercetta è la media del gruppo di riferimento e il coefficiente del fattore è direttamente la differenza \"Diplomata meno Non diplomata\".\n\n::: {.callout-note title=\"Il test t come caso particolare del modello lineare\"}\nIl confronto classico tra due medie indipendenti, sotto l'ipotesi di una varianza comune, può essere scritto come un modello lineare con un predittore binario. Il punto didattico non è sostituire un nome di procedura con un altro, ma riconoscere che **una media, due medie e più medie appartengono alla stessa struttura modellistica**.\n:::\n\n## Codifiche diverse, stesse quantità sostantive\n\nLo stesso confronto può essere parametrizzato in modi differenti. Consideriamo due forme particolarmente utili.\n\n| Parametrizzazione | Formula | Coefficienti |\n|---|---|---|\n| **Riferimento (dummy)** | `y ~ gruppo` | intercetta = $\\mu_0$; coefficiente = $\\Delta$ |\n| **Medie di cella** | `y ~ 0 + gruppo` | un coefficiente per $\\mu_0$ e uno per $\\mu_1$ |\n\nCon la parametrizzazione a medie di cella la matrice del modello contiene una colonna indicatrice per ciascun gruppo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nX_cells <- model.matrix(\n  ~ 0 + mom_hs,\n  data = kidiq\n)\n\nhead(X_cells)\n#>   mom_hsNon diplomata mom_hsDiplomata\n#> 1                   0               1\n#> 2                   0               1\n#> 3                   0               1\n#> 4                   0               1\n#> 5                   0               1\n#> 6                   1               0\n```\n:::\n\n\nSchematizzando,\n\n$$\n\\begin{array}{c|cc}\n& \\mu_0 & \\mu_1\\\\\n\\hline\n\\text{Non diplomata} & 1 & 0\\\\\n\\text{Diplomata} & 0 & 1\n\\end{array}\n$$\n\ne la differenza non coincide più con un coefficiente elementare: viene ricostruita dopo la stima come\n\n$$\n\\Delta = \\mu_1-\\mu_0.\n$$\n\nLe due parametrizzazioni non pongono domande scientifiche diverse. Cambiano soltanto le coordinate con cui viene rappresentato lo stesso sistema di medie.\n\n::: {.callout-tip collapse=true title=\"Approfondimento: codifica centrata\"}\nCon un indicatore codificato come $-0.5$ e $0.5$, l'intercetta rappresenta il punto medio non ponderato delle due medie,\n\n$$\n\\alpha_c=\\frac{\\mu_0+\\mu_1}{2},\n$$\n\nmentre il coefficiente continua a rappresentare $\\Delta$. Questa parametrizzazione può essere utile quando il punto medio tra i gruppi ha un significato più naturale della media del gruppo di riferimento.\n:::\n\n::: {.callout-important title=\"In Bayes la parametrizzazione interagisce con i prior\"}\nSe i prior vengono assegnati direttamente ai coefficienti, cambiare parametrizzazione può cambiare anche la distribuzione a priori indotta sulle medie e sui contrasti. Per questo non basta affermare che due formule sono algebricamente equivalenti: occorre controllare che le assunzioni probabilistiche rappresentino la stessa conoscenza sostantiva.\n\nNel seguito useremo la parametrizzazione **a medie di cella**, perché rende immediato assegnare prior alle due medie e prepara il passaggio al capitolo successivo, nel quale i gruppi saranno più di due.\n:::\n\n## Specificare il modello bayesiano\n\nUsiamo quindi\n\n```r\nkid_score ~ 0 + mom_hs\n```\n\ne assumiamo, nel modello essenziale, una deviazione standard residua comune ai due gruppi:\n\n$$\nY_i \\sim \\operatorname{Normal}(\\mu_{g[i]},\\sigma).\n$$\n\nI prior sono formulati sulla scala del punteggio:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npriors_two_groups <- c(\n  prior(normal(90, 20), class = \"b\"),\n  prior(student_t(3, 0, 20), class = \"sigma\")\n)\n```\n:::\n\n\nIl prior di classe `b` viene applicato alle due medie di cella. Non stiamo assumendo che 90 sia il valore corretto: stiamo dichiarando una gamma ampia di valori plausibili sulla scala dell'outcome, da verificare attraverso le conseguenze predittive congiunte del modello.\n\n### Controllo predittivo a priori\n\nPrima di utilizzare l'informazione dei dati osservati, simuliamo dalle sole distribuzioni a priori.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_two_groups_prior <- brm(\n  formula = kid_score ~ 0 + mom_hs,\n  data = kidiq,\n  family = gaussian(),\n  prior = priors_two_groups,\n  sample_prior = \"only\",\n  backend = \"cmdstanr\",\n  chains = 4,\n  iter = 1000,\n  seed = 1234,\n  refresh = 0\n)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp_check(\n  fit_two_groups_prior,\n  type = \"dens_overlay\",\n  ndraws = 40\n)\n```\n\n::: {.cell-output-display}\n![Controllo predittivo a priori del modello a due gruppi. Le repliche traducono i prior sulle medie e sulla dispersione in possibili distribuzioni osservabili del punteggio.](06_due_gruppi_rilevanza_pratica_files/figure-html/fig-prior-predictive-two-groups-1.png){#fig-prior-predictive-two-groups fig-align='center' width=85%}\n:::\n:::\n\n\nLo scopo non è far coincidere le simulazioni con i dati che stiamo per analizzare. La domanda è più semplice: **le assunzioni a priori permettono scenari compatibili con la scala e con il fenomeno, senza concentrare molta probabilità su configurazioni palesemente implausibili?**\n\n## Adattare il modello\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_two_groups <- brm(\n  formula = kid_score ~ 0 + mom_hs,\n  data = kidiq,\n  family = gaussian(),\n  prior = priors_two_groups,\n  backend = \"cmdstanr\",\n  chains = 4,\n  iter = 2000,\n  seed = 1234,\n  refresh = 0\n)\n```\n:::\n\n\nLe diagnostiche computazionali seguono i criteri già sviluppati nell'@sec-linmod-bayesian-reg. In questo capitolo non le reintroduciamo: prima di interpretare la posterior occorre comunque verificare $\\widehat R$, ESS, eventuali divergenze e gli altri avvisi del campionatore.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(fit_two_groups)\n#>  Family: gaussian \n#>   Links: mu = identity \n#> Formula: kid_score ~ 0 + mom_hs \n#>    Data: kidiq (Number of observations: 434) \n#>   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n#>          total post-warmup draws = 4000\n#> \n#> Regression Coefficients:\n#>                    Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\n#> mom_hsNondiplomata    77.70      2.00    73.74    81.65 1.00     4214     2879\n#> mom_hsDiplomata       89.33      1.08    87.20    91.43 1.00     4092     2897\n#> \n#> Further Distributional Parameters:\n#>       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\n#> sigma    19.88      0.66    18.58    21.21 1.00     4286     2911\n#> \n#> Draws were sampled using sample(hmc). For each parameter, Bulk_ESS\n#> and Tail_ESS are effective sample size measures, and Rhat is the potential\n#> scale reduction factor on split chains (at convergence, Rhat = 1).\n```\n:::\n\n\n## Dalle coordinate del modello alle quantità di interesse\n\nUna volta adattato il modello, torniamo alle quantità definite all'inizio. Per evitare di legare l'analisi ai nomi specifici dei coefficienti, ricaviamo direttamente le medie attese per i due livelli del fattore.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngroup_grid <- tibble(\n  mom_hs = factor(\n    c(\"Non diplomata\", \"Diplomata\"),\n    levels = levels(kidiq$mom_hs)\n  )\n)\n\ngroup_epred <- posterior_epred(\n  fit_two_groups,\n  newdata = group_grid\n)\n\nfit_draws <- as_draws_df(fit_two_groups)\n\npost_two_groups <- tibble(\n  mu0   = group_epred[, 1],\n  mu1   = group_epred[, 2],\n  sigma = fit_draws$sigma\n) |>\n  mutate(\n    delta = mu1 - mu0,\n    d = delta / sigma\n  )\n\npost_two_groups |>\n  summarise(\n    across(\n      c(mu0, mu1, delta, sigma, d),\n      list(\n        median = median,\n        lower = ~ quantile(.x, 0.025),\n        upper = ~ quantile(.x, 0.975)\n      )\n    )\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"mu0_median\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mu0_lower\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mu0_upper\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mu1_median\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mu1_lower\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mu1_upper\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"delta_median\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"delta_lower\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"delta_upper\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sigma_median\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sigma_lower\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sigma_upper\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"d_median\"],\"name\":[13],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"d_lower\"],\"name\":[14],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"d_upper\"],\"name\":[15],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"77.7\",\"2\":\"73.7\",\"3\":\"81.7\",\"4\":\"89.3\",\"5\":\"87.2\",\"6\":\"91.4\",\"7\":\"11.6\",\"8\":\"7.18\",\"9\":\"16.1\",\"10\":\"19.9\",\"11\":\"18.6\",\"12\":\"21.2\",\"13\":\"0.584\",\"14\":\"0.36\",\"15\":\"0.818\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nQuesto passaggio rende visibile un principio che tornerà continuamente nei capitoli successivi: **la parametrizzazione serve al modello; le quantità derivate servono alla domanda scientifica**. Se adattassimo un modello equivalente con codifica dummy e prior coerentemente trasformati, le posteriori di $\\mu_0$, $\\mu_1$ e $\\Delta$ dovrebbero descrivere lo stesso confronto.\n\n## Direzione, grandezza e rilevanza pratica\n\nLa distribuzione a posteriori di $\\Delta$ permette di separare domande che nella pratica vengono spesso confuse.\n\nLa prima domanda riguarda la **direzione**:\n\n$$\n\\Pr(\\Delta>0\\mid y).\n$$\n\nLa seconda riguarda la **grandezza sostantiva**. Se esiste una soglia $s$ stabilita sulla base di criteri teorici, clinici o decisionali, possiamo calcolare\n\n$$\n\\Pr(\\Delta>s\\mid y).\n$$\n\nPer mostrare il calcolo useremo $s=5$ punti **solo come soglia didattica**. Il valore non va interpretato come una soglia clinica validata per questo dataset.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSESOI_delta <- 5\n\npost_two_groups |>\n  ggplot(aes(x = delta)) +\n  geom_density(fill = \"grey90\", color = \"grey40\", alpha = 0.5) +\n  geom_vline(xintercept = 0, linetype = \"dashed\") +\n  geom_vline(xintercept = SESOI_delta, linetype = \"dotted\", linewidth = 1) +\n  labs(\n    x = expression(paste(\"Differenza grezza (\", Delta, \")\")),\n    y = \"Densità a posteriori\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzione a posteriori della differenza tra le medie. La linea tratteggiata indica zero; la linea puntinata mostra, a puro scopo didattico, una soglia sostantiva di 5 punti.](06_due_gruppi_rilevanza_pratica_files/figure-html/fig-posterior-delta-two-groups-1.png){#fig-posterior-delta-two-groups fig-align='center' width=85%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(\n  P_delta_positive = mean(post_two_groups$delta > 0),\n  P_delta_gt_s = mean(post_two_groups$delta > SESOI_delta),\n  P_abs_delta_le_s = mean(abs(post_two_groups$delta) <= SESOI_delta)\n)\n#> P_delta_positive     P_delta_gt_s P_abs_delta_le_s \n#>            1.000            0.998            0.002\n```\n:::\n\n\nLe tre quantità rispondono a domande diverse:\n\n- `P_delta_positive` riguarda il segno della differenza;\n- `P_delta_gt_s` riguarda il superamento di una soglia positiva;\n- `P_abs_delta_le_s` riguarda una regione simmetrica attorno a zero, se ha senso considerare differenze comprese tra $-s$ e $s$ come praticamente piccole.\n\nNon sono nuove versioni di una soglia di significatività. Una probabilità a posteriori diventa una decisione soltanto quando viene collegata a conseguenze, costi e criteri stabiliti per il problema concreto.\n\n::: {.callout-note title=\"SESOI e ROPE non sono sinonimi\"}\nUna **SESOI** identifica la minima grandezza dell'effetto ritenuta sostantivamente rilevante. Una **ROPE** rappresenta invece un intervallo di valori considerati praticamente vicini all'assenza di effetto. Una soglia direzionale, come $\\Delta>5$, e una regione simmetrica, come $[-5,5]$, rispondono quindi a domande differenti. I loro confini devono essere giustificati dal dominio, non scelti dopo avere osservato la posterior.\n:::\n\n## La differenza standardizzata è una quantità secondaria {#sec-bayesian-effect-size}\n\nQuando la scala originaria è interpretabile, $\\Delta$ rimane in genere la quantità più trasparente da comunicare. La standardizzazione può essere utile per confrontare risultati ottenuti con strumenti diversi o per una sintesi meta-analitica:\n\n$$\nd = \\frac{\\Delta}{\\sigma}.\n$$\n\nNel modello attuale $\\Delta$ e $\\sigma$ sono entrambe incerte. Calcolando il rapporto draw per draw, tale incertezza viene propagata automaticamente alla posterior di $d$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npost_two_groups |>\n  summarise(\n    d_median = median(d),\n    d_lower = quantile(d, 0.025),\n    d_upper = quantile(d, 0.975)\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"d_median\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"d_lower\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"d_upper\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"0.584\",\"2\":\"0.36\",\"3\":\"0.818\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nL'indice $d$ non è una misura pura della \"forza\" della differenza: dipende anche dalla dispersione della popolazione e dalla qualità della misurazione. Per questo una differenza grezza identica può corrispondere a valori standardizzati diversi in popolazioni con diversa variabilità.\n\n::: {.callout-caution title=\"Evitare categorie automatiche\"}\nLe soglie 0.2, 0.5 e 0.8 associate storicamente a effetti \"piccoli\", \"medi\" e \"grandi\" non sono confini naturali. Se il dominio dispone di criteri sostantivi più informativi, questi devono avere la precedenza. In ogni caso, la differenza standardizzata dovrebbe affiancare, non sostituire, la differenza espressa sulla scala originale.\n:::\n\n## Controllare il modello nei due gruppi\n\nUn controllo predittivo marginale può apparire soddisfacente anche quando il modello descrive male uno dei due gruppi. Poiché la domanda scientifica riguarda proprio un confronto tra distribuzioni condizionate, il controllo deve rispettare questa struttura.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp_check(\n  fit_two_groups,\n  type = \"dens_overlay_grouped\",\n  group = \"mom_hs\",\n  ndraws = 20\n)\n```\n\n::: {.cell-output-display}\n![Controllo predittivo a posteriori separato per livello di istruzione materna. Le distribuzioni osservate vengono confrontate con repliche generate dal modello all'interno di ciascun gruppo.](06_due_gruppi_rilevanza_pratica_files/figure-html/fig-grouped-ppc-two-groups-1.png){#fig-grouped-ppc-two-groups fig-align='center' width=85%}\n:::\n:::\n\n\nQuesto grafico permette di cercare discrepanze nella posizione, nella dispersione e nella forma delle distribuzioni dei due gruppi. Un buon accordo non dimostra che il modello sia vero; indica soltanto che, per le caratteristiche osservate, non emergono discrepanze evidenti.\n\n::: {.callout-tip collapse=true title=\"Approfondimento: se le dispersioni differiscono\"}\nIl modello essenziale usa un unico parametro $\\sigma$ e assume quindi la stessa dispersione residua nei due gruppi. Se questa assunzione è inadeguata, `brms` consente di modellare anche $\\sigma$ in funzione del gruppo, per esempio:\n\n```r\nbf(\n  kid_score ~ 0 + mom_hs,\n  sigma ~ 0 + mom_hs\n)\n```\n\nQuesta estensione modifica anche il significato di una differenza standardizzata, perché non esiste più un'unica deviazione standard residua naturale da usare come denominatore. Il problema viene ripreso nel capitolo dedicato al controllo e alla revisione del modello.\n:::\n\n::: {.callout-caution title=\"Gruppi indipendenti e misure appaiate sono disegni diversi\"}\nIl modello di questo capitolo assume osservazioni indipendenti appartenenti a due gruppi. Se le due misure provengono dagli stessi individui, la dipendenza entro persona deve essere rappresentata: si può modellare la distribuzione delle differenze individuali nel caso più semplice oppure utilizzare un modello per misure ripetute. Trattare le osservazioni appaiate come due gruppi indipendenti perde informazione sulla struttura del disegno.\n:::\n\n## Comunicare i risultati\n\nUn resoconto utile dovrebbe partire dalle quantità scientifiche, non dalla codifica del software. È quindi opportuno riportare:\n\n1. le medie stimate dei due gruppi;\n2. la differenza $\\Delta$ sulla scala originaria e la sua incertezza;\n3. la probabilità della direzione, se rilevante per la domanda;\n4. la probabilità di superare una soglia sostantiva, soltanto se tale soglia è giustificata;\n5. eventualmente la differenza standardizzata, specificando il denominatore;\n6. gli aspetti del modello effettivamente controllati;\n7. i limiti imposti dal disegno alla generalizzazione e all'interpretazione causale.\n\n\n\n> Nel campione analizzato, la media a posteriori del punteggio cognitivo è 77.7 punti nel gruppo \"Non diplomata\" e 89.3 punti nel gruppo \"Diplomata\". La differenza \"Diplomata meno Non diplomata\" è 11.6 punti, con intervallo di credibilità al 95% [7.2, 16.1]. La probabilità a posteriori che la differenza sia positiva è 1.000. Usando esclusivamente a scopo illustrativo una soglia di 5 punti, la probabilità che la differenza la superi è 0.998. La differenza standardizzata è $d=$ 0.58 ([0.36, 0.82]). I controlli predittivi esaminati non mostrano discrepanze evidenti nelle caratteristiche considerate. Poiché il confronto è osservazionale, il risultato descrive un'associazione tra istruzione materna e punteggio del bambino e non identifica un effetto causale del diploma.\n\n## Errori comuni\n\n::: {.callout-caution}\n1. **Interpretare un coefficiente senza conoscere la codifica.** I coefficienti cambiano significato quando cambia il riferimento o la parametrizzazione.\n2. **Confondere coefficienti e quantità sostantive.** Le medie di gruppo e il loro contrasto possono essere ricostruiti anche quando non coincidono direttamente con i coefficienti del modello.\n3. **Sostituire la differenza grezza con $d$.** La standardizzazione è utile per alcuni confronti, ma nasconde l'unità di misura e dipende dalla dispersione.\n4. **Inventare una soglia dopo avere visto i risultati.** SESOI e ROPE devono derivare da ragioni sostantive o decisionali indipendenti dalla posterior osservata.\n5. **Interpretare un intervallo che comprende zero come prova di equivalenza.** Incertezza ed equivalenza pratica non sono la stessa cosa.\n6. **Controllare soltanto la distribuzione marginale complessiva.** In un confronto tra gruppi è essenziale verificare che il modello descriva adeguatamente ciascun gruppo.\n7. **Attribuire causalità a un contrasto osservazionale.** La regressione non crea, da sola, le condizioni necessarie per identificare un effetto causale.\n:::\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nPassare da una media a due gruppi richiede una modifica minima della struttura del modello: alla sola intercetta si aggiunge un'informazione sull'appartenenza al gruppo. Da questa modifica nasce una matrice del modello con più colonne, ma non cambia la logica generale dell'inferenza.\n\nIl punto centrale è distinguere ciò che dipende dalla **parametrizzazione** da ciò che appartiene alla **domanda scientifica**. Intercetta e coefficienti possono cambiare significato quando cambia la codifica; le medie $\\mu_0$, $\\mu_1$ e il contrasto $\\Delta$ restano invece le quantità da interpretare. Nel quadro bayesiano possiamo descriverne l'intera incertezza, calcolare probabilità sulla direzione e, quando esistono criteri indipendenti, valutare la probabilità che la differenza raggiunga una grandezza sostantivamente rilevante.\n\nLa differenza standardizzata aggiunge una scala comparativa, ma non sostituisce l'interpretazione nelle unità originarie. Analogamente, una soglia pratica non trasforma automaticamente l'inferenza in una decisione: occorre specificare perché quella soglia conti e quali conseguenze siano associate alle diverse azioni.\n\nNel prossimo capitolo aggiungeremo un terzo e poi ulteriori gruppi. La parametrizzazione a medie di cella utilizzata qui rende il passaggio immediato: avremo una media per ciascun gruppo e formuleremo le domande scientifiche come **contrasti tra queste medie**. In questa prospettiva, ciò che tradizionalmente viene chiamato ANOVA non introduce una nuova logica inferenziale: è un'estensione dello stesso modello lineare a un predittore categoriale con più livelli.\n\n## Esercizi {.unnumbered .unlisted}\n\n### Esercizio 1 — Dalla matrice alle medie {.unnumbered .unlisted}\n\n*10 minuti · Codice: no*\n\nCon codifica dummy, il modello è\n\n$$\n\\mu_i = \\alpha+\\beta x_i,\n$$\n\ncon $x=0$ per il gruppo A e $x=1$ per il gruppo B.\n\n1. Ricava $\\mu_A$ e $\\mu_B$.\n2. Dimostra che $\\Delta=\\mu_B-\\mu_A=\\beta$.\n3. Scrivi le due righe distinte della matrice del modello.\n4. Spiega che cosa cambierebbe usando `y ~ 0 + gruppo`.\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nCon le medie di cella non esiste una colonna di intercetta globale: ogni gruppo possiede la propria colonna indicatrice.\n:::\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\nCon la codifica dummy, $\\mu_A=\\alpha$ e $\\mu_B=\\alpha+\\beta$, quindi $\\Delta=\\beta$. Le righe della matrice sono $[1,0]$ per A e $[1,1]$ per B. Con `y ~ 0 + gruppo`, le righe diventano $[1,0]$ e $[0,1]`: i due coefficienti rappresentano direttamente $\\mu_A$ e $\\mu_B$, mentre il contrasto viene calcolato come loro differenza.\n:::\n\n### Esercizio 2 — Direzione e rilevanza non sono la stessa domanda {.unnumbered .unlisted}\n\n*10–15 minuti · Codice: no*\n\nPer il contrasto \"B meno A\" si ottengono:\n\n- mediana a posteriori di $\\Delta$: 7.2 punti;\n- intervallo di credibilità al 95%: $[2.1,12.3]$;\n- $\\Pr(\\Delta>0\\mid y)=0.996$;\n- $\\Pr(\\Delta>5\\mid y)=0.80$;\n- mediana a posteriori di $d$: 0.40, con intervallo $[0.12,0.68]$.\n\n1. Che cosa dice la prima probabilità?\n2. Perché la seconda probabilità è più bassa?\n3. Quale quantità useresti per comunicare l'ampiezza nella scala originale?\n4. Quale informazione aggiunge $d$?\n5. Quale conclusione causale sarebbe ingiustificata se A e B fossero gruppi osservazionali?\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\nLa posterior sostiene fortemente una differenza positiva, ma è meno certa che la differenza superi 5 punti, perché questa seconda condizione è più esigente. L'ampiezza sulla scala originaria è descritta da $\\Delta$; $d$ esprime la stessa differenza rispetto alla dispersione residua comune e può essere utile per confronti tra studi. Se i gruppi sono osservazionali, nessuna di queste quantità dimostra che l'appartenenza a B causi il cambiamento dell'outcome.\n:::\n\n### Esercizio 3 — La quantità sostantiva è invariabile rispetto alla codifica {.unnumbered .unlisted}\n\n*15 minuti · Codice: guidato*\n\nSupponi di avere adattato due modelli equivalenti, uno con codifica dummy e uno a medie di cella.\n\nNel modello dummy:\n\n$$\n\\alpha=80,\\qquad \\beta=7.\n$$\n\nNel modello a medie di cella:\n\n$$\n\\gamma_A=80,\\qquad \\gamma_B=87.\n$$\n\n1. Ricostruisci $\\mu_A$, $\\mu_B$ e $\\Delta$ in entrambi i casi.\n2. Quali coefficienti cambiano significato?\n3. Quali quantità rimangono identiche?\n4. Perché, in un'analisi bayesiana, non basta cambiare formula mantenendo arbitrariamente gli stessi prior numerici sui coefficienti?\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nCon la codifica dummy, la media di B è una somma di coefficienti. Con le medie di cella, le due medie sono coefficienti diretti.\n:::\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\nNel primo modello $\\mu_A=80$, $\\mu_B=80+7=87$ e $\\Delta=7$. Nel secondo $\\mu_A=80$, $\\mu_B=87$ e $\\Delta=87-80=7$. I coefficienti hanno coordinate diverse, ma le quantità sostantive sono identiche. In Bayes, tuttavia, prior indipendenti assegnati a coordinate diverse possono indurre distribuzioni diverse su medie e contrasti; per ottenere modelli sostantivamente equivalenti occorre trasformare coerentemente anche i prior.\n:::\n\n### Esercizio 4 — Preparare il passaggio a tre gruppi {.unnumbered .unlisted}\n\n*10 minuti · Codice: no*\n\nImmagina ora tre gruppi, A, B e C, e la formula\n\n```r\nscore ~ 0 + gruppo\n```\n\n1. Quante colonne contiene la matrice del modello?\n2. Che cosa rappresentano i tre coefficienti?\n3. Scrivi i contrasti $B-A$, $C-A$ e $C-B$.\n4. Perché l'aggiunta del terzo gruppo non richiede una nuova teoria statistica?\n5. Quale problema nasce se si iniziano a esaminare molti contrasti senza avere chiarito prima quali rispondono alla domanda scientifica?\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\nLa matrice contiene tre colonne indicatrici, una per ciascun gruppo. I tre coefficienti rappresentano direttamente $\\mu_A$, $\\mu_B$ e $\\mu_C$. I contrasti sono $\\mu_B-\\mu_A$, $\\mu_C-\\mu_A$ e $\\mu_C-\\mu_B$. La struttura rimane quella del modello lineare: cambia soltanto il numero di colonne e quindi il numero di medie rappresentate. Con molti gruppi diventa però essenziale definire in anticipo quali contrasti sono scientificamente rilevanti, invece di interpretare indiscriminatamente tutte le differenze possibili.\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.6.1\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.1            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.1           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] gridExtra_2.3.1      inline_0.3.21        rlang_1.3.0         \n#>  [4] magrittr_2.0.5       snakecase_0.11.1     otel_0.2.0          \n#>  [7] compiler_4.6.1       reshape2_1.4.5       vctrs_0.7.3         \n#> [10] stringr_1.6.0        pkgconfig_2.0.3      arrayhelpers_1.1-2  \n#> [13] fastmap_1.2.0        backports_1.5.1      labeling_0.4.3      \n#> [16] cmdstanr_0.9.0       rmarkdown_2.31       tzdb_0.5.0          \n#> [19] ps_1.9.3             haven_2.5.5          purrr_1.2.2         \n#> [22] xfun_0.60            cachem_1.1.0         jsonlite_2.0.0      \n#> [25] broom_1.0.13         parallel_4.6.1       R6_2.6.1            \n#> [28] stringi_1.8.9        RColorBrewer_1.1-3   lubridate_1.9.5     \n#> [31] estimability_2.0.0   knitr_1.51           R.utils_2.13.0      \n#> [34] readr_2.2.0          Matrix_1.7-6         timechange_0.4.0    \n#> [37] tidyselect_1.2.1     abind_1.4-8          yaml_2.3.12         \n#> [40] codetools_0.2-20     processx_3.9.0       curl_7.1.0          \n#> [43] pkgbuild_1.4.8       plyr_1.8.9           lattice_0.22-9      \n#> [46] bridgesampling_1.2-1 S7_0.2.2             coda_0.19-4.1       \n#> [49] evaluate_1.0.5       RcppParallel_6.2.0   pillar_1.11.1       \n#> [52] tensorA_0.36.2.1     checkmate_2.3.4      stats4_4.6.1        \n#> [55] distributional_0.8.1 generics_0.1.4       rprojroot_2.1.1     \n#> [58] hms_1.1.4            rstantools_2.7.0     scales_1.4.0        \n#> [61] xtable_1.8-8         glue_1.8.1           emmeans_2.0.4       \n#> [64] tools_4.6.1          data.table_1.18.4    forcats_1.0.1       \n#> [67] mvtnorm_1.4-2        grid_4.6.1           QuickJSR_1.10.0     \n#> [70] nlme_3.1-170         cli_3.6.6            textshaping_1.0.5   \n#> [73] svUnit_1.0.8         Brobdingnag_1.2-9    V8_8.2.0            \n#> [76] gtable_0.3.6         R.methodsS3_1.8.2    digest_0.6.39       \n#> [79] htmlwidgets_1.6.4    farver_2.1.2         memoise_2.0.1       \n#> [82] htmltools_0.5.9      R.oo_1.27.1          lifecycle_1.0.5\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "06_due_gruppi_rilevanza_pratica_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}