{
  "hash": "e88cc6049a289d432e7f42183d66be0b",
  "result": {
    "engine": "knitr",
    "markdown": "# Modello gerarchico beta-binomiale {#sec-mcmc-hier-beta-binom}\n\n::: {.callout-note appearance=\"minimal\"}\nIn questo capitolo introdurremo il concetto di *struttura gerarchica* nell'inferenza bayesiana\nusando il modello beta-binomiale. In questo contesto, concetti chiave come la scambiabilità, gli iperparametri, la concentrazione e lo *shrinkage* possono essere osservati in modo particolarmente chiaro, prima di passare, in seguito, al caso gaussiano che, pur condividendo la stessa logica di base, richiede strumenti computazionali più sofisticati e meno trasparenti dal punto di vista analitico.\n:::\n\n## Panoramica del capitolo {.unnumbered .unlisted}\n\n* Specificare un modello beta–binomiale gerarchico.\n* Spiegare il ruolo della probabilità media nella popolazione $\\mu$ e concentrazione $\\kappa$.\n* Interpretare lo *shrinkage* e collegarlo al numero di prove per soggetto.\n* Leggere le principali diagnostiche MCMC.\n* Confrontare la prestazione media con un valore di riferimento (es. 0.5).\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n\nif (!requireNamespace(\"pacman\")) install.packages(\"pacman\")\npacman::p_load(cmdstanr, posterior, bayesplot, ggplot2, dplyr, tibble, stringr)\nconflicts_prefer(posterior::ess_bulk)\nconflicts_prefer(posterior::ess_tail)\n\n# Definisci i colori tematici\ncol_prior <- palette_qualitative[2]        # Azzurro per distribuzioni a priori\ncol_data <- palette_qualitative[6]         # Rosso-arancio per dati empirici\ncol_posterior <- palette_qualitative[5]    # Blu per stime a posteriori\ncol_mean <- palette_qualitative[3]         # Verde per medie di popolazione\ncol_interval <- palette_qualitative[7]     # Rosa per intervalli di credibilità\ncol_shrinkage <- palette_qualitative[8]    # Grigio per segmenti di shrinkage\ncol_highlight <- palette_qualitative[1]    # Arancione per elementi evidenziati\n\ncolor_names <- c(\n  \"#E69F00\" = \"Arancione\",\n  \"#56B4E9\" = \"Azzurro\", \n  \"#009E73\" = \"Verde\",\n  \"#F0E442\" = \"Giallo\",\n  \"#0072B2\" = \"Blu\",\n  \"#D55E00\" = \"Rosso-arancio\",\n  \"#CC79A7\" = \"Rosa\",\n  \"#999999\" = \"Grigio\"\n)\n```\n:::\n\n:::\n\n## Meccanismi di regolarizzazione\n\nIn questo capitolo, le probabilità di successo individuali sono interpretate come realizzazioni scambiabili estratte da una distribuzione Beta comune. I conteggi di successi per ciascun individuo sono modellati mediante distribuzioni binomiali condizionate a tali probabilità, mentre gli iperparametri della distribuzione Beta — che ne determinano posizione e dispersione — vengono stimati direttamente dai dati.\n\nNel @sec-multilevel, dedicato ai modelli gaussiani a effetti misti, ritroveremo la medesima struttura concettuale in un contesto continuo: i parametri individuali saranno concepiti come estrazioni da una distribuzione normale, la verosimiglianza assumerà una forma gaussiana e il grado di concentrazione della distribuzione degli effetti individuali sarà espresso dalla deviazione standard degli effetti casuali. Il principio unificante resta invariato: gli individui condividono caratteristiche comuni pur mantenendo una propria specificità, e questa condivisione di informazione genera un *pooling* parziale che bilancia la stabilità delle inferenze di gruppo con la sensibilità alle differenze individuali.\n\nIn questa prospettiva, il modello beta-binomiale può essere considerato l’analogo discreto del modello gaussiano a effetti misti. La probabilità individuale $p_i$ svolge un ruolo concettualmente equivalente a quello del parametro continuo $\\theta_j$ nei modelli gaussiani, la distribuzione Beta rappresenta il corrispettivo discreto della distribuzione Normale e il parametro di concentrazione $\\kappa$ è interpretabile come l’equivalente della deviazione standard degli effetti casuali.\n\nOltre al suo interesse intrinseco, il modello beta-binomiale offre dunque un caso di studio particolarmente trasparente per osservare all’opera i meccanismi di *pooling* e di regolarizzazione, prima di estenderli a modelli lineari gerarchici più complessi [si vedano @gelman1995bayesian; @McElreath_rethinking].\n\n## Perché adottare una struttura gerarchica\n\nL'analisi di dati psicologici raccolti su più individui pone una sfida metodologica importante: come è possibile conciliare il rispetto delle differenze individuali con l'esigenza di formulare conclusioni valide a livello di popolazione? Da un lato, ogni partecipante presenta caratteristiche uniche che meritano di essere rappresentate; dall'altro, l'obiettivo della ricerca è spesso quello di comprendere tendenze generali che vanno oltre il caso singolo. I modelli gerarchici bayesiani offrono una soluzione elegante a questa sfida, integrando entrambe le prospettive in un unico quadro inferenziale coerente.\n\nLa logica alla base di questi modelli è insieme semplice e potente. Ogni individuo contribuisce con i propri dati alla stima del proprio parametro specifico, ma al tempo stesso partecipa alla definizione del profilo generale della popolazione. Questo profilo collettivo, a sua volta, esercita un'influenza regolatrice sulle stime individuali. Il risultato è un equilibrio dinamico: quando disponiamo di poche osservazioni per un determinato soggetto, la stima del suo parametro tende ad avvicinarsi alla media del gruppo; quando invece le osservazioni sono numerose, prevale l'evidenza empirica specifica di quel partecipante. Questo fenomeno, noto come *shrinkage* (letteralmente \"restringimento\" o \"contrazione\"), non è un artificio statistico imposto dall'esterno, ma emerge naturalmente dalla struttura probabilistica del modello.\n\n### Il principio di scambiabilità\n\nIl fondamento concettuale di questo approccio risiede nel principio di scambiabilità. In assenza di informazioni che permettano di distinguere sistematicamente alcuni individui dagli altri, ad esempio in base a covariate quali l'età, il livello di istruzione o l'appartenenza a gruppi clinici, è metodologicamente appropriato trattare i parametri individuali come realizzazioni indipendenti provenienti da una distribuzione comune. In termini psicologici, ciò equivale a riconoscere che tutti gli individui del campione appartengono alla stessa popolazione di riferimento, pur manifestando una certa variabilità individuale.\n\nConsideriamo un esempio concreto. Supponiamo di analizzare la precisione del riconoscimento delle espressioni facciali. Se non abbiamo ragioni teoriche o empiriche per ritenere che alcuni individui appartengano a sottogruppi sistematicamente diversi (per esempio, in base all'età o alla formazione), possiamo considerare le loro probabilità di successo come *scambiabili*. Ciò significa che, prima di osservare i dati, non è possibile distinguere a priori le prestazioni dei partecipanti: ciascuno ha la stessa probabilità di mostrare un determinato livello di abilità. Il modello gerarchico cattura questa intuizione, rappresentando tutti i partecipanti come provenienti da una distribuzione comune che descrive il livello medio di abilità della popolazione, pur preservando le differenze individuali attorno a tale valore centrale.\n\nNaturalmente, quando sono disponibili covariate rilevanti o si identificano sottogruppi teoricamente motivati, il modello può essere esteso in modo naturale includendo predittori che spiegano parte della variabilità tra i soggetti. Tuttavia, la logica strutturale di base rimane inalterata: il modello continua a operare una regolarizzazione gerarchica, ora condizionata alle caratteristiche osservate dei partecipanti.\n\n## Struttura del modello e parametrizzazione\n\nIl modello gerarchico adottato si basa su una struttura generativa a due livelli che riflette sia il processo di generazione dei dati osservati sia le ipotesi sulla popolazione di riferimento.\n\n**Livello individuale (verosimiglianza).**\nPer ciascun partecipante $i$, il numero di successi $y_i$ osservati su $n_i$ prove è modellato mediante una distribuzione binomiale con probabilità di successo individuale $p_i$:\n$$\ny_i \\sim \\text{Binomiale}(n_i, p_i).\n$$\nQuesto livello del modello descrive il meccanismo stocastico attraverso il quale i dati empirici vengono generati a partire dai parametri individuali.\n\n**Livello di popolazione (distribuzione dei parametri individuali).**\nLe probabilità di successo individuali $p_i$ non sono considerate come parametri indipendenti, ma come realizzazioni scambiabili estratte da una distribuzione Beta comune, caratterizzata dagli iperparametri $\\alpha$ e $\\beta$:\n$$\np_i \\sim \\text{Beta}(\\alpha, \\beta).\n$$\nQuesta distribuzione cattura la variabilità interindividuale nella popolazione. Gli iperparametri $\\alpha$ e $\\beta$ ne determinano la forma complessiva e, di conseguenza, il modo in cui le probabilità individuali si distribuiscono attorno a un valore tipico.\n\n**Distribuzioni *a priori* sugli iperparametri.**\nPer completare la descrizione del modello, agli iperparametri $\\alpha$ e $\\beta$ vengono assegnate distribuzioni *a priori* debolmente informative, che riflettono una conoscenza preliminare limitata e lasciano ai dati un ruolo predominante nell’inferenza.\n\n### Una parametrizzazione più interpretabile\n\nSebbene la parametrizzazione tradizionale in termini di $\\alpha$ e $\\beta$ sia matematicamente conveniente, essa risulta spesso poco immediata dal punto di vista interpretativo. Una riformulazione alternativa, basata sui concetti di media e concentrazione, permette di interpretare i parametri del modello in modo più diretto:\n\n* La **media di popolazione**\n  $$\n  \\mu = \\frac{\\alpha}{\\alpha + \\beta}\n  $$\n  rappresenta la probabilità media di successo nella popolazione, ovvero il livello tipico di performance atteso.\n\n* La **concentrazione**\n  $$\n  \\kappa = \\alpha + \\beta\n  $$\n  quantifica il grado di omogeneità tra i partecipanti. Valori elevati di $\\kappa$ indicano che le probabilità individuali sono fortemente concentrate attorno alla media $\\mu$, suggerendo una popolazione relativamente omogenea, mentre valori ridotti di $\\kappa$, al contrario, consentono una maggiore dispersione delle $p_i$ e riflettono una popolazione più eterogenea.\n\nQuesta parametrizzazione rende più agevole sia la specificazione di distribuzioni *a priori* sostantivamente motivate sia l’interpretazione dei risultati, facilitando il collegamento tra i parametri statistici del modello e le caratteristiche psicologiche della popolazione studiata.\n\n## Il meccanismo di *shrinkage* bayesiano\n\nUno degli aspetti più istruttivi del modello gerarchico emerge dall’analisi della distribuzione *a posteriori* dei parametri individuali. Quando gli iperparametri $\\alpha$ e $\\beta$ sono noti — o, più realisticamente, stimati dai dati — la coniugazione tra la distribuzione Beta e la verosimiglianza binomiale conduce a una distribuzione *a posteriori* la cui forma rende particolarmente trasparente il meccanismo di regolarizzazione bayesiana.\n\nLa stima bayesiana per l'individuo $i$-esimo combina in modo bilanciato la sua evidenza empirica con l'informazione di popolazione:\n$$\n\\mathbb{E}[p_i \\mid y_i, \\alpha, \\beta] = w_i \\,\\hat{p}_i + (1 - w_i)\\,\\mu,\n$$\ndove:\n\n* $\\hat{p}_i = y_i / n_i$ è la proporzione osservata per l'individuo.\n* $\\mu = \\alpha / (\\alpha + \\beta)$ è la probabilità media a priori nella popolazione.\n* $w_i = \\frac{n_i}{n_i + \\kappa}$ è il peso di fiducia nei dati individuali, con $\\kappa = \\alpha + \\beta$ che ne determina l'intensità.\n\nQuesta media ponderata realizza il meccanismo di *shrinkage* (o *regolarizzazione*): la stima finale \"restringe\" l'osservazione grezza $\\hat{p}_i$ verso la media della popolazione $\\mu$. Il peso $w_i$ determina quanto.\n\n**1. Il ruolo della dimensione campionaria individuale ($n_i$).**  \nIl peso $w_i = n_i / (n_i + \\kappa)$ regola l'equilibrio tra dato individuale e informazione di gruppo:\n\n* dati scarsi ($n_i$ piccolo): $w_i \\approx 0$. La stima è attratta verso $\\mu$. Il modello, in mancanza di evidenza solida, preserva per l'individuo l'informazione del gruppo.\n* dati abbondanti ($n_i$ grande): $w_i \\approx 1$. La stima coincide con $\\hat{p}_i$. Il modello affida la stima all'evidenza individuale, ormai affidabile.\n\n**2. Il ruolo dell'eterogeneità di popolazione ($\\kappa$).**  \nIl parametro $\\kappa = \\alpha + \\beta$, noto come concentrazione, modula globalmente l'intensità dello *shrinkage*:\n\n* $\\kappa$ grande (popolazione omogenea): il denominatore $n_i + \\kappa$ cresce, riducendo $w_i$. Il modello promuove una forte regolarizzazione verso una media comune ritenuta molto informativa per tutti.\n* $\\kappa$ piccolo (popolazione eterogenea): $w_i$ rimane vicino a 1 anche per $n_i$ modesti. Il modello permette maggiore differenziazione, ritenendo la media di popolazione meno rappresentativa per i singoli.\n\nQuesto bilanciamento adattivo tra informazione individuale e informazione di gruppo costituisce il nucleo dello *shrinkage* bayesiano e rappresenta uno dei principali vantaggi dei modelli gerarchici. Il modello non impone a priori un grado fisso di regolarizzazione, ma lo apprende dai dati, producendo stime che risultano al tempo stesso sensibili alle specificità individuali e ancorate alla struttura della popolazione di riferimento.\n\n## Un'applicazione pratica: lo studio sulla terapia tattile\n\n### Il contesto sperimentale\n\nPer illustrare concretamente il funzionamento del modello gerarchico beta-binomiale, esaminiamo uno studio sperimentale di @rosa1998close, che ha indagato l'efficacia della cosiddetta \"terapia tattile\". Questo controverso approccio terapeutico si basa sull'assunto che alcuni operatori sanitari, specificamente addestrati, siano in grado di percepire e manipolare il cosiddetto \"campo energetico umano\" che circonda il corpo.\n\nPer verificare questa affermazione, i ricercatori hanno progettato un esperimento in condizioni controllate. Ventotto praticanti del *Therapeutic Touch* dovevano identificare, senza alcun contatto visivo o fisico, quale delle due mani di un partecipante era stata avvicinata dallo sperimentatore. Il disegno prevedeva che ciascun operatore completasse dieci prove indipendenti, ottenendo in ciascuna un risultato binario: identificazione corretta o errore.\n\nDal punto di vista statistico, l'obiettivo inferenziale si articola su due livelli complementari:\n\n1. **livello individuale**: stimare la probabilità di successo specifica di ciascun operatore, riconoscendo che potrebbero esistere differenze individuali nell'abilità (ammesso che tale abilità esista).\n\n2. **livello di popolazione**: stimare la probabilità media di successo dell'intero gruppo di operatori, per valutare se complessivamente la performance si discosti dalla pura casualità.\n\nEntrambi i parametri possono essere interpretati in base al confronto con il valore di riferimento di 0.5, che rappresenta la performance attesa per puro caso in un compito a due alternative forzate. Se gli operatori possiedono effettivamente la capacità dichiarata, si dovrebbero osservare probabilità di successo sistematicamente superiori a tale valore.\n\nQuesto contesto sperimentale si presta idealmente all'applicazione di un modello gerarchico, poiché combina l'interesse per le specificità individuali con la necessità di trarre conclusioni sulla popolazione generale, in un dominio dove la performance casuale costituisce un punto di riferimento cruciale.\n\n### Preparazione e ispezione dei dati\n\nProcediamo innanzitutto all'importazione dei dati e alla loro organizzazione. Il dataset contiene le risposte di ciascun operatore per ogni singola prova.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Importazione dei dati\nurl <- \"https://raw.githubusercontent.com/boboppie/kruschke-doing_bayesian_data_analysis/master/2e/TherapeuticTouchData.csv\"\n\ntt_dat <- read.csv(url)\ntt_dat %>% glimpse()\n#> Rows: 280\n#> Columns: 2\n#> $ y <int> 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,…\n#> $ s <chr> \"S01\", \"S01\", \"S01\", \"S01\", \"S01\", \"S01\", \"S01\", \"S01\", \"S01\", \"S01\"…\n```\n:::\n\n\nAggreghiamo quindi i dati per operatore, calcolando le statistiche sufficienti necessarie per il modello: il numero totale di successi e il numero di prove completate. Includiamo anche la proporzione empirica di successi come riferimento descrittivo iniziale.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nby_subject <- tt_dat |> \n  group_by(s) |> \n  summarise(\n    y = sum(y),\n    n_trials = n(),\n    prop_emp = y / n_trials,\n    .groups = \"drop\"\n  ) |> \n  arrange(s)\n\nby_subject |>  \n  head()\n#> # A tibble: 6 × 4\n#>   s         y n_trials prop_emp\n#>   <chr> <int>    <int>    <dbl>\n#> 1 S01       1       10      0.1\n#> 2 S02       2       10      0.2\n#> 3 S03       3       10      0.3\n#> 4 S04       3       10      0.3\n#> 5 S05       3       10      0.3\n#> 6 S06       3       10      0.3\n```\n:::\n\n\n### Verifica predittiva a priori\n\nPrima di adattare il modello ai dati, è buona pratica verificare che le distribuzioni a priori scelte generino previsioni ragionevoli. In altre parole, vogliamo assicurarci che le nostre *prior* non escludano a priori scenari plausibili né favoriscano eccessivamente valori estremi.\n\nPer gli iperparametri $\\alpha$ e $\\beta$ adottiamo distribuzioni Gamma debolmente informative, specificate nella parametrizzazione *shape-rate*: $\\alpha \\sim \\text{Gamma}(2, 2)$ e $\\beta \\sim \\text{Gamma}(2, 2)$. Queste *prior* consentono una vasta di configurazioni possibili per la distribuzione Beta della popolazione, senza imporre vincoli troppo restrittivi.\n\nGeneriamo campioni dalla distribuzione predittiva a priori per visualizzare le implicazioni di queste scelte:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(1)\na_draw <- rgamma(2000, shape = 2, rate = 2)\nb_draw <- rgamma(2000, shape = 2, rate = 2)\nmu_draw <- a_draw / (a_draw + b_draw)\nkappa_draw <- a_draw + b_draw\n\ntibble(mu = mu_draw) |> \n  ggplot(aes(x = mu)) +\n  geom_density(linewidth = 0.6, fill = col_prior, alpha = 0.5) +\n  labs(x = \"Media della popolazione (μ)\", \n       y = \"Densità\", \n       title = \"Distribuzione predittiva a priori\\nper la media della popolazione\",\n       subtitle = \"Prior Gamma(2,2) su α e β\")\n```\n\n::: {.cell-output-display}\n![](10_stan_hier_beta_binom_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nCome possiamo osservare, la distribuzione a priori per la media della popolazione $\\mu$ si distribuisce su un ampio intervallo di valori, senza concentrarsi in modo inappropriato su alcuna regione particolare. Questo comportamento riflette un atteggiamento epistemico prudente: prima di osservare i dati, non imponiamo forti vincoli sulla performance media degli operatori.\n\nAllo stesso modo, le distribuzioni implicite per il parametro di concentrazione $\\kappa$ non impongono né un'omogeneità estrema (che costringerebbe tutti gli operatori a essere quasi identici) né una variabilità eccessiva (che impedirebbe al modello di condividere informazioni tra gli individui). Qualora si desideri un controllo ancora più esplicito su questi aspetti, è possibile specificare *prior* direttamente sulla parametrizzazione $(\\mu, \\kappa)$.\n\n### Implementazione del modello in Stan\n\nTraduciamo ora la struttura generativa del modello in codice Stan. L'architettura del programma riflette direttamente la struttura gerarchica descritta in precedenza.\n\n**Blocco `data`**: specifica i dati osservati che forniamo al modello: il numero di operatori, i successi ottenuti da ciascuno e il numero di prove completate.\n\n**Blocco `parameters`**: dichiara i parametri da stimare – gli iperparametri $\\alpha$ e $\\beta$ che caratterizzano la distribuzione Beta di popolazione e le probabilità individuali $p_i$ per ciascun operatore, vincolate all'intervallo $[0,1]$.\n\n**Blocco `model`**: specifica le distribuzioni a priori per gli iperparametri e la struttura gerarchica del modello. Qui definiamo esplicitamente che le probabilità individuali sono estratte da una distribuzione Beta comune e che i dati osservati seguono una distribuzione binomiale condizionata a tali probabilità.\n\n**Blocco `generated quantities`**: calcola quantità derivate di interesse, in particolare la media della popolazione $\\mu = \\alpha/(\\alpha + \\beta)$, che utilizzeremo per confrontare la performance media con la soglia casuale di 0.5.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstan_code <- \"\ndata {\n  int<lower=1> N;                  // numero di operatori\n  array[N] int<lower=0> y;         // successi per operatore\n  array[N] int<lower=1> n_trials;  // prove per operatore\n}\nparameters {\n  real<lower=0> alpha;             // parametro shape della Beta\n  real<lower=0> beta;              // parametro shape della Beta\n  array[N] real<lower=0, upper=1> p; // probabilità individuali\n}\nmodel {\n  alpha ~ gamma(2, 2);             // prior su alpha\n  beta  ~ gamma(2, 2);             // prior su beta\n  \n  // Livello di popolazione: le probabilità individuali seguono una Beta comune\n  for (i in 1:N) {\n    p[i] ~ beta(alpha, beta);\n  }\n  \n  // Livello individuale: verosimiglianza binomiale\n  for (i in 1:N) {\n    y[i] ~ binomial(n_trials[i], p[i]);\n  }\n}\ngenerated quantities {\n  real overall_p = alpha / (alpha + beta); // media di popolazione\n}\n\"\n```\n:::\n\n\nProcediamo alla compilazione del modello:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod <- cmdstanr::cmdstan_model(write_stan_file(stan_code))\n```\n:::\n\n\nPrepariamo i dati nel formato richiesto da Stan:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstan_data <- list(\n  N        = nrow(by_subject),\n  y        = as.integer(by_subject$y),\n  n_trials = as.integer(by_subject$n_trials)\n)\n```\n:::\n\n\nE infine avviamo il campionamento MCMC utilizzando l'algoritmo di default (*No-U-Turn Sampler*):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(84735)\nfit <- mod$sample(\n  data = stan_data,\n  chains = 4,\n  parallel_chains = 4,\n  iter_warmup = 1000,\n  iter_sampling = 2000,\n  adapt_delta = 0.9,\n  max_treedepth = 12,\n  refresh = 0\n)\n```\n:::\n\n\n### Diagnostica della convergenza\n\nAl termine del campionamento, è essenziale verificare che l'algoritmo MCMC abbia raggiunto la convergenza. Esaminiamo le principali diagnostiche per gli iperparametri e per un sottoinsieme rappresentativo delle probabilità individuali:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nposterior::summarise_draws(\n  fit$draws(variables = c(\"alpha\", \"beta\", \"overall_p\", \"p[1]\", \"p[2]\", \"p[3]\")),\n  \"mean\", \"sd\", \"rhat\", \"ess_bulk\", \"ess_tail\"\n)\n#> # A tibble: 6 × 6\n#>   variable   mean     sd  rhat ess_bulk ess_tail\n#>   <chr>     <dbl>  <dbl> <dbl>    <dbl>    <dbl>\n#> 1 alpha     2.30  0.625   1.00    6375.    5674.\n#> 2 beta      2.83  0.777   1.00    6916.    5882.\n#> 3 overall_p 0.449 0.0453  1.00    9668.    6381.\n#> 4 p[1]      0.217 0.105   1.00   13325.    5691.\n#> 5 p[2]      0.283 0.116   1.00   14168.    5108.\n#> 6 p[3]      0.349 0.120   1.00   13573.    5489.\n```\n:::\n\n\nGli indici $\\hat{R}$ prossimi a 1.00 indicano che le catene hanno raggiunto una distribuzione stazionaria comune, mentre valori di dimensione campionaria effettiva (ESS) dell'ordine delle migliaia confermano che disponiamo di un numero sufficiente di campioni indipendenti per l'inferenza. In presenza di problemi di convergenza, questi indicatori mostrerebbero segnali d'allarme che richiederebbero un intervento correttivo.\n\n### Analisi dello *shrinkage* e interpretazione dei risultati\n\nUno degli aspetti più illuminanti dell'analisi consiste nell'esaminare visivamente il fenomeno dello *shrinkage*. Estraiamo le stime a posteriori delle probabilità individuali e confrontiamole graficamente con le proporzioni empiriche osservate.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Estrazione delle distribuzioni a posteriori\ndraws_p  <- fit$draws(\"p\")\ndraws_mu <- fit$draws(\"overall_p\")\nmu_hat   <- posterior::summarise_draws(draws_mu, \"mean\")$mean\n\n# Calcolo delle statistiche riassuntive per le probabilità individuali\nsum_p <- posterior::summarise_draws(draws_p, \"mean\", \"median\", \"sd\") %>%\n  mutate(s = as.integer(stringr::str_extract(variable, \"\\\\d+\"))) %>%\n  arrange(s)\n\n# Calcolo degli intervalli di credibilità al 90%\nqs <- posterior::summarise_draws(draws_p, ~ quantile2(.x, probs = c(0.05, 0.95))) %>%\n  mutate(s = as.integer(stringr::str_extract(variable, \"\\\\d+\"))) %>%\n  arrange(s)\n\nsum_p <- sum_p %>% \n  left_join(qs %>% select(s, q5 = `q5`, q95 = `q95`), by = \"s\")\n\n# Integrazione con i dati osservati\ndf_shrink <- by_subject %>%\n  mutate(s_idx = as.integer(stringr::str_extract(s, \"\\\\d+\"))) %>%\n  arrange(s_idx) %>%\n  select(s, s_idx, prop_emp, n_trials) %>%\n  inner_join(\n    sum_p %>% select(s, post_mean = mean, post_med = median, \n                     post_q05 = q5, post_q95 = q95),\n    by = join_by(s_idx == s)\n  ) %>%\n  arrange(prop_emp) %>%\n  mutate(s_ord = factor(s, levels = s))\n```\n:::\n\n\nCreiamo ora una visualizzazione che mostra simultaneamente le proporzioni empiriche, le stime a posteriori e l'entità della contrazione verso la media di popolazione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(df_shrink, aes(x = s_ord)) +\n  # Segmenti per lo shrinkage\n  geom_segment(aes(xend = s_ord, y = prop_emp, yend = post_mean), \n               linewidth = 0.8, alpha = 0.7, color = col_shrinkage,\n               arrow = arrow(length = unit(0.1, \"cm\"), ends = \"both\", type = \"closed\")) +\n  # Punti per le stime empiriche\n  geom_point(aes(y = prop_emp), size = 3, alpha = 0.9, color = col_data, \n             shape = 16) +\n  # Punti per le stime a posteriori\n  geom_point(aes(y = post_mean), size = 3, color = col_posterior, shape = 17) +\n  # Intervalli di credibilità\n  geom_errorbar(aes(ymin = post_q05, ymax = post_q95), \n                width = 0.2, alpha = 0.8, linewidth = 0.6, color = col_interval) +\n  # Media di popolazione\n  geom_hline(yintercept = mu_hat, linetype = \"dashed\", alpha = 0.8,\n             color = col_mean, linewidth = 0.7) +\n  labs(x = \"Operatore\", \n       y = \"Probabilità di successo\",\n       title = \"Effetto di shrinkage\\nnel modello gerarchico beta-binomiale\",\n       subtitle = sprintf(\"Shrinkage verso la media di popolazione: %.3f\", mu_hat),\n       caption = paste0(\n         \"Punti \", color_names[col_data], \": proporzioni empiriche | \",\n         \"Punti \", color_names[col_posterior], \": stime a posteriori | \",\n         \"Segmenti \", color_names[col_shrinkage], \": entità dello shrinkage\"\n       )) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 9),\n    axis.text.y = element_text(size = 9),\n    plot.caption = element_text(size = 8, color = \"gray40\", hjust = 0),\n    plot.subtitle = element_text(face = \"bold\", color = col_mean)\n  ) +\n  scale_x_discrete(labels = function(x) gsub(\"s\", \"Op. \", x)) +\n  # Evidenzia i segmenti di shrinkage più ampi\n  geom_segment(data = df_shrink %>% \n                 mutate(shrinkage_magnitude = abs(prop_emp - post_mean)) %>%\n                 filter(shrinkage_magnitude > quantile(abs(prop_emp - post_mean), 0.7)),\n               aes(xend = s_ord, y = prop_emp, yend = post_mean),\n               linewidth = 1.2, alpha = 1, color = col_highlight)\n```\n\n::: {.cell-output-display}\n![](10_stan_hier_beta_binom_files/figure-html/tt-shrinkage-plot-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nIn questa visualizzazione, i punti rossi rappresentano le proporzioni empiriche (i dati grezzi), mentre i triangoli blu mostrano le stime a posteriori prodotte dal modello gerarchico. I segmenti verticali collegano ciascuna coppia di stime, rendendo visibile l'entità dello shrinkage. Gli intervalli di credibilità al 90% (barre verticali) quantificano l'incertezza associata a ciascuna stima a posteriori.\n\nSi nota chiaramente un effetto di regolarizzazione: le stime a posteriori sono sistematicamente \"attratte\" verso la media della popolazione (linea tratteggiata), con un effetto più marcato per gli operatori con proporzioni empiriche più estreme. Questo comportamento è particolarmente pronunciato per gli operatori che hanno ottenuto solo successi o solo insuccessi nelle dieci prove: in questi casi, la proporzione empirica suggerirebbe probabilità pari a 0 o 1, ma il modello gerarchico, riconoscendo la limitatezza del campione (solo dieci prove), produce stime più moderate e realistiche.\n\nLa regolarizzazione operata dal modello gerarchico sembra sostanziale, ma con sole dieci prove per partecipante, è metodologicamente appropriata. In pratica, il modello ci sta dicendo: \"Attenzione, dieci prove sono poche per poter affermare con certezza che questa performance estrema rifletta la vera abilità dell'operatore; dobbiamo tenere conto anche di ciò che sappiamo sugli altri partecipanti\". Questo bilanciamento automatico tra l'evidenza individuale e l'informazione di gruppo rappresenta uno dei principali vantaggi dell'approccio gerarchico.\n\n### Verifica predittiva a posteriori\n\nUn ulteriore passo essenziale consiste nel valutare l'adeguatezza complessiva del modello mediante una verifica predittiva a posteriori. L'idea di fondo è semplice: se il modello è adeguato, dovrebbe essere in grado di generare dati simulati simili ai dati realmente osservati.\n\nProcediamo campionando dalla distribuzione predittiva a posteriori: per ciascuna iterazione MCMC, si genera un dataset replicato completo utilizzando i valori degli iperparametri campionati in quell'iterazione. Quindi, confrontiamo le statistiche sintetiche dei dati osservati con la distribuzione di queste stesse statistiche calcolate sui dati replicati.\n\nIn particolare, ci concentriamo sulla media complessiva delle proporzioni individuali, una statistica naturale per valutare la tendenza centrale della performance.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\ndraws <- posterior::as_draws_df(fit$draws(c(\"alpha\", \"beta\")))\nS <- 1000\nidx <- sample(seq_len(nrow(draws)), S, replace = TRUE)\n\nyrep_mean <- numeric(S)\nyobs_mean <- mean(by_subject$y / by_subject$n_trials)\n\nfor (s in seq_len(S)) {\n  # Estrai i valori degli iperparametri per questa iterazione\n  a <- draws$alpha[idx[s]]\n  b <- draws$beta[idx[s]]\n  \n  # Genera probabilità individuali dalla distribuzione Beta di popolazione\n  p_ <- rbeta(nrow(by_subject), a, b)\n  \n  # Genera dati replicati dalla verosimiglianza binomiale\n  y_ <- rbinom(nrow(by_subject), size = by_subject$n_trials, prob = p_)\n  \n  # Calcola la statistica di interesse per questo dataset replicato\n  yrep_mean[s] <- mean(y_ / by_subject$n_trials)\n}\n\n# Visualizzazione\ntibble(yrep_mean = yrep_mean) %>%\n  ggplot(aes(x = yrep_mean)) +\n  geom_density(linewidth = 0.6, fill = col_prior, alpha = 0.5) +\n  geom_vline(xintercept = yobs_mean, linetype = \"dashed\", \n             color = col_data, linewidth = 1) +\n  annotate(\"text\", x = yobs_mean + 0.02, y = 10, \n           label = sprintf(\"Media osservata = %.3f\", yobs_mean),\n           color = col_data, hjust = 0) +\n  labs(x = \"Media delle proporzioni (dati replicati)\", \n       y = \"Densità\",\n       title = \"Verifica predittiva a posteriori\",\n       subtitle = \"Distribuzione delle medie replicate vs. valore osservato\")\n```\n\n::: {.cell-output-display}\n![](10_stan_hier_beta_binom_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nLa distribuzione delle medie replicate (in blu) rappresenta la variabilità che ci aspetteremmo di osservare in campioni futuri generati dallo stesso processo, secondo quanto stimato dal modello. La linea tratteggiata rossa indica il valore effettivamente osservato nei dati reali.\n\nSe il valore osservato cade in una regione di alta densità della distribuzione predittiva, come accade in questo caso, possiamo concludere che il modello è adeguato nel riprodurre questa caratteristica dei dati. Se invece il valore osservato cadesse in una coda estrema della distribuzione predittiva, ciò costituirebbe un segnale d'allarme, suggerendo che il modello potrebbe non catturare adeguatamente alcuni aspetti importanti del processo generativo dei dati.\n\nEventuali discrepanze sistematiche potrebbero indicare la necessità di rivedere le assunzioni del modello, per esempio, riconsiderando le distribuzioni a priori sulla concentrazione, o valutando se l'ipotesi di scambiabilità semplice sia appropriata, oppure esplorando l'inclusione di covariate per modellare fonti di eterogeneità non catturate dalla struttura gerarchica di base.\n\n### Valutazione dell'efficacia della terapia tattile\n\nL'obiettivo principale dello studio è determinare se i praticanti del *Therapeutic Touch* sono in grado di identificare il campo energetico umano con un'accuratezza superiore a quella attesa per puro caso (0.5). Per rispondere a questa domanda, possiamo esaminare direttamente la distribuzione a posteriori della probabilità media di successo nella popolazione $\\mu$, ovvero `overall_p`.\n\nCalcoliamo gli intervalli di credibilità (IC) per questo parametro chiave:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calcolo dell'intervallo di credibilità per l'accuratezza media\ndraws_mu <- fit$draws(\"overall_p\")\nmu_summary <- posterior::summarise_draws(\n  draws_mu,\n  mean = ~mean(.x),\n  sd = ~sd(.x),\n  ~quantile2(.x, probs = c(0.025, 0.05, 0.25, 0.5, 0.75, 0.95, 0.975))\n)\n\nprint(mu_summary)\n#> # A tibble: 1 × 10\n#>   variable   mean     sd  q2.5    q5   q25   q50   q75   q95 q97.5\n#>   <chr>     <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n#> 1 overall_p 0.449 0.0453 0.361 0.375 0.418 0.449 0.479 0.523 0.537\n```\n:::\n\n\nPossiamo anche calcolare la probabilità a posteriori che l'accuratezza media sia maggiore di 0.5:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_above_chance <- posterior::summarise_draws(\n  draws_mu,\n  prob_above_0.5 = ~mean(.x > 0.5)\n)\nprint(prob_above_chance)\n#> # A tibble: 1 × 2\n#>   variable  prob_above_0.5\n#>   <chr>              <dbl>\n#> 1 overall_p          0.134\n```\n:::\n\n\n**Interpretazione:** l'intervallo di credibilità al 95% per l'accuratezza media della popolazione ($\\mu$) è [0.361, 0.537]. Questo intervallo contiene il valore di riferimento 0.5 (anche se la maggior parte della massa della distribuzione, ovvero, il 79% dell'IC, si trova al di sotto di esso). La probabilità a posteriori che l'accuratezza media sia maggiore di 0.5 è solo del %.\n\n**Conclusione sull'efficacia:** i dati non forniscono prove convincenti a sostegno dell'efficacia del *Therapeutic Touch*. La performance media del gruppo di operatori non è statisticamente distinguibile dal caso, con una lieve tendenza verso performance peggiori rispetto al valore atteso di 0.5. Questo risultato, ottenuto da un modello che tiene conto della variabilità individuale, fornisce una risposta robusta alla domanda di ricerca originale, in linea con le conclusioni dello studio di @rosa1998close.\n\n### Vantaggi del modello gerarchico in questo contesto\n\nL'adozione di un modello gerarchico beta-binomiale in questo contesto sperimentale offre diversi vantaggi metodologici rispetto agli approcci non gerarchici:\n\n1. **Stime robuste per soggetti con dati limitati:** con solo 10 prove per operatore, le proporzioni empiriche grezze sono stime molto instabili delle reali abilità individuali. Il modello gerarchico, attraverso il meccanismo di *shrinkage*, produce stime più conservative e realistiche, in particolare per quegli operatori con proporzioni empiriche estreme (0 o 1), evitando così conclusioni fuorvianti sulle abilità individuali basate su evidenze aneddotiche.\n\n2. **Inferenza simultanea a più livelli:** il modello ci permette di trarre conclusioni sia a livello individuale (le abilità specifiche $p_i$) che a livello di popolazione (l'accuratezza media $\\mu$ e l'eterogeneità $\\kappa$), il tutto all'interno di un unico quadro coerente. Al contrario, un'analisi separata per ciascun operatore non solo fallirebbe nel fornire una stima affidabile della tendenza centrale, ma perderebbe del tutto l'informazione sull'eterogeneità sistematica del gruppo, limitando la generalizzabilità dei risultati.\n\n3. **Quantificazione dell'eterogeneità:** il parametro di concentrazione $\\kappa$ (o la sua varianza equivalente nella distribuzione Beta) misura direttamente la dispersione delle abilità individuali nella popolazione. Questo valore non è solo un iperparametro tecnico, ma fornisce una risposta sostanziale a una domanda di ricerca fondamentale: quanto sono simili gli operatori? Un valore elevato di $\\kappa$ indica una popolazione omogenea, con abilità degli operatori concentrate attorno alla media comune. Un valore ridotto di $\\kappa$ indica invece una popolazione marcatamente eterogenea, caratterizzata da una grande variabilità delle abilità tra gli individui.\n\n4. **Gestione automatica dell'incertezza:** il modello propaga l'incertezza in modo appropriato a tutti i livelli della gerarchia. Gli intervalli di credibilità delle probabilità individuali incorporano l'incertezza sia sulla stima del singolo operatore che sugli iperparametri della popolazione, producendo intervalli più calibrati e realistici.\n\n5. **Pooling parziale delle informazioni:** a differenza di un approccio che aggrega tutti i dati (ignorando le differenze individuali) o che analizza ogni soggetto separatamente (ignorando le similarità), il modello gerarchico trova un equilibrio ottimale tra questi due estremi. Il grado di *pooling* è determinato dai dati stessi: maggiore è il numero di prove per soggetto, minore è lo *shrinkage* verso la media.\n\nIn sintesi, la struttura gerarchica rappresenta una scelta metodologica ottimale per l'analisi di dati sperimentali in psicologia, caratterizzati da un tipico disegno \"multi-livello\": molti partecipanti, ciascuno con un numero limitato di osservazioni ripetute. A differenza di altri modelli che trattano le osservazioni come indipendenti o che considerano i soggetti in modo isolato, questo modello sfrutta l'informazione di gruppo per produrre stime individuali regolarizzate e stabili, anche quando i dati grezzi sarebbero troppo scarsi. Contemporaneamente, esso fornisce una valutazione integrata e quantitativa dell'eterogeneità della popolazione, preservando una calibrazione rigorosa dell'incertezza statistica a tutti i livelli.\n\n## Dal modello beta-binomiale ai modelli gaussiani gerarchici\n\nOra che abbiamo sviluppato una comprensione concreta del funzionamento dei modelli gerarchici attraverso il caso beta-binomiale, possiamo anticipare un'importante transizione: l'estensione ai modelli gaussiani a effetti misti per dati continui. Questa transizione, pur comportando un cambiamento nella formalizzazione matematica, mantiene inalterata la struttura concettuale che abbiamo esplorato. La tabella seguente evidenzia le corrispondenze tra i due framework:\n\n| Aspetto | Modello Beta-Binomiale | Modello Gaussiano Gerarchico |\n|---------|------------------------|------------------------------|\n| **Parametri individuali** | $p_i$ (probabilità di successo) | $\\theta_j$ (effetti casuali) |\n| **Distribuzione di popolazione** | $\\text{Beta}(\\alpha, \\beta)$ | $\\text{Normale}(\\mu, \\sigma_\\theta)$ |\n| **Parametro di concentrazione** | $\\kappa = \\alpha + \\beta$ | Deviazione standard $\\sigma_\\theta$ |\n| **Verosimiglianza** | $y_i \\sim \\text{Binomiale}(n_i, p_i)$ | $y_{ij} \\sim \\text{Normale}(\\theta_j, \\sigma_y)$ |\n| **Meccanismo di shrinkage** | Regolato da $w_i = n_i/(n_i + \\kappa)$ | Regolato da $\\sigma_\\theta$ e dall'informazione disponibile |\n\nIl principio fondamentale rimane invariato: il modello stima simultaneamente i parametri individuali e le caratteristiche della distribuzione della popolazione. Il fenomeno dello *shrinkage* emerge naturalmente come conseguenza della struttura gerarchica e bilancia automaticamente l'evidenza individuale con l'informazione di gruppo.\n\nNel caso gaussiano:\n\n- le probabilità di successo $p_i$ vengono sostituite da effetti casuali $\\theta_j$, che rappresentano le deviazioni individuali rispetto alla media di gruppo;\n- la distribuzione Beta viene sostituita da una distribuzione Normale per gli effetti casuali;\n- il parametro di concentrazione $\\kappa$ trova il suo analogo nella deviazione standard $\\sigma_\\theta$: valori piccoli di $\\sigma_\\theta$ indicano maggiore omogeneità (shrinkage più forte), mentre valori grandi permettono maggiore eterogeneità.\n\nSebbene le formule matematiche specifiche siano diverse, la logica inferenziale sottostante rimane la stessa: la condivisione delle informazioni tra le unità, la regolarizzazione delle stime individuali tramite le informazioni di gruppo e l'adattamento automatico del grado di regolarizzazione in base alla quantità di dati disponibili.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIl modello gerarchico beta-binomiale si presta in modo ideale come punto di partenza pedagogico per l'inferenza multilivello Questo perché, grazie alla trasparenza derivante dalla coniugazione Beta-binomiale e da una parametrizzazione intuitiva (media $\\mu$ e concentrazione $\\kappa$), è possibile visualizzare il cuore dell'inferenza gerarchica: il meccanismo dello *shrinkage*.\n\nLa formula esplicita del peso $w_i = n_i/(n_i + \\kappa)$ non è solo un risultato algebrico, ma l'espressione matematica di un importante principio inferenziale: il modello bilancia in modo automatico e ottimale l'informazione individuale e quella di gruppo. In tal modo, la struttura gerarchica non appare come un compromesso arbitrario, ma come la soluzione naturale alla tensione fondamentale tra specificità individuale e generalizzazione di gruppo, una conseguenza diretta dell'assunzione di scambiabilità e del quadro probabilistico.\n\nPadroneggiare questo caso esemplare fornisce quindi un framework concettuale robusto e trasferibile. Una volta consolidata l'intuizione nel dominio discreto e binomiale, il lettore sarà in grado di identificare e generalizzare i principi operativi fondamentali, ovvero la condivisione dell'informazione, la regolarizzazione e la stima simultanea, ai più comuni modelli gaussiani a effetti misti per dati continui. I dettagli matematici possono cambiare, ma la filosofia statistica fondamentale rimane invariata: la condivisione parsimoniosa dell'informazione per migliorare le inferenze a tutti i livelli.\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.5.2 (2025-10-31)\n#> Platform: aarch64-apple-darwin20\n#> Running under: macOS Tahoe 26.2\n#> \n#> Matrix products: default\n#> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] stringr_1.6.0         cmdstanr_0.8.0        ragg_1.5.0           \n#>  [4] tinytable_0.15.2      withr_3.0.2           systemfonts_1.3.1    \n#>  [7] patchwork_1.3.2       ggdist_3.3.3          tidybayes_3.0.7      \n#> [10] bayesplot_1.15.0      ggplot2_4.0.1         reliabilitydiag_0.2.1\n#> [13] priorsense_1.2.0      posterior_1.6.1       loo_2.9.0            \n#> [16] rstan_2.32.7          StanHeaders_2.32.10   brms_2.23.0          \n#> [19] Rcpp_1.1.0            sessioninfo_1.2.3     conflicted_1.2.0     \n#> [22] janitor_2.2.1         matrixStats_1.5.0     modelr_0.1.11        \n#> [25] tibble_3.3.0          dplyr_1.1.4           tidyr_1.3.2          \n#> [28] rio_1.2.4             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] gridExtra_2.3         inline_0.3.21         sandwich_3.1-1       \n#>  [4] rlang_1.1.6           magrittr_2.0.4        multcomp_1.4-29      \n#>  [7] snakecase_0.11.1      otel_0.2.0            compiler_4.5.2       \n#> [10] vctrs_0.6.5           pkgconfig_2.0.3       arrayhelpers_1.1-0   \n#> [13] fastmap_1.2.0         backports_1.5.0       labeling_0.4.3       \n#> [16] utf8_1.2.6            rmarkdown_2.30        ps_1.9.1             \n#> [19] purrr_1.2.0           xfun_0.55             cachem_1.1.0         \n#> [22] jsonlite_2.0.0        broom_1.0.11          parallel_4.5.2       \n#> [25] R6_2.6.1              stringi_1.8.7         RColorBrewer_1.1-3   \n#> [28] lubridate_1.9.4       estimability_1.5.1    knitr_1.51           \n#> [31] zoo_1.8-15            pacman_0.5.1          Matrix_1.7-4         \n#> [34] splines_4.5.2         timechange_0.3.0      tidyselect_1.2.1     \n#> [37] abind_1.4-8           yaml_2.3.12           codetools_0.2-20     \n#> [40] processx_3.8.6        curl_7.0.0            pkgbuild_1.4.8       \n#> [43] lattice_0.22-7        bridgesampling_1.2-1  S7_0.2.1             \n#> [46] coda_0.19-4.1         evaluate_1.0.5        survival_3.8-3       \n#> [49] RcppParallel_5.1.11-1 pillar_1.11.1         tensorA_0.36.2.1     \n#> [52] checkmate_2.3.3       stats4_4.5.2          distributional_0.5.0 \n#> [55] generics_0.1.4        rprojroot_2.1.1       rstantools_2.5.0     \n#> [58] scales_1.4.0          xtable_1.8-4          glue_1.8.0           \n#> [61] emmeans_2.0.1         tools_4.5.2           data.table_1.18.0    \n#> [64] mvtnorm_1.3-3         grid_4.5.2            QuickJSR_1.8.1       \n#> [67] colorspace_2.1-2      nlme_3.1-168          cli_3.6.5            \n#> [70] textshaping_1.0.4     svUnit_1.0.8          Brobdingnag_1.2-9    \n#> [73] V8_8.0.1              gtable_0.3.6          digest_0.6.39        \n#> [76] TH.data_1.1-5         htmlwidgets_1.6.4     farver_2.1.2         \n#> [79] memoise_2.0.1         htmltools_0.5.9       lifecycle_1.0.4      \n#> [82] MASS_7.3-65\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n\n",
    "supporting": [
      "10_stan_hier_beta_binom_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}