{
  "hash": "74b6deaf31f15015d11fb0748635c82c",
  "result": {
    "engine": "knitr",
    "markdown": "# Entropia e informazione di Shannon {#sec-entropy-shannon-information}\n\n## Introduzione {.unnumbered .unlisted}\n\nIn ambito probabilistico, l'entropia fornisce una misura quantitativa del grado di incertezza di un sistema. Si consideri il tentativo di prevedere la risposta di uno studente a un test a scelta multipla. In assenza di informazioni sulla sua preparazione, l'ipotesi più conservativa è che tutte le opzioni siano equiprobabili — una condizione che corrisponde al massimo livello di incertezza. Se invece sapessimo che lo studente è molto preparato e fornisce quasi sempre la risposta corretta, l'incertezza risulterebbe drasticamente ridotta. È questa quantificazione sistematica dell'incertezza a costituire l'essenza del concetto di entropia.\n\nUn esempio chiarisce questa dualità: il lancio di una moneta equilibrata riflette un'elevata entropia a causa dell'intrinseca imprevedibilità del risultato. All'opposto, il comportamento stereotipato di un paziente che fornisce invariabilmente la medesima risposta rappresenta una situazione a entropia pressoché nulla.\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\n- Introdurre il concetto di informazione e la sua unità di misura (bit). \n- Definire l'entropia come media della sorpresa di Shannon. \n- Interpretare l'entropia in termini di incertezza e capacità di codifica.  \n- Stimare l'entropia da distribuzioni teoriche e da campioni osservati.  \n- Collegare l'entropia alla codifica di Huffman e al limite teorico di compressione.  \n\n::: {.callout-tip collapse=true}\n## Prerequisiti\n\n- Per i concetti di base sulla teoria dell'informazione, si rimanda ai primi due capitoli di  *Information Theory: A Tutorial Introduction* [@stone2022information].\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n\nlibrary(igraph)\nlibrary(ggraph)\nlibrary(tidygraph)\n\n# Funzione per calcolare la lunghezza media del codice di Huffman\nhuffman_encoding <- function(probabilities) {\n  # Crea la \"coda con priorità\" iniziale come lista di liste\n  heap <- lapply(names(probabilities), function(sym) list(probabilities[[sym]], list(sym, \"\")))\n\n  # Funzione per ordinare la heap per probabilità (peso)\n  sort_heap <- function(heap) {\n    heap[order(sapply(heap, function(x) x[[1]]))]\n  }\n\n  # Costruzione dell'albero di Huffman\n  while (length(heap) > 1) {\n    heap <- sort_heap(heap)\n    lo <- heap[[1]]\n    hi <- heap[[2]]\n    heap <- heap[-c(1, 2)]\n\n    # Aggiunge i prefissi \"0\" e \"1\" ai codici\n    for (i in seq_along(lo)[-1]) {\n      lo[[i]][[2]] <- paste0(\"0\", lo[[i]][[2]])\n    }\n    for (i in seq_along(hi)[-1]) {\n      hi[[i]][[2]] <- paste0(\"1\", hi[[i]][[2]])\n    }\n\n    merged <- c(list(lo[[1]] + hi[[1]]), lo[-1], hi[-1])\n    heap <- append(heap, list(merged))\n  }\n\n  # Estrai la lista finale dei simboli e codici\n  final <- heap[[1]][-1]\n  names(final) <- sapply(final, function(x) x[[1]])\n\n  # Crea dizionario con codici\n  huffman_dict <- lapply(final, function(x) x[[2]])\n\n  # Calcolo della lunghezza media del codice\n  avg_length <- sum(mapply(function(sym, code) {\n    probabilities[[sym]] * nchar(code)\n  }, names(huffman_dict), huffman_dict))\n\n  return(list(avg_length = avg_length, codes = huffman_dict))\n}\n```\n:::\n\n:::\n\n## Che cos'è l'informazione?\n\nL'informazione può essere concettualizzata come la riduzione di incertezza riguardo a un insieme di possibili esiti. Il *bit* rappresenta l'unità fondamentale, corrispondente alla quantità di conoscenza ottenuta quando si sceglie tra due alternative equiprobabili. \n\nMatematicamente, ogni volta che il numero di possibili esiti raddoppia, è richiesto un bit aggiuntivo per specificare univocamente un elemento. Questa relazione è catturata dalla funzione logaritmica in base 2: dato un insieme di $N$ alternative equiprobabili, la quantità di informazione necessaria per identificare un elemento specifico è $\\log_2(N)$ bit.\n\n### Dalle scelte ai bit: un esempio visivo\n\nPer comprendere come l'informazione venga misurata in bit, consideriamo un percorso con incroci sequenziali. Ogni scelta tra due alternative equiprobabili (sinistra o destra) può essere codificata con un singolo bit, convenzionalmente rappresentato con 0 per una direzione e 1 per l'altra.\n\nIl seguente diagramma ad albero illustra questo principio. Ogni percorso dalla radice alle foglie è univocamente descritto da una sequenza di bit, dove ciascun bit rappresenta una decisione binaria. Per raggiungere la destinazione `D011`, la sequenza corretta è `0-1-1`, corrispondente a tre scelte consecutive.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](01_entropy_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nL'albero mostra come, partendo dal nodo radice `A`, ogni livello raddoppi il numero di percorsi possibili. Con tre decisioni sequenziali, otteniamo $2^3 = 8$ percorsi finali, ciascuno identificato da una stringa di 3 bit. Il logaritmo in base 2 del numero di esiti possibili ($\\log_2(8) = 3$) corrisponde esattamente al numero di bit necessari per specificare qualsiasi percorso.\n\nIn generale, dato un insieme di $m$ destinazioni distinte, il numero di bit necessari è:\n\n$$\nn = \\log_2 m.\n$$\n\nLa scelta del logaritmo in base 2 non è arbitraria: calcola l'esponente a cui elevare 2 per ottenere il numero di alternative, ovvero il numero di decisioni binarie necessarie per selezionare un'opzione tra $m$ possibilità equiprobabili.\n\n## La sorpresa e l'informazione di Shannon\n\nFinora abbiamo considerato situazioni con esiti equiprobabili. Introduciamo ora un elemento cruciale: la *probabilità dell'evento*. Eventi con probabilità differenti veicolano quantità di informazione diverse. Un evento altamente probabile genera scarsa sorpresa e contribuisce poco all'informazione; un evento raro produce una sorpresa significativa e trasmette un'informazione più sostanziale.\n\nShannon formalizzò questa intuizione definendo l'informazione (o \"sorpresa\") associata a un evento $x$ come:\n\n$$\nh(x) = \\log_2 \\frac{1}{p(x)} = -\\log_2 p(x) \\ \\text{bit}.\n$$ {#eq-shannon-information-def}\n\nL'informazione è inversamente proporzionale alla probabilità: al diminuire di $p(x)$, aumenta $h(x)$ secondo una progressione logaritmica.[^information]\n\n[^information]: Per le proprietà dei logaritmi: $\\log(1/x) = -\\log(x)$, poiché $\\log(1/x) = \\log(1) - \\log(x) = 0 - \\log(x)$.\n\nConsideriamo tre eventi con probabilità 0.5, 0.25 e 0.10. La sorpresa corrispondente è 1.00, 2.00 e 3.32 bit rispettivamente. Un'osservazione inattesa possiede un \"peso informativo\" maggiore, modificando in misura più sostanziale il nostro stato di conoscenza.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np_vals <- seq(0.001, 1, by = 0.001)\nsurprise <- -log2(p_vals)\n\nggplot(data.frame(p = p_vals, h = surprise), aes(x = p, y = h)) +\n  geom_line(size = 1) +\n  labs(\n    x = \"Probabilità dell'evento p(x)\",\n    y = \"Sorpresa h(x) [bit]\",\n    title = \"Relazione tra probabilità e sorpresa nell'informazione di Shannon\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](01_entropy_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nLa curva mostra come la sorpresa cresca asintoticamente al diminuire della probabilità.\n\n## L'entropia di Shannon\n\nFinora abbiamo esaminato la sorpresa di singoli eventi. Per caratterizzare l'incertezza complessiva di un sistema che può generare esiti diversi, calcoliamo il *valore atteso* della sorpresa su tutti i possibili risultati. Questa quantità è l'*entropia*.\n\n### Definizione formale\n\nPer una variabile casuale discreta $X$ che assume valori $x_1, x_2, \\dots, x_n$ nell'insieme $\\mathcal{X}$, ciascuno con probabilità $p(x)$, l'entropia di Shannon è:\n\n$$\nH(X) = \\mathbb{E}[h(X)] = -\\sum_{x \\in \\mathcal{X}} p(x) \\log_2 p(x).\n$$ {#eq-entropy-def}\n\nOgni termine della sommatoria, $-p(x)\\log_2 p(x)$, rappresenta il contributo informativo medio dell'esito $x$, ponderato per la sua probabilità di occorrenza.\n\n::: {.callout-note}\n### Approfondimento matematico\n- La **sommatoria** considera tutti gli elementi dello spazio campionario.\n- Il **logaritmo in base 2** quantifica l'informazione in bit, coerente con l'interpretazione in termini di scelte binarie.\n- Il **segno negativo** compensa il fatto che i logaritmi di probabilità ($0 \\leq p(x) \\leq 1$) sono non positivi, producendo una quantità sempre non negativa.\n- Per convenzione, $0 \\cdot \\log_2 0 = 0$: eventi impossibili non contribuiscono all'entropia.\n:::\n\n### Proprietà fondamentali\n\nL'entropia possiede tre caratteristiche matematiche fondamentali:\n\n**Valore massimo.** L'entropia raggiunge il massimo quando tutti gli esiti sono equiprobabili. In questa configurazione di massima indeterminazione, non disponiamo di alcuna informazione privilegiata per prevedere il risultato. Per una variabile con $n$ esiti, il massimo è $\\log_2 n$ bit.\n\n**Valore minimo.** L'entropia è zero quando il risultato è deterministico, cioè quando un singolo evento ha probabilità 1. Non sussiste alcuna incertezza: l'osservazione non genera sorpresa.\n\n**Additività.** Per variabili casuali indipendenti $X$ e $Y$:\n$$\nH(X, Y) = H(X) + H(Y).\n$$\nL'incertezza totale di un sistema di variabili indipendenti è la somma delle incertezze individuali.\n\n### Interpretazione operativa\n\nL'entropia può essere interpretata in due modi complementari:\n\n1. **Come sorpresa media attesa:** è la quantità media di informazione che ci aspettiamo di ricevere osservando ripetutamente le realizzazioni della variabile.\n\n2. **Come lunghezza media minima di codifica:** rappresenta il numero medio di bit necessari per descrivere un'osservazione di $X$ in uno schema di codifica ottimale. Questa è un'implicazione profonda: nessun algoritmo può rappresentare le realizzazioni di $X$ usando in media meno di $H(X)$ bit per simbolo.\n\nPossiamo anche convertire l'entropia in un numero equivalente di alternative equiprobabili:\n$$\nm = 2^{H(X)}.\n$$ {#eq-entropy-bits-equivalence}\n\nUn'entropia di $H(X)$ bit corrisponde alla stessa incertezza che sperimenteremmo scegliendo tra $m$ esiti tutti ugualmente probabili. Questa conversione fornisce un'utile intuizione: l'entropia misura l'\"ampiezza efficace\" dello spazio delle possibilità.\n\n::: {#exercise-entropy-discrete-rv .callout .exercise collapse=\"true\" collapsed=\"true\"}\n## Esercizio — Entropia di una moneta.\n\n**1. Moneta equa.**\n\nPer una moneta equilibrata con $p(\\text{testa}) = p(\\text{croce}) = 0.5$:\n\n$$\nH(X) = 0.5 \\log_2\\frac{1}{0.5} + 0.5 \\log_2\\frac{1}{0.5} = 1 \\ \\text{bit}.\n$$\nQuesto è il valore massimo per una variabile binaria.\n\n**2. Moneta sbilanciata.**\n\nPer $p(\\text{testa}) = 0.9$ e $p(\\text{croce}) = 0.1$:\n\nLa sorpresa di ciascun esito è:\n$$\nh(\\text{testa}) = \\log_2\\frac{1}{0.9} \\approx 0.15 \\ \\text{bit}, \\quad\nh(\\text{croce}) = \\log_2\\frac{1}{0.1} \\approx 3.32 \\ \\text{bit}.\n$$\n\nL'entropia media:\n$$\nH(X) = 0.9 \\times 0.15 + 0.1 \\times 3.32 \\approx 0.469 \\ \\text{bit}.\n$$\n\nSebbene l'esito raro (\"croce\") sia molto sorprendente, l'entropia media è inferiore a 1 bit perché quell'esito si verifica raramente.\n\n**3. Numero equivalente di alternative.**\n\nL'entropia di 0.469 bit corrisponde a:\n$$\nm = 2^{0.469} \\approx 1.38\n$$\nalternative equiprobabili. Questo non indica un dado fisico con 1.38 facce, ma quantifica l'incertezza media del sistema.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Funzione per calcolare l'entropia di una moneta\nentropy_coin <- function(p) {\n  ifelse(p == 0 | p == 1, 0,\n         -p * log2(p) - (1 - p) * log2(1 - p))\n}\n\n# Sequenza di probabilità\np_values <- seq(0, 1, by = 0.01)\nH_values <- entropy_coin(p_values)\n\n# Dati per i punti di esempio\npoints_df <- data.frame(\n  p = c(0.5, 0.9),\n  H = entropy_coin(c(0.5, 0.9)),\n  label = c(\"Moneta equa\\nH=1 bit\", \"Moneta sbilanciata\\nH=0.469 bit\")\n)\n\n# Grafico\nggplot(data.frame(p = p_values, H = H_values), aes(x = p, y = H)) +\n  geom_line(size = 1) +\n  geom_point(data = points_df, aes(x = p, y = H), color = \"brown\", size = 3) +\n  geom_text(data = points_df, aes(label = label), vjust = -1, hjust = 0.5) +\n  labs(\n    x = expression(paste(\"Probabilità di testa, \", p)),\n    y = \"Entropia H(X) [bit]\"\n  )\n```\n\n::: {.cell-output-display}\n![](01_entropy_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=85%}\n:::\n:::\n\n:::\n\n::: {#exercise-entropy-eight-sided-die .callout .exercise collapse=\"true\" collapsed=\"true\"}\n#### Esercizio — Entropia di un dado con otto facce.\n\nPer un dado equo con otto facce, tutti gli esiti hanno probabilità $p(x) = 1/8$:\n\n$$\nH(X) = - \\sum_{i=1}^{8} \\frac{1}{8} \\log_2 \\frac{1}{8} = \\log_2 8 = 3 \\text{ bit}.\n$$\n\nL'entropia coincide con $\\log_2 m$ perché la distribuzione è uniforme. Questo conferma che $m = 2^{H(X)} = 2^3 = 8$ alternative equiprobabili.\n::: \n\n::: {#exercise-entropy-discrete-rv-2 .callout .exercise collapse=\"true\" collapsed=\"true\"}\n#### Esercizio — Entropia di una variabile discreta non uniforme.\n\nSia $X$ con valori $a, b, c, d$ e probabilità $p(a) = \\frac{1}{2}$, $p(b) = \\frac{1}{4}$, $p(c) = \\frac{1}{8}$, $p(d) = \\frac{1}{8}$:\n\n$$\nH(X) = -\\left(\\frac{1}{2} \\cdot (-1) + \\frac{1}{4} \\cdot (-2) + \\frac{1}{8} \\cdot (-3) + \\frac{1}{8} \\cdot (-3)\\right) = \\frac{7}{4} = 1.75 \\text{ bit}.\n$$\n\nL'entropia dipende solo dalla distribuzione di probabilità, non dai valori specifici assunti dalla variabile.\n:::\n\n## Stimare l'entropia dai dati\n\n### Da distribuzioni teoriche\n\nQuando la distribuzione di probabilità è nota, l'entropia si calcola direttamente applicando la formula. Questo è il caso ideale, tipico dell'analisi teorica.\n\n### Da campioni osservati\n\nNella pratica della ricerca empirica, la distribuzione vera è ignota e deve essere stimata dai dati. L'approccio più diretto utilizza le frequenze relative come stime delle probabilità:\n\n$$\n\\hat{p}(x) = \\frac{\\text{conteggio delle osservazioni con valore } x}{n}\n$$\n\nL'entropia campionaria diventa:\n$$\n\\hat{H}(X) = -\\sum_{x \\in \\mathcal{X}} \\hat{p}(x) \\log_2 \\hat{p}(x)\n$$\n\nQuesta stima quantifica l'incertezza presente nella distribuzione osservata. Un campione con frequenze uniformi avrà entropia alta; un campione dominato da un singolo valore avrà entropia bassa.\n\n**Nota:** la stima può essere soggetta a bias, specialmente con campioni piccoli rispetto al numero di categorie.\n\n::: {#exercise-entropy-sample-obs .callout .exercise collapse=\"true\" collapsed=\"true\"}\n#### Esercizio — Entropia di due campioni.\n\nConsideriamo:\n$$\n\\begin{align}\nx &= \\{1, 2, 3, 3, 3, 3, 2, 1, 3, 3, 2, 1, 1, 4, 4, 3, 1, 2\\}, \\notag\\\\\ny &= \\{3, 4, 1, 1, 1, 1, 4, 3, 1, 1, 4, 3, 3, 2, 2, 1, 3, 4\\}. \\notag\n\\end{align}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- c(1, 2, 3, 3, 3, 3, 2, 1, 3, 3, 2, 1, 1, 4, 4, 3, 1, 2)\ny <- c(3, 4, 1, 1, 1, 1, 4, 3, 1, 1, 4, 3, 3, 2, 2, 1, 3, 4)\n\n# Funzione per calcolare l'entropia\ncalculate_entropy <- function(vec) {\n  p <- as.numeric(table(vec)) / length(vec)\n  -sum(p * log2(p))\n}\n\ncat(sprintf(\"Entropia di x: %.4f bit\\n\", calculate_entropy(x)))\n#> Entropia di x: 1.8776 bit\ncat(sprintf(\"Entropia di y: %.4f bit\\n\", calculate_entropy(y)))\n#> Entropia di y: 1.8776 bit\n```\n:::\n\n\nEntrambi i vettori hanno entropia di 1.8776 bit, pur avendo distribuzioni specifiche diverse.\n:::\n\n### Entropia di variabili continue\n\nIl concetto si estende alle variabili continue attraverso l'*entropia differenziale*:\n\n$$\nH(X) = -\\int_{\\mathcal{X}} p(x) \\log_2 p(x) \\, dx,\n$$ {#eq-entropy-differential-def}\n\ndove l'integrale sostituisce la sommatoria e $p(x)$ è la funzione di densità.\n\nL'interpretazione è analoga: una densità concentrata (picco stretto) implica bassa entropia; una densità dispersa implica alta entropia. A differenza del caso discreto, l'entropia differenziale può assumere valori negativi quando la densità è estremamente concentrata.\n\n::: {#exercise-entropy-normal .callout .exercise collapse=\"true\" collapsed=\"true\"}\n#### Esercizio — Entropia della distribuzione normale.\n\nPer $X \\sim \\mathcal{N}(\\mu,\\sigma^2)$, l'entropia differenziale ha forma chiusa:\n\n$$\nH(X)=\\tfrac12 \\log_2\\!\\big(2\\pi e\\,\\sigma^2\\big)\\ \\text{bit}.\n$$\n\nLa dipendenza è interamente in $\\sigma$: raddoppiare $\\sigma$ aggiunge esattamente 1 bit.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nh_norm_bits <- function(sigma) 0.5 * log2(2 * pi * exp(1) * sigma^2)\n\nsigmas <- c(0.5, 1, 2)\nentropie <- sapply(sigmas, h_norm_bits)\nround(entropie, 3)  # 1.047, 2.047, 3.047\n#> [1] 1.05 2.05 3.05\n\n# Visualizzazione\ndf <- data.frame(\n  x = rep(seq(-6, 6, length.out = 1000), times = length(sigmas)),\n  sigma = factor(rep(sigmas, each = 1000))\n)\ndf$dens <- mapply(function(x, s) dnorm(x, mean = 0, sd = s), df$x, as.numeric(as.character(df$sigma)))\n\nggplot(df, aes(x = x, y = dens, group = sigma)) +\n  geom_line(aes(linetype = sigma), linewidth = 1) +\n  labs(\n    subtitle = paste0(\"H(σ=0.5)≈\", round(entropie[1],3), \" bit; \",\n                      \"H(σ=1)≈\",   round(entropie[2],3), \" bit; \",\n                      \"H(σ=2)≈\",   round(entropie[3],3), \" bit\"),\n    x = \"x\", y = \"densità\"\n  ) \n```\n\n::: {.cell-output-display}\n![](01_entropy_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nIn psicologia, questo significa che la stessa variabile misurata con maggiore dispersione (punteggi più eterogenei) porta a un'entropia più alta.\n:::\n\n## La codifica di Huffman\n\nAbbiamo visto che l'entropia $H(X)$ misura la sorpresa media di una variabile casuale $X$. Un risultato fondamentale della teoria dell'informazione stabilisce che l'entropia rappresenta il **limite inferiore teorico** per la lunghezza media di un codice binario in grado di rappresentare senza perdite gli esiti di $X$. Formalmente, è impossibile progettare un sistema di codifica che utilizzi in media meno di $H(X)$ bit per simbolo.\n\nL'algoritmo di *Huffman*, sviluppato da David A. Huffman nel 1952 durante i suoi studi universitari, fornisce un metodo costruttivo ed efficiente per generare codici prefissi che si avvicinano asintoticamente a questo limite teorico.\n\n### Il principio di ottimizzazione\n\nL'intuizione fondamentale dell'algoritmo è tanto semplice quanto potente: *assegnare codici brevi agli eventi ad alta probabilità e codici più lunghi agli eventi rari*. Questa strategia di ottimizzazione rispecchia comportamenti comunicativi quotidiani in cui tendiamo ad abbreviare espressioni frequenti (\"tvb\", \"xké\") mentre utilizziamo forme estese per concetti meno comuni.\n\n### L'algoritmo di Huffman: una spiegazione passo-passo\n\nImmagina di voler comprimere un messaggio assegnando a ogni lettera un codice binario. L'obiettivo è usare pochi bit per le lettere frequenti e più bit per quelle rare. L'algoritmo di Huffman risolve questo problema costruendo un **albero binario** in modo sistematico.\n\n#### Fase 1: preparazione iniziale\n- **Crea foglie per ogni simbolo**: per ogni lettera dell'alfabeto, crea un \"nodo foglia\" che contiene la lettera e la sua frequenza (o probabilità) nel messaggio.\n- **Organizza in coda prioritaria**: metti tutti questi nodi in una lista ordinata dalla frequenza più bassa alla più alta.\n\n#### Fase 2: costruzione dell'albero (il cuore dell'algoritmo)\n\n**Ripeti finché non resta un solo nodo**:\n\n1. **Prendi i due nodi meno frequenti**: estrai dalla coda i due nodi con le frequenze più basse.\n   \n2. **Crea un nuovo nodo padre**: \n   - unisci questi due nodi in un nuovo nodo interno\n   - la frequenza del nuovo nodo è la **somma** delle frequenze dei due figli\n   - collega i due nodi originali come figli di questo nuovo nodo\n\n3. **Reinserisci in coda**: metti il nuovo nodo nella coda mantenendo l'ordinamento per frequenza.\n\n**Esempio visivo**:\n```\nFrequenze: A:5, B:3, C:2, D:1\n\nPasso 1: Prendi D(1) e C(2) → Crea nodo DC(3)\n         DC(3)\n        /    \\\n      D(1)   C(2)\n\nPasso 2: Prendi B(3) e DC(3) → Crea nodo BDC(6)\n         BDC(6)\n        /     \\\n      B(3)   DC(3)\n             /   \\\n           D(1)  C(2)\n\nPasso 3: Prendi A(5) e BDC(6) → Crea radice ABCD(11)\n```\n\n#### Fase 3: assegnazione dei codici\n\nOra che l'albero è completo, assegna i codici binari:\n\n- **parti dalla radice** e scendi verso ogni foglia;\n- **assegna 0** a ogni ramo sinistro;\n- **assegna 1** a ogni ramo destro;\n- **il codice di ogni lettera** è la sequenza di 0 e 1 incontrata dal percorso radice-foglia.\n\n I codici finali nell'esempio sono:\n\n- A: 0 (percorso radice → sinistro), 1 bit;\n- B: 10 (radice → destro → sinistro), 2 bit;\n- C: 111 (radice → destro → destro → destro), 3 bit;\n- D: 110 (radice → destro → destro → sinistro), 3 bit.\n\nQuindi se dovessi codificare la parola \"BAD\", la rappresentazione binaria sarebbe:\n\n- B → `10`;\n- A → `0`;\n- D → `110`.\n\nRisultato: `100110`.\n\n**Perché questi codici funzionano senza ambiguità?**\n\nPerché è un **codice prefisso**: nessun codice è l'inizio di un altro codice:\n\n- `0` (A) non è l'inizio di `10` (B), `110` (D) o `111` (C);\n- `10` (B) non è l'inizio di `110` (D) o `111` (C);\n- `110` (D) non è l'inizio di `111` (C).\n\nQuando decodifichi `100110`:\n\n1. leggi `1` → non corrisponde a nessun codice completo, continua...\n2. leggi `10` → trovato B! Ricominci da capo.\n3. leggi `0` → trovato A! Ricominci da capo.\n4. leggi `1` → continua...\n5. leggi `11` → continua...\n6. leggi `110` → trovato D!\n\nL'algoritmo garantisce che i simboli più frequenti ottengano i codici più corti, minimizzando la lunghezza media del messaggio codificato.\n\n### Esempio applicativo\n\nConsideriamo un sistema di comunicazione con quattro simboli e le seguenti distribuzioni di frequenza:\n\n| Simbolo | Frequenza | Probabilità |\n|---------|-----------|-------------|\n| A       | 20        | 0.465       |\n| B       | 10        | 0.233       |\n| C       | 8         | 0.186       |\n| D       | 5         | 0.116       |\n\n**Costruzione dell'albero di Huffman:**\n\n1. Unione iniziale: D(0.116) + C(0.186) → N1(0.302).\n2. Unione successiva: B(0.233) + N1(0.302) → N2(0.535).\n3. Unione finale: A(0.465) + N2(0.535) → Radice(1.000).\n\n**Rappresentazione ad albero:**\n```\n         (Radice)\n        0/      \\1\n      (A:0.465) (N2:0.535)\n              0/        \\1\n         (B:0.233)    (N1:0.302)\n                    0/        \\1\n                (D:0.116)  (C:0.186)\n```\n\n**Codici risultanti:**\n\n- A: `0` (1 bit);\n- B: `10` (2 bit);\n- D: `110` (3 bit);\n- C: `111` (3 bit).\n\nSi osserva come la lunghezza di ciascun codice sia inversamente proporzionale alla probabilità del simbolo corrispondente.\n\n### Analisi di efficienza\n\nValutiamo le performance della codifica rispetto al limite teorico:\n\n* **Lunghezza media del codice:**\n  $$\n  L = (0.465\\cdot 1) + (0.233\\cdot 2) + (0.186\\cdot 3) + (0.116\\cdot 3) = 1.907 \\ \\text{bit/simbolo}.\n  $$\n\n* **Entropia della distribuzione:**\n  $$\n  H(X) = -\\sum p(x)\\log_2 p(x) \\approx 1.842 \\ \\text{bit/simbolo}.\n  $$\n\nL'efficienza della codifica risulta:\n$$\n\\eta = \\frac{H(X)}{L} \\approx 96.6\\%.\n$$\n\nIl codice di Huffman (1.907 bit/simbolo) si avvicina notevolmente al limite teorico dell'entropia (1.842 bit/simbolo). La discrepanza residua è attribuibile al vincolo di lunghezza intera dei codici, mentre l'entropia rappresenta un limite continuo teoricamente raggiungibile solo asintoticamente.\n\n::: {#exercise-entropy-huffman .callout .exercise collapse=\"true\" collapsed=\"true\"}\n#### Esercizio — Verifica della codifica di Huffman.\n\nPer $p(A) = 0.4$, $p(B) = 0.3$, $p(C) = 0.2$, $p(D) = 0.1$:\n\nCodifica Huffman: A = `0`, B = `10`, C = `110`, D = `111`\n\nLunghezza media:\n$$\nL = 0.4 \\times 1 + 0.3 \\times 2 + 0.2 \\times 3 + 0.1 \\times 3 = 1.9 \\text{ bit}\n$$\n\nEntropia:\n$$\nH(X) = -[0.4 \\log_2 0.4 + 0.3 \\log_2 0.3 + 0.2 \\log_2 0.2 + 0.1 \\log_2 0.1] = 1.8465 \\text{ bit}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprobabilities <- list(A = 0.4, B = 0.3, C = 0.2, D = 0.1)\n\nhuffman_encoding <- function(probabilities) {\n  nodes <- lapply(names(probabilities), function(sym) {\n    list(symbol = sym, prob = probabilities[[sym]], left = NULL, right = NULL)\n  })\n\n  while (length(nodes) > 1) {\n    nodes <- nodes[order(sapply(nodes, function(n) n$prob))]\n    left <- nodes[[1]]\n    right <- nodes[[2]]\n    merged <- list(symbol = NULL, prob = left$prob + right$prob, left = left, right = right)\n    nodes <- c(nodes[-c(1, 2)], list(merged))\n  }\n\n  assign_codes <- function(node, prefix = \"\", code_map = list()) {\n    if (!is.null(node$symbol)) {\n      code_map[[node$symbol]] <- prefix\n    } else {\n      code_map <- assign_codes(node$left, paste0(prefix, \"0\"), code_map)\n      code_map <- assign_codes(node$right, paste0(prefix, \"1\"), code_map)\n    }\n    return(code_map)\n  }\n\n  code_map <- assign_codes(nodes[[1]])\n  avg_length <- sum(sapply(names(probabilities), function(sym) {\n    probabilities[[sym]] * nchar(code_map[[sym]])\n  }))\n\n  return(list(avg_length = avg_length, huffman_dict = code_map))\n}\n\nresult <- huffman_encoding(probabilities)\ncat(sprintf(\"Lunghezza media: %.2f bit/simbolo\\n\", result$avg_length))\n#> Lunghezza media: 1.90 bit/simbolo\n```\n:::\n\n\nL'entropia (1.8465 bit) è il limite teorico; Huffman (1.9 bit) vi si avvicina molto.\n:::\n\n::: {.callout-tip title=\"Sintesi: entropia e codifica\"}\n* L'entropia $H(X)$ rappresenta la lunghezza media teorica minima per codificare una variabile casuale.\n* La codifica di Huffman costruisce un codice binario che si avvicina a questo limite, usando più bit per i simboli rari e meno per quelli frequenti.\n* L'entropia fornisce un criterio per valutare l'efficienza di una codifica: più la lunghezza media si avvicina all'entropia, più è efficiente.\n:::\n\n## Applicazioni psicologiche dell'entropia\n\nIl concetto di entropia, inteso come sorpresa media, trova applicazione diretta in psicologia. La sorpresa — formalizzata attraverso l'informazione di Shannon — è collegata a correlati emotivi, meccanismi di apprendimento e processi motivazionali.\n\n@spector1956expectations indagò l'effetto della probabilità a priori sulla soddisfazione percepita in seguito a promozione lavorativa. Esiti inizialmente improbabili generavano un impatto emotivo più intenso rispetto a esiti attesi. L'entropia non è quindi una mera astrazione matematica, ma un indicatore predittivo dell'intensità della risposta affettiva.\n\nRicerche di neuroscienze cognitive hanno evidenziato come eventi ad alta sorpresa modulino l'attività di regioni cerebrali implicate nell'elaborazione emotiva (amigdala, corteccia prefrontale ventromediale). Studi con *Ecological Momentary Assessment* mostrano che la probabilità soggettiva di un evento si correla sistematicamente con le fluttuazioni dell'umore: episodi rari e inattesi inducono oscillazioni emotive di maggiore ampiezza.\n\nL'entropia può quindi essere impiegata non solo come strumento descrittivo, ma anche come variabile esplicativa in modelli che esplorano l'intreccio tra aspettative, sorpresa ed esperienza emotiva.\n\n::: {#exercise-entropy-mood .callout .exercise collapse=\"true\" collapsed=\"true\"}\n#### Esercizio — Sorpresa e umore.\n\nSimuliamo 200 osservazioni dove la sorpresa influenza la variazione di umore:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\n\nn <- 200\np_event <- runif(n, min = 0.05, max = 0.95)\nsurprise <- -log2(p_event)\ndelta_mood <- 0.5 * surprise + rnorm(n, mean = 0, sd = 0.5)\n\ndf <- data.frame(p_event, surprise, delta_mood)\n\nggplot(df, aes(x = surprise, y = delta_mood)) +\n  geom_point(alpha = 0.6) +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"blue\") +\n  labs(x = \"Sorpresa (bit)\", y = \"Δ Umore\") \n```\n\n::: {.cell-output-display}\n![](01_entropy_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nEventi più sorprendenti producono variazioni di umore maggiori.\n:::\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIn questo capitolo abbiamo esplorato la capacità dell'*entropia* di quantificare sistematicamente l'incertezza e l'informazione nei sistemi complessi. Attraverso esempi che vanno dal semplice lancio di una moneta alla sofisticata codifica efficiente dei messaggi, abbiamo verificato come questo potente strumento matematico trovi applicazione concreta in contesti sia teorici che pratici.\n\nAbbiamo imparato che l'entropia misura l'incertezza: le situazioni più imprevedibili, come il risultato del lancio di una moneta equilibrata, presentano un'elevata entropia, mentre i comportamenti stereotipati e deterministici hanno un'entropia prossima a zero. Abbiamo anche scoperto che l'informazione è concettualmente equivalente alla sorpresa: gli eventi rari e inaspettati, formalizzati attraverso l'informazione di Shannon, veicolano un contenuto informativo maggiore rispetto agli eventi comuni e attesi. Infine, abbiamo compreso che l'entropia stabilisce un limite teorico alla compressione dei dati, rappresentando il numero minimo di bit necessari per descrivere un'informazione senza perdite; un principio che l'algoritmo di Huffman realizza con eleganza ed efficacia computazionale.\n\n### La rilevanza per la ricerca psicologica {.unnumbered .unlisted}\n\nQuesti concetti trovano un'eco immediata nella ricerca psicologica contemporanea. Nell'ambito della modellizzazione cognitiva, l'entropia fornisce una metrica quantitativa del \"lavoro\" informazionale necessario per elaborare stimoli diversi, offrendo una misura rigorosa della complessità dei processi mentali. D'altro canto, lo studio delle emozioni beneficia del legame tra probabilità e risposta affettiva: gli eventi ad alta sorpresa, e quindi ad alta entropia, tendono a innescare reazioni emotive più intense, gettando un ponte teorico tra la teoria dell'informazione e le neuroscienze affettive. In prospettiva evolutiva, questi fondamenti ci condurranno direttamente alla valutazione dei modelli psicologici, dove l'entropia costituirà la base per strumenti sofisticati di confronto e selezione basati sulla capacità predittiva.\n\n### Verso strumenti più avanzati {.unnumbered .unlisted}\n\nL'entropia non rappresenta un punto di arrivo, bensì un punto di partenza verso strumenti inferenziali più raffinati. Nel prossimo capitolo incontreremo la *divergenza di Kullback-Leibler*, che misura direttamente quanto un modello si discosti dalla realtà utilizzando proprio i concetti di entropia che abbiamo introdotto in questo capitlo. Questo, a sua volta, ci preparerà all'incontro con l'*ELPD* (*Expected Log Predictive Density*), una metrica fondamentale per confrontare modelli bayesiani nella pratica della ricerca applicata.\n\nComprendere l'entropia significa quindi acquisire uno strumento interpretativo potente: ci permette di tradurre osservazioni qualitative sulla variabilità del comportamento in misure quantitative, trasformando l'intuizione in un'analisi rigorosa. Questo salto epistemologico, da \"questo comportamento è variabile\" a \"l'entropia di questo comportamento è X bit\", rende la teoria dell'informazione un alleato indispensabile per la psicologia contemporanea nella sua transizione verso paradigmi più quantitativi e predittivi.\n\n::: {.callout-note collapse=\"true\" title=\"Mappa concettuale: dall'entropia alla valutazione dei modelli\"}\n\n**Entropia $H(X)$**  \n→ Misura l'incertezza intrinseca di una variabile casuale.  \n→ Interpretabile come sorpresa media o lunghezza media minima di codifica.  \n\n**Divergenza di Kullback–Leibler $D_{KL}(P \\parallel Q)$**  \n→ Confronta distribuzione vera $P$ e modello $Q$.  \n→ Misura l'inefficienza nel codificare dati di $P$ usando $Q$.  \n\n**Expected Log Predictive Density (ELPD)**  \n→ Valuta la capacità predittiva su dati nuovi.  \n→ Collegata alla minimizzazione della KL.  \n\n**Collegamento:**  \nEntropia → incertezza nei dati.  \nKL → spreco informativo del modello.  \nELPD → quanto bene il modello prevede, riducendo quello spreco.\n\n:::\n\n::: {#fig-h-kl-elpd}\n![](../../figures/entropy_kl_elpd.png){width=\"80%\"}\n\nDiagramma visivo che collega Entropia → Divergenza KL → ELPD.\n:::\n\n::: {.callout-note collapse=true}\n## Informazioni sull'ambiente di sviluppo {.unnumbered .unlisted} \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.5.2 (2025-10-31)\n#> Platform: aarch64-apple-darwin20\n#> Running under: macOS Tahoe 26.1\n#> \n#> Matrix products: default\n#> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] tidygraph_1.3.1       ggraph_2.2.2          igraph_2.2.1         \n#>  [4] ragg_1.5.0            tinytable_0.15.1      withr_3.0.2          \n#>  [7] systemfonts_1.3.1     patchwork_1.3.2       ggdist_3.3.3         \n#> [10] tidybayes_3.0.7       bayesplot_1.14.0      ggplot2_4.0.1        \n#> [13] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.6.1      \n#> [16] loo_2.8.0             rstan_2.32.7          StanHeaders_2.32.10  \n#> [19] brms_2.23.0           Rcpp_1.1.0            sessioninfo_1.2.3    \n#> [22] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [25] modelr_0.1.11         tibble_3.3.0          dplyr_1.1.4          \n#> [28] tidyr_1.3.1           rio_1.2.4             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] gridExtra_2.3         inline_0.3.21         sandwich_3.1-1       \n#>  [4] rlang_1.1.6           magrittr_2.0.4        multcomp_1.4-29      \n#>  [7] snakecase_0.11.1      compiler_4.5.2        mgcv_1.9-4           \n#> [10] vctrs_0.6.5           stringr_1.6.0         pkgconfig_2.0.3      \n#> [13] arrayhelpers_1.1-0    fastmap_1.2.0         backports_1.5.0      \n#> [16] labeling_0.4.3        rmarkdown_2.30        purrr_1.2.0          \n#> [19] xfun_0.54             cachem_1.1.0          jsonlite_2.0.0       \n#> [22] tweenr_2.0.3          broom_1.0.10          parallel_4.5.2       \n#> [25] R6_2.6.1              stringi_1.8.7         RColorBrewer_1.1-3   \n#> [28] lubridate_1.9.4       estimability_1.5.1    knitr_1.50           \n#> [31] zoo_1.8-14            Matrix_1.7-4          splines_4.5.2        \n#> [34] timechange_0.3.0      tidyselect_1.2.1      viridis_0.6.5        \n#> [37] abind_1.4-8           yaml_2.3.10           codetools_0.2-20     \n#> [40] curl_7.0.0            pkgbuild_1.4.8        lattice_0.22-7       \n#> [43] bridgesampling_1.2-1  S7_0.2.1              coda_0.19-4.1        \n#> [46] evaluate_1.0.5        survival_3.8-3        polyclip_1.10-7      \n#> [49] RcppParallel_5.1.11-1 pillar_1.11.1         tensorA_0.36.2.1     \n#> [52] checkmate_2.3.3       stats4_4.5.2          distributional_0.5.0 \n#> [55] generics_0.1.4        rprojroot_2.1.1       rstantools_2.5.0     \n#> [58] scales_1.4.0          xtable_1.8-4          glue_1.8.0           \n#> [61] emmeans_2.0.0         tools_4.5.2           graphlayouts_1.2.2   \n#> [64] mvtnorm_1.3-3         grid_4.5.2            QuickJSR_1.8.1       \n#> [67] colorspace_2.1-2      nlme_3.1-168          ggforce_0.5.0        \n#> [70] cli_3.6.5             textshaping_1.0.4     svUnit_1.0.8         \n#> [73] viridisLite_0.4.2     Brobdingnag_1.2-9     V8_8.0.1             \n#> [76] gtable_0.3.6          digest_0.6.39         ggrepel_0.9.6        \n#> [79] TH.data_1.1-5         htmlwidgets_1.6.4     farver_2.1.2         \n#> [82] memoise_2.0.1         htmltools_0.5.8.1     lifecycle_1.0.4      \n#> [85] MASS_7.3-65\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "01_entropy_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}