{
  "hash": "f1243850c850715578d4ce76577f08e5",
  "result": {
    "engine": "knitr",
    "markdown": "# Comprendere e comunicare la distribuzione a posteriori {#sec-bayesian-inference-summary-posterior}\n\n::: {.callout-note appearance=\"minimal\"}\n\nNei capitoli precedenti abbiamo imparato a costruire distribuzioni a posteriori combinando prior e verosimiglianza. Ora la domanda si sposta su un piano diverso: **che cosa ci dice, in pratica, la distribuzione così ottenuta?**\n\nLa posterior non è una curva da riassumere con pochi indici: è la rappresentazione quantitativa dell'incertezza che resta sul parametro, condizionata al modello, al prior e ai dati. Dice quali regioni dello spazio parametrico sono più plausibili, e permette di rispondere a domande precise: quanta incertezza rimane dopo l'osservazione, quanto è probabile che il parametro superi una soglia scientificamente rilevante, quanto che cada in una regione considerata trascurabile.\n\nMedia, mediana, moda, intervalli di credibilità e probabilità a posteriori sono altrettanti **modi concisi di comunicarla**: ciascuno conserva un aspetto dell'informazione e ne perde altri. Per questo la sintesi non si sceglie con una procedura automatica, ma a partire dalla domanda a cui si vuole rispondere.\n:::\n\n::: {.callout-important appearance=\"minimal\" .chapter-status}\n**Da sapere.** Il prior descrive l'incertezza sul parametro prima dei dati; la posterior descrive l'incertezza dopo l'aggiornamento. La distribuzione a posteriori è l'oggetto inferenziale completo. Una stima puntuale ne riassume la posizione, un intervallo ne riassume una regione di massa e una probabilità a posteriori risponde a una specifica affermazione sul parametro.\n\n**Da saper fare.** Interpretare la densità a posteriori; distinguere media, mediana e moda; calcolare deviazione standard e intervalli di credibilità; confrontare intervalli a code uguali e di massima densità; calcolare probabilità relative a soglie o regioni sostantive; formulare un resoconto breve senza trasformare una sintesi nella distribuzione completa.\n\n**Approfondimento facoltativo.** Le proprietà decisionali delle stime puntuali, la dipendenza del MAP dalla parametrizzazione e la sintesi di distribuzioni posteriori multivariate possono essere rimandate in una prima lettura.\n\n[Che cosa significano queste etichette?](../../guida-al-manuale.qmd#sec-percorsi-lettura)\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Prerequisiti\"}\n\n- Sono dati per noti l’aggiornamento bayesiano del @sec-grid-approx e il modello Beta-Binomiale del @sec-conjugate-families.\n- È utile distinguere la densità di probabilità dalla probabilità associata a un intervallo.\n- Per un richiamo sulla notazione degli intervalli si può consultare l'@sec-apx-numbers; la lettura del codice R è facoltativa.\n\n:::\n\n::: {.callout-caution collapse=\"true\" title=\"Preparazione del notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |>\n  source()\n```\n:::\n\n:::\n\n## Che cosa rappresenta una distribuzione a posteriori\n\nPer un parametro continuo $\\theta$, la distribuzione a posteriori è indicata con\n\n$$\np(\\theta\\mid y),\n$$\n\ndove $y$ rappresenta i dati osservati. Questa distribuzione combina ciò che il modello specificava prima dei dati con l'informazione fornita dalla verosimiglianza:\n\n$$\np(\\theta\\mid y)\n\\propto\np(y\\mid\\theta)p(\\theta).\n$$\n\nLa posterior assegna maggiore densità alle regioni di $\\theta$ sostenute congiuntamente dal prior e dai dati. La sua lettura sostantiva può essere organizzata attraverso tre domande:\n\n1. **Dove si concentra la plausibilità?**  \n   È la domanda a cui rispondono media, mediana e moda.\n\n2. **Quanto è estesa l'incertezza?**  \n   È la domanda a cui rispondono deviazione standard e intervalli di credibilità.\n\n3. **Quanto è plausibile un'affermazione specifica?**  \n   È la domanda a cui rispondono quantità come $P(\\theta>0.50\\mid y)$ o $P(0.50<\\theta<0.70\\mid y)$.\n\n::: {.callout-important title=\"Densità non significa probabilità puntuale\"}\nPer un parametro continuo, la probabilità che $\\theta$ sia esattamente uguale a un singolo valore è zero. L'altezza della curva indica una **densità relativa**, non la probabilità puntuale di quel valore. Le probabilità si ottengono considerando aree sotto la curva, cioè intervalli o regioni del parametro.\n:::\n\n## Un esempio guida: prevalenza di sintomi depressivi gravi\n\nConsideriamo i punteggi BDI-II di 30 partecipanti clinici, costruiti per l'esempio a partire dal contesto descritto da @zetsche_2019future. Definiamo come esito di interesse un punteggio almeno pari a 30.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbdi <- c(\n  26, 35, 30, 25, 44, 30, 33, 43, 22, 43,\n  24, 19, 39, 31, 25, 28, 35, 30, 26, 31,\n  41, 36, 26, 35, 33, 28, 27, 34, 27, 22\n)\n\nn <- length(bdi)\ny <- sum(bdi >= 30)\n\nc(successi = y, prove = n, proporzione = y / n)\n#>    successi       prove proporzione \n#>      17.000      30.000       0.567\n```\n:::\n\n\nSia $\\theta$ la probabilità che un partecipante della popolazione clinica di riferimento presenti un punteggio almeno pari a 30. Usiamo, esclusivamente per illustrare il calcolo, il prior\n\n$$\n\\theta\\sim\\operatorname{Beta}(8,2).\n$$\n\nQuesto prior ha media 0.80 e concentrazione 10: prima dei dati concentra quindi la plausibilità su valori relativamente elevati. Con $y=17$ successi e $n-y=13$ insuccessi, la posterior è\n\n$$\n\\theta\\mid y\n\\sim\n\\operatorname{Beta}(8+17,\\,2+13)\n=\n\\operatorname{Beta}(25,15).\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalpha_prior <- 8\nbeta_prior <- 2\nalpha_post <- alpha_prior + y\nbeta_post <- beta_prior + n - y\n\nposterior_parameters <- tibble(\n  distribuzione = c(\"Prior\", \"Posterior\"),\n  alpha = c(alpha_prior, alpha_post),\n  beta = c(beta_prior, beta_post),\n  media = c(\n    alpha_prior / (alpha_prior + beta_prior),\n    alpha_post / (alpha_post + beta_post)\n  ),\n  concentrazione = c(\n    alpha_prior + beta_prior,\n    alpha_post + beta_post\n  )\n)\n\nposterior_parameters\n#> # A tibble: 2 x 5\n#>   distribuzione alpha  beta media concentrazione\n#>   <chr>         <dbl> <dbl> <dbl>          <dbl>\n#> 1 Prior             8     2 0.8               10\n#> 2 Posterior        25    15 0.625             40\n```\n:::\n\n\nLa proporzione osservata è 0.567, mentre la media posterior è 0.625. La posterior si colloca tra l'informazione iniziale e i dati perché conserva entrambe le fonti. Non dice che una delle due sia “vera”: descrive il risultato dell'aggiornamento all'interno del modello specificato.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_grid <- seq(0, 1, length.out = 1001)\n\nposterior_curve <- tibble(\n  theta = theta_grid,\n  densita = dbeta(theta_grid, alpha_post, beta_post)\n)\n\nggplot(posterior_curve, aes(x = theta, y = densita)) +\n  geom_area(fill = modern_palette$grey6, alpha = 0.6) +\n  geom_line(colour = PRIMARY, linewidth = 1.1) +\n  labs(\n    title = \"Distribuzione a posteriori di theta\",\n    subtitle = \"Beta(25, 15): plausibilità aggiornata dopo prior e dati\",\n    x = expression(theta),\n    y = \"Densità a posteriori\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzione a posteriori del parametro θ nell'esempio sulla prevalenza di sintomi depressivi gravi. La densità Beta(25, 15) sintetizza la plausibilità aggiornata dopo aver combinato il prior con i dati osservati.](03_summary_posterior_files/figure-pdf/fig-summary-posterior-density-1.png){#fig-summary-posterior-density fig-align='center' fig-pos='H' fig-alt='Curva unimodale della densità a posteriori di theta, concentrata approssimativamente tra 0,45 e 0,80 e con il massimo vicino a 0.63.' width=85%}\n:::\n:::\n\n\n## Riassumere la posizione della posterior\n\nUna stima puntuale comprime la distribuzione in un solo numero. Non esiste però un unico centro universalmente migliore: media, mediana e moda rispondono a criteri differenti.\n\n### Media a posteriori\n\nLa media è il valore atteso della posterior:\n\n$$\nE(\\theta\\mid y)\n=\n\\int \\theta\\,p(\\theta\\mid y)\\,d\\theta.\n$$\n\nPer una distribuzione Beta:\n\n$$\nE(\\theta\\mid y)\n=\n\\frac{\\alpha_{\\text{post}}}\n{\\alpha_{\\text{post}}+\\beta_{\\text{post}}}.\n$$\n\nLa media utilizza tutta la distribuzione ed è la stima ottimale quando la perdita associata all'errore è quadratica. Può essere influenzata da code lunghe o asimmetriche.\n\n### Mediana a posteriori\n\nLa mediana divide la massa posterior in due parti uguali:\n\n$$\nP(\\theta\\leq\\theta_{0.50}\\mid y)=0.50.\n$$\n\nÈ la stima ottimale quando la perdita cresce in proporzione all'errore assoluto. In una distribuzione asimmetrica, la mediana comunica con immediatezza il punto sotto il quale si trova metà della plausibilità posterior.\n\n### Moda a posteriori\n\nLa moda, o stima MAP, è il valore di massima densità:\n\n$$\n\\hat\\theta_{\\mathrm{MAP}}\n=\n\\arg\\max_\\theta p(\\theta\\mid y).\n$$\n\nPer una Beta con $\\alpha>1$ e $\\beta>1$:\n\n$$\n\\hat\\theta_{\\mathrm{MAP}}\n=\n\\frac{\\alpha-1}{\\alpha+\\beta-2}.\n$$\n\nLa moda individua il picco della densità, ma non considera quanta massa si trovi intorno a quel picco. Può inoltre cambiare sotto una trasformazione del parametro, perciò non dovrebbe essere trattata automaticamente come “il valore più probabile” in senso assoluto.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nposterior_mean <- alpha_post / (alpha_post + beta_post)\nposterior_median <- qbeta(0.50, alpha_post, beta_post)\nposterior_mode <- (alpha_post - 1) / (alpha_post + beta_post - 2)\n\npoint_summaries <- tibble(\n  sintesi = c(\"Media\", \"Mediana\", \"Moda (MAP)\"),\n  valore = c(posterior_mean, posterior_median, posterior_mode)\n)\n\npoint_summaries\n#> # A tibble: 3 x 2\n#>   sintesi    valore\n#>   <chr>       <dbl>\n#> 1 Media       0.625\n#> 2 Mediana     0.627\n#> 3 Moda (MAP)  0.632\n```\n:::\n\n\nNel nostro esempio le tre sintesi sono vicine perché la posterior è unimodale e solo moderatamente asimmetrica. Il fatto che siano simili non significa che siano intercambiabili in generale.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(posterior_curve, aes(x = theta, y = densita)) +\n  geom_line(colour = modern_palette$grey3, linewidth = 1) +\n  geom_vline(\n    data = point_summaries,\n    aes(xintercept = valore, linetype = sintesi),\n    colour = PRIMARY,\n    linewidth = 0.9\n  ) +\n  labs(\n    title = \"Tre sintesi della stessa distribuzione\",\n    subtitle = \"Le differenze dipendono dalla forma della posterior\",\n    x = expression(theta),\n    y = \"Densità a posteriori\",\n    linetype = NULL\n  ) +\n  legenda_in_alto\n```\n\n::: {.cell-output-display}\n![Media, mediana e moda della stessa distribuzione a posteriori. Le tre linee verticali sono vicine perché la posterior è unimodale e solo moderatamente asimmetrica, ma rappresentano criteri di sintesi differenti.](03_summary_posterior_files/figure-pdf/fig-summary-posterior-point-summaries-1.png){#fig-summary-posterior-point-summaries fig-align='center' fig-pos='H' fig-alt='Curva della densità a posteriori con tre linee verticali quasi sovrapposte che indicano media, mediana e moda.' width=85%}\n:::\n:::\n\n\n::: {.callout-tip title=\"Una regola di comunicazione\"}\nUna stima puntuale dovrebbe essere accompagnata almeno da una misura dell'incertezza. Dire soltanto “la stima è 0.625” nasconde quasi tutta l'informazione contenuta nella posterior.\n:::\n\n## Riassumere l'incertezza\n\n### Deviazione standard a posteriori\n\nLa varianza posterior è\n\n$$\n\\operatorname{Var}(\\theta\\mid y)\n=\nE\\left[(\\theta-E(\\theta\\mid y))^2\\mid y\\right].\n$$\n\nLa sua radice quadrata, la deviazione standard a posteriori, esprime la dispersione nella stessa unità del parametro. Non misura la “qualità” della stima: dice quanto la plausibilità resta distribuita intorno alla media.\n\nPer una distribuzione Beta:\n\n$$\n\\operatorname{Var}(\\theta\\mid y)\n=\n\\frac{\\alpha\\beta}\n{(\\alpha+\\beta)^2(\\alpha+\\beta+1)}.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nposterior_variance <-\n  alpha_post * beta_post /\n  ((alpha_post + beta_post)^2 *\n     (alpha_post + beta_post + 1))\n\nposterior_sd <- sqrt(posterior_variance)\n\nc(varianza = posterior_variance, deviazione_standard = posterior_sd)\n#>            varianza deviazione_standard \n#>             0.00572             0.07561\n```\n:::\n\n\n### Intervallo a code uguali\n\nUn intervallo a code uguali del $100(1-\\alpha)\\%$ è definito dai quantili\n\n$$\n\\left[\nq_{\\alpha/2},\nq_{1-\\alpha/2}\n\\right].\n$$\n\nPer un intervallo al 94%, il 3% della massa rimane in ciascuna coda. L'espressione “a code uguali” è preferibile a “simmetrico”: in una distribuzione asimmetrica, infatti, l'intervallo non è necessariamente simmetrico intorno alla media o alla mediana.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_interval <- 0.94\nalpha_interval <- 1 - prob_interval\n\neti_94 <- qbeta(\n  c(alpha_interval / 2, 1 - alpha_interval / 2),\n  alpha_post,\n  beta_post\n)\n\neti_94\n#> [1] 0.478 0.761\n```\n:::\n\n\nCondizionatamente al modello, al prior e ai dati, la probabilità posterior che $\\theta$ cada tra 0.478 e 0.761 è 0.94.\n\n### Intervallo di massima densità\n\nUn intervallo di massima densità raccoglie la massa richiesta includendo i punti a densità più alta: ogni valore incluso ha densità almeno pari a quella dei valori esclusi. Per una posterior unimodale e continua è, di norma, l'intervallo contiguo più corto a parità di massa.\n\nLa funzione seguente calcola l'intervallo più corto per una distribuzione Beta.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhdi_beta <- function(prob, shape1, shape2) {\n  stopifnot(prob > 0, prob < 1, shape1 > 0, shape2 > 0)\n\n  width <- function(lower_prob) {\n    qbeta(lower_prob + prob, shape1, shape2) -\n      qbeta(lower_prob, shape1, shape2)\n  }\n\n  solution <- optimize(\n    width,\n    interval = c(0, 1 - prob)\n  )\n\n  c(\n    inferiore = qbeta(solution$minimum, shape1, shape2),\n    superiore = qbeta(solution$minimum + prob, shape1, shape2)\n  )\n}\n\nhdi_94 <- hdi_beta(prob_interval, alpha_post, beta_post)\nhdi_94\n#> inferiore superiore \n#>     0.483     0.765\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ninterval_comparison <- tibble(\n  tipo = c(\"Code uguali\", \"Massima densità\"),\n  inferiore = c(eti_94[1], hdi_94[1]),\n  superiore = c(eti_94[2], hdi_94[2]),\n  ampiezza = superiore - inferiore\n)\n\ninterval_comparison\n#> # A tibble: 2 x 4\n#>   tipo            inferiore superiore ampiezza\n#>   <chr>               <dbl>     <dbl>    <dbl>\n#> 1 Code uguali         0.478     0.761    0.283\n#> 2 Massima densità     0.483     0.765    0.283\n```\n:::\n\n\nNel nostro esempio i due intervalli sono simili perché la posterior non è fortemente asimmetrica. Nessuno dei due è “la posterior”: entrambi comprimono il 94% della massa in due estremi numerici.\n\n::: {.callout-caution title=\"Distribuzioni multimodali\"}\nQuando la posterior è multimodale, la regione di massima densità può essere formata da più intervalli separati. Forzarla in un unico intervallo può includere zone di bassa densità e nascondere la struttura della distribuzione. In questi casi il grafico della posterior è indispensabile.\n:::\n\n## Probabilità posteriori di affermazioni sostantive\n\nSpesso la domanda scientifica non è “qual è il centro della distribuzione?”, ma “quanto è plausibile che il parametro superi una soglia rilevante?”. La posterior consente di rispondere integrando la densità sulla regione corrispondente.\n\nNel nostro esempio possiamo calcolare:\n\n$$\nP(\\theta>0.50\\mid y),\n\\qquad\nP(\\theta>0.60\\mid y),\n\\qquad\nP(0.50<\\theta<0.70\\mid y).\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nposterior_probabilities <- tibble(\n  affermazione = c(\n    \"theta > 0.50\",\n    \"theta > 0.60\",\n    \"0.50 < theta < 0.70\"\n  ),\n  probabilita = c(\n    pbeta(0.50, alpha_post, beta_post, lower.tail = FALSE),\n    pbeta(0.60, alpha_post, beta_post, lower.tail = FALSE),\n    pbeta(0.70, alpha_post, beta_post) -\n      pbeta(0.50, alpha_post, beta_post)\n  )\n)\n\nposterior_probabilities\n#> # A tibble: 3 x 2\n#>   affermazione        probabilita\n#>   <chr>                     <dbl>\n#> 1 theta > 0.50              0.946\n#> 2 theta > 0.60              0.637\n#> 3 0.50 < theta < 0.70       0.782\n```\n:::\n\n\nQueste quantità comunicano aspetti differenti:\n\n- $P(\\theta>0.50\\mid y)$ chiede se la categoria riguardi la maggioranza della popolazione;\n- $P(\\theta>0.60\\mid y)$ usa una soglia più esigente;\n- $P(0.50<\\theta<0.70\\mid y)$ valuta una regione, non un singolo punto.\n\nLa soglia deve essere scelta per ragioni sostantive, non perché produce una probabilità più favorevole. Cambiare soglia significa cambiare domanda.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nthresholds <- c(0.50, 0.60, 0.70)\n\nthreshold_regions <- bind_rows(\n  lapply(thresholds, function(cutoff) {\n    posterior_curve |>\n      mutate(\n        soglia = cutoff,\n        regione = if_else(theta > cutoff, \"Sopra la soglia\", \"Sotto la soglia\")\n      )\n  })\n)\n\nggplot(threshold_regions, aes(x = theta, y = densita, fill = regione)) +\n  geom_area(alpha = 0.65, position = \"identity\") +\n  geom_vline(\n    aes(xintercept = soglia),\n    linetype = \"dashed\",\n    linewidth = 0.7\n  ) +\n  facet_wrap(~ soglia, labeller = label_both) +\n  scale_fill_manual(\n    values = c(\n      \"Sotto la soglia\" = modern_palette$grey6,\n      \"Sopra la soglia\" = PRIMARY\n    )\n  ) +\n  labs(\n    title = \"La probabilità posterior dipende dall'affermazione formulata\",\n    x = expression(theta),\n    y = \"Densità a posteriori\",\n    fill = NULL\n  ) +\n  legenda_in_alto\n```\n\n::: {.cell-output-display}\n![Probabilità posteriori associate a tre soglie sostantive. In ciascun pannello la distribuzione resta invariata, mentre l'area evidenziata rappresenta la massa a posteriori al di sopra della soglia indicata.](03_summary_posterior_files/figure-pdf/fig-summary-posterior-threshold-regions-1.png){#fig-summary-posterior-threshold-regions fig-align='center' fig-pos='H' fig-alt='Tre pannelli con la stessa curva a posteriori e soglie pari a 0.50, 0.60 e 0.70. L\\'area a destra della soglia diminuisce all\\'aumentare del valore di riferimento.' width=85%}\n:::\n:::\n\n\n::: {.callout-important title=\"La distribuzione viene prima della soglia\"}\nLa posterior resta la stessa nei tre pannelli. Ciò che cambia è la domanda posta alla distribuzione. Una probabilità posterior non è una proprietà isolata dei dati: dipende dalla regione di parametro definita come scientificamente rilevante.\n:::\n\n## Intervalli di credibilità e intervalli di confidenza\n\nUn intervallo di credibilità e un intervallo di confidenza possono avere estremi numericamente simili, ma rispondono a interpretazioni differenti.\n\n- Un intervallo di credibilità contiene una determinata massa della distribuzione a posteriori, condizionatamente al modello, al prior e ai dati.\n- Un intervallo di confidenza è prodotto da una procedura che, sotto ripetizioni ipotetiche del campionamento e date le assunzioni del metodo, raggiunge una determinata frequenza di copertura.\n\nPer il singolo intervallo bayesiano possiamo formulare una probabilità sul parametro all'interno del modello. Per il singolo intervallo frequentista, la probabilità di copertura non viene assegnata al parametro fisso dopo che gli estremi sono stati osservati.\n\nLa differenza non rende ogni intervallo bayesiano ben calibrato o informativo. Un prior inadeguato, una verosimiglianza mal specificata o dati poco rappresentativi producono una posterior fuorviante: che la sintesi sia interpretabile non sostituisce la valutazione del modello.\n\n## Come comunicare una posterior in forma succinta\n\nUn resoconto essenziale contiene quattro elementi:\n\n- il parametro e la sua interpretazione sostantiva, con il modello e il prior adottati;\n- una stima centrale;\n- un intervallo di credibilità;\n- dove serve, una probabilità riferita a una soglia definita in anticipo.\n\nSi chiude ricordando che l'inferenza è condizionata a quelle scelte.\n\nPer l'esempio precedente, una formulazione possibile è:\n\n> Con un prior $\\operatorname{Beta}(8,2)$ e 17 casi su 30, la distribuzione a posteriori della proporzione è $\\operatorname{Beta}(25,15)$. La mediana a posteriori è 0.627 e l'intervallo a code uguali al 94% è [0.478, 0.761]. La probabilità posterior che la proporzione superi 0.50 è 0.946. Tali conclusioni sono condizionate dal prior, dal modello binomiale e dalla definizione adottata dell'esito.\n\nPer quanto conciso, il resoconto non è neutrale: sceglie la mediana, un livello di massa del 94% e la soglia 0.50, e ognuna delle tre è una decisione. Quando la forma della posterior o la dipendenza dal prior contano per l'interpretazione, il grafico della distribuzione e un'analisi di sensibilità diventano indispensabili.\n\n## Più parametri: le sintesi marginali non bastano sempre\n\nNei modelli con più parametri, ogni distribuzione marginale descrive un parametro dopo avere integrato sugli altri. È un'operazione utile che però nasconde le dipendenze: due parametri possono avere marginali ampie ed essere vincolati a combinazioni congiunte molto strette.\n\nPer questo, oltre alle sintesi univariate, è spesso necessario esaminare:\n\n- grafici congiunti o *pair plot*;\n- correlazioni posteriori;\n- trasformazioni sostantive dei parametri;\n- quantità predittive, che propagano congiuntamente tutta l'incertezza.\n\n::: {.callout-note collapse=\"true\" title=\"Approfondimento: perché il MAP richiede cautela\"}\nLa densità cambia quando il parametro viene trasformato, perché la trasformazione modifica la scala e introduce un termine Jacobiano. Di conseguenza, il punto di massima densità di $\\theta$ non si trasforma necessariamente nel punto di massima densità di $g(\\theta)$. Media, mediana e probabilità di regioni trasformate devono anch'esse essere interpretate nella scala sostantiva appropriata, ma il MAP è particolarmente sensibile a questo problema.\n:::\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nLa distribuzione a posteriori descrive per intero l'incertezza sul parametro all'interno del modello. Interpretarla non significa trovare l'unico “numero corretto”, ma capire come la plausibilità si distribuisce fra valori e regioni.\n\nLe sintesi posteriori svolgono tre funzioni complementari:\n\n1. **localizzare** la distribuzione mediante media, mediana o moda;\n2. **descrivere l'incertezza** mediante deviazione standard e intervalli;\n3. **rispondere a domande scientifiche** mediante probabilità di soglie o regioni.\n\nOgni sintesi perde informazione. Due posterior possono avere la stessa media ma dispersioni molto diverse; due posterior con lo stesso intervallo possono avere forme differenti; una probabilità elevata sopra una soglia può cambiare sensibilmente quando la soglia cambia. Per questo motivo la scelta delle sintesi deve seguire la domanda scientifica ed essere accompagnata, quando necessario, dalla distribuzione completa.\n\nIl passaggio fondamentale è quindi:\n\n$$\n\\text{posterior completa}\n\\longrightarrow\n\\text{domanda sostantiva}\n\\longrightarrow\n\\text{sintesi appropriata}.\n$$\n\nNon è la sintesi a dare significato alla posterior: è la posterior, interrogata con una domanda esplicita, a dare significato alla sintesi.\n\n## Esercizi {.unnumbered .unlisted}\n\n### Esercizio 1 — Comprendere {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 15 minuti*\n\nConsidera la seguente distribuzione a posteriori discreta:\n\n| $\\theta$ | 0.30 | 0.50 | 0.70 | 0.90 |\n|---:|---:|---:|---:|---:|\n| $P(\\theta\\mid y)$ | 0.05 | 0.25 | 0.50 | 0.20 |\n\n1. Spiega che cosa significa assegnare probabilità posterior 0.50 a $\\theta=0.70$.\n2. Calcola $P(\\theta\\geq0.70\\mid y)$.\n3. Calcola la media posterior.\n4. Individua mediana e moda.\n5. Spiega quali informazioni vengono perse comunicando soltanto la media.\n6. Spiega perché, nel caso continuo, non interpreteremmo l'altezza della densità come probabilità di un singolo valore.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nLa media si ottiene moltiplicando ciascun valore di $\\theta$ per la probabilità corrispondente e sommando i prodotti. La mediana è il primo valore per cui la probabilità cumulata raggiunge almeno 0.50.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\nLa probabilità 0.50 attribuita a $\\theta=0.70$ significa che, all'interno del modello discreto e dopo aver osservato i dati, metà della massa posterior è assegnata esattamente a quel valore.\n\n$$\nP(\\theta\\geq0.70\\mid y)=0.50+0.20=0.70.\n$$\n\nLa media è:\n\n$$\n0.30(0.05)+0.50(0.25)+0.70(0.50)+0.90(0.20)=0.67.\n$$\n\nLa probabilità cumulata raggiunge 0.30 a $\\theta=0.50$ e 0.80 a $\\theta=0.70$, quindi la mediana è 0.70. Anche la moda è 0.70, perché riceve la probabilità maggiore.\n\nComunicando soltanto la media 0.67 perdiamo la dispersione della massa, la presenza del 20% su 0.90 e la probabilità del 30% assegnata a valori non superiori a 0.50. Nel caso continuo, ogni singolo punto ha probabilità zero: le probabilità riguardano aree o intervalli, non l'altezza puntuale della densità.\n:::\n\n### Esercizio 2 — Prevedere {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 10 minuti*\n\nConsidera tre posterior Beta con la stessa media, 0.625, ma concentrazioni differenti:\n\n- A: $\\operatorname{Beta}(5,3)$;\n- B: $\\operatorname{Beta}(25,15)$;\n- C: $\\operatorname{Beta}(100,60)$.\n\nPrima di effettuare qualsiasi calcolo, prevedi:\n\n1. quale distribuzione avrà l'intervallo al 94% più ampio;\n2. quale avrà l'intervallo più stretto;\n3. in quale distribuzione sarà maggiore $P(\\theta>0.70\\mid y)$;\n4. in quale distribuzione sarà maggiore $P(\\theta>0.60\\mid y)$;\n5. perché la stessa media non implica la stessa conclusione sostantiva.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nAll'aumentare della concentrazione, la distribuzione si restringe intorno alla media 0.625. Considera separatamente una soglia sopra la media, 0.70, e una soglia sotto la media, 0.60.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\nA ha la concentrazione minore e quindi l'intervallo più ampio; C ha la concentrazione maggiore e quindi l'intervallo più stretto.\n\nPoiché 0.70 è sopra la media comune, la distribuzione più diffusa A lascia più massa oltre 0.70. Restringendosi intorno a 0.625, C assegna sempre meno massa a valori così alti.\n\nPoiché 0.60 è sotto la media, la concentrazione crescente sposta una quota maggiore della massa sopra 0.60: $P(\\theta>0.60\\mid y)$ è quindi maggiore in C.\n\nLa media comunica soltanto il centro. Le probabilità riferite a una soglia dipendono anche dalla dispersione e dalla posizione della soglia rispetto alla distribuzione.\n:::\n\n### Esercizio 3 — Modificare {.unnumbered .unlisted}\n\n*Codice: sì · Tempo indicativo: 20 minuti*\n\nRiprendi l'esempio con 17 successi su 30 prove.\n\n1. Calcola la posterior usando il prior Beta(8,2).\n2. Calcola $P(\\theta>c\\mid y)$ per $c=0.50$, $0.60$ e $0.70$.\n3. Ripeti l'analisi usando il prior Beta(2,2).\n4. Per ciascun prior, riporta media, intervallo a code uguali al 94% e le tre probabilità di superamento.\n5. Scrivi due frasi: una descrive ciò che rimane uguale cambiando soglia; l'altra descrive ciò che cambia modificando il prior.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nPer il prior Beta(2,2), la posterior è Beta(19,15). Usa `pbeta()` con `lower.tail = FALSE` e `qbeta()` per l'intervallo.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\nUn possibile codice è:\n\n```r\nsummarise_beta_posterior <- function(alpha_prior, beta_prior,\n                                     successi = 17, prove = 30,\n                                     soglie = c(0.50, 0.60, 0.70)) {\n  alpha_post <- alpha_prior + successi\n  beta_post <- beta_prior + prove - successi\n\n  list(\n    parametri = c(alpha_post, beta_post),\n    media = alpha_post / (alpha_post + beta_post),\n    intervallo_94 = qbeta(\n      c(0.03, 0.97),\n      alpha_post,\n      beta_post\n    ),\n    probabilita_superamento = pbeta(\n      soglie,\n      alpha_post,\n      beta_post,\n      lower.tail = FALSE\n    )\n  )\n}\n\nsummarise_beta_posterior(8, 2)\nsummarise_beta_posterior(2, 2)\n```\n\nCon una posterior fissata, cambiare soglia non modifica la distribuzione: cambia soltanto la regione sulla quale viene calcolata la massa. Cambiare prior, invece, modifica la posterior stessa e quindi tutte le sintesi che ne derivano. Il confronto mostra perché una probabilità posterior deve sempre essere comunicata insieme al modello e al prior.\n:::\n\n### Esercizio 4 — Criticare {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 15 minuti*\n\nValuta la seguente comunicazione dei risultati:\n\n> “La stima vera della prevalenza è 0.625. L'intervallo al 94% dimostra che il 94% dei prossimi campioni avrà una proporzione compresa tra 0.478 e 0.761. Poiché $P(\\theta>0.50\\mid y)=0.946$, l'ipotesi nulla è stata rifiutata con una probabilità di errore del 5.4%.”\n\nIndividua almeno quattro problemi e riscrivi il resoconto in forma corretta.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nDistingui tra parametro e campioni futuri, stima puntuale e verità, probabilità posterior e tasso di errore frequentista. Ricorda inoltre di dichiarare prior e modello.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Elementi per la risposta\"}\nLa media posterior 0.625 non è “la stima vera”: è una sintesi della distribuzione. L'intervallo riguarda $\\theta$, non la proporzione che sarà osservata in campioni futuri; per quest'ultima servirebbe la distribuzione predittiva. La probabilità 0.946 è la massa posterior della regione $\\theta>0.50$ nel modello specificato e non è un tasso frequentista di errore di tipo I. Inoltre, una probabilità elevata non equivale a una dimostrazione definitiva.\n\nUna formulazione corretta è:\n\n> “Assumendo un modello Beta-Binomiale con prior Beta(8,2), dopo 17 casi su 30 la posterior della proporzione è Beta(25,15). La media posterior è 0.625 e l'intervallo a code uguali al 94% è circa [0.478, 0.761]. La probabilità posterior che la proporzione superi 0.50 è circa 0.946. Le conclusioni sono condizionate al prior, al modello e alla definizione dell'esito.”\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.6.1\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.1            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.1           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8         tidyselect_1.2.1     farver_2.1.2        \n#>  [4] S7_0.2.2             fastmap_1.2.0        tensorA_0.36.2.1    \n#>  [7] digest_0.6.39        timechange_0.4.0     estimability_2.0.0  \n#> [10] lifecycle_1.0.5      magrittr_2.0.5       compiler_4.6.1      \n#> [13] rlang_1.3.0          tools_4.6.1          utf8_1.2.6          \n#> [16] yaml_2.3.12          knitr_1.51           labeling_0.4.3      \n#> [19] bridgesampling_1.2-1 pkgbuild_1.4.8       curl_7.1.0          \n#> [22] RColorBrewer_1.1-3   abind_1.4-8          purrr_1.2.2         \n#> [25] grid_4.6.1           stats4_4.6.1         xtable_1.8-8        \n#> [28] inline_0.3.21        emmeans_2.0.4        scales_1.4.0        \n#> [31] cli_3.6.6            mvtnorm_1.4-2        rmarkdown_2.31      \n#> [34] generics_0.1.4       otel_0.2.0           RcppParallel_6.2.0  \n#> [37] cachem_1.1.0         stringr_1.6.0        parallel_4.6.1      \n#> [40] vctrs_0.7.3          V8_8.2.0             Matrix_1.7-6        \n#> [43] jsonlite_2.0.0       arrayhelpers_1.1-2   glue_1.8.1          \n#> [46] codetools_0.2-20     distributional_0.8.1 lubridate_1.9.5     \n#> [49] stringi_1.8.9        gtable_0.3.6         QuickJSR_1.10.0     \n#> [52] pillar_1.11.1        htmltools_0.5.9      Brobdingnag_1.2-9   \n#> [55] R6_2.6.1             textshaping_1.0.5    rprojroot_2.1.1     \n#> [58] evaluate_1.0.5       lattice_0.22-9       backports_1.5.1     \n#> [61] memoise_2.0.1        broom_1.0.13         snakecase_0.11.1    \n#> [64] rstantools_2.7.0     coda_0.19-4.1        gridExtra_2.3.1     \n#> [67] nlme_3.1-170         checkmate_2.3.4      xfun_0.60           \n#> [70] pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "03_summary_posterior_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}