{
  "hash": "f94468ed3baf327d43c21c732967f39a",
  "result": {
    "engine": "knitr",
    "markdown": "# Limiti dell'inferenza frequentista: un laboratorio computazionale {#sec-limits-freq-inference}\n\n::: {.callout-note appearance=\"minimal\"}\nNel manuale abbiamo analizzato i fondamenti teorici della critica al valore-$p$: la sua definizione come probabilità condizionata all'ipotesi nulla, le controversie storiche tra Fisher e Neyman-Pearson e la dichiarazione dell'American Statistical Association del 2016 [@wasserstein2016asa].\n\nIn questo capitolo non ripeteremo quelle argomentazioni, ma ne esploreremo alcune conseguenze mediante simulazioni computazionali. Genereremo dati, applicheremo procedure basate sui valori-$p$ e osserveremo come i risultati cambiano quando si moltiplicano i test, si selezionano le analisi o si applica rigidamente una soglia convenzionale.\n\nLe simulazioni sono volutamente semplici. Non riproducono tutta la complessità della ricerca reale, ma isolano alcuni meccanismi fondamentali e permettono di comprenderli in modo operativo.\n:::\n\n::: {.callout-important appearance=\"minimal\" .chapter-status}\n**Da sapere.** Assumendo vera l'ipotesi nulla, il valore-$p$ esprime la probabilità di osservare un risultato almeno altrettanto estremo di quello ottenuto; non esprime la probabilità che l'ipotesi nulla sia vera. Il $p$-hacking e l'uso rigido della soglia 0.05 possono produrre conclusioni instabili e aumentare il rischio di falsi positivi.\n\n**Da saper fare.** Eseguire e interpretare simulazioni che mostrano l'inflazione dei falsi positivi, gli effetti della selezione dei risultati, la confusione tra $P(\\text{Dati} \\mid H_0)$ e $P(H_0 \\mid \\text{Dati})$ e la fragilità delle decisioni basate su una soglia fissa.\n\n**Approfondimento facoltativo.** Le evidenze tratte dalla letteratura e i passaggi analitici più dettagliati approfondiscono gli stessi problemi, ma possono essere saltati senza perdere il filo concettuale del capitolo. Gli esercizi finali consolidano invece gli obiettivi essenziali.\n\n[Che cosa significano queste etichette?](../../guida-al-manuale.qmd#sec-percorsi-lettura)\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Prerequisiti\"}\n\n- Rivedere nel manuale la trattazione del **valore-$p$ e dei suoi fraintendimenti**, che fornisce le basi teoriche per le simulazioni presentate qui.\n- Leggere l'approfondimento [Inferenza frequentista in psicologia](https://ccaudek.github.io/utet-frequentista/).\n- Leggere le seguenti appendici: @sec-apx-numbers e @sec-apx-sums.\n:::\n\n::: {.callout-caution collapse=\"true\" title=\"Preparazione del notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |>\n  source()\n```\n:::\n\n:::\n\n## Simulazione 1: il $p$-hacking in azione\n\nImmaginiamo che, in assenza di un effetto reale, un ricercatore possa esaminare numerosi risultati candidati: diverse variabili dipendenti, diversi sottogruppi o diverse specificazioni analitiche. Ogni test aggiuntivo offre una nuova possibilità di superare casualmente la soglia di significatività.\n\nPer isolare questo meccanismo consideriamo un caso idealizzato: il ricercatore esegue 20 test indipendenti, tutti riferiti a ipotesi nulle vere, e riporta soltanto il valore-$p$ più basso. La simulazione non rappresenta tutte le forme possibili di $p$-hacking, ma mostra con chiarezza il problema della selezione tra molti risultati [@gelman2013garden; @wicherts2016degrees].\n\nParametri della simulazione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn_tests <- 20\nn_per_group <- 30\nn_simulations <- 5000\nalpha <- 0.05\n```\n:::\n\n\nLa funzione seguente genera, per ciascun test, due campioni da popolazioni identiche. Non esiste quindi alcun effetto reale. Al termine vengono conservati soltanto il valore-$p$ minimo e l'informazione relativa al superamento della soglia.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsimulate_phacking <- function(n_tests, n_per_group) {\n  p_values <- replicate(n_tests, {\n    group1 <- rnorm(n_per_group, mean = 0, sd = 1)\n    group2 <- rnorm(n_per_group, mean = 0, sd = 1)\n    t.test(group1, group2)$p.value\n  })\n\n  min(p_values)\n}\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nbest_p_values <- replicate(\n  n_simulations,\n  simulate_phacking(n_tests, n_per_group)\n)\n\nfalse_positive_rate <- mean(best_p_values < alpha)\ntheoretical_fwer <- 1 - (1 - alpha)^n_tests\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntibble(p_value = best_p_values) |>\n  ggplot(aes(x = p_value)) +\n  geom_histogram(\n    bins = 50,\n    fill = palette_qualitative[2],\n    color = \"white\",\n    alpha = 0.85\n  ) +\n  geom_vline(\n    xintercept = alpha,\n    color = palette_qualitative[6],\n    linetype = \"dashed\",\n    linewidth = 1\n  ) +\n  annotate(\n    \"text\",\n    x = 0.18,\n    y = Inf,\n    vjust = 2,\n    label = sprintf(\n      \"Almeno un falso positivo: %.1f%%\",\n      false_positive_rate * 100\n    ),\n    color = palette_qualitative[6],\n    fontface = \"bold\",\n    size = 4.5\n  ) +\n  labs(\n    x = \"Valore-p minimo tra 20 test\",\n    y = \"Frequenza\",\n    title = \"Selezionare il valore-p più basso tra molti test\",\n    subtitle = \"Tutte le ipotesi nulle sono vere\"\n  ) +\n  scale_x_continuous(breaks = seq(0, 1, 0.1))\n```\n\n::: {.cell-output-display}\n![Distribuzione del valore-p minimo quando vengono eseguiti 20 test indipendenti sotto l'ipotesi nulla.](01_limits_stat_freq_files/figure-html/fig-phacking-minimum-1.png){#fig-phacking-minimum fig-align='center' width=85%}\n:::\n:::\n\n\n**Interpretazione.** Anche se l'effetto reale è sempre zero, selezionando il valore-$p$ più basso tra 20 test indipendenti si ottiene almeno un risultato con $p < 0.05$ in circa 63.6% delle simulazioni. Il livello nominale del 5% controlla l'errore di tipo I per un singolo test prestabilito, non la probabilità di almeno un falso positivo quando vengono eseguiti molti test e si seleziona il risultato più favorevole.\n\nSotto l'ipotesi di indipendenza, il risultato può essere calcolato analiticamente:\n\n$$\n\\begin{aligned}\nP(\\text{almeno un falso positivo})\n&= 1 - P(\\text{nessun falso positivo}) \\\\\n&= 1 - (1 - \\alpha)^k.\n\\end{aligned}\n$$\n\nCon $\\alpha = 0.05$ e $k = 20$:\n\n$$\n1 - 0.95^{20} \\approx 0.642.\n$$\n\nIl valore esatto dipende da quanto i test sono correlati fra loro. Nella ricerca reale le analisi condotte sullo stesso dataset raramente sono indipendenti, quindi la probabilità può discostarsi dal 64%. Rimane però invariato il principio: provare molte analisi e riportare selettivamente quella più favorevole altera il tasso di errore della procedura complessiva.\n\n::: {.callout-note title=\"Riflessione\"}\nQuesto scenario non richiede necessariamente malafede. La flessibilità può emergere da decisioni che, considerate singolarmente, sembrano ragionevoli. Il problema è strutturale: quando le scelte dipendono dai risultati osservati e non vengono dichiarate, l'interpretazione convenzionale del valore-$p$ non è più giustificata.\n:::\n\n## Simulazione 2: la selezione modifica la distribuzione dei valori-$p$\n\nSe i risultati vengono selezionati in funzione della soglia di 0.05, la distribuzione dei valori-$p$ riportati può mostrare un eccesso di valori immediatamente inferiori alla soglia. Per comprendere il meccanismo confrontiamo due scenari idealizzati.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn_studies <- 5000\nn_per_group <- 50\n```\n:::\n\n\n**Scenario 1: letteratura senza selezione dei risultati.** Nel 50% degli studi è presente un effetto moderato, $d = 0.3$; nel restante 50% l'effetto è nullo. Tutti i risultati vengono riportati, indipendentemente dal valore-$p$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsimulate_unselected_literature <- function() {\n  has_true_effect <- sample(c(TRUE, FALSE), 1)\n  true_d <- ifelse(has_true_effect, 0.3, 0)\n\n  group1 <- rnorm(n_per_group, mean = 0, sd = 1)\n  group2 <- rnorm(n_per_group, mean = true_d, sd = 1)\n\n  t.test(group1, group2)$p.value\n}\n\nset.seed(321)\nunselected_pvalues <- replicate(\n  n_studies,\n  simulate_unselected_literature()\n)\n```\n:::\n\n\n**Scenario 2: letteratura con selezione dei risultati.** Manteniamo la stessa prevalenza degli effetti. Per ciascuno studio vengono però generati fino a dieci risultati candidati indipendenti. Se uno di essi produce $p < 0.05$, viene riportato il primo risultato significativo; altrimenti viene riportato l'ultimo valore-$p$ calcolato. Si tratta di una rappresentazione semplificata della ricerca selettiva della significatività, non di un modello completo delle pratiche reali.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsimulate_selected_literature <- function() {\n  has_true_effect <- sample(c(TRUE, FALSE), 1)\n  true_d <- ifelse(has_true_effect, 0.3, 0)\n\n  for (attempt in seq_len(10)) {\n    group1 <- rnorm(n_per_group, mean = 0, sd = 1)\n    group2 <- rnorm(n_per_group, mean = true_d, sd = 1)\n    p <- t.test(group1, group2)$p.value\n\n    if (p < 0.05) return(p)\n  }\n\n  p\n}\n\nset.seed(654)\nselected_pvalues <- replicate(\n  n_studies,\n  simulate_selected_literature()\n)\n```\n:::\n\n\nPer osservare meglio la regione intorno alla soglia limitiamo i grafici ai valori-$p$ inferiori a 0.10. Questa scelta ha una funzione esclusivamente grafica: non implica che tutti questi risultati siano significativi o pubblicabili.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np1 <- tibble(p_value = unselected_pvalues) |>\n  filter(p_value < 0.10) |>\n  ggplot(aes(x = p_value)) +\n  geom_histogram(\n    bins = 40,\n    fill = palette_qualitative[2],\n    color = \"white\",\n    alpha = 0.85\n  ) +\n  geom_vline(\n    xintercept = 0.05,\n    color = palette_qualitative[6],\n    linetype = \"dashed\",\n    linewidth = 1\n  ) +\n  labs(\n    title = \"A) Nessuna selezione\",\n    x = \"Valore-p\",\n    y = \"Frequenza\"\n  ) +\n  scale_x_continuous(breaks = seq(0, 0.10, 0.01)) +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n\np2 <- tibble(p_value = selected_pvalues) |>\n  filter(p_value < 0.10) |>\n  ggplot(aes(x = p_value)) +\n  geom_histogram(\n    bins = 40,\n    fill = palette_qualitative[6],\n    color = \"white\",\n    alpha = 0.85\n  ) +\n  geom_vline(\n    xintercept = 0.05,\n    color = palette_qualitative[6],\n    linetype = \"dashed\",\n    linewidth = 1\n  ) +\n  labs(\n    title = \"B) Selezione dei risultati\",\n    x = \"Valore-p\",\n    y = \"Frequenza\"\n  ) +\n  scale_x_continuous(breaks = seq(0, 0.10, 0.01)) +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np1 + p2\n```\n\n::: {.cell-output-display}\n![Confronto tra una letteratura senza selezione dei risultati e una letteratura in cui vengono ricercati risultati significativi.](01_limits_stat_freq_files/figure-html/fig-pvalue-distribution-1.png){#fig-pvalue-distribution fig-align='center' width=85%}\n:::\n:::\n\n\nQuantifichiamo il rapporto tra la frequenza dei valori appena sotto e appena sopra 0.05:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nratio_near_threshold <- function(p_values) {\n  below <- sum(p_values >= 0.04 & p_values < 0.05)\n  above <- sum(p_values >= 0.05 & p_values < 0.06)\n  below / above\n}\n\nratio_unselected <- ratio_near_threshold(unselected_pvalues)\nratio_selected <- ratio_near_threshold(selected_pvalues)\n\nprop_sig_unselected <- mean(unselected_pvalues < 0.05)\nprop_sig_selected <- mean(selected_pvalues < 0.05)\n```\n:::\n\n\n**Interpretazione.** Nel primo scenario non emerge una discontinuità netta in corrispondenza della soglia. Il rapporto tra valori appena sotto e appena sopra 0.05 è 1.22, mentre la proporzione complessiva di risultati con $p < 0.05$ è 18.8%.\n\nNel secondo scenario la selezione produce un accumulo più evidente di valori inferiori a 0.05. Il rapporto tra le due regioni sale a 19.04 e la proporzione di risultati significativi raggiunge 69.2%. La letteratura osservata appare quindi più ricca di risultati positivi di quanto giustificato dal processo generativo.\n\n### Evidenze nella letteratura scientifica\n\nAnalisi su larga scala hanno cercato impronte aggregate compatibili con selezione analitica e bias di pubblicazione. @head2015extent hanno esaminato un ampio corpus multidisciplinare e hanno rilevato un modesto eccesso di valori appena inferiori a 0.05. In economia, @brodeur2020methods hanno documentato irregolarità nella distribuzione delle statistiche riportate in prossimità delle soglie convenzionali.\n\nQueste irregolarità non permettono di stabilire quale scelta sia stata compiuta in un singolo articolo. Possono derivare da molteplici processi, tra cui flessibilità analitica, reporting selettivo e selezione editoriale. Devono quindi essere interpretati come segnali a livello aggregato, non come prove di scorrettezza individuale.\n\nLa *p-curve* analizza la distribuzione dei valori-$p$ significativi in un insieme di studi. Sotto specifiche assunzioni, può essere utilizzata per valutare se l'insieme dei risultati possieda valore evidenziale e per stimare la potenza media o l'ampiezza dell'effetto [@simonsohn2014p]. Non fornisce invece, per ciascun risultato, la probabilità diretta che l'effetto sia reale.\n\n::: {.callout-note title=\"Implicazioni pratiche\"}\nLe distribuzioni aggregate possono aiutare a diagnosticare problemi sistemici, ma non sostituiscono l'esame dei singoli studi. Preregistrazione, dichiarazione delle analisi esplorative, correzioni per confronti multipli e condivisione di dati e codice riducono lo spazio per selezioni non trasparenti [@wicherts2016degrees].\n:::\n\n## Simulazione 3: il grande equivoco\n\nUno degli errori più diffusi consiste nel ritenere che un valore-$p$ pari a 0.03 indichi una probabilità del 3% che l'ipotesi nulla sia vera, oppure una probabilità del 97% che l'effetto esista. Questa interpretazione inverte la direzione della probabilità condizionata.\n\n### Che cosa misura il valore-$p$?\n\nIl valore-$p$ è la probabilità, calcolata sotto l'ipotesi nulla, di osservare un risultato almeno altrettanto estremo di quello ottenuto:\n\n$$\np = P(T \\geq T_{\\text{oss}} \\mid H_0),\n$$\n\ndove la definizione precisa di “almeno altrettanto estremo” dipende dal test e dalla sua natura unilaterale o bilaterale. Il valore-$p$ non è $P(H_0 \\mid \\text{Dati})$.\n\n### Perché l'inversione è sbagliata\n\nLe due probabilità\n\n$$\nP(\\text{Dati} \\mid H_0)\n\\qquad \\text{e} \\qquad\nP(H_0 \\mid \\text{Dati})\n$$\n\nrispondono a domande diverse. Il teorema di Bayes mostra quali informazioni sono necessarie per ottenere la seconda:\n\n$$\nP(H_0 \\mid \\text{Dati}) =\n\\frac{\n  P(\\text{Dati} \\mid H_0) P(H_0)\n}{\n  P(\\text{Dati} \\mid H_0) P(H_0)\n  + P(\\text{Dati} \\mid H_1) P(H_1)\n}.\n$$\n\nOccorre dunque specificare la plausibilità a priori delle ipotesi e un modello per la probabilità dei dati sotto ciascuna di esse. La potenza statistica è una quantità diversa: rappresenta, per una specifica alternativa, la probabilità di superare una soglia decisionale, per esempio $P(p < \\alpha \\mid H_1)$; non coincide con la probabilità dei dati specificamente osservati sotto $H_1$.\n\nLa simulazione seguente affronta una domanda più limitata ma utile: **tra i risultati che superano una determinata soglia, quale proporzione proviene da studi in cui l'effetto è realmente presente?** Questa proporzione è il valore predittivo positivo, o PPV, della regola di selezione adottata.\n\n### Simulazione\n\nImmaginiamo un campo esplorativo nel quale soltanto il 10% delle ipotesi esaminate corrisponde a un effetto reale. Quando l'effetto esiste, la sua ampiezza standardizzata è $d = 0.5$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprior_prob_effect <- 0.10\neffect_size_if_true <- 0.5\nn_studies <- 10000\nn_per_group <- 30\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(987)\nresults <- tibble(\n  study_id = seq_len(n_studies),\n  has_true_effect = runif(n_studies) < prior_prob_effect\n) |>\n  rowwise() |>\n  mutate(\n    true_d = ifelse(has_true_effect, effect_size_if_true, 0),\n    p_value = {\n      group1 <- rnorm(n_per_group, mean = 0, sd = 1)\n      group2 <- rnorm(n_per_group, mean = true_d, sd = 1)\n      t.test(group1, group2)$p.value\n    }\n  ) |>\n  ungroup()\n```\n:::\n\n\nIl processo generativo contiene due tipi di studi:\n\n1. nel 90% dei casi l'effetto è nullo e un risultato significativo costituisce un falso positivo;\n2. nel 10% dei casi l'effetto è pari a $d = 0.5$ e un risultato significativo costituisce un vero positivo.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncalculate_ppv <- function(data, p_threshold) {\n  selected <- data |>\n    filter(p_value < p_threshold)\n\n  if (nrow(selected) == 0) return(NA_real_)\n  mean(selected$has_true_effect)\n}\n\nthresholds <- c(0.05, 0.01, 0.005, 0.001)\n\nppv_results <- tibble(\n  threshold = thresholds,\n  ppv = vapply(\n    thresholds,\n    function(x) calculate_ppv(results, x),\n    numeric(1)\n  )\n)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nresults |>\n  filter(p_value < 0.05) |>\n  ggplot(aes(x = p_value, fill = has_true_effect)) +\n  geom_histogram(bins = 35, position = \"stack\", alpha = 0.85) +\n  scale_fill_manual(\n    values = c(\n      \"FALSE\" = palette_qualitative[6],\n      \"TRUE\" = palette_qualitative[3]\n    ),\n    labels = c(\n      \"FALSE\" = \"Nessun effetto: falso positivo\",\n      \"TRUE\" = \"Effetto reale: vero positivo\"\n    )\n  ) +\n  labs(\n    x = \"Valore-p\",\n    y = \"Numero di studi\",\n    fill = \"Origine del risultato\",\n    title = \"Composizione dei risultati con p < 0.05\",\n    subtitle = sprintf(\n      \"Prevalenza degli effetti reali nel campo: %.0f%%\",\n      prior_prob_effect * 100\n    )\n  )\n```\n\n::: {.cell-output-display}\n![Composizione dei risultati con p < 0.05 nel modello simulato.](01_limits_stat_freq_files/figure-html/fig-ppv-composition-1.png){#fig-ppv-composition fig-align='center' width=85%}\n:::\n:::\n\n\nLa tabella confronta il PPV simulato con una lettura errata molto comune, secondo la quale $1-p$ rappresenterebbe la probabilità che l'effetto sia reale.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncomparison_summary <- ppv_results |>\n  transmute(\n    `Soglia di selezione` = sprintf(\"p < %.3f\", threshold),\n    `Lettura errata: P(effetto reale)` = sprintf(\n      \"%.1f%%\",\n      100 * (1 - threshold)\n    ),\n    `PPV nel modello simulato` = sprintf(\"%.1f%%\", 100 * ppv),\n    `Sovrastima` = sprintf(\n      \"%.1f punti percentuali\",\n      100 * ((1 - threshold) - ppv)\n    )\n  )\n\nknitr::kable(\n  comparison_summary,\n  align = c(\"l\", \"c\", \"c\", \"c\"),\n  caption = \"Confronto tra una lettura errata della soglia e il PPV nel modello simulato\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Confronto tra una lettura errata della soglia e il PPV nel modello simulato\n\n|Soglia di selezione | Lettura errata: P(effetto reale) | PPV nel modello simulato |       Sovrastima       |\n|:-------------------|:--------------------------------:|:------------------------:|:----------------------:|\n|p < 0.050           |              95.0%               |          53.0%           | 42.0 punti percentuali |\n|p < 0.010           |              99.0%               |          74.9%           | 24.1 punti percentuali |\n|p < 0.005           |              99.5%               |          81.1%           | 18.4 punti percentuali |\n|p < 0.001           |              99.9%               |          91.6%           | 8.3 punti percentuali  |\n\n\n:::\n:::\n\n\n**Interpretazione.** Nel modello adottato, tra i risultati con $p < 0.05$ la proporzione di effetti reali è 53.0%; tra quelli con $p < 0.01$ è 74.9%; tra quelli con $p < 0.001$ è 91.6%.\n\nQuesti numeri non sono proprietà universali delle soglie. Dipendono dalla prevalenza degli effetti reali, dalla loro ampiezza, dalla numerosità campionaria, dal test e dalle eventuali procedure di selezione. La simulazione mostra che la significatività statistica non coincide con la probabilità che un effetto sia reale.\n\n::: {.callout-important title=\"Distinzione essenziale\"}\nIl PPV calcolato qui è condizionato all'evento $p < \\alpha$: confronta l'origine vera o nulla dei risultati selezionati in molte ripetizioni del processo generativo. Non è una probabilità a posteriori ottenuta dal valore-$p$ esatto di un singolo studio.\n:::\n\n## Simulazione 4: la fragilità della soglia $p = 0.05$\n\nUn valore-$p$ pari a 0.049 e uno pari a 0.051 forniscono evidenze molto simili, ma una regola decisionale rigida li assegna a categorie opposte. La simulazione seguente mostra come repliche dello stesso studio, generate con lo stesso effetto vero, possano cadere sui due lati della soglia per effetto della variabilità campionaria.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntrue_effect <- 0.2\nn_per_group <- 50\nn_replications <- 1000\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(246)\nreplications <- tibble(replication = seq_len(n_replications)) |>\n  rowwise() |>\n  mutate(\n    p_value = {\n      group1 <- rnorm(n_per_group, mean = 0, sd = 1)\n      group2 <- rnorm(n_per_group, mean = true_effect, sd = 1)\n      t.test(group1, group2)$p.value\n    },\n    significant = p_value < 0.05\n  ) |>\n  ungroup()\n\nprop_significant <- mean(replications$significant)\nmedian_p <- median(replications$p_value)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npalette_signif <- c(\n  \"TRUE\" = palette_qualitative[3],\n  \"FALSE\" = palette_qualitative[8]\n)\n\nreplications |>\n  mutate(significant = factor(significant, levels = c(TRUE, FALSE))) |>\n  ggplot(aes(x = p_value, fill = significant)) +\n  geom_histogram(bins = 50, color = \"white\", alpha = 0.85) +\n  geom_vline(\n    xintercept = 0.05,\n    color = \"black\",\n    linetype = \"dashed\",\n    linewidth = 1\n  ) +\n  scale_fill_manual(\n    values = palette_signif,\n    labels = c(\n      \"TRUE\" = \"p < 0.05\",\n      \"FALSE\" = \"p >= 0.05\"\n    )\n  ) +\n  annotate(\n    \"text\",\n    x = 0.55,\n    y = Inf,\n    vjust = 2,\n    label = sprintf(\n      \"Effetto vero: d = %.1f\\nRepliche con p < 0.05: %.0f%%\\nMediana p: %.3f\",\n      true_effect,\n      prop_significant * 100,\n      median_p\n    ),\n    hjust = 0.5,\n    size = 4\n  ) +\n  labs(\n    x = \"Valore-p\",\n    y = \"Numero di repliche\",\n    fill = NULL,\n    title = sprintf(\n      \"%d repliche dello stesso studio con lo stesso effetto vero\",\n      n_replications\n    ),\n    subtitle = \"La classificazione cambia, ma il processo generativo rimane identico\"\n  )\n```\n\n::: {.cell-output-display}\n![Lo stesso effetto vero produce valori-p differenti in campioni diversi.](01_limits_stat_freq_files/figure-html/fig-threshold-fragility-1.png){#fig-threshold-fragility fig-align='center' width=85%}\n:::\n:::\n\n\n**Interpretazione.** Le repliche producono valori-$p$ molto diversi, benché l'effetto sottostante sia sempre $d = 0.2$. La proporzione di risultati con $p < 0.05$ è una proprietà del disegno e dell'effetto considerato, non una misura della verità del risultato ottenuto in una singola replica.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nreplications |>\n  filter(p_value > 0.03, p_value < 0.07) |>\n  mutate(significant = factor(significant, levels = c(TRUE, FALSE))) |>\n  ggplot(aes(x = p_value, fill = significant)) +\n  geom_histogram(bins = 20, color = \"white\", alpha = 0.85) +\n  geom_vline(\n    xintercept = 0.05,\n    color = \"black\",\n    linetype = \"dashed\",\n    linewidth = 1\n  ) +\n  scale_fill_manual(\n    values = palette_signif,\n    labels = c(\n      \"TRUE\" = \"p < 0.05\",\n      \"FALSE\" = \"p >= 0.05\"\n    )\n  ) +\n  labs(\n    x = \"Valore-p\",\n    y = \"Numero di repliche\",\n    fill = NULL,\n    title = \"La zona grigia intorno a 0.05\",\n    subtitle = \"Piccole fluttuazioni campionarie cambiano l'etichetta assegnata al risultato\"\n  )\n```\n\n::: {.cell-output-display}\n![Dettaglio della regione immediatamente circostante la soglia di 0.05.](01_limits_stat_freq_files/figure-html/fig-threshold-zoom-1.png){#fig-threshold-zoom fig-align='center' width=85%}\n:::\n:::\n\n\nLo zoom rende visibile il problema: i risultati immediatamente ai due lati della soglia sono molto simili sul piano dell'evidenza, ma vengono spesso descritti con linguaggi opposti. Come osservano @gelman2006difference:\n\n> *The difference between \"significant\" and \"not significant\" is not itself statistically significant.*\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nLe simulazioni hanno trasformato alcune critiche teoriche al valore-$p$ in problemi osservabili:\n\n1. **la selezione tra molti risultati modifica il tasso di errore complessivo**: il livello nominale del singolo test non protegge una procedura nella quale si provano molte analisi e si riporta soltanto quella più favorevole;\n\n2. **la distribuzione aggregata dei valori-$p$ può segnalare processi di selezione**: un accumulo vicino alle soglie convenzionali è compatibile con flessibilità analitica, reporting selettivo e bias di pubblicazione, ma non identifica la causa in un singolo studio;\n\n3. **il valore-$p$ non è la probabilità che l'ipotesi nulla sia vera**: la terza simulazione ha mostrato che il PPV di una regola di selezione dipende anche dalla prevalenza e dall'ampiezza degli effetti reali, non soltanto dalla soglia adottata;\n\n4. **la soglia 0.05 produce una classificazione discontinua di un'evidenza continua**: risultati quasi identici possono ricevere etichette opposte per effetto di piccole fluttuazioni campionarie.\n\nQueste osservazioni non implicano che il valore-$p$ sia sempre privo di utilità. Indicano piuttosto che deve essere interpretato insieme alla stima dell'effetto, alla sua incertezza, alla qualità del disegno, alla trasparenza delle analisi e alla plausibilità del modello. Nei capitoli successivi vedremo come l'approccio bayesiano renda esplicite alcune quantità che il valore-$p$ non fornisce.\n\n## Esercizi {.unnumbered .unlisted}\n\nGli esercizi seguenti consolidano i concetti essenziali del capitolo. Prima di aprire il suggerimento o la soluzione, prova a formulare una risposta con parole tue e, quando è richiesto l'uso di R, anticipa il risultato prima di eseguire il codice.\n\n### Esercizio 1 — Comprendere {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 10 minuti*\n\nCompleta le frasi seguenti e giustifica ciascuna risposta in una o due frasi.\n\n1. Quando un ricercatore esegue molti test e riporta soltanto il valore-$p$ più basso, il rischio di ottenere almeno un falso positivo aumenta perché...\n2. Un valore-$p$ pari a 0.03 esprime..., ma non esprime...\n3. Due risultati con $p = 0.049$ e $p = 0.051$ non giustificano conclusioni scientifiche opposte perché...\n4. Un accumulo anomalo di valori-$p$ appena inferiori a 0.05 può essere un indizio di...\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nRiprendi le quattro simulazioni del capitolo e associa a ciascuna frase il problema principale che illustra: confronti multipli, inversione della probabilità condizionata, soglia dicotomica e selezione dei risultati.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\n1. Ogni test offre una nuova possibilità di superare casualmente la soglia. Anche se ciascun test ha un tasso di falsi positivi del 5%, la probabilità di ottenere almeno un risultato significativo cresce con il numero dei test eseguiti.\n2. Un valore-$p$ pari a 0.03 esprime la probabilità di osservare dati almeno altrettanto estremi di quelli ottenuti, assumendo vera l'ipotesi nulla. Non esprime la probabilità che l'ipotesi nulla sia vera, né la probabilità che l'effetto esista.\n3. I due valori sono quasi identici e possono derivare da piccole fluttuazioni campionarie. La soglia 0.05 trasforma artificialmente una variazione continua dell'evidenza in due categorie contrapposte, “significativo” e “non significativo”.\n4. Un accumulo di valori appena inferiori a 0.05 può indicare selezione dei risultati, analisi ripetute fino al raggiungimento della significatività o altre forme di $p$-hacking. L'andamento, da solo, non dimostra però quale pratica sia stata adottata in un singolo studio.\n:::\n\n### Esercizio 2 — Prevedere {.unnumbered .unlisted}\n\n*Codice: facoltativo · Tempo indicativo: 10 minuti*\n\nNella Simulazione 1 l'ipotesi nulla è vera, i test sono indipendenti e ciascun test ha probabilità 0.05 di produrre un falso positivo. Prima di effettuare i calcoli, prevedi se la probabilità di ottenere almeno un risultato significativo sarà **inferiore, vicina o superiore al 50%** quando vengono eseguiti:\n\n- 5 test;\n- 20 test;\n- 50 test.\n\nVerifica poi le previsioni usando\n\n$$\nP(\\text{almeno un falso positivo}) = 1 - (1 - 0.05)^k,\n$$\n\ndove $k$ è il numero di test. Determina infine il numero minimo di test necessario per superare una probabilità del 50%.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nCalcola prima la probabilità di non ottenere alcun falso positivo, $0.95^k$, e poi considera l'evento complementare.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\nLe probabilità sono:\n\n$$\n\\begin{aligned}\nk=5  &: \\quad 1-0.95^5 \\approx 0.226,\\\\\nk=20 &: \\quad 1-0.95^{20} \\approx 0.642,\\\\\nk=50 &: \\quad 1-0.95^{50} \\approx 0.923.\n\\end{aligned}\n$$\n\nQuindi, con 5 test la probabilità è inferiore al 50%; con 20 e 50 test è superiore al 50%. Il numero minimo di test necessario per superare il 50% è 14:\n\n$$\n1-0.95^{14} \\approx 0.512.\n$$\n\nUna verifica in R può essere effettuata con:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nk <- c(5, 20, 50)\n1 - (1 - 0.05)^k\n#> [1] 0.226 0.642 0.923\n\nk_min <- which(1 - (1 - 0.05)^(1:100) > 0.50)[1]\nk_min\n#> [1] 14\n```\n:::\n\n\nIl punto importante non è soltanto il risultato numerico: il livello nominale del 5% protegge dal falso positivo quando viene considerato un singolo test prestabilito, non quando si provano molte analisi e si seleziona quella più favorevole.\n:::\n\n### Esercizio 3 — Modificare {.unnumbered .unlisted}\n\n*Codice: sì · Tempo indicativo: 15 minuti*\n\nRiprendi la Simulazione 4, mantenendo invariato l'effetto vero ($d = 0.2$), e ripetila con tre diverse numerosità campionarie per gruppo:\n\n- $n = 25$;\n- $n = 50$;\n- $n = 200$.\n\nPer ogni condizione calcola la proporzione di repliche con $p < 0.05$. Prima di eseguire il codice, prevedi:\n\n1. in quale condizione la proporzione di risultati significativi sarà maggiore;\n2. se l'aumento della numerosità campionaria eliminerà completamente la variabilità dei valori-$p$;\n3. quale aspetto del problema della soglia 0.05 rimarrà invariato.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nÈ sufficiente trasformare il codice già presente nel capitolo in una funzione che riceva `n_per_group` come argomento. Per rendere l'esercizio più rapido, puoi usare 5000 repliche per ciascuna condizione.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\nUn possibile svolgimento è il seguente:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\n\nestimate_significance_rate <- function(n_per_group,\n                                       true_effect = 0.2,\n                                       n_replications = 5000) {\n  p_values <- replicate(n_replications, {\n    g1 <- rnorm(n_per_group, mean = 0, sd = 1)\n    g2 <- rnorm(n_per_group, mean = true_effect, sd = 1)\n    t.test(g1, g2)$p.value\n  })\n\n  tibble(\n    n_per_group = n_per_group,\n    proportion_significant = mean(p_values < 0.05),\n    median_p_value = median(p_values)\n  )\n}\n\nresults_n <- purrr::map_dfr(\n  c(25, 50, 200),\n  estimate_significance_rate\n)\n\nresults_n\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"n_per_group\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"proportion_significant\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"median_p_value\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"25\",\"2\":\"0.0978\",\"3\":\"0.3994\"},{\"1\":\"50\",\"2\":\"0.1700\",\"3\":\"0.2932\"},{\"1\":\"200\",\"2\":\"0.5070\",\"3\":\"0.0479\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nAll'aumentare della numerosità campionaria cresce la probabilità di rilevare l'effetto reale e, quindi, aumenta la proporzione di risultati con $p < 0.05$. La variabilità campionaria si riduce, ma non scompare: repliche differenti continuano a produrre valori-$p$ differenti.\n\nRimane inoltre invariata la natura convenzionale della soglia. Un valore appena inferiore a 0.05 e uno appena superiore restano molto simili sul piano dell'evidenza, anche quando lo studio ha una numerosità maggiore. L'aumento del campione migliora la precisione e la potenza, ma non rende scientificamente naturale una classificazione rigidamente binaria.\n:::\n\n### Esercizio 4 — Criticare {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 10–15 minuti*\n\nUn articolo riporta il risultato seguente:\n\n> Nel primo studio l'intervento ha prodotto un effetto statisticamente significativo, $p = 0.049$, e possiamo quindi concludere che l'intervento funziona. In una replica il risultato non è stato significativo, $p = 0.051$, e ciò dimostra che l'effetto non esiste. I due studi conducono dunque a conclusioni opposte.\n\nIndividua almeno tre problemi nel ragionamento e riscrivi la conclusione in una forma più appropriata.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\nConsidera il significato effettivo del valore-$p$, la vicinanza tra 0.049 e 0.051 e le informazioni che mancano per valutare l'effetto.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Elementi per la risposta\"}\nUna buona risposta dovrebbe includere almeno i punti seguenti:\n\n- $p = 0.049$ non è la probabilità che l'intervento funzioni e non dimostra, da solo, che l'effetto esista;\n- $p = 0.051$ non dimostra che l'effetto sia assente;\n- la differenza tra 0.049 e 0.051 è minima e non giustifica conclusioni opposte;\n- per confrontare i due studi servono almeno le stime dell'effetto e la loro incertezza, oltre a informazioni sul disegno, sulla numerosità campionaria e sulle analisi effettuate;\n- occorre sapere se le analisi erano state stabilite in anticipo o se sono state provate molte alternative.\n\nUna possibile riformulazione è:\n\n> I due studi hanno prodotto valori-$p$ molto simili, collocati sui due lati della soglia convenzionale di 0.05. Questa differenza non è sufficiente per concludere che il primo studio dimostri la presenza dell'effetto e il secondo la sua assenza. Per valutare la coerenza dei risultati è necessario confrontare le stime dell'effetto, la loro incertezza e la qualità dei disegni di ricerca, evitando di ridurre l'evidenza a una classificazione binaria.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.6.1\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.1            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.1           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8         tidyselect_1.2.1     farver_2.1.2        \n#>  [4] S7_0.2.2             fastmap_1.2.0        tensorA_0.36.2.1    \n#>  [7] digest_0.6.39        timechange_0.4.0     estimability_2.0.0  \n#> [10] lifecycle_1.0.5      magrittr_2.0.5       compiler_4.6.1      \n#> [13] rlang_1.3.0          tools_4.6.1          yaml_2.3.12         \n#> [16] knitr_1.51           labeling_0.4.3       bridgesampling_1.2-1\n#> [19] htmlwidgets_1.6.4    pkgbuild_1.4.8       curl_7.1.0          \n#> [22] RColorBrewer_1.1-3   abind_1.4-8          purrr_1.2.2         \n#> [25] grid_4.6.1           stats4_4.6.1         xtable_1.8-8        \n#> [28] inline_0.3.21        emmeans_2.0.4        scales_1.4.0        \n#> [31] cli_3.6.6            mvtnorm_1.4-2        rmarkdown_2.31      \n#> [34] generics_0.1.4       otel_0.2.0           RcppParallel_6.2.0  \n#> [37] cachem_1.1.0         stringr_1.6.0        parallel_4.6.1      \n#> [40] vctrs_0.7.3          V8_8.2.0             Matrix_1.7-6        \n#> [43] jsonlite_2.0.0       arrayhelpers_1.1-2   glue_1.8.1          \n#> [46] codetools_0.2-20     distributional_0.8.1 lubridate_1.9.5     \n#> [49] stringi_1.8.9        gtable_0.3.6         QuickJSR_1.10.0     \n#> [52] pillar_1.11.1        htmltools_0.5.9      Brobdingnag_1.2-9   \n#> [55] R6_2.6.1             textshaping_1.0.5    rprojroot_2.1.1     \n#> [58] evaluate_1.0.5       lattice_0.22-9       backports_1.5.1     \n#> [61] memoise_2.0.1        broom_1.0.13         snakecase_0.11.1    \n#> [64] rstantools_2.7.0     coda_0.19-4.1        gridExtra_2.3.1     \n#> [67] nlme_3.1-170         checkmate_2.3.4      xfun_0.60           \n#> [70] pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "01_limits_stat_freq_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}