{
  "hash": "6fe2139b6ac729d106aa0bdc8bc58eb1",
  "result": {
    "engine": "knitr",
    "markdown": "# La decisione sul singolo paziente: dal punteggio osservato alla probabilità clinica {#sec-bayesian-inference-single-patient-cutoff}\n\n::: {.callout-important appearance=\"minimal\" .chapter-status}\n**Da sapere.** Un punteggio osservato non coincide con il punteggio vero postulato dal modello psicometrico, perché contiene errore di misura. Nel modello Normale-Normale, la distribuzione normativa dei punteggi veri costituisce il prior, il modello dell'errore di misura costituisce la distribuzione generativa del punteggio osservato e il loro aggiornamento produce la posterior sul punteggio vero del singolo paziente.\n\n**Da saper fare.** Interpretare prior, likelihood, posterior e distribuzione predittiva nel caso di un singolo paziente; calcolare la stima di Kelley e riconoscerla come media a posteriori nel modello adottato; interpretare $P(\\theta > c \\mid X)$ senza trasformarla automaticamente in una diagnosi; distinguere l'incertezza sul punteggio vero dalla variabilità di una nuova somministrazione.\n\n**Approfondimento facoltativo.** La derivazione algebrica dell'equivalenza tra Kelley e la media a posteriori, l'analisi di sensibilità rispetto all'attendibilità e la formulazione delle decisioni mediante funzioni di perdita possono essere rimandate in una prima lettura.\n\n[Che cosa significano queste etichette?](../../guida-al-manuale.qmd#sec-percorsi-lettura)\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Prerequisiti\"}\n\n- Sono dati per noti l’equilibrio tra prior e dati del capitolo 11 e la distribuzione predittiva a posteriori del capitolo 13.\n- È utile conoscere la distribuzione normale e i concetti di affidabilità, errore standard di misurazione e punteggio vero.\n- L'@sec-measurement-error-method-appendix offre un approfondimento sull’errore di misurazione e sulla varianza di metodo; il codice R è facoltativo.\n\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |>\n  source()\n```\n:::\n\n:::\n\n## Una vignetta clinica: quando due punti sembrano decisivi {#sec-vignetta-clinica}\n\nImmaginiamo che un clinico somministri un test standardizzato per la sintomatologia depressiva. Il manuale dello strumento indica un *cut-off* operativo pari a 70. Il paziente ottiene un punteggio osservato di 72.\n\nUna lettura meccanica sembra immediata:\n\n$$\n72 > 70.\n$$\n\nIl paziente è dunque sopra soglia? Il confronto aritmetico è corretto, ma non esaurisce il problema. Ogni punteggio psicometrico contiene errore di misura; due punti sopra il cut-off non autorizzano, da soli, una conclusione diagnostica netta.\n\nIn questo capitolo formuleremo una domanda più precisa:\n\n::: {.callout-note title=\"La domanda sul punteggio vero\" icon=false}\nDato il punteggio osservato $X = 72$, quale probabilità attribuisce il modello all'evento che il **punteggio vero** del paziente, indicato con $\\theta$, superi la soglia di 70?\n\n$$\nP(\\theta > 70 \\mid X = 72).\n$$\n:::\n\nQuesta domanda riguarda l'incertezza sul livello latente misurato dal test. Non equivale ancora alla domanda diagnostica complessiva, che richiede altre informazioni cliniche e una regola decisionale.\n\n::: {.callout-warning title=\"Una cautela sul cut-off\" icon=false}\nNella pratica, molti cut-off sono definiti e validati sui **punteggi osservati**, non direttamente sui punteggi veri latenti. Confrontare $\\theta$ con lo stesso valore numerico del cut-off è quindi una scelta modellistica utile a scopo didattico, ma deve essere giustificata nell'applicazione reale. Il capitolo mostra il meccanismo inferenziale; non propone una procedura diagnostica universale.\n:::\n\n## Il punteggio osservato non è il punteggio vero {#sec-punteggio-osservato-vero}\n\nNella teoria classica dei test, il punteggio osservato $X$ viene rappresentato come:\n\n$$\nX = \\theta + \\varepsilon,\n$$\n\ndove:\n\n- $\\theta$ è il **punteggio vero** postulato dal modello, cioè la componente stabile e sistematica della misurazione;\n- $\\varepsilon$ è l'**errore di misura**, cioè la componente accidentale della singola somministrazione.\n\nIl termine *punteggio vero* non va interpretato in senso ontologico. Nel nostro esempio, $\\theta$ non è \"la depressione reale\" del paziente in senso assoluto. È il valore latente che il modello del test cerca di stimare separando la componente stabile dalle fluttuazioni della misurazione.\n\nL'**attendibilità** $\\rho$ è definita come la proporzione della varianza osservata attribuibile ai punteggi veri:\n\n$$\n\\rho = \\frac{\\sigma_\\theta^2}{\\sigma_X^2}.\n$$\n\nSotto le assunzioni della teoria classica dei test,\n\n$$\n\\sigma_\\theta^2 = \\rho\\sigma_X^2,\n\\qquad\n\\sigma_e^2 = (1-\\rho)\\sigma_X^2.\n$$\n\nLa radice quadrata di $\\sigma_e^2$ è l'errore standard della misura (*standard error of measurement*, SEM):\n\n$$\n\\text{SEM} = \\sigma_X\\sqrt{1-\\rho}.\n$$\n\n## Il contesto numerico {#sec-contesto-numerico}\n\nUseremo lo stesso scenario in tutto il capitolo:\n\n- media normativa: $\\mu_X = 70$;\n- deviazione standard osservata nella popolazione normativa: $\\sigma_X = 15$;\n- attendibilità: $\\rho = 0.85$;\n- punteggio osservato: $X = 72$;\n- soglia: $c = 70$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmu_pop  <- 70\nsigma_X <- 15\nrho     <- 0.85\nX_obs   <- 72\ncut_off <- 70\n\nsigma_theta2 <- rho * sigma_X^2\nsigma_e2     <- (1 - rho) * sigma_X^2\n\nsigma_theta <- sqrt(sigma_theta2)\nsigma_e     <- sqrt(sigma_e2)\n\ncat(\"DS dei punteggi veri:\", round(sigma_theta, 2), \"\\n\")\n#> DS dei punteggi veri: 13.8\ncat(\"Errore standard della misura:\", round(sigma_e, 2), \"\\n\")\n#> Errore standard della misura: 5.81\n```\n:::\n\n\nIl SEM è circa 5.81 punti. Ciò non significa che ogni misurazione sbagli esattamente di questa quantità. Significa che, nel modello, le ripetizioni del test attorno allo stesso punteggio vero presentano una deviazione standard pari a circa 5.81.\n\n## Prior, modello di misura e posterior {#sec-prior-likelihood-posterior-paziente}\n\nIl caso del singolo paziente permette di dare un significato sostantivo ai tre elementi dell'aggiornamento bayesiano.\n\n### Il prior: cosa sappiamo prima del punteggio individuale\n\nPrima di osservare $X=72$, il modello descrive come sono distribuiti i punteggi veri nella popolazione normativa:\n\n$$\n\\theta \\sim \\mathcal{N}(\\mu_X,\\sigma_\\theta^2).\n$$\n\nNel nostro esempio:\n\n$$\n\\theta \\sim \\mathcal{N}(70,\\rho\\cdot15^2).\n$$\n\nIl prior non afferma che il paziente \"sia medio\". Esprime che, prima di usare il suo punteggio, i valori vicini alla media normativa sono più frequenti nel modello rispetto ai valori estremi.\n\n### Il modello di misura: quali punteggi può produrre un dato $\\theta$\n\nCondizionatamente al punteggio vero, una singola somministrazione è modellata come:\n\n$$\nX\\mid\\theta \\sim \\mathcal{N}(\\theta,\\sigma_e^2).\n$$\n\nQuesta distribuzione risponde alla domanda:\n\n> Se il punteggio vero fosse $\\theta$, quali punteggi osservati potrebbe produrre il test a causa dell'errore di misura?\n\nDopo avere osservato $X=72$, la stessa funzione, considerata come funzione di $\\theta$, costituisce la likelihood. Non è una distribuzione a priori sui possibili valori di $\\theta$: misura quanto ciascun valore di $\\theta$ rende compatibile il punteggio osservato.\n\n### La posterior: combinare informazione normativa e punteggio individuale\n\nL'aggiornamento è:\n\n$$\np(\\theta\\mid X)\n\\propto\np(X\\mid\\theta)p(\\theta).\n$$\n\nPoiché prior e modello di misura sono normali, anche la posterior è normale:\n\n$$\n\\theta\\mid X\n\\sim\n\\mathcal{N}(\\mu_{\\text{post}},\\sigma_{\\text{post}}^2),\n$$\n\ncon\n\n$$\n\\sigma_{\\text{post}}^2\n=\n\\left(\n\\frac{1}{\\sigma_\\theta^2}\n+\n\\frac{1}{\\sigma_e^2}\n\\right)^{-1},\n$$\n\n$$\n\\mu_{\\text{post}}\n=\n\\sigma_{\\text{post}}^2\n\\left(\n\\frac{\\mu_X}{\\sigma_\\theta^2}\n+\n\\frac{X}{\\sigma_e^2}\n\\right).\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsigma_post2 <- 1 / (1 / sigma_theta2 + 1 / sigma_e2)\nsigma_post  <- sqrt(sigma_post2)\n\nmu_post <- sigma_post2 *\n  (mu_pop / sigma_theta2 + X_obs / sigma_e2)\n\ncat(\"Media a posteriori:\", round(mu_post, 2), \"\\n\")\n#> Media a posteriori: 71.7\ncat(\"DS a posteriori:\", round(sigma_post, 2), \"\\n\")\n#> DS a posteriori: 5.36\n```\n:::\n\n\nLa distribuzione a posteriori è quindi:\n\n$$\n\\theta\\mid X=72\n\\sim\n\\mathcal{N}(71.7, 5.36^2).\n$$\n\n| Elemento | Distribuzione | Significato sostantivo |\n|---|---|---|\n| Prior | $p(\\theta)$ | distribuzione normativa dei punteggi veri prima di osservare il paziente |\n| Modello di misura | $p(X\\mid\\theta)$ | variabilità delle misurazioni che un dato punteggio vero può generare |\n| Posterior | $p(\\theta\\mid X)$ | incertezza aggiornata sul punteggio vero del paziente dopo $X=72$ |\n\n## Kelley come media a posteriori {#sec-kelley-shrinkage}\n\nLa formula classica di @Kelley1923 per stimare il punteggio vero è:\n\n$$\n\\hat\\theta_{\\text{Kelley}}\n=\n\\rho X+(1-\\rho)\\mu_X.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_kelley <- rho * X_obs + (1 - rho) * mu_pop\ncat(\"Stima di Kelley:\", round(theta_kelley, 2), \"\\n\")\n#> Stima di Kelley: 71.7\n```\n:::\n\n\nNel modello adottato, la media a posteriori coincide con la stima di Kelley:\n\n$$\n\\mu_{\\text{post}}\n=\n\\rho X+(1-\\rho)\\mu_X.\n$$\n\nPer il nostro paziente:\n\n$$\n0.85\\times72+0.15\\times70=71.7.\n$$\n\nL'attendibilità determina il peso del punteggio osservato:\n\n- se $\\rho$ è alta, il punteggio osservato riceve molto peso;\n- se $\\rho$ è bassa, il punteggio osservato è considerato più rumoroso e la stima viene corretta maggiormente verso la media normativa.\n\nQuesto spostamento è una forma di *shrinkage*. Non è una penalizzazione arbitraria del paziente: deriva dalla combinazione tra frequenza normativa dei punteggi veri e precisione della misurazione.\n\nAnche la deviazione standard posterior assume una forma semplice:\n\n$$\n\\sigma_{\\text{post}}\n=\n\\sigma_X\\sqrt{\\rho(1-\\rho)}.\n$$\n\nQuesta quantità coincide con l'errore standard dell'errore di stima usato nella formulazione classica di Kelley. La coincidenza riguarda questo specifico modello e le sue assunzioni; non rende equivalenti in generale inferenza frequentista e inferenza bayesiana.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Prior normativo, likelihood riscalata e posterior del punteggio vero. La posterior combina la distribuzione normativa con l'informazione fornita dal punteggio osservato.](07_singolo_paziente_files/figure-html/fig-single-patient-prior-likelihood-posterior-1.png){#fig-single-patient-prior-likelihood-posterior fig-align='center' fig-alt='Tre curve mostrano il prior normativo, la likelihood riscalata centrata sul punteggio osservato 72 e la posterior del punteggio vero, più concentrata e centrata tra prior e osservazione.' width=85%}\n:::\n:::\n\n\n::: {.callout-note title=\"La likelihood nel grafico\" icon=false}\nLa likelihood è stata moltiplicata per una costante per renderla visibile accanto alle due densità. Questo riscalamento non cambia la posterior, perché nella relazione $p(\\theta\\mid X)\\propto p(X\\mid\\theta)p(\\theta)$ qualsiasi costante comune viene eliminata dalla normalizzazione.\n:::\n\n## La probabilità di superare la soglia {#sec-domanda-clinica-diretta}\n\nLa posterior consente di calcolare direttamente:\n\n$$\nP(\\theta>c\\mid X)\n=\n1-\\Phi\\left(\n\\frac{c-\\mu_{\\text{post}}}{\\sigma_{\\text{post}}}\n\\right),\n$$\n\ndove $\\Phi$ è la funzione di ripartizione della normale standard.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_sopra_cutoff <- 1 - pnorm(\n  cut_off,\n  mean = mu_post,\n  sd = sigma_post\n)\n\nIC_post <- qnorm(\n  c(.025, .975),\n  mean = mu_post,\n  sd = sigma_post\n)\n\ncat(\n  \"P(theta > 70 | X = 72):\",\n  round(prob_sopra_cutoff * 100, 1), \"%\\n\"\n)\n#> P(theta > 70 | X = 72): 62.5 %\ncat(\n  \"Intervallo di credibilità al 95%: [\",\n  round(IC_post[1], 1), \", \",\n  round(IC_post[2], 1), \"]\\n\",\n  sep = \"\"\n)\n#> Intervallo di credibilità al 95%: [61.2, 82.2]\n```\n:::\n\n\nNel modello, la probabilità che il punteggio vero superi la soglia è circa **62.5%**. Il superamento è quindi più plausibile del non superamento, ma l'incertezza rimane sostanziale.\n\nL'intervallo di credibilità al 95% è [61.2, 82.2]. Condizionatamente al modello, ai parametri normativi, all'attendibilità assunta e al punteggio osservato, la posterior assegna il 95% della propria probabilità a questo intervallo.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Posterior del punteggio vero. L'area a destra della soglia rappresenta P(θ > 70 | X = 72).](07_singolo_paziente_files/figure-html/fig-single-patient-threshold-probability-1.png){#fig-single-patient-threshold-probability fig-align='center' fig-alt='Curva della distribuzione a posteriori del punteggio vero con una linea tratteggiata sulla soglia 70, una linea puntinata sul punteggio osservato 72 e l\\'area a destra di 70 evidenziata.' width=85%}\n:::\n:::\n\n\n::: {.callout-important title=\"Che cosa significa il 62%?\" icon=false}\nIl valore non significa che il paziente abbia una probabilità del 62% di \"essere depresso\". Significa che, sotto il modello specificato, il 62% della distribuzione a posteriori del punteggio vero si trova sopra la soglia numerica di 70. Il passaggio da questa quantità a una diagnosi richiede validità diagnostica del test, informazioni cliniche aggiuntive e una regola decisionale.\n:::\n\n## Posterior e predittiva: due oggetti diversi {#sec-posterior-predittiva}\n\nLa posterior sul punteggio vero risponde a:\n\n> Quali valori di $\\theta$ sono plausibili per questo paziente dopo avere osservato $X=72$?\n\nUna domanda diversa è:\n\n> Se ripetessimo il test, quale nuovo punteggio osservato $\\tilde X$ potremmo ottenere?\n\nLa risposta è la distribuzione predittiva a posteriori:\n\n$$\np(\\tilde X\\mid X)\n=\n\\int p(\\tilde X\\mid\\theta)p(\\theta\\mid X)\\,d\\theta.\n$$\n\nNel modello Normale-Normale:\n\n$$\n\\tilde X\\mid X\n\\sim\n\\mathcal{N}\n\\left(\n\\mu_{\\text{post}},\n\\sigma_{\\text{post}}^2+\\sigma_e^2\n\\right).\n$$\n\nLa varianza predittiva comprende:\n\n1. l'incertezza residua sul punteggio vero;\n2. un nuovo errore di misura nella seconda somministrazione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsigma_pred <- sqrt(sigma_post2 + sigma_e2)\n\nIC_pred <- qnorm(\n  c(.025, .975),\n  mean = mu_post,\n  sd = sigma_pred\n)\n\nprob_pred_sopra <- 1 - pnorm(\n  cut_off,\n  mean = mu_post,\n  sd = sigma_pred\n)\n\ncat(\"DS predittiva:\", round(sigma_pred, 2), \"\\n\")\n#> DS predittiva: 7.9\ncat(\n  \"Intervallo predittivo al 95%: [\",\n  round(IC_pred[1], 1), \", \",\n  round(IC_pred[2], 1), \"]\\n\",\n  sep = \"\"\n)\n#> Intervallo predittivo al 95%: [56.2, 87.2]\ncat(\n  \"P(X nuovo > 70 | X = 72):\",\n  round(prob_pred_sopra * 100, 1), \"%\\n\"\n)\n#> P(X nuovo > 70 | X = 72): 58.5 %\n```\n:::\n\n\nLa probabilità che una **nuova misurazione osservata** superi 70 è circa 58.5%, diversa da $P(\\theta>70\\mid X)$ perché riguarda un oggetto diverso e include un nuovo errore di misura.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Posterior del punteggio vero e distribuzione predittiva di una nuova somministrazione. La predittiva è più ampia perché include anche un nuovo errore di misura.](07_singolo_paziente_files/figure-html/fig-single-patient-posterior-predictive-1.png){#fig-single-patient-posterior-predictive fig-align='center' fig-alt='Due curve con lo stesso centro confrontano la posterior del punteggio vero, più stretta, e la distribuzione predittiva del nuovo punteggio osservato, più ampia. Una linea verticale indica la soglia 70.' width=85%}\n:::\n:::\n\n\n| Domanda | Distribuzione rilevante | Fonte di variabilità |\n|---|---|---|\n| Qual è il punteggio vero? | $p(\\theta\\mid X)$ | incertezza residua su $\\theta$ |\n| Quale punteggio osserveremo ripetendo il test? | $p(\\tilde X\\mid X)$ | incertezza su $\\theta$ + nuovo errore di misura |\n\n## L'attendibilità modifica sia la stima sia l'incertezza {#sec-sensibilita-attendibilita}\n\nA parità di punteggio osservato, una maggiore attendibilità:\n\n- assegna più peso a $X$ nella media posterior;\n- riduce la dispersione posterior;\n- riduce la variabilità predittiva di una nuova somministrazione.\n\nLa tabella seguente mantiene invariati $X=72$, $\\mu_X=70$ e $\\sigma_X=15$ e modifica soltanto $\\rho$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nposterior_by_reliability <- function(rho_value) {\n  mu_post_value <- rho_value * X_obs +\n    (1 - rho_value) * mu_pop\n\n  sd_post_value <- sigma_X *\n    sqrt(rho_value * (1 - rho_value))\n\n  sd_pred_value <- sqrt(\n    sd_post_value^2 +\n      (1 - rho_value) * sigma_X^2\n  )\n\n  data.frame(\n    attendibilita = rho_value,\n    media_posterior = mu_post_value,\n    ds_posterior = sd_post_value,\n    prob_theta_sopra = 1 - pnorm(\n      cut_off,\n      mu_post_value,\n      sd_post_value\n    ),\n    ds_predittiva = sd_pred_value,\n    prob_nuovo_sopra = 1 - pnorm(\n      cut_off,\n      mu_post_value,\n      sd_pred_value\n    )\n  )\n}\n\nreliability_table <- do.call(\n  rbind,\n  lapply(c(.60, .85, .95), posterior_by_reliability)\n)\n\nreliability_table |>\n  mutate(\n    attendibilita = sprintf(\"%.2f\", attendibilita),\n    media_posterior = sprintf(\"%.2f\", media_posterior),\n    ds_posterior = sprintf(\"%.2f\", ds_posterior),\n    prob_theta_sopra = sprintf(\"%.1f%%\", 100 * prob_theta_sopra),\n    ds_predittiva = sprintf(\"%.2f\", ds_predittiva),\n    prob_nuovo_sopra = sprintf(\"%.1f%%\", 100 * prob_nuovo_sopra)\n  ) |>\n  setNames(c(\n    \"Attendibilità\",\n    \"Media posterior\",\n    \"DS posterior\",\n    \"P(theta > 70 | X)\",\n    \"DS predittiva\",\n    \"P(X nuovo > 70 | X)\"\n  )) |>\n  tt(caption = \"Effetto dell'attendibilità sull'inferenza per il singolo paziente\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_p81mcoyff7iuvuzjz95o = TinyTable.createTableFunctions(\"tinytable_p81mcoyff7iuvuzjz95o\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '3', j: 1 }, { i: '3', j: 2 }, { i: '3', j: 3 }, { i: '3', j: 4 }, { i: '3', j: 5 }, { i: '3', j: 6 } ], css_id: 'tinytable_css_7dshabs15v4ek8i83mdj',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 } ], css_id: 'tinytable_css_tn7eeslfd3vn5rzdgs54',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_p81mcoyff7iuvuzjz95o.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_p81mcoyff7iuvuzjz95o td.tinytable_css_7dshabs15v4ek8i83mdj, #tinytable_p81mcoyff7iuvuzjz95o th.tinytable_css_7dshabs15v4ek8i83mdj {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_p81mcoyff7iuvuzjz95o td.tinytable_css_tn7eeslfd3vn5rzdgs54, #tinytable_p81mcoyff7iuvuzjz95o th.tinytable_css_tn7eeslfd3vn5rzdgs54 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_p81mcoyff7iuvuzjz95o\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Effetto dell'attendibilità sull'inferenza per il singolo paziente</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">Attendibilità</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Media posterior</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">DS posterior</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">P(theta > 70 | X)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">DS predittiva</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">P(X nuovo > 70 | X)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">0.60</td>\n                  <td data-row=\"1\" data-col=\"2\">71.20</td>\n                  <td data-row=\"1\" data-col=\"3\">7.35</td>\n                  <td data-row=\"1\" data-col=\"4\">56.5%</td>\n                  <td data-row=\"1\" data-col=\"5\">12.00</td>\n                  <td data-row=\"1\" data-col=\"6\">54.0%</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">0.85</td>\n                  <td data-row=\"2\" data-col=\"2\">71.70</td>\n                  <td data-row=\"2\" data-col=\"3\">5.36</td>\n                  <td data-row=\"2\" data-col=\"4\">62.5%</td>\n                  <td data-row=\"2\" data-col=\"5\">7.90</td>\n                  <td data-row=\"2\" data-col=\"6\">58.5%</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">0.95</td>\n                  <td data-row=\"3\" data-col=\"2\">71.90</td>\n                  <td data-row=\"3\" data-col=\"3\">3.27</td>\n                  <td data-row=\"3\" data-col=\"4\">71.9%</td>\n                  <td data-row=\"3\" data-col=\"5\">4.68</td>\n                  <td data-row=\"3\" data-col=\"6\">65.8%</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nLa tabella mostra perché l'attendibilità è un elemento sostantivo dell'interpretazione. Non modifica soltanto la larghezza di un intervallo: stabilisce quanto il singolo punteggio osservato possa spostare l'inferenza rispetto alla distribuzione normativa.\n\n::: {.callout-warning title=\"L'attendibilità non è necessariamente nota con certezza\" icon=false}\nIl capitolo tratta $\\rho$, $\\mu_X$ e $\\sigma_X$ come quantità note. Nella pratica sono stimate da campioni normativi, possono variare tra popolazioni e condizioni di somministrazione e possono non descrivere perfettamente il singolo paziente. Un modello più completo rappresenterebbe anche questa incertezza.\n:::\n\n## Dalla probabilità alla decisione {#sec-decisione-clinica}\n\nIl modello restituisce:\n\n$$\nP(\\theta>70\\mid X=72)\n\\approx\n0.62.\n$$\n\nQuesta probabilità non produce automaticamente una decisione. Per decidere occorre considerare almeno:\n\n- conseguenze di un falso positivo e di un falso negativo;\n- validità del cut-off rispetto all'obiettivo clinico;\n- prevalenza e contesto del problema;\n- informazioni provenienti da colloquio, anamnesi e altre misure;\n- possibilità di ripetere o integrare la valutazione.\n\n::: {.callout-note title=\"Una formulazione prudente\" icon=false}\nDato il modello psicometrico adottato e il punteggio osservato di 72, la distribuzione a posteriori assegna circa il 62.5% di probabilità a valori del punteggio vero superiori a 70. Il risultato segnala un'incertezza clinicamente rilevante e può motivare un approfondimento, ma non sostiene da solo una diagnosi.\n:::\n\nLa funzione dell'analisi bayesiana non è sostituire il giudizio clinico con un algoritmo. È separare con chiarezza:\n\n1. ciò che il test ha osservato;\n2. ciò che il modello inferisce sul punteggio vero;\n3. ciò che potrebbe accadere in una nuova misurazione;\n4. la decisione che si sceglie di prendere e i costi associati agli errori.\n\n## Sintesi operativa {#sec-sintesi-operativa}\n\n| Passaggio | Domanda | Risposta del modello |\n|---|---|---|\n| Prior | Prima del punteggio individuale, quali valori di $\\theta$ sono plausibili? | distribuzione normativa dei punteggi veri |\n| Modello di misura | Se $\\theta$ fosse noto, quali valori di $X$ potremmo osservare? | normale centrata in $\\theta$ con varianza di errore |\n| Posterior | Dopo $X=72$, quali valori di $\\theta$ sono plausibili? | normale centrata in 71.7 |\n| Probabilità di soglia | Quanta posterior cade sopra 70? | circa 62.5% |\n| Predittiva | Quale valore potremmo osservare ripetendo il test? | distribuzione più ampia, perché include nuovo errore |\n| Decisione | Che cosa conviene fare? | richiede probabilità, conseguenze e contesto clinico |\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nQuesto capitolo chiude la Parte applicando a un singolo caso gli oggetti introdotti nei capitoli precedenti.\n\nIl **prior** non è un'aggiunta astratta: descrive la distribuzione normativa dei punteggi veri prima di osservare il paziente. La **likelihood** traduce l'attendibilità del test in un modello concreto dell'errore di misura. Il loro prodotto produce la **posterior**, che quantifica l'incertezza residua sul punteggio vero del paziente. Integrando nuovamente sul parametro si ottiene la **distribuzione predittiva a posteriori** di una futura misurazione.\n\nNel modello Normale-Normale, la media posterior coincide con la stima classica di Kelley. Il contributo bayesiano non consiste dunque nel rigettare la psicometria classica, ma nel collocare la stima puntuale dentro una distribuzione completa e nel rendere direttamente formulabili domande come $P(\\theta>c\\mid X)$.\n\nIl risultato numerico non deve tuttavia essere sovrainterpretato. La probabilità che il punteggio vero superi una soglia non è automaticamente la probabilità di una diagnosi, e un cut-off non sostituisce la validità del modello, la qualità della misura o il giudizio clinico. L'inferenza bayesiana rende l'incertezza esplicita; non la elimina.\n\n## Esercizi {.unnumbered .unlisted}\n\n### Esercizio 1 — Comprendere {.unnumbered .unlisted}\n\n*Codice: no · 10 minuti*\n\nPer il caso discusso nel capitolo, associa ciascuna domanda alla distribuzione corretta e spiega in una frase la scelta.\n\n1. Prima di conoscere il punteggio del paziente, quali punteggi veri sono plausibili nella popolazione normativa?\n2. Se il punteggio vero fosse 75, quali punteggi osservati potrebbe produrre il test?\n3. Dopo avere osservato $X=72$, quali punteggi veri sono plausibili per il paziente?\n4. Se il test venisse ripetuto, quali nuovi punteggi osservati sarebbero plausibili?\n\nLe distribuzioni disponibili sono:\n\n- $p(\\theta)$;\n- $p(X\\mid\\theta)$;\n- $p(\\theta\\mid X)$;\n- $p(\\tilde X\\mid X)$.\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nChiediti prima di tutto quale sia l'oggetto incerto in ciascuna domanda: il punteggio vero oppure un punteggio osservato.\n:::\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\n1. $p(\\theta)$: è il prior normativo sui punteggi veri prima del dato individuale.\n2. $p(X\\mid\\theta)$: descrive la variabilità delle misure osservate a punteggio vero fissato.\n3. $p(\\theta\\mid X)$: è la posterior sul punteggio vero dopo avere osservato il paziente.\n4. $p(\\tilde X\\mid X)$: è la predittiva a posteriori di una nuova misurazione.\n\nLa differenza decisiva è che posterior e prior riguardano $\\theta$, mentre modello di misura e predittiva riguardano punteggi osservabili.\n:::\n\n### Esercizio 2 — Prevedere {.unnumbered .unlisted}\n\n*Codice: no · 10 minuti*\n\nConfronta tre test che hanno la stessa media normativa, la stessa deviazione standard e lo stesso punteggio osservato $X=72$, ma attendibilità pari a 0.60, 0.85 e 0.95. Prima di rileggere la tabella del capitolo, prevedi che cosa accade aumentando l'attendibilità:\n\n1. alla media posterior;\n2. alla deviazione standard posterior;\n3. a $P(\\theta>70\\mid X)$;\n4. alla dispersione della predittiva di una nuova misurazione.\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nUna maggiore attendibilità significa che una quota maggiore della differenza tra 72 e la media normativa viene attribuita al punteggio vero e una quota minore all'errore.\n:::\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\nAumentando l'attendibilità:\n\n1. la media posterior si avvicina a 72, perché il punteggio osservato riceve più peso;\n2. la deviazione standard posterior diminuisce, perché resta meno incertezza sul punteggio vero;\n3. la probabilità che $\\theta$ superi 70 aumenta;\n4. la predittiva di una nuova misurazione diventa meno dispersa, perché diminuisce anche il nuovo errore di misura.\n\nQuesti cambiamenti non dipendono dal fatto che 72 sia \"più significativo\", ma dal diverso modello della qualità della misura.\n:::\n\n### Esercizio 3 — Modificare {.unnumbered .unlisted}\n\n*Codice: no · 10–15 minuti*\n\nMantieni invariati $\\mu_X=70$, $\\sigma_X=15$ e $\\rho=0.85$, ma considera tre punteggi osservati: 68, 72 e 80.\n\nSenza eseguire simulazioni:\n\n1. calcola la media posterior usando\n\n   $$\n   \\mu_{\\text{post}}=\\rho X+(1-\\rho)\\mu_X;\n   $$\n\n2. stabilisci per quale punteggio $P(\\theta>70\\mid X)$ sarà inferiore a 0.50, poco superiore a 0.50 oppure nettamente superiore a 0.50;\n3. spiega perché la deviazione standard posterior resta uguale nei tre casi.\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nCon $\\rho=0.85$, la media posterior è $0.85X+10.5$. La varianza posterior dipende da $\\rho$ e $\\sigma_X$, non dal valore particolare di $X$.\n:::\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\nLe medie posterior sono:\n\n- per $X=68$: $0.85\\times68+0.15\\times70=68.3$;\n- per $X=72$: $71.7$;\n- per $X=80$: $78.5$.\n\nPoiché tutte le posterior hanno la stessa deviazione standard:\n\n- con $X=68$, la media è sotto 70 e quindi $P(\\theta>70\\mid X)<0.50$;\n- con $X=72$, la media è poco sopra 70 e la probabilità è soltanto moderatamente superiore a 0.50;\n- con $X=80$, la media è molto sopra 70 e la probabilità è nettamente maggiore.\n\nLa dispersione non cambia perché, nel modello con varianze note, il valore osservato sposta il centro della posterior ma non la sua precisione.\n:::\n\n### Esercizio 4 — Criticare {.unnumbered .unlisted}\n\n*Codice: no · 10 minuti*\n\nUn referto afferma:\n\n> «Il paziente ha ottenuto 72, quindi è clinicamente depresso. L'analisi bayesiana conferma la diagnosi con una probabilità del 62%. Se il test venisse ripetuto, vi sarebbe ancora il 62% di probabilità di superare il cut-off.»\n\nIndividua almeno tre problemi e riscrivi il passaggio in una forma più corretta.\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nDistingui: punteggio osservato, punteggio vero, diagnosi e nuovo punteggio osservato.\n:::\n\n::: {.callout-note collapse=true title=\"Elementi per la risposta\"}\nIl passaggio contiene almeno quattro problemi:\n\n1. il superamento del cut-off osservato non equivale automaticamente a una diagnosi;\n2. il 62% riguarda $P(\\theta>70\\mid X=72)$ sotto uno specifico modello, non la probabilità che il paziente abbia il disturbo;\n3. il risultato dipende dall'attendibilità e dai parametri normativi assunti;\n4. la probabilità che una nuova misurazione superi 70 deriva dalla predittiva ed è diversa, nel nostro esempio circa 58.5%.\n\nUna formulazione possibile è:\n\n> «Dato il modello psicometrico adottato e il punteggio osservato di 72, la distribuzione a posteriori assegna circa il 62.5% di probabilità a punteggi veri superiori a 70. Questa quantità non coincide con la probabilità di una diagnosi e deve essere integrata con altre informazioni cliniche. Il modello predice inoltre una probabilità di circa 58.5% che una nuova somministrazione superi la stessa soglia.»\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.5.2\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.0            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.0           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] S7_0.2.2              fastmap_1.2.0         tensorA_0.36.2.1     \n#>  [7] digest_0.6.39         timechange_0.4.0      estimability_2.0.0   \n#> [10] lifecycle_1.0.5       magrittr_2.0.5        compiler_4.6.1       \n#> [13] rlang_1.3.0           tools_4.6.1           yaml_2.3.12          \n#> [16] knitr_1.51            labeling_0.4.3        bridgesampling_1.2-1 \n#> [19] htmlwidgets_1.6.4     pkgbuild_1.4.8        curl_7.1.0           \n#> [22] RColorBrewer_1.1-3    abind_1.4-8           purrr_1.2.2          \n#> [25] grid_4.6.1            stats4_4.6.1          xtable_1.8-8         \n#> [28] inline_0.3.21         emmeans_2.0.4         scales_1.4.0         \n#> [31] cli_3.6.6             mvtnorm_1.4-2         rmarkdown_2.31       \n#> [34] generics_0.1.4        otel_0.2.0            RcppParallel_5.1.11-2\n#> [37] cachem_1.1.0          stringr_1.6.0         parallel_4.6.1       \n#> [40] vctrs_0.7.3           V8_8.2.0              Matrix_1.7-5         \n#> [43] jsonlite_2.0.0        litedown_0.10         arrayhelpers_1.1-1   \n#> [46] glue_1.8.1            codetools_0.2-20      distributional_0.8.1 \n#> [49] lubridate_1.9.5       stringi_1.8.7         gtable_0.3.6         \n#> [52] QuickJSR_1.10.0       pillar_1.11.1         htmltools_0.5.9      \n#> [55] Brobdingnag_1.2-9     R6_2.6.1              textshaping_1.0.5    \n#> [58] rprojroot_2.1.1       evaluate_1.0.5        lattice_0.22-9       \n#> [61] backports_1.5.1       memoise_2.0.1         broom_1.0.13         \n#> [64] snakecase_0.11.1      rstantools_2.6.0      coda_0.19-4.1        \n#> [67] gridExtra_2.3.1       nlme_3.1-170          checkmate_2.3.4      \n#> [70] xfun_0.60             pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "07_singolo_paziente_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}