{
  "hash": "60bee1f25db1d4f31a00f61612e51730",
  "result": {
    "engine": "knitr",
    "markdown": "# Oltre il cut-off: inferenza bayesiana sul singolo paziente {#sec-bayesian-inference-single-patient-cutoff}\n\n::: {.callout-important appearance=\"minimal\" .chapter-status}\n**Da sapere.** Un punteggio osservato non coincide con il punteggio vero postulato dal modello psicometrico: è una singola misurazione e contiene errore. Nel modello Normale-Normale, la distribuzione normativa dei punteggi veri costituisce il prior, il modello dell'errore di misura descrive come nasce il punteggio osservato e il loro aggiornamento produce una distribuzione a posteriori sul punteggio vero del singolo paziente.\n\n**Da saper fare.** Interpretare prior, likelihood, posterior e distribuzione predittiva nel caso di un singolo paziente; riconoscere la stima di Kelley come media a posteriori nel modello adottato; interpretare $P(\\theta>c\\mid X)$ senza trasformarla automaticamente in una diagnosi; distinguere l'incertezza sul punteggio vero dalla variabilità di una nuova somministrazione.\n\n**Approfondimento facoltativo.** Le formule del modello Normale-Normale, l'equivalenza algebrica tra Kelley e la media a posteriori, l'analisi di sensibilità rispetto all'attendibilità e la formulazione delle decisioni mediante funzioni di perdita possono essere rimandate in una prima lettura.\n\n[Che cosa significano queste etichette?](../../guida-al-manuale.qmd#sec-percorsi-lettura)\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Prerequisiti\"}\n\n- Sono dati per noti l’equilibrio tra prior e dati del capitolo 11 e la distribuzione predittiva a posteriori del capitolo 13.\n- È utile conoscere la distribuzione normale e i concetti di affidabilità, errore standard di misurazione e punteggio vero.\n- L'@sec-measurement-error-method-appendix offre un approfondimento sull’errore di misurazione e sulla varianza di metodo; il codice R è facoltativo.\n\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |>\n  source()\n```\n:::\n\n:::\n\n## Quando due punti sembrano una diagnosi {#sec-vignetta-clinica}\n\nImmaginiamo che un clinico somministri un test standardizzato per la sintomatologia depressiva. Il manuale indica un *cut-off* operativo pari a 70 e il paziente ottiene 72.\n\nLa lettura più immediata è:\n\n$$\n72>70.\n$$\n\nIl confronto aritmetico è corretto. Il problema nasce quando lo si trasforma senza altri passaggi in una conclusione clinica: «il paziente è sopra soglia, dunque presenta il disturbo». Questo modo di ragionare è attraente perché converte una misura continua e incerta in una decisione netta. Ma il punteggio di 72 è soltanto *una realizzazione osservata di un processo di misurazione imperfetto*.\n\nL'alternativa bayesiana non consiste nell'ignorare il cut-off. Consiste nel porre una domanda più precisa:\n\n::: {.callout-note title=\"La domanda inferenziale\" icon=false}\nDato il punteggio osservato $X=72$, quale probabilità attribuisce il modello all'evento che il **punteggio vero** del paziente, indicato con $\\theta$, superi la soglia di 70?\n\n$$\nP(\\theta>70\\mid X=72).\n$$\n:::\n\nQuesta domanda rende esplicita l'incertezza sul livello latente che il test cerca di misurare. Non coincide ancora con la probabilità di una diagnosi: per arrivare a una decisione clinica sono necessarie la validità diagnostica dello strumento, altre informazioni sul paziente e una valutazione delle conseguenze degli errori possibili.\n\n::: {.callout-warning title=\"Cut-off osservato e soglia sul tratto latente\" icon=false}\n\nNella pratica, i cut-off sono spesso definiti sui **punteggi osservati**. Una regola come $X>70$ può essere stata validata come criterio operativo di screening o classificazione, ma ciò non significa che il punteggio osservato coincida con il livello vero del paziente o che l’errore di misura possa essere ignorato.\n\nIl confronto $P(\\theta>70\\mid X=72)$ pone una domanda diversa: quanto è plausibile che il tratto latente $\\theta$ superi la soglia $70$, dato il punteggio osservato? Perché questa domanda sia sostantivamente corretta, occorre giustificare che la stessa soglia numerica abbia un significato interpretabile anche sulla scala latente.\n\nNel presente capitolo questa corrispondenza viene assunta a scopo didattico, per mostrare come l’incertezza di misurazione possa essere incorporata nell’inferenza sul singolo caso. Non si propone quindi di sostituire automaticamente i cut-off validati con una soglia sul punteggio vero, né di fornire una procedura diagnostica universale.\n:::\n\n### Dal punteggio osservato al punteggio vero {#sec-punteggio-osservato-vero}\n\nNella teoria classica dei test, il punteggio osservato è rappresentato come\n\n$$\nX=\\theta+\\varepsilon,\n$$\ndove $\\theta$ è la componente stabile e sistematica postulata dal modello e $\\varepsilon$ è l'errore accidentale della singola somministrazione.\n\nIl termine *punteggio vero* non va inteso in senso ontologico. Nel nostro esempio, $\\theta$ non è «la depressione reale» del paziente in senso assoluto. È la quantità latente che il modello psicometrico cerca di separare dalle fluttuazioni della misura.\n\nL'**attendibilità** $\\rho$ esprime la proporzione della varianza osservata attribuibile ai punteggi veri:\n\n$$\n\\rho=\\frac{\\sigma_\\theta^2}{\\sigma_X^2}.\n$$\n\nSotto le assunzioni della teoria classica dei test,\n\n$$\n\\sigma_\\theta^2=\\rho\\sigma_X^2,\n\\qquad\n\\sigma_e^2=(1-\\rho)\\sigma_X^2.\n$$\n\nLa radice quadrata di $\\sigma_e^2$ è l'errore standard della misura (*standard error of measurement*, SEM):\n\n$$\n\\text{SEM}=\\sigma_X\\sqrt{1-\\rho}.\n$$\n\n### Il caso che seguiremo {#sec-contesto-numerico}\n\nUseremo lo stesso scenario in tutto il capitolo:\n\n- media normativa: $\\mu_X=70$;\n- deviazione standard osservata nella popolazione normativa: $\\sigma_X=15$;\n- attendibilità: $\\rho=0.85$;\n- punteggio osservato: $X=72$;\n- soglia: $c=70$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmu_pop  <- 70\nsigma_X <- 15\nrho     <- 0.85\nX_obs   <- 72\ncut_off <- 70\n\nsigma_theta2 <- rho * sigma_X^2\nsigma_e2     <- (1 - rho) * sigma_X^2\n\nsigma_theta <- sqrt(sigma_theta2)\nsigma_e     <- sqrt(sigma_e2)\n\ncat(\"DS dei punteggi veri:\", round(sigma_theta, 2), \"\\n\")\n#> DS dei punteggi veri: 13.8\ncat(\"Errore standard della misura:\", round(sigma_e, 2), \"\\n\")\n#> Errore standard della misura: 5.81\n```\n:::\n\n\nIl SEM è circa 5.81 punti. Ciò non significa che ogni misurazione sbagli esattamente di questa quantità. Significa che, nel modello, le ripetizioni del test attorno allo stesso punteggio vero hanno una deviazione standard di circa 5.81 punti. Il valore osservato è quindi informativo, ma non corrisponde perfettamente al livello latente.\n\n## Costruire l'inferenza sul singolo paziente {#sec-prior-likelihood-posterior-paziente}\n\nIl caso del singolo paziente ha il vantaggio di rendere concreti i tre elementi dell'aggiornamento bayesiano. Questi elementi non sono concetti astratti, ma descrivono ciò che sappiamo prima del test, il funzionamento della misurazione e le conclusioni che possiamo trarre osservando il risultato.\n\n**Prima del punteggio individuale: il prior normativo.** La distribuzione dei punteggi veri nella popolazione di riferimento è modellata come\n\n$$\n\\theta\\sim\\mathcal{N}(\\mu_X,\\sigma_\\theta^2).\n$$\n\nNel nostro esempio,\n\n$$\n\\theta\\sim\\mathcal{N}(70,\\rho\\cdot15^2).\n$$\n\nIl prior non afferma che il paziente «sia medio». Piuttosto, esprime l'idea che, prima di utilizzare il punteggio individuale, i valori vicini alla media normativa sono più frequenti nel modello rispetto a quelli estremi.\n\n**Come nasce il punteggio osservato: il modello di misura.** Condizionatamente al punteggio vero,\n\n$$\nX\\mid\\theta\\sim\\mathcal{N}(\\theta,\\sigma_e^2).\n$$\n\nLa distribuzione risponde alla domanda: se il punteggio vero fosse $\\theta$, quali valori osservati potrebbe produrre il test a causa dell'errore di misura? Dopo che è stato osservato il valore $X=72$, la stessa espressione, letta come funzione di $\\theta$, diventa la funzione di verosimiglianza. Essa misura quanto ciascun valore candidato di $\\theta$ sia compatibile con il punteggio ottenuto.\n\n**Dopo il punteggio: la posterior.** Il prior normativo e la likelihood vengono combinati mediante\n\n$$\np(\\theta\\mid X)\\propto p(X\\mid\\theta)p(\\theta).\n$$\n\nIl risultato non è un nuovo verdetto binario, ma una distribuzione completa sui valori plausibili del punteggio vero.\n\n::: {.callout-note collapse=\"true\" title=\"Le formule del modello Normale-Normale\"}\n\nPoiché prior e modello di misura sono normali, anche la posterior è normale:\n\n$$\n\\theta\\mid X\n\\sim\n\\mathcal{N}(\\mu_{\\text{post}},\\sigma_{\\text{post}}^2),\n$$\n\ncon\n\n$$\n\\sigma_{\\text{post}}^2\n=\n\\left(\n\\frac{1}{\\sigma_\\theta^2}\n+\n\\frac{1}{\\sigma_e^2}\n\\right)^{-1},\n$$\n\ne\n\n$$\n\\mu_{\\text{post}}\n=\n\\sigma_{\\text{post}}^2\n\\left(\n\\frac{\\mu_X}{\\sigma_\\theta^2}\n+\n\\frac{X}{\\sigma_e^2}\n\\right).\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsigma_post2 <- 1 / (1 / sigma_theta2 + 1 / sigma_e2)\nsigma_post  <- sqrt(sigma_post2)\n\nmu_post <- sigma_post2 *\n  (mu_pop / sigma_theta2 + X_obs / sigma_e2)\n\ncat(\"Media a posteriori:\", round(mu_post, 2), \"\\n\")\n#> Media a posteriori: 71.7\ncat(\"DS a posteriori:\", round(sigma_post, 2), \"\\n\")\n#> DS a posteriori: 5.36\n```\n:::\n\n:::\n\nNel nostro caso,\n\n$$\n\\theta\\mid X=72\n\\sim\n\\mathcal{N}(71.7, 5.36^2).\n$$\n\nLa media della posterior è 71.7: il punteggio osservato di 72 sposta l'inferenza al di sopra della media normativa, ma non viene considerato come una misura priva di errore. La deviazione standard posterior, pari a circa 5.36, descrive l'incertezza che rimane sul punteggio vero.\n\n| Elemento | Distribuzione | Domanda sostantiva |\n|---|---|---|\n| Prior | $p(\\theta)$ | prima di osservare il paziente, quali punteggi veri sono plausibili? |\n| Modello di misura | $p(X\\mid\\theta)$ | a punteggio vero fissato, quali misure potrebbe produrre il test? |\n| Posterior | $p(\\theta\\mid X)$ | dopo $X=72$, quali punteggi veri sono plausibili per il paziente? |\n\n### Perché la stima si sposta verso la media {#sec-kelley-shrinkage}\n\nLa formula classica di @Kelley1923 per stimare il punteggio vero è\n\n$$\n\\hat\\theta_{\\text{Kelley}}\n=\n\\rho X+(1-\\rho)\\mu_X.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_kelley <- rho * X_obs + (1 - rho) * mu_pop\ncat(\"Stima di Kelley:\", round(theta_kelley, 2), \"\\n\")\n#> Stima di Kelley: 71.7\n```\n:::\n\n\nNel modello adottato, questa stima coincide esattamente con la media a posteriori:\n\n$$\n\\mu_{\\text{post}}\n=\n\\rho X+(1-\\rho)\\mu_X.\n$$\n\nPer il nostro paziente,\n\n$$\n0.85\\times72+0.15\\times70=71.7.\n$$\n\nLa formula rende evidente il ruolo dell'attendibilità. Se $\\rho$ è alta, il punteggio individuale riceve un peso maggiore. Se è bassa, il punteggio viene considerato più rumoroso e la stima si sposta maggiormente verso la media normativa.\n\nQuesto spostamento, detto *shrinkage*, non è una correzione punitiva né un modo per «normalizzare» il paziente. È il risultato della combinazione di due informazioni: la posizione del singolo punteggio e la precisione con cui è stato misurato. Un valore estremo ma poco attendibile fornisce meno informazioni su $\\theta$ rispetto a un valore estremo ottenuto con uno strumento molto preciso.\n\nAnche la deviazione standard posterior assume una forma semplice:\n\n$$\n\\sigma_{\\text{post}}\n=\n\\sigma_X\\sqrt{\\rho(1-\\rho)}.\n$$\n\nQuesta quantità coincide con l'errore standard dell'errore di stima nella formulazione classica di Kelley. Tale coincidenza vale per questo specifico modello e per le sue assunzioni, ma non rende equivalenti, in generale, l'inferenza frequentista e l'inferenza bayesiana.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Prior normativo, likelihood riscalata e posterior del punteggio vero. La posterior combina la distribuzione normativa con l'informazione fornita dal punteggio osservato.](07_singolo_paziente_files/figure-pdf/fig-single-patient-prior-likelihood-posterior-1.png){#fig-single-patient-prior-likelihood-posterior fig-align='center' fig-alt='Tre curve mostrano il prior normativo, la likelihood riscalata centrata sul punteggio osservato 72 e la posterior del punteggio vero, più concentrata e centrata tra prior e osservazione.' width=85%}\n:::\n:::\n\n\nLa @fig-single-patient-prior-likelihood-posterior mostra l'intero aggiornamento. Il prior concentra maggiormente il peso vicino alla media, la likelihood favorisce i valori di $\\theta$ compatibili con il punteggio osservato e la posterior combina le due fonti risultando più concentrata.\n\n::: {.callout-note title=\"Perché la likelihood è riscalata nel grafico?\" icon=false}\nLa likelihood è stata moltiplicata per una costante per poterla visualizzare accanto alle due densità. Il riscalamento non cambia la posterior: nella relazione $p(\\theta\\mid X)\\propto p(X\\mid\\theta)p(\\theta)$ qualsiasi costante comune viene eliminata dalla normalizzazione.\n:::\n\n## Trasformare la posterior in una domanda clinica {#sec-domanda-clinica-diretta}\n\nUna volta ottenuta la posterior, non siamo obbligati a ridurla a una sola stima. Possiamo porre direttamente la domanda che aveva motivato il capitolo:\n\n$$\nP(\\theta>c\\mid X)\n=\n1-\\Phi\\left(\n\\frac{c-\\mu_{\\text{post}}}{\\sigma_{\\text{post}}}\n\\right),\n$$\n\ndove $\\Phi$ è la funzione di ripartizione della normale standard.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_sopra_cutoff <- 1 - pnorm(\n  cut_off,\n  mean = mu_post,\n  sd = sigma_post\n)\n\nIC_post <- qnorm(\n  c(.025, .975),\n  mean = mu_post,\n  sd = sigma_post\n)\n\ncat(\n  \"P(theta > 70 | X = 72):\",\n  round(prob_sopra_cutoff * 100, 1), \"%\\n\"\n)\n#> P(theta > 70 | X = 72): 62.5 %\ncat(\n  \"Intervallo di credibilità al 95%: [\",\n  round(IC_post[1], 1), \", \",\n  round(IC_post[2], 1), \"]\\n\",\n  sep = \"\"\n)\n#> Intervallo di credibilità al 95%: [61.2, 82.2]\n```\n:::\n\n\nNel modello, la probabilità che il punteggio vero superi la soglia è di circa **62.5%**. Il superamento è dunque più plausibile del non superamento, ma l'incertezza resta sostanziale. La posterior non trasforma il punteggio di 72 in una certezza, ma quantifica quanto l'evidenza disponibile sostenga i valori sopra e sotto la soglia.\n\nL'intervallo di credibilità al 95% è [61.2, 82.2]. Condizionatamente al modello, ai parametri normativi, all'attendibilità assunta e al punteggio osservato, il 95% della probabilità a posteriori si colloca in questo intervallo.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Posterior del punteggio vero. L'area a destra della soglia rappresenta P(θ > 70 | X = 72).](07_singolo_paziente_files/figure-pdf/fig-single-patient-threshold-probability-1.png){#fig-single-patient-threshold-probability fig-align='center' fig-alt='Curva della distribuzione a posteriori del punteggio vero con una linea tratteggiata sulla soglia 70, una linea puntinata sul punteggio osservato 72 e l\\'area a destra di 70 evidenziata.' width=85%}\n:::\n:::\n\n\nLa @fig-single-patient-threshold-probability rende visibile l'interpretazione: la soglia divide la posterior in due aree e la probabilità richiesta è l'area a destra di 70.\n\n::: {.callout-important title=\"Che cosa significa il 62.5%?\" icon=false}\nCiò non significa che il paziente abbia una probabilità del 62.5% di «essere depresso». Significa che, secondo il modello specifico, questa quota della distribuzione a posteriori **del punteggio vero** si colloca al di sopra della soglia numerica di 70. Per passare da questa quantità a una diagnosi sono necessarie la validità diagnostica, informazioni cliniche aggiuntive e una regola decisionale.\n:::\n\n### Stimare il tratto e prevedere una nuova misura non sono la stessa cosa {#sec-posterior-predittiva}\n\nLa posterior risponde alla domanda:\n\n> Quali valori di $\\theta$ sono plausibili per questo paziente dopo avere osservato $X=72$?\n\nUna domanda diversa riguarda ciò che vedremmo ripetendo il test:\n\n> Quale nuovo punteggio osservato $\\tilde X$ potremmo ottenere?\n\nLa risposta è la distribuzione predittiva a posteriori:\n\n$$\np(\\tilde X\\mid X)\n=\n\\int p(\\tilde X\\mid\\theta)p(\\theta\\mid X)\\,d\\theta.\n$$\n\nNel modello Normale-Normale,\n\n$$\n\\tilde X\\mid X\n\\sim\n\\mathcal{N}\n\\left(\n\\mu_{\\text{post}},\n\\sigma_{\\text{post}}^2+\\sigma_e^2\n\\right).\n$$\n\nLa varianza predittiva contiene due fonti di incertezza: quella residua sul punteggio vero e un nuovo errore di misura nella seconda somministrazione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsigma_pred <- sqrt(sigma_post2 + sigma_e2)\n\nIC_pred <- qnorm(\n  c(.025, .975),\n  mean = mu_post,\n  sd = sigma_pred\n)\n\nprob_pred_sopra <- 1 - pnorm(\n  cut_off,\n  mean = mu_post,\n  sd = sigma_pred\n)\n\ncat(\"DS predittiva:\", round(sigma_pred, 2), \"\\n\")\n#> DS predittiva: 7.9\ncat(\n  \"Intervallo predittivo al 95%: [\",\n  round(IC_pred[1], 1), \", \",\n  round(IC_pred[2], 1), \"]\\n\",\n  sep = \"\"\n)\n#> Intervallo predittivo al 95%: [56.2, 87.2]\ncat(\n  \"P(X nuovo > 70 | X = 72):\",\n  round(prob_pred_sopra * 100, 1), \"%\\n\"\n)\n#> P(X nuovo > 70 | X = 72): 58.5 %\n```\n:::\n\n\nLa probabilità che una **nuova misurazione osservata** superi 70 è circa 58.5%. È diversa da $P(\\theta>70\\mid X)$ perché riguarda un altro oggetto e include una nuova fluttuazione della misura.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Posterior del punteggio vero e distribuzione predittiva di una nuova somministrazione. La predittiva è più ampia perché include anche un nuovo errore di misura.](07_singolo_paziente_files/figure-pdf/fig-single-patient-posterior-predictive-1.png){#fig-single-patient-posterior-predictive fig-align='center' fig-alt='Due curve con lo stesso centro confrontano la posterior del punteggio vero, più stretta, e la distribuzione predittiva del nuovo punteggio osservato, più ampia. Una linea verticale indica la soglia 70.' width=85%}\n:::\n:::\n\n\nLa @fig-single-patient-posterior-predictive mostra che le due distribuzioni hanno lo stesso centro ma ampiezze diverse. La posterior descrive l'incertezza sul tratto latente; la predittiva è più larga perché include anche ciò che potrebbe cambiare nella prossima somministrazione.\n\n| Domanda | Distribuzione rilevante | Fonte di variabilità |\n|---|---|---|\n| Qual è il punteggio vero? | $p(\\theta\\mid X)$ | incertezza residua su $\\theta$ |\n| Quale punteggio osserveremo ripetendo il test? | $p(\\tilde X\\mid X)$ | incertezza su $\\theta$ + nuovo errore di misura |\n\n## Quanto dipende dalla qualità della misura? {#sec-sensibilita-attendibilita}\n\nL'attendibilità non è un dettaglio tecnico aggiunto alla fine dell'analisi. Determina quanto il punteggio individuale può modificare ciò che sappiamo prima della misurazione.\n\nA parità di $X$, una maggiore attendibilità:\n\n- assegna più peso al punteggio osservato nella media posterior;\n- riduce l'incertezza sul punteggio vero;\n- riduce la variabilità predittiva di una nuova somministrazione.\n\nLa tabella seguente mantiene invariati $X=72$, $\\mu_X=70$ e $\\sigma_X=15$ e modifica soltanto $\\rho$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nposterior_by_reliability <- function(rho_value) {\n  mu_post_value <- rho_value * X_obs +\n    (1 - rho_value) * mu_pop\n\n  sd_post_value <- sigma_X *\n    sqrt(rho_value * (1 - rho_value))\n\n  sd_pred_value <- sqrt(\n    sd_post_value^2 +\n      (1 - rho_value) * sigma_X^2\n  )\n\n  data.frame(\n    attendibilita = rho_value,\n    media_posterior = mu_post_value,\n    ds_posterior = sd_post_value,\n    prob_theta_sopra = 1 - pnorm(\n      cut_off,\n      mu_post_value,\n      sd_post_value\n    ),\n    ds_predittiva = sd_pred_value,\n    prob_nuovo_sopra = 1 - pnorm(\n      cut_off,\n      mu_post_value,\n      sd_pred_value\n    )\n  )\n}\n\nreliability_table <- do.call(\n  rbind,\n  lapply(c(.60, .85, .95), posterior_by_reliability)\n)\n\nreliability_table |>\n  mutate(\n    attendibilita = sprintf(\"%.2f\", attendibilita),\n    media_posterior = sprintf(\"%.2f\", media_posterior),\n    ds_posterior = sprintf(\"%.2f\", ds_posterior),\n    prob_theta_sopra = sprintf(\"%.1f%%\", 100 * prob_theta_sopra),\n    ds_predittiva = sprintf(\"%.2f\", ds_predittiva),\n    prob_nuovo_sopra = sprintf(\"%.1f%%\", 100 * prob_nuovo_sopra)\n  ) |>\n  setNames(c(\n    \"Attendibilità\",\n    \"Media posterior\",\n    \"DS posterior\",\n    \"P(theta > 70 | X)\",\n    \"DS predittiva\",\n    \"P(X nuovo > 70 | X)\"\n  )) |>\n  tt(caption = \"Effetto dell'attendibilità sull'inferenza per il singolo paziente\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{talltblr}[         %% tabularray outer open\ncaption={Effetto dell'attendibilità sull'inferenza per il singolo paziente},\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]Q[]Q[]Q[]},\nhline{2}={1-6}{solid, black, 0.05em},\nhline{1}={1-6}{solid, black, 0.08em},\nhline{5}={1-6}{solid, black, 0.08em},\n}                     %% tabularray inner close\nAttendibilità & Media posterior & DS posterior & P(theta > 70 | X) & DS predittiva & P(X nuovo > 70 | X) \\\\\n0.60 & 71.20 & 7.35 & 56.5% & 12.00 & 54.0% \\\\\n0.85 & 71.70 & 5.36 & 62.5% & 7.90 & 58.5% \\\\\n0.95 & 71.90 & 3.27 & 71.9% & 4.68 & 65.8% \\\\\n\\end{talltblr}\n\\end{table}\n:::\n:::\n\n\nQuesto confronto chiarisce un aspetto spesso trascurato nell'interpretazione professionale dei test: lo stesso punteggio numerico non fornisce sempre la stessa evidenza. Il suo significato dipende dalla qualità della misurazione. Con un'attendibilità più alta, una quota maggiore della distanza tra il punteggio e la media normativa viene attribuita al punteggio vero; con un'attendibilità più bassa, una quota maggiore resta compatibile con l'errore.\n\n::: {.callout-warning title=\"L'attendibilità non è necessariamente nota con certezza\" icon=false}\nIl capitolo tratta $\\rho$, $\\mu_X$ e $\\sigma_X$ come quantità note. Nella pratica, queste quantità sono stimate da campioni normativi e possono variare da una popolazione all'altra e a seconda delle condizioni di somministrazione, senza riuscire a descrivere perfettamente il singolo paziente. Un modello più completo dovrebbe rappresentare anche questa incertezza.\n:::\n\n## Dalla probabilità alla decisione {#sec-decisione-clinica}\n\nIl modello restituisce una quantità interpretabile:\n\n$$\nP(\\theta>70\\mid X=72)\n\\approx\n0.62.\n$$\n\nQuesta probabilità migliora il ragionamento rispetto al semplice confronto $72>70$, ma non produce automaticamente una decisione. Per decidere occorre considerare almeno:\n\n- le conseguenze di un falso positivo e di un falso negativo;\n- la validità del cut-off rispetto all'obiettivo clinico;\n- la prevalenza e il contesto del problema;\n- le informazioni provenienti da colloquio, anamnesi e altre misure;\n- la possibilità di ripetere o integrare la valutazione.\n\n::: {.callout-note title=\"Una formulazione prudente\" icon=false}\nDato il modello psicometrico adottato e il punteggio osservato di 72, la distribuzione a posteriori assegna circa il 62.5% di probabilità a valori del punteggio vero superiori a 70. Il risultato segnala un'incertezza clinicamente rilevante che può motivare un approfondimento, ma non è sufficiente a sostenere una diagnosi.\n:::\n\nL'analisi bayesiana non mira a sostituire il giudizio clinico con un algoritmo. Il suo contributo è quello di impedire che passaggi concettualmente diversi vengano confusi:\n\n1. il test **osserva** un punteggio;\n2. il modello **inferisce** un livello latente;\n3. la predittiva descrive che cosa potremmo **osservare di nuovo**;\n4. il professionista **decide** tenendo conto delle conseguenze e del contesto.\n\n### Una mappa del ragionamento {#sec-sintesi-operativa}\n\n| Passaggio | Domanda | Risposta del modello |\n|---|---|---|\n| Prior | Prima del punteggio individuale, quali valori di $\\theta$ sono plausibili? | distribuzione normativa dei punteggi veri |\n| Modello di misura | Se $\\theta$ fosse noto, quali valori di $X$ potremmo osservare? | normale centrata in $\\theta$ con varianza di errore |\n| Posterior | Dopo $X=72$, quali valori di $\\theta$ sono plausibili? | normale centrata in 71.7 |\n| Probabilità di soglia | Quanta posterior cade sopra 70? | circa 62.5% |\n| Predittiva | Quale valore potremmo osservare ripetendo il test? | distribuzione più ampia, perché include un nuovo errore |\n| Decisione | Che cosa conviene fare? | richiede probabilità, conseguenze e contesto clinico |\n\n## Il punto del capitolo {.unnumbered .unlisted}\n\nIl fraintendimento iniziale nasce dal considerare il punteggio osservato come una proprietà certa della persona e il cut-off come se producesse direttamente una diagnosi. Il modello bayesiano non elimina la soglia né nega l'utilità del test. Mostra, però, che tra il dato e la decisione esiste un passaggio inferenziale che deve essere esplicitato.\n\nIn questo passaggio, il prior descrive la distribuzione normativa dei punteggi veri, la likelihood traduce l'attendibilità in un modello dell'errore di misura e la posterior quantifica ciò che il punteggio individuale permette di apprendere sul paziente. Nel modello Normale-Normale, la media posteriore coincide con la stima classica di Kelly; l'alternativa bayesiana non rigetta quindi la psicometria classica, ma inserisce la stima puntuale all'interno di una distribuzione completa.\n\nIl guadagno sostantivo è la possibilità di formulare direttamente domande come $P(\\theta>c\\mid X)$ e, allo stesso tempo, di distinguerle da domande diverse: la probabilità di una diagnosi, la probabilità che una nuova somministrazione superi il cut-off e la scelta clinica più opportuna.\n\nL'inferenza bayesiana rende l'incertezza visibile e utilizzabile. Tuttavia, non trasforma il test in un giudice infallibile né sostituisce il professionista, ma rende più difficile confondere la misura con il costrutto e il risultato con la decisione.\n\n## Esercizi {.unnumbered .unlisted}\n\n### Esercizio 1 — Comprendere {.unnumbered .unlisted}\n\n*Codice: no · 10 minuti*\n\nPer il caso discusso nel capitolo, associa ciascuna domanda alla distribuzione corretta e spiega in una frase la scelta.\n\n1. Prima di conoscere il punteggio del paziente, quali punteggi veri sono plausibili nella popolazione normativa?\n2. Se il punteggio vero fosse 75, quali punteggi osservati potrebbe produrre il test?\n3. Dopo avere osservato $X=72$, quali punteggi veri sono plausibili per il paziente?\n4. Se il test venisse ripetuto, quali nuovi punteggi osservati sarebbero plausibili?\n\nLe distribuzioni disponibili sono:\n\n- $p(\\theta)$;\n- $p(X\\mid\\theta)$;\n- $p(\\theta\\mid X)$;\n- $p(\\tilde X\\mid X)$.\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nChiediti prima di tutto quale sia l'oggetto incerto in ciascuna domanda: il punteggio vero oppure un punteggio osservato.\n:::\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\n1. $p(\\theta)$: è il prior normativo sui punteggi veri prima del dato individuale.\n2. $p(X\\mid\\theta)$: descrive la variabilità delle misure osservate a punteggio vero fissato.\n3. $p(\\theta\\mid X)$: è la posterior sul punteggio vero dopo avere osservato il paziente.\n4. $p(\\tilde X\\mid X)$: è la predittiva a posteriori di una nuova misurazione.\n\nLa differenza decisiva è che posterior e prior riguardano $\\theta$, mentre modello di misura e predittiva riguardano punteggi osservabili.\n:::\n\n### Esercizio 2 — Prevedere {.unnumbered .unlisted}\n\n*Codice: no · 10 minuti*\n\nConfronta tre test che hanno la stessa media normativa, la stessa deviazione standard e lo stesso punteggio osservato $X=72$, ma attendibilità pari a 0.60, 0.85 e 0.95. Prima di rileggere la tabella del capitolo, prevedi che cosa accade aumentando l'attendibilità:\n\n1. alla media posterior;\n2. alla deviazione standard posterior;\n3. a $P(\\theta>70\\mid X)$;\n4. alla dispersione della predittiva di una nuova misurazione.\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nUna maggiore attendibilità significa che una quota maggiore della differenza tra 72 e la media normativa viene attribuita al punteggio vero e una quota minore all'errore.\n:::\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\nAumentando l'attendibilità:\n\n1. la media posterior si avvicina a 72, perché il punteggio osservato riceve più peso;\n2. la deviazione standard posterior diminuisce, perché resta meno incertezza sul punteggio vero;\n3. la probabilità che $\\theta$ superi 70 aumenta;\n4. la predittiva di una nuova misurazione diventa meno dispersa, perché diminuisce anche il nuovo errore di misura.\n\nQuesti cambiamenti non dipendono dal fatto che 72 sia \"più significativo\", ma dal diverso modello della qualità della misura.\n:::\n\n### Esercizio 3 — Modificare {.unnumbered .unlisted}\n\n*Codice: no · 10–15 minuti*\n\nMantieni invariati $\\mu_X=70$, $\\sigma_X=15$ e $\\rho=0.85$, ma considera tre punteggi osservati: 68, 72 e 80.\n\nSenza eseguire simulazioni:\n\n1. calcola la media posterior usando\n\n   $$\n   \\mu_{\\text{post}}=\\rho X+(1-\\rho)\\mu_X;\n   $$\n\n2. stabilisci per quale punteggio $P(\\theta>70\\mid X)$ sarà inferiore a 0.50, poco superiore a 0.50 oppure nettamente superiore a 0.50;\n3. spiega perché la deviazione standard posterior resta uguale nei tre casi.\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nCon $\\rho=0.85$, la media posterior è $0.85X+10.5$. La varianza posterior dipende da $\\rho$ e $\\sigma_X$, non dal valore particolare di $X$.\n:::\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\nLe medie posterior sono:\n\n- per $X=68$: $0.85\\times68+0.15\\times70=68.3$;\n- per $X=72$: $71.7$;\n- per $X=80$: $78.5$.\n\nPoiché tutte le posterior hanno la stessa deviazione standard:\n\n- con $X=68$, la media è sotto 70 e quindi $P(\\theta>70\\mid X)<0.50$;\n- con $X=72$, la media è poco sopra 70 e la probabilità è soltanto moderatamente superiore a 0.50;\n- con $X=80$, la media è molto sopra 70 e la probabilità è nettamente maggiore.\n\nLa dispersione non cambia perché, nel modello con varianze note, il valore osservato sposta il centro della posterior ma non la sua precisione.\n:::\n\n### Esercizio 4 — Criticare {.unnumbered .unlisted}\n\n*Codice: no · 10 minuti*\n\nUn referto afferma:\n\n> «Il paziente ha ottenuto 72, quindi è clinicamente depresso. L'analisi bayesiana conferma la diagnosi con una probabilità del 62%. Se il test venisse ripetuto, vi sarebbe ancora il 62% di probabilità di superare il cut-off.»\n\nIndividua almeno tre problemi e riscrivi il passaggio in una forma più corretta.\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nDistingui: punteggio osservato, punteggio vero, diagnosi e nuovo punteggio osservato.\n:::\n\n::: {.callout-note collapse=true title=\"Elementi per la risposta\"}\nIl passaggio contiene almeno quattro problemi:\n\n1. il superamento del cut-off osservato non equivale automaticamente a una diagnosi;\n2. il 62% riguarda $P(\\theta>70\\mid X=72)$ sotto uno specifico modello, non la probabilità che il paziente abbia il disturbo;\n3. il risultato dipende dall'attendibilità e dai parametri normativi assunti;\n4. la probabilità che una nuova misurazione superi 70 deriva dalla predittiva ed è diversa, nel nostro esempio circa 58.5%.\n\nUna formulazione possibile è:\n\n> «Dato il modello psicometrico adottato e il punteggio osservato di 72, la distribuzione a posteriori assegna circa il 62.5% di probabilità a punteggi veri superiori a 70. Questa quantità non coincide con la probabilità di una diagnosi e deve essere integrata con altre informazioni cliniche. Il modello predice inoltre una probabilità di circa 58.5% che una nuova somministrazione superi la stessa soglia.»\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.5.2\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.1            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.1           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8         tidyselect_1.2.1     farver_2.1.2        \n#>  [4] S7_0.2.2             fastmap_1.2.0        tensorA_0.36.2.1    \n#>  [7] digest_0.6.39        timechange_0.4.0     estimability_2.0.0  \n#> [10] lifecycle_1.0.5      magrittr_2.0.5       compiler_4.6.1      \n#> [13] rlang_1.3.0          tools_4.6.1          yaml_2.3.12         \n#> [16] knitr_1.51           labeling_0.4.3       bridgesampling_1.2-1\n#> [19] pkgbuild_1.4.8       curl_7.1.0           RColorBrewer_1.1-3  \n#> [22] abind_1.4-8          purrr_1.2.2          grid_4.6.1          \n#> [25] stats4_4.6.1         xtable_1.8-8         inline_0.3.21       \n#> [28] emmeans_2.0.4        scales_1.4.0         cli_3.6.6           \n#> [31] mvtnorm_1.4-2        rmarkdown_2.31       generics_0.1.4      \n#> [34] otel_0.2.0           RcppParallel_6.2.0   cachem_1.1.0        \n#> [37] stringr_1.6.0        parallel_4.6.1       vctrs_0.7.3         \n#> [40] V8_8.2.0             Matrix_1.7-6         jsonlite_2.0.0      \n#> [43] litedown_0.10        arrayhelpers_1.1-2   glue_1.8.1          \n#> [46] codetools_0.2-20     distributional_0.8.1 lubridate_1.9.5     \n#> [49] stringi_1.8.7        gtable_0.3.6         QuickJSR_1.10.0     \n#> [52] pillar_1.11.1        htmltools_0.5.9      Brobdingnag_1.2-9   \n#> [55] R6_2.6.1             textshaping_1.0.5    rprojroot_2.1.1     \n#> [58] evaluate_1.0.5       lattice_0.22-9       backports_1.5.1     \n#> [61] memoise_2.0.1        broom_1.0.13         snakecase_0.11.1    \n#> [64] rstantools_2.7.0     coda_0.19-4.1        gridExtra_2.3.1     \n#> [67] nlme_3.1-170         checkmate_2.3.4      xfun_0.60           \n#> [70] pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "07_singolo_paziente_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\usepackage{rotating}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}