{
  "hash": "4da849e25148afbe7298948a563a8e3a",
  "result": {
    "engine": "knitr",
    "markdown": "# Valutare i modelli bayesiani  {#sec-div-kl-lppd-elpd}\n\n## Introduzione {.unnumbered .unlisted}\n\nI capitoli precedenti ci hanno fornito due strumenti concettuali fondamentali: l'*entropia*, che misura l'incertezza di una distribuzione, e la *divergenza di Kullback–Leibler* ($D_{\\text{KL}}$), che quantifica la distanza informazionale tra due distribuzioni. È giunto il momento di fare il passo successivo: utilizzare questi strumenti per *valutare e confrontare i modelli statistici* in ambito bayesiano. \n\nTutto parte da una domanda cruciale: *quanto sarà capace il nostro modello di prevedere dati mai visti?* Un modello valido non è quello che si adatta perfettamente ai dati osservati, ma quello che sa *generalizzare* efficacemente a situazioni future. Questa distinzione tra adattamento (*fitting*) e generalizzazione è il cuore della valutazione predittiva.\n\nImmaginiamo di sviluppare un test psicometrico per stimare l'ansia pre-esame. Non ci interessa solo che il modello descriva bene il campione usato per costruirlo; vogliamo essere sicuri che fornirà *previsioni affidabili anche per nuovi studenti*. Scegliere tra modelli statistici, in questo senso, è come scegliere tra test psicologici: cerchiamo lo strumento che offre la maggiore affidabilità predittiva.\n\nUn approccio intuitivo per valutare le prestazioni previsive è calcolare l'*errore quadratico medio* (MSE)[^mse] sui dati a disposizione, presupponendo che sarà simile per dati futuri. Tuttavia, questa strategia trascura un elemento essenziale: *l'incertezza delle stime*. Le nostre previsioni dipendono da parametri di cui non conosciamo il valore esatto, ma solo la distribuzione a posteriori. È la *distribuzione predittiva a posteriori* che, propagando questa incertezza, fornisce una visione completa e probabilistica delle previsioni.\n\n[^mse]: L'errore quadratico medio (MSE) misura la discrepanza tra valori previsti e osservati: $\\text{MSE} = \\frac{1}{n}\\sum_{i=1}^n (y_i - \\hat{y}_i)^2$. Sebbene utile, non cattura l'incertezza probabilistica delle previsioni.\n\nSorge però un problema: valutare la predittiva sugli stessi dati usati per stimare il modello porta a un *ottimismo eccessivo* e al rischio di *overfitting*. Per una stima realistica della capacità di generalizzazione, serve un criterio che valuti la performance predittiva *su dati non osservati*.\n\nÈ qui che entra in gioco l'*Expected Log Predictive Density (ELPD)*.\nL'ELPD misura, attraverso il *log-score*, quanto bene un modello prevede dati futuri generati dalla distribuzione vera. In sostanza, rappresenta l'accuratezza predittiva *attesa*. Un ELPD più alto indica una migliore capacità predittiva. (Anticipiamo un collegamento teorico che formalizzeremo dopo: *massimizzare l'ELPD equivale a minimizzare la divergenza di Kullback–Leibler dalla verità*.)\n\nLa sfida pratica è che l'ELPD, essendo un'aspettativa rispetto alla distribuzione \"vera\" (sconosciuta) dei dati, non è calcolabile direttamente. Dobbiamo quindi ricorrere a *approssimazioni numeriche*. La più diffusa è la *cross-validazione leave-one-out (LOO)*, che per ogni osservazione valuta quanto bene il modello l'avrebbe predetta senza averla mai vista. Sommando questi contributi, otteniamo una stima *out-of-sample* dell'ELPD, molto meno soggetta a overfitting.\n\nIn questo capitolo vedremo come la LOO fornisca un criterio solido per confrontare modelli bayesiani, evitando il sovradattamento e guidandoci verso la scelta del modello con le migliori capacità di generalizzazione. Percorreremo tutto l'itinerario logico: dal *log-score*, alla *LPPD* (valutazione in-sample), fino all'*ELPD* stimato tramite *PSIS-LOO*, mostrando come questi strumenti si ancorino saldamente alla teoria dell'informazione e come si applichino concretamente al confronto tra modelli.\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\nPer rispondere alla domanda fondamentale sulla qualità predittiva dei modelli, seguiremo un percorso che procede dalla teoria alla pratica, toccando i passaggi chiave:\n\n* **Costruire la distribuzione predittiva posteriore** ⇒ propagare l’incertezza dei parametri nelle previsioni.\n* **Applicare il log-score** ⇒ valutare la bontà delle predizioni osservazione per osservazione.\n* **Passare da LPPD (in-sample) a ELPD (out-of-sample)** ⇒ distinguere adattamento e generalizzazione.\n* **Collegare ELPD e divergenza di Kullback–Leibler** ⇒ giustificazione teorica della misura.\n* **Stimare l’ELPD con PSIS-LOO** ⇒ ottenere un’approssimazione efficiente, con controlli diagnostici.\n* **Confrontare modelli tramite ΔELPD e il suo errore standard** ⇒ scegliere il modello più predittivo mantenendo la parsimonia.\n\n::: {.callout-tip collapse=true}\n## Prerequisiti\n\n- Per comprendere appieno questo capitolo è utile leggere il capitolo 7 *Ulysses’ Compass* di *Statistical Rethinking* (@McElreath_rethinking).\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n\nlibrary(gt)\nlibrary(conflicted)\nlibrary(brms)\nlibrary(loo)\nconflicts_prefer(rstan::loo)\n```\n:::\n\n:::\n\n::: {.callout-tip title=\"In sintesi\" collapse=\"false\"}\n**ELPD in pillole**\n\n* **Che cos’è:** Una misura della capacità predittiva *fuori campione* di un modello.\n* **Come si calcola (in teoria):** È la media del *log-score* che il modello assegna a dati futuri. Valori più alti ⇒ modello migliore.\n* **Perché è giusto usarlo:** Massimizzare l’ELPD significa avvicinarsi il più possibile alla distribuzione “vera” dei dati, minimizzando la divergenza di Kullback–Leibler.\n* **Come si usa in pratica:** Lo stimiamo con la *cross–validazione leave-one-out* (PSIS-LOO), che fornisce un’approssimazione efficiente senza bisogno di raccogliere nuovi dati.\n:::\n\n::: {.callout-important title=\"Intuizione e definizione dell'ELPD\"}\n\n#### L’obiettivo: prevedere il futuro {.unnumbered .unlisted}\n\nImmaginiamo che il nostro modello, una volta addestrato sui dati $y$, produca una *distribuzione predittiva* $q(\\tilde{y} \\mid y)$. Lo scopo non è solo adattarsi ai dati già osservati, ma saper predire bene dati *nuovi* $\\tilde{y}$, generati dalla *vera* ma sconosciuta distribuzione $p(\\tilde{y})$.\n\nLa domanda chiave è quindi: *quanto è buona $q$ nel prevedere $p$?*\n\n#### La metrica: il log-score {.unnumbered .unlisted}\n\nLo strumento ideale per rispondere a questa domanda è il *log-score*, uno *scoring rule proprio*. In media, assegna il punteggio più alto proprio quando la distribuzione predittiva $q$ coincide con la distribuzione vera $p$.\n\nLa nostra quantità obiettivo è l’*Expected Log Predictive Density (ELPD):*\n$$\n\\mathrm{ELPD} = \\mathbb{E}_{p(\\tilde y)}\\!\\left[\\log q(\\tilde y \\mid y)\\right].\n$$\nQuesta formula rappresenta il valore *atteso* del log-score che il modello assegna a una nuova osservazione $\\tilde{y}$ generata da $p$. In altre parole, l’ELPD è la media, rispetto alla distribuzione vera dei dati, del punteggio logaritmico attribuito dal modello a dati futuri.\n\n**Regola d’oro:** *massimizzare l’ELPD equivale a ridurre al minimo la distanza informazionale dalla verità.*\n\n#### Perché è la scelta corretta: il collegamento con l’inferenza {.unnumbered .unlisted}\n\nIl legame con la teoria dell’informazione è diretto. La *divergenza di Kullback–Leibler (KL)* tra $p$ e $q$ si decompone così:\n\n$$\nD_{\\mathrm{KL}}(p \\parallel q) \\;=\\;\n\\underbrace{\\mathbb{E}_{p}[\\log p(\\tilde y)]}_{\\text{entropia di } p}\n\\;-\\;\n\\underbrace{\\mathbb{E}_{p}[\\log q(\\tilde y \\mid y)]}_{\\text{ELPD}}.\n$$\n\nIl primo termine (l’entropia di $p$) è una costante fissata dalla natura dei dati.\n**Minimizzare la divergenza KL equivale quindi a massimizzare l’ELPD.**\n\nScegliere il modello con l’ELPD più alto significa scegliere la distribuzione predittiva *più vicina alla verità* in senso informazionale.\n:::\n\n::: {.callout-note title=\"Dalla teoria alla pratica\"}\n#### La sfida pratica e la soluzione (LOO) {.unnumbered .unlisted}\n\nNon possiamo calcolare l’ELPD vero perché non conosciamo $p(\\tilde{y})$.\nLa soluzione è stimarlo usando i dati a nostra disposizione, ma *senza usare la stessa osservazione sia per addestrare il modello che per testarlo* (sarebbe un cheating).\n\nIl metodo di riferimento è la *Leave-One-Out Cross-Validation (LOO)*:\n\n$$\n\\widehat{\\mathrm{ELPD}}_{\\mathrm{LOO}} = \\sum_{i=1}^{n} \\log q(y_i \\mid y_{-i}),\n$$\n\ndove $q(y_i \\mid y_{-i})$ è la densità predittiva di $y_i$ quando il modello è addestrato su *tutti i dati tranne $y_i$*.  \n\nQuesto approccio fornisce una stima quasi non distorta dell’ELPD: è concettualmente identica all’ELPD teorico, ma stimata dai dati reali senza bisogno di conoscere la distribuzione vera.\n:::\n\n::: {.callout-tip title=\"Efficienza nella pratica: PSIS-LOO\"}\nRicalcolare il modello $n$ volte può essere proibitivo. Per questo si utilizza l’efficiente *PSIS-LOO* (*Pareto Smoothed Importance Sampling LOO*), che permette di ottenere la stessa stima senza rifittare il modello per ogni osservazione.  \n\nIn più, PSIS-LOO fornisce le diagnostiche *Pareto-$k$*, utili per valutare l’affidabilità dell’approssimazione e capire se alcuni punti esercitano un’influenza eccessiva.\n:::\n\n::: {.callout-tip title=\"Interpretazione e confronto\"}\n#### Come si interpretano i valori di ELPD {.unnumbered .unlisted}\n\n* **Scala:** L’ELPD è una somma su tutte le $n$ osservazioni. Un ELPD totale più alto indica un modello migliore.  \n* **Confronto:** Per confrontare due modelli, $A$ e $B$, si calcola $\\Delta ELPD = ELPD_A - ELPD_B$.  \n  L’errore standard di questa differenza aiuta a valutare se il miglioramento è credibile.  \n* **Normalizzazione:** Con dataset di dimensioni diverse è fondamentale usare l’*ELPD per osservazione* ($ELPD/n$) per un confronto equo.  \n\n**Nota pratica:** Alcuni software (ad es. Stan) riportano la *devianza*, definita come $-2 \\times ELPD$.  \nIn quel caso, **un valore più basso indica un modello migliore**. Controllare sempre la convenzione usata.\n:::\n\n::: {.callout-note collapse=true title=\"Esempio pratico di confronto ELPD\"}\nSupponiamo di confrontare due modelli, $A$ e $B$, stimati sullo stesso dataset ($n = 200$).  \n\n| Modello | ELPD totale | ELPD per osservazione | ΔELPD rispetto a B | SE(ΔELPD) |\n|---------|-------------|-----------------------|--------------------|-----------|\n| A       | -520        | -2.60                 | +10                | 4.5       |\n| B       | -530        | -2.65                 | —                  | —         |\n\n**Interpretazione:** \n\n* Il modello A ha un ELPD più alto (−520 contro −530).  \n* La differenza è ΔELPD = 10, con errore standard 4.5.  \n* Poiché ΔELPD è circa **2 volte** l’errore standard, possiamo ritenere credibile il miglioramento di A rispetto a B.  \n:::\n\n::: {.callout-note collapse=true title=\"Esempio con la devianza (Stan)\"}\nAlcuni software, come Stan, riportano la *devianza*, definita come:\n\n$$\n\\text{Devianza} = -2 \\times ELPD.\n$$\n\nRiprendiamo l’esempio precedente.  \n\n| Modello | ELPD totale | Devianza (= −2 × ELPD) | ΔELPD rispetto a B | SE(ΔELPD) |\n|---------|-------------|-------------------------|--------------------|-----------|\n| A       | -520        | 1040                    | +10                | 4.5       |\n| B       | -530        | 1060                    | —                  | —         |\n\n**Interpretazione (convenzione Stan):**  \n* Un valore di **devianza più basso** indica un modello migliore.  \n* Qui il modello A ha devianza 1040 contro 1060 di B, quindi è preferibile.  \n* La differenza di devianza (20 punti) corrisponde a ΔELPD = 10, con SE = 4.5, quindi il vantaggio di A è credibile.\n:::\n\n## Il punto di partenza: dalle previsioni deterministiche a quelle probabilistiche\n\nPrima di addentrarci nei dettagli tecnici, facciamo un passo indietro per chiarire perché la valutazione predittiva bayesiana è diversa da quella frequentista classica.\n\n**Nell’approccio classico**, una volta stimati i parametri (ad esempio con la massima verosimiglianza), li trattiamo come valori “veri” e fissi. Se $\\hat{\\theta}$ è la nostra stima puntuale, la previsione per un nuovo dato $\\tilde{y}$ è:\n\n$$\np(\\tilde{y} \\mid \\hat{\\theta}).\n$$\n\nIn questo modo si ragiona come se $\\hat{\\theta}$ fosse noto con certezza. Ma nella realtà la stima è solo una “fotografia” dei dati raccolti: se ripetessimo l’esperimento, otterremmo una stima diversa. Questo approccio, quindi, ignora l’incertezza sui parametri.\n\n**Nell’approccio bayesiano**, invece, riconosciamo che i parametri non sono numeri fissi ma quantità sconosciute. Dopo aver osservato i dati, la nostra conoscenza su $\\theta$ è descritta da un'intera distribuzione — la distribuzione a posteriori $p(\\theta \\mid y)$ — che riflette tutte le ipotesi plausibili sui parametri date le osservazioni.\n\nLa previsione per un nuovo dato $\\tilde{y}$ diventa quindi:\n\n$$\np(\\tilde{y} \\mid y) = \\int p(\\tilde{y} \\mid \\theta)\\, p(\\theta \\mid y)\\, d\\theta.\n$$ {#eq-predictive-posterior}\n\nQuesta è la *distribuzione predittiva a posteriori*: una media pesata delle previsioni possibili, dove il peso è dato da quanto ciascun valore di $\\theta$ è coerente con i dati osservati.\n\n::: {.callout-note title=\"Analogia didattica\"}\nImmaginiamo di dover prevedere il tempo di domani.\n\n* L’approccio “classico” è come chiedere a un solo meteorologo, prendere la sua previsione e considerarla come se fosse la verità.\n* L’approccio “bayesiano” è come consultare molti meteorologi diversi, dare più fiducia a chi ha fatto buone previsioni in passato, e costruire una previsione che tenga conto di tutte le opinioni plausibili.\n\nIl risultato non è una previsione unica, ma una *distribuzione di possibili scenari*, che ci dice sia cosa aspettarci più probabilmente sia quanto siamo incerti.\n:::\n\n## Distribuzione predittiva posteriore: il cuore delle previsioni bayesiane\n\nAbbiamo già incontrato la distribuzione predittiva posteriore nel capitolo sul modello *Beta–Binomiale*: è lo strumento che, nell’approccio bayesiano, consente di prevedere nuovi dati incorporando sia la struttura del modello sia l’incertezza sui parametri.  \n\nLa logica è elegante nella sua semplicità: dopo aver osservato i dati $y$, non otteniamo un singolo “miglior” valore dei parametri, ma una *distribuzione posteriore* $p(\\theta \\mid y)$ che riflette i valori plausibili di $\\theta$ e la nostra incertezza.\n\n> **Esempio concreto:**  \n> Uno psicologo che stima il livello medio di ansia in una popolazione, invece di affermare “la media è 4.7”, dirà:  *“il valore più plausibile è 4.7, **ma** è ragionevole che sia tra 4.2 e 5.1”*, riflettendo la variabilità della distribuzione a posteriori.\n\n### Decomposizione dell’integrale: cosa significa davvero\n\nL’@eq-predictive-posterior può sembrare astratta, ma si capisce bene se la leggiamo passo passo:\n\n1. $p(\\tilde{y} \\mid \\theta)$: se conoscessimo il vero valore di $\\theta$, questa sarebbe la nostra previsione per $\\tilde{y}$.  \n2. $p(\\theta \\mid y)$: descrive la nostra incertezza su quale sia il vero valore di $\\theta$.  \n3. *L’integrale*: combina le previsioni possibili, pesandole secondo la plausibilità di ciascun valore di $\\theta$.  \n\n::: {.callout-note collapse=true title=\"Intuizione dettagliata\"}\nSe conoscessimo $\\theta$, la predizione sarebbe:\n\n$$\np(\\tilde y \\mid \\theta).\n$$\nMa $\\theta$ non lo conosciamo: abbiamo solo la distribuzione posteriore $p(\\theta \\mid y)$.  \nLa predittiva posteriore si ottiene quindi come media pesata:\n\n$$\np(\\tilde y \\mid y) = \\int p(\\tilde y \\mid \\theta)\\, p(\\theta \\mid y)\\, d\\theta.\n$$\n\n**Esempio binomiale.**  \nSe i dati futuri sono generati da una Binomiale con $m$ prove e parametro $\\theta$:\n\n$$\np(\\tilde y = x \\mid \\theta) = \\binom{m}{x}\\,\\theta^x (1-\\theta)^{m-x},\n$$\n\nallora la distribuzione predittiva diventa:\n\n$$\np(\\tilde y = x \\mid y) = \\int \\binom{m}{x}\\,\\theta^x (1-\\theta)^{m-x}\\,p(\\theta\\mid y)\\,d\\theta.\n$$\n\n- Con prior Beta e dati binomiali, questo integrale ha una soluzione chiusa: la distribuzione *Beta–Binomiale*.  \n- In generale, non c’è formula chiusa: servono *approssimazioni numeriche* (ottenute mediante il metodo basato su griglia o mediante il metodo MCMC).\n:::\n\n### Approssimazione numerica con il metodo su griglia\n\nNella maggior parte dei casi l’integrale che definisce la distribuzione predittiva posteriore non può essere risolto in forma chiusa. Un modo semplice e intuitivo per affrontare il problema è *approssimarlo con una somma*, utilizzando una *griglia di valori* del parametro $\\theta$. L’idea di fondo è trasformare un calcolo continuo (l’integrale) in un calcolo discreto (una somma pesata).\n\nIl procedimento segue quattro passaggi:\n\n1. **Definire una griglia di valori possibili per $\\theta$.**\n   Ad esempio, scegliamo $J=1000$ punti equispaziati tra 0 e 1:\n   $$\n   \\theta_1, \\theta_2, \\dots, \\theta_J.\n   $$\n\n2. **Calcolare la distribuzione posteriore su ogni punto della griglia.**\n   Per ciascun $\\theta_j$, valutiamo la densità posteriore $p(\\theta_j \\mid y)$ e normalizziamo in modo che la somma dei valori sia uguale a 1. I risultati diventano i *pesi* $w_j$:\n   $$\n   w_j = \\frac{p(\\theta_j \\mid y)}{\\sum_{\\ell=1}^J p(\\theta_\\ell \\mid y)}.\n   $$\n\n3. **Combinare le distribuzioni predittive condizionate.**\n   Per ogni possibile esito futuro $x$, calcoliamo la probabilità predittiva come media pesata delle predittive condizionate:\n   $$\n   p(\\tilde y = x \\mid y) \\;\\approx\\; \\sum_{j=1}^J w_j \\, p(\\tilde y = x \\mid \\theta_j).\n   $$\n\n4. **Ottenere la distribuzione predittiva.**\n   Ripetendo il calcolo per tutti i possibili valori di $x$, otteniamo una distribuzione completa (*pmf*) per i dati futuri. Da questa distribuzione possiamo:\n\n   * ricavare probabilità,\n   * generare campioni simulati di $\\tilde y$,\n   * confrontare le previsioni del modello con i dati osservati.\n\n**Da ricordare:**\n\n* La distribuzione predittiva posteriore non è la media di singoli valori, ma una *vera e propria distribuzione di probabilità* sui dati futuri.\n* Il metodo su griglia è il modo più semplice per implementare questa logica: discretizza i possibili valori di $\\theta$, li pesa in base alla loro plausibilità e combina le predizioni corrispondenti.\n* In problemi più complessi, la stessa idea viene realizzata in maniera più efficiente con l’*MCMC*: invece di una griglia fissa, utilizziamo campioni $\\theta^{(s)}$ estratti dalla distribuzione posteriore.\n\n::: {.callout-note collapse=true title=\"Esempio numerico completo (R)\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ------------------------------------------------------------------\n# Predittiva posteriore per Binomiale con metodo su griglia \n# ------------------------------------------------------------------\n\n# 1) Dati osservati e prior\nk <- 10   # successi osservati\nn <- 50   # prove osservate totali\na <- 1    # prior Beta(a, b)\nb <- 1\nm <- 10   # numero di prove future che vogliamo prevedere (per costruire la pmf di tilde y)\nJ <- 1001 # numero di punti della griglia su theta (dispari per includere 0, 0.5, 1)\n\n# 2) Griglia su theta (da 0 a 1)\ntheta <- seq(0, 1, length.out = J)\n\n# 3) Densità posteriore NON normalizzata su ogni punto di griglia\n#    Posteriore Beta(a + k, b + n - k) -> densità proporzionale a theta^(a+k-1) * (1-theta)^(b+n-k-1)\npost_unnorm <- theta^(a + k - 1) * (1 - theta)^(b + n - k - 1)\n\n# 4) Normalizziamo per ottenere pesi che sommano a 1 (w_j)\nw <- post_unnorm / sum(post_unnorm)\n\n# (controllo) I pesi devono sommare a 1\nsum(w)  # ~ 1\n#> [1] 1\n\n# 5) Costruiamo la pmf predittiva p(tilde y = x | y) come media pesata delle Binomiali condizionate\nx_vals  <- 0:m                # tutti i possibili esiti futuri in m prove\npred_pmf <- rep(NA_real_, m+1)\n\n# Per ogni x, sommiamo w_j * P(tilde y = x | theta_j)\nfor (i in 1:(m+1)) {\n  x <- x_vals[i]\n  # vettore di probabilità condizionate per tutti i theta_j\n  p_x_given_theta <- dbinom(x, size = m, prob = theta)\n  # media pesata rispetto ai pesi posteriori w_j\n  pred_pmf[i] <- sum(w * p_x_given_theta)\n}\n\n# (controllo) La pmf deve sommare a 1\nsum(pred_pmf)  # ~ 1\n#> [1] 1\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 6) Tabella finale con la pmf predittiva\npred_df <- data.frame(x = x_vals, p = pred_pmf)\nhead(pred_df)   # prime righe\n#>   x      p\n#> 1 0 0.1139\n#> 2 1 0.2506\n#> 3 2 0.2762\n#> 4 3 0.1995\n#> 5 4 0.1040\n#> 6 5 0.0407\n```\n:::\n\n\nConfronto con la **formula chiusa** (Beta–Binomiale) per verifica didattica:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 7) Parametri della posteriore coniugata\na_post <- a + k\nb_post <- b + n - k\n\n# 8) Funzione Beta-Binomiale (pmf): choose(m, x) * Beta(x+a_post, m-x+b_post) / Beta(a_post, b_post)\ndbetabinom <- function(x, m, a, b) {\n  choose(m, x) * beta(x + a, m - x + b) / beta(a, b)\n}\n\n# 9) pmf teorica Beta-Binomiale\nbb_pmf <- rep(NA_real_, m+1)\nfor (i in 1:(m+1)) {\n  bb_pmf[i] <- dbetabinom(x_vals[i], m, a_post, b_post)\n}\n\n# 10) Confronto numerico: scarto massimo tra griglia e formula chiusa\nmax_abs_err <- max(abs(pred_pmf - bb_pmf))\nmax_abs_err   # con J grande dovrebbe essere molto vicino a 0\n#> [1] 1.92e-15\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Affianca le due colonne per ispezione\ndata.frame(x = x_vals, grid = pred_pmf, beta_binom = bb_pmf) |> head()\n#>   x   grid beta_binom\n#> 1 0 0.1139     0.1139\n#> 2 1 0.2506     0.2506\n#> 3 2 0.2762     0.2762\n#> 4 3 0.1995     0.1995\n#> 5 4 0.1040     0.1040\n#> 6 5 0.0407     0.0407\n```\n:::\n\n\n**Cosa osservare:**\n\n* `w` contiene i **pesi posteriori** sui diversi valori di $\\theta$; sommano a 1.\n* Per ogni possibile esito futuro `x`, la **pmf predittiva** `pred_pmf[i]` è una **media pesata** delle probabilità binomiali condizionate a ciascun `theta[j]`.\n* Con prior Beta e dati binomiali, la soluzione chiusa (**Beta–Binomiale**) coincide con l’approssimazione su griglia (errore massimo vicino a 0 se `J` è grande).\n:::\n\n### Notazione e terminologia\n\nPer sintesi useremo talvolta la forma compatta $p(\\cdot \\mid y)$ per indicare la predittiva posteriore. Quando vogliamo evidenziare la previsione marginale per una singola osservazione $y_i$ scriviamo:\n\n$$\np(y_i \\mid y) = \\int p(y_i \\mid \\theta)\\, p(\\theta \\mid y)\\, d\\theta.\n$$\n\n**Idea chiave:** la predittiva posteriore propaga l’incertezza sui parametri nelle previsioni.\nQuesto rende la valutazione predittiva coerente con il principio bayesiano e utilizzabile nel confronto tra modelli.\n\n::: {.callout-note title=\"Mappa concettuale\"}\n\n| Quantità              | Significato                       | Uso principale                   |\n| --------------------- | --------------------------------- | -------------------------------- |\n| $p(y_i \\mid \\theta)$  | Verosimiglianza                   | Calcolo predittivo               |\n| $p(\\theta \\mid y)$    | Distribuzione posteriore          | Ponderazione                     |\n| $p(y_i \\mid y)$       | Predizione media bayesiana        | Log-score, LPPD                  |\n| $p(y_i \\mid y_{-i})$  | Predizione LOO (*leave-one-out*)  | ELPD                             |\n| $p(\\tilde{y} \\mid y)$ | Distribuzione predittiva completa | Divergenza KL, confronto modelli |\n:::\n\n## Il problema fondamentale della valutazione predittiva\n\nOra che sappiamo come costruire previsioni bayesiane, affrontiamo la domanda centrale: *come possiamo valutare la qualità di queste previsioni?*\n\n### Il dilemma teorico\n\nQuando costruiamo un modello statistico, non ci interessa solo spiegare i dati già osservati, ma vogliamo sapere *quanto bene il modello riuscirà a predire dati futuri*.\n\nIn termini formali, distinguiamo tra due distribuzioni:\n\n* la *vera distribuzione dei dati futuri* $p(\\tilde{y})$, che purtroppo non conosciamo mai;\n* la *distribuzione predittiva del modello* $p(\\tilde{y} \\mid y)$, cioè le previsioni del modello dopo aver visto i dati osservati $y$.\n\nL’obiettivo è quindi misurare *quanto $p(\\tilde{y} \\mid y)$ si avvicina a $p(\\tilde{y})$*.\n\n### La divergenza di Kullback–Leibler come misura di distanza\n\nLa *divergenza di Kullback–Leibler* (KL) è lo strumento che la teoria dell’informazione ci mette a disposizione per quantificare questa distanza:\n\n$$\nD_{\\text{KL}}(p \\parallel q) \\;=\\; \\mathbb{E}_{p} \\left[ \\log \\frac{p(\\tilde{y})}{q(\\tilde{y} \\mid y)} \\right].\n$$ {#eq-kl-divergence-def}\n\n**Interpretazione intuitiva:**\n\n* se il modello $q$ assegna probabilità elevate agli stessi eventi che sono probabili nella realtà $p$, allora $D_{\\text{KL}}$ sarà piccolo;\n* se invece il modello “sbaglia bersaglio”, attribuendo alta probabilità a eventi che in realtà sono rari, $D_{\\text{KL}}$ sarà grande.\n\n::: {.callout-note title=\"Idea chiave\"}\nLa divergenza KL misura *quanta informazione perdiamo* quando usiamo le predizioni del modello $q$ al posto della distribuzione vera $p$.\n:::\n\n### L’ostacolo pratico\n\nC’è però un problema fondamentale: *la distribuzione vera $p(\\tilde{y})$ non la conosciamo mai.*\n\nAbbiamo soltanto i dati osservati. Non possiamo quindi calcolare direttamente la distanza tra $p$ e $q$. Questo rende necessarie strategie di approssimazione, che vedremo nei prossimi capitoli: la *validazione incrociata* e criteri predittivi come l’*Expected Log Predictive Density (ELPD)*.\n\n### Mini-esempio intuitivo\n\nImmagina una moneta truccata che produce *testa* il 70% delle volte. Vogliamo confrontare due modelli:\n\n* **Modello A**: assume che la moneta sia equa ($p=0.5$);\n* **Modello B**: assume che la probabilità di testa sia $p=0.65$.\n\nSe sapessimo che la probabilità “vera” è $p=0.7$, sarebbe chiaro che il Modello B è più vicino alla realtà. La divergenza di Kullback–Leibler servirebbe proprio a quantificare *quanta informazione perdiamo* scegliendo A invece di B.\n\n::: {.callout-important title=\"Il punto cruciale\"}\nNella pratica non conosciamo mai la probabilità vera della moneta.\nAbbiamo solo i dati osservati (i lanci). Per decidere quale modello predice meglio, dobbiamo basarci su criteri che stimano indirettamente la capacità predittiva: ELPD e LOO sono tra i più efficaci.\n:::\n\n## Il log-score: misurare l’accuratezza predittiva punto per punto {#sec-logscore}\n\nAbbiamo definito la distribuzione predittiva posteriore e visto il problema teorico della valutazione. Ora introduciamo il primo strumento pratico: il *log-score*.\n\n### La domanda di base\n\nPer ogni osservazione nei nostri dati ci chiediamo: *quanto il nostro modello considerava plausibile proprio questo risultato?* Il log-score fornisce la risposta.\n\n### Definizione formale\n\nIl log-score per un’osservazione $y_i$ è:\n\n$$\n\\text{Log-score}(y_i) = \\log p(y_i \\mid y) ,\n$$ {#eq-log-score-def}\ndove $p(y_i \\mid y)$ è la distribuzione predittiva posteriore:\n$$\np(y_i \\mid y) = \\int p(y_i \\mid \\theta)\\, p(\\theta \\mid y)\\, d\\theta .\n$$\n\n\n### Interpretazione: “scommettere” sui dati\n\nIl log-score misura quanto bene il modello avrebbe “puntato” sul risultato osservato:\n\n* se $p(y_i \\mid y)$ è alto (l’osservazione era plausibile), il log-score è vicino a 0 → **buono**;\n* se $p(y_i \\mid y)$ è basso (l’osservazione era quasi esclusa), il log-score diventa molto negativo → **scarso**.\n\n::: {.callout-note title=\"Perché usare il logaritmo?\"}\nIl logaritmo trasforma prodotti di probabilità in somme, rendendo i calcoli più stabili. Inoltre penalizza fortemente i casi in cui il modello assegna probabilità quasi nulla a ciò che accade davvero.\n:::\n\n### Dal singolo dato al punteggio totale\n\nPer valutare l’intero dataset, sommiamo i log-score di tutte le osservazioni:\n\n$$\nS = \\sum_{i=1}^n \\log p(y_i \\mid y).\n$$ {#eq-log-score-sum-def}\n\nPiù $S$ è alto (meno negativo), più il modello “scommette bene” sui dati osservati (*in-sample*).\n\n### Due filosofie a confronto: parametri fissi vs incerti\n\n#### Approccio classico: parametri fissi\n\nNell’impostazione frequentista tradizionale fissiamo i parametri a una stima puntuale, tipicamente $\\hat{\\theta}$, e calcoliamo:\n\n$$\n\\log p(y_i \\mid \\hat{\\theta}).\n$$\nQuesto ignora completamente l’incertezza sui parametri.\n\n#### Approccio bayesiano: parametri incerti\n\nNell’approccio bayesiano riconosciamo che i parametri restano incerti anche dopo aver visto i dati. Perciò mescoliamo le previsioni su tutti i valori plausibili:\n\n$$\n\\begin{align}\n\\log p(y_i \\mid y) &= \\log \\int p(y_i \\mid \\theta)\\, p(\\theta \\mid y)\\, d\\theta .\n\\end{align}\n$$ {#eq-integral-p-h-mid-yi}\n\n::: {.callout-note title=\"Differenza chiave\"}\n* **Frequentista:** “Quanto sono plausibili i dati se i parametri valgono esattamente $\\hat{\\theta}$?”\n* **Bayesiano:** “Quanto sono plausibili i dati, in media, considerando tutti i valori di $\\theta$ compatibili con i dati osservati?”\n\nLa seconda prospettiva è più realistica, perché include l’incertezza sui parametri.\n:::\n\n### Implementazione pratica con MCMC\n\nL’integrale dell’@eq-integral-p-h-mid-yi di solito non ha soluzione chiusa. Con i campioni MCMC $\\theta^{(1)},\\dots,\\theta^{(S)}$, lo stimiamo così:\n\n1. **Likelihood per campione**\n   $p(y_i \\mid \\theta^{(s)})$ per $s=1,\\dots,S$.\n2. **Media aritmetica**\n   $$\n   p(y_i \\mid y) \\;\\approx\\; \\frac{1}{S}\\sum_{s=1}^S p(y_i \\mid \\theta^{(s)}).\n   $$ {#eq-mcmc-posterior-parameter-distr}\n\nInfine si prende il logaritmo per ottenere il log-score.\n\n### La LPPD: una misura complessiva\n\nRipetendo il procedimento per tutte le osservazioni e sommando otteniamo la *Log Pointwise Predictive Density (LPPD):*\n\n$$\n\\text{LPPD} = \\sum_{i=1}^n \\log \\left[ \\frac{1}{S} \\sum_{s=1}^S p(y_i \\mid \\theta^{(s)}) \\right].\n$$ {#eq-lppd-def}\n\n* **Log-score classico**: valuta le predizioni con un solo $\\hat{\\theta}$ → ignora l’incertezza.\n* **LPPD bayesiana**: media le predizioni su tutti i parametri plausibili → incorpora l’incertezza in modo naturale.\n\n### Il problema nascosto: overfitting in-sample\n\nLa LPPD è calcolata sugli stessi dati usati per stimare il modello. Un modello molto flessibile può adattarsi perfettamente anche al rumore, ottenendo una LPPD alta *in-sample* ma poco utile per generalizzare.\n\n**Analogia:** è come valutare uno studente facendogli ripetere gli stessi esercizi studiati a memoria: punteggio alto, ma poca garanzia di riuscire con esercizi nuovi.\n\nPer questo serve una misura *out-of-sample*: l’ELPD stimato con la validazione incrociata (LOO), che vedremo subito.\n\n::: {.callout-note collapse=true title=\"Esempio pratico: calcolo della LPPD\"}\nSupponiamo un singolo dato $y_i=3$ successi su $n=5$.\nAbbiamo tre possibili valori di $\\theta$ dalla posteriore, con pesi didattici:\n\n* $\\theta^{(1)}=0.3$, $w^{(1)}=0.2$\n* $\\theta^{(2)}=0.5$, $w^{(2)}=0.5$\n* $\\theta^{(3)}=0.7$, $w^{(3)}=0.3$\n\nPer ciascun $\\theta^{(s)}$ calcoliamo $p(y_i \\mid \\theta^{(s)})$, poi facciamo la media pesata (eq. @eq-mcmc-posterior-parameter-distr), e infine il log.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ny_i  <- 3\nn_i  <- 5\ntheta_vals        <- c(0.3, 0.5, 0.7)\nposterior_weights <- c(0.2, 0.5, 0.3)\n\n# 1. Likelihood per ogni campione\nlikelihoods <- dbinom(y_i, size = n_i, prob = theta_vals)\n\n# 2. Media pesata delle likelihood\np_yi_given_y <- sum(posterior_weights * likelihoods)\n\n# 3. Log-score (per un solo dato)\nlog_score_i <- log(p_yi_given_y)\n\ncbind(theta_vals, likelihoods)\n#>      theta_vals likelihoods\n#> [1,]        0.3       0.132\n#> [2,]        0.5       0.312\n#> [3,]        0.7       0.309\np_yi_given_y\n#> [1] 0.275\nlog_score_i\n#> [1] -1.29\n```\n:::\n\n\nCon più osservazioni ${y_i}_{i=1}^n$, la LPPD è la somma dei log-score punto per punto (@eq-lppd-def).\n:::\n\n## La svolta: dall’adattamento alla generalizzazione\n\n### Il problema dell’overfitting spiegato\n\nImmagina di voler valutare la capacità di uno studente di *riconoscere emozioni nei volti*.\n\n1. **Scenario A:** lo testi sempre con le *stesse fotografie* viste durante l’allenamento.\n2. **Scenario B:** lo testi con *fotografie nuove* di persone mai viste prima.\n\nNel primo caso, lo studente probabilmente ottiene un punteggio alto, ma non sappiamo se ha davvero imparato a riconoscere le emozioni o se sta semplicemente ricordando quelle immagini specifiche. Il secondo scenario è più onesto: misura la *capacità di generalizzazione*.\n\nQuesto è esattamente il passaggio da *LPPD* a *ELPD*:\n\n* **LPPD** (in-sample) ≈ Scenario A: valuta quanto bene il modello “ricorda” i dati visti.\n* **ELPD** (out-of-sample) ≈ Scenario B: valuta quanto bene il modello *generalizza* a casi nuovi.\n\n### Guardare oltre i dati osservati\n\nQuando valutiamo un modello, non basta chiedersi *quanto bene spiega i dati già visti*. La domanda giusta è: *quanto bene predirebbe dati nuovi, mai osservati?*\n\nLa *Expected Log Predictive Density (ELPD)* risponde proprio a questa domanda. La logica è la stessa della LPPD (si sommano log-verosimiglianze punto per punto), ma con una differenza cruciale: *per valutare $y_i$ non usiamo $y_i$ nell'addestramento*.\n\nLa tecnica operativa è la *Leave-One-Out (LOO)*:\n\n$$\n\\widehat{\\mathrm{ELPD}}_{\\mathrm{LOO}} \\;=\\; \\sum_{i=1}^n \\log p(y_i \\mid y_{-i}),\n$$ {#eq-elpd-loo}\ndove $y_{-i}$ indica il dataset a cui è stata tolta l'osservazione $i$. In questo modo ogni punto è valutato *fuori campione*, proprio come nello Scenario B.\n\n### Un esempio concreto per chiarire la differenza\n\nSupponi di costruire un modello che predice i *punteggi di memoria a breve termine* a partire dal livello di concentrazione.\n\n* Con **LPPD**, valuti il modello sugli *stessi studenti* usati per stimarlo:\n  “Quanto bene spiega questi dati noti?”\n* Con **ELPD (LOO)**, togli uno studente alla volta, stimi il modello sugli altri e *predici* il punteggio dello studente escluso: “Quanto bene predirebbe un *nuovo* studente?”\n\n### Procedura passo-passo (LOO)\n\n1. **Esclusione**: si rimuove la prima osservazione $y_1$ dal dataset.\n2. **Stima del modello**: si adatta il modello ai dati rimanenti $y_{-1}$.\n3. **Valutazione predittiva**: si calcola la densità predittiva $p(y_1 \\mid y_{-1})$ e il corrispondente logaritmo.\n4. **Iterazione**: si ripete la procedura per ogni osservazione $i = 1, \\dots, n$.\n5. **Aggregazione**: si sommano tutti i valori di log-verosimiglianza ottenuti, ricavando così $\\widehat{\\mathrm{ELPD}}_{\\mathrm{LOO}}$.\n\n::: {.callout-tip title=\"Punti chiave operativi\"}\n* **LPPD** misura l'accuratezza *sui dati di stima* e può sovrastimare le prestazioni per modelli flessibili (rischio di overfitting).\n* **ELPD (LOO)** fornisce una stima più realistica della *capacità di generalizzazione* del modello.\n* Nella pratica, riadattare il modello $n$ volte risulta computazionalmente oneroso: si utilizza **PSIS-LOO** per stimare $\\widehat{\\mathrm{ELPD}}_{\\mathrm{LOO}}$ a partire da un singolo adattamento, con diagnostiche (*Pareto-k*) per valutarne l'affidabilità.\n* In presenza di dati **dipendenti o gerarchici**, l'unità di \"leave-one-out\" deve corrispondere al *cluster* (ad esempio, il soggetto), non alla singola osservazione.\n:::\n\n## Il collegamento con la divergenza KL\n\n### La teoria che unifica tutto\n\nAbbiamo visto che l’ELPD fornisce una misura empirica della capacità predittiva di un modello. Ma perché proprio l’ELPD è la scelta corretta? La giustificazione profonda poggia su un concetto centrale della teoria dell’informazione: la *divergenza di Kullback–Leibler (KL)*.\n\n### Cosa misura la divergenza KL?\n\nLa divergenza KL, $D_{\\text{KL}}$, quantifica la distanza informazionale tra:\n\n* la *distribuzione vera dei dati futuri* $p(\\tilde{y})$, che rappresenta la realtà (sconosciuta);\n* la *distribuzione predittiva del modello* $q(\\tilde{y}\\mid y)$, che rappresenta la nostra approssimazione.\n\nFormalmente:\n\n$$\nD_{\\text{KL}}(p \\parallel q) \\;=\\; \\mathbb{E}_p \\left[ \\log \\frac{p(\\tilde{y})}{q(\\tilde{y} \\mid y)} \\right],\n$$\ndove l’aspettativa $\\mathbb{E}_p$ è presa rispetto alla distribuzione vera $p$.\n\n### Scomposizione della divergenza KL\n\nPossiamo riscrivere la formula come:\n\n$$\nD_{\\text{KL}}(p \\parallel q)\n\\;=\\;\n\\underbrace{\\mathbb{E}_{p}\\big[\\log p(\\tilde{y})\\big]}_{-H(p)}\n\\;-\\;\n\\underbrace{\\mathbb{E}_{p}\\big[\\log q(\\tilde{y} \\mid y)\\big]}_{\\text{accuratezza predittiva (ELPD teorica)}}.\n$$ {#eq-kl-decomposition}\n\n> Nota: $H(p) = -\\mathbb{E}_{p}[\\log p(\\tilde{y})]$, quindi $\\mathbb{E}_{p}[\\log p(\\tilde{y})] = -H(p)$.\n\n* **(1) Entropia di $p$**: rappresenta l’incertezza intrinseca della distribuzione vera. È una costante, indipendente dal modello.\n* **(2) Accuratezza predittiva**: misura quanto il modello $q$ assegna probabilità alte agli eventi che davvero accadono. Questo termine è esattamente ciò che stimiamo con l’ELPD.\n\n### Il collegamento fondamentale\n\nPoiché l’entropia di $p$ è costante, *minimizzare la divergenza KL equivale a massimizzare l’ELPD*.\n\nDate due distribuzioni predittive $q_A$ e $q_B$, la differenza nelle rispettive divergenze KL si riduce a:\n\n$$\nD_{\\text{KL}}(p \\parallel q_A) - D_{\\text{KL}}(p \\parallel q_B)\n= \\mathrm{ELPD}(q_B) - \\mathrm{ELPD}(q_A).\n$$\n\n### Conclusione teorica fondamentale\n\n$$\n\\text{Massimizzare l’ELPD} \\;\\;\\equiv\\;\\; \\text{Minimizzare la divergenza KL dalla verità}.\n$$\n\nIn altre parole, scegliere il modello con l’ELPD più alto significa scegliere quello la cui distribuzione predittiva è, in media, *più vicina alla realtà*.\n\nQuesto principio unifica teoria dell’informazione e pratica statistica: ELPD non è solo un criterio empirico, ma la traduzione operativa del principio di *minimizzazione della distanza dalla verità*.\n\n::: {.callout-note}\n**Messaggio chiave.**\nL’ELPD è la stima empirica di (meno) la divergenza KL.\nPiù alto è l’ELPD → più bassa è la divergenza KL → migliore è la capacità predittiva.\n:::\n\n### Esempio: collegamento ELPD–KL in pratica\n\nSupponiamo di voler predire il numero di “teste” in $n=10$ lanci di una moneta:\n\n* **Distribuzione vera**: $p(y) = \\text{Binom}(n=10, p=0.6)$.\n* **Modello candidato**: $q(y) = \\text{Binom}(n=10, q=0.5)$.\n\nCalcoliamo l’ELPD per il modello candidato e confrontiamolo con quello del “modello vero”:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn <- 10\np <- 0.6   # probabilità vera\nq <- 0.5   # probabilità del modello candidato\n\ny_vals <- 0:n\np_y    <- dbinom(y_vals, size = n, prob = p)      # distribuzione vera\nlog_q  <- log(dbinom(y_vals, size = n, prob = q)) # log-predittiva modello q\nlog_p  <- log(dbinom(y_vals, size = n, prob = p)) # log-predittiva modello p\n\n# ELPD\nelpd_q <- sum(p_y * log_q)\nelpd_p <- sum(p_y * log_p)\n\n# Divergenza KL\nkl_pq  <- sum(p_y * (log_p - log_q))\n\ncat(sprintf(\"ELPD modello candidato (q=0.5): %.4f\\n\", elpd_q))\n#> ELPD modello candidato (q=0.5): -2.0549\ncat(sprintf(\"ELPD modello vero      (q=0.6): %.4f\\n\", elpd_p))\n#> ELPD modello vero      (q=0.6): -1.8536\ncat(sprintf(\"Differenza ELPD (vero - candidato): %.4f\\n\", elpd_p - elpd_q))\n#> Differenza ELPD (vero - candidato): 0.2014\ncat(sprintf(\"KL(p || q): %.4f\\n\", kl_pq))\n#> KL(p || q): 0.2014\n```\n:::\n\n\n**Risultati attesi:**\n\n* L’ELPD del modello candidato è più basso rispetto a quello del modello vero.\n* La differenza tra i due ELPD coincide con la divergenza KL $D_{\\text{KL}}(p|q)$.\n\nQuesto mostra sia algebricamente sia numericamente che *massimizzare ELPD = minimizzare KL*.\n\n## Stima dell'ELPD nella pratica: il metodo Leave-One-Out Cross-Validation\n\nCome abbiamo stabilito, l'ELPD rappresenta la misura ideale per valutare la capacità predittiva di un modello, grazie alla sua diretta connessione con la divergenza di Kullback-Leibler. Tuttavia, la sua definizione teorica richiede il calcolo di un'aspettativa rispetto alla vera distribuzione dei dati futuri $p(\\tilde{y})$, che nella pratica risulta sempre ignota.\n\n*In che modo è possibile stimare questa quantità?* La soluzione metodologicamente più solida è offerta dalla *Leave-One-Out Cross-Validation* (LOO-CV), una procedura che consente di approssimare l'ELPD teorico utilizzando esclusivamente i dati osservati.\n\n### L’idea alla base della LOO-CV\n\nL'approccio Leave-One-Out si basa su un concetto intuitivo ma potente: utilizzare ciascuna osservazione del dataset come dato \"nuovo\", valutando la capacità del modello - stimato sulle restanti osservazioni - di prevederla adeguatamente.\n\nLa procedura si articola nei seguenti passi:\n\n1. **Isolamento**: si seleziona un'osservazione $y_i$ dal dataset.\n2. **Esclusione**: la si rimuove temporaneamente dal campione di stima.\n3. **Stima**: si adatta il modello ai dati rimanenti $y_{-i}$.\n4. **Valutazione**: si calcola la densità predittiva per l'osservazione esclusa, $q(y_i \\mid y_{-i})$.\n5. **Iterazione**: si ripete il processo per tutte le $n$ osservazioni.\n6. **Aggregazione**: si sommano i logaritmi delle densità predittive ottenute.\n\nFormalmente:\n\n$$\n\\mathrm{ELPD}_{\\mathrm{LOO}} \\;=\\; \\sum_{i=1}^n \\log q(y_i \\mid y_{-i}) .\n$$ {#eq-elpd-loo}\nIl risultato è una stima *out-of-sample* genuina: ciascuna osservazione viene valutata da un modello stimato in sua assenza, garantendo così una valutazione imparziale della capacità predittiva.\n\n### Perché funziona\n\nLa LOO-CV sostituisce l’aspettativa teorica rispetto a $p(\\tilde{y})$ con una media empirica sulle osservazioni reali. Ogni $y_i$ è trattata come nuovo dato generato da $p$, e la media dei log-score fuori campione fornisce una stima della capacità predittiva attesa:\n\n$$\n\\mathrm{ELPD}_{\\mathrm{LOO}} \\;\\approx\\; \\mathbb{E}_{p}\\!\\left[\\log q(\\tilde{y}\\mid y)\\right].\n$$ {#eq-elpd-loo-interpretation}\n\n### Confrontare i modelli con LOO-CV\n\nUna volta ottenuta la stima dell'ELPD-LOO per ciascun modello, il confronto avviene calcolando la differenza:\n\n$$\n\\Delta \\mathrm{ELPD} \\;=\\; \\mathrm{ELPD}_{\\mathrm{LOO}}(M_1) - \\mathrm{ELPD}_{\\mathrm{LOO}}(M_2).\n$$ {#eq-delta-elpd}\n\nUn valore positivo di $\\Delta \\mathrm{ELPD}$ indica una migliore capacità predittiva del modello $M_1$ rispetto a $M_2$. Per una valutazione completa, è fondamentale accompagnare questa differenza con il suo errore standard: secondo una regola empirica consolidata, un vantaggio pari ad almeno due errori standard può considerarsi credibile.\n\n> **Coerenza metodologica:** nei confronti tra modelli, è essenziale mantenere la stessa definizione puntuale della verosimiglianza (identica unità di osservazione o cluster) attraverso tutti i modelli analizzati.\n\n### Overfitting e vantaggi della validazione LOO\n\nLa valutazione di un modello sugli stessi dati utilizzati per la stima tende a sovrastimarne sistematicamente le prestazioni, un fenomeno noto come overfitting. La validazione Leave-One-Out (LOO) supera questa limitazione strutturale: ciascuna osservazione $y_i$ viene valutata da un modello stimato escludendo proprio $y_i$, producendo così una stima più realistica della capacità predittiva del modello su nuovi dati.\n\n### PSIS-LOO: l'approssimazione efficiente\n\nIl refitting ripetuto del modello per ciascuna osservazione risulta spesso proibitivo dal punto di vista computazionale. Il metodo *Pareto-Smoothed Importance Sampling LOO* (PSIS-LOO) supera questa limitazione stimando $\\mathrm{ELPD}_{\\mathrm{LOO}}$ a partire da un'unica campionatura MCMC, offrendo al contempo strumenti diagnostici per valutarne l'affidabilità.\n\n* **Diagnostica Pareto-$k$** (interpretazione orientativa):\n  - $k \\leq 0.5$: stima affidabile\n  - $0.5 < k \\leq 0.7$: attendibilità moderata, interpretare con cautela\n  - $k > 0.7$: possibile instabilità → considerare alternative come *K-fold CV*, LOO per cluster o refitting mirato\n\n* **Vantaggi principali**: efficienza computazionale, stima puntuale dell'ELPD con errore standard, e controllo qualità attraverso il parametro $k$.\n\nIn R, le metodologie descritte sono implementate nel pacchetto `loo`, che risulta già integrato negli ambienti `brms` e `rstanarm` attraverso le funzioni `loo()` e `loo_compare()`. Per gli utenti che lavorano direttamente con Stan, è sufficiente calcolare la *log-verosimiglianza punto per punto* all'interno del blocco `generated quantities` e successivamente passare l'output alla funzione `loo::loo()`.\n\n::: {.callout-note title=\"Validazione per cluster\"}\nIn presenza di dati dipendenti (come nei studi EMA, misure ripetute o trial multipli per soggetto), la procedura LOO deve essere applicata a livello di cluster. Ciò significa che per ogni validazione si esclude l'intero gruppo di osservazioni correlate (ad esempio, tutti i dati di un soggetto o di una sessione sperimentale), preservando così la struttura di dipendenza dei dati.\n:::\n\n### Sintesi concettuale\n\n* L'ELPD quantifica la capacità predittiva del modello su dati non osservati.\n* In assenza della distribuzione vera $p(\\tilde{y})$, la procedura LOO-CV ne fornisce una stima empirica.\n* Le differenze nell'ELPD-LOO tra modelli approssimano le relative divergenze di Kullback-Leibler.\n* L'implementazione PSIS-LOO garantisce efficienza computazionale e include diagnostiche di affidabilità (parametro $k$ di Pareto).\n* Linea guida operativa: privilegiare i modelli con ELPD-LOO più elevato, riportando sistematicamente $\\Delta \\mathrm{ELPD}$ *con il corrispondente errore standard*, e integrando la valutazione con considerazioni sulla parsimonia e l'interpretabilità.\n\n::: {.callout-note collapse=true title=\"Esempio: confronto ELPD-LOO tra due modelli\"}\nQuesto esempio mostra come passare dalla definizione teorica dell’ELPD alla stima pratica via LOO, nel caso elementare Beta–Bernoulliano.\n\n**Dati:** $y=\\{1,1,1,0,1\\}$ (cinque prove indipendenti: quattro successi, un insuccesso).\n\n**Modello A (Bayesiano):** $Y\\sim\\mathrm{Bernoulli}(\\theta)$, prior $\\theta\\sim \\mathrm{Beta}(1,1)$.\nPer LOO, per ogni $i$:\n\n* escludi $y_i$;\n* posteriore $\\theta \\mid y_{-i} \\sim \\mathrm{Beta}(1+s_{-i},\\,1+(n-1)-s_{-i})$;\n* predittiva per $y_i$: $q(y_i=1\\mid y_{-i}) = \\dfrac{\\alpha}{\\alpha+\\beta}$.\n\n**Modello B (confronto):** moneta equa fissa ($q=0.5$).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Dati\ny <- c(1, 1, 1, 0, 1)\nn <- length(y)\n\n# Log-predittiva LOO per Modello A (Beta(1,1) + Bernoulli)\nloo_log_pred_beta <- function(i, y, a0 = 1, b0 = 1) {\n  yi <- y[i]\n  s_minus <- sum(y) - yi         # successi tra i rimanenti\n  n_minus <- n - 1\n  alpha <- a0 + s_minus\n  beta  <- b0 + (n_minus - s_minus)\n  p1 <- alpha / (alpha + beta)   # P(y=1 | y_-i)\n  p  <- if (yi == 1) p1 else (1 - p1)\n  log(p)\n}\n\n# Log-predittive punto-per-punto\nlp_A <- sapply(seq_along(y), loo_log_pred_beta, y = y)\nlp_B <- rep(log(0.5), n)\n\n# ELPD-LOO\nelpd_A <- sum(lp_A)\nelpd_B <- sum(lp_B)\n\n# Differenza e SE (stima semplice da varianza dei contributi puntowise)\ndiff_pt <- lp_A - lp_B\nse_diff <- sqrt(n * var(diff_pt))\n\n# Tabella riassuntiva\nres <- data.frame(\n  i = 1:n, y = y,\n  lp_A = round(lp_A, 6),\n  lp_B = round(lp_B, 6),\n  diff = round(diff_pt, 6)\n)\nprint(res)\n#>   i y   lp_A   lp_B   diff\n#> 1 1 1 -0.405 -0.693  0.288\n#> 2 2 1 -0.405 -0.693  0.288\n#> 3 3 1 -0.405 -0.693  0.288\n#> 4 4 0 -1.792 -0.693 -1.099\n#> 5 5 1 -0.405 -0.693  0.288\ncat(sprintf(\"\\nELPD-LOO Modello A: %.6f\\n\", elpd_A))\n#> \n#> ELPD-LOO Modello A: -3.413620\ncat(sprintf(\"ELPD-LOO Modello B: %.6f\\n\", elpd_B))\n#> ELPD-LOO Modello B: -3.465736\ncat(sprintf(\"Differenza (A-B)  : %.6f\\n\", elpd_A - elpd_B))\n#> Differenza (A-B)  : 0.052116\ncat(sprintf(\"SE differenza     : %.6f\\n\", se_diff))\n#> SE differenza     : 1.386294\n```\n:::\n\n\n**Interpretazione:** ogni riga è il log-score *fuori campione* dei due modelli. Con 4/5 successi, il Modello A assegna probabilità $>0.5$ ai successi (e $<0.5$ all’unico insuccesso), quindi tende ad avere ELPD-LOO più alto. Con $n$ piccolo, l’SE è grande: la lezione è didattica, non inferenziale.\n\n> **Regola pratica:** $|\\Delta \\mathrm{ELPD}| \\ge 2 \\times \\mathrm{SE}$ → evidenza credibile a favore del modello migliore.\n:::\n\n::: {.callout-note title=\"Implementazione pratica: stima e confronto dell'ELPD-LOO\"}\n**Strumenti computazionali**\n\n* Funzioni `loo::loo()` e `loo::loo_compare()` nel pacchetto R omonimo; già integrate negli ambienti `brms` e `rstanarm`.\n* **Implementazione Stan personalizzata**: memorizzare la *log-verosimiglianza puntuale* nel blocco `generated quantities` e fornire la matrice risultante a `loo()`.\n\n**Procedura operativa**\n\n1. Stimare ciascun modello candidato (`brm()`, `stan_glm()` o codice Stan personalizzato).\n2. Estrarre la *log-verosimiglianza puntuale* (tramite `log_lik()` o variabile definita in Stan).\n3. Applicare `loo()` per ottenere ELPD, errore standard e diagnostiche Pareto-$k$\n4. Confrontare i modelli con `loo_compare()`, riportando $\\Delta \\mathrm{ELPD}$ ed errore standard.\n5. In presenza di valori elevati di Pareto-$k$: ricorrere a *K-fold CV*, LOO per cluster, o valutare un refitting più robusto.\n\n**Criteri decisionali**\n\n* Privilegiare i modelli con valori più elevati di ELPD-LOO.\n* Comunicare sistematicamente $\\Delta \\mathrm{ELPD}$ *accompagnato dall'errore standard*.\n* Per differenze inferiori a $2\\times \\mathrm{SE}$, considerare prioritariamente parsimonia e interpretabilità.\n* Nel caso di serie temporali, adottare schemi di validazione *leave-future-out* strutturati a blocchi temporali.\n:::\n\n## Criteri di informazione per la valutazione dei modelli\n\nLa *metrica fondamentale* per la valutazione predittiva è l'ELPD (*Expected Log Predictive Density*), che misura quanto la distribuzione predittiva del modello $q(\\tilde{y} \\mid y)$ si avvicini alla distribuzione vera dei dati $p(\\tilde{y})$, minimizzando la divergenza di Kullback-Leibler. I *criteri di informazione* costituiscono diverse approssimazioni - di varia accuratezza - per stimare questa capacità predittiva *su nuovi dati*, bilanciando in modo ottimale il trade-off tra adattamento ai dati osservati e complessità del modello.\n\nTra i vari criteri disponibili, LOO e WAIC rappresentano le approssimazioni concettualmente più vicine all'ELPD in un'ottica bayesiana, mentre AIC e BIC si collocano nell'ambito della statistica frequentista, dove funzionano bene per modelli con strutture parametriche semplici e dati indipendenti. Essendo statistiche asintotiche, il loro utilizzo richiede campioni di dati di numerosità elevata per garantire stime affidabili.\n\n### Panoramica dei criteri di valutazione\n\n**AIC** – *Per modelli classici*  \nStima la divergenza KL basandosi sulla verosimiglianza massimizzata.  \n$\\text{AIC} = -2\\log p(y\\mid \\hat\\theta) + 2k$  \nPenalità fissa: $2k$ parametri  \nIdeale per: campioni grandi, modelli regolari senza gerarchie\n\n**BIC** – *Per modelli parsimoniosi*  \nApprossima la verosimiglianza marginale, favorendo la semplicità.  \n$\\text{BIC} = -2\\log p(y\\mid \\hat\\theta) + k\\log n$  \nPenalità crescente: $k\\log n$  \nAdatto a: selezione del modello \"vero\", non predizione\n\n**WAIC** – *Approccio bayesiano*  \nStima direttamente l'accuratezza predittiva in ottica bayesiana.  \n$\\text{elpd}_{\\text{waic}} = \\sum_i \\log \\big(\\tfrac{1}{S}\\sum_s p(y_i\\mid \\theta^{(s)})\\big) - p_{\\text{waic}}$  \nPenalità adattiva: $p_{\\text{waic}} = \\sum_i V_s[\\log p(y_i\\mid \\theta^{(s)})]$  \nUtilizzo: alternativa pratica a LOO, richiede likelihood puntuale\n\n**LOO (PSIS-LOO)** – *Riferimento predittivo*  \nStima l'ELPD mediante validazione leave-one-out.  \n$\\text{elpd}_{\\text{loo}} = \\sum_i \\log q(y_i\\mid y_{-i})$  \nPenalità stimata: $p_{\\text{loo}} \\approx \\sum_i (\\text{lppd}_i - \\text{elpd}_{\\text{loo},i})$  \nVantaggi: efficiente con PSIS, include diagnostiche di affidabilità\n\n> $V_s[\\cdot] = \\operatorname{Var}_s[\\cdot]$; $\\text{lppd}_i = \\log\\big(\\tfrac{1}{S}\\sum_s p(y_i\\mid \\theta^{(s)})\\big)$\n\n::: {.callout-tip title=\"Scala e convenzioni (Stan/loo)\"}\n* **Scala ELPD:** più alto è meglio.\n* **Scala IC (devianza):** $\\text{LOOIC}=-2,\\text{elpd}*{\\text{loo}}$, $\\text{WAIC}=-2,\\text{elpd}*{\\text{waic}}$ → più basso è meglio.\n* In `loo`, `brms` e `rstanarm` troverai sia $\\text{elpd}$ e SE, sia l’IC corrispondente. Riporta **sempre** $\\Delta \\text{ELPD}$ con il suo SE.\n:::\n\n### Linee guida per la scelta del criterio\n\n* **Predizione bayesiana su nuovi dati** → **PSIS-LOO** costituisce lo strumento privilegiato, con **WAIC** come utile riscontro, data la frequente convergenza dei risultati.\n\n* **Modelli frequentisti regolari** → **AIC** offre una soluzione immediata per campioni di ampiezza medio-elevata e strutture semplici, mentre **BIC** risulta preferibile quando si intende enfatizzare la parsimonia o la consistenza asintotica.\n\n* **Strutture gerarchiche e dati dipendenti** → è fondamentale identificare correttamente l'unità di predizione *pointwise*, generalmente **il cluster**; in tali contesti, LOO e WAIC mantengono la loro validità, a differenza di AIC e BIC.\n\n* **Analisi di serie storiche** → si raccomandano protocolli di validazione *leave-future-out* strutturati a blocchi, in alternativa all'applicazione standard del LOO.\n\n### Penalizzazione \"effettiva\" e complessità del modello\n\nNei modelli bayesiani, la complessità non corrisponde al mero numero di parametri, ma dipende criticamente da quanto i dati siano informativi riguardo ai parametri stessi. I criteri WAIC e LOO quantificano una *penalizzazione effettiva* ($p_{\\text{waic}}$, $p_{\\text{loo}}$) basata sulla variabilità della log-verosimiglianza posteriore punto per punto. Questo approccio genera una penalizzazione adattiva, che riflette più fedelmente la complessità reale del modello, particolarmente in contesti gerarchici o non regolari.\n\n## Guida operativa alla valutazione dei modelli\n\n### Workflow principale\n\n> **Preparazione:** definisci l'unità di validazione appropriata (singole osservazioni per dati indipendenti, interi cluster per dati raggruppati).\n\n1. **Stima** i modelli candidati\n2. **Estrai** la verosimiglianza punto per punto dalle simulazioni posteriori\n3. **Calcola** PSIS-LOO (`loo()`) per ottenere:\n   - $\\mathrm{elpd}_{\\mathrm{loo}}$ e errore standard\n   - Diagnostiche Pareto-$k$\n4. **Confronta** i modelli con `loo_compare()`\n5. **Interpreta** i risultati considerando:\n   - Differenze di ELPD e relativa incertezza\n   - Semplicità e interpretabilità del modello\n   - Adeguatezza al contesto applicativo\n\n### Errori da evitare e controlli essenziali\n\n* **Metriche in-sample** → Evita MSE sui dati di training (sovrastima le prestazioni). *Usa* ELPD-LOO o WAIC.\n* **Scale incoerenti** → Non confrontare direttamente AIC/BIC con ELPD. *Calcola* differenze sulla stessa scala (ΔELPD).\n* **Validazione impropria** → Con dati raggruppati, *escludi* interi cluster, non singole osservazioni.\n* **Diagnostiche ignorate** → Con PSIS-LOO:\n  - $k \\le 0.5$: procedi con fiducia\n  - $0.5 < k \\le 0.7$: risultati da interpretare con cautela\n  - $k > 0.7$: passa a K-fold CV per stime più robuste\n* **Incertezza trascurata** → *Riporta sempre* l'errore standard di ΔELPD.\n* **Pre-processing scorretto** → Trasformazioni e selezione di variabili vanno *ripetute* per ogni fold di validazione.\n\n### Approccio complementare\n\n**(Raccomandato)** Calcola WAIC come verifica aggiuntiva di robustezza. I due criteri (LOO e WAIC) dovrebbero convergere verso conclusioni simili.\n\n**Orientamento finale:** Tutti i criteri mirano a stimare l'ELPD. AIC e BIC offrono approssimazioni classiche, mentre WAIC e LOO rappresentano le controparti bayesiane più dirette. La scelta dello strumento dipende dalla struttura dei dati, ma la comunicazione dei risultati deve sempre includere sia l'entità delle differenze che la loro incertezza.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nIl principio guida di questo capitolo è semplice: **un buon modello è quello che fa buone previsioni su dati che non ha mai visto**. Nel paradigma bayesiano, questo si traduce nell'uso della *distribuzione predittiva a posteriori* $p(\\tilde y \\mid y)$ e nella sua bontà, misurata dall'*Expected Log Predictive Density (ELPD)*—l'accuratezza predittiva attesa su dati futuri. Dal punto di vista teorico, massimizzare l'ELPD equivale a minimizzare la divergenza di Kullback-Leibler dalla verità, creando un ponte diretto tra teoria dell'informazione e pratica della modellistica.\n\nSul piano operativo, l'ELPD viene stimato in modo efficiente con *PSIS-LOO*, che, partendo da un unico adattamento del modello, fornisce anche le fondamentali diagnostiche *Pareto-$k$* per valutarne l'affidabilità. *WAIC* rappresenta un'alternativa pienamente bayesiana, spesso in accordo con LOO. *AIC* e *BIC*, sebbene utili in contesti classici e regolari, possono risultare fuorvianti in scenari bayesiani con piccoli campioni, strutture gerarchiche o dipendenze complesse, poiché si basano su stime puntuali e approssimazioni asintotiche.\n\nNel confronto tra modelli, non ci si deve limitare a dichiarare un vincitore. È una buona pratica di reporting includere:\n\n*   I valori di $\\text{ELPD}_{\\text{LOO}}$ (o LOOIC, su scala devianza);\n*   Le *differenze* $\\Delta \\mathrm{ELPD}$ con i relativi *errori standard*;\n*   Un *riepilogo delle diagnostiche Pareto-$k$* (es., numero di osservazioni con $k>0.7$) e le eventuali azioni intraprese (K-fold, LOO per cluster, refit mirato);\n*   L'*ELPD per osservazione* ($\\mathrm{ELPD}/n$) quando si confrontano dataset di dimensioni diverse.\n\nÈ cruciale scegliere l'unità di predizione corretta (ad esempio, *per cluster* in dati gerarchici) e adottare schemi *leave-future-out* in presenza di *dipendenze temporali*. Ricorda che molti software (come l'ecosistema Stan/`loo`) riportano i risultati anche in *scala devianza* ($\\text{LOOIC} = -2 \\cdot \\text{ELPD}_{\\text{LOO}}$): in questo caso, *valori più bassi indicano un modello migliore*.\n\nInfine, la selezione del modello *non è un processo meccanico*. Differenze esigue nell'ELPD, specialmente se accompagnate da un errore standard ampio, raramente hanno rilevanza sostanziale. In questi casi, è preferibile privilegiare *parsimonia* e *coerenza teorica*. L'obiettivo ultimo non è solo prevedere, ma *comprendere*. L'ELPD e la LOO forniscono una bussola quantitativa preziosa, che deve essere integrata con la conoscenza del dominio, la struttura dei dati e l'interpretabilità del modello.\n\n**Messaggio fondamentale:** il modello migliore è quello che *predice meglio il futuro* senza sacrificare *interpretabilità* e *coerenza teorica*.\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.5.1 (2025-06-13)\n#> Platform: aarch64-apple-darwin20\n#> Running under: macOS Tahoe 26.0\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] gt_1.1.0              ragg_1.5.0            tinytable_0.13.0     \n#>  [4] withr_3.0.2           systemfonts_1.2.3     patchwork_1.3.2      \n#>  [7] ggdist_3.3.3          tidybayes_3.0.7       bayesplot_1.14.0     \n#> [10] ggplot2_4.0.0         reliabilitydiag_0.2.1 priorsense_1.1.1     \n#> [13] posterior_1.6.1       loo_2.8.0             rstan_2.32.7         \n#> [16] StanHeaders_2.32.10   brms_2.23.0           Rcpp_1.1.0           \n#> [19] sessioninfo_1.2.3     conflicted_1.2.0      janitor_2.2.1        \n#> [22] matrixStats_1.5.0     modelr_0.1.11         tibble_3.3.0         \n#> [25] dplyr_1.1.4           tidyr_1.3.1           rio_1.2.4            \n#> [28] here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] gridExtra_2.3         inline_0.3.21         sandwich_3.1-1       \n#>  [4] rlang_1.1.6           magrittr_2.0.4        multcomp_1.4-28      \n#>  [7] snakecase_0.11.1      compiler_4.5.1        vctrs_0.6.5          \n#> [10] stringr_1.5.2         pkgconfig_2.0.3       arrayhelpers_1.1-0   \n#> [13] fastmap_1.2.0         backports_1.5.0       rmarkdown_2.30       \n#> [16] purrr_1.1.0           xfun_0.53             cachem_1.1.0         \n#> [19] jsonlite_2.0.0        broom_1.0.10          parallel_4.5.1       \n#> [22] R6_2.6.1              stringi_1.8.7         RColorBrewer_1.1-3   \n#> [25] lubridate_1.9.4       estimability_1.5.1    knitr_1.50           \n#> [28] zoo_1.8-14            Matrix_1.7-4          splines_4.5.1        \n#> [31] timechange_0.3.0      tidyselect_1.2.1      abind_1.4-8          \n#> [34] codetools_0.2-20      curl_7.0.0            pkgbuild_1.4.8       \n#> [37] lattice_0.22-7        bridgesampling_1.1-2  S7_0.2.0             \n#> [40] coda_0.19-4.1         evaluate_1.0.5        survival_3.8-3       \n#> [43] RcppParallel_5.1.11-1 xml2_1.4.0            pillar_1.11.1        \n#> [46] tensorA_0.36.2.1      checkmate_2.3.3       stats4_4.5.1         \n#> [49] distributional_0.5.0  generics_0.1.4        rprojroot_2.1.1      \n#> [52] rstantools_2.5.0      scales_1.4.0          xtable_1.8-4         \n#> [55] glue_1.8.0            emmeans_1.11.2-8      tools_4.5.1          \n#> [58] fs_1.6.6              mvtnorm_1.3-3         grid_4.5.1           \n#> [61] QuickJSR_1.8.1        colorspace_2.1-2      nlme_3.1-168         \n#> [64] cli_3.6.5             textshaping_1.0.3     svUnit_1.0.8         \n#> [67] Brobdingnag_1.2-9     V8_8.0.0              gtable_0.3.6         \n#> [70] digest_0.6.37         TH.data_1.1-4         htmlwidgets_1.6.4    \n#> [73] farver_2.1.2          memoise_2.0.1         htmltools_0.5.8.1    \n#> [76] lifecycle_1.0.4       MASS_7.3-65\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n\n",
    "supporting": [
      "03_model_comparison_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}