{
  "hash": "8c051238c9834c727a3c60b66944a95b",
  "result": {
    "engine": "knitr",
    "markdown": "# Inferenza su una media: il modello a sola intercetta {#sec-mcmc-one-mean}\n\n::: {.callout-note appearance=\"minimal\"}\nNei capitoli precedenti, il modello lineare è stato introdotto prima con un solo predittore e poi esteso a più predittori. Qui compiamo il movimento opposto: eliminiamo tutti i predittori e osserviamo cosa rimane:\n\n$$\nY_i \\sim \\operatorname{Normal}(\\mu, \\sigma).\n$$\n\nQuesto è il **modello a sola intercetta**. Nella notazione della regressione,\n\n$$\nY_i = \\alpha + \\varepsilon_i, \\qquad \\varepsilon_i \\sim \\operatorname{Normal}(0, \\sigma),\n$$\n\ncon $\\alpha=\\mu$. \n\nLa semplicità del modello è utile dal punto di vista didattico, perché isola tre quantità che nei modelli più complessi possono essere facilmente confuse:\n\n- **la media della popolazione modellata, $\\mu$**, cioè il centro della distribuzione;\n- **la deviazione standard, $\\sigma$**, che descrive la dispersione delle osservazioni individuali attorno al centro;\n- **una nuova osservazione, $\\widetilde y$**, la cui incertezza comprende sia ciò che non sappiamo sui parametri sia la variabilità tra individui.\n\nNon introdurremo quindi un nuovo workflow. Utilizzeremo quello già sviluppato con `brms`, ma su un modello abbastanza semplice da rendere trasparente il significato delle quantità inferenziali che useremo nei capitoli successivi.\n:::\n\n::: {.callout-important appearance=\"minimal\" .chapter-status}\n**Da sapere.** L'inferenza su una media è un caso particolare del modello lineare: la matrice del modello contiene soltanto la colonna dell'intercetta. La distribuzione a posteriori di $\\mu$, la posterior di $\\sigma$ e la distribuzione predittiva di una nuova osservazione rispondono a domande differenti.\n\n**Da saper fare.** Riconoscere il modello `y ~ 1`; interpretare intercetta e deviazione standard sulla scala dell'outcome; formulare prior plausibili; adattare il modello con `brms`; distinguere l'incertezza sulla media dalla variabilità individuale; calcolare probabilità posteriori rispetto a soglie sostantive; interpretare una previsione per una nuova osservazione e un controllo predittivo a posteriori.\n\n**Approfondimento facoltativo.** Il confronto tra verosimiglianza normale e Student-$t$ è un'anticipazione del tema della revisione del modello e può essere saltato in una prima lettura. Il percorso essenziale termina dopo i controlli predittivi del modello normale.\n\n[Che cosa significano queste etichette?](../../guida-al-manuale.qmd#sec-percorsi-lettura)\n:::\n\n::: {.callout-tip collapse=true title=\"Prerequisiti\"}\n- Il modello lineare come modello generativo è introdotto nell'@sec-linear-generative.\n- Il workflow bayesiano completo con `brms` è sviluppato nell'@sec-linmod-bayesian-reg e qui viene dato per acquisito.\n- La relazione tra formule R e matrice del modello è discussa nell'@sec-multiple-regression.\n- Per il trattamento frequentista della media campionaria, del test $t$ e dell'intervallo di confidenza si veda il modulo [utet-frequentista](https://ccaudek.github.io/utet-frequentista).\n- L'esempio sulle altezze degli adulti !Kung San è tratto da @McElreath_rethinking.\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del notebook\"}\n\n\n:::\n\n## Dalla domanda scientifica alla quantità di interesse\n\nConsideriamo le altezze rilevate da Nancy Howell tra gli adulti !Kung San del Kalahari [@McElreath_rethinking]. La domanda è volutamente semplice:\n\n> Qual è il centro della distribuzione delle altezze nella popolazione rappresentata dal campione e quanta variabilità individuale osserviamo attorno a quel centro?\n\nNel modello normale a sola intercetta, questa domanda produce due parametri fondamentali:\n\n- $\\mu$: la media della popolazione modellata;\n- $\\sigma$: la deviazione standard delle altezze individuali attorno a $\\mu$.\n\nDalla distribuzione a posteriori possiamo poi costruire quantità derivate che rispondono a domande ulteriori. Per esempio:\n\n- $\\Pr(\\mu>c\\mid y)$, se esiste una soglia $c$ sostantivamente motivata;\n- $p(\\widetilde y\\mid y)$, se vogliamo descrivere l'altezza plausibile di una nuova persona proveniente dallo stesso processo modellato.\n\n::: {.callout-important title=\"Parametro, dispersione e previsione sono domande diverse\"}\nChiedere **dove si trova la media**, **quanto variano gli individui** e **quale valore potrebbe assumere una nuova osservazione** non equivale a formulare tre versioni della stessa domanda. Le tre domande richiedono, rispettivamente, la posterior di $\\mu$, la posterior di $\\sigma$ e la distribuzione predittiva a posteriori.\n:::\n\n::: {.callout-important title=\"La popolazione non è definita dal modello\"}\nIl modello può quantificare con grande precisione l'incertezza su $\\mu$ e $\\sigma$, ma non decide quali individui siano rappresentati dal campione. La generalizzazione dipende dalla procedura di campionamento, dalla popolazione effettivamente osservata e dalle condizioni nelle quali i dati sono stati raccolti. Un intervallo di credibilità stretto non compensa una popolazione target mal definita.\n:::\n\n### Che cosa cambia rispetto alla regressione\n\nDal punto di vista del workflow, quasi nulla. Continuiamo a specificare una distribuzione dei dati, assegnare prior ai parametri, adattare il modello, controllare il campionamento e confrontare repliche simulate con i dati osservati. Cambia soltanto la **componente sistematica**: non vi sono predittori e la media condizionata è la stessa per tutte le osservazioni.\n\nQuesta riduzione è importante per il percorso del capitolo. Dopo avere visto che più predittori aggiungono colonne alla matrice del modello, qui vediamo il caso limite in cui ne rimane una sola: la colonna dell'intercetta. Nel capitolo successivo aggiungeremo una variabile categoriale e quella nuova colonna permetterà di rappresentare due medie e il loro contrasto.\n\n## Esplorazione dei dati\n\nCarichiamo il dataset ed esaminiamo la struttura delle variabili:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheight_raw <- rio::import(\n  here::here(\"data\", \"Howell_18.csv\")\n)\n\nheight_data <- height_raw |>\n  dplyr::filter(!is.na(height))\n\ndplyr::glimpse(height_raw)\n#> Rows: 352\n#> Columns: 4\n#> $ height <dbl> 152, 140, 137, 157, 145, 164, 149, 169, 148, 165, 154, 151, 145~\n#> $ weight <dbl> 47.8, 36.5, 31.9, 53.0, 41.3, 63.0, 38.2, 55.5, 34.9, 54.5, 49.~\n#> $ age    <dbl> 63.0, 63.0, 65.0, 41.0, 51.0, 35.0, 32.0, 27.0, 19.0, 54.0, 47.~\n#> $ male   <int> 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, ~\n```\n:::\n\n\nIl file include già gli individui adulti selezionati per l'analisi. Prima di specificare il modello, verifichiamo la numerosità del campione, la presenza di valori mancanti e le caratteristiche principali della distribuzione (posizione, dispersione e forma):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheight_summary <- height_raw |>\n  summarise(\n    n       = sum(!is.na(height)),\n    missing = sum(is.na(height)),\n    mean    = mean(height, na.rm = TRUE),\n    sd      = sd(height, na.rm = TRUE),\n    min     = min(height, na.rm = TRUE),\n    max     = max(height, na.rm = TRUE)\n  )\n\nheight_summary\n#>     n missing mean   sd min max\n#> 1 352       0  155 7.74 137 179\n```\n:::\n\n\nVisualizziamo la forma della distribuzione empirica tramite un istogramma:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheight_data |>\n  ggplot(aes(x = height)) +\n  geom_histogram(\n    binwidth = 3,\n    boundary = 0,\n    color = \"white\",\n    fill = modern_palette$grey3\n  ) +\n  labs(\n    x = \"Altezza (cm)\",\n    y = \"Frequenza\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzione osservata delle altezze nel campione di adulti !Kung San. L'istogramma permette di valutare posizione, dispersione, asimmetria e presenza di osservazioni estreme prima di specificare il modello.](05_inferenza_su_una_media_files/figure-pdf/fig-howell-height-distribution-1.png){#fig-howell-height-distribution fig-align='center' fig-pos='H' fig-alt='Istogramma delle altezze degli adulti !Kung San, espresse in centimetri, con la maggior parte delle osservazioni concentrata nella zona centrale della distribuzione.' width=85%}\n:::\n:::\n\n\nL'analisi grafica non serve a decidere in modo meccanico se i dati seguano perfettamente una distribuzione normale. Il suo scopo è identificare le proprietà geometriche fondamentali che il modello statistico dovrà essere in grado di riprodurre: la centralità, la dispersione, l'eventuale asimmetria e la presenza di osservazioni anomale o outliers.\n\n## Il modello a sola intercetta\n\nLa specificazione è\n\n$$\nY_i \\mid \\mu,\\sigma \\sim \\operatorname{Normal}(\\mu,\\sigma).\n$$\n\nPoiché non vi sono predittori, la media attesa è costante per tutte le osservazioni:\n\n$$\n\\mu_i=\\alpha=\\mu.\n$$\n\nLa formula R\n\n```r\nheight ~ 1\n```\n\nesprime esattamente questa struttura. La matrice del modello si riduce a una colonna di valori unitari:\n\n$$\n\\mathbf X=\n\\begin{bmatrix}\n1\\\\\n1\\\\\n\\vdots\\\\\n1\n\\end{bmatrix},\n\\qquad\n\\boldsymbol\\mu=\\mathbf X\\alpha.\n$$\n\nIl legame con il capitolo precedente è diretto: il modello a sola intercetta non è un metodo separato per stimare una media, ma il caso più semplice della stessa grammatica del modello lineare. La differenza rispetto ai modelli con predittori risiede unicamente nella matrice del modello, non nella logica inferenziale.\n\n::: {.callout-note title=\"Perché l'intercetta coincide con la media\"}\nNei modelli con predittori, l'intercetta rappresenta la media condizionata quando tutti i predittori sono pari a zero secondo la codifica adottata. Nel modello `height ~ 1`, non essendovi altre colonne, l'intercetta coincide direttamente con la media $\\mu$ della distribuzione.\n:::\n\n## Calibrare i prior e osservarne le implicazioni\n\nNel capitolo sul workflow abbiamo già visto che un prior non va valutato soltanto dalla sua forma astratta: occorre considerarne le implicazioni sulla scala concreta del fenomeno. Per le altezze, espresse in centimetri, adottiamo le seguenti distribuzioni:\n\n$$\n\\begin{aligned}\n\\mu &\\sim \\operatorname{Normal}(160,20),\\\\\n\\sigma &\\sim \\operatorname{LogNormal}\\!\\left(\\log 15,0.5\\right).\n\\end{aligned}\n$$\n\nLa prima distribuzione esprime incertezza sul centro della popolazione, collocandolo in un intervallo ragionevole per le altezze di adulti. La seconda assegna probabilità solo a valori positivi di dispersione, con una massa concentrata su valori compatibili con la variabilità tipica di misure antropometriche.\n\nNon è necessario classificare questi prior in termini assoluti come \"deboli\" o \"forti\": ciò che conta è se le loro conseguenze siano plausibili per il problema in esame. Una verifica esplicita, attraverso controlli predittivi a priori, è sempre preferibile a un'etichetta generica.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheight_priors <- c(\n  prior(normal(160, 20), class = \"Intercept\"),\n  prior(lognormal(log(15), 0.5), class = \"sigma\")\n)\n\nheight_priors\n#>                    prior     class coef group resp dpar nlpar   lb   ub tag\n#>          normal(160, 20) Intercept                            <NA> <NA>    \n#>  lognormal(log(15), 0.5)     sigma                            <NA> <NA>    \n#>  source\n#>    user\n#>    user\n```\n:::\n\n\n### Controllo predittivo a priori\n\nPrima di condizionare il modello alle altezze osservate, lo simuleremo direttamente a partire dal modello definito soltanto dai prior. Il controllo predittivo a priori traduce le assunzioni su $\\mu$ e $\\sigma$ in distribuzioni di possibili altezze, ovvero sulla scala in cui è possibile giudicarle sostantivamente.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_height_prior <- brm(\n  formula = height ~ 1,\n  data = height_data,\n  family = gaussian(),\n  prior = height_priors,\n  sample_prior = \"only\",\n  chains = 4,\n  iter = 1000,\n  seed = 1234,\n  backend = \"cmdstanr\",\n  refresh = 0\n)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp_check(\n  fit_height_prior,\n  type = \"dens_overlay\",\n  ndraws = 50\n)\n```\n\n::: {.cell-output-display}\n![Controllo predittivo a priori del modello a sola intercetta. Le densità rappresentano dataset simulati dai prior su media e deviazione standard, prima di condizionare il modello alle altezze osservate.](05_inferenza_su_una_media_files/figure-pdf/fig-prior-predictive-one-mean-1.png){#fig-prior-predictive-one-mean fig-align='center' fig-pos='H' fig-alt='Cinquanta curve di densità sovrapposte mostrano distribuzioni di altezze generate dal modello prima dell\\'osservazione dei dati.' width=85%}\n:::\n:::\n\n\nL'obiettivo non è che ogni singola replica appaia realistica in ogni dettaglio, ma piuttosto che il modello non attribuisca una massa di probabilità apprezzabile a scenari incompatibili con quanto sappiamo riguardo alle altezze. Se la maggior parte delle distribuzioni simulate, o una loro porzione sostanziale, risulta implausibile (per esempio, altezze negative o medie eccessivamente estreme), è necessario rivedere i prior. Se invece il problema riguarda la forma complessiva della distribuzione, potrebbe essere necessario modificare la specifica del modello stesso.\n\n## Adattare il modello normale\n\nCondizioniamo ora il modello alle osservazioni:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_height_normal <- brm(\n  formula = height ~ 1,\n  data = height_data,\n  family = gaussian(),\n  prior = height_priors,\n  chains = 4,\n  iter = 2000,\n  warmup = 1000,\n  seed = 1234,\n  backend = \"cmdstanr\",\n  refresh = 0\n)\n```\n:::\n\n\nDopo l'adattamento, non introduciamo nuove diagnostiche: applichiamo gli stessi criteri già discussi nel capitolo sul workflow: $\\widehat R$, ESS, eventuali avvisi del campionatore e, se necessario, ispezione grafica delle catene.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(fit_height_normal)\n#>  Family: gaussian \n#>   Links: mu = identity \n#> Formula: height ~ 1 \n#>    Data: height_data (Number of observations: 352) \n#>   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n#>          total post-warmup draws = 4000\n#> \n#> Regression Coefficients:\n#>           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\n#> Intercept   154.59      0.42   153.79   155.39 1.00     3661     2417\n#> \n#> Further Distributional Parameters:\n#>       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\n#> sigma     7.78      0.29     7.23     8.37 1.00     3403     2376\n#> \n#> Draws were sampled using sample(hmc). For each parameter, Bulk_ESS\n#> and Tail_ESS are effective sample size measures, and Rhat is the potential\n#> scale reduction factor on split chains (at convergence, Rhat = 1).\n```\n:::\n\n\n::: {.callout-note title=\"Diagnostica del calcolo, non del fenomeno\"}\nUna diagnostica MCMC soddisfacente indica che l'algoritmo ha approssimato in modo affidabile la distribuzione a posteriori del modello specificato. Tuttavia, non attesta che la distribuzione normale sia una descrizione adeguata delle altezze né che il campione osservato sia rappresentativo della popolazione a cui si intende generalizzare. Si tratta di una verifica di tipo computazionale, non sostantiva.\n:::\n\n## Interpretare la distribuzione a posteriori\n\nEstraiamo i draw posteriori e rinominiamo l'intercetta come $\\mu$, per rendere esplicito il suo significato nel modello a sola intercetta:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheight_draws <- as_draws_df(fit_height_normal)\n\nheight_posterior_summary <- height_draws |>\n  transmute(\n    mu = b_Intercept,\n    sigma = sigma\n  ) |>\n  summarise(\n    mu_median    = median(mu),\n    mu_lower     = quantile(mu, 0.025),\n    mu_upper     = quantile(mu, 0.975),\n    sigma_median = median(sigma),\n    sigma_lower  = quantile(sigma, 0.025),\n    sigma_upper  = quantile(sigma, 0.975)\n  )\n\nheight_posterior_summary\n#> # A tibble: 1 x 6\n#>   mu_median mu_lower mu_upper sigma_median sigma_lower sigma_upper\n#>       <dbl>    <dbl>    <dbl>        <dbl>       <dbl>       <dbl>\n#> 1      155.     154.     155.         7.77        7.23        8.37\n```\n:::\n\n\nLe due posterior descrivono oggetti diversi:\n\n- la posterior di $\\mu$ quantifica ciò che sappiamo sul **centro** della distribuzione;\n- la posterior di $\\sigma$ quantifica ciò che sappiamo sulla **dispersione tra osservazioni**.\n\nUna posterior stretta per $\\mu$ non implica quindi che gli individui siano simili tra loro. Significa soltanto che il centro della distribuzione è stimato con precisione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmcmc_plot(\n  fit_height_normal,\n  type = \"areas\",\n  variable = c(\"b_Intercept\", \"sigma\"),\n  prob = 0.95\n)\n```\n\n::: {.cell-output-display}\n![Distribuzioni a posteriori della media delle altezze e della deviazione standard individuale. Le aree mostrano l'incertezza a posteriori sui due parametri del modello.](05_inferenza_su_una_media_files/figure-pdf/fig-one-mean-posterior-1.png){#fig-one-mean-posterior fig-align='center' fig-pos='H' fig-alt='Distribuzioni a posteriori per la media della popolazione e la deviazione standard, ciascuna accompagnata dal proprio intervallo di credibilità.' width=85%}\n:::\n:::\n\n\n### Probabilità rispetto a una soglia sostantiva\n\nSe esiste una soglia definita da una domanda scientifica, possiamo calcolare direttamente la massa posteriore che si trova oltre quella soglia. Per esempio:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nthreshold_cm <- 155\n\nmean(height_draws$b_Intercept > threshold_cm)\n#> [1] 0.17\n```\n:::\n\n\nIl calcolo rappresenta\n\n$$\n\\Pr(\\mu>155\\mid y,\\mathcal M),\n$$\n\ndove $\\mathcal M$ ricorda che la probabilità è condizionata alla specificazione del modello e ai prior. La soglia deve avere un significato indipendente dal risultato numerico. Se viene scelta dopo avere esaminato la posterior, la sua natura esplorativa va dichiarata esplicitamente.\n\n## Media della popolazione e nuova osservazione\n\nQuesta è la distinzione più importante del capitolo. Una domanda sul parametro medio e una domanda su una nuova persona non condividono la stessa distribuzione: rispondono a due livelli inferenziali diversi.\n\nPer la media della popolazione, usiamo direttamente i draw di $\\mu$. Per una nuova osservazione, invece, dobbiamo generare\n\n$$\n\\widetilde y \\sim \\operatorname{Normal}(\\mu,\\sigma)\n$$\nper ciascuna configurazione plausibile di $\\mu$ e $\\sigma$ nella distribuzione a posteriori. La distribuzione predittiva incorpora quindi tre componenti di incertezza:\n\n1. l'incertezza su $\\mu$;\n2. l'incertezza su $\\sigma$;\n3. la variabilità individuale descritta dal modello dei dati.\n\nNel modello a sola intercetta non esistono predittori e tutte le osservazioni condividono lo stesso profilo. Possiamo quindi estrarre una qualunque colonna di `posterior_predict()` come draw dalla distribuzione di una nuova osservazione, purché sia considerata *exchangeable* con quelle già modellate.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnew_height_draws <- posterior_predict(fit_height_normal)[, 1]\n\nprediction_summary <- tibble(\n  quantity = c(\"Media mu\", \"Nuova altezza\"),\n  median = c(\n    median(height_draws$b_Intercept),\n    median(new_height_draws)\n  ),\n  lower = c(\n    quantile(height_draws$b_Intercept, 0.025),\n    quantile(new_height_draws, 0.025)\n  ),\n  upper = c(\n    quantile(height_draws$b_Intercept, 0.975),\n    quantile(new_height_draws, 0.975)\n  )\n)\n\nprediction_summary\n#> # A tibble: 2 x 4\n#>   quantity      median lower upper\n#>   <chr>          <dbl> <dbl> <dbl>\n#> 1 Media mu        155.  154.  155.\n#> 2 Nuova altezza   154.  139.  170.\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbind_rows(\n  tibble(value = height_draws$b_Intercept, quantity = \"Media mu\"),\n  tibble(value = new_height_draws, quantity = \"Nuova altezza\")\n) |>\n  ggplot(aes(x = value, fill = quantity)) +\n  geom_density(alpha = 0.35) +\n  scale_fill_qualitative() +\n  labs(\n    x = \"Altezza (cm)\",\n    y = \"Densità\",\n    fill = NULL\n  )\n```\n\n::: {.cell-output-display}\n![Confronto tra la distribuzione a posteriori della media della popolazione e la distribuzione predittiva di una nuova altezza. La seconda è molto più ampia perché incorpora la variabilità individuale.](05_inferenza_su_una_media_files/figure-pdf/fig-compare-mean-new-height-1.png){#fig-compare-mean-new-height fig-align='center' fig-pos='H' fig-alt='Due curve di densità: una stretta per la media della popolazione e una molto più larga per l\\'altezza di una nuova persona.' width=85%}\n:::\n:::\n\n\nCon più osservazioni, la distribuzione a posteriori di $\\mu$ tende a restringersi, perché impariamo con maggiore precisione dove si trova il centro. La distribuzione predittiva individuale, invece, non collassa nello stesso modo: anche se $\\mu$ e $\\sigma$ fossero noti con certezza, persone diverse continuerebbero a presentare altezze differenti.\n\n::: {.callout-important title=\"Precisione del parametro e variabilità individuale\"}\nUna media può essere stimata con grande precisione in una popolazione molto eterogenea. L'ampiezza della posterior di $\\mu$ misura l'incertezza sul parametro; $\\sigma$ e la distribuzione predittiva descrivono invece la variabilità delle osservazioni. Confondere questi due livelli porta a interpretazioni errate anche quando il calcolo è formalmente corretto.\n:::\n\n## Controllare ciò che il modello riesce a riprodurre\n\nDopo la stima, torniamo alla scala dei dati per verificare ciò che il modello è in grado di riprodurre. Il controllo predittivo a posteriori confronta le altezze osservate con repliche generate dal modello adattato. È naturale iniziare esaminando la forma marginale della distribuzione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp_check(\n  fit_height_normal,\n  type = \"dens_overlay\",\n  ndraws = 50\n)\n```\n\n::: {.cell-output-display}\n![Controllo predittivo a posteriori della distribuzione delle altezze. La densità osservata è confrontata con cinquanta repliche generate dal modello normale adattato.](05_inferenza_su_una_media_files/figure-pdf/fig-posterior-predictive-density-height-1.png){#fig-posterior-predictive-density-height fig-align='center' fig-pos='H' fig-alt='Curva di densità delle altezze osservate sovrapposta a cinquanta curve generate dalla distribuzione predittiva a posteriori del modello normale.' width=85%}\n:::\n:::\n\n\nIl grafico non fornisce un giudizio globale di adeguatezza, ma evidenzia alcune caratteristiche visibili, come posizione, dispersione, forma e code, e può suggerire dove cercare eventuali discrepanze. Se una caratteristica è particolarmente rilevante per la domanda scientifica, deve essere esaminata mediante una statistica o una rappresentazione mirata.\n\n::: {.callout-note title=\"Il workflow è lo stesso, ma la domanda del controllo cambia\"}\nNel capitolo sulla regressione, il controllo includeva anche la relazione tra l'outcome e il predittore; qui, in assenza di predittori, i controlli si concentrano unicamente sulla distribuzione marginale dell'outcome. Questa differenza è dovuta alla struttura del modello e non a una procedura diagnostica diversa.\n:::\n## Approfondimento: se la distribuzione normale non descrive bene le code {.unnumbered}\n\n::: {.callout-tip appearance=\"minimal\" .optional-section}\n**Approfondimento facoltativo.** Questa sezione anticipa il tema della revisione del modello, che verrà sviluppato sistematicamente più avanti nella Parte *Modelli*.\n:::\n\nLa scelta della distribuzione normale costituisce un'ipotesi sul processo che genera gli scarti attorno a $\\mu$. Se i dati mostrano code più pesanti di quelle che il modello è in grado di riprodurre, una possibile alternativa è la distribuzione $t$ di Student:\n\n$$\nY_i \\sim \\operatorname{StudentT}(\\nu, \\mu, \\sigma).\n$$\n\nIl parametro $\\nu$ controlla il peso delle code: valori piccoli producono code più pesanti, valori grandi fanno approssimare la distribuzione a una normale. La $t$ non è intrinsecamente \"migliore\": rappresenta un'ipotesi generativa diversa, e va valutata per le conseguenze che produce sulle quantità di interesse.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_height_student <- brm(\n  formula = height ~ 1,\n  data = height_data,\n  family = student(),\n  prior = c(\n    prior(normal(160, 20), class = \"Intercept\"),\n    prior(lognormal(log(15), 0.5), class = \"sigma\"),\n    prior(gamma(2, 0.1), class = \"nu\")\n  ),\n  chains = 4,\n  iter = 2000,\n  warmup = 1000,\n  seed = 1234,\n  backend = \"cmdstanr\",\n  refresh = 0\n)\n```\n:::\n\n\nPossiamo confrontare le distribuzioni a posteriori di $\\mu$ ottenute con le due specificazioni:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbind_rows(\n  as_draws_df(fit_height_normal)  |> transmute(mu = b_Intercept, model = \"Normale\"),\n  as_draws_df(fit_height_student) |> transmute(mu = b_Intercept, model = \"Student-t\")\n) |>\n  ggplot(aes(x = mu, fill = model)) +\n  geom_density(alpha = 0.35) +\n  scale_fill_qualitative() +\n  labs(\n    x = expression(mu),\n    y = \"Densità\",\n    fill = \"Modello\"\n  )\n```\n\n::: {.cell-output-display}\n![Confronto tra le distribuzioni a posteriori della media ottenute con modello normale e Student-t. Il confronto mostra quanto l'inferenza su mu sia sensibile alla diversa rappresentazione delle code.](05_inferenza_su_una_media_files/figure-pdf/fig-compare-normal-student-mean-1.png){#fig-compare-normal-student-mean fig-align='center' fig-pos='H' fig-alt='Due curve di densità sovrapposte rappresentano la media delle altezze stimata con un modello normale e con un modello t di Student.' width=85%}\n:::\n:::\n\n\nUna forte somiglianza tra le due posteriori indicherebbe che, **per la quantità $\\mu$ e per queste due specificazioni**, la conclusione è poco sensibile alla rappresentazione delle code. Ciò non dimostra tuttavia che gli outlier siano assenti, né che la distribuzione normale sia la scelta corretta, né che tutte le altre quantità derivate dal modello siano ugualmente robuste.\n\n## Comunicare il risultato distinguendo le quantità\n\nUn resoconto utile non deve riportare tutto l'output di `brms`. Deve rendere chiaro **quale popolazione è stata modellata**, **quale distribuzione è stata assunta** e **quale quantità risponde alla domanda**. Per esempio:\n\n> Abbiamo modellato le altezze osservate mediante una distribuzione normale con media $\\mu$ e deviazione standard $\\sigma$ ignote. La mediana a posteriori di $\\mu$ è 154.6 cm, con intervallo di credibilità al 95% [153.8, 155.4]. La deviazione standard delle osservazioni è stimata in 7.8 cm, con intervallo al 95% [7.2, 8.4]. La distribuzione predittiva per una nuova osservazione è sostanzialmente più ampia della posterior della media, perché incorpora la variabilità tra individui. I controlli predittivi eseguiti non hanno evidenziato discrepanze rilevanti nelle caratteristiche esaminate; questa valutazione non costituisce una prova globale di correttezza del modello né estende automaticamente le conclusioni ad altre popolazioni.\n\nLa struttura del resoconto rispecchia così la struttura dell'analisi: **parametro medio**, **dispersione individuale**, **previsione** e **portata della generalizzazione** rimangono distinti.\n\n## Errori frequenti\n\n::: {.callout-caution}\n1. **Trattare la media campionaria e $\\mu$ come lo stesso oggetto.** La media campionaria è una statistica descrittiva calcolata sui dati osservati; $\\mu$ è un parametro del modello, la cui interpretazione dipende dalla popolazione di riferimento e dal processo di campionamento che ha generato i dati.\n2. **Usare $\\sigma$ come misura dell'incertezza su $\\mu$.** $\\sigma$ descrive la dispersione delle osservazioni attorno alla media; l'incertezza sul valore di $\\mu$ è invece rappresentata dalla distribuzione a posteriori del parametro stesso.\n3. **Utilizzare l'intervallo di credibilità di $\\mu$ come intervallo per prevedere un nuovo individuo.** La variabilità predittiva per una nuova osservazione è sempre più ampia di quella relativa al parametro medio, perché incorpora anche la variabilità individuale.\n4. **Pensare che un modello senza predittori sia \"senza assunzioni\".** Anche il modello a sola intercetta incorpora assunzioni rilevanti: la forma della distribuzione dei dati, la scelta dei prior, l'exchangeability delle osservazioni e le condizioni di campionamento.\n5. **Interpretare un controllo predittivo favorevole come prova della normalità.** Un PPC che non mostra discrepanze visibili indica che il modello non contraddice apertamente alcune caratteristiche dei dati; non dimostra che la specificazione sia vera, né che sia l'unica compatibile con i dati osservati.\n6. **Confondere precisione interna e generalizzabilità.** Una distribuzione a posteriori molto concentrata attorno a una stima non garantisce che il campione sia rappresentativo della popolazione di interesse; la precisione interna e la validità esterna sono questioni separate.\n:::\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nL'inferenza su una media non richiede un nuovo metodo statistico. Si tratta del modello lineare nella sua forma più semplice: una sola colonna nella matrice del modello e un solo coefficiente nella componente sistematica. Questo punto di vista permette di collegare direttamente la media ai modelli già studiati, senza considerarla come una procedura isolata.\n\nLa semplicità del modello rende inoltre evidente una distinzione che rimarrà centrale in tutto il Companion. La distribuzione a posteriori di $\\mu$ descrive ciò che sappiamo sul centro della distribuzione, la distribuzione di $\\sigma$ descrive quanto variano le osservazioni e la distribuzione predittiva descrive cosa potrebbe accadere a una nuova unità. Aumentare la precisione della media non elimina la variabilità individuale.\n\nNel capitolo successivo aggiungeremo una sola informazione alla matrice del modello: l'appartenenza a un gruppo. Con una codifica appropriata, l'intercetta continuerà a rappresentare una media e il nuovo coefficiente rappresenterà la differenza tra due medie. Il confronto tra due gruppi emergerà quindi come un'estensione diretta del modello `y ~ 1`, e non come una tecnica separata.\n\n## Esercizi {.unnumbered .unlisted}\n\n### Esercizio 1 — Comprendere: che cosa rimane senza predittori {.unnumbered .unlisted}\n\n*Codice: no · 10 minuti*\n\nConsidera il modello\n\n```r\nanxiety ~ 1\n```\n\nper i punteggi di ansia di un campione di studenti.\n\n1. Scrivi il modello generativo normale.\n2. Disegna schematicamente la matrice del modello.\n3. Spiega perché l'intercetta coincide con la media $\\mu$.\n4. Distingui il significato di $\\mu$, $\\sigma$ e $\\widetilde y$.\n5. Indica quale informazione sul disegno servirebbe per stabilire a quali studenti sia ragionevole generalizzare.\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nNel modello a sola intercetta la matrice contiene soltanto una colonna di $1$. La generalizzabilità non è determinata dalla precisione della posterior.\n:::\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\nIl modello è\n\n$$\nY_i\\mid\\mu,\\sigma\\sim\\operatorname{Normal}(\\mu,\\sigma).\n$$\n\nLa matrice del modello è un vettore colonna di $1$, quindi il predittore lineare è identico per tutte le osservazioni e l'intercetta coincide con $\\mu$. La posterior di $\\mu$ riguarda il centro della distribuzione; $\\sigma$ riguarda la dispersione individuale; $\\widetilde y$ è una nuova osservazione e richiede la distribuzione predittiva. Per generalizzare occorre conoscere, tra le altre cose, la popolazione di riferimento e il meccanismo con cui gli studenti sono entrati nel campione.\n:::\n\n### Esercizio 2 — Interpretare: parametro o nuova osservazione? {.unnumbered .unlisted}\n\n*Codice: no · 10 minuti*\n\nUn modello produce:\n\n- mediana di $\\mu$: 154,8 cm;\n- intervallo di credibilità al 95% per $\\mu$: [154,1; 155,5] cm;\n- mediana di $\\sigma$: 7,6 cm;\n- intervallo predittivo al 95% per una nuova osservazione: [139,7; 169,9] cm;\n- $\\Pr(\\mu>155\\mid y)=0,29$.\n\nPer ciascuna quantità, indica a quale domanda risponde. Spiega poi perché raccogliere molte più osservazioni dalla stessa popolazione restringerebbe soprattutto l'incertezza su $\\mu$, senza rendere necessariamente molto più stretta la distribuzione delle altezze individuali.\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\nLa posterior di $\\mu$ descrive il centro della popolazione modellata e la probabilità 0,29 riguarda la massa posteriore del parametro sopra 155 cm. $\\sigma$ descrive la dispersione individuale. L'intervallo predittivo riguarda una nuova osservazione ed è molto più ampio perché incorpora la variabilità tra individui. Più dati permettono di localizzare meglio il centro, ma non eliminano l'eterogeneità reale rappresentata da $\\sigma$.\n:::\n\n### Esercizio 3 — Dal modello a una media al modello per due gruppi {.unnumbered .unlisted}\n\n*Codice: no · 10–15 minuti*\n\nConfronta le formule:\n\n```r\ny ~ 1\ny ~ gruppo\n```\n\nsupponendo che `gruppo` abbia due livelli e sia codificato con una variabile indicatrice 0/1.\n\n1. Quante colonne contiene la matrice del modello nel primo caso?\n2. Quale nuova colonna compare nel secondo?\n3. Se il gruppo codificato 0 è il riferimento, che cosa rappresentano intercetta e coefficiente di `gruppo`?\n4. Perché il secondo modello può essere interpretato come un'estensione del primo anziché come una procedura completamente nuova?\n\n::: {.callout-tip collapse=true title=\"Suggerimento\"}\nNel secondo modello il predittore lineare può essere scritto $\\mu_i=\\alpha+\\beta g_i$, con $g_i\\in\\{0,1\\}$.\n:::\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\n`y ~ 1` produce soltanto la colonna dell'intercetta. Con `y ~ gruppo` compare una seconda colonna che indica l'appartenenza al gruppo non di riferimento. Con codifica 0/1, $\\alpha$ è la media del gruppo di riferimento e $\\beta$ è la differenza tra la media del gruppo codificato 1 e quella del gruppo di riferimento. Il confronto tra gruppi usa quindi la stessa struttura del modello lineare, con una colonna aggiuntiva nella matrice del modello.\n:::\n\n### Esercizio 4 — Criticare e comunicare {.unnumbered .unlisted}\n\n*Codice: no · 15 minuti*\n\nValuta il seguente resoconto:\n\n> L'altezza media è 154,8 cm, con un intervallo al 95% tra 154,1 e 155,5 cm. Ciò significa che quasi tutti gli adulti hanno un'altezza vicina a 155 cm. Poiché $\\widehat R=1$ e il PPC è buono, il modello normale è corretto e il risultato può essere generalizzato agli esseri umani adulti.\n\nIndividua almeno quattro errori e riscrivi il resoconto distinguendo:\n\n- posterior della media;\n- variabilità individuale;\n- diagnostica computazionale;\n- controllo predittivo;\n- popolazione alla quale l'inferenza può essere riferita.\n\n::: {.callout-note collapse=true title=\"Soluzione commentata\"}\nL'intervallo [154,1; 155,5] riguarda $\\mu$, non le altezze individuali. La variabilità tra persone deve essere descritta mediante $\\sigma$ o la distribuzione predittiva. $\\widehat R$ riguarda la qualità del campionamento MCMC, mentre un PPC valuta soltanto le caratteristiche dei dati esaminate e non prova che il modello sia vero. Infine, la portata della generalizzazione dipende dal campionamento e dalla popolazione rappresentata dai dati. Un resoconto appropriato separa quindi precisione sul parametro, dispersione delle osservazioni, adeguatezza del calcolo e validità esterna.\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.6.1\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.1            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.1           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] gridExtra_2.3.1      inline_0.3.21        rlang_1.3.0         \n#>  [4] magrittr_2.0.5       snakecase_0.11.1     otel_0.2.0          \n#>  [7] ggridges_0.5.7       compiler_4.6.1       vctrs_0.7.3         \n#> [10] reshape2_1.4.5       stringr_1.6.0        pkgconfig_2.0.3     \n#> [13] arrayhelpers_1.1-2   fastmap_1.2.0        backports_1.5.1     \n#> [16] labeling_0.4.3       utf8_1.2.6           cmdstanr_0.9.0      \n#> [19] rmarkdown_2.31       ps_1.9.3             purrr_1.2.2         \n#> [22] xfun_0.60            cachem_1.1.0         jsonlite_2.0.0      \n#> [25] broom_1.0.13         parallel_4.6.1       R6_2.6.1            \n#> [28] stringi_1.8.9        RColorBrewer_1.1-3   lubridate_1.9.5     \n#> [31] estimability_2.0.0   knitr_1.51           R.utils_2.13.0      \n#> [34] Matrix_1.7-6         timechange_0.4.0     tidyselect_1.2.1    \n#> [37] abind_1.4-8          yaml_2.3.12          codetools_0.2-20    \n#> [40] curl_7.1.0           processx_3.9.0       pkgbuild_1.4.8      \n#> [43] lattice_0.22-9       plyr_1.8.9           bridgesampling_1.2-1\n#> [46] S7_0.2.2             coda_0.19-4.1        evaluate_1.0.5      \n#> [49] RcppParallel_6.2.0   pillar_1.11.1        tensorA_0.36.2.1    \n#> [52] checkmate_2.3.4      stats4_4.6.1         distributional_0.8.1\n#> [55] generics_0.1.4       rprojroot_2.1.1      rstantools_2.7.0    \n#> [58] scales_1.4.0         xtable_1.8-8         glue_1.8.1          \n#> [61] emmeans_2.0.4        tools_4.6.1          data.table_1.18.4   \n#> [64] mvtnorm_1.4-2        grid_4.6.1           QuickJSR_1.10.0     \n#> [67] nlme_3.1-170         cli_3.6.6            textshaping_1.0.5   \n#> [70] svUnit_1.0.8         Brobdingnag_1.2-9    V8_8.2.0            \n#> [73] gtable_0.3.6         R.methodsS3_1.8.2    digest_0.6.39       \n#> [76] farver_2.1.2         memoise_2.0.1        htmltools_0.5.9     \n#> [79] R.oo_1.27.1          lifecycle_1.0.5\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n\n",
    "supporting": [
      "05_inferenza_su_una_media_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}