{
  "hash": "eab6007c5c6fe5093fd6ee0513ffd82a",
  "result": {
    "engine": "knitr",
    "markdown": "# Introduzione pratica a Stan {#sec-mcmc-stan-intro}\n\n## Introduzione {.unnumbered .unlisted}\n\nL'esplorazione dell'algoritmo di Metropolis ha fornito le fondamenta concettuali e metodologiche per affrontare l'inferenza bayesiana in scenari realistici, consentendoci di comprendere i principi operativi del campionamento MCMC. Questo bagaglio teorico trova ora la sua logica realizzazione pratica in Stan, l'ambiente di programmazione probabilistica che rappresenta uno degli strumenti più potenti per la modellazione bayesiana avanzata.\n\nStan non è tanto un software statistico, quanto un linguaggio di programmazione probabilistica specializzato nell'espressione dichiarativa di modelli bayesiani e nell'inferenza tramite algoritmi avanzati. La sua implementazione dell'Hamiltonian Monte Carlo (HMC) e, in particolare, dell'algoritmo NUTS (No-U-Turn Sampler), garantisce un'efficienza esplorativa notevolmente superiore rispetto ai campionatori Metropolis elementari, pur mantenendo intatta la logica inferenziale fondamentale che abbiamo già assimilato. La transizione verso Stan costituisce quindi l’evoluzione naturale del nostro percorso di apprendimento.\n\nIl vantaggio operativo per la ricerca psicologica è notevole. Modelli gerarchici multilivello, processi di apprendimento iterativo e strutture dinamiche – tipicamente complessi da implementare attraverso codici personalizzati – risultano accessibili mediante una sintassi dichiarativa. Ciò consente ai ricercatori di concentrarsi sulla formalizzazione teorica piuttosto che sui dettagli computazionali.\n\n### Obiettivi del capitolo {.unnumbered .unlisted}\n\nIn questo capitolo acquisiremo familiarità con gli elementi costitutivi di Stan attraverso un approccio progressivo:\n\n- **Struttura fondamentale** dei programmi Stan e loro componenti essenziali\n- **Implementazione pratica** di modelli semplici utilizzando l'interfaccia `cmdstanr`\n- **Interpretazione dei risultati** attraverso statistiche riassuntive e diagnostiche di convergenza\n- **Validazione del modello** tramite verifiche predittive a priori e a posteriori\n\nL'obiettivo finale trascende l'apprendimento tecnico: sviluppare la capacità di tradurre teorie psicologiche in modelli generativi espliciti, conducendo analisi statistiche trasparenti, riproducibili e sostantivamente significative.\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\nif (!requireNamespace(\"pacman\")) install.packages(\"pacman\")\npacman::p_load(cmdstanr, posterior, insight)\n```\n:::\n\n:::\n\nOttimo testo: è già chiaro e formalmente corretto.\nPer studenti di psicologia senza esperienza di programmazione, però, conviene **ridurre il gergo tecnico**, **eliminare la metafora culinaria** (che può distrarre) e **rafforzare l’intuizione funzionale** — cioè far capire “a cosa serve ciascun blocco” senza che debbano ancora pensare in termini di codice.\n\n## Programmazione probabilistica con Stan\n\nI programmi scritti in Stan seguono una struttura ordinata e sempre uguale, suddivisa in *blocchi*.\nOgni blocco ha uno scopo preciso e contribuisce a costruire il modello statistico passo dopo passo [@nicenboim2025introduction]:\n\n* **`data`** – contiene i dati osservati, cioè le informazioni raccolte nel nostro studio (ad esempio i punteggi di un test o le risposte dei partecipanti);\n* **`parameters`** – elenca le quantità sconosciute che vogliamo stimare, come le medie, le varianze o i coefficienti di regressione;\n* **`model`** – descrive come i parametri e i dati sono collegati tra loro, specificando le **distribuzioni a priori** e la **verosimiglianza** del modello;\n* **`generated quantities`** – serve a calcolare risultati aggiuntivi, come previsioni, indici di bontà di adattamento o trasformazioni dei parametri stimati.\n\nQuesta organizzazione rende i programmi Stan *facili da leggere*: il codice segue la stessa logica con cui pensiamo a un modello statistico.\nSi parte dai dati, si dichiarano le quantità da stimare, si definisce la relazione tra ciò che è noto e ciò che è ignoto, e infine si producono i risultati utili per l’interpretazione.\n\nLa stessa struttura si applica a una grande varietà di modelli, dai più semplici (come la regressione lineare) ai modelli gerarchici complessi, offrendo un modo coerente e trasparente per tradurre il ragionamento statistico in calcolo computazionale.\n\nOttimo testo — già molto ben strutturato.\nPer un pubblico di studenti di psicologia (che in genere non ha familiarità con i concetti di compilazione o workflow computazionale), conviene rendere la prosa più **discorsiva e intuitiva**, mantenendo però la precisione metodologica.\n\n### L’ecosistema Stan in R\n\nL’interfaccia `cmdstanr` permette di utilizzare Stan direttamente da R seguendo un flusso di lavoro chiaro e riproducibile.\nOgni fase del processo inferenziale è esplicita e facilmente controllabile:\n\n1. **Specificazione del modello** – si scrive il modello statistico in un file di testo con estensione `.stan`, descrivendo le relazioni tra dati, parametri e distribuzioni;\n2. **Compilazione** – Stan traduce il modello in un programma eseguibile ottimizzato, pronto per l’inferenza;\n3. **Preparazione dei dati** – in R si organizza l’insieme dei dati in una *lista* con nomi coerenti rispetto a quelli dichiarati nel file `.stan`;\n4. **Campionamento** – la funzione `sample()` avvia l’inferenza bayesiana, producendo campioni dalla distribuzione a posteriori dei parametri;\n5. **Analisi posteriore** – i risultati vengono esplorati e visualizzati con pacchetti dedicati come `posterior` e `bayesplot`.\n\nQuesto approccio sistematico rende l’intero processo *trasparente e ripetibile*:\n\n* la **compilazione** genera un eseguibile indipendente che può essere riutilizzato con dati diversi;\n* la **separazione tra modello e dati** aumenta la chiarezza concettuale e consente di adattare lo stesso codice a più studi o repliche sperimentali.\n\nOttimo testo — il contenuto è corretto e ben organizzato.\nPuò però essere reso **più fluido, didattico e intuitivo** per studenti di psicologia, chiarendo brevemente *perché* Stan impone questa “disciplina” e *come* ciò aiuta nella pratica (anche senza conoscenze di programmazione).\n\n### Sistema di tipizzazione in Stan\n\nStan utilizza un *sistema di tipizzazione statica*, cioè richiede che per ogni variabile sia dichiarato in anticipo il suo *tipo* e, se necessario, i *vincoli* che ne definiscono l’intervallo di valori possibili.\n\nI tipi più comuni sono:\n\n* `int` – per valori interi (ad esempio, il numero di prove o di risposte corrette);\n* `real` – per numeri reali (come medie, deviazioni standard o probabilità);\n* `vector` – per insiemi di valori numerici;\n* vincoli opzionali come `lower=0` o `upper=1` servono a specificare limiti (ad esempio per parametri che devono essere positivi o compresi tra 0 e 1).\n\nQuesta dichiarazione esplicita rende il modello *più sicuro e trasparente*:\n\n* previene errori di specificazione (per esempio, impedisce di trattare una probabilità come se potesse assumere valori negativi);\n* migliora l’efficienza del calcolo, perché Stan può ottimizzare le operazioni sapendo in anticipo il tipo di ogni variabile;\n* e documenta in modo automatico le **assunzioni del modello**, rendendo il codice più leggibile e riproducibile.\n\n## Modello Beta–Binomiale in Stan\n\nCostruiamo ora il nostro primo modello in Stan, partendo da un caso semplice ma molto istruttivo: la stima della probabilità di successo $\\theta$ in una sequenza di prove di tipo Bernoulliano, cioè di eventi che possono avere solo due esiti (successo o insuccesso).\n\n### Scenario applicativo: un dado forse truccato\n\nImmaginiamo di lanciare un dado 1000 volte e di registrare ogni uscita del numero 6 come *successo* (`1`), e tutte le altre come *insuccesso* (`0`).\nSe il dado fosse perfettamente equilibrato, la probabilità di successo sarebbe $\\theta = 1/6 \\approx 0.167$.\nTuttavia, invece di dare per scontata l’equità del dado, adottiamo un approccio bayesiano: lasciamo che siano i dati a informarci su $\\theta$.\n\nIn R, possiamo simulare i dati in questo modo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nn <- 1000\ndice_df <- tibble(res = sample(1:6, size = n, replace = TRUE))\ny <- as.integer(dice_df$res == 6)    # 1 per “6”, 0 altrimenti\nmean(y)                              # Frequenza osservata di \"6\"\n#> [1] 0.164\n```\n:::\n\n\n### Formalizzazione del modello\n\nIl modello si compone di due elementi fondamentali:\n\n* **Verosimiglianza** – ogni osservazione $y_i$ è una prova indipendente con probabilità di successo $\\theta$:\n  $$\n  y_i \\sim \\text{Bernoulli}(\\theta)\n  $$\n* **Distribuzione a priori** – assumiamo inizialmente che tutte le probabilità siano ugualmente plausibili:\n  $$\n  \\theta \\sim \\text{Beta}(1,1)\n  $$\n  che corrisponde a una distribuzione uniforme su $[0,1]$.[^prior_implicito]\n\n[^prior_implicito]: In Stan, se un parametro è vincolato all’intervallo $[0,1]$ e non si assegna una distribuzione a priori, viene automaticamente applicata una prior uniforme $\\text{Beta}(1,1)$.\n\nQuesta specificazione corrisponde al *modello Beta–Binomiale*, in cui il numero totale di successi $k = \\sum_{i=1}^N y_i$ segue una distribuzione binomiale:\n$$\nk \\sim \\text{Binomiale}(N, \\theta).\n$$\n\n### Implementazione Bernoulliana vettoriale\n\nIl modo più diretto per tradurre il modello in Stan è indicare esplicitamente che ogni prova segue una distribuzione Bernoulli con probabilità $\\theta$.\nStan permette di scrivere questa relazione in forma *vettoriale*, cioè di applicarla a tutte le osservazioni in un’unica istruzione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstancode <- \"\ndata {\n  int<lower=1> N;                    // Numero di osservazioni\n  array[N] int<lower=0, upper=1> y;  // Esiti binari (0/1)\n}\nparameters {\n  real<lower=0, upper=1> theta;      // Probabilità di successo\n}\nmodel {\n  theta ~ beta(1, 1);                // Prior uniforme\n  y ~ bernoulli(theta);              // Verosimiglianza vettorializzata\n}\n\"\n```\n:::\n\n\nQuesta formulazione riflette la logica modulare di Stan:\n\n* il blocco `data` riceve i dati osservati;\n* il blocco `parameters` dichiara i parametri da stimare;\n* il blocco `model` descrive la struttura probabilistica del modello.\n\n[^target-plus]: Internamente, Stan calcola la log-verosimiglianza accumulandola nella variabile `target`. L’istruzione `~` è una scorciatoia per:\n```stan\ntarget += beta_lpdf(theta | 1, 1);\ntarget += bernoulli_lpmf(y | theta);\n```\nQuesta forma esplicita è utile in modelli complessi o con verosimiglianze personalizzate.\n\n\n### Array e vector: una distinzione importante\n\nIn Stan, la scelta tra `array` e `vector` non è casuale ma riflette la natura delle variabili:\n\n* `array[N] int`: viene usato per variabili *discrete* (intere), come le risposte binarie `0` e `1`;\n* `vector[N]`: viene usato per variabili *continue* (numeri reali).\n\nNel nostro caso, gli esiti Bernoulliani sono discreti, quindi devono essere dichiarati come `array[N] int`.\nSe usassimo `vector[N]`, Stan genererebbe un errore di compilazione: un vettore può contenere solo numeri reali.\nQuesta distinzione tipologica è una forma di “controllo di coerenza” che previene errori logici nella definizione del modello.\n\n### Implementazione binomiale: sfruttare la sufficienza statistica\n\nL’approccio Bernoulliano è chiaro, ma può risultare meno efficiente.\nPoiché nel modello Bernoulli l’informazione sui dati è riassunta interamente dal *numero di successi*, possiamo usare questa *statistica sufficiente* per semplificare il calcolo.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstancode <- \"\ndata {\n  int<lower=1> N;                      // Numero di prove\n  array[N] int<lower=0, upper=1> y;    // Sequenza di esiti\n}\ntransformed data {\n  int<lower=0, upper=N> k = sum(y);    // Successi totali (statistica sufficiente)\n}\nparameters {\n  real<lower=0, upper=1> theta;        // Probabilità di successo\n}\nmodel {\n  theta ~ beta(1, 1);                  // Prior uniforme\n  k ~ binomial(N, theta);              // Verosimiglianza compatta\n}\n\"\n```\n:::\n\n\nQuesta versione compatta produce gli stessi risultati inferenziali, ma con meno operazioni:\nStan deve calcolare la probabilità di ottenere $k$ successi in $N$ prove, invece di considerare ogni singola osservazione.\nIn questo modo il modello resta *equivalente dal punto di vista statistico*, ma è *più efficiente computazionalmente*.\n\n\n### In sintesi\n\n| Versione                | Descrizione                                     | Vantaggio principale        |\n| ----------------------- | ----------------------------------------------- | --------------------------- |\n| Bernoulliana vettoriale | Modello esplicito per ogni osservazione         | Più intuitiva e trasparente |\n| Binomiale compatta      | Modello basato sulla statistica sufficiente (k) | Più efficiente nel calcolo  |\n\nOttimo testo — chiaro, completo e ben organizzato.\nPer renderlo **più didattico** e adatto a studenti di psicologia (magari non abituati al linguaggio computazionale), conviene:\n\n* alleggerire il tono tecnico e rendere più espliciti i collegamenti concettuali tra teoria e codice;\n* introdurre brevi frasi di transizione che aiutino a “leggere” i blocchi di codice come parte del ragionamento inferenziale;\n* semplificare alcune formulazioni (“target”, “benchmark analitico”) mantenendo rigore e precisione.\n\n#### Verifica mediante soluzione analitica\n\nNel modello Beta–Binomiale, la coniugazione tra prior e verosimiglianza consente di ottenere una *soluzione analitica esatta*, che rappresenta un utile punto di riferimento per verificare i risultati ottenuti tramite campionamento MCMC.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nk <- sum(y)\npost_mean_analytical <- (1 + k) / (2 + n)\npost_ci_analytical <- qbeta(c(0.025, 0.975), 1 + k, 1 + n - k)\n```\n:::\n\n\nLe stime ottenute con MCMC dovrebbero avvicinarsi a questi valori, con differenze dovute soltanto alla *variabilità Monte Carlo*.\n\n### Workflow operativo: dalla compilazione all’analisi\n\nL’intero processo in Stan segue una sequenza logica ben definita, che può essere vista come un vero e proprio *workflow inferenziale*.\n\n**1. Compilazione del modello**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod <- cmdstan_model(\n  write_stan_file(stancode),\n  compile = TRUE\n)\n```\n:::\n\n\nLa *compilazione* traduce il modello Stan in un programma eseguibile ottimizzato, che può essere riutilizzato per analizzare dataset diversi senza doverlo ricompilare ogni volta.\n\n**2. Preparazione dei dati**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstan_data <- list(\n  N = length(y),\n  y = y\n)\n```\n:::\n\n\nI nomi e le strutture delle variabili devono corrispondere *esattamente* a quelli dichiarati nel blocco `data` del modello Stan, altrimenti l’esecuzione produrrà un errore.\n\n**3. Campionamento MCMC**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit1 <- mod$sample(\n  data = stan_data,\n  iter_warmup = 1000,      # Fase di adattamento (burn-in)\n  iter_sampling = 2000,    # Campioni usati per l’inferenza\n  chains = 4,              # Catene indipendenti\n  parallel_chains = 4,     # Esecuzione parallela\n  seed = 4790,\n  refresh = 0\n)\n```\n:::\n\n\nIn questa fase, Stan esegue il *campionamento MCMC* per esplorare la distribuzione a posteriori di $\\theta$.\nOgni catena parte da un punto iniziale diverso e, dopo la fase di adattamento, genera campioni dalla stessa distribuzione.\n\n### Analisi dei risultati\n\n**Statistiche descrittive**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit1$summary(variables = \"theta\")\n#> # A tibble: 1 × 10\n#>   variable  mean median     sd    mad    q5   q95  rhat ess_bulk ess_tail\n#>   <chr>    <dbl>  <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl>    <dbl>    <dbl>\n#> 1 theta    0.164  0.164 0.0117 0.0119 0.145 0.184  1.00    2443.    3636.\n```\n:::\n\n\nRestituisce le principali statistiche riassuntive (media, deviazione standard, quantili).\n\n**Diagnostiche di convergenza**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndraws <- fit1$draws(variables = \"theta\", format = \"draws_matrix\")\nposterior::summarise_draws(\n  draws,\n  mean, sd, ~quantile(.x, c(0.025, 0.5, 0.975)), rhat, ess_bulk, ess_tail\n)\n#> # A tibble: 1 × 9\n#>   variable  mean     sd `2.5%` `50%` `97.5%`  rhat ess_bulk ess_tail\n#>   <chr>    <dbl>  <dbl>  <dbl> <dbl>   <dbl> <dbl>    <dbl>    <dbl>\n#> 1 theta    0.164 0.0117  0.142 0.164   0.188  1.00    2443.    3636.\n```\n:::\n\n\nValori di $\\hat{R} \\approx 1.0$ e *Effective Sample Size (ESS)* elevati indicano che le catene sono ben mescolate e che il campionamento ha raggiunto la *convergenza* verso la distribuzione a posteriori.\n\n**Validazione grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbayesplot::mcmc_trace(fit1$draws(\"theta\"), n_warmup = 1000)\n```\n\n::: {.cell-output-display}\n![](03_stan_intro_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nIl *traceplot* mostra l’andamento delle catene nel tempo.\nCatene sovrapposte e senza trend sistematici sono il segnale visivo di una buona convergenza.\n\n### Sintesi interpretativa\n\nL’approccio bayesiano offre un quadro più completo rispetto alla sola stima puntuale:\n\n* fornisce l’intera *distribuzione a posteriori* di $\\theta$, che quantifica l’incertezza in modo esplicito;\n* include *strumenti diagnostici* per valutare l’affidabilità delle stime;\n* fornisce una base coerente per *previsioni e decisioni* fondate sulla probabilità.\n\n::: {.callout-note}\nLa frequenza relativa `mean(y)` rappresenta una stima puntuale della probabilità di successo, ma non dice nulla sull’incertezza associata.\nLa distribuzione a posteriori, invece, ne descrive l’intera gamma di valori plausibili, permettendo inferenze più ricche e robuste.\n:::\n\n### Distribuzione predittiva a posteriori\n\nStimare i parametri del modello è solo il primo passo dell’inferenza bayesiana.\nL’obiettivo sostantivo è *valutare cosa il modello prevede*: quanti successi potremmo aspettarci se ripetessimo l’esperimento in condizioni simili?\n\nLa *distribuzione predittiva a posteriori* formalizza questa idea: combina la variabilità del processo (descritta dalla verosimiglianza) con l’incertezza sui parametri (descritta dalla distribuzione a posteriori).\nIn altre parole, tiene conto sia del *caso* sia di ciò che *non sappiamo con certezza* sul parametro.\n\nPer nuovi dati $\\tilde{y}$, la distribuzione predittiva si ottiene integrando su tutti i possibili valori di $\\theta$:\n\n$$\np(\\tilde{y} \\mid y) = \\int p(\\tilde{y} \\mid \\theta) \\, p(\\theta \\mid y) \\, d\\theta.\n$$\n\nQuesta espressione rappresenta la “media ponderata” di tutte le possibili previsioni condizionate su $\\theta$, pesate dalla loro plausibilità a posteriori.\n\n#### Implementazione mediante campionamento\n\nIn pratica, l’integrale precedente si calcola **per approssimazione Monte Carlo**, sfruttando direttamente i campioni MCMC già ottenuti.\nIl procedimento è semplice:\n\n1. **Campionamento parametrico:** estraiamo molti valori $\\theta^{(s)}$ dalla distribuzione a posteriori;\n2. **Simulazione predittiva:** per ciascun $\\theta^{(s)}$, generiamo un possibile numero di successi futuri $\\tilde{y}^{(s)} \\sim \\text{Binomiale}(n_{\\text{new}}, \\theta^{(s)})$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Numero di prove nel nuovo esperimento\nn_new <- 1000\n\n# Campioni posteriori di theta\nposterior_theta <- as.numeric(fit1$draws(\"theta\", format = \"matrix\"))\n\n# Simulazione della distribuzione predittiva\nyrep_count <- rbinom(\n  n = length(posterior_theta),\n  size = n_new,\n  prob = posterior_theta\n)\n```\n:::\n\n\n#### Analisi dei risultati predittivi\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Statistiche riassuntive\nmean_pred <- mean(yrep_count)  \nci_pred <- quantile(yrep_count, c(0.025, 0.5, 0.975))\n\nc(Media = mean_pred, \n  \"2.5%\" = ci_pred[1], \n  \"Mediana\" = ci_pred[2], \n  \"97.5%\" = ci_pred[3])\n#>       Media   2.5%.2.5% Mediana.50% 97.5%.97.5% \n#>         165         134         164         197\n```\n:::\n\n\nLa media e i quantili della distribuzione predittiva riassumono le previsioni del modello:\nla media indica il numero di successi “atteso”, mentre i limiti dell’intervallo di credibilità esprimono il grado di incertezza.\n\n\n#### Visualizzazione della distribuzione predittiva\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntibble(Successi = yrep_count) |>\n  ggplot(aes(x = Successi)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 30, alpha = 0.7) +\n  geom_vline(xintercept = mean_pred, linetype = \"dashed\", linewidth = 1) +\n  geom_vline(xintercept = ci_pred[c(1,3)], linetype = \"dotted\", linewidth = 0.8) +\n  labs(\n    x = \"Numero di successi predetti\",\n    y = \"Densità\",\n    title = \"Distribuzione predittiva a posteriori\",\n    subtitle = \"Linea tratteggiata: media predittiva; linee puntinate: intervallo di credibilità al 95%\"\n  )\n```\n\n::: {.cell-output-display}\n![](03_stan_intro_files/figure-html/unnamed-chunk-14-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nIl grafico mostra la distribuzione dei possibili numeri di successi futuri:\nle linee verticali indicano la media predittiva e l’intervallo di credibilità al 95%.\n\n\n#### Analisi dei risultati predittivi con Stan e *bayesplot*\n\nUn modo alternativo — e spesso più elegante — per ottenere la distribuzione predittiva consiste nel *lasciare che sia Stan a generare i dati simulati* durante il campionamento, sfruttando il blocco `generated quantities`.\nIn questo modo l’intera procedura inferenziale (stima + previsione) rimane all’interno dello stesso modello.\n\n**1. Estensione del modello Stan**\n\nNel blocco `generated quantities` si può aggiungere la generazione di un nuovo numero di successi predetti $\\tilde{y}$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstancode_pred <- \"\ndata {\n  int<lower=1> N;                      // Numero di prove osservate\n  array[N] int<lower=0, upper=1> y;    // Esiti osservati\n  int<lower=1> N_new;                  // Numero di prove future\n}\ntransformed data {\n  int<lower=0, upper=N> k = sum(y);    // Successi osservati\n}\nparameters {\n  real<lower=0, upper=1> theta;        // Probabilità di successo\n}\nmodel {\n  theta ~ beta(1, 1);                  // Prior uniforme\n  k ~ binomial(N, theta);              // Verosimiglianza\n}\ngenerated quantities {\n  int yrep;                            // Successi predetti\n  yrep = binomial_rng(N_new, theta);   // Simulazione predittiva\n}\n\"\n```\n:::\n\n\nQuesto semplice blocco aggiunge, per ogni campione MCMC, una *replica simulata* del numero di successi futuri `yrep`.\n\n**2. Esecuzione del modello con Stan**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Preparazione dei dati per Stan\nstan_data_pred <- list(\n  N = length(y),\n  y = y,\n  N_new = 1000\n)\n\n# Compilazione e campionamento\nmod_pred <- cmdstan_model(write_stan_file(stancode_pred))\nfit_pred <- mod_pred$sample(\n  data = stan_data_pred,\n  iter_warmup = 1000,\n  iter_sampling = 2000,\n  chains = 4,\n  parallel_chains = 4,\n  seed = 4790,\n  refresh = 0\n)\n```\n:::\n\n\nOra ogni iterazione MCMC restituisce, oltre a `theta`, anche una simulazione predittiva `yrep`.\n\n**3. Estrazione e analisi della distribuzione predittiva**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Estrazione delle repliche predittive\nyrep_stan <- fit_pred$draws(\"yrep\", format = \"matrix\")\n\n# Statistiche riassuntive\nposterior::summarise_draws(\n  yrep_stan,\n  mean, sd, ~quantile(.x, c(0.025, 0.5, 0.975))\n)\n#> # A tibble: 1 × 6\n#>   variable  mean    sd `2.5%` `50%` `97.5%`\n#>   <chr>    <dbl> <dbl>  <dbl> <dbl>   <dbl>\n#> 1 yrep      165.  16.4    133   165     197\n```\n:::\n\n\nI risultati coincidono (entro l’errore Monte Carlo) con quelli ottenuti manualmente tramite `rbinom()`.\n\n**4. Visualizzazione con `bayesplot`**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbayesplot::mcmc_hist(\n  yrep_stan,\n  binwidth = 5,\n  color = \"white\"\n) +\n  vline_at(mean_pred, linetype = \"dashed\", linewidth = 1) +\n  vline_at(ci_pred[c(1,3)], linetype = \"dotted\", linewidth = 0.8) +\n  labs(\n    title = \"Distribuzione predittiva a posteriori (da Stan)\",\n    subtitle = \"Linea tratteggiata: media predittiva; linee puntinate: intervallo di credibilità al 95%\",\n    x = \"Numero di successi predetti\",\n    y = \"Densità\"\n  )\n```\n\n::: {.cell-output-display}\n![](03_stan_intro_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nIl grafico risultante è del tutto analogo a quello prodotto con `ggplot2`, ma qui la distribuzione predittiva proviene *direttamente dal modello Stan*, senza ulteriori passaggi in R.\n\n**5. Interpretazione**\n\nQuesto approccio offre due vantaggi principali:\n\n* l’intero processo di inferenza e previsione rimane *internamente coerente*, poiché le simulazioni sono basate sugli stessi campioni posteriori usati per stimare $\\theta$;\n* i risultati possono essere facilmente confrontati o riutilizzati in altre analisi bayesiane (*posterior predictive checks*, confronti modello–dati, ecc.).\n\n**In sintesi:**\nSia l’approccio manuale (con `rbinom()`) sia quello integrato in Stan producono la stessa distribuzione predittiva.\nTuttavia, includere la simulazione nel blocco `generated quantities` è la pratica più elegante e riproducibile, perché mantiene l’intera catena logica — dati, stima, previsione — all’interno del modello stesso.\n\n#### Interpretazione sostantiva\n\nLa distribuzione predittiva rappresenta una *previsione pienamente bayesiana*:\nnon si limita a usare un valore puntuale di $\\theta$, ma incorpora l’intera incertezza sul parametro.\n\n* **Scenario equo:** se il dado è equilibrato ($\\theta = 1/6 \\approx 0.167$), il numero atteso di successi in 1000 lanci sarebbe circa 167.\n* **Scenario osservato:** la distribuzione predittiva si centra intorno a $n_{\\text{new}} \\times \\mathbb{E}[\\theta \\mid y]$, riflettendo ciò che abbiamo appreso dai dati.\n* **Decisione inferenziale:** uno scostamento sistematico da questo scenario equo suggerirebbe che il dado non è bilanciato.\n\nIn sintesi, la distribuzione predittiva a posteriori *propaga l’incertezza* in modo coerente:\ndai parametri stimati alle osservazioni future.\nQuesto approccio fornisce previsioni più realistiche e complete rispetto a una semplice stima puntuale.\n\n## Dati continui: stima della media con varianza nota\n\nUn problema di base nelle scienze psicologiche è stimare la *media di popolazione* di una variabile continua. Per fissare le idee, pensiamo ai punteggi a un test di intelligenza (QI).\nPer concentrarci sull’idea chiave, *assumiamo nota* la deviazione standard della popolazione, $\\sigma = 15$. È un’ipotesi rara nella pratica, ma didatticamente utile: in questo modo l’unico parametro incognito è la media $\\mu$. La semplificazione aiuta a confrontare con chiarezza approccio classico e bayesiano.\n\n### Generazione dei dati simulati\n\nSupponiamo di raccogliere i punteggi di $n = 30$ partecipanti, ipotizzando che il valore vero della media nella popolazione sia $\\mu = 105$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nn <- 30\nsigma <- 15\ny_cont <- rnorm(n, mean = 105, sd = sigma)\n\ntibble(y = y_cont) |>\n  ggplot(aes(x = y)) +\n  geom_histogram(bins = 15, fill = PRIMARY, color = \"white\") +\n  labs(x = \"Punteggio\", y = \"Frequenza\") \n```\n\n::: {.cell-output-display}\n![](03_stan_intro_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n### Specificazione del modello bayesiano\n\n#### Verosimiglianza (componente probabilistica)\n\nAssumiamo osservazioni indipendenti, ciascuna con distribuzione Normale di media $\\mu$ e deviazione standard $\\sigma$ nota:\n\n$$\ny_i \\sim \\mathcal{N}(\\mu, \\sigma), \\quad \\text{per } i = 1, \\dots, n.\n$$\n\n#### Conoscenza a priori: la distribuzione prior\n\nPoniamo un *prior normale* su $\\mu$, centrato su $\\mu_0=100$ e con deviazione standard $\\tau=30$:\n\n$$\n\\mu \\sim \\mathcal{N}(\\mu_0, \\tau).\n$$\n\nUn $\\tau$ ampio riflette grande incertezza iniziale, lasciando che i dati “spostino” la posterior in modo sostanziale.\n\n### Implementazione in Stan\n\nIl modello bayesiano viene implementato nel seguente codice Stan:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstancode_norm <- \"\ndata {\n  int<lower=1> N;           // numerosità campionaria\n  vector[N] y;              // vettore delle osservazioni\n  real<lower=0> sigma;      // deviazione standard nota\n  real mu0;                 // media della distribuzione prior\n  real<lower=0> tau;        // deviazione standard del prior\n}\n\nparameters {\n  real mu;                  // parametro di interesse: media della popolazione\n}\n\nmodel {\n  // Distribuzione prior\n  mu ~ normal(mu0, tau);\n  \n  // Funzione di verosimiglianza\n  y ~ normal(mu, sigma);\n}\n\"\n```\n:::\n\n\n## Preparazione dei dati e campionamento MCMC\n\nI dati devono essere organizzati in una lista compatibile con la specifica del blocco `data`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstan_data2 <- list(\n  N     = length(y_cont),\n  y     = y_cont,\n  sigma = sigma,\n  mu0   = 100,\n  tau   = 30\n)\n```\n:::\n\n\nProcediamo quindi con la compilazione del modello e il campionamento mediante algoritmo MCMC:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod2 <- cmdstanr::cmdstan_model(write_stan_file(stancode_norm), compile = TRUE)\n\nfit2 <- mod2$sample(\n  data = stan_data2,\n  iter_warmup     = 1000,    # iterazioni di burn-in\n  iter_sampling   = 4000,    # iterazioni per campionamento\n  chains          = 4,       # numero di catene\n  parallel_chains = 4,       # catene parallele\n  seed            = 4790,    # seme per riproducibilità\n  refresh         = 0        # output silenziato\n)\n```\n:::\n\n\n## Analisi dei risultati\n\n### Sintesi numerica della distribuzione a posteriori\n\nI risultati del campionamento MCMC possono essere sintetizzati come segue:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprint(fit2$summary(variables = \"mu\"), n = Inf)\n#> # A tibble: 1 × 10\n#>   variable  mean median    sd   mad    q5   q95  rhat ess_bulk ess_tail\n#>   <chr>    <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>    <dbl>    <dbl>\n#> 1 mu        104.   104.  2.72  2.74  99.8  109.  1.00    5500.    7540.\n```\n:::\n\n\nAlternativamente, utilizzando il pacchetto `posterior`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndraws2 <- fit2$draws(variables = \"mu\", format = \"draws_matrix\")\nposterior::summarise_draws(\n  draws2, \n  mean, \n  sd, \n  ~quantile(.x, c(0.025, 0.5, 0.975)), \n  rhat, \n  ess_bulk, \n  ess_tail\n)\n#> # A tibble: 1 × 9\n#>   variable  mean    sd `2.5%` `50%` `97.5%`  rhat ess_bulk ess_tail\n#>   <chr>    <dbl> <dbl>  <dbl> <dbl>   <dbl> <dbl>    <dbl>    <dbl>\n#> 1 mu        104.  2.72   98.9  104.    110.  1.00    5500.    7540.\n```\n:::\n\n\n### Diagnostica della convergenza e interpretazione\n\n* **$\\hat R \\approx 1$** → catene ben mescolate e convergenti.\n* **ESS alto** → campioni efficaci, stime stabili.\n* **Media a posteriori** → stima puntuale bayesiana di $\\mu$.\n* **Intervallo di credibilità 95%** → incertezza residua sulla media (qui non enorme, dato $n=30$, ma ancora informativa).\n\n**In sintesi:** l’approccio bayesiano fornisce *l’intera posterior* di $\\mu$, non solo una media. All’aumentare di $n$, l’intervallo di credibilità si restringe: l’informazione dei dati domina sul prior.\n\n### Verifica analitica della coniugatezza\n\nCon $\\sigma^2$ nota e prior normale su $\\mu$, la posterior è *ancora normale* (coniugatezza). In forma chiusa:\n\n$$\n\\begin{aligned}\n\\text{Var}(\\mu \\mid \\mathbf{y}) &= \\left(\\frac{n}{\\sigma^2} + \\frac{1}{\\tau^2}\\right)^{-1}, \\\\\n\\mathbb{E}[\\mu \\mid \\mathbf{y}] &= \\text{Var}(\\mu \\mid \\mathbf{y}) \\cdot \\left(\\frac{n\\bar{y}}{\\sigma^2} + \\frac{\\mu_0}{\\tau^2}\\right).\n\\end{aligned}\n$$\n\n#### Calcolo analitico della posterior\n\nApplicando le formule ai nostri dati simulati:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calcolo delle quantità necessarie\nybar <- mean(y_cont)\ntau2 <- 30^2\nsigma2 <- sigma^2\n\n# Varianza e deviazione standard a posteriori\npost_var <- 1 / (n / sigma2 + 1 / tau2)\npost_sd <- sqrt(post_var)\n\n# Media a posteriori\npost_mean <- post_var * (n * ybar / sigma2 + 100 / tau2)\n\n# Risultati\nc(post_mean_closed = post_mean, post_sd_closed = post_sd)\n#> post_mean_closed   post_sd_closed \n#>           104.26             2.73\n```\n:::\n\n\n#### Confronto con le stime MCMC\n\nEstrazione dei campioni della catena MCMC per il parametro $\\mu$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmu_draws <- as.numeric(draws2[, \"mu\"])\nc(mean_mcmc = mean(mu_draws), sd_mcmc = sd(mu_draws))\n#> mean_mcmc   sd_mcmc \n#>    104.24      2.72\n```\n:::\n\n\nI valori *coincidono entro il rumore Monte Carlo*, validando sia il modello sia l’implementazione.\n\n### Visualizzazione dei risultati\n\nUn punto di partenza fondamentale è l'analisi dell'istogramma dei campioni MCMC:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbayesplot::mcmc_hist(fit2$draws(\"mu\"), \n                     binwidth = 1,\n                     fill = \"steelblue\", \n                     alpha = 0.7) +\n  labs(title = \"Distribuzione a posteriori di μ\",\n       subtitle = \"Stima della media della popolazione\",\n       x = \"Valore di μ\", \n       y = \"Frequenza\")\n```\n\n::: {.cell-output-display}\n![](03_stan_intro_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nQuesta visualizzazione non rappresenta semplicemente un singolo valore puntuale, ma mostra l'intero spettro di valori plausibili per il parametro $\\mu$, complete delle relative frequenze campionarie. La forma della distribuzione riflette l'incertezza residua sulla stima dopo aver incorporato sia l'informazione priorica sia l'evidenza empirica.\n\n#### Traiettorie delle catene\n\nPer valutare la convergenza delle catene MCMC, è utile esaminare le traiettorie di campionamento:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbayesplot::mcmc_trace(fit2$draws(\"mu\"), \n                      alpha = 0.7) +\n  labs(title = \"Traiettorie delle catene MCMC per μ\",\n       x = \"Iterazione\", \n       y = \"Valore di μ\") \n```\n\n::: {.cell-output-display}\n![](03_stan_intro_files/figure-html/unnamed-chunk-28-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n#### Densità delle catene\n\nLa sovrapposizione delle densità delle diverse catene fornisce un'ulteriore verifica della stabilità del campionamento:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbayesplot::mcmc_dens_overlay(fit2$draws(\"mu\")) +\n  labs(title = \"Densità a posteriori per μ\",\n       subtitle = \"Confronto tra le quattro catene MCMC\",\n       x = \"Valore di μ\", \n       y = \"Densità\")\n```\n\n::: {.cell-output-display}\n![](03_stan_intro_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nTracce ben mescolate e densità sovrapposte indicano una buona convergenza.\n\n#### Interpretazione metodologica\n\nQuesto esempio costituisce l'equivalente bayesiano di un \"test per la media\" in contesto parametrico, caratterizzato da:\n\n- deviazione standard della popolazione nota;\n- prior normale con elevata varianza iniziale sul parametro $\\mu$.\n\nA differenza dell'approccio frequentista tradizionale, che restituisce principalmente stime puntuali e intervalli di confidenza, il metodo bayesiano fornisce un'intera *distribuzione di probabilità a posteriori* per il parametro di interesse. \n\nQuesto rappresenta un vantaggio epistemologico significativo:\n\n- **Trasparenza**: l'incertezza viene comunicata in modo completo e intuitivo.\n- **Propagazione dell'incertezza**: la distribuzione a posteriori può essere direttamente utilizzata come input per fasi analitiche successive.\n- **Decisioni informate**: supporta processi decisionali che richiedono una quantificazione rigorosa del rischio.\n- **Previsioni robuste**: permette di generare previsioni che incorporano automaticamente l'incertezza parametrica.\n\nLa distribuzione a posteriori rappresenta quindi non solo una stima, ma uno strumento inferenziale completo che sintetizza in modo coerente l'informazione precedente e l'evidenza empirica.\n\n### Intervalli di credibilità nell'inferenza bayesiana\n\nPer sintetizzare questa distribuzione in forma interpretabile, si utilizzano gli intervalli di credibilità, che delimitano regioni di valori plausibili per il parametro condizionatamente al modello e ai dati osservati.\n\n#### Interpretazione probabilistica diretta\n\nQuando affermiamo che l'intervallo di credibilità al 94% per μ è [101, 110], intendiamo che esiste una probabilità del 94% che il parametro μ appartenga a questo intervallo, dato il modello specificato e i dati osservati. Formalmente:\n\nP(101 ≤ μ ≤ 110 | dati, modello) = 0.94.\n\nQuesta interpretazione è diretta e intuitiva, a differenza di quella degli intervalli di confidenza frequentisti, che si riferiscono alla frequenza di copertura in ipotetiche ripetizioni campionarie.\n\n#### Tipologie di intervalli di credibilità\n\nEsistono due principali tipologie di intervalli di credibilità, ciascuna con caratteristiche distintive.\n\n**L'intervallo Equal-Tailed (ETI)** è definito come l'intervallo che lascia probabilità uguali nelle code della distribuzione. Per un intervallo al 94%, lascia il 3% di probabilità nella coda inferiore e il 3% in quella superiore. I vantaggi dell'ETI includono la stabilità, essendo invariante rispetto a trasformazioni monotone del parametro, e la facilità di interpretazione. Il limite principale consiste nella possibile inclusione di regioni a bassa densità di probabilità in distribuzioni asimmetriche.\n\n**L'intervallo Highest Density (HDI)** è definito come l'intervallo più breve che contiene la probabilità specificata. Massimizza la densità di probabilità all'interno dell'intervallo, concentrandosi sulle regioni più credibili. I vantaggi dell'HDI includono l'efficienza, rappresentando la regione più credibile per il parametro, e la migliore adattabilità a distribuzioni asimmetriche. I limiti principali consistono nella non invarianza rispetto a trasformazioni monotone e nella possibile frammentazione in distribuzioni multimodali.\n\n#### Scelta tra ETI e HDI\n\nIn contesti pratici, la scelta tra i due tipi di intervallo dipende dalle caratteristiche della distribuzione a posteriori. Per distribuzioni simmetriche e unimodali, come la distribuzione normale, ETI e HDI coincidono. Per distribuzioni asimmetriche, l'HDI è generalmente preferibile poiché evita di includere valori a bassa plausibilità. La scelta finale dovrebbe essere guidata dalle caratteristiche specifiche della distribuzione a posteriori e dagli obiettivi inferenziali del ricercatore.\n\n#### Implementazione in R\n\nIl calcolo degli intervalli di credibilità può essere implementato in R attraverso diverse funzioni. Per l'Equal-Tailed Interval al 94%:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmu_samples <- as.numeric(fit2$draws(\"mu\"))\neti_94 <- quantile(mu_samples, probs = c(0.03, 0.97))\n```\n:::\n\n\nPer l'Highest Density Interval al 94%:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhdi_94 <- bayesplot::mcmc_areas(fit2$draws(\"mu\"), \n                               prob = 0.94, \n                               point_est = \"mean\")\n```\n:::\n\n\nLa visualizzazione degli intervalli di credibilità permette di comunicare efficacemente i risultati dell'analisi bayesiana, evidenziando sia la stima centrale sia l'incertezza associata al parametro di interesse.\n\n#### Visualizzazione degli intervalli di credibilità\n\nLa visualizzazione grafica degli intervalli di credibilità rappresenta uno strumento fondamentale per comunicare efficacemente i risultati dell'analisi bayesiana. Il pacchetto `bayesplot` offre funzioni specializzate per questo scopo.\n\nLa funzione `mcmc_areas()` permette di visualizzare la distribuzione a posteriori evidenziando gli intervalli di credibilità centrali. L'area colorata rappresenta la regione di credibilità, mentre la linea continua mostra la densità della distribuzione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calcolo dell'HDI per riferimento\nhdi94 <- bayesplot::mcmc_areas(fit2$draws(\"mu\"), prob = 0.94)\n\n# Visualizzazione principale con ETI\np <- bayesplot::mcmc_areas(fit2$draws(\"mu\"), prob = 0.94) +\n  labs(x = expression(mu), y = \"Densità\",\n       title = \"Distribuzione a posteriori di μ\",\n       subtitle = \"Area colorata: intervallo di credibilità al 94% (ETI)\") \np\n```\n\n::: {.cell-output-display}\n![](03_stan_intro_files/figure-html/unnamed-chunk-32-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nPer confrontare visivamente i due approcci, è possibile sovrapporre i limiti dell'HDI come linee verticali tratteggiate:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Estrai i draw del parametro\nmu_draws <- as.numeric(fit2$draws(\"mu\"))\n\n# --- ETI al 94% (equal-tailed) ---\neti_94 <- quantile(mu_draws, probs = c(0.03, 0.97))\neti_94\n#>    3%   97% \n#>  99.1 109.4\n#      3%     97%\n\n# --- HDI al 94% ---\nhdi_vals <- bayestestR::hdi(mu_draws, ci = 0.94)\nhdi_lower <- hdi_vals$CI_low\nhdi_upper <- hdi_vals$CI_high\nc(hdi_lower = hdi_lower, hdi_upper = hdi_upper)\n#> hdi_lower hdi_upper \n#>      99.2     109.5\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np <- bayesplot::mcmc_areas(fit2$draws(\"mu\"), prob = 0.94, point_est = \"mean\") +\n  labs(\n    x = expression(mu), y = \"Densità\",\n    title = \"Distribuzione a posteriori di \\u03BC\",\n    subtitle = \"Area colorata: intervallo di credibilità al 94% (ETI)\"\n  ) +\n  geom_vline(xintercept = c(hdi_lower, hdi_upper),\n             linetype = \"dashed\")\n\np\n```\n\n::: {.cell-output-display}\n![](03_stan_intro_files/figure-html/unnamed-chunk-34-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nQuesta rappresentazione visiva consente di apprezzare le differenze concettuali tra i due tipi di intervallo. Nel caso di distribuzioni simmetriche come quella normale qui considerata, ETI e HDI coincidono, rendendo le linee tratteggiate sovrapposte ai bordi dell'area colorata.\n\nLa visualizzazione grafica non solo facilita l'interpretazione dei risultati, ma costituisce anche un potente strumento didattico per comprendere le proprietà della distribuzione a posteriori e la natura degli intervalli di credibilità bayesiani.\n\n#### Posterior asimmetrica: esempio Beta\n\nIn distribuzioni asimmetriche, invece, le differenze emergono chiaramente. Un esempio utile è la distribuzione Beta(6,2), che mostra una coda a sinistra: in questo caso l’HDI risulta più corto e aderente alla parte densa della distribuzione, mentre l’ETI si estende ulteriormente verso la coda meno informativa.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\ntheta_draws <- rbeta(5000, shape1 = 6, shape2 = 2)\n\neti_beta <- bayestestR::eti(theta_draws, ci = 0.94)\nhdi_beta <- bayestestR::hdi(theta_draws, ci = 0.94)\n\neti_beta\n#> 94% ETI: [0.43, 0.96]\nhdi_beta\n#> 94% HDI: [0.49, 0.98]\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data.frame(theta = theta_draws), aes(x = theta)) +\n  geom_density() +\n  geom_vline(xintercept = c(eti_beta$CI_low, eti_beta$CI_high), linewidth = 0.7) +\n  geom_vline(xintercept = c(hdi_beta$CI_low, hdi_beta$CI_high), \n             linewidth = 1.2, linetype = \"dashed\") +\n  labs(x = expression(theta), y = \"Densità\")\n```\n\n::: {.cell-output-display}\n![](03_stan_intro_files/figure-html/unnamed-chunk-36-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n#### Quale livello utilizzare? 89%, 94% o 95%?\n\nRimane infine la questione di quale livello di probabilità utilizzare. La tradizione frequentista ha reso familiare il 95%, e molti analisti continuano a preferirlo per ragioni di continuità. Altri autori, come McElreath, suggeriscono il 94%, mentre Kruschke propone l’89% come scelta più stabile con campioni ridotti. In realtà non esiste una soglia “corretta” in senso assoluto: ciò che conta è la coerenza interna dell’analisi e la chiarezza nel riportare sia il livello scelto sia la definizione di intervallo adottata. In presenza di distribuzioni asimmetriche può essere particolarmente istruttivo mostrare sia l’ETI sia l’HDI, perché offrono prospettive complementari sulla distribuzione a posteriori del parametro.\n\n## Test di ipotesi in prospettiva bayesiana\n\nL’approccio bayesiano consente di formulare domande in termini diretti e intuitivi, ad esempio:\n\n> *“Qual è la probabilità che la media superi una determinata soglia?”*\n\nQuesta impostazione si discosta da quella frequentista, che restituisce soltanto un esito dicotomico di rifiuto o non rifiuto dell’ipotesi nulla. In ambito bayesiano, al contrario, si ottiene una misura continua della plausibilità di ciascuna ipotesi, che rende l’incertezza più trasparente e consente di esprimere giudizi graduati.\n\n### Probabilità a posteriori sopra una soglia\n\nRiprendiamo l’esempio dei punteggi QI con modello normale a varianza nota. Una prima domanda semplice è calcolare\n\n$$\nP(\\mu > 110 \\mid y),\n$$\n\ncioè la probabilità che la media di popolazione superi il valore 110.\n\nQuesta quantità si ricava facilmente dai campioni MCMC della distribuzione a posteriori di $\\mu$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Estraiamo i campioni MCMC per mu\nmu_draws <- as.numeric(fit2$draws(\"mu\"))\n\n# Calcoliamo la probabilità che mu superi la soglia 110\np_gt_110 <- mean(mu_draws > 110)\np_gt_110\n#> [1] 0.0193\n```\n:::\n\n\nIl risultato rappresenta la probabilità, condizionatamente a modello e dati, che $\\mu$ sia superiore a 110. Non si tratta dunque di un’affermazione sì/no, ma di una misura graduata della plausibilità.\n\nIl valore può essere verificato anche in forma analitica, sfruttando la coniugatezza del modello normale-normale:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calcolo analitico con distribuzione normale coniugata\np_gt_110_closed <- 1 - pnorm(110, mean = post_mean, sd = post_sd)\nc(MCMC = p_gt_110, ClosedForm = p_gt_110_closed)\n#>       MCMC ClosedForm \n#>     0.0193     0.0176\n```\n:::\n\n\nI due risultati dovrebbero coincidere, salvo piccole discrepanze dovute al rumore Monte Carlo.\n\n### Decisione pratica e ROPE\n\nLa valutazione delle ipotesi acquista senso compiuto solo quando si traduce in una decisione. Una regola semplice consiste nell’agire come se $\\mu > 110$ qualora la probabilità a posteriori superi una soglia prefissata $p^\\*$, scelta in base al bilancio tra costi e benefici. Ad esempio, con $p^\\* = 0.90$ si decide di agire solo se $P(\\mu > 110 \\mid y) \\geq 0.90$, altrimenti si rinvia o si raccolgono nuovi dati. La soglia $p^\\*$ non è arbitraria: un valore troppo basso aumenta il rischio di un’azione ingiustificata, mentre un valore troppo alto espone al rischio di trascurare un’azione necessaria. L’approccio bayesiano ha il merito di rendere esplicito questo nesso tra evidenza statistica e conseguenze pratiche, permettendo di calibrare la decisione sulla base delle priorità del contesto.\n\nSpesso, tuttavia, l’interesse non è stabilire se la media sia *esattamente* pari a un certo valore, ma se possa essere considerata *praticamente equivalente* a esso entro un margine di tolleranza ritenuto accettabile. Per questo si introduce la *ROPE* (*Region of Practical Equivalence*), che definisce un intervallo attorno al valore soglia. Nel nostro esempio poniamo:\n\n$$\n\\text{ROPE} = [108,\\,112].\n$$\nL’idea non è più chiedersi se $\\mu = 110$, ma se $\\mu$ appartenga a un intervallo che, per il problema in esame, può essere considerato equivalente a 110.\n\n### Calcolo e interpretazione\n\nA partire dai campioni MCMC possiamo stimare la probabilità che $\\mu$ cada al di sotto, all’interno o al di sopra della ROPE:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrope <- c(108, 112)\n\nP_below <- mean(mu_draws <  rope[1])                       # Probabilità sotto ROPE\nP_in    <- mean(mu_draws >= rope[1] & mu_draws <= rope[2]) # Probabilità dentro ROPE\nP_above <- mean(mu_draws >  rope[2])                       # Probabilità sopra ROPE\n\nc(P_below = P_below, P_in = P_in, P_above = P_above)\n#> P_below    P_in P_above \n#> 0.91463 0.08250 0.00287\n```\n:::\n\n\nSe la distribuzione a posteriori è ben approssimata da una Normale, gli stessi valori possono essere calcolati anche in forma chiusa:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nP_below_cf <- pnorm(rope[1], mean = post_mean, sd = post_sd)\nP_in_cf    <- pnorm(rope[2], mean = post_mean, sd = post_sd) -\n              pnorm(rope[1], mean = post_mean, sd = post_sd)\nP_above_cf <- 1 - pnorm(rope[2], mean = post_mean, sd = post_sd)\n\nc(P_below_cf = P_below_cf, P_in_cf = P_in_cf, P_above_cf = P_above_cf)\n#> P_below_cf    P_in_cf P_above_cf \n#>    0.91498    0.08275    0.00226\n```\n:::\n\n\nSe la probabilità che $\\mu$ cada all’interno della ROPE è elevata, si conclude che la media è praticamente equivalente al valore soglia. Se invece la probabilità si concentra al di sopra o al di sotto dell’intervallo, si parla rispettivamente di un’evidenza che $\\mu$ sia superiore o inferiore in senso rilevante. Nel caso in cui nessuna delle tre categorie prevalga nettamente, l’esito è quello di incertezza: in tale situazione è opportuno raccogliere ulteriori dati o riconsiderare l’ampiezza della ROPE adottata.\n\n### Esempio di report\n\n> Con ROPE = $[108,112]$, si ottiene: $P(\\mu < 108) = 0.92$, $P(108 \\leq \\mu \\leq 112) = 0.08$, $P(\\mu > 112) = 0.003$.\n> Questi risultati indicano che la media $\\mu$ è con alta probabilità *inferiore* a 110, nel senso pratico definito dalla ROPE.\n\n## Diagnostiche di campionamento\n\nDopo aver ottenuto i campioni dalla distribuzione a posteriori, il passo successivo è verificare la loro qualità. Un modello ben specificato e un campionamento MCMC efficiente producono catene che esplorano in modo completo e bilanciato lo spazio dei parametri. Per questo, nei riepiloghi forniti da Stan e dai pacchetti associati compaiono alcune statistiche diagnostiche fondamentali, che meritano attenzione. La quantità `lp__` compare in ogni output: non è un parametro del modello, ma la log-densità a posteriori, utile come strumento di controllo.\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit2$summary(variables = c(\"mu\",\"lp__\"))\n#> # A tibble: 2 × 10\n#>   variable  mean median    sd   mad    q5   q95  rhat ess_bulk ess_tail\n#>   <chr>    <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>    <dbl>    <dbl>\n#> 1 mu       104.   104.  2.72  2.74   99.8 109.   1.00    5500.    7540.\n#> 2 lp__     -14.5  -14.2 0.705 0.313 -15.9 -14.0  1.00    7357.    9176.\n```\n:::\n\n\nUn primo indicatore chiave è la statistica di convergenza $\\hat{R}$ (o *R-hat*). Essa confronta la variabilità *intra-catena* con quella *inter-catena*: quando le catene hanno raggiunto lo stesso equilibrio, oscillano nelle stesse regioni della distribuzione e $\\hat{R}$ tende a 1. Nel nostro esempio, i valori sono 1.001 per `mu` e 1.001 per `lp__`, praticamente indistinguibili da 1. In generale, valori inferiori a 1.01 sono considerati ottimali, mentre valori superiori a 1.05 segnalano possibili problemi di convergenza.\n\nUn secondo gruppo di statistiche riguarda la dimensione del campione effettivo (ESS, *effective sample size*). Poiché i campioni MCMC sono correlati, l’ESS misura a quanti campioni indipendenti essi siano “equivalenti”. Nel nostro caso, per `mu` l’ESS è pari a 5500 (bulk) e 7540 (tail), mentre per `lp__` è rispettivamente 7357 e 9176. Si tratta di valori elevati, che assicurano stime stabili anche per i quantili estremi. A titolo illustrativo, l’errore Monte Carlo sulla media di `mu`, calcolato come $\\text{sd}/\\sqrt{\\text{ESS}}$, è circa 0.04: un valore trascurabile rispetto alla deviazione standard della posterior, pari a 2.72.\n\nOltre agli indici numerici, è utile considerare la forma della distribuzione stimata. Nel riepilogo, la media (104.24) e la mediana (104.24) coincidono quasi perfettamente, segnalando una distribuzione sostanzialmente simmetrica. La deviazione standard (2.72) e la MAD (2.74) risultano molto vicine, confermando che la variabilità è ben catturata. I quantili dal 5° al 95° definiscono un intervallo credibile al 90% compreso tra circa  e : ne consegue che la soglia 110 si colloca al di sopra di questo intervallo, con bassa probabilità di essere superata.\n\nPer un riscontro visivo della dinamica delle catene, il *traceplot* deve mostrare linee ben mescolate, senza trend o stazionamenti anomali:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbayesplot::mcmc_trace(fit2$draws(\"mu\"), n_warmup = 1000)\n```\n\n::: {.cell-output-display}\n![](03_stan_intro_files/figure-html/unnamed-chunk-43-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nUn’ulteriore verifica consiste nel confronto delle densità tra catene:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbayesplot::mcmc_dens_overlay(fit2$draws(\"mu\"))\n```\n\n::: {.cell-output-display}\n![](03_stan_intro_files/figure-html/unnamed-chunk-44-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nLa buona sovrapposizione delle curve indica che le catene hanno raggiunto la stessa distribuzione stazionaria.\n\nInfine, `lp__` — la log-densità a posteriori — non è un parametro di interesse sostantivo ma uno strumento diagnostico: anche per `lp__` gli indici $\\hat{R}$ e ESS risultano eccellenti (1.001, 7357/9176), confermando un’esplorazione regolare dello spazio dei parametri.\n\nIn sintesi, tutti gli indici diagnostici — $\\hat{R}$ prossimo a 1, ESS elevati, coerenza tra media, mediana e misure di dispersione, oltre a traceplot e densità sovrapposte — convergono verso la stessa conclusione: il campionamento MCMC è stato stabile ed efficiente. Possiamo quindi considerare le stime ottenute come una rappresentazione affidabile della distribuzione a posteriori prevista dal nostro modello.\n\n### Prior e Posterior Predictive Check\n\nUn passaggio cruciale nell’analisi bayesiana consiste nel verificare la capacità del modello di generare dati plausibili. Questo controllo può avvenire in due momenti distinti.\n\nPrima dell’osservazione dei dati si esegue il *prior predictive check*, che serve a valutare se il prior scelto sia compatibile con valori ragionevoli. Se, ad esempio, i priors producono simulazioni di punteggi di QI del tutto inverosimili, è segno che occorre rivederne la specificazione.\n\nDopo l’aggiornamento con i dati osservati, si procede al *posterior predictive check*. In questa fase l’attenzione si sposta sulla capacità del modello stimato di riprodurre l’evidenza empirica: i dati simulati a posteriori dovrebbero assomigliare ai dati reali, sia nelle tendenze centrali sia nella variabilità. Se emergono scostamenti sistematici, ciò indica che il modello non riesce a catturare adeguatamente il fenomeno e richiede un perfezionamento.\n\nQuesti concetti sono già stati introdotti in precedenza; qui ci concentreremo sulla loro implementazione pratica utilizzando l’ecosistema di Stan.\n\n### Prior Predictive Check\n\nIl primo passo, prima ancora di osservare i dati, è verificare se le nostre assunzioni a priori producono valori plausibili. In termini concreti: il prior scelto per $\\mu$ genera punteggi di QI che hanno senso rispetto al dominio del problema?\n\nIl modello è definito come\n\n$$\ny_i \\mid \\mu \\sim \\mathcal{N}(\\mu, \\sigma), \n\\qquad\n\\mu \\sim \\mathcal{N}(\\mu_0, \\tau).\n$$\n\nCombinando la verosimiglianza con il prior, otteniamo la *distribuzione predittiva a priori* per una singola osservazione:\n\n$$\ny_i \\sim \\mathcal{N}\\!\\Big(\\mu_0,\\; \\sqrt{\\sigma^2 + \\tau^2}\\Big).\n$$\nQuesta distribuzione descrive quali valori ci aspetteremmo *prima di osservare alcun dato*. Se produce valori estremamente inverosimili (ad esempio QI < 40 o > 160), significa che il prior è troppo *ampio* o mal centrato. Se invece concentra quasi tutta la massa in un intervallo ristretto, rischia di essere *eccessivamente informativo*, lasciando poco spazio ai dati.\n\n#### Implementazione in Stan\n\nPer eseguire un *prior predictive check* possiamo utilizzare lo stesso modello Stan destinato all’inferenza, con una piccola modifica. Introduciamo una variabile booleana `compute_likelihood` che decide se attivare o meno la riga `y ~ normal(mu, sigma);`. In questo modo possiamo “spegnere” la verosimiglianza e simulare esclusivamente dal prior. Inoltre, nel blocco `generated quantities` generiamo delle repliche $y_{\\text{rep}}$ da confrontare con i dati osservati.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstancode_norm_ppc <- \"\ndata {\n  int<lower=0> N;\n  vector[N] y;                 // usato solo se compute_likelihood=1\n  real<lower=0> sigma;         // sd nota\n  real mu0;                    // media del prior su mu\n  real<lower=0> mu_prior_sd;   // sd del prior\n  int<lower=0, upper=1> compute_likelihood; // 1 = attiva likelihood\n}\nparameters {\n  real mu;\n}\nmodel {\n  mu ~ normal(mu0, mu_prior_sd);\n  if (compute_likelihood == 1) {\n    y ~ normal(mu, sigma);\n  }\n}\ngenerated quantities {\n  vector[N] y_rep;\n  vector[N] log_lik; \n\n  for (n in 1:N) {\n    y_rep[n] = normal_rng(mu, sigma); \n    log_lik[n] = normal_lpdf(y[n] | mu, sigma); \n  }\n}\n\"\nstanmod_ppc <- cmdstan_model(write_stan_file(stancode_norm_ppc), compile = TRUE)\n```\n:::\n\n\nPer un controllo *puro* del prior impostiamo `compute_likelihood = 0`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nN_ppc <- length(y_cont)\n\nstan_data_prior <- list(\n  N = N_ppc,\n  y = rep(0, N_ppc),   # placeholder, ignorato se compute_likelihood=0\n  sigma = sigma,\n  mu0 = 100,\n  mu_prior_sd = 30,\n  compute_likelihood = 0\n)\n\nfit_prior <- stanmod_ppc$sample(\n  data = stan_data_prior,\n  iter_warmup = 500,\n  iter_sampling = 2000,\n  chains = 4,\n  parallel_chains = 4,\n  seed = 4790,\n  refresh = 500\n)\n```\n:::\n\n\nDopo il campionamento estraiamo le repliche $y_{\\text{rep}}$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Estrazione delle repliche\nyrep_mat_prior <- posterior::as_draws_matrix(fit_prior$draws(\"y_rep\"))\n\n# Selezione delle colonne y_rep[1],...,y_rep[N]\nyrep_mat_prior <- as.matrix(\n  yrep_mat_prior[, paste0(\"y_rep[\", 1:N_ppc, \"]\")]\n)\n```\n:::\n\n\nPossiamo ora confrontare i dati osservati con alcune repliche simulate:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nidx <- sample(seq_len(nrow(yrep_mat_prior)), 100)\n\nbayesplot::ppc_dens_overlay(\n  y = y_cont,\n  yrep = yrep_mat_prior[idx, , drop = FALSE]\n) \n```\n\n::: {.cell-output-display}\n![](03_stan_intro_files/figure-html/unnamed-chunk-48-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n#### Interpretazione\n\nSe le distribuzioni simulate dal prior coprono la gamma dei dati reali, le nostre assunzioni iniziali sono plausibili. Se invece risultano troppo ampie o troppo strette, occorre ripensare la scelta di `mu_prior_sd` o la posizione del prior. In questo senso, il *prior predictive check* rappresenta un primo banco di prova fondamentale: ci permette di verificare se il modello, ancora prima di vedere i dati, è coerente con le conoscenze di base sul fenomeno studiato.\n\nNel grafico vediamo la distribuzione osservata dei punteggi (linea scura) confrontata con un insieme di repliche simulate dal prior (linee chiare). L’insieme delle simulazioni copre bene la variabilità dei dati reali: i punteggi osservati cadono in una regione ampiamente compatibile con quanto previsto a priori. Questo indica che il prior scelto è sufficientemente ampio da includere valori plausibili, senza però generare in prevalenza esiti palesemente irrealistici.\n\nL’esercizio conferma quindi che le assunzioni iniziali sul parametro $\\mu$ non introducono vincoli eccessivi né distorsioni forti. Il modello, ancora prima di essere aggiornato con i dati, è coerente con la conoscenza di base sul fenomeno considerato (i punteggi di QI), e può essere usato come punto di partenza per l’inferenza bayesiana.\n\n### Posterior Predictive Check\n\nDopo aver verificato la plausibilità del *prior*, il passo successivo è valutare se il modello, una volta aggiornato con i dati, riesca a riprodurre in modo realistico l’evidenza empirica. Questo è lo scopo del *posterior predictive check*. Abbiamo già incontrato questo strumento nel caso del modello beta-binomiale; qui lo applichiamo al modello normale con prior normale, sfruttando le funzioni di Stan.\n\nPer procedere, riattiviamo la verosimiglianza (`compute_likelihood = 1`) e stimiamo la distribuzione a posteriori di $\\mu$. Nel blocco `generated quantities` Stan genera repliche $y_{\\text{rep}}$, ossia nuovi dataset simulati sotto l’ipotesi che il modello e i parametri stimati siano corretti. Il confronto fra i dati osservati e queste repliche permette di valutare direttamente la capacità predittiva del modello.\n\nIl principio è semplice: il *prior predictive check* serve a valutare le assunzioni prima di vedere i dati, mentre il *posterior predictive check* indaga se, dopo l’aggiornamento, il modello sia effettivamente in grado di riprodurre il fenomeno osservato.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstan_data_post <- list(\n  N = length(y_cont),\n  y = y_cont,\n  sigma = sigma,\n  mu0 = 100,\n  mu_prior_sd = 30,\n  compute_likelihood = 1\n)\n```\n:::\n\n\nIl campionamento da Stan:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_post <- stanmod_ppc$sample(\n  data = stan_data_post,\n  iter_warmup = 1000,\n  iter_sampling = 10000,\n  chains = 4,\n  parallel_chains = 4,\n  seed = 4790,\n  refresh = 1000\n)\n```\n:::\n\n\nUna volta estratte le repliche, possiamo confrontarle con i dati reali:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ny_rep <- fit_post$draws(\"y_rep\", format = \"matrix\")\nppc_dens_overlay(y = stan_data_post$y, yrep = y_rep[1:100, ])\n```\n\n::: {.cell-output-display}\n![](03_stan_intro_files/figure-html/unnamed-chunk-51-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nSe le distribuzioni simulate coprono bene quella dei dati osservati, il modello descrive adeguatamente il fenomeno. Al contrario, scostamenti sistematici — ad esempio repliche con media troppo bassa o varianza troppo elevata — segnalano che il modello non cattura pienamente la realtà e dovrebbe essere rivisto.\n\nIl collegamento con la fase di verifica dei *prior* è immediato: un prior troppo vago può generare simulazioni poco credibili già in fase predittiva a priori, mentre un prior troppo rigido rischia di imporre vincoli eccessivi. Nel *posterior predictive check*, tuttavia, ciò che conta è il risultato finale: dopo l’aggiornamento con i dati, le simulazioni devono riflettere con realismo l’evidenza empirica.\n\nNel grafico osserviamo la distribuzione empirica dei punteggi (linea scura) affiancata a un insieme di repliche simulate dalla distribuzione a posteriori (linee chiare). A differenza del controllo sul *prior*, qui il modello è stato aggiornato con i dati, e le simulazioni riflettono sia le assunzioni iniziali sia l’informazione empirica raccolta.\n\nIl confronto mostra una buona corrispondenza: le repliche coprono con realismo la forma della distribuzione osservata, senza evidenziare scostamenti sistematici. In particolare, la media delle repliche si allinea bene a quella dei dati reali, e la variabilità simulata risulta compatibile con quella empirica. Questo conferma quanto già emerso dall’analisi numerica: la stima a posteriori della media $\\mu$ (circa 104) è coerente con il campione osservato e attribuisce bassa probabilità all’ipotesi che $\\mu$ superi la soglia di 110.\n\nNel complesso, il *posterior predictive check* suggerisce che il modello normale con prior scelto descrive adeguatamente il fenomeno considerato (i punteggi QI in questo esempio). Si tratta quindi di una base affidabile per trarre conclusioni inferenziali e, se necessario, collegare i risultati a decisioni pratiche.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nStan rappresenta il punto di approdo naturale del percorso seguito fin qui. Dopo aver introdotto la logica dell’inferenza bayesiana con algoritmi semplici come Metropolis e aver visto come i linguaggi probabilistici abbiano reso più accessibile questa logica, Stan ci mette ora a disposizione uno strumento capace di tradurre queste idee in pratica su modelli reali e complessi.\n\nIl suo valore non risiede soltanto nella potenza computazionale, ma soprattutto nella possibilità di *spostare l’attenzione dal calcolo all’idea scientifica*. Con Stan possiamo formulare ipotesi psicologiche in termini formali, esplicitarne le assunzioni e sottoporle a verifica empirica in modo trasparente e riproducibile. Il ricercatore non è più costretto a concentrarsi sui dettagli algoritmici, ma può dedicarsi a ciò che conta davvero: la sostanza teorica del modello e la sua capacità di descrivere i dati.\n\nNei capitoli che seguono impareremo a utilizzarlo prima con esempi semplici, per poi estendere gradualmente l’analisi a modelli più articolati. L’obiettivo non è solo acquisire familiarità con la sintassi, ma soprattutto interiorizzare un *modo di pensare*: quello che fa della modellazione bayesiana uno strumento essenziale della psicologia scientifica contemporanea.\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.5.1 (2025-06-13)\n#> Platform: aarch64-apple-darwin20\n#> Running under: macOS Tahoe 26.0.1\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] insight_1.4.2         cmdstanr_0.9.0        ragg_1.5.0           \n#>  [4] tinytable_0.13.0      withr_3.0.2           systemfonts_1.3.1    \n#>  [7] patchwork_1.3.2       ggdist_3.3.3          tidybayes_3.0.7      \n#> [10] bayesplot_1.14.0      ggplot2_4.0.0         reliabilitydiag_0.2.1\n#> [13] priorsense_1.1.1      posterior_1.6.1       loo_2.8.0            \n#> [16] rstan_2.32.7          StanHeaders_2.32.10   brms_2.23.0          \n#> [19] Rcpp_1.1.0            sessioninfo_1.2.3     conflicted_1.2.0     \n#> [22] janitor_2.2.1         matrixStats_1.5.0     modelr_0.1.11        \n#> [25] tibble_3.3.0          dplyr_1.1.4           tidyr_1.3.1          \n#> [28] rio_1.2.4             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] gridExtra_2.3         inline_0.3.21         sandwich_3.1-1       \n#>  [4] rlang_1.1.6           magrittr_2.0.4        multcomp_1.4-28      \n#>  [7] snakecase_0.11.1      ggridges_0.5.7        compiler_4.5.1       \n#> [10] reshape2_1.4.4        vctrs_0.6.5           stringr_1.5.2        \n#> [13] pkgconfig_2.0.3       arrayhelpers_1.1-0    fastmap_1.2.0        \n#> [16] backports_1.5.0       labeling_0.4.3        utf8_1.2.6           \n#> [19] rmarkdown_2.30        ps_1.9.1              purrr_1.1.0          \n#> [22] xfun_0.53             cachem_1.1.0          jsonlite_2.0.0       \n#> [25] broom_1.0.10          parallel_4.5.1        R6_2.6.1             \n#> [28] stringi_1.8.7         RColorBrewer_1.1-3    lubridate_1.9.4      \n#> [31] estimability_1.5.1    knitr_1.50            zoo_1.8-14           \n#> [34] pacman_0.5.1          Matrix_1.7-4          splines_4.5.1        \n#> [37] timechange_0.3.0      tidyselect_1.2.1      abind_1.4-8          \n#> [40] yaml_2.3.10           codetools_0.2-20      processx_3.8.6       \n#> [43] curl_7.0.0            pkgbuild_1.4.8        plyr_1.8.9           \n#> [46] lattice_0.22-7        bayestestR_0.17.0     bridgesampling_1.1-2 \n#> [49] S7_0.2.0              coda_0.19-4.1         evaluate_1.0.5       \n#> [52] survival_3.8-3        RcppParallel_5.1.11-1 pillar_1.11.1        \n#> [55] tensorA_0.36.2.1      checkmate_2.3.3       stats4_4.5.1         \n#> [58] distributional_0.5.0  generics_0.1.4        rprojroot_2.1.1      \n#> [61] rstantools_2.5.0      scales_1.4.0          xtable_1.8-4         \n#> [64] glue_1.8.0            emmeans_1.11.2-8      tools_4.5.1          \n#> [67] data.table_1.17.8     mvtnorm_1.3-3         grid_4.5.1           \n#> [70] QuickJSR_1.8.1        colorspace_2.1-2      nlme_3.1-168         \n#> [73] cli_3.6.5             textshaping_1.0.4     svUnit_1.0.8         \n#> [76] Brobdingnag_1.2-9     V8_8.0.1              gtable_0.3.6         \n#> [79] digest_0.6.37         TH.data_1.1-4         htmlwidgets_1.6.4    \n#> [82] farver_2.1.2          memoise_2.0.1         htmltools_0.5.8.1    \n#> [85] lifecycle_1.0.4       MASS_7.3-65\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n\n",
    "supporting": [
      "03_stan_intro_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}