{
  "hash": "c2451d4ee003eb9607e862797f5d1356",
  "result": {
    "engine": "knitr",
    "markdown": "# Modellazione dell'eterogeneità: soggetti, popolazione e condizioni {#sec-formal-models-developments}\n\n::: {.callout-note appearance=\"minimal\"}\n\nSeguendo il tutorial di @knight2023tutorial, in questo capitolo estendiamo il modello presentato in precedenza lungo tre direzioni complementari. Partiamo dal livello individuale, in cui stimiamo i parametri di ciascun partecipante ($\\alpha_i, \\beta_i$). Questo passaggio consente di mappare l'eterogeneità interindividuale (sensibilità al feedback e deriva motivazionale), ma le stime dei singoli rimangono isolate le une dalle altre.\n\nPer superare questo limite introduciamo la versione *gerarchica (multilevel)*: i parametri dei singoli sono considerati *estratti* da distribuzioni di popolazione (es. normali) descritte da iperparametri. In questo modo le informazioni vengono condivise tra individui, con il tipico effetto di *shrinkage* che stabilizza le stime, soprattutto quando i dati per soggetto sono pochi o rumorosi.\n\nInfine, consideriamo il caso dei *gruppi noti*, stimando iperparametri separati per ciascuna condizione. Ciò permette di quantificare differenze sistematiche *a livello di popolazione* tra condizioni sperimentali, oltre alle differenze tra individui. Valuteremo i modelli con criteri *predittivi* (ELPD tramite *LOO-CV*), così da bilanciare in modo esplicito *complessità* e *capacità di generalizzazione*. \n:::\n\n### Obiettivi di apprendimento {.unnumbered .unlisted}\n\nAl termine del capitolo saprai:\n\n- modellare l’eterogeneità con tre granulosità (sample-level, person-level, gerarchico);\n- stimare e interpretare $(\\alpha_i, \\beta_i)$ e gli iper-parametri di popolazione;\n- valutare i modelli con ELPD/LOO e diagnosticare problemi (Pareto-k, divergenze);\n- tradurre risultati in implicazioni psicologiche (apprendimento vs drift) evitando conclusioni iperboliche;\n- costruire figure che mostrano shrinkage e differenze tra condizioni.\n\n### Panoramica del capitolo {.unnumbered .unlisted}\n\n* *Modello a livello individuale*: stima di $\\alpha_i$ e $\\beta_i$ per ogni soggetto.\n* *Modello gerarchico*: parametri individuali estratti da distribuzioni di popolazione → *shrinkage* e maggiore robustezza.\n* *Gruppi noti*: iper-parametri specifici per condizione (*approach* vs *avoidance*).\n* *Confronto predittivo*: ELPD e *LOO-CV* per scegliere il modello.\n* *Implicazioni psicologiche*: quando e perché la gerarchia migliora l’inferenza.\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n\nsuppressPackageStartupMessages({\n  library(cmdstanr)\n  library(bayesplot)\n  library(tidybayes)\n  library(posterior)\n  library(loo)\n  library(patchwork)\n  library(conflicted)\n})\n\nconflicts_prefer(loo::loo)\nconflicts_prefer(dplyr::count)\n```\n:::\n\n:::\n\n## Modello a livello individuale \n\n::: {.callout-tip title=\"Perché non basta un unico parametro per tutti?\"}\nIl modello *sample-level*, stimando un **unico set di parametri per l'intera popolazione**, **maschera l'eterogeneità individuale**. Sebbene possa fornire un quadro generale, tale semplificazione è **suscettibile di produrre inferenze fuorvianti** in psicologia, dove i processi di interesse, come l'apprendimento o la motivazione, sono intrinsecamente variabili tra individui.\n\nIl modello *person-level* supera questa limitazione **stimando separatamente i parametri per ciascun partecipante** $(\\alpha_i, \\beta_i)$. Questo approccio consente di (i) quantificare la **sensibilità idiosincratica al feedback** e (ii) tracciare la **dinamica individuale della motivazione** (*deriva motivazionale*), rendendo conto direttamente della variabilità psicologica interindividuale.\n:::\n\nA differenza del modello *sample-level*, analizzato in precedenza, che stima un unico insieme di parametri $(\\alpha_i, \\beta_i)$ per l'intero campione, risultando così insensibile alle differenze individuali, il modello a livello individuale (o *person-level*) introduce un importante avanzamento concettuale e metodologico. Questo approccio stima parametri distinti, $\\alpha_i$ e $\\beta_i$, per ciascun partecipante, riconoscendo esplicitamente l'eterogeneità presente nella popolazione.\n\nNella sua formulazione, il modello assegna a ogni individuo un tasso di apprendimento $\\alpha_i$ e una deriva motivazionale $\\beta_i$ personalizzati. Questi parametri catturano, rispettivamente, la sensibilità specifica di un soggetto al feedback ricevuto e la sua inclinazione motivazionale intrinseca. Il parametro $\\sigma$, che rappresenta la variabilità residua o il rumore decisionale, è solitamente considerato comune a tutti i partecipanti, assumendo che l'errore di processo sia fondamentalmente simile tra gli individui.\n\nL'adozione di un modello a livello individuale offre diversi vantaggi analitici. In primo luogo, consente di mappare con precisione la variabilità interindividuale nei processi cognitivi sottostanti l'aggiornamento degli obiettivi. In secondo luogo, permette di identificare profili comportamentali distinti, come, ad esempio, soggetti altamente reattivi al feedback contrapposti ad altri che mostrano un adattamento più contenuto. Infine, questo modello evita l'assunzione, spesso irrealistica, che tutti i partecipanti rispondano agli stimoli ambientali in modo identico.\n\nÈ tuttavia necessario notare che il modello a livello individuale, nella sua forma pura, non incorpora alcun meccanismo di condivisione delle informazioni tra i soggetti. Ogni partecipante viene modellato in modo completamente indipendente dagli altri. È proprio questa caratteristica a distinguerlo dal modello gerarchico (o *multilevel*), nel quale i parametri individuali vengono concettualizzati come provenienti da una distribuzione di gruppo sovraordinata. Questa struttura gerarchica, che verrà esaminata in seguito, migliora notevolmente la robustezza e l'affidabilità delle stime, soprattutto quando si lavora con serie di dati limitate o particolarmente rumorose.\n\n### Preparazione dei dati\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Caricamento del dataset\ndat <- rio::import(\"data/goal_data.csv\")\n\n# Ordina i dati per soggetto e per trial\ndat <- dat |> \n  arrange(subject, trial)\n\n# (Opzionale) Verifica che l'ordinamento sia corretto\nstr(dat)\n#> 'data.frame':\t600 obs. of  5 variables:\n#>  $ subject    : int  1 1 1 1 1 1 1 1 1 1 ...\n#>  $ condition  : chr  \"approach\" \"approach\" \"approach\" \"approach\" ...\n#>  $ goal       : int  2 2 2 4 4 2 2 4 2 4 ...\n#>  $ performance: int  0 2 2 4 2 0 4 2 4 4 ...\n#>  $ trial      : int  1 2 3 4 5 6 7 8 9 10 ...\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(dat$subject)  # restituisce il numero di trial per soggetto\n#> \n#>  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 \n#> 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 \n#> 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 \n#> 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 \n#> 53 54 55 56 57 58 59 60 \n#> 10 10 10 10 10 10 10 10\n```\n:::\n\n\n::: {.callout-caution title=\"Standardizzazione: cosa implica\"}\n- Z-score su *goal* e *performance* allinea le scale ai *prior* (Normal(0,1)).\n- Interpretazione: $\\beta$ corrisponde allo spostamento medio per trial in unità di deviazione standard; $\\alpha$ corrisponde alla frazione di errore corretta per trial.\n- Non mescolare scaling per sottogruppi se poi si confrontano le condizioni: usare un'unica scala globale.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1) Ordina per soggetto e trial\ndat <- dat %>% arrange(subject, trial)\n\n# 2) Salva scale originali (per eventuale back-transform)\ngoal_mean <- mean(dat$goal, na.rm = TRUE); goal_sd <- sd(dat$goal, na.rm = TRUE)\nperf_mean <- mean(dat$performance, na.rm = TRUE); perf_sd <- sd(dat$performance, na.rm = TRUE)\n\n# 3) Standardizza\ndat <- dat %>%\n  mutate(\n    goal_z = (goal - goal_mean) / goal_sd,\n    perf_z = (performance - perf_mean) / perf_sd\n  )\n\n# 4) Lista per Stan (condition è opzionale qui: non usata nel baseline)\nstan_data <- list(\n  subject       = dat$subject,\n  trial         = dat$trial,\n  observed_goal = dat$goal_z,\n  performance   = dat$perf_z,\n  Nsubj         = dplyr::n_distinct(dat$subject),\n  Ntotal        = nrow(dat)\n)\n\nstr(stan_data)\n#> List of 6\n#>  $ subject      : int [1:600] 1 1 1 1 1 1 1 1 1 1 ...\n#>  $ trial        : int [1:600] 1 2 3 4 5 6 7 8 9 10 ...\n#>  $ observed_goal: num [1:600] -2 -2 -2 -1.07 -1.07 ...\n#>  $ performance  : num [1:600] -2.89 -1.99 -1.99 -1.1 -1.99 ...\n#>  $ Nsubj        : int 60\n#>  $ Ntotal       : int 600\n```\n:::\n\n\n### Definizione del modello Stan\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstancode <- \"\ndata {\n  int<lower=1> Ntotal;                 // es. 600\n  int<lower=1> Nsubj;                  // es. 60\n  array[Ntotal] int<lower=1> subject;  // indice soggetto (1..Nsubj)\n  array[Ntotal] int<lower=1> trial;    // 1..T per ciascun soggetto (ordinati)\n  vector[Ntotal] observed_goal;        // Z-score\n  vector[Ntotal] performance;          // Z-score\n}\n\nparameters {\n  vector[Nsubj] alpha;                 // guadagno per soggetto\n  vector[Nsubj] beta;                  // drift per soggetto\n  real<lower=1e-6> sigma;              // dev. std residua (comune)\n}\n\ntransformed parameters {\n  vector[Ntotal] ghat;                 // traiettoria predetta\n\n  for (i in 1:Ntotal) {\n    if (trial[i] == 1) {\n      // reset a inizio soggetto: primo stato = prima osservazione\n      ghat[i] = observed_goal[i];\n    } else {\n      int s = subject[i];\n      // ricorsione: usa predizione e performance del trial precedente (stesso soggetto se i dati sono ordinati)\n      ghat[i] = ghat[i - 1]\n                + alpha[s] * (performance[i - 1] - ghat[i - 1])\n                + beta[s];\n    }\n  }\n}\n\nmodel {\n  // Priors semplici coerenti con z-score\n  alpha ~ normal(0, 1);\n  beta  ~ normal(0, 1);\n  sigma ~ normal(0, 1);   // half-normal(1) per via del lower bound\n\n  // Likelihood\n  observed_goal ~ normal(ghat, sigma);\n}\n\ngenerated quantities {\n  vector[Ntotal] yrep;\n  vector[Ntotal] log_lik;\n\n  for (i in 1:Ntotal) {\n    yrep[i]   = normal_rng(ghat[i], sigma);\n    log_lik[i] = normal_lpdf(observed_goal[i] | ghat[i], sigma);\n  }\n}\n\"\n```\n:::\n\n\n**Intuizione**: a ogni trial, il soggetto confronta la propria prestazione con l'obiettivo corrente. Il parametro $\\alpha_i$ regola l'entità della correzione verso la prestazione, mentre $\\beta_i$ spinge l'obiettivo verso l'alto o verso il basso, indipendentemente dall'errore. Se $\\alpha_i$ è prossimo a 0, il soggetto è inerte; se è prossimo a 1, il soggetto è aggressivo; se $\\beta_i > 0$, il soggetto è ambizioso; se $\\beta_i < 0$, il soggetto è in fase di de-escalation.\n\nQuesto modello presuppone che i dati siano *ordinati per soggetto e per trial*, altrimenti la dinamica `i - 1` non corrisponde al *trial* precedente dello stesso soggetto. \n\nEsaminiamo in dettaglio il significato di `alpha[subject[i]]` e `beta[subject[i]]`. Nel modello Stan, ogni trial `i` è associato a un determinato soggetto. Tale informazione è contenuta nel vettore:\n\n```stan\narray[Ntotal] int<lower=1> subject;\n```\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstan_data$subject\n#>   [1]  1  1  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  2  2  3  3  3  3  3\n#>  [26]  3  3  3  3  3  4  4  4  4  4  4  4  4  4  4  5  5  5  5  5  5  5  5  5  5\n#>  [51]  6  6  6  6  6  6  6  6  6  6  7  7  7  7  7  7  7  7  7  7  8  8  8  8  8\n#>  [76]  8  8  8  8  8  9  9  9  9  9  9  9  9  9  9 10 10 10 10 10 10 10 10 10 10\n#> [101] 11 11 11 11 11 11 11 11 11 11 12 12 12 12 12 12 12 12 12 12 13 13 13 13 13\n#> [126] 13 13 13 13 13 14 14 14 14 14 14 14 14 14 14 15 15 15 15 15 15 15 15 15 15\n#> [151] 16 16 16 16 16 16 16 16 16 16 17 17 17 17 17 17 17 17 17 17 18 18 18 18 18\n#> [176] 18 18 18 18 18 19 19 19 19 19 19 19 19 19 19 20 20 20 20 20 20 20 20 20 20\n#> [201] 21 21 21 21 21 21 21 21 21 21 22 22 22 22 22 22 22 22 22 22 23 23 23 23 23\n#> [226] 23 23 23 23 23 24 24 24 24 24 24 24 24 24 24 25 25 25 25 25 25 25 25 25 25\n#> [251] 26 26 26 26 26 26 26 26 26 26 27 27 27 27 27 27 27 27 27 27 28 28 28 28 28\n#> [276] 28 28 28 28 28 29 29 29 29 29 29 29 29 29 29 30 30 30 30 30 30 30 30 30 30\n#> [301] 31 31 31 31 31 31 31 31 31 31 32 32 32 32 32 32 32 32 32 32 33 33 33 33 33\n#> [326] 33 33 33 33 33 34 34 34 34 34 34 34 34 34 34 35 35 35 35 35 35 35 35 35 35\n#> [351] 36 36 36 36 36 36 36 36 36 36 37 37 37 37 37 37 37 37 37 37 38 38 38 38 38\n#> [376] 38 38 38 38 38 39 39 39 39 39 39 39 39 39 39 40 40 40 40 40 40 40 40 40 40\n#> [401] 41 41 41 41 41 41 41 41 41 41 42 42 42 42 42 42 42 42 42 42 43 43 43 43 43\n#> [426] 43 43 43 43 43 44 44 44 44 44 44 44 44 44 44 45 45 45 45 45 45 45 45 45 45\n#> [451] 46 46 46 46 46 46 46 46 46 46 47 47 47 47 47 47 47 47 47 47 48 48 48 48 48\n#> [476] 48 48 48 48 48 49 49 49 49 49 49 49 49 49 49 50 50 50 50 50 50 50 50 50 50\n#> [501] 51 51 51 51 51 51 51 51 51 51 52 52 52 52 52 52 52 52 52 52 53 53 53 53 53\n#> [526] 53 53 53 53 53 54 54 54 54 54 54 54 54 54 54 55 55 55 55 55 55 55 55 55 55\n#> [551] 56 56 56 56 56 56 56 56 56 56 57 57 57 57 57 57 57 57 57 57 58 58 58 58 58\n#> [576] 58 58 58 58 58 59 59 59 59 59 59 59 59 59 59 60 60 60 60 60 60 60 60 60 60\n```\n:::\n\n\nOgni elemento `subject[i]` ci dice *a quale soggetto appartiene il trial `i`*, usando un numero intero da `1` a `Nsubj`. Quindi se `subject[137] == 24`, significa che il 137-esimo *trial* appartiene al soggetto 24.\n\nOra, se abbiamo un vettore di parametri specifici per ogni soggetto\n\n```stan\nvector[Nsubj] alpha;\nvector[Nsubj] beta;\n```\n\nallora:\n\n* `alpha[subject[i]]` significa: prendi il valore del parametro `alpha` associato al soggetto a cui appartiene il trial `i`;\n* lo stesso vale per `beta[subject[i]]`.\n\nPer esempio, supponiamo che\n\n```stan\nsubject = [1, 1, 1, 2, 2, 3, 3]\nalpha = [0.5, 0.8, 1.1]  // Tre soggetti: 1, 2, 3\n```\n\nallora:\n\n* `alpha[subject[4]] = alpha[2] = 0.8`, perché il 4° trial è del soggetto 2.\n* `beta[subject[6]] = beta[3] = ...`, perché il 6° trial è del soggetto 3.\n\nIn sintesi, la sintassi `alpha[subject[i]]` (e `beta[subject[i]]`) indica: “Nel trial `i`, usa il valore del parametro `alpha` (o `beta`) del soggetto indicato da `subject[i]`”. Questo metodo consente di associare in modo compatto ogni osservazione ai parametri della persona corrispondente.\n\n### Compilazione ed esecuzione del modello  \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstanmod <- cmdstan_model(\n  write_stan_file(stancode),\n  compile = TRUE\n)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit1 <- stanmod$sample(\n  data = stan_data,\n  iter_warmup = 1000,\n  iter_sampling = 5000,\n  chains = 4,\n  parallel_chains = 4,\n  refresh = 1000,\n  seed = 4790\n)\n```\n:::\n\n\n\n### Analisi dei risultati\n\nQuesto modello genera un insieme di campioni posteriori per i parametri $\\alpha$ e $\\beta$, uno per ciascun partecipante. \n\nI campioni vengono estratti in formato \"draws_matrix\" (per tabelle riassuntive):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstandraws <- fit1$draws(format = \"draws_matrix\")\n```\n:::\n\n\nStatistiche descrittive compatte per $\\alpha_i$, $\\beta_i$ e $\\sigma$: media, mediana e intervalli di credibilità al 95% (2.5% - 97.5%):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstandraws |> \n  subset_draws(variable = c(\"alpha\", \"beta\", \"sigma\")) |> \n  summarise_draws(\n    mean,\n    ~ quantile(.x, probs = c(0.025, 0.5, 0.975))\n  ) |> \n  print()\n#> # A tibble: 121 x 5\n#>    variable   mean   `2.5%` `50%` `97.5%`\n#>    <chr>     <dbl>    <dbl> <dbl>   <dbl>\n#>  1 alpha[1]  0.662  0.161   0.683   1.02 \n#>  2 alpha[2]  0.181 -0.265   0.178   0.595\n#>  3 alpha[3]  0.167 -0.251   0.186   0.507\n#>  4 alpha[4]  0.300 -0.515   0.303   0.950\n#>  5 alpha[5]  0.400  0.0561  0.399   0.744\n#>  6 alpha[6]  0.586 -0.00103 0.613   1.04 \n#>  7 alpha[7]  0.408  0.121   0.406   0.750\n#>  8 alpha[8]  0.119 -0.0767  0.109   0.343\n#>  9 alpha[9]  0.487  0.00886 0.487   0.927\n#> 10 alpha[10] 0.811  0.440   0.811   1.11 \n#> # i 111 more rows\n```\n:::\n\n\n**Checklist rapida**\n\n- R-hat ≤ 1.01 e ESS > 400? ✓\n- Traceplot senza “stallo”? ✓\n- Posterior di $\\sigma$ non schiacciata verso 0? ✓\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Se qualche Rhat > 1.01 o ESS basso, considerare run più lunghi o reparametrizzazioni\nfit1$summary(variables = c(\"alpha\", \"beta\", \"sigma\")) |>\n  dplyr::select(variable, rhat, ess_bulk, ess_tail) |>\n  dplyr::arrange(dplyr::desc(rhat)) |>\n  print(n = 10)\n#> # A tibble: 121 x 4\n#>    variable   rhat ess_bulk ess_tail\n#>    <chr>     <dbl>    <dbl>    <dbl>\n#>  1 alpha[34]  1.18     15.0     10.9\n#>  2 beta[47]   1.17     15.8     17.1\n#>  3 beta[34]   1.17     15.6     11.2\n#>  4 alpha[47]  1.16     16.8     17.2\n#>  5 beta[46]   1.16     17.0     18.5\n#>  6 beta[56]   1.14     19.0     26.8\n#>  7 alpha[56]  1.14     19.4     43.0\n#>  8 beta[40]   1.12     21.2     71.7\n#>  9 beta[32]   1.12     20.4     22.4\n#> 10 beta[26]   1.12     20.7     27.6\n#> # i 111 more rows\n```\n:::\n\n\nEstrazione \"tidy\" dei parametri a livello di persona con la funzione `tidybayes::spread_draws`. Questo produce le colonne: `.draw, subject, alpha, beta`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nposteriors_person = spread_draws(fit1, alpha[subject], beta[subject])\n```\n:::\n\n\nCalcolo della media e dell'intervallo di credibilità al 95% per ciascun soggetto: \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calcolo media e intervallo credibile al 95% per ciascun soggetto\nCIs_person <- posteriors_person %>%\n  group_by(subject) %>%\n  summarise(\n    across(c(alpha, beta), list(\n      lower = ~quantile(.x, 0.025),\n      mean  = ~mean(.x),\n      upper = ~quantile(.x, 0.975)\n    ), .names = \"{.col}_{.fn}\")\n  ) %>%\n  arrange(alpha_mean) %>%\n  mutate(alpha_order = row_number()) %>%\n  arrange(beta_mean) %>%\n  mutate(beta_order = row_number())\n```\n:::\n\n\nGrafico 1: CI al 95% per $\\alpha_i$, ordinati per `alpha_mean`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_person_alpha <- ggplot(data = CIs_person) +\n  geom_point(aes(y = alpha_order, x = alpha_mean)) +\n  geom_errorbar(\n    aes(y = alpha_order, xmin = alpha_lower, xmax = alpha_upper),\n    orientation = \"y\"\n  ) +\n  labs(x = expression(alpha), y = \"Subject\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_modeling_heterogeneity_files/figure-pdf/unnamed-chunk-15-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nGrafico 2: CI al 95% per $\\beta_i$, ordinati per `beta_mean`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_person_beta <- ggplot(data = CIs_person) +\n  geom_point(aes(y = beta_order, x = beta_mean)) +\n  geom_errorbar(\n    aes(y = beta_order, xmin = beta_lower, xmax = beta_upper),\n    orientation = \"y\"\n  ) +\n  labs(x = expression(beta), y = \"Subject\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_modeling_heterogeneity_files/figure-pdf/unnamed-chunk-17-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nGrafico 3: Dispersione bivariata (`alpha_mean` vs `beta_mean`) + croci di CI 95%.  Le barre verticali e orizzontali forniscono un'istantanea della (co)variabilità individuale:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_person_alphabeta <- ggplot(data = CIs_person) +\n  geom_point(aes(x = alpha_mean, y = beta_mean)) +\n  geom_errorbar(\n    aes(x = alpha_mean, ymin = beta_lower, ymax = beta_upper),\n    alpha = 0.25\n  ) +\n  geom_errorbar(\n    aes(y = beta_mean, xmin = alpha_lower, xmax = alpha_upper),\n    alpha = 0.25,\n    orientation = \"y\"\n  ) +\n  labs(x = expression(alpha), y = expression(beta))\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_modeling_heterogeneity_files/figure-pdf/unnamed-chunk-19-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nI grafici mostrano una marcata eterogeneità tra i partecipanti per quanto riguarda i parametri $\\alpha$ (tasso di apprendimento) e $\\beta$ (drift motivazionale), con intervalli di credibilità al 95% calcolati per ciascun $\\alpha_i$ e $\\beta_i$.\n\nPer quanto riguarda $\\alpha$, i partecipanti mostrano valori distribuiti lungo quasi tutto l’intervallo [0,1]. Alcuni soggetti hanno un valore di $\\alpha$ molto vicino a 0 (bassa sensibilità al feedback), mentre altri si avvicinano a 1 (forte aggiornamento in risposta all’errore). L’ampiezza degli intervalli di credibilità varia, ma nella maggior parte dei casi fornisce stime sufficientemente informative.\n\nPer quanto riguarda $\\beta$, i valori si distribuiscono attorno a 0, ma con marcate differenze individuali: alcuni soggetti mostrano un drift positivo (tendenza ad aumentare sistematicamente gli obiettivi), altri un drift negativo (tendenza a ridurli). Gli intervalli di credibilità confermano questa eterogeneità.\n\nIl punto chiave è che questa variabilità non può essere colta dal modello sample-level. Infatti, stimando un unico $\\alpha$ e un unico $\\beta$ comuni a tutti, restituisce una sorta di \"media\" del comportamento dei partecipanti. In pratica, un soggetto con $\\alpha \\approx 0$ e uno con $\\alpha \\approx 0.9$ verrebbero descritti dallo stesso parametro $\\alpha$, che potrebbe cadere a metà strada ma non rappresenterebbe bene né l'uno né l'altro. Allo stesso modo, le derive motivazionali individuali $\\beta$, ovvero positive, negative o vicine a zero, verrebbero tutte appiattite su un valore medio.\n\nI grafici dimostrano quindi l’utilità del modello a livello individuale: esso permette di mappare differenze sostanziali tra i soggetti, che nel modello a livello di campione vengono perse.\n\nIn sintesi, il modello *sample-level* offre una descrizione parsimoniosa, ma rischia di mascherare differenze psicologicamente rilevanti. Il modello *person-level* mostra che i partecipanti non solo differiscono per il grado di apprendimento dal feedback ($\\alpha$), ma anche per la direzione e l'intensità della deriva motivazionale ($\\beta$). Questa eterogeneità costituisce un'informazione preziosa per comprendere i profili comportamentali individuali, impossibile da cogliere con un modello che assume parametri omogenei per l'intero campione.\n\n## Modello gerarchico\n\nIl *modello a livello individuale* (*person-level*) stima parametri distinti $(\\alpha_i, \\beta_i)$ per ogni partecipante $i$. In questa formulazione, ogni individuo possiede il proprio tasso di apprendimento $\\alpha_i$ e la propria deriva motivazionale $\\beta_i$, il che consente di mappare la variabilità interindividuale nei processi di aggiornamento degli obiettivi e di identificare profili comportamentali distinti. Il parametro $\\sigma$, che cattura la variabilità residua (rumore decisionale), rimane comune a tutti i soggetti in questa versione di base, ma può essere esteso a varianze specifiche per ciascun soggetto quando necessario.\n\nSebbene la stima separata dei parametri per ogni partecipante rappresenti un passo avanti nel riconoscere le differenze individuali, questo approccio presenta un limite cruciale: le stime restano *concettualmente e statisticamente isolate*. Analizzare i dati \"soggetto per soggetto\" equivale a condurre una serie di analisi indipendenti, senza riutilizzare l'informazione presente nel resto del campione.\n\nQuesta frammentazione ha tre conseguenze sfavorevoli. Prima, riduce il potere statistico, perché ogni stima utilizza solo una frazione dei dati totali. Seconda, aumenta la variabilità delle stime, soprattutto quando il numero di osservazioni per soggetto è esiguo. Terza, complica la generalizzazione a livello di popolazione, rendendo meno solide le conclusioni aggregate.\n\nUn sintomo tipico è la presenza, per molti soggetti, di intervalli di credibilità molto ampi o di posteriori multi-modali su $\\alpha_i$ e/o su $\\beta_i$: segnali di informazione locale insufficiente e, talvolta, di non-identificabilità in specifiche regioni dello spazio dei parametri.\n\nÈ in questo contesto che i modelli gerarchici mostrano il loro valore, \"prestando\" l'informazione a livello di popolazione per regolarizzare le stime individuali ed evitare valori estremi non supportati dai dati. I modelli gerarchici bayesiani (o multilevel) concettualizzano i parametri individuali non come entità indipendenti, ma come realizzazioni di una distribuzione di gruppo sovraordinata. In pratica, si introduce un pooling parziale: i parametri specifici del soggetto vengono tirati verso la tendenza della popolazione nella misura in cui i loro dati sono poco informativi.\n\nFormalmente,\n$$\n\\alpha_i \\sim \\mathcal{N}(\\mu_\\alpha,\\ \\tau_\\alpha^2),\\qquad\n\\beta_i \\sim \\mathcal{N}(\\mu_\\beta,\\ \\tau_\\beta^2),\n$$\ndove $(\\mu_\\alpha,\\tau_\\alpha)$ e $(\\mu_\\beta,\\tau_\\beta)$ sono *iperparametri* che descrivono la popolazione. Questa struttura consente di bilanciare in modo ottimale le *idiosincrasie individuali* e le *regolarità aggregate* (Kruschke & Vanpaemel, 2015; Turner et al., 2013; Vincent, 2016). Il risultato è una *regolarizzazione*: le stime estreme vengono attenuate (*shrinkage*) verso la media della popolazione, riducendo il peso delle stime instabili o rumorose e producendo inferenze più *robuste* e *interpretabili*, specialmente con campioni piccoli o pochi trial per soggetto (Boehm et al., 2018; Rouder & Lu, 2005).\n\n> *Intuizione*: più i dati del soggetto $i$ sono informativi, meno la stima di $(\\alpha_i,\\beta_i)$ viene “tirata” verso $(\\mu_\\alpha,\\mu_\\beta)$; con dati scarsi/rumorosi, lo shrinkage aumenta e protegge dall’*overfitting*.\n\n### Definizione del modello Stan\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstancode <- \"\ndata {\n  int<lower=1> Ntotal;\n  int<lower=1> Nsubj;\n  array[Ntotal] int<lower=1> subject;\n  array[Ntotal] int<lower=1> trial;\n  vector[Ntotal] observed_goal;   // z-score\n  vector[Ntotal] performance;     // z-score\n}\n\nparameters {\n  // Iper-parametri di popolazione\n  real alpha_mean;\n  real<lower=0> alpha_sd;\n  real beta_mean;\n  real<lower=0> beta_sd;\n\n  // Non-centrato: fattori standard per i soggetti\n  vector[Nsubj] alpha_raw;\n  vector[Nsubj] beta_raw;\n\n  real<lower=1e-6> sigma;\n}\n\ntransformed parameters {\n  // Ricostruzione parametri individuali\n  vector[Nsubj] alpha_unconstrained = alpha_mean + alpha_sd * alpha_raw;\n  vector[Nsubj] beta  = beta_mean  + beta_sd  * beta_raw;\n\n  // Vincolo morbido su alpha per stabilità\n  vector[Nsubj] alpha = 0.95 * tanh(alpha_unconstrained);\n\n  vector[Ntotal] ghat;\n\n  for (i in 1:Ntotal) {\n    if (trial[i] == 1) {\n      ghat[i] = observed_goal[i];\n    } else {\n      int s = subject[i];\n      ghat[i] = ghat[i - 1]\n                + alpha[s] * (performance[i - 1] - ghat[i - 1])\n                + beta[s];\n    }\n  }\n}\n\nmodel {\n  // Iper-priori debolmente informativi (coerenti con z-score)\n  alpha_mean ~ normal(0, 0.5);\n  alpha_sd   ~ exponential(1);\n  beta_mean  ~ normal(0, 0.5);\n  beta_sd    ~ exponential(1);\n\n  alpha_raw  ~ normal(0, 1);\n  beta_raw   ~ normal(0, 1);\n\n  sigma ~ student_t(3, 0, 0.5);\n\n  // Likelihood\n  observed_goal ~ normal(ghat, sigma);\n}\n\ngenerated quantities {\n  vector[Ntotal] yrep;\n  vector[Ntotal] log_lik;\n  for (i in 1:Ntotal) {\n    yrep[i]    = normal_rng(ghat[i], sigma);\n    log_lik[i] = normal_lpdf(observed_goal[i] | ghat[i], sigma);\n  }\n}\n\"\n```\n:::\n\n\n::: {.callout-note collapse=true title=\"Parametrizzazione tramite tanh per il tasso di apprendimento\"}\nLa scelta di modellare il tasso di apprendimento $\\alpha$ mediante una trasformazione `tanh` (tangente iperbolica) è motivata da considerazioni sia teoriche che pratiche.\n\nDal punto di vista del modello dinamico, la stabilità del processo di aggiornamento ricorsivo richiede che il parametro $\\alpha$ si trovi nell'intervallo (0, 2). Tuttavia, quando si lavora con dati standardizzati, una pratica comune per migliorare la convergenza degli algoritmi, è preferibile contenere $\\alpha$ in un intervallo più ristretto, tipicamente $(-1, 1),$ al fine di evitare aggiornamenti eccessivi che potrebbero destabilizzare le stime.\n\nLa funzione `tanh` fornisce una soluzione elegante a questo requisito, mappando in modo continuo e differenziabile qualsiasi valore reale (ad esempio, il valore di un parametro latente non vincolato) nell'intervallo (-1, 1). L'applicazione di un fattore moltiplicativo di 0.95 applicato all'output di `tanh` (cioè $\\alpha = 0.95 \\cdot \\text{tanh}(\\cdot)$) introduce un ulteriore margine di sicurezza numerica, allontanandosi leggermente dai limiti estremi dell'intervallo. Questa contrazione marginale si è rivelata efficace nel ridurre il verificarsi di divergenze durante il campionamento con la tecnica di Hamilton Monte Carlo (HMC), migliorando la stabilità e l'efficienza computazionale dell'inferenza.\n\nQuesta parametrizzazione garantisce quindi che i valori di $\\alpha$ siano sempre ben definiti e gestibili dal punto di vista numerico, facilitando un processo inferenziale robusto ed efficiente. \n:::\n\n### Differenza chiave rispetto al modello precedente\n\nNel *Person-Level Model* i parametri individuali sono stimati in modo indipendente, mentre qui valgono relazioni del tipo:\n\n$$\n\\alpha_s \\sim \\mathcal{N}(\\alpha_{\\text{mean}}, \\alpha_{\\text{sd}}), \\quad\n\\beta_s \\sim \\mathcal{N}(\\beta_{\\text{mean}}, \\beta_{\\text{sd}}).\n$$\n\nQuesta struttura gerarchica introduce un vincolo statistico che collega i soggetti, generando un duplice vantaggio metodologico. Da un lato, essa preserva le differenze individuali, evitando l'assunzione irrealistica di parametri identici per tutti i partecipanti. Dall'altro lato, sfrutta sistematicamente le somiglianze tra i soggetti per ottenere stime più robuste a livello individuale e inferenze più precise sulla popolazione di riferimento.\n\n### Compilazione ed esecuzione\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstanmod <- cmdstan_model(\n  write_stan_file(stancode),\n  compile = TRUE\n)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit2 <- stanmod$sample(\n  data = stan_data,\n  iter_warmup = 1000,\n  iter_sampling = 4000,\n  chains = 4, parallel_chains = 4,\n  seed = 4790,\n  refresh = 500,\n  adapt_delta = 0.995,  # riduce divergenze\n  max_treedepth = 15\n)\n```\n:::\n\n\n### Analisi dei risultati\n\nEseguiamo l'analisi dei risultati seguendo lo schema usato sopra.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Estrazione dei campioni posteriori come matrice \nstandraws <- fit2$draws(format = \"draws_matrix\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Statistiche descrittive aggregate\nstandraws |> \n  subset_draws(variable = c(\"alpha\", \"beta\", \"sigma\", \"alpha_mean\", \"beta_mean\", \"alpha_sd\", \"beta_sd\")) |> \n  summarise_draws(\n    mean,\n    ~ quantile(.x, probs = c(0.025, 0.5, 0.975))\n  )\n#> # A tibble: 125 x 5\n#>    variable   mean `2.5%` `50%` `97.5%`\n#>    <chr>     <dbl>  <dbl> <dbl>   <dbl>\n#>  1 alpha[1]  0.576 0.292  0.587   0.795\n#>  2 alpha[2]  0.385 0.0594 0.393   0.664\n#>  3 alpha[3]  0.320 0.0187 0.328   0.582\n#>  4 alpha[4]  0.490 0.145  0.505   0.749\n#>  5 alpha[5]  0.367 0.0957 0.371   0.621\n#>  6 alpha[6]  0.552 0.257  0.563   0.775\n#>  7 alpha[7]  0.467 0.215  0.471   0.704\n#>  8 alpha[8]  0.221 0.0149 0.216   0.459\n#>  9 alpha[9]  0.510 0.209  0.520   0.754\n#> 10 alpha[10] 0.637 0.425  0.644   0.812\n#> # i 115 more rows\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Estrai le draw per i parametri individuali (alpha e beta per ciascun soggetto)\nposteriors_person <- spread_draws(fit2, alpha[subject], beta[subject])\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calcolo degli intervalli credibili per ciascun soggetto\nCIs_person <- posteriors_person %>%\n  group_by(subject) %>%\n  summarise(\n    across(c(alpha, beta), list(\n      lower = ~quantile(.x, 0.025),\n      mean  = ~mean(.x),\n      upper = ~quantile(.x, 0.975)\n    ), .names = \"{.col}_{.fn}\")\n  ) %>%\n  arrange(alpha_mean) %>%\n  mutate(alpha_order = row_number()) %>%\n  arrange(beta_mean) %>%\n  mutate(beta_order = row_number())\n```\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Grafico: intervalli credibili per alpha\nplot_person_alpha <- ggplot(CIs_person) +\n  geom_point(aes(y = alpha_order, x = alpha_mean)) +\n  geom_errorbar(\n    aes(y = alpha_order, xmin = alpha_lower, xmax = alpha_upper),\n    orientation = \"y\"\n  ) +\n  labs(x = expression(alpha), y = \"Soggetto\")\n\n# Grafico: intervalli credibili per beta\nplot_person_beta <- ggplot(CIs_person) +\n  geom_point(aes(y = beta_order, x = beta_mean)) +\n  geom_errorbar(\n    aes(y = beta_order, xmin = beta_lower, xmax = beta_upper),\n    orientation = \"y\"\n  ) +\n  labs(x = expression(beta), y = \"Soggetto\")\n\n# Grafico: relazione tra alpha e beta per ciascun soggetto\nplot_person_alphabeta <- ggplot(CIs_person) +\n  geom_point(aes(x = alpha_mean, y = beta_mean)) +\n  geom_errorbar(\n    aes(x = alpha_mean, ymin = beta_lower, ymax = beta_upper),\n    alpha = 0.25\n  ) +\n  geom_errorbar(\n    aes(y = beta_mean, xmin = alpha_lower, xmax = alpha_upper),\n    alpha = 0.25,\n    orientation = \"y\"\n  ) +\n  labs(x = expression(alpha), y = expression(beta))\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_modeling_heterogeneity_files/figure-pdf/unnamed-chunk-28-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_modeling_heterogeneity_files/figure-pdf/unnamed-chunk-29-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_modeling_heterogeneity_files/figure-pdf/unnamed-chunk-30-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nInfine, calcoliamo le stime a posteriori degli iper-parametri:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Riassunto per alpha_mean e beta_mean con intervallo al 95%\nstandraws |>\n  subset_draws(variable = c(\"alpha_mean\", \"beta_mean\")) |>\n  summarise_draws(\n    mean,\n    ~quantile(.x, probs = c(0.025, 0.975))\n  )\n#> # A tibble: 2 x 4\n#>   variable    mean `2.5%` `97.5%`\n#>   <chr>      <dbl>  <dbl>   <dbl>\n#> 1 alpha_mean 0.621 0.521    0.732\n#> 2 beta_mean  0.114 0.0495   0.176\n```\n:::\n\n\n#### Interpretazione\n\nIl modello gerarchico bayesiano fornisce inferenze a *due livelli*:\n\n* **Livello individuale**: parametri $\\alpha_s$ e $\\beta_s$ per ciascun partecipante, con i relativi intervalli di credibilità.\n* **Livello di popolazione**: distribuzioni a priori/posteriori degli iperparametri $\\alpha_{\\text{mean}}, \\alpha_{\\text{sd}}, \\beta_{\\text{mean}}, \\beta_{\\text{sd}}$ e del parametro residuo $\\sigma$.\n\nI grafici relativi a $\\alpha$ e $\\beta$ evidenziano chiaramente l'eterogeneità interindividuale, mentre gli iperparametri descrivono la tendenza generale.\n\nRispetto a un modello puramente individuale, gli intervalli di credibilità delle stime soggettive risultano meno dispersi e più regolari. Questo fenomeno è noto come \"shrinkage\": le stime dei singoli soggetti sono \"attirate\" verso la media della popolazione, riducendo l'impatto dei dati rumorosi o scarsi.\n\nNel grafico bivariato, lo shrinkage si traduce in una distribuzione più compatta dei punti attorno al centro della distribuzione collettiva. L'effetto principale è una maggiore robustezza delle inferenze: le stime estreme vengono mitigate, la variabilità non plausibile è penalizzata e la capacità di generalizzare a nuovi dati risulta rafforzata (Boehm et al., 2018).\n\n## Differenze tra i gruppi\n\nIn questo terzo modello, estendiamo la struttura gerarchica introducendo le condizioni sperimentali (approach vs avoidance). L'idea è che i parametri individuali $\\alpha_s$ e $\\beta_s$ non siano estratti da una distribuzione comune, ma da distribuzioni diverse a seconda del gruppo di appartenenza del soggetto.\n\nIn questo modo, per ciascuna condizione, è possibile stimare una media e una deviazione standard a livello di popolazione: $\\alpha_{\\text{mean},c}$ e $\\alpha_{\\text{sd},c}$, $\\beta_{\\text{mean},c}$ e $\\beta_{\\text{sd},c}$, con $c \\in \\{1,2\\}$.\n\n### Preparazione dei dati\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1) Ordina per soggetto e trial\ndat <- dat %>% arrange(subject, trial)\n\n# 2) Codifica la condizione come intero (1 = approach, 2 = avoidance)\ndat <- dat %>%\n  mutate(cond_id = as.integer(factor(condition)))\n\n# Verifica che ogni soggetto appartenga a una sola condizione\nchk <- dat %>% distinct(subject, cond_id) %>% count(subject) %>% filter(n > 1)\nstopifnot(nrow(chk) == 0)  # se fallisce, il design non è between-subject\n\n# 3) Standardizza goal e performance su tutto il dataset\ngoal_mean <- mean(dat$goal, na.rm = TRUE); goal_sd <- sd(dat$goal, na.rm = TRUE)\nperf_mean <- mean(dat$performance, na.rm = TRUE); perf_sd <- sd(dat$performance, na.rm = TRUE)\n\ndat <- dat %>%\n  mutate(\n    goal_z = (goal - goal_mean) / goal_sd,\n    perf_z = (performance - perf_mean) / perf_sd\n  )\n\n# 4) Vettore che assegna a ciascun soggetto la sua condizione\nsubjects <- sort(unique(dat$subject))\nsubj_cond <- dat %>%\n  group_by(subject) %>%\n  summarise(cond = first(cond_id), .groups = \"drop\") %>%\n  arrange(subject) %>%\n  pull(cond)\n\n# 5) Lista per Stan\nstan_data <- list(\n  Ntotal        = nrow(dat),\n  Nsubj         = length(subjects),\n  C             = length(unique(dat$cond_id)),   # numero condizioni\n  subject       = dat$subject,\n  trial         = dat$trial,\n  observed_goal = dat$goal_z,\n  performance   = dat$perf_z,\n  subj_cond     = subj_cond\n)\n\nstr(stan_data)\n#> List of 8\n#>  $ Ntotal       : int 600\n#>  $ Nsubj        : int 60\n#>  $ C            : int 2\n#>  $ subject      : int [1:600] 1 1 1 1 1 1 1 1 1 1 ...\n#>  $ trial        : int [1:600] 1 2 3 4 5 6 7 8 9 10 ...\n#>  $ observed_goal: num [1:600] -2 -2 -2 -1.07 -1.07 ...\n#>  $ performance  : num [1:600] -2.89 -1.99 -1.99 -1.1 -1.99 ...\n#>  $ subj_cond    : int [1:60] 1 2 2 1 2 1 2 1 2 1 ...\n```\n:::\n\n\n### Definizione del modello Stan\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstancode <- \"\n// Modello gerarchico con iper-parametri specifici per condizione\ndata {\n  int<lower=1> Ntotal;\n  int<lower=1> Nsubj;\n  int<lower=1> C;                            // numero condizioni\n  array[Ntotal] int<lower=1> subject;        // 1..Nsubj\n  array[Ntotal] int<lower=1> trial;          // 1..T all'interno di soggetto\n  vector[Ntotal] observed_goal;              // z-score\n  vector[Ntotal] performance;                // z-score\n  array[Nsubj] int<lower=1, upper=C> subj_cond; // condizione per soggetto\n}\n\nparameters {\n  // Iper-parametri per condizione\n  vector[C] alpha_mean;\n  vector<lower=0>[C] alpha_sd;\n  vector[C] beta_mean;\n  vector<lower=0>[C] beta_sd;\n\n  // Non-centrato: fattori standard per soggetti\n  vector[Nsubj] alpha_raw;\n  vector[Nsubj] beta_raw;\n\n  real<lower=1e-6> sigma;\n}\n\ntransformed parameters {\n  vector[Nsubj] alpha_uncon;\n  vector[Nsubj] beta;\n  vector[Nsubj] alpha;           \n  vector[Ntotal] ghat;\n\n  // Ricostruzione dei parametri individuali in base alla condizione\n  for (s in 1:Nsubj) {\n    int c = subj_cond[s];\n    alpha_uncon[s] = alpha_mean[c] + alpha_sd[c] * alpha_raw[s];\n    beta[s]        = beta_mean[c]  + beta_sd[c]  * beta_raw[s];\n    alpha[s]       = 0.95 * tanh(alpha_uncon[s]); // vincolo di stabilità\n  }\n\n  // Dinamica\n  for (i in 1:Ntotal) {\n    if (trial[i] == 1) {\n      ghat[i] = observed_goal[i];\n    } else {\n      int s = subject[i];\n      ghat[i] = ghat[i - 1]\n                + alpha[s] * (performance[i - 1] - ghat[i - 1])\n                + beta[s];\n    }\n  }\n}\n\nmodel {\n  // Iper-priori debolmente informativi\n  alpha_mean ~ normal(0, 0.5);\n  alpha_sd   ~ exponential(1);\n  beta_mean  ~ normal(0, 0.5);\n  beta_sd    ~ exponential(1);\n\n  alpha_raw  ~ normal(0, 1);\n  beta_raw   ~ normal(0, 1);\n\n  sigma ~ student_t(3, 0, 0.5);\n\n  // Likelihood\n  observed_goal ~ normal(ghat, sigma);\n}\n\ngenerated quantities {\n  vector[Ntotal] yrep;\n  vector[Ntotal] log_lik;\n  for (i in 1:Ntotal) {\n    yrep[i]    = normal_rng(ghat[i], sigma);\n    log_lik[i] = normal_lpdf(observed_goal[i] | ghat[i], sigma);\n  }\n}\n\"\n```\n:::\n\n\n### Come funziona la distinzione tra i gruppi\n\n**Assegnazione della condizione.** Nel blocco `data`, il vettore `subj_cond` assegna a ciascun soggetto il numero della condizione (1 = *approach*, 2 = *avoidance*).\n\n**Parametri di gruppo.** Gli iperparametri `alpha_mean[c]`, `alpha_sd[c]`, `beta_mean[c]`, `beta_sd[c]` sono specifici per condizione. Ad esempio, `alpha_mean[1]` è la media di $\\alpha$ per il gruppo *approach*, mentre `alpha_mean[2]` è la media di $\\alpha$ per il gruppo *avoidance*.\n\n**Parametri individuali.** In `transformed parameters`, i parametri dei singoli soggetti vengono generati in base alla loro condizione di appartenenza. Di conseguenza, i soggetti *approach* e quelli *avoidance* condividono rispettivamente due diverse distribuzioni di partenza.\n\nIn sintesi, il modello permette di stimare non solo le differenze tra individui, ma anche *le differenze sistematiche tra condizioni sperimentali*.\n\n### Compilazione ed esecuzione\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstanmod <- cmdstan_model(write_stan_file(stancode), compile = TRUE)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit3 <- stanmod$sample(\n  data = stan_data,\n  iter_warmup = 1000,\n  iter_sampling = 5000,\n  chains = 4, parallel_chains = 4,\n  seed = 123,\n  adapt_delta = 0.999,   # ↑ riduce divergenze\n  max_treedepth = 15\n)\n```\n:::\n\n\n### Risultati\n\n#### Ispezione rapida delle variabili (opzionale)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndraws_df <- as_draws_df(fit3$draws())   # oppure: fit3$draws(format = \"df\")\nnames(draws_df)[grepl(\"alpha_mean|beta_mean|alpha\\\\[|beta\\\\[\", names(draws_df))]\n#>   [1] \"alpha_mean[1]\" \"alpha_mean[2]\" \"beta_mean[1]\"  \"beta_mean[2]\" \n#>   [5] \"beta[1]\"       \"beta[2]\"       \"beta[3]\"       \"beta[4]\"      \n#>   [9] \"beta[5]\"       \"beta[6]\"       \"beta[7]\"       \"beta[8]\"      \n#>  [13] \"beta[9]\"       \"beta[10]\"      \"beta[11]\"      \"beta[12]\"     \n#>  [17] \"beta[13]\"      \"beta[14]\"      \"beta[15]\"      \"beta[16]\"     \n#>  [21] \"beta[17]\"      \"beta[18]\"      \"beta[19]\"      \"beta[20]\"     \n#>  [25] \"beta[21]\"      \"beta[22]\"      \"beta[23]\"      \"beta[24]\"     \n#>  [29] \"beta[25]\"      \"beta[26]\"      \"beta[27]\"      \"beta[28]\"     \n#>  [33] \"beta[29]\"      \"beta[30]\"      \"beta[31]\"      \"beta[32]\"     \n#>  [37] \"beta[33]\"      \"beta[34]\"      \"beta[35]\"      \"beta[36]\"     \n#>  [41] \"beta[37]\"      \"beta[38]\"      \"beta[39]\"      \"beta[40]\"     \n#>  [45] \"beta[41]\"      \"beta[42]\"      \"beta[43]\"      \"beta[44]\"     \n#>  [49] \"beta[45]\"      \"beta[46]\"      \"beta[47]\"      \"beta[48]\"     \n#>  [53] \"beta[49]\"      \"beta[50]\"      \"beta[51]\"      \"beta[52]\"     \n#>  [57] \"beta[53]\"      \"beta[54]\"      \"beta[55]\"      \"beta[56]\"     \n#>  [61] \"beta[57]\"      \"beta[58]\"      \"beta[59]\"      \"beta[60]\"     \n#>  [65] \"alpha[1]\"      \"alpha[2]\"      \"alpha[3]\"      \"alpha[4]\"     \n#>  [69] \"alpha[5]\"      \"alpha[6]\"      \"alpha[7]\"      \"alpha[8]\"     \n#>  [73] \"alpha[9]\"      \"alpha[10]\"     \"alpha[11]\"     \"alpha[12]\"    \n#>  [77] \"alpha[13]\"     \"alpha[14]\"     \"alpha[15]\"     \"alpha[16]\"    \n#>  [81] \"alpha[17]\"     \"alpha[18]\"     \"alpha[19]\"     \"alpha[20]\"    \n#>  [85] \"alpha[21]\"     \"alpha[22]\"     \"alpha[23]\"     \"alpha[24]\"    \n#>  [89] \"alpha[25]\"     \"alpha[26]\"     \"alpha[27]\"     \"alpha[28]\"    \n#>  [93] \"alpha[29]\"     \"alpha[30]\"     \"alpha[31]\"     \"alpha[32]\"    \n#>  [97] \"alpha[33]\"     \"alpha[34]\"     \"alpha[35]\"     \"alpha[36]\"    \n#> [101] \"alpha[37]\"     \"alpha[38]\"     \"alpha[39]\"     \"alpha[40]\"    \n#> [105] \"alpha[41]\"     \"alpha[42]\"     \"alpha[43]\"     \"alpha[44]\"    \n#> [109] \"alpha[45]\"     \"alpha[46]\"     \"alpha[47]\"     \"alpha[48]\"    \n#> [113] \"alpha[49]\"     \"alpha[50]\"     \"alpha[51]\"     \"alpha[52]\"    \n#> [117] \"alpha[53]\"     \"alpha[54]\"     \"alpha[55]\"     \"alpha[56]\"    \n#> [121] \"alpha[57]\"     \"alpha[58]\"     \"alpha[59]\"     \"alpha[60]\"\n```\n:::\n\n\n#### Differenze tra condizioni sugli iper-parametri\n\nL'obiettivo è verificare se i parametri di popolazione *$\\alpha$* (tasso di aggiornamento) e *$\\beta$* (drift/tendenza) differiscono tra le due condizioni sperimentali (*approach* vs *avoidance*). Per rispondere a questa domanda procediamo in quattro passaggi: recuperiamo le etichette delle condizioni dal dataset; calcoliamo il contrasto tra condizioni ($\\Delta =$ condizione$_2$ − condizione$_1$); stimiamo la media della differenza, il 95% CrI e la probabilità a posteriori che la differenza sia negativa; visualizziamo i risultati per facilitarne l'interpretazione.\n\n##### Step 1. Etichette di condizione\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncond_labels <- dat %>%\n  distinct(cond_id, condition) %>%\n  arrange(cond_id) %>%\n  pull(condition)\n\ncond_labels\n#> [1] \"approach\"  \"avoidance\"\n# Esempio: c(\"approach\", \"avoidance\")\n```\n:::\n\n\n##### Step 2. Contrasto su α (media per condizione)\n\nCalcoliamo $\\Delta_\\alpha = \\alpha_{\\text{avoidance}} - \\alpha_{\\text{approach}}$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndelta_alpha <- fit3 |>\n  spread_draws(alpha_mean[cond]) |>\n  mutate(cond = factor(cond, levels = 1:2, labels = cond_labels)) |>\n  pivot_wider(names_from = cond, values_from = alpha_mean, names_prefix = \"alpha_mean_\") |>\n  mutate(delta_alpha_mean = alpha_mean_avoidance - alpha_mean_approach)\n\ndelta_alpha |> \n  summarise(\n    mean   = mean(delta_alpha_mean),\n    low95  = quantile(delta_alpha_mean, 0.025),\n    upp95  = quantile(delta_alpha_mean, 0.975),\n    p_lt0  = mean(delta_alpha_mean < 0)\n  )\n#> # A tibble: 1 x 4\n#>     mean  low95   upp95 p_lt0\n#>    <dbl>  <dbl>   <dbl> <dbl>\n#> 1 -0.247 -0.481 -0.0349 0.989\n```\n:::\n\n\n##### Step 3. Contrasto su β (media per condizione)\n\nIn modo analogo, calcoliamo $\\Delta_\\beta = \\beta_{\\text{avoidance}} - \\beta_{\\text{approach}}$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndelta_beta <- fit3 |>\n  spread_draws(beta_mean[cond]) |>\n  mutate(cond = factor(cond, levels = 1:2, labels = cond_labels)) |>\n  pivot_wider(names_from = cond, values_from = beta_mean, names_prefix = \"beta_mean_\") |>\n  mutate(delta_beta_mean = beta_mean_avoidance - beta_mean_approach)\n\ndelta_beta |> \n  summarise(\n    mean   = mean(delta_beta_mean),\n    low95  = quantile(delta_beta_mean, 0.025),\n    upp95  = quantile(delta_beta_mean, 0.975),\n    p_lt0  = mean(delta_beta_mean < 0)\n  )\n#> # A tibble: 1 x 4\n#>     mean  low95   upp95 p_lt0\n#>    <dbl>  <dbl>   <dbl> <dbl>\n#> 1 -0.126 -0.251 0.00152 0.974\n```\n:::\n\n\n##### Step 4. Visualizzazione delle posterior\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npost_alpha <- fit3 |>\n  spread_draws(alpha_mean[cond]) |>\n  mutate(parameter = \"alpha_mean\",\n         condition = factor(cond, levels = 1:2, labels = cond_labels)) |>\n  rename(value = alpha_mean)\n\npost_beta <- fit3 |>\n  spread_draws(beta_mean[cond]) |>\n  mutate(parameter = \"beta_mean\",\n         condition = factor(cond, levels = 1:2, labels = cond_labels)) |>\n  rename(value = beta_mean)\n\nposterior_both <- bind_rows(post_alpha, post_beta)\n\nggplot(posterior_both, aes(x = value, fill = condition)) +\n  geom_density(alpha = 0.6) +\n  facet_wrap(~parameter, scales = \"free\") +\n  labs(x = \"Posterior mean\", y = \"Density\", fill = \"Condition\") +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![](03_modeling_heterogeneity_files/figure-pdf/unnamed-chunk-40-1.png){fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\n##### Risultati numerici\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_delta_alpha_neg <- mean(draws_df$`alpha_mean[2]` - draws_df$`alpha_mean[1]` < 0)\nprob_delta_beta_neg  <- mean(draws_df$`beta_mean[2]` - draws_df$`beta_mean[1]` < 0)\n\ncat(\"P(delta_alpha_mean < 0):\", round(prob_delta_alpha_neg, 3), \"\\n\")\n#> P(delta_alpha_mean < 0): 0.989\ncat(\"P(delta_beta_mean < 0):\", round(prob_delta_beta_neg, 3), \"\\n\")\n#> P(delta_beta_mean < 0): 0.974\n\nsummary_df <- tibble(\n  parameter = c(\"alpha_mean\", \"beta_mean\"),\n  delta_mean = c(\n    mean(draws_df$`alpha_mean[2]` - draws_df$`alpha_mean[1]`),\n    mean(draws_df$`beta_mean[2]` - draws_df$`beta_mean[1]`)\n  ),\n  lower_95 = c(\n    quantile(draws_df$`alpha_mean[2]` - draws_df$`alpha_mean[1]`, 0.025),\n    quantile(draws_df$`beta_mean[2]` - draws_df$`beta_mean[1]`, 0.025)\n  ),\n  upper_95 = c(\n    quantile(draws_df$`alpha_mean[2]` - draws_df$`alpha_mean[1]`, 0.975),\n    quantile(draws_df$`beta_mean[2]` - draws_df$`beta_mean[1]`, 0.975)\n  ),\n  prob_below_0 = c(prob_delta_alpha_neg, prob_delta_beta_neg)\n)\n\nsummary_df\n#> # A tibble: 2 x 5\n#>   parameter  delta_mean lower_95 upper_95 prob_below_0\n#>   <chr>           <dbl>    <dbl>    <dbl>        <dbl>\n#> 1 alpha_mean     -0.247   -0.481 -0.0349         0.989\n#> 2 beta_mean      -0.126   -0.251  0.00152        0.974\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary_df |> \n  ggplot(aes(x = parameter, y = delta_mean)) +\n  geom_bar(stat = \"identity\", fill = \"steelblue\", width = 0.5) +\n  geom_errorbar(aes(ymin = lower_95, ymax = upper_95), width = 0.2) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  labs(\n    x = \"Parametro\",\n    y = \"Differenza media\\n(cond2 - cond1)\"\n  )\n```\n\n::: {.cell-output-display}\n![](03_modeling_heterogeneity_files/figure-pdf/unnamed-chunk-42-1.png){fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\n##### Interpretazione dei risultati\n\nPer quanto riguarda **$\\Delta_\\alpha$ (avoidance − approach)**, la media è −0.247 con un intervallo di credibilità al 95% pari a [−0.481, −0.035] e $P(\\Delta<0) = 0.989$. Ciò indica un'evidenza forte che l'aggiornamento ($\\alpha$) è più basso nella condizione *avoidance*. L'effetto è moderato (circa 0.25 deviazioni standard).\n\nPer quanto riguarda **$\\Delta_\\beta$ (avoidance − approach)**, la media è −0.126 con un intervallo di credibilità al 95% pari a [−0.251, 0.002] e $P(\\Delta<0) = 0.974$. La probabilità che $\\beta$ sia più basso nella condizione *avoidance* è elevata, ma l'intervallo credibile include lo zero. L'evidenza è quindi suggestiva ma non conclusiva.\n\n##### Significato sostantivo\n\nNella condizione di *avoidance* si osserva un rallentamento significativo nell'aggiornamento delle credenze, come evidenziato dal parametro $\\alpha$ più basso. Parallelamente, emerge una tendenza alla riduzione del parametro $\\beta$, sebbene con un grado di incertezza che ne impedisce una conclusione definitiva.\n\nQuesti risultati suggeriscono che la manipolazione sperimentale influisce prevalentemente sulla dinamica di apprendimento, mentre il suo eventuale effetto sulla componente di drift richiederà verifiche più approfondite attraverso raccolte dati più estese o modelli dotati di maggiore sensibilità discriminativa.\n\n## Confronto tra modelli\n\nPer confrontare la capacità predittiva dei modelli è stata impiegata la cross-validazione leave-one-out (LOO-CV), che fornisce una stima della densità predittiva attesa (ELPD). Valori più elevati di ELPD indicano una superiore accuratezza predittiva fuori campione.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlog_lik1 <- fit1$draws(variables = \"log_lik\", format = \"matrix\")\nlog_lik2 <- fit2$draws(variables = \"log_lik\", format = \"matrix\")\nlog_lik3 <- fit3$draws(variables = \"log_lik\", format = \"matrix\")\n\n# Calcola LOO per ciascun modello\nloo1 <- loo(log_lik1)\nloo2 <- loo(log_lik2)\nloo3 <- loo(log_lik3)\n\n# Confronto tra i modelli\nmodel_comparison <- loo_compare(loo1, loo2, loo3)\nprint(model_comparison)\n#>   model elpd_diff se_diff p_worse diag_diff       diag_elpd\n#>  model3       0.0     0.0      NA            5 k_psis > 0.7\n#>  model2      -4.7     3.9    0.89            5 k_psis > 0.7\n#>  model1     -23.2     7.6    1.00           33 k_psis > 0.7\n```\n:::\n\n\nIl modello gerarchico con condizione (Modello 3) presenta le migliori prestazioni predittive secondo la metrica ELPD. Tuttavia, il confronto diretto con il modello gerarchico senza condizione (Modello 2) rivela una differenza di ELPD pari a -4.7 (SE = 3.9), un divario di entità contenuta rispetto all'incertezza campionaria. Sebbene si osservi una tendenza a favore del Modello 3, non è possibile stabilire con sufficiente sicurezza che l'inclusione della condizione produca un reale miglioramento delle prestazioni predittive.\n\nBen diverso è il caso del confronto con il modello non gerarchico (Modello 1), che mostra una perdita significativa di capacità predittiva con un ELPD inferiore di 23.3 unità (SE = 7.6) rispetto al Modello 3. In questo caso, la magnitudine della differenza, nettamente superiore all'errore standard, consente di concludere che il Modello 1 genera prestazioni predittive significativamente inferiori.\n\n### Cosa impariamo\n\nIl confronto tra modelli ha messo in luce l'importanza cruciale della struttura gerarchica. I modelli gerarchici (Modelli 2 e 3) dimostrano una capacità descrittiva nettamente superiore rispetto al modello non gerarchico, confermando il valore epistemologico della condivisione delle informazioni tra i soggetti per ottenere stime più robuste e previsioni più accurate.\n\nPer quanto riguarda l'effetto della condizione sperimentale, il modello che lo include (Modello 3) mostra una tendenza verso prestazioni migliori, sebbene il vantaggio predittivo rispetto al modello gerarchico semplice (Modello 2) non raggiunga una solidità statistica convincente. Questa conclusione è coerente con le stime parametriche, in cui la differenza tra le condizioni appare più marcata per il parametro $\\alpha$ rispetto al parametro $\\beta$.\n\nLa scelta del modello dipende quindi dagli obiettivi della ricerca. Se si privilegia la parsimonia, il Modello 2 è già adeguato. Se invece l'obiettivo primario è testare esplicitamente l'effetto della condizione, il Modello 3 risulta preferibile, nonostante il reale guadagno predittivo rimanga incerto.\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nQuesto capitolo ha tracciato un percorso metodologico che, partendo dal livello individuale, conduce a una rappresentazione della collettività, incrementando progressivamente la complessità del modello in modo controllato e giustificato.\n\nL'approccio *person-level*, stimando parametri specifici per ciascun soggetto $(\\alpha_i, \\beta_i)$, ha rivelato una marcata eterogeneità individuale sia nella velocità di aggiornamento che nella deriva decisionale. Tuttavia, questa flessibilità analitica presenta un costo metodologico sostanziale: l'assenza di condivisione delle informazioni tra i soggetti rende le stime particolarmente fragili quando il numero di osservazioni per partecipante è limitato.\n\nIl modello *gerarchico* supera questa limitazione trattando i parametri individuali come realizzazioni di distribuzioni di popolazione. Questa architettura produce inferenze più stabili e generalizzabili, grazie al meccanismo dello \"shrinkage\", che attenua le stime estreme non sufficientemente supportate dai dati. Il risultato è un duplice vantaggio: stime individuali più affidabili e un quadro generale della popolazione.\n\nL'introduzione di *iperparametri specifici per condizione* permette, infine, di isolare differenze sistematiche tra gruppi a livello di popolazione. I risultati ottenuti indicano effetti credibili principalmente sul parametro $\\alpha$ (velocità di apprendimento), mentre l'evidenza riguardo al parametro $\\beta$ appare più incerta, in linea con l'ipotesi che la manipolazione sperimentale agisca principalmente sui processi di aggiornamento delle credenze.\n\nDal punto di vista predittivo, il confronto mediante ELPD/LOO-CV dimostra che la struttura gerarchica è un elemento cruciale: i modelli multilevel presentano una capacità predittiva sensibilmente superiore rispetto al modello non gerarchico. Il vantaggio del modello che include la condizione rispetto a quello gerarchico semplice, sebbene orientato nella direzione attesa, risulta modesto rispetto all'incertezza campionaria, rendendolo preferibile quando l'obiettivo è testare l'effetto sperimentale, ma meno decisivo in un'ottica di parsimonia.\n\nEmergono tre messaggi metodologici fondamentali: la progettazione della struttura del modello dovrebbe riflettere le dipendenze naturali presenti nei dati, bilanciando complessità e vincoli; l'integrazione tra informazioni individuali e di popolazione produce stime più robuste e interpretazioni più chiare; la valutazione predittiva out-of-sample allinea la selezione del modello all'obiettivo della generalizzazione.\n\nIn sintesi, il passaggio da modelli basati sul livello della persona a gerarchie che incorporano gruppi noti non rappresenta solo un affinamento tecnico, ma un'evoluzione concettuale verso framework che catturano adeguatamente la struttura della popolazione, rispettano l'eterogeneità individuale e quantificano con rigore le differenze tra le condizioni. Questa architettura metodologica getta solide basi per le future estensioni, dall'identificazione di sottogruppi latenti alla modellazione di strutture temporali più sofisticate, mantenendo come principi guida la capacità predittiva e la coerenza psicologica delle ipotesi teoriche.\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.5.2\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] cmdstanr_0.9.0        ragg_1.5.2            tinytable_0.17.0     \n#>  [4] withr_3.0.3           systemfonts_1.3.2     patchwork_1.3.2      \n#>  [7] ggdist_3.3.3          tidybayes_3.0.7       bayesplot_1.15.0     \n#> [10] ggplot2_4.0.3         reliabilitydiag_0.2.1 priorsense_1.2.0     \n#> [13] posterior_1.7.0       loo_2.10.0            rstan_2.32.7         \n#> [16] StanHeaders_2.32.10   brms_2.23.0           Rcpp_1.1.2           \n#> [19] sessioninfo_1.2.4     conflicted_1.2.0      janitor_2.2.1        \n#> [22] matrixStats_1.5.0     modelr_0.1.11         tibble_3.3.1         \n#> [25] dplyr_1.2.1           tidyr_1.3.2           rio_1.3.0            \n#> [28] here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8          tidyselect_1.2.1      farver_2.1.2         \n#>  [4] R.utils_2.13.0        S7_0.2.2              fastmap_1.2.0        \n#>  [7] tensorA_0.36.2.1      digest_0.6.39         timechange_0.4.0     \n#> [10] estimability_2.0.0    lifecycle_1.0.5       processx_3.9.0       \n#> [13] magrittr_2.0.5        compiler_4.6.1        rlang_1.3.0          \n#> [16] tools_4.6.1           utf8_1.2.6            yaml_2.3.12          \n#> [19] data.table_1.18.4     knitr_1.51            labeling_0.4.3       \n#> [22] bridgesampling_1.2-1  pkgbuild_1.4.8        curl_7.1.0           \n#> [25] RColorBrewer_1.1-3    abind_1.4-8           purrr_1.2.2          \n#> [28] R.oo_1.27.1           grid_4.6.1            stats4_4.6.1         \n#> [31] xtable_1.8-8          inline_0.3.21         emmeans_2.0.3        \n#> [34] scales_1.4.0          cli_3.6.6             mvtnorm_1.4-1        \n#> [37] rmarkdown_2.31        generics_0.1.4        otel_0.2.0           \n#> [40] RcppParallel_5.1.11-2 cachem_1.1.0          stringr_1.6.0        \n#> [43] parallel_4.6.1        vctrs_0.7.3           V8_8.2.0             \n#> [46] Matrix_1.7-5          jsonlite_2.0.0        arrayhelpers_1.1-1   \n#> [49] glue_1.8.1            ps_1.9.3              codetools_0.2-20     \n#> [52] distributional_0.8.1  lubridate_1.9.5       stringi_1.8.7        \n#> [55] gtable_0.3.6          QuickJSR_1.10.0       pillar_1.11.1        \n#> [58] htmltools_0.5.9       Brobdingnag_1.2-9     R6_2.6.1             \n#> [61] textshaping_1.0.5     rprojroot_2.1.1       evaluate_1.0.5       \n#> [64] lattice_0.22-9        R.methodsS3_1.8.2     backports_1.5.1      \n#> [67] memoise_2.0.1         broom_1.0.13          snakecase_0.11.1     \n#> [70] rstantools_2.6.0      coda_0.19-4.1         gridExtra_2.3.1      \n#> [73] nlme_3.1-169          checkmate_2.3.4       xfun_0.60            \n#> [76] pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "03_modeling_heterogeneity_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}