{
  "hash": "1c56e2eb3248cd5cdde34a6abc4637ba",
  "result": {
    "engine": "knitr",
    "markdown": "# Due gruppi: codifiche, differenze e rilevanza pratica {#sec-linear-models-two-groups}\n\nIl confronto tra due gruppi o condizioni è uno dei problemi più ricorrenti nella ricerca psicologica: un gruppo clinico presenta punteggi diversi da un gruppo di controllo? Due condizioni sperimentali producono prestazioni differenti? Un intervento è associato a un cambiamento tale da avere rilievo pratico?\n\nNel @sec-mcmc-one-mean abbiamo formulato la stima di una singola media come un modello lineare a sola intercetta. Per confrontare due gruppi è sufficiente estendere la componente sistematica inserendo un predittore che ne indichi l'appartenenza. Il modello non cambia natura; cambia solo la specificazione della media.\n\nSe assegniamo a $x_i$ il valore 0 per il gruppo di riferimento e 1 per il gruppo di confronto, il modello diventa:\n\n$$\nY_i \\mid x_i, \\alpha, \\beta, \\sigma \\sim \\operatorname{Normal}(\\mu_i, \\sigma), \\qquad \\mu_i = \\alpha + \\beta x_i.\n$$\n\nCon questa codifica (*dummy coding*), $\\alpha$ esprime la media del gruppo di riferimento, mentre $\\beta$ quantifica direttamente la differenza tra le medie dei due gruppi. L'inferenza bayesiana fornisce la distribuzione a posteriori di questo contrasto, permettendo di calcolare la direzione, l'ampiezza e la rilevanza clinica o pratica della differenza.\n\n::: {.callout-important appearance=\"minimal\" .chapter-status}\n**Da sapere.** Il confronto tra due gruppi è un modello lineare con un predittore binario. Le codifiche *dummy*, centrata e a medie di cella descrivono le stesse medie, ma modificano il significato immediato dei coefficienti e dei prior. La distribuzione a posteriori consente di valutare direzione, ampiezza e rilevanza pratica della differenza, senza trasformare SESOI o ROPE in nuove soglie decisionali automatiche. Nei dati osservazionali, una differenza tra gruppi non identifica di per sé un effetto causale.\n\n**Da saper fare.** Specificare e stimare con `brms` un modello gaussiano per due gruppi; scegliere prior coerenti con la parametrizzazione ed eseguire i controlli predittivi a priori e a posteriori; ricavare dai campioni posteriori le medie di gruppo, la differenza grezza $\\Delta$ e la differenza standardizzata $d$; calcolare probabilità posteriori rispetto a zero, a una soglia di rilevanza pratica e a una ROPE; comunicare le conclusioni mantenendo distinta la rilevanza statistica da quella sostantiva.\n\n**Approfondimento facoltativo.** Gli effetti della parametrizzazione sui prior indotti, i modelli con dispersioni differenti, le diverse definizioni della differenza standardizzata, il confronto appaiato e le estensioni robuste possono essere rimandati in una prima lettura. Nel percorso essenziale è sufficiente padroneggiare il modello omoschedastico, le quantità sostantive derivate e la loro interpretazione probabilistica.\n\n[Che cosa significano queste etichette?](../../guida-al-manuale.qmd#sec-percorsi-lettura)\n:::\n\n::: {.callout-note title=\"Obiettivi del capitolo\"}\nAl termine del capitolo dovresti essere in grado di:\n\n- rappresentare il confronto tra due gruppi mediante un modello lineare con predittore binario;\n- interpretare le codifiche dummy, centrata e a medie di cella;\n- riconoscere come la parametrizzazione influisca sul significato dei coefficienti e sulla specificazione dei prior;\n- distinguere le medie di gruppo, la differenza grezza e la differenza standardizzata;\n- calcolare quantità derivate per ogni campione a posteriori;\n- definire una soglia di rilevanza pratica sulla scala appropriata;\n- usare una regione di equivalenza pratica senza trasformarla in una nuova soglia automatica;\n- valutare l'ipotesi di uguale dispersione tra i gruppi;\n- ricondurre un confronto appaiato a un modello sulla differenza intra-individuale;\n- distinguere una differenza descrittiva tra gruppi da un effetto causale.\n:::\n\n::: {.callout-tip collapse=true title=\"Percorsi di lettura\"}\nIl capitolo appartiene al **percorso essenziale** e al **percorso concettuale**. Le sezioni sulle parametrizzazioni, sulle quantità derivate e sulla rilevanza pratica sono centrali per entrambi. Le note sui prior indotti, sui modelli eteroschedastici e sulle diverse definizioni di differenza standardizzata costituiscono approfondimenti utili soprattutto per il percorso computazionale avanzato.\n:::\n\n::: {.callout-tip collapse=true title=\"Prerequisiti e approfondimenti\"}\n- Il modello a sola intercetta è discusso nell'@sec-mcmc-one-mean.\n- Il workflow bayesiano completo con `brms` è presentato nell'@sec-linmod-bayesian-reg.\n- Per la trattazione frequentista del test $t$ per campioni indipendenti e appaiati si veda il modulo [utet-frequentista](https://ccaudek.github.io/utet-frequentista).\n- L'esempio sul QI è tratto da @gelman2021regression.\n- Un riferimento classico sulla stima bayesiana robusta della differenza tra gruppi è @kruschke2013bayesian.\n:::\n\n::: {.callout-caution collapse=true title=\"Preparazione del Notebook\"}\n\n\n:::\n\n## Dalla domanda scientifica alle quantità di interesse\n\nPer illustrare il confronto tra gruppi, utilizzeremo il dataset `kidiq`, che fornisce informazioni sullo sviluppo cognitivo di un campione di bambini e su alcune caratteristiche del nucleo familiare [@gelman2021regression]. In particolare, ci concentreremo su due variabili:\n\n* `kid_score`: il punteggio ottenuto dal bambino nei test di sviluppo cognitivo (QI);\n* `mom_hs`: una variabile indicatore (0/1) che segnala se la madre ha conseguito o meno il diploma di scuola superiore.\n\nLa domanda della ricerca di tipo descrittivo è:\n\n> Di quanto differiscono, in media, i punteggi cognitivi dei bambini nei due gruppi definiti dal livello di istruzione della madre?\n\nIndichiamo con $\\mu_0$ la media teorica dei bambini le cui madri non sono diplomate ($mom\\_hs = 0$) e con $\\mu_1$ la media dei bambini le cui madri sono diplomate ($mom\\_hs = 1$). Le principali quantità di interesse per il contrasto sono:\n\n$$\n\\Delta = \\mu_1 - \\mu_0\n$$\nche esprime la differenza assoluta sulla scala originaria del punteggio di QI, e\n\n$$\nd = \\frac{\\Delta}{\\sigma}\n$$\nche rappresenta la dimensione dell'effetto standardizzata (*d* di Cohen) calcolata rispetto alla deviazione standard residua comune $\\sigma$ stimata dal modello.\n\nInoltre, è possibile definire a priori una soglia di rilevanza pratica o clinica $s$. Ad esempio, se consideriamo sostanziale uno scostamento positivo di almeno 5 punti sul punteggio cognitivo, le quantità probabilistiche di interesse diventano:\n\n$$\n\\Pr(\\Delta > 0 \\mid y) \\qquad \\text{e} \\qquad \\Pr(\\Delta > 5 \\mid y).\n$$\n\n::: {.callout-important title=\"Direzionalità delle soglie teoriche\"}\nLa probabilità della differenza assoluta $\\Pr(\\vert{}\\Delta\\vert{} > 5 \\mid y)$ valuta uno scostamento di almeno 5 punti in entrambe le direzioni. Se l'ipotesi scientifica presuppone una direzione specifica, è teoricamente più corretto e informativo isolare $\\Pr(\\Delta > 5 \\mid y)$ o $\\Pr(\\Delta < -5 \\mid y)$. Questo criterio deve essere stabilito in base al significato metrico e clinico della variabile, senza mai essere selezionato a posteriori per manipolare i risultati.\n:::\n\n::: {.callout-warning title=\"Natura descrittiva del contrasto ed effetto causale\"}\nIl livello di istruzione materna è una caratteristica osservata e non una condizione assegnata casualmente tramite un esperimento. Di conseguenza, il parametro $\\Delta$ descrive un puro contrasto associativo tra i due gruppi e non può essere interpretato, in assenza di un controllo dei fattori di confondimento e di specifiche assunzioni di identificazione, come l'effetto causale diretto del diploma materno sul punteggio del bambino.\n:::\n\n## Esplorazione dei dati\n\nCarichiamo il dataset codificando la variabile esplicativa come fattore ed esaminiamo le statistiche descrittive principali per ciascun gruppo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nkidiq <- rio::import(\n  here::here(\"data\", \"kidiq.dta\")\n) |>\n  transmute(\n    kid_score,\n    mom_hs = factor(\n      mom_hs,\n      levels = c(0, 1),\n      labels = c(\"Non diplomata\", \"Diplomata\")\n    )\n  ) |>\n  drop_na()\n\nkidiq |>\n  group_by(mom_hs) |>\n  summarise(\n    n        = n(),\n    media_QI = mean(kid_score),\n    sd_QI    = sd(kid_score),\n    .groups  = \"drop\"\n  )\n#> # A tibble: 2 x 4\n#>   mom_hs            n media_QI sd_QI\n#>   <fct>         <int>    <dbl> <dbl>\n#> 1 Non diplomata    93     77.5  22.6\n#> 2 Diplomata       341     89.3  19.0\n```\n:::\n\n\nSebbene la tabella delle medie offra una prima sintesi numerica del contrasto, essa non è in grado di mostrare né la forma delle distribuzioni né l'entità della loro sovrapposizione.\n\nVisualizziamo l'intera struttura dei dati combinando grafici a violino, boxplot e la mappa dei singoli punti osservati:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nkidiq |>\n  ggplot(aes(x = mom_hs, y = kid_score)) +\n  geom_violin(trim = FALSE, alpha = 0.4, fill = \"grey80\", color = \"grey50\") +\n  geom_boxplot(width = 0.12, outlier.shape = NA, alpha = 0.7, fatigue = TRUE) +\n  geom_jitter(width = 0.08, alpha = 0.25, size = 1.2, color = \"grey30\") +\n  labs(\n    x = \"Istruzione materna\",\n    y = \"Punteggio cognitivo del bambino\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzione dei punteggi cognitivi nei due gruppi definiti dall'istruzione materna. Le medie possono differire anche quando le distribuzioni individuali mostrano un'ampia sovrapposizione.](06_due_gruppi_rilevanza_pratica_files/figure-pdf/fig-kidiq-two-groups-1.png){#fig-kidiq-two-groups fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\nL'ispezione grafica suggerisce uno scostamento tra i centri delle due distribuzioni, ma evidenzia anche una marcata variabilità interna a ciascun gruppo. Il modello lineare dovrà quindi essere in grado di catturare e quantificare separatamente queste due caratteristiche: la differenza di posizione e l'eterogeneità residua condivisa.\n\n## Il modello lineare con indicatore binario\n\nDefiniamo la variabile indicatore (*dummy variable*) ponendo $x_i = 0$ per il gruppo delle madri \"Non diplomate\" e $x_i = 1$ per il gruppo delle madri \"Diplomate\". Il modello gaussiano omoschedastico assume la forma:\n\n$$\n\\begin{aligned} \nY_i \\mid x_i, \\alpha, \\beta, \\sigma &\\sim \\operatorname{Normal}(\\mu_i,\\sigma), \\\\ \\mu_i &= \\alpha + \\beta x_i. \n\\end{aligned}\n$$ {#eq-two-groups-dummy}\n\nIl sistema di equazioni lineari chiarisce la scomposizione delle medie condizionate per i due profili:\n\n* Per il gruppo di riferimento ($x_i = 0$):\n\n$$\\mu_0 = \\alpha$$\n\n* Per il gruppo di confronto ($x_i = 1$):\n\n$$\\mu_1 = \\alpha + \\beta$$\n\nSottraendo le due espressioni, la differenza tra le medie coincide direttamente con il coefficiente angolare della retta di regressione:\n\n$$\n\\Delta = \\mu_1 - \\mu_0 = (\\alpha + \\beta) - \\alpha = \\beta.\n$$\n\nIn questa formulazione, il parametro $\\sigma$ definisce la deviazione standard residua comune all'interno di entrambi i gruppi. L'assunzione di omoschedasticità (uguaglianza delle varianze nei gruppi) costituisce un'ipotesi teorica del modello che dovrà essere esplicitamente sottoposta a verifica diagnostica e non accettata a priori.\n\n::: {.callout-note title=\"Il test t di Student come caso speciale del modello lineare\"}\nIl classico test $t$ di Student per campioni indipendenti a varianze omogenee è matematicamente equivalente a un modello di regressione lineare con un unico predittore dicotomico. Nonostante questo parallelismo formale accomuni le due strutture algebriche, le interpretazioni frequentista e bayesiana rimangono profondamente diverse sul piano concettuale. Tale equivalenza mostra tuttavia come il modello lineare sia un framework unificato in grado di riassumere le procedure statistiche tradizionali senza la necessità di introdurre strutture matematiche ad hoc.\n:::\n\n## Tre parametrizzazioni dello stesso confronto\n\nLo stesso sistema di medie di gruppo può essere formalizzato mediante codifiche algebriche diverse. La scelta della parametrizzazione non altera in alcun modo le quantità sostantive stimate ($\\mu_0$, $\\mu_1$ e $\\Delta$), ma modifica radicalmente il significato matematico immediato dei singoli coefficienti e la struttura delle assunzioni a priori.\n\n| Parametrizzazione | Sintassi `brms` | Significato dei coefficienti |\n| --- | --- | --- |\n| **Codifica Dummy** ($x \\in \\{0, 1\\}$) | `y ~ 1 + x` | L'intercetta esprime la media del gruppo di riferimento ($\\mu_0$).<br>\n\n<br>Il coefficiente angolare esprime il contrasto assoluto ($\\Delta$). |\n| **Codifica Centrata** ($x_c \\in \\{-0.5, 0.5\\}$) | `y ~ 1 + x_c` | L'intercetta esprime il punto medio non ponderato tra i gruppi.<br>\n\n<br>Il coefficiente angolare esprime il contrasto assoluto ($\\Delta$). |\n| **Medie di Cella** | `y ~ 0 + gruppo` | Il modello esclude l'intercetta globale.<br>\n\n<br>Vengono stimati direttamente i due parametri di posizione $\\mu_0$ e $\\mu_1$. |\n\n### 1. Codifica Dummy (Variabile Indicatore)\n\nRappresenta l'approccio standard quando è possibile identificare un gruppo di controllo o di riferimento logicamente prioritario. L'intercetta riflette la stima puntuale di tale categoria di riferimento, mentre il coefficiente associato al predittore esprime lo scostamento necessario per raggiungere la media del gruppo di confronto.\n\n### 2. Codifica Centrata\n\nSottraendo il valore costante $0.5$ alla variabile *dummy*, si ottiene un predittore centrato $x_i^c$ con valori pari a $-0.5$ (non diplomata) e $0.5$ (diplomata). Sotto questa formulazione, l'intercetta si sposta sul **punto medio non ponderato** delle medie dei due gruppi:\n\n$$\\alpha_c = \\frac{\\mu_0 + \\mu_1}{2}$$\n\n> **Nota sulla ponderazione:** il valore di $\\alpha_c$ non corrisponde alla media empirica complessiva del campione (*grand mean*) se i due gruppi presentano numerosità sbilanciate ($n_0 \\neq n_1$). Il coefficiente angolare della pendenza continua a quantificare l'effetto differenziale totale $\\Delta$.\n\n### 3. Medie di Cella\n\nRimuovendo esplicitamente l'intercetta globale tramite la sintassi `0 + gruppo`, il framework lineare stima in modo isolato i parametri di posizione di ciascun livello del fattore. Questa parametrizzazione risulta particolarmente vantaggiosa quando si desidera assegnare distribuzioni a priori indipendenti e specifiche alle singole medie, demandando il calcolo dei contrasti a una fase successiva di post-elaborazione sui campioni della distribuzione a posteriori.\n\n::: {.callout-important title=\"L'architettura del modello vincola la struttura dei prior\"}\nAssegnare *prior* reciprocamente indipendenti all'intercetta e al coefficiente di pendenza non equivale a dichiarare *prior* indipendenti sulle medie dei singoli gruppi. Ad esempio, nella codifica *dummy* la media del secondo gruppo è definita come combinazione lineare ($\\mu_1 = \\alpha + \\beta$); di conseguenza, l'incertezza associata ad $\\alpha$ si ripercuote matematicamente sia su $\\mu_0$ sia su $\\mu_1$. Non esiste una codifica oggettivamente migliore: il ricercatore deve scegliere la parametrizzazione che rende la traduzione delle ipotesi teoriche in vincoli probabilistici più trasparente e controllabile.\n:::\n\n## Specificazione del modello e controllo a priori\n\nAdottiamo la codifica *dummy* impostando il gruppo delle madri \"Non diplomate\" come livello baseline di riferimento. I *prior* vengono calibrati direttamente sulla scala metrica del QI (punti di punteggio cognitivo):\n\n* Una distribuzione normale attorno al valore centrale atteso per il gruppo di riferimento;\n* una distribuzione normale speculare e centrata su zero per la differenza tra i gruppi, che esprime scetticismo verso effetti artificialmente enormi;\n* una distribuzione a supporto positivo per la dispersione residua comune all'interno delle categorie.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npriors_two_groups <- c(\n  prior(normal(90, 20), class = \"Intercept\"),\n  prior(normal(0, 15), class = \"b\"),\n  prior(student_t(3, 0, 20), class = \"sigma\")\n)\n```\n:::\n\n\nPrima di condizionare il modello all'evidenza empirica, eseguiamo una simulazione predittiva a priori (*prior predictive check*) per assicurarci che le assunzioni adottate non generino sistematicamente scenari matematicamente impossibili o biologicamente assurdi rispetto al dominio del QI:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_two_groups_prior <- brm(\n  formula = kid_score ~ 1 + mom_hs,\n  data = kidiq,\n  family = gaussian(),\n  prior = priors_two_groups,\n  sample_prior = \"only\", # Estrae campioni esclusivamente dalle distribuzioni a priori\n  backend = \"cmdstanr\",\n  chains = 4,\n  iter = 1000,\n  seed = 1234,\n  refresh = 0\n)\n```\n:::\n\n\nVisualizziamo il profilo delle densità simulate generate dai soli *prior*:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp_check(\n  fit_two_groups_prior,\n  type = \"dens_overlay\",\n  ndraws = 40\n)\n```\n\n::: {.cell-output-display}\n![Controllo predittivo a priori per il modello a due gruppi. Le repliche servono a valutare le conseguenze congiunte dei prior sulla scala osservata.](06_due_gruppi_rilevanza_pratica_files/figure-pdf/fig-prior-predictive-two-groups-1.png){#fig-prior-predictive-two-groups fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\n> **Nota diagnostica:** questo controllo non ha lo scopo di certificare se i *prior* siano \"oggettivamente corretti\" o veri. La sua funzione è puramente pragmatica: esplicitare e rendere visibili sulla scala osservabile le conseguenze congiunte delle nostre scelte probabilistiche, consentendo di individuare e correggere tempestivamente vincoli a priori eccessivamente dogmatici (iper-concentrati) o irrealisticamente dispersi.\n\n## Stima del modello e verifiche computazionali\n\nProcediamo al condizionamento del modello integrando i dati empirici per ottenere la distribuzione a posteriori:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_two_groups <- brm(\n  formula = kid_score ~ 1 + mom_hs,\n  data = kidiq,\n  family = gaussian(),\n  prior = priors_two_groups,\n  backend = \"cmdstanr\",\n  chains = 4,\n  iter = 2000,\n  seed = 1234,\n  refresh = 0\n)\n```\n:::\n\n\nLe verifiche formali sulla convergenza e sulla qualità algoritmica del campionamento MCMC seguono i criteri metodologici già illustrati nell'@sec-linmod-bayesian-reg:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummarise_draws(\n  as_draws_array(fit_two_groups),\n  \"mean\", \n  \"sd\", \n  \"rhat\", \n  \"ess_bulk\", \n  \"ess_tail\"\n)\n#> # A tibble: 6 x 6\n#>   variable             mean    sd  rhat ess_bulk ess_tail\n#>   <chr>               <dbl> <dbl> <dbl>    <dbl>    <dbl>\n#> 1 b_Intercept          77.7 2.07  1.000    3872.    3028.\n#> 2 b_mom_hsDiplomata    11.5 2.35  1.000    3859.    2944.\n#> 3 sigma                19.9 0.670 1.00     3548.    2468.\n#> 4 Intercept            86.8 0.940 1.00     4054.    2878.\n#> 5 lprior              -11.7 0.127 1.000    3794.    3107.\n#> 6 lp__              -1922.  1.20  1.00     2159.    2877.\n```\n:::\n\n\n> **Nota di interpretazione:** è importante ripetere che la convergenza ottimale delle catene e l'assenza di patologie numeriche non garantiscono la validità scientifica del modello. Valori ideali di $\\widehat{R}$ e un numero elevato di campioni effettivi ($ESS$) indicano semplicemente che l'algoritmo Stan ha esplorato la distribuzione a posteriori congiunta in modo matematicamente affidabile. La valutazione dell'adeguatezza della verosimiglianza normale e dell'assunzione di omoschedasticità spetta invece ai successivi controlli predittivi a posteriori.\n\n## Dalle coordinate del modello alle quantità sostantive\n\nDopo aver stimato i parametri nelle \"coordinate\" algebriche della regressione ($\\alpha$ e $\\beta$), passiamo alla derivazione delle quantità dotate di un immediato significato scientifico. Estraiamo i campioni dalla distribuzione a posteriori per calcolare, draw dopo draw, le medie dei due gruppi, la loro differenza grezza e l'effetto standardizzato:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npost_two_groups <- as_draws_df(fit_two_groups) |>\n  transmute(\n    mu0   = b_Intercept,\n    delta = b_mom_hsDiplomata,\n    mu1   = b_Intercept + b_mom_hsDiplomata,\n    sigma = sigma,\n    d     = delta / sigma\n  )\n\nsummarise_draws(\n  post_two_groups[, c(\"mu0\", \"mu1\", \"delta\", \"sigma\", \"d\")]\n)\n#> # A tibble: 5 x 10\n#>   variable   mean median    sd   mad     q5    q95  rhat ess_bulk ess_tail\n#>   <chr>     <dbl>  <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl>    <dbl>    <dbl>\n#> 1 mu0      77.7   77.7   2.07  2.10  74.3   81.1   1.00     3723.    2904.\n#> 2 mu1      89.3   89.3   1.07  1.03  87.5   91.1   1.00     4005.    2983.\n#> 3 delta    11.5   11.6   2.35  2.41   7.75  15.4   1.000    3810.    2887.\n#> 4 sigma    19.9   19.9   0.670 0.663 18.8   21.0   1.000    3441.    2465.\n#> 5 d         0.581  0.581 0.120 0.122  0.388  0.781 1.000    3896.    2791.\n```\n:::\n\n\nQuesta operazione mette in luce un principio fondamentale del workflow bayesiano: il modello viene parametrizzato nella forma computazionalmente più efficiente o comoda per il campionamento, ma l'analisi finale deve essere costruita sulle quantità matematiche che rispondono in modo diretto agli interrogativi della ricerca.\n\n### La differenza sulla scala originale\n\nLa distribuzione a posteriori di $\\Delta$ (espressa in punti di QI) mantiene l'unità di misura originale del test ed è la metrica principale da comunicare quando la scala possiede un significato clinico o pratico ben noto.\n\nVisualizziamo la densità della differenza a posteriori confrontandola sia con l'ipotesi di assenza di effetto sia con una soglia di rilevanza pratica (*SESOI* — *Smallest Effect Size of Interest*):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSESOI_delta <- 5\n\npost_two_groups |>\n  ggplot(aes(x = delta)) +\n  geom_density(fill = \"grey90\", color = \"grey40\", alpha = 0.5) +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"firebrick\") +\n  geom_vline(xintercept = SESOI_delta, linetype = \"dotted\", color = \"steelblue\", size = 1) +\n  labs(\n    x = expression(paste(\"Differenza grezza (\", Delta, \")\")),\n    y = \"Densità a posteriori\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzione a posteriori della differenza grezza tra le medie. Le linee verticali indicano l'assenza di effetto (0) e la soglia di rilevanza pratica stabilita (5 punti di QI).](06_due_gruppi_rilevanza_pratica_files/figure-pdf/fig-posterior-delta-two-groups-1.png){#fig-posterior-delta-two-groups fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\nLe probabilità associate a queste soglie sostantive si ottengono contando quanti draw della posterior soddisfano i rispettivi criteri logici:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(\n  P_delta_positive = mean(post_two_groups$delta > 0),\n  P_delta_relevant = mean(post_two_groups$delta > SESOI_delta),\n  P_delta_in_rope  = mean(abs(post_two_groups$delta) <= SESOI_delta)\n)\n#> P_delta_positive P_delta_relevant  P_delta_in_rope \n#>          1.00000          0.99775          0.00225\n```\n:::\n\n\nLe ultime due quantità rispondono a domande speculari e complementari (la probabilità che l'effetto sia sostanziale vs la probabilità che l'effetto sia trascurabile o nullo). È fondamentale ricordare che tali valori probabilistici non si traducono automaticamente in decisioni binarie: la soglia dei 5 punti deve essere validata teoricamente sulla base della letteratura del dominio, e il livello di certezza richiesto per agire di conseguenza deve essere fissato prima di esaminare i dati per evitare distorsioni interpretative.\n\n## Differenza standardizzata e dimensione dell'effetto {#sec-bayesian-effect-size}\n\nSe la differenza grezza rappresenta la metrica più trasparente quando la scala ha un significato psicometrico o clinico noto, la standardizzazione si rivela utile per confrontare risultati ottenuti attraverso strumenti di misura differenti o per alimentare studi meta-analitici.\n\nNel modello lineare omoschedastico, la dimensione dell'effetto standardizzata è definita come:\n\n$$\nd = \\frac{\\mu_1 - \\mu_0}{\\sigma} = \\frac{\\Delta}{\\sigma}.\n$$ {#eq-standardized-difference}\n\nPoiché sia la differenza tra le medie ($\\Delta$) sia la deviazione standard residua ($\\sigma$) sono parametri incerti, il valore di $d$ viene calcolato separatamente per ogni singolo *draw* della distribuzione a posteriori. In questo modo, l'incertezza stimata per entrambe le componenti si propaga matematicamente e in modo automatico sul rapporto finale.\n\n::: {.callout-note title=\"Natura e limiti del parametro d\"}\nIl formalismo espresso nella @eq-standardized-difference rappresenta il contrasto tra le medie condizionate misurato in unità di deviazione standard residua comune. Si tratta dell'equivalente modellistico del $d$ di Cohen per campioni indipendenti, ma non include la correzione algoritmica per piccoli campioni tipica del *g* di Hedges. Inoltre, in presenza di eteroschedasticità (varianze disuguali tra gruppi) o di disegni a misure ripetute, la scelta del denominatore non è univoca e richiede una definizione esplicita.\n:::\n\nVisualizziamo la distribuzione a posteriori di $d$, sovrapponendo i benchmark convenzionali proposti da Cohen:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npost_two_groups |>\n  ggplot(aes(x = d)) +\n  geom_density(fill = \"grey90\", color = \"grey40\", alpha = 0.5) +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"firebrick\") +\n  geom_vline(\n    xintercept = c(0.2, 0.5, 0.8),\n    linetypes  = \"dotted\",\n    color      = \"grey30\"\n  ) +\n  labs(\n    x = expression(paste(\"Differenza standardizzata (\", d, \")\")),\n    y = \"Densità a posteriori\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzione a posteriori della differenza standardizzata d. I benchmark a 0.2, 0.5 e 0.8 sono inclusi come riferimenti storici e convenzionali, non come confini naturali del fenomeno.](06_due_gruppi_rilevanza_pratica_files/figure-pdf/fig-posterior-standardized-difference-1.png){#fig-posterior-standardized-difference fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\nPossiamo ora tradurre le soglie standardizzate in enunciati probabilistici diretti, calcolando la percentuale di campioni della posterior che supera ogni valore critico:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(\n  P_d_positive = mean(post_two_groups$d > 0),\n  P_d_gt_0_2   = mean(post_two_groups$d > 0.2),\n  P_d_gt_0_5   = mean(post_two_groups$d > 0.5),\n  P_d_gt_0_8   = mean(post_two_groups$d > 0.8)\n)\n#> P_d_positive   P_d_gt_0_2   P_d_gt_0_5   P_d_gt_0_8 \n#>       1.0000       0.9995       0.7418       0.0335\n```\n:::\n\n\n### Perché standardizzare (e quando evitare di farlo)\n\nL'indice standardizzato facilita la sintesi quantitativa tra studi diversi, ma non costituisce una trasformazione matematicamente neutra. Presenta infatti alcuni vincoli strutturali:\n\n* **Dipendenza dalla varianza:** a parità di differenza grezza nei punteggi, popolazioni più omogenee (con $\\sigma$ minore) generano artificialmente valori di $d$ più elevati.\n* **Sensibilità metodologica:** il denominatore risente direttamente della qualità dello strumento e del controllo sperimentale: una misura meno precisa aumenta $\\sigma$ e diminuisce il valore di $d$.\n* **Asimmetria degli effetti:** due ricerche possono mostrare un'identica dimensione dell'effetto $d$ pur presentando differenze grezze e ricadute pratiche radicalmente diverse.\n\nIl significato clinico, educativo o sociale di un risultato emerge con maggiore chiarezza sulla scala nativa del fenomeno. La buona pratica scientifica prevede quindi di documentare sempre la differenza grezza e di affiancarle la stima standardizzata solo come integrazione comparativa.\n\n### Uso critico delle soglie convenzionali\n\nI valori $0.2$, $0.5$ e $0.8$ vengono meccanicamente associati alle etichette di effetto \"piccolo\", \"medio\" e \"grande\". Jacob Cohen introdusse questi criteri come semplici punti di riferimento generali, da impiegare esclusivamente in assenza di qualunque conoscenza pregressa sul dominio, mettendone in guardia contro un uso rigido.\n\nUn effetto inferiore a $0.2$ può assumere una rilevanza scientifica straordinaria se applicato a un esito critico (ad esempio, i tassi di mortalità o di abbandono scolastico) attraverso un intervento economico su vasta scala. Al contrario, un effetto superiore a 0.8 può rivelarsi irrilevante se l'indicatore finale non possiede un reale valore teorico o applicativo. Sostituire il binarismo \"significativo/non significativo\" con la classificazione categoriale \"piccolo/medio/grande\" non risolve l'esigenza di una valutazione critica del dato.\n\n::: {.callout-warning title=\"L'incertezza supera le categorie rigide\"}\nLa distribuzione a posteriori di $d$ può intersecare contemporaneamente più fasce convenzionali. Questa dispersione non rappresenta un limite del modello, ma esprime l'incertezza reale sul parametro. Qualora la letteratura scientifica di riferimento fornisca una soglia specifica per il costrutto in esame, tale valore deve avere la priorità assoluta rispetto alle tassonomie generiche.\n:::\n\n## SESOI e regione di equivalenza pratica\n\nLa **SESOI** (*Smallest Effect Size of Interest*) definisce la minima grandezza dell'effetto considerata rilevante dal punto di vista scientifico o clinico. La **ROPE** (*Region of Practical Equivalence*) identifica invece un intervallo di valori attorno all'effetto nullo ($0$) all'interno del quale gli effetti sono giudicati così esigui da essere considerati praticamente equivalenti all'assenza di effetto.\n\nQuesti due concetti sono strettamente correlati. Se, ad esempio, stabiliamo che uno scostamento di 5 punti sul QI rappresenta la minima variazione dotata di impatto pratico, la corrispondente regione di equivalenza sulla scala originale del test è definita dall'intervallo:\n\n$$[-5, 5]$$\n\nAttraverso i campioni della distribuzione a posteriori, possiamo suddividere lo spazio degli effetti e quantificare con precisione:\n\n* la massa di probabilità a posteriori che supera la soglia positiva di rilevanza;\n* la massa che scende sotto la soglia negativa;\n* la massa interamente contenuta all'interno della regione di equivalenza pratica (effetto trascurabile).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(\n  P_relevant_positive      = mean(post_two_groups$delta > 5),\n  P_relevant_negative      = mean(post_two_groups$delta < -5),\n  P_practically_equivalent = mean(abs(post_two_groups$delta) <= 5)\n)\n#>      P_relevant_positive      P_relevant_negative P_practically_equivalent \n#>                  0.99775                  0.00000                  0.00225\n```\n:::\n\n\nLa frazione di posterior che cade all'interno della ROPE non determina automaticamente una conclusione scientifica univoca. L'interpretazione richiede l'adozione esplicita di una regola decisionale definita a priori (come il posizionamento dell'intero intervallo di credibilità rispetto ai confini della ROPE), la valutazione dei costi legati a eventuali falsi positivi o negativi e la verifica che la precisione del campionamento sia adeguata.\n\nLa scelta della ROPE dovrebbe idealmente privilegiare la scala metrica originale dei dati. Qualora sia necessario operare su indici standardizzati, è possibile applicare lo stesso principio alla distribuzione di $d$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbayestestR::rope(\n  post_two_groups$d,\n  range = c(-0.1, 0.1),\n  ci    = 0.95\n)\n#> # Proportion of samples inside the ROPE [-0.10, 0.10]:\n#> \n#> Inside ROPE\n#> -----------\n#> 0.00 %\n```\n:::\n\n\n> **Nota metodologica:** i confini standardizzati pari a $[-0.1, 0.1]$ proposti nella funzione precedente costituiscono un punto di riferimento puramente convenzionale e generico. Tali limiti non devono mai essere applicati in modo acritico o automatico, ma devono essere esplicitamente giustificati in base alle specificità teoriche del costrutto esaminato e al disegno sperimentale adottato.\n\n## Controllare l'adeguatezza del modello\n\nLa convergenza computazionale ottimale delle catene MCMC non garantisce che la struttura matematica scelta sia in grado di rappresentare fedelmente le distribuzioni reali dei due gruppi. Per iniziare a valutare l'adeguatezza del modello, eseguiamo un controllo predittivo a posteriori (*PPC*) sulla distribuzione marginale globale:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npp_check(\n  fit_two_groups,\n  type = \"dens_overlay\",\n  ndraws = 40\n)\n```\n\n::: {.cell-output-display}\n![Controllo predittivo a posteriori della distribuzione marginale. Un buon accordo complessivo non garantisce che il modello riproduca separatamente entrambi i gruppi.](06_due_gruppi_rilevanza_pratica_files/figure-pdf/fig-ppc-two-groups-1.png){#fig-ppc-two-groups fig-align='center' fig-pos='H' width=85%}\n:::\n:::\n\n\nUn allineamento soddisfacente sulla densità marginale aggregata può tuttavia mascherare anomalie locali o asimmetrie all'interno delle singole categorie. Per esaminare esplicitamente il comportamento del modello nei sottogruppi, estraiamo le distribuzioni delle medie attese condizionate per ciascun livello del fattore:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnew_groups <- tibble(\n  mom_hs = factor(\n    c(\"Non diplomata\", \"Diplomata\"),\n    levels = levels(kidiq$mom_hs)\n  )\n)\n\nmu_group_draws <- posterior_epred(\n  fit_two_groups,\n  newdata = new_groups\n)\n\nposterior::summarise_draws(\n  as_draws_matrix(mu_group_draws)\n)\n#> # A tibble: 2 x 10\n#>   variable  mean median    sd   mad    q5   q95  rhat ess_bulk ess_tail\n#>   <chr>    <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>    <dbl>    <dbl>\n#> 1 ...1      77.7   77.7  2.07  2.10  74.3  81.1  1.00    3723.    2904.\n#> 2 ...2      89.3   89.3  1.07  1.03  87.5  91.1  1.00    4005.    2983.\n```\n:::\n\n\n### Uguale dispersione nei due gruppi\n\n### Eteroschedasticità: modellare la dispersione tra i gruppi\n\nIl modello lineare classico impone il vincolo di omoschedasticità tramite un unico parametro globale di scala $\\sigma$. Se uno dei due gruppi presenta una variabilità interna significativamente diversa rispetto all'altro, questa assunzione rigida rischia di distorcere gli intervalli di credibilità e di inficiare il calcolo della dimensione dell'effetto standardizzata $d$.\n\nPer superare questo limite, possiamo estendere il framework bayesiano introducendo una sotto-formula che modella esplicitamente la dispersione residua in funzione dell'appartenenza al gruppo:\n\n```r\nbf(\n  kid_score ~ 1 + mom_hs,\n  sigma ~ 0 + mom_hs\n)\n```\n\n> **Nota di calcolo:** in `brms`, la componente lineare per il parametro di scala utilizza di default una funzione di *link* logaritmica ($\\log(\\sigma)$). Questa trasformazione garantisce che le deviazioni standard stimate rimangano vincolate a valori strettamente positivi sulla scala originale. I *prior* per questa sezione del modello devono pertanto essere calibrati tenendo conto della scala logaritmica.\n\n### Code pesanti e osservazioni estreme\n\nQualora i controlli diagnostici evidenzino la presenza di valori estremi o anomalie strutturali che la distribuzione gaussiana fatica a riprodurre, è opportuno adottare una verosimiglianza $t$ di Student come specificazione robusta del modello [@kruschke2013bayesian]:\n\n```r\nbrm(\n  kid_score ~ 1 + mom_hs,\n  data = kidiq,\n  family = student(),\n  prior = ...\n)\n```\n\nL'adozione di un approccio statistico robusto non deve mai essere considerata un espediente automatico per tollerare errori di campionamento, refusi nella codifica dei dati o la presenza di popolazioni eterogenee non modellate (es. distribuzioni miste). Qualsiasi architettura alternativa deve essere supportata da solide motivazioni teoriche e convalidata attraverso il workflow predittivo.\n\n## Differenza standardizzata e affidabilità della misura\n\nLa deviazione standard residua ($\\sigma$) stimata dal modello incorpora sia la variabilità biologica o psicologica intrinseca tra gli individui, sia la quota di variabilità dovuta all'errore di misurazione dello strumento. Sotto le assunzioni della teoria classica dei test — che prevede un errore additivo, indipendente e con media pari a zero — l'impiego di una misura caratterizzata da una bassa affidabilità (*reliability*) gonfia artificialmente la dispersione entro i gruppi. Di conseguenza, il denominatore della @eq-standardized-difference aumenta, producendo una sistematica attenuazione della dimensione dell'effetto standardizzata $d$.\n\nQuesta conclusione, però, richiede cautela:\n\n* **Eteroschedasticità dell'errore:** se l'entità dell'errore di misura varia sistematicamente tra i gruppi, l'effetto non si limita a una semplice attenuazione lineare, ma distorce la simmetria del confronto.\n* **Misclassificazione del predittore:** qualora l'errore di misura colpisca la variabile indipendente (ad esempio, un'errata assegnazione dei soggetti ai gruppi), a subire una distorsione non è solo la variabilità residua, ma la stessa differenza grezza $\\Delta$ sui punteggi centoidi.\n* **Eterogeneità dei costrutti:** strumenti differenti, pur se formalmente standardizzati sulla medesima scala metrica, possono mappare dimensioni latenti non perfettamente equivalenti, rendendo il confronto tra i rispettivi indici $d$ puramente nominale.\n\nI modelli avanzati in grado di separare analiticamente la variabilità dei costrutti latenti dall'errore delle componenti osservate saranno trattati in dettaglio nel capitolo dedicato all'errore di misurazione (@sec-meas-error-regr).\n\n## Due misure sugli stessi individui\n\nFinora abbiamo considerato il confronto tra gruppi indipendenti. Quando invece lo stesso partecipante viene osservato in due momenti o condizioni (ad esempio, in un disegno prima-dopo), le due misure risultano intrinsecamente dipendenti. Trattarle come osservazioni indipendenti ignorerebbe l'informazione legata all'appaiamento, sovrastimando la variabilità residua.\n\nUna strategia classica per analizzare questi dati consiste nel calcolare preliminarmente lo scostamento individuale:\n\n$$\nD_i = Y_{i,\\mathrm{pre}} - Y_{i,\\mathrm{post}}.\n$$\n\nIl problema si riduce così all'adattamento di un modello lineare a sola intercetta applicato direttamente sulla variabile delle differenze intra-individuali:\n\n$$\nD_i \\sim \\operatorname{Normal}(\\mu_D, \\sigma_D).\n$$\n\nPer illustrare questo approccio, utilizziamo i punteggi pre e post relativi ai sintomi depressivi misurati tramite la scala CES-D [@tarrats2025efficacy]:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndf_pre_post <- readxl::read_excel(\n  here::here(\"data\", \"Tarrats-Pons.xlsx\"),\n  sheet = 3\n) |>\n  select(\n    IdentificationNumber,\n    Sample,\n    CESD = `CESS-D`\n  ) |>\n  pivot_wider(\n    names_from  = Sample,\n    values_from = CESD,\n    names_prefix = \"CESD_\"\n  ) |>\n  mutate(\n    diff = CESD_PRE - CESD_POST\n  ) |>\n  drop_na(diff)\n```\n:::\n\n\nCondizioniamo il modello a sola intercetta stimando i parametri sulla serie delle differenze:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_paired <- brm(\n  formula = diff ~ 1,\n  data    = df_pre_post,\n  family  = gaussian(),\n  prior   = c(\n    prior(normal(0, 10), class = \"Intercept\"),\n    prior(student_t(3, 0, 10), class = \"sigma\")\n  ),\n  backend = \"cmdstanr\",\n  chains  = 4,\n  iter    = 2000,\n  seed    = 1234,\n  refresh = 0\n)\n```\n:::\n\n\nPer derivare le quantità sostantive, manipoliamo i campioni a posteriori:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Estraiamo i draws mantenendo la struttura formale dell'oggetto posterior\ndraws_paired <- as_draws(fit_paired)\n\n# Utilizziamo mutate_variables per calcolare l'effetto standardizzato d_z\ndraws_derived <- posterior::mutate_variables(\n  draws_paired,\n  mean_difference = b_Intercept,\n  sd_difference   = sigma,\n  d_z             = b_Intercept / sigma\n)\n\n# Selezioniamo le sole quantità di interesse e generiamo i summary descrittivi\ndraws_subset <- subset_draws(\n  draws_derived, \n  variable = c(\"mean_difference\", \"sd_difference\", \"d_z\")\n)\n\nsummarise_draws(draws_subset)\n#> # A tibble: 3 x 10\n#>   variable          mean median     sd    mad     q5    q95  rhat ess_bulk\n#>   <chr>            <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl> <dbl>    <dbl>\n#> 1 mean_difference  4.69   4.70  0.985  1.02    3.11   6.30   1.00    3208.\n#> 2 sd_difference   11.3   11.2   0.721  0.721  10.1   12.5    1.00    3045.\n#> 3 d_z              0.418  0.416 0.0907 0.0936  0.272  0.567  1.00    3339.\n#>   ess_tail\n#>      <dbl>\n#> 1    2763.\n#> 2    2355.\n#> 3    3005.\n```\n:::\n\n\nPer ottenere valutazioni probabilistiche dirette sul segno del cambiamento, estraiamo il vettore specifico tramite `merge_chains`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Estrazione del vettore a posteriori e calcolo della probabilità di riduzione sintomatologica\nmean_diff_samples <- as_draws_matrix(draws_subset, variable = \"mean_difference\")\nmean(mean_diff_samples > 0)\n#> [1] 1\n```\n:::\n\n\n> **Interpretazione della metrica:** avendo definito la differenza come `pre - post`, un valore a posteriori positivo di $\\mu_D$ indica una riduzione netta della sintomatologia depressiva. L'indice standardizzato $d_z = \\mu_D / \\sigma_D$ esprime il contrasto in unità di deviazione standard delle *differenze* intra-individuali. Di conseguenza, $d_z$ non è matematicamente confrontabile con il $d$ di Cohen calcolato su gruppi indipendenti, poiché il suo valore risente direttamente della covarianza tra i due tempi di rilevazione.\n\n::: {.callout-note title=\"Perché e quando l'appaiamento incrementa l'efficienza\"}\nQuando le misure ripetute sullo stesso individuo mostrano una correlazione positiva stabile, l'operazione di sottrazione elimina dal modello la variabilità interindividuale a livello di baseline (le differenze costanti tra le persone). La deviazione standard delle differenze ($\\sigma_D$) risulterà così nettamente inferiore rispetto alla variabilità grezza dei punteggi originari, determinando un aumento della precisione (intervalli di credibilità più stretti). Tale guadagno informativo non è tuttavia garantito da un automatismo matematico, ma dipende strettamente dall'affidabilità temporale dello strumento e dall'assenza di pattern complessi di dati mancanti (*missing data*).\n:::\n\nSe il disegno sperimentale include più di due occasioni di misura, intervalli temporali irregolari tra i soggetti, covariate che variano nel tempo o osservazioni incomplete, il semplice calcolo delle differenze mostra evidenti limiti. In questi scenari, l'estensione verso un **modello lineare multilivello (o a effetti misti)** strutturato direttamente sulle osservazioni longitudinali originarie rappresenta una soluzione metodologicamente più solida e flessibile.\n\n## Comunicare i risultati\n\nUna rendicontazione scientifica trasparente e informativa del confronto tra due gruppi dovrebbe integrare i seguenti elementi metodologici:\n\n1. Le stime dei parametri di posizione (medie di gruppo) o le rispettive distribuzioni a posteriori;\n2. la differenza grezza accompagnata da un intervallo di credibilità (es. HDI al 95%);\n3. la probabilità a posteriori associata alla direzione dell'effetto;\n4. la probabilità di superare una soglia di rilevanza pratica (*SESOI*), se definita a priori;\n5. la dimensione dell'effetto standardizzata, esplicitando chiaramente la natura del denominatore impiegato per il calcolo;\n6. gli esiti dei principali controlli di adeguatezza e robustezza (*PPC*);\n7. i vincoli strutturali del disegno di ricerca e i limiti alla validità dell'interpretazione causale.\n\nUn possibile modello di stesura per la sezione Risultati è il seguente:\n\n> Per verificare lo scostamento nello sviluppo cognitivo in base al background familiare, abbiamo stimato un modello lineare bayesiano gaussiano. Nel campione analizzato, il punteggio medio dei bambini nel gruppo delle madri diplomate ($\\mu_1 = 89.3$, HDI 95% $[86.5, 92.1]$) è risultato superiore a quello del gruppo delle madri non diplomate ($\\mu_0 = 77.5$, HDI 95% $[72.8, 82.2]$). La distribuzione a posteriori della differenza grezza indica un incremento plausibile di $\\Delta = 11.8$ punti di QI (HDI 95% $[6.3, 17.3]$).\n> La probabilità che il contrasto sia strettamente positivo è pari a $\\Pr(\\Delta > 0 \\mid y) > .99$, mentre la probabilità che lo scostamento superi la soglia di rilevanza teorica di 5 punti è $\\Pr(\\Delta > 5 \\mid y) = .98$. A titolo comparativo, la dimensione dell'effetto standardizzata basata sulla deviazione standard residua comune ($\\sigma = 18.2$) è pari a $d = 0.65$ (HDI 95% $[0.34, 0.96]$). I controlli predittivi a posteriori confermano l'adeguatezza della verosimiglianza normale. Trattandosi di un disegno osservazionale e non sperimentale, tale contrasto descrive un'associazione sistematica e non può essere interpretato come effetto causale diretto dell'istruzione materna.\n\n> **Guida alla redazione:** I valori numerici e gli intervalli devono essere inseriti attingendo direttamente dalle sintesi computazionali dei *draws*. È buona pratica metodologica evitare l'uso di aggettivi qualificativi ambigui o assoluti (come \"effetto grande\", \"forte legame\" o \"differenza trascurabile\") a meno che non si stia ancorando esplicitamente il dato a criteri di categorizzazione standardizzati o a soglie cliniche formalmente giustificate all'interno del dominio di studio.\n\n## Errori frequenti\n\n::: {.callout-caution}\n1. **Interpretare il coefficiente senza conoscere la codifica.** Con un fattore, il significato di intercetta e coefficienti dipende dal gruppo di riferimento e dai contrasti usati.\n2. **Confondere la differenza grezza con quella standardizzata.** $\\Delta$ conserva l'unità di misura; $d$ dipende anche dal denominatore scelto.\n3. **Usare le soglie di Cohen come leggi naturali.** Sono riferimenti convenzionali, non criteri universali di importanza.\n4. **Definire SESOI o ROPE dopo avere visto la posterior.** La soglia deve derivare dal problema scientifico e dalle conseguenze pratiche.\n5. **Concludere equivalenza soltanto perché l'intervallo comprende zero.** Mancanza di precisione ed equivalenza pratica sono situazioni diverse.\n6. **Assumere automaticamente varianze uguali.** La dispersione comune è parte della specificazione e deve essere controllata.\n7. **Trattare dati appaiati come gruppi indipendenti.** In questo modo si ignora la dipendenza tra misure della stessa persona.\n8. **Attribuire un significato causale alla differenza osservata.** Un contrasto tra gruppi non randomizzati può riflettere molte differenze concomitanti.\n:::\n\n## Riflessioni conclusive\n\nIl confronto tra due gruppi o condizioni non richiede un impianto statistico separato o speciale, ma rientra pienamente nel modello lineare, che è un framework flessibile. Utilizzando un indicatore binario (*dummy coding*), l'intercetta e il coefficiente angolare della regressione si collegano direttamente alle medie condizionate dei gruppi e alla loro differenza. La scelta di codifiche alternative (come quella centrata o le medie di cella) non altera il sistema delle quantità sostantive, ma modifica radicalmente l'assegnazione dei *prior* e la trasparenza delle assunzioni teoriche sottostanti.\n\nL'inferenza bayesiana permette di superare i limiti delle decisioni dicotomiche imposte valore-*p*. L'accesso all'intera distribuzione a posteriori di $\\Delta$ consente infatti di stimare con precisione la direzione, l'ampiezza sulla scala originaria e la probabilità che l'effetto superi una soglia di rilevanza pratica stabilita a priori. Sebbene l'effetto standardizzato ($d$) rimanga uno strumento utile per il confronto tra studi e la ricerca meta-analitica, esso risente fortemente della variabilità della popolazione e della precisione psicometrica delle misure. Per questo motivo, l'indice standardizzato deve sempre affiancare, e non sostituire, la differenza grezza espressa nelle unità metriche native del fenomeno.\n\nL'introduzione della *SESOI* e della *ROPE* sposta il focus della ricerca dall'esistenza puramente statistica di un effetto alla sua importanza pratica o clinica, esplicitando il confine tra differenze sostanziali e scostamenti trascurabili.  L'applicazione di questi parametri non esime tuttavia il ricercatore dall'onere di giustificare i propri benchmark dal punto di vista teorico né dalla necessità di pianificare studi con una precisione (numerosità campionaria) adeguata. Allo stesso modo, l'assenza di patologie nell'algoritmo di campionamento MCMC non garantisce la correttezza della specificazione teorica che deve sempre essere validata verificando l'adeguatezza della forma distributiva e l'assunzione di omoschedasticità.\n\nInfine, la distinzione tra gruppi indipendenti e misure appaiate evidenzia come la struttura del disegno di ricerca vincoli la definizione stessa degli *estimand* e delle deviazioni standard di riferimento. Nel prossimo capitolo estenderemo questa stessa architettura al confronto tra più di due gruppi, mostrando come l'analisi della varianza (ANOVA) a una via possa essere ricondotta in modo del tutto naturale a un modello lineare con predittori categoriali, in cui le ipotesi scientifiche vengono tradotte e verificate mediante la manipolazione delle medie di cella e la pianificazione dei contrasti.\n\n## Concetti da ricordare\n\n1. Il confronto tra due gruppi è un modello lineare con predittore binario.\n2. La codifica determina il significato dei coefficienti, non le medie sostantive implicate dal modello.\n3. La differenza grezza $\\Delta$ è generalmente la prima quantità da interpretare.\n4. Il contrasto standardizzato $d$ è una quantità derivata e dipende dalla deviazione standard scelta.\n5. Prior su coefficienti diversi possono indurre strutture a priori differenti sulle medie di gruppo.\n6. SESOI e ROPE formalizzano un giudizio sostantivo, ma non forniscono da sole una decisione universale.\n7. La dispersione comune è un'assunzione del modello, non una proprietà garantita dei dati.\n8. Nei disegni appaiati l'unità di analisi è la differenza entro persona, oppure l'intera traiettoria in un modello multilivello.\n9. Errore di misurazione e affidabilità influenzano le differenze standardizzate.\n10. Una differenza osservata tra gruppi non identifica automaticamente un effetto causale.\n\n::: {.callout-important title=\"Esercizi\" collapse=\"true\"}\n\n### 1. Interpretare la codifica dummy\n\nNel modello\n\n$$\nY_i\\sim\\operatorname{Normal}(70+8x_i,12),\n$$\n\n$x_i=0$ identifica il gruppo A e $x_i=1$ il gruppo B. Interpreta $\\mu_A$, $\\mu_B$, $\\Delta$ e $\\sigma$.\n\n### 2. Cambiare il gruppo di riferimento\n\nInverti il gruppo di riferimento in `kidiq` e adatta nuovamente il modello. Verifica come cambiano intercetta e coefficiente e come rimangono invariate le medie dei gruppi e la differenza «Diplomata meno Non diplomata» opportunamente ricostruita.\n\n### 3. Codifica centrata\n\nCrea un indicatore con valori $-0.5$ e $0.5$. Adatta il modello e verifica che l'intercetta corrisponda al punto medio delle due medie, mentre la pendenza coincide con la differenza.\n\n### 4. Medie di cella\n\nAdatta il modello `kid_score ~ 0 + mom_hs`. Estrai i due coefficienti e costruisci $\\Delta$ per ogni draw. Confronta la posterior ottenuta con quella del modello dummy.\n\n### 5. Soglia sostantiva\n\nCalcola $\\Pr(\\Delta>2\\mid y)$, $\\Pr(\\Delta>5\\mid y)$ e $\\Pr(\\Delta>10\\mid y)$. Spiega perché le tre probabilità non rappresentano analisi in competizione, ma risposte a soglie sostantive differenti.\n\n### 6. Differenza grezza e standardizzata\n\nImmagina due popolazioni con la stessa differenza $\\Delta=5$, ma deviazioni standard rispettivamente pari a 5 e 20. Calcola $d$ in entrambi i casi e discuti perché il significato pratico della differenza grezza può essere identico mentre la misura standardizzata cambia.\n\n### 7. Varianze diverse\n\nSupponi che il grafico mostri una dispersione molto maggiore nel gruppo «Diplomata». Quale assunzione del modello base è messa in discussione? Descrivi come cambieresti la specificazione e perché un unico $d=\\Delta/\\sigma$ diventerebbe ambiguo.\n\n### 8. Dati appaiati\n\nPer cinque partecipanti, i punteggi pre sono `20, 18, 25, 21, 16` e i punteggi post sono `15, 17, 19, 18, 14`. Calcola le differenze `pre - post`, la loro media e la loro deviazione standard. Spiega quale parametro stimeresti con `diff ~ 1`.\n\n### 9. Criticare il linguaggio causale\n\nRiscrivi in modo descrittivo la frase:\n\n> Il diploma materno aumenta il QI dei figli di otto punti.\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Tracce di soluzione\"}\n1. $\\mu_A=70$, $\\mu_B=78$, $\\Delta=8$ e $\\sigma=12$ descrive la dispersione comune attorno alle due medie.\n2. Con il gruppo B come riferimento, l'intercetta stima $\\mu_B$ e il coefficiente diventa $\\mu_A-\\mu_B=-\\Delta$. Le quantità sostantive non cambiano.\n3. Con $-0.5$ e $0.5$, l'intercetta è $(\\mu_A+\\mu_B)/2$ e la pendenza è ancora $\\mu_B-\\mu_A$.\n4. I coefficienti sono direttamente le due medie; il contrasto si ottiene sottraendo, draw per draw, il coefficiente del gruppo di riferimento da quello del confronto.\n5. Aumentando la soglia, la probabilità di superarla non può aumentare. La scelta della soglia dipende dal significato pratico, non dai dati osservati.\n6. I valori sono 1 e 0.25. La standardizzazione incorpora l'eterogeneità della popolazione; per questo non sostituisce l'interpretazione della scala originale.\n7. È messa in discussione l'omoschedasticità. Si può modellare `sigma` in funzione del gruppo. Con due dispersioni, occorre dichiarare quale deviazione standard viene usata per standardizzare.\n8. Le differenze sono `5, 1, 6, 3, 2`. Il modello a sola intercetta stima la media della distribuzione delle differenze e la loro dispersione.\n9. Una formulazione compatibile con i dati osservazionali è: «Nel campione analizzato, i figli di madri diplomate presentano in media un punteggio di QI superiore di circa otto punti rispetto ai figli di madri non diplomate».\n:::\n\n::: {.callout-note collapse=true title=\"Informazioni sull'ambiente di sviluppo\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.5.2\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] readxl_1.5.0          cmdstanr_0.9.0        bayestestR_0.18.1    \n#>  [4] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [7] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#> [10] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [13] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [16] loo_2.10.0            rstan_2.32.7          StanHeaders_2.32.10  \n#> [19] brms_2.23.0           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [22] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [25] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [28] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] gridExtra_2.3.1       inline_0.3.21         rlang_1.3.0          \n#>  [4] magrittr_2.0.5        snakecase_0.11.1      otel_0.2.0           \n#>  [7] compiler_4.6.1        reshape2_1.4.5        vctrs_0.7.3          \n#> [10] stringr_1.6.0         pkgconfig_2.0.3       arrayhelpers_1.1-1   \n#> [13] fastmap_1.2.0         backports_1.5.1       labeling_0.4.3       \n#> [16] utf8_1.2.6            rmarkdown_2.31        tzdb_0.5.0           \n#> [19] ps_1.9.3              haven_2.5.5           purrr_1.2.2          \n#> [22] xfun_0.60             cachem_1.1.0          jsonlite_2.0.0       \n#> [25] broom_1.0.13          parallel_4.6.1        R6_2.6.1             \n#> [28] stringi_1.8.7         RColorBrewer_1.1-3    lubridate_1.9.5      \n#> [31] cellranger_1.1.0      estimability_2.0.0    knitr_1.51           \n#> [34] pacman_0.5.1          R.utils_2.13.0        readr_2.2.0          \n#> [37] Matrix_1.7-5          timechange_0.4.0      tidyselect_1.2.1     \n#> [40] abind_1.4-8           yaml_2.3.12           codetools_0.2-20     \n#> [43] curl_7.1.0            processx_3.9.0        pkgbuild_1.4.8       \n#> [46] plyr_1.8.9            lattice_0.22-9        bridgesampling_1.2-1 \n#> [49] S7_0.2.2              coda_0.19-4.1         evaluate_1.0.5       \n#> [52] RcppParallel_5.1.11-2 pillar_1.11.1         tensorA_0.36.2.1     \n#> [55] checkmate_2.3.4       stats4_4.6.1          insight_1.5.2        \n#> [58] distributional_0.8.1  generics_0.1.4        rprojroot_2.1.1      \n#> [61] hms_1.1.4             rstantools_2.6.0      scales_1.4.0         \n#> [64] xtable_1.8-8          glue_1.8.1            emmeans_2.0.4        \n#> [67] tools_4.6.1           data.table_1.18.4     forcats_1.0.1        \n#> [70] mvtnorm_1.4-2         grid_4.6.1            QuickJSR_1.10.0      \n#> [73] nlme_3.1-170          cli_3.6.6             textshaping_1.0.5    \n#> [76] svUnit_1.0.8          Brobdingnag_1.2-9     V8_8.2.0             \n#> [79] gtable_0.3.6          R.methodsS3_1.8.2     digest_0.6.39        \n#> [82] farver_2.1.2          memoise_2.0.1         htmltools_0.5.9      \n#> [85] R.oo_1.27.1           lifecycle_1.0.5\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n\n<!--\nNote per l'integrazione editoriale:\n- il titolo di sezione conserva l'identificatore #sec-linear-models-two-groups;\n- la sezione sulla standardizzazione conserva #sec-bayesian-effect-size, così i riferimenti ai due capitoli originari rimangono validi;\n- verificare il nome della colonna `CESS-D` nel file Tarrats-Pons.xlsx;\n- verificare che theme_manuscript() sia disponibile in code/_common.R;\n- dopo la revisione dell'indice, aggiornare eventuali riferimenti al capitolo successivo sull'ANOVA;\n- nel capitolo sull'errore di misurazione mantenere il riferimento #sec-meas-error-regr.\n-->\n",
    "supporting": [
      "06_due_gruppi_rilevanza_pratica_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}