<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Approfondimenti, implementazioni riproducibili e materiali integrativi associati al manuale Inferenza bayesiana in psicologia: Ragionare con l’incertezza.">
<title>27&nbsp; Due gruppi: codifiche, differenze e rilevanza pratica – Ragionare con l'incertezza</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/modelli/07_piu_gruppi_contrasti_anova.html" rel="next">
<link href="../../chapters/modelli/05_inferenza_su_una_media.html" rel="prev">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-852af3d06ec72eeb83abe568abde0a2c.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-ad70a6f0db1617724bec401cc1948888.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-852af3d06ec72eeb83abe568abde0a2c.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c5da18ce6443f6e523d776c3a4a48f1a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-d8e094ca8ba168f48cf7d0e2354bdb1d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-c5da18ce6443f6e523d776c3a4a48f1a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": true,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QT5S3P9D31"></script><script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QT5S3P9D31', { 'anonymize_ip': true});
</script><script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"headline",
  "consent_type":"express",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"it"
  });
});
</script><style>html{ scroll-behavior: smooth; }</style>
<link href="../../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../../site_libs/pagedtable-1.1/js/pagedtable.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
<meta property="og:title" content="27&nbsp; Due gruppi: codifiche, differenze e rilevanza pratica – Ragionare con l’incertezza">
<meta property="og:description" content="Approfondimenti, implementazioni riproducibili e materiali integrativi associati al manuale Inferenza bayesiana in psicologia: Ragionare con l’incertezza.">
<meta property="og:image" content="https://ccaudek.github.io/utet-companion/chapters/modelli/06_due_gruppi_rilevanza_pratica_files/figure-html/fig-kidiq-two-groups-1.png">
<meta property="og:site_name" content="Ragionare con l’incertezza">
<meta property="og:image:height" content="1297">
<meta property="og:image:width" content="2100">
<meta name="twitter:title" content="27&nbsp; Due gruppi: codifiche, differenze e rilevanza pratica – Ragionare con l’incertezza">
<meta name="twitter:description" content="Approfondimenti, implementazioni riproducibili e materiali integrativi associati al manuale Inferenza bayesiana in psicologia: Ragionare con l’incertezza.">
<meta name="twitter:image" content="https://ccaudek.github.io/utet-companion/chapters/modelli/06_due_gruppi_rilevanza_pratica_files/figure-html/fig-kidiq-two-groups-1.png">
<meta name="twitter:image-height" content="1297">
<meta name="twitter:image-width" content="2100">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://ccaudek.github.io/utet-companion/chapters/modelli/06_due_gruppi_rilevanza_pratica.html">
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/modelli/_intro_sec_regression.html">Modelli</a></li><li class="breadcrumb-item"><a href="../../chapters/modelli/06_due_gruppi_rilevanza_pratica.html"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Due gruppi: codifiche, differenze e rilevanza pratica</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Attiva/disattiva la barra laterale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Ricerca" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Ragionare con l’incertezza</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="../../guida-al-manuale.html" title="Guida al manuale" class="quarto-navigation-tool px-1" aria-label="Guida al manuale"><i class="bi bi-book"></i></a>
    <a href="https://github.com/ccaudek/utet-companion/" title="Eseguire il codice" class="quarto-navigation-tool px-1" aria-label="Eseguire il codice"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Attiva/disattiva la modalità oscura"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Attiva/disattiva la modalità lettore">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
    <div id="quarto-search" class="quarto-navigation-tool px-1" title="Ricerca"></div>
</div>
    </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Inferenza bayesiana in psicologia</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guida-al-manuale.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Guida al manuale</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Crisi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/crisi/_intro_sec_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dove comincia il percorso</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/crisi/01_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">La crisi della replicabilità: come un sistema produce evidenze fragili</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/crisi/conclusions_sec_crisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della Parte Crisi</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Diagnosi</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/diagnosi/_intro_sec_limits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dove siamo nel percorso</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/diagnosi/01_limits_stat_freq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Limiti dell’inferenza frequentista: un laboratorio computazionale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/diagnosi/02_effect_size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">La dimensione dell’effetto: un laboratorio computazionale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/diagnosi/03_s_m_errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Errori di segno e di grandezza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/diagnosi/04_p_values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">La fragilità del valore-<span class="math inline">\(p\)</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/diagnosi/05_degrees_of_freedom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">I gradi di libertà del ricercatore</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/diagnosi/conclusions_sec_limits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della Parte Diagnosi</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Svolta</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/svolta/_intro_sec_bayesian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dove siamo nel percorso</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/svolta/00_epistemological_foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Fondamenti epistemologici dell’inferenza bayesiana</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/svolta/01_grid_approx.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Quantificare e aggiornare l’incertezza con l’approssimazione su griglia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/svolta/02_conjugate_families.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Il modello Beta-Binomiale: capire la coniugazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/svolta/03_summary_posterior.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Comprendere e comunicare la distribuzione a posteriori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/svolta/04_balance_prior_post.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">L’equilibrio tra prior e verosimiglianza</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/svolta/05_prior_pred_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Distribuzione predittiva a priori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/svolta/06_post_pred_distr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Distribuzione predittiva a posteriori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/svolta/07_singolo_paziente.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Oltre il cut-off: inferenza bayesiana sul singolo paziente</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/svolta/conclusions_sec_bayesian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della Parte Svolta</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Calcolo</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/calcolo/_intro_sec_stan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dove siamo nel percorso</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/calcolo/01_metropolis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Campionare invece di risolvere: l’intuizione dell’algoritmo di Metropolis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/calcolo/02_ppl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Linguaggi di programmazione probabilistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/calcolo/03_stan_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Stan: leggere un modello bayesiano</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/calcolo/04_stan_odds_ratio_stan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Odds ratio in Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/calcolo/05_stan_two_means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Confrontare due medie con Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/calcolo/06_bayesian_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Flusso di lavoro bayesiano</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/calcolo/conclusions_sec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della Parte Calcolo</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Modelli</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/modelli/_intro_sec_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dove siamo nel percorso</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/modelli/01_modello_lineare_generativo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Il modello lineare come modello generativo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/modelli/02_regressione_verso_media.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Regressione verso la media: che cosa predice una retta</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/modelli/03_regressione_bayesiana_brms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Regressione bayesiana con <code>brms</code>: il workflow completo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/modelli/04_dalla_formula_al_programma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Regressione multipla: dalla formula al programma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/modelli/05_inferenza_su_una_media.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Inferenza su una media: il modello a sola intercetta</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/modelli/06_due_gruppi_rilevanza_pratica.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Due gruppi: codifiche, differenze e rilevanza pratica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/modelli/07_piu_gruppi_contrasti_anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Più gruppi: medie di cella, contrasti e ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/modelli/08_modelli_multilivello_partial_pooling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Modelli multilivello: eterogeneità e partial pooling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/modelli/09_quando_il_modello_sbaglia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Quando il modello sbaglia: controllo e revisione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/modelli/10_associazione_previsione_effetto_causale.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Associazione, previsione ed effetto causale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/modelli/conclusions_sec_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della Parte Modelli</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Causalità</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/causalita/_intro_sec_causality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dove siamo nel percorso</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/causalita/01_specification_error.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Dal bias da variabile omessa al problema dell’identificazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/causalita/02_propedeutic_causality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Definire un effetto causale: interventi, controfattuali ed estimand</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/causalita/03_causality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Identificare effetti causali nei dati osservazionali</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/causalita/conclusions_sec_causality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della Parte <em>Causalità</em></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Estensioni</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/estensioni/_intro_sec_glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dove siamo nel percorso</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/estensioni/01_glm_modello_osservazionale.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Oltre il modello gaussiano: il GLM come modello osservazionale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/estensioni/02_conteggi_distribuzione_ipotesi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Quando la distribuzione è un’ipotesi: conteggi, Poisson e revisione del modello</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/estensioni/03_quando_ordine_contiene_informazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Quando l’ordine contiene informazione: dal GLM statico al modello dinamico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/estensioni/conclusions_sec_glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della Parte <em>Estensioni</em></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Applicazione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/applicazione/_intro_sec_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dove siamo nel percorso</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/applicazione/01_dalla_descrizione_alla_spiegazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Dalla descrizione alla spiegazione: che cosa richiede un modello del processo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/applicazione/02_costruire_modello_dinamico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Dalla teoria verbale alla teoria eseguibile: costruire un modello dinamico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/applicazione/03_rescorla_wagner.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Rescorla–Wagner: una teoria processuale messa alla prova</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/applicazione/04_eterogeneita_modelli_dinamici.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Lo stesso meccanismo per tutti? Eterogeneità e generalizzazione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/applicazione/05_decisione_ottimale.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Dalla previsione causale all’azione: decisione, utilità e conseguenze</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/applicazione/conclusions_sec_applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della Parte Applicazione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Valutazione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/valutazione/_intro_sec_entropy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dove siamo nel percorso</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/valutazione/01_entropy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Sorpresa e incertezza: il linguaggio della previsione probabilistica</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/valutazione/02_kl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Dalla sorpresa al confronto: entropia incrociata e divergenza KL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/valutazione/03_valutare_modelli_bayesiani.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Valutare i modelli bayesiani: ELPD, LOO e critica predittiva</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/valutazione/04_generalizzazione.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Generalizzare a che cosa? Dalle osservazioni ai nuovi studi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/valutazione/conclusions_sec_entropy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Riflessioni conclusive della Parte Valutazione</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">Visione</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/visione/_intro_sec_epilogue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dove siamo arrivati</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/visione/01_changes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Riforma</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/visione/02_integrity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Integrità della ricerca</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/visione/03_epilogue.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Epilogo</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendici</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false">
 <span class="menu-text">Orientamento</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a00_glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Glossario operativo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a60_bayesian_workflow_checklist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Checklist del workflow bayesiano</span></span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Richiami matematici e notazionali</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a11_numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Sistemi numerici e intervalli</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a12_sum_notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Sommatorie</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a13_sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Insiemi e operazioni insiemistiche</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a14_combinatorics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Calcolo combinatorio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a15_calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">Introduzione agli integrali</span></span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false">
 <span class="menu-text">Ambiente computazionale e Stan</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a40_troubleshooting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">H</span>&nbsp; <span class="chapter-title">Problemi comuni con R, Stan e CmdStanR</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a41_install_cmdstan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">I</span>&nbsp; <span class="chapter-title">Come installare CmdStan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a42_cmdstanr_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">J</span>&nbsp; <span class="chapter-title">Implementazione di modelli bayesiani con Stan tramite <code>cmdstanr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a43_stan_lang.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">K</span>&nbsp; <span class="chapter-title">Introduzione al linguaggio Stan</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a44_stan_diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">L</span>&nbsp; <span class="chapter-title">Diagnostica delle catene MCMC</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a45_stan_prior-predictive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">M</span>&nbsp; <span class="chapter-title">Controlli predittivi a priori</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a46_stan_posterior_predictive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">N</span>&nbsp; <span class="chapter-title">Controlli predittivi a posteriori</span></span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false">
 <span class="menu-text">Approfondimenti sui modelli</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="false" aria-label="Attiva/disattiva sezione">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a50_lin_fun.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">O</span>&nbsp; <span class="chapter-title">La funzione lineare</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a51_matrix_algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">P</span>&nbsp; <span class="chapter-title">Algebra delle matrici per la regressione</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a52_reglin_frequentist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">Q</span>&nbsp; <span class="chapter-title">La regressione lineare bivariata: prospettiva frequentista</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a53_regression_likelihood.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">R</span>&nbsp; <span class="chapter-title">Derivazione della log-verosimiglianza nella regressione lineare</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/appendix/a54_errore_misurazione_varianza_metodo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">S</span>&nbsp; <span class="chapter-title">Errore di misurazione e varianza di metodo</span></span></a>
  </div>
</li>
      </ul>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2"><h2 id="toc-title">Sommario</h2>
   
  <ul class="collapse">
<li><a href="#dalla-domanda-scientifica-alle-quantit%C3%A0-di-interesse" id="toc-dalla-domanda-scientifica-alle-quantità-di-interesse" class="nav-link active" data-scroll-target="#dalla-domanda-scientifica-alle-quantit%C3%A0-di-interesse"><span class="header-section-number">27.1</span> Dalla domanda scientifica alle quantità di interesse</a></li>
  <li><a href="#esplorare-i-due-gruppi" id="toc-esplorare-i-due-gruppi" class="nav-link" data-scroll-target="#esplorare-i-due-gruppi"><span class="header-section-number">27.2</span> Esplorare i due gruppi</a></li>
  <li><a href="#da-una-media-a-due-medie" id="toc-da-una-media-a-due-medie" class="nav-link" data-scroll-target="#da-una-media-a-due-medie"><span class="header-section-number">27.3</span> Da una media a due medie</a></li>
  <li><a href="#tre-parametrizzazioni-dello-stesso-confronto" id="toc-tre-parametrizzazioni-dello-stesso-confronto" class="nav-link" data-scroll-target="#tre-parametrizzazioni-dello-stesso-confronto"><span class="header-section-number">27.4</span> Tre parametrizzazioni dello stesso confronto</a></li>
  <li><a href="#specificare-il-modello-bayesiano" id="toc-specificare-il-modello-bayesiano" class="nav-link" data-scroll-target="#specificare-il-modello-bayesiano"><span class="header-section-number">27.5</span> Specificare il modello bayesiano</a></li>
  <li><a href="#adattare-il-modello" id="toc-adattare-il-modello" class="nav-link" data-scroll-target="#adattare-il-modello"><span class="header-section-number">27.6</span> Adattare il modello</a></li>
  <li><a href="#dal-modello-alla-domanda-di-ricerca" id="toc-dal-modello-alla-domanda-di-ricerca" class="nav-link" data-scroll-target="#dal-modello-alla-domanda-di-ricerca"><span class="header-section-number">27.7</span> Dal modello alla domanda di ricerca</a></li>
  <li><a href="#dai-coefficienti-alle-quantit%C3%A0-di-interesse" id="toc-dai-coefficienti-alle-quantità-di-interesse" class="nav-link" data-scroll-target="#dai-coefficienti-alle-quantit%C3%A0-di-interesse"><span class="header-section-number">27.8</span> Dai coefficienti alle quantità di interesse</a></li>
  <li><a href="#direzione-grandezza-e-rilevanza-pratica" id="toc-direzione-grandezza-e-rilevanza-pratica" class="nav-link" data-scroll-target="#direzione-grandezza-e-rilevanza-pratica"><span class="header-section-number">27.9</span> Direzione, grandezza e rilevanza pratica</a></li>
  <li><a href="#sec-bayesian-effect-size" id="toc-sec-bayesian-effect-size" class="nav-link" data-scroll-target="#sec-bayesian-effect-size"><span class="header-section-number">27.10</span> La differenza standardizzata è una quantità secondaria</a></li>
  <li><a href="#controllare-il-modello-nei-due-gruppi" id="toc-controllare-il-modello-nei-due-gruppi" class="nav-link" data-scroll-target="#controllare-il-modello-nei-due-gruppi"><span class="header-section-number">27.11</span> Controllare il modello nei due gruppi</a></li>
  <li><a href="#comunicare-i-risultati" id="toc-comunicare-i-risultati" class="nav-link" data-scroll-target="#comunicare-i-risultati"><span class="header-section-number">27.12</span> Comunicare i risultati</a></li>
  <li><a href="#errori-comuni" id="toc-errori-comuni" class="nav-link" data-scroll-target="#errori-comuni"><span class="header-section-number">27.13</span> Errori comuni</a></li>
  </ul><div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/ccaudek/utet-companion/issues/new" class="toc-action"><i class="bi bi-github"></i>Segnala un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/modelli/_intro_sec_regression.html">Modelli</a></li><li class="breadcrumb-item"><a href="../../chapters/modelli/06_due_gruppi_rilevanza_pratica.html"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Due gruppi: codifiche, differenze e rilevanza pratica</span></a></li></ol></nav><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-linear-models-two-groups" class="quarto-section-identifier"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Due gruppi: codifiche, differenze e rilevanza pratica</span></span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Codice</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Mostra il codice</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Nascondere il codice</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>Nel capitolo precedente abbiamo visto che stimare una sola media equivale ad adattare il modello lineare più semplice, <code>y ~ 1</code>. Il confronto tra due gruppi costituisce il passo successivo: aggiungiamo un predittore categoriale che indica a quale gruppo appartiene ciascuna osservazione.</p>
<p>La logica del modello non cambia. Cambia la struttura della media condizionata. Invece di una sola media, il modello deve rappresentarne due e, soprattutto, la loro differenza:</p>
<p><span class="math display">\[
\Delta = \mu_1 - \mu_0.
\]</span></p>
<p>Questo passaggio è importante perché mostra una proprietà generale del modello lineare: <strong>le procedure tradizionalmente presentate come analisi distinte possono essere ricondotte alla stessa grammatica di formule, matrici del modello e quantità derivate</strong>. Con due gruppi, la codifica determina il significato immediato dei coefficienti, mentre le quantità sostantive, ovvero le due medie e il loro contrasto, rimangono il vero oggetto dell’inferenza.</p>
<p>L’obiettivo del capitolo non è quindi imparare un nuovo “test”, ma capire come rappresentare un confronto tra gruppi, come tradurre i coefficienti in quantità scientificamente rilevanti e come distinguere una differenza statisticamente plausibile da una differenza importante dal punto di vista sostantivo.</p>
</div>
</div>
</div>
<div class="chapter-status callout callout-style-simple callout-important no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Da sapere.</strong> Il confronto tra due gruppi è un modello lineare con un predittore categoriale a due livelli. Codifiche diverse possono attribuire significati diversi ai coefficienti, ma descrivono le stesse medie di gruppo e lo stesso contrasto quando il modello e i prior sono specificati in modo coerente. La differenza grezza <span class="math inline">\(\Delta\)</span> è la quantità principale; la differenza standardizzata <span class="math inline">\(d\)</span> è una quantità derivata utile soprattutto per confronti tra studi. Una differenza osservazionale non identifica, da sola, un effetto causale.</p>
<p><strong>Da saper fare.</strong> Passare da <code>y ~ 1</code> a <code>y ~ gruppo</code>; leggere la matrice del modello per una variabile categoriale; ricostruire le medie dei gruppi e il contrasto indipendentemente dalla parametrizzazione; specificare e adattare con <code>brms</code> un modello gaussiano per due gruppi; calcolare probabilità a posteriori sulla direzione e su una soglia sostantiva; distinguere differenza grezza, differenza standardizzata e variabilità individuale; eseguire un controllo predittivo separato per gruppo.</p>
<p><strong>Approfondimento facoltativo.</strong> La codifica centrata, i modelli con dispersioni diverse, le verosimiglianze robuste e i disegni appaiati possono essere rimandati. Nel percorso essenziale è sufficiente comprendere la relazione tra codifica, medie e contrasto e saper interpretare l’incertezza sulla differenza.</p>
</div>
</div>
</div>
<p><a href="../../guida-al-manuale.html#sec-percorsi-lettura">Che cosa significano queste etichette?</a></p>
<div class="callout callout-style-default callout-tip callout-titled" title="Prerequisiti">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Prerequisiti
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Il modello a sola intercetta è discusso nell’<a href="#sec-mcmc-one-mean" class="quarto-xref"><span class="quarto-unresolved-ref">sec-mcmc-one-mean</span></a>.</li>
<li>La relazione tra formula R e matrice del modello è introdotta nell’<a href="#sec-linar-models-brms" class="quarto-xref"><span class="quarto-unresolved-ref">sec-linar-models-brms</span></a>.</li>
<li>Il workflow bayesiano completo con <code>brms</code> è presentato nell’<a href="#sec-linmod-bayesian-reg" class="quarto-xref"><span class="quarto-unresolved-ref">sec-linmod-bayesian-reg</span></a>.</li>
<li>Per la trattazione frequentista del test <span class="math inline">\(t\)</span> per campioni indipendenti si veda il modulo <a href="https://ccaudek.github.io/utet-frequentista">utet-frequentista</a>.</li>
<li>L’esempio sul QI è tratto da <span class="citation" data-cites="gelman2021regression">Gelman et al. (<a href="#ref-gelman2021regression" role="doc-biblioref">2021</a>)</span>.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-empty-content callout-titled" title="Preparazione del notebook">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Attenzione</span>Preparazione del notebook
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">

</div>
</div>
</div>
<section id="dalla-domanda-scientifica-alle-quantità-di-interesse" class="level2" data-number="27.1"><h2 data-number="27.1" class="anchored" data-anchor-id="dalla-domanda-scientifica-alle-quantità-di-interesse">
<span class="header-section-number">27.1</span> Dalla domanda scientifica alle quantità di interesse</h2>
<p>Come illustrazione, utilizziamo il dataset <code>kidiq</code>, che contiene informazioni sullo sviluppo cognitivo di un campione di bambini e su alcune caratteristiche familiari <span class="citation" data-cites="gelman2021regression">(<a href="#ref-gelman2021regression" role="doc-biblioref">Gelman et al., 2021</a>)</span>. Ci concentriamo su:</p>
<ul>
<li>
<code>kid_score</code>: il punteggio del bambino in un test di sviluppo cognitivo;</li>
<li>
<code>mom_hs</code>: un indicatore del conseguimento del diploma di scuola superiore da parte della madre.</li>
</ul>
<p>La domanda è di tipo descrittivo:</p>
<blockquote class="blockquote">
<p>Di quanto differiscono, in media, i punteggi cognitivi dei bambini nei due gruppi definiti dal livello di istruzione della madre?</p>
</blockquote>
<p>Indichiamo con <span class="math inline">\(\mu_0\)</span> la media del gruppo “Non diplomata” e con <span class="math inline">\(\mu_1\)</span> la media del gruppo “Diplomata”. La quantità principale è il contrasto</p>
<p><span class="math display">\[
\Delta = \mu_1 - \mu_0.
\]</span></p>
<p>Il segno di <span class="math inline">\(\Delta\)</span> indica la direzione della differenza, mentre il suo valore assoluto conserva l’unità di misura originaria del punteggio. Possiamo inoltre considerare, come quantità secondaria,</p>
<p><span class="math display">\[
d = \frac{\Delta}{\sigma},
\]</span> dove <span class="math inline">\(\sigma\)</span> è la deviazione standard residua comune assunta dal modello.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Prima la quantità scientifica, poi la codifica">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Prima la quantità scientifica, poi la codifica
</div>
</div>
<div class="callout-body-container callout-body">
<p>La domanda sostantiva riguarda <span class="math inline">\(\mu_0\)</span>, <span class="math inline">\(\mu_1\)</span> e soprattutto <span class="math inline">\(\Delta\)</span>. I coefficienti prodotti dal software sono coordinate utili per rappresentare queste quantità, ma il loro significato dipende dalla codifica scelta. Separare le <strong>quantità di interesse</strong> dai <strong>coefficienti della parametrizzazione</strong> evita molte confusioni quando il modello diventa più complesso.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Una differenza tra gruppi non è automaticamente causale">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Avviso</span>Una differenza tra gruppi non è automaticamente causale
</div>
</div>
<div class="callout-body-container callout-body">
<p>Il livello di istruzione materna è osservato, non assegnato sperimentalmente. Il contrasto <span class="math inline">\(\Delta\)</span> esprime quindi la differenza tra i valori attesi dell’outcome nei due gruppi nella popolazione rappresentata dal campione. Si tratta di una <strong>descrizione condizionata</strong>: quantifica quanto i due gruppi differiscono in media, ma non spiega il perché.</p>
<p>Attribuire a <span class="math inline">\(\Delta\)</span> un significato causale, per esempio interpretandolo come l’effetto del conseguimento del diploma, richiederebbe ulteriori assunzioni di identificazione: come un disegno che controlli i fattori confondenti o un modello causale esplicito che giustifichi l’aggiustamento per le variabili rilevanti. Il modello di regressione, da solo, non fornisce queste condizioni. La stima di <span class="math inline">\(\Delta\)</span> è una stima della differenza; la sua interpretazione causale è una questione che va oltre la procedura statistica.</p>
</div>
</div>
</section><section id="esplorare-i-due-gruppi" class="level2" data-number="27.2"><h2 data-number="27.2" class="anchored" data-anchor-id="esplorare-i-due-gruppi">
<span class="header-section-number">27.2</span> Esplorare i due gruppi</h2>
<p>Carichiamo i dati e rendiamo esplicito l’ordine dei livelli del fattore. Il primo livello sarà il riferimento nella codifica standard di R.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">kidiq</span> <span class="op">&lt;-</span> <span class="fu">rio</span><span class="fu">::</span><span class="fu"><a href="http://gesistsa.github.io/rio/reference/import.html">import</a></span><span class="op">(</span></span>
<span>  <span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"data"</span>, <span class="st">"kidiq.dta"</span><span class="op">)</span></span>
<span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">transmute</span><span class="op">(</span></span>
<span>    <span class="va">kid_score</span>,</span>
<span>    mom_hs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span></span>
<span>      <span class="va">mom_hs</span>,</span>
<span>      levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span>,</span>
<span>      labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Non diplomata"</span>, <span class="st">"Diplomata"</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">drop_na</span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">kidiq</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">mom_hs</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">summarise</span><span class="op">(</span></span>
<span>    n        <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span>,</span>
<span>    media_QI <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">kid_score</span><span class="op">)</span>,</span>
<span>    sd_QI    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">kid_score</span><span class="op">)</span>,</span>
<span>    .groups  <span class="op">=</span> <span class="st">"drop"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["mom_hs"],"name":[1],"type":["fct"],"align":["left"]},{"label":["n"],"name":[2],"type":["int"],"align":["right"]},{"label":["media_QI"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["sd_QI"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"Non diplomata","2":"93","3":"77.5","4":"22.6"},{"1":"Diplomata","2":"341","3":"89.3","4":"19.0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Le statistiche descrittive suggeriscono la posizione dei due gruppi, ma non mostrano da sole la variabilità interna e la sovrapposizione tra le distribuzioni.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">kidiq</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">mom_hs</span>, y <span class="op">=</span> <span class="va">kid_score</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_violin</span><span class="op">(</span>trim <span class="op">=</span> <span class="cn">FALSE</span>, alpha <span class="op">=</span> <span class="fl">0.4</span>, fill <span class="op">=</span> <span class="st">"grey80"</span>, color <span class="op">=</span> <span class="st">"grey50"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_boxplot</span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.12</span>, outlier.shape <span class="op">=</span> <span class="cn">NA</span>, alpha <span class="op">=</span> <span class="fl">0.7</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_jitter</span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.08</span>, alpha <span class="op">=</span> <span class="fl">0.25</span>, size <span class="op">=</span> <span class="fl">1.2</span>, color <span class="op">=</span> <span class="st">"grey30"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="st">"Istruzione materna"</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Punteggio cognitivo del bambino"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-kidiq-two-groups" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-kidiq-two-groups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06_due_gruppi_rilevanza_pratica_files/figure-html/fig-kidiq-two-groups-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figura&nbsp;27.1: Distribuzione dei punteggi cognitivi nei due gruppi definiti dall’istruzione materna. Una differenza tra le medie può coesistere con una considerevole sovrapposizione tra le osservazioni individuali."><img src="06_due_gruppi_rilevanza_pratica_files/figure-html/fig-kidiq-two-groups-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kidiq-two-groups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;27.1: Distribuzione dei punteggi cognitivi nei due gruppi definiti dall’istruzione materna. Una differenza tra le medie può coesistere con una considerevole sovrapposizione tra le osservazioni individuali.
</figcaption></figure>
</div>
</div>
</div>
<p>Il grafico anticipa una distinzione che accompagnerà tutto il capitolo: <strong>differenza tra le medie</strong> e <strong>variabilità tra individui</strong> sono aspetti diversi. Il modello deve rappresentarli separatamente.</p>
</section><section id="da-una-media-a-due-medie" class="level2" data-number="27.3"><h2 data-number="27.3" class="anchored" data-anchor-id="da-una-media-a-due-medie">
<span class="header-section-number">27.3</span> Da una media a due medie</h2>
<p>Nel capitolo precedente, la formula</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">kid_score</span> <span class="op">~</span> <span class="fl">1</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<p>produceva una matrice del modello con una sola colonna di <span class="math inline">\(1\)</span>, corrispondente a un unico parametro di media. Aggiungendo il fattore <code>mom_hs</code>,</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">kid_score</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> <span class="va">mom_hs</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<p>R costruisce una seconda colonna che codifica l’appartenenza al gruppo non di riferimento. Per default, R utilizza la <strong>codifica dummy</strong> (nota anche come <em>treatment coding</em>): il primo livello del fattore (in ordine alfabetico o secondo i livelli specificati) diventa il gruppo di riferimento e viene rappresentato da 0; gli altri livelli vengono rappresentati da 1.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">X_dummy</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/model.matrix.html">model.matrix</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span> <span class="va">mom_hs</span>,</span>
<span>  data <span class="op">=</span> <span class="va">kidiq</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">X_dummy</span><span class="op">)</span></span>
<span><span class="co">#&gt;   (Intercept) mom_hsDiplomata</span></span>
<span><span class="co">#&gt; 1           1               1</span></span>
<span><span class="co">#&gt; 2           1               1</span></span>
<span><span class="co">#&gt; 3           1               1</span></span>
<span><span class="co">#&gt; 4           1               1</span></span>
<span><span class="co">#&gt; 5           1               1</span></span>
<span><span class="co">#&gt; 6           1               0</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Con questa codifica, la struttura delle righe della matrice è la seguente:</p>
<p><span class="math display">\[
\begin{array}{c|cc}
&amp; (\text{Intercept}) &amp; \text{mom\_hs}_{\text{Diplomata}} \\
\hline
\text{Non diplomata} &amp; 1 &amp; 0 \\
\text{Diplomata} &amp; 1 &amp; 1
\end{array}
\]</span></p>
<p>Il modello gaussiano si scrive quindi come</p>
<p><span id="eq-two-groups-dummy"><span class="math display">\[
\begin{aligned}
Y_i \mid x_i,\alpha,\beta,\sigma
&amp;\sim \operatorname{Normal}(\mu_i,\sigma), \\
\mu_i &amp;= \alpha + \beta x_i.
\end{aligned}
\tag{27.1}\]</span></span></p>
<p>Sostituendo i due possibili valori della variabile indicatrice <span class="math inline">\(x_i\)</span>:</p>
<p><span class="math display">\[
\mu_0 = \alpha, \qquad \mu_1 = \alpha + \beta.
\]</span></p>
<p>Ne consegue che</p>
<p><span class="math display">\[
\Delta = \mu_1 - \mu_0 = \beta.
\]</span></p>
<p>Con questa parametrizzazione, l’intercetta <span class="math inline">\(\alpha\)</span> rappresenta la media del gruppo di riferimento (le madri non diplomate), mentre il coefficiente <span class="math inline">\(\beta\)</span> corrisponde esattamente alla differenza tra le medie dei due gruppi (Diplomate meno Non diplomate). La stima di <span class="math inline">\(\beta\)</span> risponde quindi direttamente alla domanda sulla differenza attesa tra i due livelli di istruzione.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Il test $t$ come caso particolare del modello lineare">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Il test <span class="math inline">\(t\)</span> come caso particolare del modello lineare
</div>
</div>
<div class="callout-body-container callout-body">
<p>Il classico confronto tra due medie indipendenti, sotto l’ipotesi di varianza comune, può essere espresso come un modello lineare con un singolo predittore binario. L’obiettivo didattico non è rinominare una procedura familiare, ma riconoscere che <strong>una media, due medie e più medie appartengono alla stessa struttura modellistica</strong>: ciò che cambia è soltanto la matrice del modello.</p>
</div>
</div>
</section><section id="tre-parametrizzazioni-dello-stesso-confronto" class="level2" data-number="27.4"><h2 data-number="27.4" class="anchored" data-anchor-id="tre-parametrizzazioni-dello-stesso-confronto">
<span class="header-section-number">27.4</span> Tre parametrizzazioni dello stesso confronto</h2>
<p>Lo stesso sistema di due medie può essere rappresentato mediante coordinate diverse. Questo è uno dei passaggi più importanti del capitolo, perché prepara direttamente il passaggio ai modelli con più gruppi: <strong>la codifica modifica il significato immediato dei coefficienti, ma non modifica le medie di gruppo e i contrasti che costituiscono la domanda scientifica</strong>, purché anche i prior vengano trasformati in modo coerente.</p>
<p>Per fissare le idee, chiamiamo A il gruppo “Non diplomata” e B il gruppo “Diplomata”, con</p>
<p><span class="math display">\[
\mu_A = \mu_0,\qquad
\mu_B = \mu_1,\qquad
\Delta = \mu_B-\mu_A.
\]</span></p>
<p>Le tre parametrizzazioni più utili in questo percorso sono:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead><tr class="header">
<th>Parametrizzazione</th>
<th>Formula</th>
<th>Riga per A</th>
<th>Riga per B</th>
<th>Significato dei coefficienti</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Riferimento (dummy)</strong></td>
<td><code>y ~ 1 + gruppo</code></td>
<td><span class="math inline">\([1,0]\)</span></td>
<td><span class="math inline">\([1,1]\)</span></td>
<td>intercetta = <span class="math inline">\(\mu_A\)</span>; coefficiente = <span class="math inline">\(\Delta\)</span>
</td>
</tr>
<tr class="even">
<td><strong>Centrata</strong></td>
<td>
<code>y ~ 1 + x_c</code>, con <span class="math inline">\(x_c\in\{-0.5,0.5\}\)</span>
</td>
<td><span class="math inline">\([1,-0.5]\)</span></td>
<td><span class="math inline">\([1,0.5]\)</span></td>
<td>intercetta = <span class="math inline">\((\mu_A+\mu_B)/2\)</span>; coefficiente = <span class="math inline">\(\Delta\)</span>
</td>
</tr>
<tr class="odd">
<td><strong>Medie di cella</strong></td>
<td><code>y ~ 0 + gruppo</code></td>
<td><span class="math inline">\([1,0]\)</span></td>
<td><span class="math inline">\([0,1]\)</span></td>
<td>primo coefficiente = <span class="math inline">\(\mu_A\)</span>; secondo coefficiente = <span class="math inline">\(\mu_B\)</span>
</td>
</tr>
</tbody>
</table>
<p>La tabella mostra già il punto essenziale: <strong>le righe della matrice cambiano e, con esse, cambia il significato dei coefficienti</strong>. Le due medie e la loro differenza, invece, possono sempre essere ricostruite <span class="citation" data-cites="caudek2001statistica">(<a href="#ref-caudek2001statistica" role="doc-biblioref">Caudek &amp; Luccio, 2001</a>)</span>.</p>
<section id="parametrizzazione-1-gruppo-di-riferimento-dummy-coding" class="level3" data-number="27.4.1"><h3 data-number="27.4.1" class="anchored" data-anchor-id="parametrizzazione-1-gruppo-di-riferimento-dummy-coding">
<span class="header-section-number">27.4.1</span> Parametrizzazione 1: gruppo di riferimento (<em>dummy coding</em>)</h3>
<p>Con le impostazioni standard di R, un fattore utilizza normalmente una codifica a gruppo di riferimento. Nel nostro esempio:</p>
<p><span class="math display">\[
\mu_i=\alpha+\beta x_i,
\qquad
x_i=
\begin{cases}
0 &amp; \text{gruppo A},\\
1 &amp; \text{gruppo B}.
\end{cases}
\]</span></p>
<p>Sostituendo i due valori possibili di <span class="math inline">\(x_i\)</span>:</p>
<p><span class="math display">\[
\mu_A=\alpha,
\qquad
\mu_B=\alpha+\beta.
\]</span></p>
<p>Di conseguenza,</p>
<p><span class="math display">\[
\Delta=\mu_B-\mu_A=\beta.
\]</span></p>
<p>Questa parametrizzazione è particolarmente comoda quando uno dei gruppi costituisce un riferimento sostantivo naturale: l’intercetta ne rappresenta direttamente la media, mentre il coefficiente del fattore rappresenta lo scostamento del secondo gruppo rispetto al primo.</p>
</section><section id="parametrizzazione-2-codifica-centrata" class="level3" data-number="27.4.2"><h3 data-number="27.4.2" class="anchored" data-anchor-id="parametrizzazione-2-codifica-centrata">
<span class="header-section-number">27.4.2</span> Parametrizzazione 2: codifica centrata</h3>
<p>Possiamo trasformare l’indicatore <span class="math inline">\(0/1\)</span> sottraendo <span class="math inline">\(0.5\)</span>, ottenendo</p>
<p><span class="math display">\[
x_i^c=
\begin{cases}
-0.5 &amp; \text{gruppo A},\\
\phantom{-}0.5 &amp; \text{gruppo B}.
\end{cases}
\]</span></p>
<p>Il modello diventa</p>
<p><span class="math display">\[
\mu_i=\alpha_c+\beta_c x_i^c.
\]</span></p>
<p>Per i due gruppi:</p>
<p><span class="math display">\[
\mu_A=\alpha_c-\frac{\beta_c}{2},
\qquad
\mu_B=\alpha_c+\frac{\beta_c}{2}.
\]</span></p>
<p>Sommando e sottraendo queste due equazioni otteniamo:</p>
<p><span class="math display">\[
\alpha_c=\frac{\mu_A+\mu_B}{2},
\qquad
\beta_c=\mu_B-\mu_A=\Delta.
\]</span></p>
<p>L’intercetta non rappresenta quindi la media complessiva osservata nel campione, ma il <strong>punto medio non ponderato delle due medie di gruppo</strong>. Se i gruppi hanno numerosità diverse, questo valore non coincide in generale con la <em>grand mean</em> campionaria.</p>
<p>Possiamo vedere la codifica direttamente nella matrice del modello:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">kidiq_centered</span> <span class="op">&lt;-</span> <span class="va">kidiq</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span></span>
<span>    mom_hs_c <span class="op">=</span> <span class="fu">if_else</span><span class="op">(</span></span>
<span>      <span class="va">mom_hs</span> <span class="op">==</span> <span class="st">"Diplomata"</span>,</span>
<span>      <span class="fl">0.5</span>,</span>
<span>      <span class="op">-</span><span class="fl">0.5</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">X_centered</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/model.matrix.html">model.matrix</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span> <span class="va">mom_hs_c</span>,</span>
<span>  data <span class="op">=</span> <span class="va">kidiq_centered</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">X_centered</span><span class="op">)</span></span>
<span><span class="co">#&gt;   (Intercept) mom_hs_c</span></span>
<span><span class="co">#&gt; 1           1      0.5</span></span>
<span><span class="co">#&gt; 2           1      0.5</span></span>
<span><span class="co">#&gt; 3           1      0.5</span></span>
<span><span class="co">#&gt; 4           1      0.5</span></span>
<span><span class="co">#&gt; 5           1      0.5</span></span>
<span><span class="co">#&gt; 6           1     -0.5</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="La scala della codifica determina la scala del coefficiente">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>La scala della codifica determina la scala del coefficiente
</div>
</div>
<div class="callout-body-container callout-body">
<p>La codifica <span class="math inline">\(-0.5/+0.5\)</span> è stata scelta perché la distanza tra i due valori è pari a 1; per questo il coefficiente <span class="math inline">\(\beta_c\)</span> coincide con l’intera differenza <span class="math inline">\(\Delta\)</span>. Con una codifica <span class="math inline">\(-1/+1\)</span>, spesso associata alle codifiche a somma zero, la distanza tra i livelli sarebbe 2 e il coefficiente rappresenterebbe <span class="math inline">\(\Delta/2\)</span>.</p>
<p>Questo dettaglio diventa importante con più gruppi: prima di interpretare un coefficiente è sempre necessario sapere <strong>quali numeri sono stati inseriti nella matrice del modello</strong>.</p>
</div>
</div>
</section><section id="parametrizzazione-3-medie-di-cella" class="level3" data-number="27.4.3"><h3 data-number="27.4.3" class="anchored" data-anchor-id="parametrizzazione-3-medie-di-cella">
<span class="header-section-number">27.4.3</span> Parametrizzazione 3: medie di cella</h3>
<p>La parametrizzazione a medie di cella elimina l’intercetta globale:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">y</span> <span class="op">~</span> <span class="fl">0</span> <span class="op">+</span> <span class="va">gruppo</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<p>e crea una colonna indicatrice per ciascun gruppo. Nel nostro esempio:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">X_cells</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/model.matrix.html">model.matrix</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span> <span class="fl">0</span> <span class="op">+</span> <span class="va">mom_hs</span>,</span>
<span>  data <span class="op">=</span> <span class="va">kidiq</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">X_cells</span><span class="op">)</span></span>
<span><span class="co">#&gt;   mom_hsNon diplomata mom_hsDiplomata</span></span>
<span><span class="co">#&gt; 1                   0               1</span></span>
<span><span class="co">#&gt; 2                   0               1</span></span>
<span><span class="co">#&gt; 3                   0               1</span></span>
<span><span class="co">#&gt; 4                   0               1</span></span>
<span><span class="co">#&gt; 5                   0               1</span></span>
<span><span class="co">#&gt; 6                   1               0</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Le due righe caratteristiche sono:</p>
<p><span class="math display">\[
\begin{array}{c|cc}
&amp; \gamma_A &amp; \gamma_B \\
\hline
\text{gruppo A} &amp; 1 &amp; 0 \\
\text{gruppo B} &amp; 0 &amp; 1
\end{array}
\]</span></p>
<p>e il predittore lineare può essere scritto come</p>
<p><span class="math display">\[
\mu_i
=
\gamma_A I(A)_i
+
\gamma_B I(B)_i.
\]</span></p>
<p>Poiché ogni osservazione appartiene a uno soltanto dei due gruppi,</p>
<p><span class="math display">\[
\gamma_A=\mu_A,
\qquad
\gamma_B=\mu_B.
\]</span></p>
<p>La differenza non coincide ora con un singolo coefficiente, ma è una quantità derivata:</p>
<p><span class="math display">\[
\Delta=\gamma_B-\gamma_A.
\]</span></p>
<p>Questa parametrizzazione rende particolarmente trasparente il passaggio ai modelli con più gruppi: aggiungendo un livello C, la matrice acquista semplicemente una terza colonna e il modello stima direttamente <span class="math inline">\(\mu_A\)</span>, <span class="math inline">\(\mu_B\)</span> e <span class="math inline">\(\mu_C\)</span>.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Che cosa cambia e che cosa rimane invariato">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Che cosa cambia e che cosa rimane invariato
</div>
</div>
<div class="callout-body-container callout-body">
<p>Se likelihood e prior sono trasformati in modo coerente, le tre parametrizzazioni descrivono lo stesso sistema di medie. Rimangono quindi invariati:</p>
<ul>
<li>la media prevista per ciascun gruppo;</li>
<li>il contrasto <span class="math inline">\(\Delta=\mu_B-\mu_A\)</span>;</li>
<li>le quantità predittive costruite sulle stesse medie.</li>
</ul>
<p>Cambiano invece:</p>
<ul>
<li>il significato immediato dell’intercetta e degli altri coefficienti;</li>
<li>la matrice del modello;</li>
<li>il modo in cui un prior assegnato ai coefficienti si traduce in un prior sulle medie e sui contrasti.</li>
</ul>
<p>Per questo, in un’analisi bayesiana, cambiare codifica senza riconsiderare i prior può produrre un modello sostantivamente diverso anche quando la parte algebrica sembra equivalente.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Il ponte verso più gruppi e ANOVA">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Il ponte verso più gruppi e ANOVA
</div>
</div>
<div class="callout-body-container callout-body">
<p>Con <span class="math inline">\(G\)</span> gruppi, la stessa logica continua a valere:</p>
<ul>
<li>con le <strong>medie di cella</strong> si ottengono <span class="math inline">\(G\)</span> colonne e <span class="math inline">\(G\)</span> coefficienti, uno per ciascuna media <span class="math inline">\(\mu_g\)</span>;</li>
<li>con una <strong>codifica a riferimento</strong> si ottengono un’intercetta e <span class="math inline">\(G-1\)</span> coefficienti, che confrontano gli altri livelli con il riferimento;</li>
<li>con codifiche <strong>centrate o a somma zero</strong> si ottengono ancora <span class="math inline">\(G-1\)</span> coordinate per descrivere gli scostamenti tra le medie secondo i contrasti scelti.</li>
</ul>
<p>Le domande scientifiche vengono poi formulate come <strong>contrasti lineari tra le medie</strong>. È questo, non un nuovo principio inferenziale, il passaggio che conduce dal confronto tra due gruppi all’ANOVA.</p>
</div>
</div>
<p>Nel seguito utilizzeremo la parametrizzazione a <strong>medie di cella</strong>, perché rende immediatamente visibili le medie dei gruppi, consente di formulare i prior direttamente su di esse e prepara in modo naturale il capitolo successivo sui contrasti tra più gruppi.</p>
</section></section><section id="specificare-il-modello-bayesiano" class="level2" data-number="27.5"><h2 data-number="27.5" class="anchored" data-anchor-id="specificare-il-modello-bayesiano">
<span class="header-section-number">27.5</span> Specificare il modello bayesiano</h2>
<p>Adottiamo quindi la parametrizzazione a medie di cella:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">kid_score</span> <span class="op">~</span> <span class="fl">0</span> <span class="op">+</span> <span class="va">mom_hs</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<p>Assumiamo inoltre che la variabilità attorno alla media di ciascun gruppo sia descritta da una deviazione standard comune:</p>
<p><span class="math display">\[
Y_i \sim \operatorname{Normal}(\mu_{g[i]}, \sigma),
\]</span> dove <span class="math inline">\(g[i]\)</span> indica il gruppo di appartenenza dell’osservazione <span class="math inline">\(i\)</span>.</p>
<p>I prior sono definiti direttamente sulla scala del punteggio cognitivo:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">priors_two_groups</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="fu">prior</span><span class="op">(</span><span class="fu">normal</span><span class="op">(</span><span class="fl">90</span>, <span class="fl">20</span><span class="op">)</span>, class <span class="op">=</span> <span class="st">"b"</span><span class="op">)</span>,</span>
<span>  <span class="fu">prior</span><span class="op">(</span><span class="fu">student_t</span><span class="op">(</span><span class="fl">3</span>, <span class="fl">0</span>, <span class="fl">20</span><span class="op">)</span>, class <span class="op">=</span> <span class="st">"sigma"</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>La dichiarazione <code>prior(normal(90, 20), class = "b")</code> assegna la stessa distribuzione a priori alle due medie di cella. Questo non significa assumere che 90 sia il valore corretto per entrambi i gruppi: stiamo invece dichiarando che valori tra circa 50 e 130 sono plausibili sulla scala dell’outcome. La distribuzione a priori su <span class="math inline">\(\sigma\)</span> è una <span class="math inline">\(t\)</span> di Student con 3 gradi di libertà; poiché <code>sigma</code> è vincolato da <code>brms</code> a valori positivi, la densità viene utilizzata sul supporto <span class="math inline">\(\sigma&gt;0\)</span>. Le code relativamente pesanti consentono di rappresentare una gamma ampia di valori plausibili per la variabilità residua.</p>
<p>Come già discusso nel capitolo sul workflow, la calibrazione dei prior va valutata sulla scala del fenomeno e verificata attraverso le conseguenze predittive del modello, piuttosto che classificata astrattamente come “debole” o “forte”.</p>
<section id="controllo-predittivo-a-priori" class="level3" data-number="27.5.1"><h3 data-number="27.5.1" class="anchored" data-anchor-id="controllo-predittivo-a-priori">
<span class="header-section-number">27.5.1</span> Controllo predittivo a priori</h3>
<p>Prima di condizionare il modello ai dati osservati, simuliamo esclusivamente dalle distribuzioni a priori, in modo da esaminare le implicazioni delle assunzioni sulla scala osservabile.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_two_groups_prior</span> <span class="op">&lt;-</span> <span class="fu">brm</span><span class="op">(</span></span>
<span>  formula <span class="op">=</span> <span class="va">kid_score</span> <span class="op">~</span> <span class="fl">0</span> <span class="op">+</span> <span class="va">mom_hs</span>,</span>
<span>  data <span class="op">=</span> <span class="va">kidiq</span>,</span>
<span>  family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">gaussian</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  prior <span class="op">=</span> <span class="va">priors_two_groups</span>,</span>
<span>  sample_prior <span class="op">=</span> <span class="st">"only"</span>,</span>
<span>  backend <span class="op">=</span> <span class="st">"cmdstanr"</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  iter <span class="op">=</span> <span class="fl">1000</span>,</span>
<span>  seed <span class="op">=</span> <span class="fl">1234</span>,</span>
<span>  refresh <span class="op">=</span> <span class="fl">0</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pp_check</span><span class="op">(</span></span>
<span>  <span class="va">fit_two_groups_prior</span>,</span>
<span>  type <span class="op">=</span> <span class="st">"dens_overlay"</span>,</span>
<span>  ndraws <span class="op">=</span> <span class="fl">40</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-prior-predictive-two-groups" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-prior-predictive-two-groups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06_due_gruppi_rilevanza_pratica_files/figure-html/fig-prior-predictive-two-groups-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figura&nbsp;27.2: Controllo predittivo a priori del modello a due gruppi. Le repliche traducono i prior sulle medie e sulla dispersione in possibili distribuzioni osservabili del punteggio cognitivo."><img src="06_due_gruppi_rilevanza_pratica_files/figure-html/fig-prior-predictive-two-groups-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-prior-predictive-two-groups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;27.2: Controllo predittivo a priori del modello a due gruppi. Le repliche traducono i prior sulle medie e sulla dispersione in possibili distribuzioni osservabili del punteggio cognitivo.
</figcaption></figure>
</div>
</div>
</div>
<p>L’obiettivo non è che le simulazioni coincidano con i dati che stiamo per analizzare — i dati non sono ancora stati utilizzati. La domanda è più semplice: <strong>i prior producono scenari compatibili con la scala del fenomeno, senza concentrare una massa eccessiva di probabilità su configurazioni palesemente implausibili (ad esempio, punteggi negativi o medie estreme che contraddicono quanto si sa sul costrutto)?</strong></p>
</section></section><section id="adattare-il-modello" class="level2" data-number="27.6"><h2 data-number="27.6" class="anchored" data-anchor-id="adattare-il-modello">
<span class="header-section-number">27.6</span> Adattare il modello</h2>
<p>A questo punto possiamo adattare il modello ai dati. Il modello assume che i due gruppi abbiano una propria media del punteggio dei bambini e che la variabilità individuale attorno a queste medie sia descritta da un unico parametro, <span class="math inline">\(\sigma\)</span>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_two_groups</span> <span class="op">&lt;-</span> <span class="fu">brm</span><span class="op">(</span></span>
<span>  formula <span class="op">=</span> <span class="va">kid_score</span> <span class="op">~</span> <span class="fl">0</span> <span class="op">+</span> <span class="va">mom_hs</span>,</span>
<span>  data <span class="op">=</span> <span class="va">kidiq</span>,</span>
<span>  family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">gaussian</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>  prior <span class="op">=</span> <span class="va">priors_two_groups</span>,</span>
<span>  backend <span class="op">=</span> <span class="st">"cmdstanr"</span>,</span>
<span>  chains <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  iter <span class="op">=</span> <span class="fl">2000</span>,</span>
<span>  seed <span class="op">=</span> <span class="fl">1234</span>,</span>
<span>  refresh <span class="op">=</span> <span class="fl">0</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>L’adattamento del modello produce una distribuzione a posteriori per ciascuna quantità ignota. In particolare, otteniamo informazioni su:</p>
<ul>
<li>la media del punteggio nel gruppo delle madri non diplomate;</li>
<li>la media del punteggio nel gruppo delle madri diplomate;</li>
<li>la variabilità dei punteggi individuali attorno alle rispettive medie di gruppo.</li>
</ul>
<p>Prima di interpretare questi risultati dobbiamo però assicurarci che il procedimento di stima abbia funzionato correttamente. Le diagnostiche computazionali sono state introdotte nell’<a href="#sec-linmod-bayesian-reg" class="quarto-xref"><span class="quarto-unresolved-ref">sec-linmod-bayesian-reg</span></a> e qui non vengono ripetute. Rimane comunque necessario controllare <span class="math inline">\(\widehat R\)</span>, la dimensione campionaria effettiva (ESS), la presenza di eventuali divergenze e gli altri avvisi prodotti dal campionatore.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_two_groups</span><span class="op">)</span></span>
<span><span class="co">#&gt;  Family: gaussian </span></span>
<span><span class="co">#&gt;   Links: mu = identity </span></span>
<span><span class="co">#&gt; Formula: kid_score ~ 0 + mom_hs </span></span>
<span><span class="co">#&gt;    Data: kidiq (Number of observations: 434) </span></span>
<span><span class="co">#&gt;   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;</span></span>
<span><span class="co">#&gt;          total post-warmup draws = 4000</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Regression Coefficients:</span></span>
<span><span class="co">#&gt;                    Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS</span></span>
<span><span class="co">#&gt; mom_hsNondiplomata    77.70      2.00    73.74    81.65 1.00     4214     2879</span></span>
<span><span class="co">#&gt; mom_hsDiplomata       89.33      1.08    87.20    91.43 1.00     4092     2897</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Further Distributional Parameters:</span></span>
<span><span class="co">#&gt;       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS</span></span>
<span><span class="co">#&gt; sigma    19.88      0.66    18.58    21.21 1.00     4286     2911</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Draws were sampled using sample(hmc). For each parameter, Bulk_ESS</span></span>
<span><span class="co">#&gt; and Tail_ESS are effective sample size measures, and Rhat is the potential</span></span>
<span><span class="co">#&gt; scale reduction factor on split chains (at convergence, Rhat = 1).</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Solo dopo aver verificato che il campionamento sia affidabile possiamo passare all’interpretazione sostantiva del modello.</p>
</section><section id="dal-modello-alla-domanda-di-ricerca" class="level2" data-number="27.7"><h2 data-number="27.7" class="anchored" data-anchor-id="dal-modello-alla-domanda-di-ricerca">
<span class="header-section-number">27.7</span> Dal modello alla domanda di ricerca</h2>
<p>L’output di un modello statistico contiene dei <strong>parametri</strong>, ma questi parametri non coincidono necessariamente con ciò che vogliamo conoscere. Nel nostro esempio, la domanda sostantiva è semplice: vogliamo sapere qual è il punteggio medio atteso nei due gruppi e quanto questi due valori differiscono.</p>
<p>Indichiamo con <span class="math inline">\(\mu_0\)</span> la media attesa dei bambini le cui madri non sono diplomate e con <span class="math inline">\(\mu_1\)</span> la media attesa dei bambini le cui madri sono diplomate. La differenza tra i gruppi è quindi</p>
<p><span class="math display">\[
\Delta = \mu_1-\mu_0.
\]</span></p>
<p>Se <span class="math inline">\(\Delta\)</span> è positiva, il punteggio medio atteso è maggiore nel gruppo delle madri diplomate; se è negativa, è maggiore nel gruppo delle madri non diplomate; se è vicino a zero, le due medie sono simili.</p>
<p>Il punto importante è che <strong>non dobbiamo limitarci a leggere i coefficienti così come compaiono nell’output del modello</strong>. È spesso più utile chiedere direttamente al modello quali valori prevede per le situazioni che ci interessano.</p>
<p>Costruiamo quindi due casi: uno corrispondente a una madre non diplomata e uno a una madre diplomata.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">group_grid</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span></span>
<span>  mom_hs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Non diplomata"</span>, <span class="st">"Diplomata"</span><span class="op">)</span>,</span>
<span>    levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/levels.html">levels</a></span><span class="op">(</span><span class="va">kidiq</span><span class="op">$</span><span class="va">mom_hs</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">group_epred</span> <span class="op">&lt;-</span> <span class="fu">posterior_epred</span><span class="op">(</span></span>
<span>  <span class="va">fit_two_groups</span>,</span>
<span>  newdata <span class="op">=</span> <span class="va">group_grid</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_draws</span> <span class="op">&lt;-</span> <span class="fu">as_draws_df</span><span class="op">(</span><span class="va">fit_two_groups</span><span class="op">)</span></span>
<span></span>
<span><span class="va">post_two_groups</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span></span>
<span>  mu0   <span class="op">=</span> <span class="va">group_epred</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>,</span>
<span>  mu1   <span class="op">=</span> <span class="va">group_epred</span><span class="op">[</span>, <span class="fl">2</span><span class="op">]</span>,</span>
<span>  sigma <span class="op">=</span> <span class="va">fit_draws</span><span class="op">$</span><span class="va">sigma</span></span>
<span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span></span>
<span>    delta <span class="op">=</span> <span class="va">mu1</span> <span class="op">-</span> <span class="va">mu0</span>,</span>
<span>    d <span class="op">=</span> <span class="va">delta</span> <span class="op">/</span> <span class="va">sigma</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">post_two_groups</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">summarise</span><span class="op">(</span></span>
<span>    <span class="fu">across</span><span class="op">(</span></span>
<span>      <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">mu0</span>, <span class="va">mu1</span>, <span class="va">delta</span>, <span class="va">sigma</span>, <span class="va">d</span><span class="op">)</span>,</span>
<span>      <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>        median <span class="op">=</span> <span class="va">median</span>,</span>
<span>        lower <span class="op">=</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">.x</span>, <span class="fl">0.025</span><span class="op">)</span>,</span>
<span>        upper <span class="op">=</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">.x</span>, <span class="fl">0.975</span><span class="op">)</span></span>
<span>      <span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["mu0_median"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["mu0_lower"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["mu0_upper"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["mu1_median"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["mu1_lower"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["mu1_upper"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["delta_median"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["delta_lower"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["delta_upper"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["sigma_median"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["sigma_lower"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["sigma_upper"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["d_median"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["d_lower"],"name":[14],"type":["dbl"],"align":["right"]},{"label":["d_upper"],"name":[15],"type":["dbl"],"align":["right"]}],"data":[{"1":"77.7","2":"73.7","3":"81.7","4":"89.3","5":"87.2","6":"91.4","7":"11.6","8":"7.18","9":"16.1","10":"19.9","11":"18.6","12":"21.2","13":"0.584","14":"0.36","15":"0.818"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>L’idea del calcolo è più importante della sintassi utilizzata.</p>
<p>Per ogni possibile configurazione dei parametri compatibile con i dati e con il modello, calcoliamo la media attesa nei due gruppi. Non otteniamo quindi un solo valore per <span class="math inline">\(\mu_0\)</span> e un solo valore per <span class="math inline">\(\mu_1\)</span>, ma <strong>un’intera distribuzione a posteriori per ciascuna media</strong>. Questo è essenziale perché permette di conservare l’incertezza della stima.</p>
<p>Per esempio, per un particolare draw della distribuzione a posteriori il modello potrebbe produrre:</p>
<p><span class="math display">\[
\mu_0 = 78,\qquad \mu_1 = 89.
\]</span></p>
<p>Per quel draw la differenza sarebbe</p>
<p><span class="math display">\[
\Delta = 89-78=11.
\]</span></p>
<p>Un altro draw potrebbe invece produrre:</p>
<p><span class="math display">\[
\mu_0 = 81,\qquad \mu_1 = 87,
\]</span> e quindi</p>
<p><span class="math display">\[
\Delta = 6.
\]</span></p>
<p>Ripetendo questo calcolo per tutti i draw otteniamo la <strong>distribuzione a posteriori di <span class="math inline">\(\Delta\)</span></strong>. Questa distribuzione descrive quali differenze tra i gruppi sono più o meno plausibili alla luce del modello, dei dati e dei prior.</p>
<p>Lo stesso principio vale per qualsiasi altra quantità derivata.</p>
<section id="la-differenza-tra-le-medie" class="level3" data-number="27.7.1"><h3 data-number="27.7.1" class="anchored" data-anchor-id="la-differenza-tra-le-medie">
<span class="header-section-number">27.7.1</span> La differenza tra le medie</h3>
<p>La quantità più direttamente collegata alla domanda di ricerca è</p>
<p><span class="math display">\[
\Delta=\mu_1-\mu_0.
\]</span></p>
<p>Questa differenza è espressa nella stessa unità di misura dell’outcome. Se, per esempio, <span class="math inline">\(\Delta=10\)</span>, significa che le due medie differiscono di 10 punti sulla scala di <code>kid_score</code>.</p>
</section><section id="una-differenza-standardizzata" class="level3" data-number="27.7.2"><h3 data-number="27.7.2" class="anchored" data-anchor-id="una-differenza-standardizzata">
<span class="header-section-number">27.7.2</span> Una differenza standardizzata</h3>
<p>In alcuni contesti può essere utile esprimere la differenza rispetto alla variabilità individuale dei punteggi. Possiamo allora calcolare</p>
<p><span class="math display">\[
d=\frac{\Delta}{\sigma},
\]</span> dove <span class="math inline">\(\sigma\)</span> rappresenta la dispersione dei punteggi individuali attorno alle medie di gruppo.</p>
<p>Anche <span class="math inline">\(d\)</span> non viene calcolato una sola volta. Per ogni draw utilizziamo i corrispondenti valori di <span class="math inline">\(\Delta\)</span> e <span class="math inline">\(\sigma\)</span>. Otteniamo così una distribuzione a posteriori anche per la dimensione dell’effetto standardizzata.</p>
<p>In generale, quindi, il procedimento è:</p>
<p><span class="math display">\[
\text{draw dei parametri}
\longrightarrow
\mu_0,\mu_1
\longrightarrow
\Delta
\longrightarrow
d.
\]</span></p>
<p>L’incertezza viene propagata lungo tutta la catena. Se siamo incerti sulle medie dei gruppi e sulla variabilità individuale, questa incertezza sarà presente anche nelle distribuzioni a posteriori di <span class="math inline">\(\Delta\)</span> e <span class="math inline">\(d\)</span>.</p>
</section></section><section id="dai-coefficienti-alle-quantità-di-interesse" class="level2" data-number="27.8"><h2 data-number="27.8" class="anchored" data-anchor-id="dai-coefficienti-alle-quantità-di-interesse">
<span class="header-section-number">27.8</span> Dai coefficienti alle quantità di interesse</h2>
<p>L’esempio mette in evidenza una regola che verrà riutilizzata nei capitoli successivi: <strong>i coefficienti sono coordinate della parametrizzazione; le quantità di interesse sono funzioni di quelle coordinate scelte perché rispondono alla domanda scientifica</strong>.</p>
<p>Nel modello a medie di cella, <span class="math inline">\(\mu_A\)</span> e <span class="math inline">\(\mu_B\)</span> coincidono direttamente con due coefficienti e</p>
<p><span class="math display">\[
\Delta=\mu_B-\mu_A
\]</span></p>
<p>è una quantità derivata. Nella codifica dummy, invece, <span class="math inline">\(\Delta\)</span> coincide con il coefficiente del gruppo, mentre <span class="math inline">\(\mu_B\)</span> è una somma di coefficienti. Nella codifica centrata, l’intercetta è il punto medio delle due medie e il coefficiente è ancora <span class="math inline">\(\Delta\)</span>.</p>
<p>Per questo, quando si interpreta un modello, la domanda più utile non è soltanto «che cosa significa questo coefficiente?», ma soprattutto:</p>
<blockquote class="blockquote">
<p><strong>Quale funzione dei parametri esprime la quantità scientifica che voglio conoscere?</strong></p>
</blockquote>
<p>Nel quadro bayesiano questa funzione viene calcolata draw per draw, conservando automaticamente l’incertezza e le dipendenze presenti nella distribuzione a posteriori congiunta. Questo principio sarà essenziale quando, con tre o più gruppi, i contrasti di interesse non coincideranno necessariamente con un singolo coefficiente.</p>
</section><section id="direzione-grandezza-e-rilevanza-pratica" class="level2" data-number="27.9"><h2 data-number="27.9" class="anchored" data-anchor-id="direzione-grandezza-e-rilevanza-pratica">
<span class="header-section-number">27.9</span> Direzione, grandezza e rilevanza pratica</h2>
<p>La distribuzione a posteriori di <span class="math inline">\(\Delta\)</span> consente di separare domande che nella pratica vengono spesso confuse. Invece di ridurre l’inferenza a un singolo giudizio binario (differenza presente o assente), possiamo articolare la domanda lungo dimensioni distinte.</p>
<p>La prima domanda riguarda la <strong>direzione</strong> della differenza:</p>
<p><span class="math display">\[
\Pr(\Delta &gt; 0 \mid y).
\]</span></p>
<p>Questa probabilità quantifica quanto la distribuzione a posteriori sostenga una differenza positiva: in altri termini, quanto sia plausibile, condizionatamente ai dati, ai prior e al modello, che i bambini del gruppo “Diplomata” abbiano un punteggio medio più alto di quelli del gruppo “Non diplomata”.</p>
<p>La seconda domanda riguarda la <strong>grandezza sostantiva</strong>. Se esiste una soglia direzionale <span class="math inline">\(s\)</span> stabilita sulla base di criteri teorici, clinici o decisionali — collegata a una <em>Smallest Effect Size of Interest</em> (SESOI) — possiamo chiederci:</p>
<p><span class="math display">\[
\Pr(\Delta &gt; s \mid y).
\]</span></p>
<p>A scopo puramente didattico, utilizzeremo <span class="math inline">\(s = 5\)</span> punti come soglia illustrativa. Questo valore non è stato derivato da considerazioni cliniche o teoriche validate per il costrutto in esame; serve unicamente a mostrare come si calcola e si interpreta una probabilità di superamento di una soglia sostantiva.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">SESOI_delta</span> <span class="op">&lt;-</span> <span class="fl">5</span></span>
<span><span class="va">ROPE_halfwidth</span> <span class="op">&lt;-</span> <span class="fl">5</span></span>
<span></span>
<span><span class="va">post_two_groups</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">delta</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_density</span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"grey90"</span>, color <span class="op">=</span> <span class="st">"grey40"</span>, alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fl">0</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="va">SESOI_delta</span>, linetype <span class="op">=</span> <span class="st">"dotted"</span>, linewidth <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span></span>
<span>    x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"Differenza grezza ("</span>, <span class="va">Delta</span>, <span class="st">")"</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    y <span class="op">=</span> <span class="st">"Densità a posteriori"</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-posterior-delta-two-groups" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-posterior-delta-two-groups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06_due_gruppi_rilevanza_pratica_files/figure-html/fig-posterior-delta-two-groups-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figura&nbsp;27.3: Distribuzione a posteriori della differenza tra le medie. La linea tratteggiata indica zero; la linea puntinata mostra, a puro scopo didattico, una soglia sostantiva di 5 punti."><img src="06_due_gruppi_rilevanza_pratica_files/figure-html/fig-posterior-delta-two-groups-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-posterior-delta-two-groups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;27.3: Distribuzione a posteriori della differenza tra le medie. La linea tratteggiata indica zero; la linea puntinata mostra, a puro scopo didattico, una soglia sostantiva di 5 punti.
</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  P_delta_positive <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">post_two_groups</span><span class="op">$</span><span class="va">delta</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span>,</span>
<span>  P_delta_gt_s <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">post_two_groups</span><span class="op">$</span><span class="va">delta</span> <span class="op">&gt;</span> <span class="va">SESOI_delta</span><span class="op">)</span>,</span>
<span>  P_delta_in_rope <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">post_two_groups</span><span class="op">$</span><span class="va">delta</span><span class="op">)</span> <span class="op">&lt;=</span> <span class="va">ROPE_halfwidth</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt; P_delta_positive     P_delta_gt_s  P_delta_in_rope </span></span>
<span><span class="co">#&gt;            1.000            0.998            0.002</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>I tre valori ottenuti rispondono a domande sostanzialmente diverse:</p>
<ul>
<li>
<code>P_delta_positive</code> quantifica la massa a posteriori associata a una differenza positiva, indipendentemente dalla sua ampiezza;</li>
<li>
<code>P_delta_gt_s</code> quantifica la massa a posteriori associata a una differenza che supera la soglia direzionale scelta;</li>
<li>
<code>P_delta_in_rope</code> quantifica la massa a posteriori contenuta nella regione di equivalenza pratica definita attorno allo zero.</li>
</ul>
<p>Nell’esempio la SESOI direzionale e la semiampiezza della ROPE assumono entrambe, per semplicità didattica, il valore numerico di 5 punti. Sono però <strong>due criteri concettualmente distinti</strong> e, in un’analisi reale, non devono necessariamente coincidere.</p>
<p>Nessuna di queste probabilità va confusa con un <em>p</em>-valore o con una soglia di significatività. Una probabilità a posteriori si trasforma in una decisione soltanto quando viene collegata a conseguenze, costi e criteri esplicitamente stabiliti per il problema concreto.</p>
<div class="callout callout-style-default callout-note callout-titled" title="SESOI e ROPE non sono sinonimi">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>SESOI e ROPE non sono sinonimi
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una <strong>SESOI</strong> (<em>Smallest Effect Size of Interest</em>) esprime il confine oltre il quale una differenza viene considerata sufficientemente grande da essere sostantivamente interessante. La sua formulazione dipende dalla domanda: può essere direzionale, come <span class="math inline">\(\Delta&gt;5\)</span>, oppure riferirsi alla grandezza della differenza in entrambe le direzioni.</p>
<p>Una <strong>ROPE</strong> (<em>Region of Practical Equivalence</em>) è invece un intervallo, per esempio <span class="math inline">\([-5,5]\)</span>, i cui valori vengono trattati come praticamente equivalenti al valore di riferimento. La probabilità di superare una soglia e la probabilità di ricadere in una ROPE rispondono quindi a domande diverse. In entrambi i casi, i confini devono essere giustificati dal dominio di ricerca e, nelle analisi confermative, stabiliti indipendentemente dalla posterior osservata.</p>
</div>
</div>
</section><section id="sec-bayesian-effect-size" class="level2" data-number="27.10"><h2 data-number="27.10" class="anchored" data-anchor-id="sec-bayesian-effect-size">
<span class="header-section-number">27.10</span> La differenza standardizzata è una quantità secondaria</h2>
<p>Quando la scala originale dell’outcome è interpretabile, come nel caso di un punteggio cognitivo, la differenza grezza <span class="math inline">\(\Delta\)</span> rappresenta in genere la quantità più trasparente da comunicare. La standardizzazione può tuttavia essere utile in due circostanze: per confrontare gli effetti ottenuti con strumenti di misurazione diversi o per integrare i risultati in una sintesi meta-analitica. In questi casi, si calcola:</p>
<p><span class="math display">\[
d = \frac{\Delta}{\sigma}.
\]</span></p>
<p>Nel modello corrente, sia <span class="math inline">\(\Delta\)</span> che <span class="math inline">\(\sigma\)</span> sono incerti. Calcolando il rapporto draw per draw, ovvero per ciascuna configurazione campionata dalla distribuzione a posteriori congiunta, l’incertezza su entrambe le quantità viene automaticamente propagata alla distribuzione a posteriori di <span class="math inline">\(d\)</span>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">post_two_groups</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">summarise</span><span class="op">(</span></span>
<span>    d_median <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">d</span><span class="op">)</span>,</span>
<span>    d_lower <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">d</span>, <span class="fl">0.025</span><span class="op">)</span>,</span>
<span>    d_upper <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">d</span>, <span class="fl">0.975</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["d_median"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["d_lower"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["d_upper"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"0.584","2":"0.36","3":"0.818"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>È importante notare che <span class="math inline">\(d\)</span> non è una misura pura della “forza” della differenza, ma dipende anche dalla dispersione della popolazione e, indirettamente, dalla qualità della misurazione. Una stessa differenza grezza può corrispondere a valori standardizzati molto diversi in popolazioni con variabilità differente. La standardizzazione, insomma, non rende l’effetto più “oggettivo” — lo rende più dipendente dal contesto di misurazione.</p>
<div class="callout callout-style-default callout-caution callout-titled" title="Evitare categorie automatiche">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Attenzione</span>Evitare categorie automatiche
</div>
</div>
<div class="callout-body-container callout-body">
<p>Le soglie 0.2, 0.5 e 0.8, storicamente associate a effetti “piccoli”, “medi” e “grandi”, non rappresentano confini naturali. Se il dominio di ricerca dispone di criteri sostantivi più informativi, ad esempio una differenza minima clinicamente rilevante, questi devono avere la precedenza. In ogni caso, la differenza standardizzata dovrebbe affiancare, non sostituire, la differenza espressa sulla scala originale.</p>
</div>
</div>
</section><section id="controllare-il-modello-nei-due-gruppi" class="level2" data-number="27.11"><h2 data-number="27.11" class="anchored" data-anchor-id="controllare-il-modello-nei-due-gruppi">
<span class="header-section-number">27.11</span> Controllare il modello nei due gruppi</h2>
<p>Un controllo predittivo sulla distribuzione marginale dell’outcome può apparire soddisfacente anche quando il modello descrive male uno dei due gruppi — perché gli scostamenti in un gruppo possono essere compensati da quelli nell’altro, o perché l’aggregazione nasconde discrepanze sistematiche. Poiché la domanda scientifica riguarda proprio un confronto tra distribuzioni condizionate, il controllo deve essere condotto rispettando questa struttura.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">pp_check</span><span class="op">(</span></span>
<span>  <span class="va">fit_two_groups</span>,</span>
<span>  type <span class="op">=</span> <span class="st">"dens_overlay_grouped"</span>,</span>
<span>  group <span class="op">=</span> <span class="st">"mom_hs"</span>,</span>
<span>  ndraws <span class="op">=</span> <span class="fl">20</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-grouped-ppc-two-groups" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-grouped-ppc-two-groups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06_due_gruppi_rilevanza_pratica_files/figure-html/fig-grouped-ppc-two-groups-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figura&nbsp;27.4: Controllo predittivo a posteriori separato per livello di istruzione materna. Le distribuzioni osservate vengono confrontate con repliche generate dal modello all’interno di ciascun gruppo."><img src="06_due_gruppi_rilevanza_pratica_files/figure-html/fig-grouped-ppc-two-groups-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-grouped-ppc-two-groups-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;27.4: Controllo predittivo a posteriori separato per livello di istruzione materna. Le distribuzioni osservate vengono confrontate con repliche generate dal modello all’interno di ciascun gruppo.
</figcaption></figure>
</div>
</div>
</div>
<p>La rappresentazione separata per gruppo permette di individuare eventuali discrepanze specifiche — nella posizione, nella dispersione o nella forma delle distribuzioni — che un controllo aggregato non mostrerebbe. Un buon accordo tra osservazioni e repliche non dimostra che il modello sia vero; indica soltanto che, per le caratteristiche esaminate, non emergono discrepanze evidenti.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Approfondimento: se le dispersioni differiscono">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Approfondimento: se le dispersioni differiscono
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Il modello essenziale usa un unico parametro <span class="math inline">\(\sigma\)</span> e assume quindi la stessa dispersione residua nei due gruppi. Se questa assunzione è inadeguata, <code>brms</code> consente di modellare anche <span class="math inline">\(\sigma\)</span> in funzione del gruppo, per esempio:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">bf</span><span class="op">(</span></span>
<span>  <span class="va">kid_score</span> <span class="op">~</span> <span class="fl">0</span> <span class="op">+</span> <span class="va">mom_hs</span>,</span>
<span>  <span class="va">sigma</span> <span class="op">~</span> <span class="fl">0</span> <span class="op">+</span> <span class="va">mom_hs</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<p>Questa estensione modifica tuttavia anche il significato di una differenza standardizzata: non esiste più un’unica deviazione standard residua da utilizzare come denominatore. Il problema verrà ripreso nel capitolo dedicato al controllo e alla revisione del modello.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled" title="Gruppi indipendenti e misure appaiate sono disegni diversi">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Attenzione</span>Gruppi indipendenti e misure appaiate sono disegni diversi
</div>
</div>
<div class="callout-body-container callout-body">
<p>Il modello presentato in questo capitolo assume osservazioni indipendenti appartenenti a due gruppi distinti. Se le due misure provengono dagli stessi individui (ad esempio, misurazioni pre e post), la dipendenza entro soggetto deve essere rappresentata nel modello. Nel caso più semplice, si può modellare la distribuzione delle differenze individuali; in alternativa, si può adottare un modello per misure ripetute. Trattare osservazioni appaiate come se provenissero da due gruppi indipendenti comporta una perdita di informazione sulla struttura del disegno e può alterare l’inferenza.</p>
</div>
</div>
</section><section id="comunicare-i-risultati" class="level2" data-number="27.12"><h2 data-number="27.12" class="anchored" data-anchor-id="comunicare-i-risultati">
<span class="header-section-number">27.12</span> Comunicare i risultati</h2>
<p>Un resoconto utile dovrebbe partire dalle quantità scientifiche, non dalla codifica del software. È quindi opportuno riportare:</p>
<ol type="1">
<li>le medie stimate dei due gruppi;</li>
<li>la differenza <span class="math inline">\(\Delta\)</span> sulla scala originaria e la sua incertezza;</li>
<li>la probabilità della direzione, se rilevante per la domanda;</li>
<li>la probabilità di superare una soglia sostantiva, soltanto se tale soglia è giustificata;</li>
<li>eventualmente la differenza standardizzata, specificando il denominatore;</li>
<li>gli aspetti del modello effettivamente controllati;</li>
<li>i limiti imposti dal disegno alla generalizzazione e all’interpretazione causale.</li>
</ol>
<blockquote class="blockquote">
<p>Nel campione analizzato, la mediana a posteriori della media del punteggio cognitivo è 77.7 punti nel gruppo “Non diplomata” e 89.3 punti nel gruppo “Diplomata”. La differenza “Diplomata meno Non diplomata” è 11.6 punti, con intervallo di credibilità al 95% [7.2, 16.1]. La probabilità a posteriori che la differenza sia positiva è 1.000. Usando esclusivamente a scopo illustrativo una soglia di 5 punti, la probabilità che la differenza la superi è 0.998. La differenza standardizzata è <span class="math inline">\(d=\)</span> 0.58 ([0.36, 0.82]). I controlli predittivi esaminati non mostrano discrepanze evidenti nelle caratteristiche considerate. Poiché il confronto è osservazionale, il risultato descrive un’associazione tra istruzione materna e punteggio del bambino e non identifica un effetto causale del diploma.</p>
</blockquote>
</section><section id="errori-comuni" class="level2" data-number="27.13"><h2 data-number="27.13" class="anchored" data-anchor-id="errori-comuni">
<span class="header-section-number">27.13</span> Errori comuni</h2>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Attenzione
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>
<strong>Interpretare un coefficiente senza conoscere la codifica.</strong> I coefficienti cambiano significato quando cambia il riferimento o la parametrizzazione.</li>
<li>
<strong>Confondere coefficienti e quantità sostantive.</strong> Le medie di gruppo e il loro contrasto possono essere ricostruiti anche quando non coincidono direttamente con i coefficienti del modello.</li>
<li>
<strong>Sostituire la differenza grezza con <span class="math inline">\(d\)</span>.</strong> La standardizzazione è utile per alcuni confronti, ma nasconde l’unità di misura e dipende dalla dispersione.</li>
<li>
<strong>Inventare una soglia dopo avere visto i risultati.</strong> SESOI e ROPE devono derivare da ragioni sostantive o decisionali indipendenti dalla posterior osservata.</li>
<li>
<strong>Interpretare un intervallo che comprende zero come prova di equivalenza.</strong> Incertezza ed equivalenza pratica non sono la stessa cosa.</li>
<li>
<strong>Controllare soltanto la distribuzione marginale complessiva.</strong> In un confronto tra gruppi è essenziale verificare che il modello descriva adeguatamente ciascun gruppo.</li>
<li>
<strong>Attribuire causalità a un contrasto osservazionale.</strong> La regressione non crea, da sola, le condizioni necessarie per identificare un effetto causale.</li>
</ol>
</div>
</div>
</section><section id="riflessioni-conclusive" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="riflessioni-conclusive">Riflessioni conclusive</h2>
<p>Per passare da una media a due gruppi è sufficiente aggiungere l’informazione sull’appartenenza al gruppo alla sola intercetta, senza modificare la struttura del modello. Questa modifica produce una matrice del modello con una colonna in più, ma non altera la logica generale dell’inferenza: ciò che cambia è la complessità della quantità di interesse, non il principio con cui viene stimata.</p>
<p>Il punto centrale è distinguere ciò che dipende dalla <strong>parametrizzazione</strong> da ciò che appartiene alla <strong>domanda scientifica</strong>. L’intercetta e i coefficienti possono cambiare significato quando cambia la codifica dei predittori, mentre le medie di gruppo, <span class="math inline">\(\mu_0\)</span> e <span class="math inline">\(\mu_1\)</span>, e il contrasto, <span class="math inline">\(\Delta\)</span>, sono invece le quantità che rispondono alla domanda sostantiva e vanno pertanto interpretate. Nel quadro bayesiano, è possibile descrivere l’intera incertezza su queste quantità, calcolare le probabilità sulla direzione e, quando sono disponibili criteri indipendenti, valutare la probabilità che la differenza raggiunga una grandezza rilevante dal punto di vista scientifico.</p>
<p>La differenza standardizzata fornisce una scala comparativa utile per la sintesi o la meta-analisi, ma non sostituisce l’interpretazione delle unità originarie, soprattutto quando queste sono direttamente interpretabili, come nel caso del punteggio cognitivo. Allo stesso modo, l’introduzione di una soglia pratica non trasforma automaticamente l’inferenza in una decisione, ma richiede di specificare perché quella soglia è rilevante e quali conseguenze siano associate alle diverse conclusioni.</p>
<p>Nel prossimo capitolo aggiungeremo un terzo gruppo e poi ulteriori livelli. La parametrizzazione a medie di cella, già adottata in precedenza, rende questo passaggio naturale: avremo una media per ciascun gruppo e formuleremo le domande scientifiche come contrasti lineari tra queste medie. In questa prospettiva, l’ANOVA tradizionale non introduce una nuova logica inferenziale, ma è un’estensione dello stesso modello lineare a un predittore categoriale con più livelli.</p>
</section><section id="esercizi" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="esercizi">Esercizi</h2>
<section id="esercizio-1-dalla-matrice-alle-medie" class="level3 unnumbered unlisted"><h3 class="unnumbered unlisted anchored" data-anchor-id="esercizio-1-dalla-matrice-alle-medie">Esercizio 1 — Dalla matrice alle medie</h3>
<p><em>10 minuti · Codice: no</em></p>
<p>Con codifica dummy, il modello è</p>
<p><span class="math display">\[
\mu_i = \alpha+\beta x_i,
\]</span></p>
<p>con <span class="math inline">\(x=0\)</span> per il gruppo A e <span class="math inline">\(x=1\)</span> per il gruppo B.</p>
<ol type="1">
<li>Ricava <span class="math inline">\(\mu_A\)</span> e <span class="math inline">\(\mu_B\)</span>.</li>
<li>Dimostra che <span class="math inline">\(\Delta=\mu_B-\mu_A=\beta\)</span>.</li>
<li>Scrivi le due righe distinte della matrice del modello.</li>
<li>Spiega che cosa cambierebbe usando <code>y ~ 0 + gruppo</code>.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Suggerimento">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Suggerimento
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Con le medie di cella non esiste una colonna di intercetta globale: ogni gruppo possiede la propria colonna indicatrice.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Soluzione commentata">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Soluzione commentata
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Con la codifica dummy, <span class="math inline">\(\mu_A=\alpha\)</span> e <span class="math inline">\(\mu_B=\alpha+\beta\)</span>, quindi <span class="math inline">\(\Delta=\beta\)</span>. Le righe della matrice sono <span class="math inline">\([1,0]\)</span> per A e <span class="math inline">\([1,1]\)</span> per B. Con <code>y ~ 0 + gruppo</code>, le righe diventano <span class="math inline">\([1,0]\)</span> e $[0,1]`: i due coefficienti rappresentano direttamente <span class="math inline">\(\mu_A\)</span> e <span class="math inline">\(\mu_B\)</span>, mentre il contrasto viene calcolato come loro differenza.</p>
</div>
</div>
</div>
</section><section id="esercizio-2-direzione-e-rilevanza-non-sono-la-stessa-domanda" class="level3 unnumbered unlisted"><h3 class="unnumbered unlisted anchored" data-anchor-id="esercizio-2-direzione-e-rilevanza-non-sono-la-stessa-domanda">Esercizio 2 — Direzione e rilevanza non sono la stessa domanda</h3>
<p><em>10–15 minuti · Codice: no</em></p>
<p>Per il contrasto “B meno A” si ottengono:</p>
<ul>
<li>mediana a posteriori di <span class="math inline">\(\Delta\)</span>: 7.2 punti;</li>
<li>intervallo di credibilità al 95%: <span class="math inline">\([2.1,12.3]\)</span>;</li>
<li>
<span class="math inline">\(\Pr(\Delta&gt;0\mid y)=0.996\)</span>;</li>
<li>
<span class="math inline">\(\Pr(\Delta&gt;5\mid y)=0.80\)</span>;</li>
<li>mediana a posteriori di <span class="math inline">\(d\)</span>: 0.40, con intervallo <span class="math inline">\([0.12,0.68]\)</span>.</li>
</ul>
<ol type="1">
<li>Che cosa dice la prima probabilità?</li>
<li>Perché la seconda probabilità è più bassa?</li>
<li>Quale quantità useresti per comunicare l’ampiezza nella scala originale?</li>
<li>Quale informazione aggiunge <span class="math inline">\(d\)</span>?</li>
<li>Quale conclusione causale sarebbe ingiustificata se A e B fossero gruppi osservazionali?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Soluzione commentata">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Soluzione commentata
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La posterior sostiene fortemente una differenza positiva, ma è meno certa che la differenza superi 5 punti, perché questa seconda condizione è più esigente. L’ampiezza sulla scala originaria è descritta da <span class="math inline">\(\Delta\)</span>; <span class="math inline">\(d\)</span> esprime la stessa differenza rispetto alla dispersione residua comune e può essere utile per confronti tra studi. Se i gruppi sono osservazionali, nessuna di queste quantità dimostra che l’appartenenza a B causi il cambiamento dell’outcome.</p>
</div>
</div>
</div>
</section><section id="esercizio-3-la-quantità-sostantiva-è-invariabile-rispetto-alla-codifica" class="level3 unnumbered unlisted"><h3 class="unnumbered unlisted anchored" data-anchor-id="esercizio-3-la-quantità-sostantiva-è-invariabile-rispetto-alla-codifica">Esercizio 3 — La quantità sostantiva è invariabile rispetto alla codifica</h3>
<p><em>15 minuti · Codice: guidato</em></p>
<p>Supponi di avere adattato due modelli equivalenti, uno con codifica dummy e uno a medie di cella.</p>
<p>Nel modello dummy:</p>
<p><span class="math display">\[
\alpha=80,\qquad \beta=7.
\]</span></p>
<p>Nel modello a medie di cella:</p>
<p><span class="math display">\[
\gamma_A=80,\qquad \gamma_B=87.
\]</span></p>
<ol type="1">
<li>Ricostruisci <span class="math inline">\(\mu_A\)</span>, <span class="math inline">\(\mu_B\)</span> e <span class="math inline">\(\Delta\)</span> in entrambi i casi.</li>
<li>Quali coefficienti cambiano significato?</li>
<li>Quali quantità rimangono identiche?</li>
<li>Perché, in un’analisi bayesiana, non basta cambiare formula mantenendo arbitrariamente gli stessi prior numerici sui coefficienti?</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled" title="Suggerimento">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Consiglio</span>Suggerimento
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Con la codifica dummy, la media di B è una somma di coefficienti. Con le medie di cella, le due medie sono coefficienti diretti.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Soluzione commentata">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Soluzione commentata
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Nel primo modello <span class="math inline">\(\mu_A=80\)</span>, <span class="math inline">\(\mu_B=80+7=87\)</span> e <span class="math inline">\(\Delta=7\)</span>. Nel secondo <span class="math inline">\(\mu_A=80\)</span>, <span class="math inline">\(\mu_B=87\)</span> e <span class="math inline">\(\Delta=87-80=7\)</span>. I coefficienti hanno coordinate diverse, ma le quantità sostantive sono identiche. In Bayes, tuttavia, prior indipendenti assegnati a coordinate diverse possono indurre distribuzioni diverse su medie e contrasti; per ottenere modelli sostantivamente equivalenti occorre trasformare coerentemente anche i prior.</p>
</div>
</div>
</div>
</section><section id="esercizio-4-preparare-il-passaggio-a-tre-gruppi" class="level3 unnumbered unlisted"><h3 class="unnumbered unlisted anchored" data-anchor-id="esercizio-4-preparare-il-passaggio-a-tre-gruppi">Esercizio 4 — Preparare il passaggio a tre gruppi</h3>
<p><em>10 minuti · Codice: no</em></p>
<p>Immagina ora tre gruppi, A, B e C, e la formula</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">score</span> <span class="op">~</span> <span class="fl">0</span> <span class="op">+</span> <span class="va">gruppo</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
<ol type="1">
<li>Quante colonne contiene la matrice del modello?</li>
<li>Che cosa rappresentano i tre coefficienti?</li>
<li>Scrivi i contrasti <span class="math inline">\(B-A\)</span>, <span class="math inline">\(C-A\)</span> e <span class="math inline">\(C-B\)</span>.</li>
<li>Perché l’aggiunta del terzo gruppo non richiede una nuova teoria statistica?</li>
<li>Quale problema nasce se si iniziano a esaminare molti contrasti senza avere chiarito prima quali rispondono alla domanda scientifica?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Soluzione commentata">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Soluzione commentata
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La matrice contiene tre colonne indicatrici, una per ciascun gruppo. I tre coefficienti rappresentano direttamente <span class="math inline">\(\mu_A\)</span>, <span class="math inline">\(\mu_B\)</span> e <span class="math inline">\(\mu_C\)</span>. I contrasti sono <span class="math inline">\(\mu_B-\mu_A\)</span>, <span class="math inline">\(\mu_C-\mu_A\)</span> e <span class="math inline">\(\mu_C-\mu_B\)</span>. La struttura rimane quella del modello lineare: cambia soltanto il numero di colonne e quindi il numero di medie rappresentate. Con molti gruppi diventa però essenziale definire in anticipo quali contrasti sono scientificamente rilevanti, invece di interpretare indiscriminatamente tutte le differenze possibili.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Informazioni sull'ambiente di sviluppo">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Informazioni sull’ambiente di sviluppo
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Mostra/Nascondi codice</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; R version 4.6.1 (2026-06-24)</span></span>
<span><span class="co">#&gt; Platform: aarch64-apple-darwin23</span></span>
<span><span class="co">#&gt; Running under: macOS Tahoe 26.6.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Matrix products: default</span></span>
<span><span class="co">#&gt; BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib </span></span>
<span><span class="co">#&gt; LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; locale:</span></span>
<span><span class="co">#&gt; [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; time zone: Europe/Zagreb</span></span>
<span><span class="co">#&gt; tzcode source: internal</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; attached base packages:</span></span>
<span><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; other attached packages:</span></span>
<span><span class="co">#&gt;  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          </span></span>
<span><span class="co">#&gt;  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         </span></span>
<span><span class="co">#&gt;  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        </span></span>
<span><span class="co">#&gt; [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      </span></span>
<span><span class="co">#&gt; [13] loo_2.10.1            rstan_2.32.7          StanHeaders_2.32.10  </span></span>
<span><span class="co">#&gt; [16] brms_2.23.1           Rcpp_1.1.2            sessioninfo_1.2.4    </span></span>
<span><span class="co">#&gt; [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    </span></span>
<span><span class="co">#&gt; [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          </span></span>
<span><span class="co">#&gt; [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           </span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span><span class="co">#&gt;  [1] gridExtra_2.3.1      inline_0.3.21        rlang_1.3.0         </span></span>
<span><span class="co">#&gt;  [4] magrittr_2.0.5       snakecase_0.11.1     otel_0.2.0          </span></span>
<span><span class="co">#&gt;  [7] compiler_4.6.1       reshape2_1.4.5       vctrs_0.7.3         </span></span>
<span><span class="co">#&gt; [10] stringr_1.6.0        pkgconfig_2.0.3      arrayhelpers_1.1-2  </span></span>
<span><span class="co">#&gt; [13] fastmap_1.2.0        backports_1.5.1      labeling_0.4.3      </span></span>
<span><span class="co">#&gt; [16] cmdstanr_0.9.0       rmarkdown_2.31       tzdb_0.5.0          </span></span>
<span><span class="co">#&gt; [19] ps_1.9.3             haven_2.5.5          purrr_1.2.2         </span></span>
<span><span class="co">#&gt; [22] xfun_0.60            cachem_1.1.0         jsonlite_2.0.0      </span></span>
<span><span class="co">#&gt; [25] broom_1.0.13         parallel_4.6.1       R6_2.6.1            </span></span>
<span><span class="co">#&gt; [28] stringi_1.8.9        RColorBrewer_1.1-3   lubridate_1.9.5     </span></span>
<span><span class="co">#&gt; [31] estimability_2.0.0   knitr_1.51           R.utils_2.13.0      </span></span>
<span><span class="co">#&gt; [34] readr_2.2.0          Matrix_1.7-6         timechange_0.4.0    </span></span>
<span><span class="co">#&gt; [37] tidyselect_1.2.1     abind_1.4-8          yaml_2.3.12         </span></span>
<span><span class="co">#&gt; [40] codetools_0.2-20     processx_3.9.0       curl_7.1.0          </span></span>
<span><span class="co">#&gt; [43] pkgbuild_1.4.8       plyr_1.8.9           lattice_0.22-9      </span></span>
<span><span class="co">#&gt; [46] bridgesampling_1.2-1 S7_0.2.2             coda_0.19-4.1       </span></span>
<span><span class="co">#&gt; [49] evaluate_1.0.5       RcppParallel_6.2.0   pillar_1.11.1       </span></span>
<span><span class="co">#&gt; [52] tensorA_0.36.2.1     checkmate_2.3.4      stats4_4.6.1        </span></span>
<span><span class="co">#&gt; [55] distributional_0.8.1 generics_0.1.4       rprojroot_2.1.1     </span></span>
<span><span class="co">#&gt; [58] hms_1.1.4            rstantools_2.7.0     scales_1.4.0        </span></span>
<span><span class="co">#&gt; [61] xtable_1.8-8         glue_1.8.1           emmeans_2.0.4       </span></span>
<span><span class="co">#&gt; [64] tools_4.6.1          data.table_1.18.4    forcats_1.0.1       </span></span>
<span><span class="co">#&gt; [67] mvtnorm_1.4-2        grid_4.6.1           QuickJSR_1.10.0     </span></span>
<span><span class="co">#&gt; [70] nlme_3.1-170         cli_3.6.6            textshaping_1.0.5   </span></span>
<span><span class="co">#&gt; [73] svUnit_1.0.8         Brobdingnag_1.2-9    V8_8.2.0            </span></span>
<span><span class="co">#&gt; [76] gtable_0.3.6         R.methodsS3_1.8.2    digest_0.6.39       </span></span>
<span><span class="co">#&gt; [79] htmlwidgets_1.6.4    farver_2.1.2         memoise_2.0.1       </span></span>
<span><span class="co">#&gt; [82] htmltools_0.5.9      R.oo_1.27.1          lifecycle_1.0.5</span></span></code></pre></div><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</div>
</div>
</div>
</section></section><section id="bibliografia" class="level2 unnumbered unlisted"><h2 class="unnumbered unlisted anchored" data-anchor-id="bibliografia">Bibliografia</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-caudek2001statistica" class="csl-entry" role="listitem">
Caudek, C., &amp; Luccio, R. (2001). <em>Statistica per psicologi</em> (III rist. 2023, Vol. 11, p. 320). Laterza.
</div>
<div id="ref-gelman2021regression" class="csl-entry" role="listitem">
Gelman, A., Hill, J., &amp; Vehtari, A. (2021). <em>Regression and other stories</em>. Cambridge University Press.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiato!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiato!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^(?:https?:)?//ccaudek\.github\.io/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../../chapters/modelli/05_inferenza_su_una_media.html" class="pagination-link" aria-label="Inferenza su una media: il modello a sola intercetta">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Inferenza su una media: il modello a sola intercetta</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/modelli/07_piu_gruppi_contrasti_anova.html" class="pagination-link" aria-label="Più gruppi: medie di cella, contrasti e ANOVA">
        <span class="nav-page-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Più gruppi: medie di cella, contrasti e ANOVA</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>Companion digitale</strong> del manuale UTET <em>Inferenza bayesiana in psicologia: Ragionare con l’incertezza</em>.</p>
</div>   
    <div class="nav-footer-center">

<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ccaudek/utet-companion/issues/new" class="toc-action"><i class="bi bi-github"></i>Segnala un problema</a></li></ul></div><div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Preferenze cookie</a></div></div>
    <div class="nav-footer-right">
<p>Realizzato con <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>