{
  "hash": "ac77727e084ea1086ef4dba94dda3228",
  "result": {
    "engine": "knitr",
    "markdown": "# Distribuzione predittiva a priori {#sec-prior-predictive-check}\n\n::: {.callout-note appearance=\"minimal\"}\n\nQuesto materiale approfondisce il capitolo 14 del manuale e introduce uno degli strumenti più caratteristici del workflow bayesiano: la distribuzione predittiva a priori.\n\nUn prior è definito sulla scala dei parametri, ma spesso è difficile valutarne il significato sostantivo osservandolo soltanto su quella scala. La domanda più concreta è un'altra: **quali dati renderebbe plausibili questo prior, una volta inserito nel modello?**\n\nLa distribuzione predittiva a priori risponde precisamente a questa domanda. Combina il prior con il modello generativo e descrive i dati che potremmo osservare prima di avere visto quelli reali. I controlli predittivi a priori (*prior predictive checks*) permettono così di verificare se l'intera specificazione iniziale produce valori, ordini di grandezza e regolarità compatibili con la conoscenza del fenomeno [@gelman2020bayesianworkflow; @gabry2019visualization].\n:::\n\n::: {.callout-important appearance=\"minimal\" .chapter-status}\n**Da sapere.** La distribuzione predittiva a priori è una media delle distribuzioni dei dati condizionate ai diversi valori del parametro. Ogni distribuzione viene pesata dalla probabilità che il prior assegna al corrispondente valore del parametro.\n\n**Da saper fare.** Interpretare la formula della distribuzione predittiva a priori; passare dalla versione discreta alla versione continua; distinguere il prior sui parametri dalla predittiva sui dati; valutare se i dati generati dal modello siano sostantivamente plausibili.\n\n**Approfondimento facoltativo.** La formula Beta-Binomiale, il confronto numerico tra calcolo esatto e simulazione e l'implementazione in Stan approfondiscono il calcolo. Nel percorso essenziale è sufficiente comprendere il significato della media ponderata e saper interpretare gli esempi forniti.\n\n[Che cosa significano queste etichette?](../../guida-al-manuale.qmd#sec-percorsi-lettura)\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Prerequisiti\"}\n\n- Sono dati per noti il ruolo del prior, discusso nel @sec-conjugate-families, e l'equilibrio tra prior e verosimiglianza del @sec-bayes-inference-prior.\n- È utile avere familiarità con l'idea di modello generativo e con la media ponderata di possibili risultati.\n- L'@sec-apx-sums e l'@sec-apx-calculus richiamano somme e integrali; l'@sec-apx-prior-predictive-check è utile soltanto per l'implementazione in Stan.\n\n:::\n\n::: {.callout-caution collapse=\"true\" title=\"Preparazione del notebook\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |>\n  source()\nconflicts_prefer(posterior::match)\nconflicts_prefer(dplyr::count)\n```\n:::\n\n:::\n\n## Dal prior ai dati possibili\n\nSupponiamo di avere specificato un modello con parametro $\\theta$ e distribuzione a priori $p(\\theta)$. Prima di osservare i dati reali possiamo porre una domanda predittiva:\n\n> Se usassimo ora il modello per generare nuovi dati, quali risultati produrrebbe e con quale probabilità?\n\nNon possiamo rispondere scegliendo un solo valore di $\\theta$, perché il prior rappresenta proprio la nostra incertezza iniziale sul parametro. Dobbiamo considerare tutti i valori contemplati dal prior e, per ciascuno di essi, i dati che il modello potrebbe generare. La distribuzione predittiva a priori è\n\n$$\np(\\tilde y)\n=\n\\int p(\\tilde y\\mid\\theta)\\,p(\\theta)\\,d\\theta,\n$$ {#eq-prior-predictive-distribution}\n\ndove $\\tilde y$ indica un dato futuro, o un intero insieme di dati futuri. Il termine $p(\\theta)$ esprime quanto sono plausibili a priori i diversi valori del parametro; $p(\\tilde y\\mid\\theta)$ descrive invece quali dati verrebbero generati se il parametro avesse un determinato valore. L'integrale combina tutte queste distribuzioni dei dati, usando il prior come sistema di pesi.\n\n::: {.callout-tip title=\"Come leggere la formula\"}\n\nLa formula può essere letta come una sequenza:\n\n1. considera un possibile valore di $\\theta$;\n2. determina quali dati produrrebbe quel valore;\n3. pesa quella previsione secondo la plausibilità a priori di $\\theta$;\n4. ripeti il procedimento per tutti i valori del parametro;\n5. somma i contributi.\n\nL'integrale non seleziona il valore “migliore” di $\\theta$: **fa una media di tutte le previsioni possibili**.\n:::\n\nIl termine $p(\\tilde y\\mid\\theta)$ ha la stessa forma matematica incontrata parlando di verosimiglianza, ma qui viene letto in una direzione diversa. Nella verosimiglianza i dati osservati sono fissi e la funzione viene esaminata al variare di $\\theta$; nella predizione, invece, $\\theta$ è fissato e osserviamo come varia la distribuzione dei possibili dati $\\tilde y$. Per questo, in questo contesto, è più chiaro parlare di **distribuzione generativa dei dati condizionata al parametro**.\n\n### Un esempio discreto: tre scenari possibili\n\nL'integrale diventa più intuitivo se immaginiamo che $\\theta$ possa assumere soltanto pochi valori. In quel caso la media continua si riduce a una somma:\n\n$$\np(\\tilde y)\n=\n\\sum_j p(\\tilde y\\mid\\theta_j)\\,p(\\theta_j).\n$$ {#eq-prior-predictive-discrete}\n\nSupponiamo che $\\theta$ possa assumere i valori $0.2$, $0.5$ e $0.8$, con le seguenti probabilità a priori:\n\n| $\\theta_j$ | $p(\\theta_j)$ |\n|---:|---:|\n| 0.2 | 0.2 |\n| 0.5 | 0.3 |\n| 0.8 | 0.5 |\n\nVogliamo prevedere il numero $\\tilde y$ di successi in due prove:\n\n$$\n\\tilde y\\mid\\theta_j \\sim \\operatorname{Binomiale}(2,\\theta_j).\n$$\n\nOgni valore di $\\theta_j$ produce una diversa distribuzione sui risultati $\\tilde y=0,1,2$. La tabella seguente mostra sia queste distribuzioni sia il contributo che ciascuna fornisce alla predittiva dopo essere stata moltiplicata per il proprio peso a priori.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntheta_values <- c(0.2, 0.5, 0.8)\nprior_weights <- c(0.2, 0.3, 0.5)\n\nmixture_components <- tidyr::expand_grid(\n  theta = theta_values,\n  y_tilde = 0:2\n) |>\n  mutate(\n    prior_weight = prior_weights[match(theta, theta_values)],\n    p_y_given_theta = dbinom(y_tilde, size = 2, prob = theta),\n    weighted_contribution = prior_weight * p_y_given_theta\n  )\n\nmixture_components |>\n  mutate(\n    across(\n      c(prior_weight, p_y_given_theta, weighted_contribution),\n      ~ round(.x, 3)\n    )\n  ) |>\n  knitr::kable(\n    col.names = c(\n      \"$\\\\theta_j$\",\n      \"$\\\\tilde y$\",\n      \"$p(\\\\theta_j)$\",\n      \"$p(\\\\tilde y\\\\mid\\\\theta_j)$\",\n      \"Contributo pesato\"\n    ),\n    align = c(\"c\", \"c\", \"c\", \"c\", \"c\"),\n    caption = \"Componenti della distribuzione predittiva discreta\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Componenti della distribuzione predittiva discreta\n\n| $\\theta_j$ | $\\tilde y$ | $p(\\theta_j)$ | $p(\\tilde y\\mid\\theta_j)$ | Contributo pesato |\n|:----------:|:----------:|:-------------:|:-------------------------:|:-----------------:|\n|    0.2     |     0      |      0.2      |           0.64            |       0.128       |\n|    0.2     |     1      |      0.2      |           0.32            |       0.064       |\n|    0.2     |     2      |      0.2      |           0.04            |       0.008       |\n|    0.5     |     0      |      0.3      |           0.25            |       0.075       |\n|    0.5     |     1      |      0.3      |           0.50            |       0.150       |\n|    0.5     |     2      |      0.3      |           0.25            |       0.075       |\n|    0.8     |     0      |      0.5      |           0.04            |       0.020       |\n|    0.8     |     1      |      0.5      |           0.32            |       0.160       |\n|    0.8     |     2      |      0.5      |           0.64            |       0.320       |\n\n\n:::\n:::\n\n\nPer ottenere la probabilità predittiva di ciascun risultato sommiamo i contributi relativi allo stesso valore di $\\tilde y$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprior_predictive_discrete <- mixture_components |>\n  group_by(y_tilde) |>\n  summarise(\n    prior_predictive_probability = sum(weighted_contribution),\n    .groups = \"drop\"\n  )\n\nprior_predictive_discrete |>\n  mutate(\n    prior_predictive_probability = round(\n      prior_predictive_probability,\n      3\n    )\n  ) |>\n  knitr::kable(\n    col.names = c(\n      \"$\\\\tilde y$\",\n      \"$p(\\\\tilde y)$\"\n    ),\n    align = c(\"c\", \"c\"),\n    caption = \"Distribuzione predittiva a priori\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Distribuzione predittiva a priori\n\n| $\\tilde y$ | $p(\\tilde y)$ |\n|:----------:|:-------------:|\n|     0      |     0.223     |\n|     1      |     0.374     |\n|     2      |     0.403     |\n\n\n:::\n:::\n\n\nI calcoli sono:\n\n$$\n\\begin{aligned}\np(\\tilde y=0)\n&=0.2(0.64)+0.3(0.25)+0.5(0.04)=0.223,\\\\\np(\\tilde y=1)\n&=0.2(0.32)+0.3(0.50)+0.5(0.32)=0.374,\\\\\np(\\tilde y=2)\n&=0.2(0.04)+0.3(0.25)+0.5(0.64)=0.403.\n\\end{aligned}\n$$\n\n::: {.callout-important title=\"Il punto essenziale\"}\n\nPer calcolare $p(\\tilde y=2)$ non scegliamo tra $\\theta=0.2$, $0.5$ e $0.8$. Calcoliamo la probabilità di due successi sotto **ciascuno** dei tre scenari e poi facciamo una media usando i pesi del prior.\n\nIl valore $\\theta=0.8$ contribuisce maggiormente perché rende due successi abbastanza probabili e, nello stesso tempo, riceve il peso a priori più elevato.\n:::\n\nLa stessa idea può essere vista graficamente. I primi tre pannelli della @fig-prior-predictive-discrete-mixture mostrano le distribuzioni condizionate ai singoli valori del parametro; l'ultimo mostra la loro media ponderata.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npredictive_plot_data <- bind_rows(\n  mixture_components |>\n    transmute(\n      y_tilde,\n      probability = p_y_given_theta,\n      distribution = paste0(\"Se theta = \", theta)\n    ),\n  prior_predictive_discrete |>\n    transmute(\n      y_tilde,\n      probability = prior_predictive_probability,\n      distribution = \"Media ponderata: predittiva\"\n    )\n)\n\npredictive_plot_data |>\n  ggplot(aes(x = factor(y_tilde), y = probability)) +\n  geom_col(fill = PRIMARY, alpha = 0.85) +\n  facet_wrap(~distribution, nrow = 1) +\n  labs(\n    x = \"Numero futuro di successi\",\n    y = \"Probabilità\",\n    title = \"La predittiva è una media di distribuzioni\",\n    subtitle = \"I pesi sono le probabilità a priori dei valori di theta\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzioni binomiali condizionate ai tre valori possibili di θ e loro media ponderata. L'ultimo pannello mostra la distribuzione predittiva a priori ottenuta combinando le tre componenti con i pesi assegnati dal prior.](05_prior_pred_distr_files/figure-html/fig-prior-predictive-discrete-mixture-1.png){#fig-prior-predictive-discrete-mixture fig-align='center' fig-alt='Quattro grafici a barre affiancati. I primi tre mostrano la distribuzione del numero di successi per theta uguale a 0.2, 0.5 e 0.8; il quarto mostra la media ponderata delle tre distribuzioni.' width=85%}\n:::\n:::\n\n\nLa distribuzione finale non coincide necessariamente con nessuna delle tre componenti. È una nuova distribuzione, ottenuta combinandole.\n\nQuando $\\theta$ può assumere infiniti valori continui non possiamo elencarli uno per uno. La logica, però, rimane identica:\n\n$$\n\\underbrace{\n\\sum_j p(\\tilde y\\mid\\theta_j)p(\\theta_j)\n}_{\\text{parametro discreto}}\n\\quad\\longrightarrow\\quad\n\\underbrace{\n\\int p(\\tilde y\\mid\\theta)p(\\theta)d\\theta\n}_{\\text{parametro continuo}}.\n$$\n\nL'integrale è semplicemente la versione continua della media ponderata appena costruita.\n\n::: {.callout-warning title=\"Tre interpretazioni da non confondere\"}\n\nLa formula **non**:\n\n- calcola una posterior, perché non sono ancora stati osservati dati;\n- sostituisce $\\theta$ con la media del prior;\n- sceglie il valore di $\\theta$ con densità a priori più alta.\n\nCombina invece tutte le distribuzioni $p(\\tilde y\\mid\\theta)$ nella misura indicata dal prior.\n:::\n\nQuesta media incorpora due fonti di incertezza. La prima riguarda il parametro: non conosciamo $\\theta$ e il prior attribuisce plausibilità a valori diversi. La seconda riguarda i dati: anche conoscendo esattamente $\\theta$, repliche differenti del processo non produrrebbero necessariamente lo stesso risultato. Per esempio, con $\\theta=0.8$ non otteniamo sempre otto successi su dieci; la distribuzione binomiale rappresenta questa variabilità residua.\n\n::: {.callout-tip title=\"Perché non basta usare la media del prior?\"}\n\nSostituire $\\theta$ con $E(\\theta)$ conserva il centro del prior, ma elimina l'incertezza sui parametri. In generale,\n\n$$\np(\\tilde y)\n\\neq\np\\!\\left(\\tilde y\\mid E(\\theta)\\right).\n$$\n\nLa differenza è particolarmente importante quando il prior è molto disperso o quando il modello è non lineare.\n:::\n\n## Come il prior modella i dati plausibili\n\nConsideriamo ora un test di dieci domande. Il parametro $\\theta$ rappresenta la probabilità di risposta corretta e il numero futuro di risposte corrette segue il modello\n\n$$\n\\tilde y\\mid\\theta\\sim\\operatorname{Binomiale}(10,\\theta).\n$$\n\nPoniamo\n\n$$\n\\theta\\sim\\operatorname{Beta}(10,3).\n$$\n\nIl prior ha media\n\n$$\nE(\\theta)=\\frac{10}{13}\\approx 0.77,\n$$\n\ne concentrazione $10+3=13$. Prima di osservare il test, il modello considera quindi più plausibili probabilità di risposta corretta relativamente alte, pur mantenendo una certa incertezza.\n\nIntegrando $\\theta$ otteniamo la distribuzione predittiva del numero di risposte corrette. La @fig-prior-predictive-beta-binomial ne mostra la forma: la massa è concentrata soprattutto sui punteggi elevati, ma rimane possibile una gamma abbastanza ampia di risultati.\n\n::: {.callout-note collapse=\"true\" title=\"Approfondimento: la formula Beta-Binomiale\"}\n\nNel modello Beta-Binomiale la distribuzione predittiva può essere calcolata esattamente:\n\n$$\np(\\tilde y=k)\n=\n\\binom{10}{k}\n\\frac{B(k+10,10-k+3)}{B(10,3)},\n\\qquad k=0,\\ldots,10,\n$$\n\ndove $B(\\cdot,\\cdot)$ è la funzione beta. La formula è riportata qui per completezza; per seguire il ragionamento è sufficiente interpretare la distribuzione mostrata nel grafico successivo.\n\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndbeta_binomial <- function(y, size, alpha, beta) {\n  exp(\n    lchoose(size, y) +\n      lbeta(y + alpha, size - y + beta) -\n      lbeta(alpha, beta)\n  )\n}\n\nprior_predictive_beta_binomial <- tibble(\n  y_tilde = 0:10,\n  probability = dbeta_binomial(\n    y = 0:10,\n    size = 10,\n    alpha = 10,\n    beta = 3\n  )\n)\n\nprior_predictive_beta_binomial |>\n  ggplot(aes(x = y_tilde, y = probability)) +\n  geom_col(fill = PRIMARY, alpha = 0.85) +\n  scale_x_continuous(breaks = 0:10) +\n  labs(\n    x = \"Numero futuro di risposte corrette\",\n    y = \"Probabilità\",\n    title = \"Distribuzione predittiva a priori\",\n    subtitle = \"theta ~ Beta(10, 3); y-tilde | theta ~ Binomiale(10, theta)\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzione predittiva a priori del numero di risposte corrette in dieci domande, ottenuta combinando un modello binomiale con un prior Beta(10, 3) sulla probabilità di risposta corretta.](05_prior_pred_distr_files/figure-html/fig-prior-predictive-beta-binomial-1.png){#fig-prior-predictive-beta-binomial fig-align='center' fig-alt='Grafico a barre della probabilità predittiva per un numero di risposte corrette compreso tra zero e dieci. La massa è concentrata soprattutto sui punteggi elevati.' width=85%}\n:::\n:::\n\n\nPossiamo riassumere alcune delle conseguenze sostantive della specificazione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprior_predictive_summary <- prior_predictive_beta_binomial |>\n  summarise(\n    media = sum(y_tilde * probability),\n    prob_da_6_a_10 = sum(probability[y_tilde >= 6]),\n    prob_da_0_a_2 = sum(probability[y_tilde <= 2]),\n    prob_10 = probability[y_tilde == 10]\n  )\n\nprior_predictive_summary |>\n  mutate(across(everything(), ~ round(.x, 3))) |>\n  knitr::kable(\n    col.names = c(\n      \"Numero medio corretto\",\n      \"$P(\\\\tilde y \\\\geq 6)$\",\n      \"$P(\\\\tilde y \\\\leq 2)$\",\n      \"$P(\\\\tilde y = 10)$\"\n    ),\n    align = rep(\"c\", 4),\n    caption = \"Alcune implicazioni della specificazione a priori\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Alcune implicazioni della specificazione a priori\n\n| Numero medio corretto | $P(\\tilde y \\geq 6)$ | $P(\\tilde y \\leq 2)$ | $P(\\tilde y = 10)$ |\n|:---------------------:|:--------------------:|:--------------------:|:------------------:|\n|         7.69          |        0.887         |        0.005         |       0.143        |\n\n\n:::\n:::\n\n\nIl modello prevede in media circa 7.69 risposte corrette. Assegna probabilità 88.7% a un risultato compreso tra 6 e 10, e soltanto 0.5% a un risultato compreso tra 0 e 2.\n\nUn punteggio perfetto non è tuttavia trascurabile: $P(\\tilde y=10)$ è circa 14.3%. Questa conseguenza può essere appropriata oppure no; dipende da ciò che sappiamo sul test. Il controllo predittivo serve precisamente a renderla visibile.\n\n::: {.callout-important title=\"Valutare le conseguenze, non soltanto il centro del prior\"}\n\nDire che il prior $\\operatorname{Beta}(10,3)$ ha media $0.77$ non basta per giudicarlo ragionevole. Bisogna chiedersi anche se le sue conseguenze sulla scala osservabile siano plausibili. Se un punteggio perfetto dovrebbe essere molto raro, questa specificazione potrebbe essere troppo permissiva nella regione alta, nonostante una media apparentemente sensata.\n:::\n\nIl prior si trasmette ai dati attraverso due proprietà distinte: la **posizione**, cioè quali valori del parametro favorisce, e la **concentrazione**, cioè quanto strettamente si raccoglie intorno a quei valori.\n\n**Stessa media, diversa concentrazione.** Confrontiamo $\\operatorname{Beta}(3,1)$ e $\\operatorname{Beta}(30,10)$. Entrambi hanno media $0.75$, ma il primo ha concentrazione 4 e il secondo concentrazione 40. Il centro è lo stesso; cambia l'incertezza ammessa su $\\theta$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprior_strength_comparison <- bind_rows(\n  tibble(\n    y_tilde = 0:10,\n    probability = dbeta_binomial(0:10, 10, 3, 1),\n    prior = \"Beta(3, 1): concentrazione 4\"\n  ),\n  tibble(\n    y_tilde = 0:10,\n    probability = dbeta_binomial(0:10, 10, 30, 10),\n    prior = \"Beta(30, 10): concentrazione 40\"\n  )\n)\n\nprior_strength_comparison |>\n  ggplot(aes(x = y_tilde, y = probability, fill = prior)) +\n  geom_col(show.legend = FALSE) +\n  facet_wrap(~prior, nrow = 1) +\n  scale_fill_qualitative() +\n  scale_x_continuous(breaks = 0:10) +\n  labs(\n    x = \"Numero futuro di risposte corrette\",\n    y = \"Probabilità\",\n    title = \"Stessa media del prior, diversa forza informativa\",\n    subtitle = \"La predittiva più debole assegna maggiore massa agli esiti lontani dal centro\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzioni predittive a priori prodotte da due prior Beta con la stessa media ma concentrazione diversa. Il prior meno concentrato genera una distribuzione dei punteggi più dispersa e assegna maggiore probabilità agli esiti lontani dal centro.](05_prior_pred_distr_files/figure-html/fig-prior-predictive-strength-comparison-1.png){#fig-prior-predictive-strength-comparison fig-align='center' fig-alt='Due grafici a barre affiancati confrontano le distribuzioni predittive ottenute da Beta(3, 1) e Beta(30, 10). La prima è più dispersa, la seconda più concentrata attorno ai punteggi alti.' width=85%}\n:::\n:::\n\n\nLe due predittive hanno lo stesso valore atteso, ma non la stessa dispersione. Il prior meno concentrato consente valori di $\\theta$ più diversi tra loro e produce quindi una gamma più ampia di punteggi plausibili.\n\n**Stessa concentrazione, diversa media.** Confrontiamo ora $\\operatorname{Beta}(3,9)$ e $\\operatorname{Beta}(9,3)$. Entrambi hanno concentrazione 12, ma il primo ha media $0.25$ e il secondo media $0.75$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprior_location_comparison <- bind_rows(\n  tibble(\n    y_tilde = 0:10,\n    probability = dbeta_binomial(0:10, 10, 3, 9),\n    prior = \"Beta(3, 9): media 0.25\"\n  ),\n  tibble(\n    y_tilde = 0:10,\n    probability = dbeta_binomial(0:10, 10, 9, 3),\n    prior = \"Beta(9, 3): media 0.75\"\n  )\n)\n\nprior_location_comparison |>\n  ggplot(aes(x = y_tilde, y = probability, fill = prior)) +\n  geom_col(show.legend = FALSE) +\n  facet_wrap(~prior, nrow = 1) +\n  scale_fill_qualitative() +\n  scale_x_continuous(breaks = 0:10) +\n  labs(\n    x = \"Numero futuro di risposte corrette\",\n    y = \"Probabilità\",\n    title = \"Stessa forza informativa, diversa posizione\",\n    subtitle = \"Cambiare il centro del prior sposta i dati che il modello considera plausibili\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribuzioni predittive a priori prodotte da due prior Beta con la stessa concentrazione ma media diversa. Lo spostamento del centro del prior modifica direttamente la regione dei punteggi considerati più plausibili.](05_prior_pred_distr_files/figure-html/fig-prior-predictive-location-comparison-1.png){#fig-prior-predictive-location-comparison fig-align='center' fig-alt='Due grafici a barre affiancati confrontano le distribuzioni predittive ottenute da Beta(3, 9) e Beta(9, 3). La prima privilegia punteggi bassi, la seconda punteggi alti.' width=85%}\n:::\n:::\n\n\nIn questo caso è la regione dei punteggi plausibili a spostarsi: la predittiva riflette direttamente il diverso centro assegnato al parametro. Questi confronti mostrano perché etichette generiche come “prior vago” o “prior informativo” non bastano. Occorre specificare **dove** il prior concentra la massa e **quanto** è concentrato.\n\n## Usare la predittiva per controllare il modello\n\nFinora abbiamo descritto la distribuzione predittiva. Per usarla come strumento diagnostico dobbiamo saperla generare e confrontarne le conseguenze con quello che sappiamo del fenomeno.\n\nQuando il modello lo consente, la predittiva può essere calcolata analiticamente. Più in generale, può essere approssimata mediante simulazione:\n\n$$\n\\theta^{(s)}\\sim p(\\theta),\n\\qquad\n\\tilde y^{(s)}\\sim p(\\tilde y\\mid\\theta^{(s)}),\n\\qquad s=1,\\ldots,S.\n$$\n\nOgni replica compie due passaggi: estrae un possibile valore del parametro dal prior e genera un possibile dato condizionato a quel valore. La distribuzione empirica degli $\\tilde y^{(s)}$ approssima così l'integrale della @eq-prior-predictive-distribution.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\nnumber_of_draws <- 20000\n\nprior_draws <- rbeta(number_of_draws, shape1 = 10, shape2 = 3)\npredictive_draws <- rbinom(\n  number_of_draws,\n  size = 10,\n  prob = prior_draws\n)\n\nsimulated_probabilities <- tibble(y_tilde = predictive_draws) |>\n  count(y_tilde, name = \"frequency\") |>\n  tidyr::complete(y_tilde = 0:10, fill = list(frequency = 0)) |>\n  mutate(probability_simulated = frequency / sum(frequency))\n\nexact_and_simulated <- prior_predictive_beta_binomial |>\n  rename(probability_exact = probability) |>\n  left_join(simulated_probabilities, by = \"y_tilde\")\n\nexact_and_simulated |>\n  ggplot(aes(x = probability_exact, y = probability_simulated)) +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\", linewidth = 0.6) +\n  geom_point(size = 3, color = PRIMARY, alpha = 0.9) +\n  coord_equal() +\n  labs(\n    x = \"Probabilità esatta\",\n    y = \"Frequenza simulata\",\n    title = \"Calcolo esatto e simulazione a confronto\",\n    subtitle = \"Punteggi da 0 a 10\"\n  )\n```\n\n::: {.cell-output-display}\n![Confronto tra le probabilità predittive Beta-Binomiali calcolate esattamente e le frequenze relative ottenute mediante simulazione. La vicinanza dei punti alla diagonale indica che la simulazione approssima accuratamente la distribuzione esatta.](05_prior_pred_distr_files/figure-html/fig-prior-predictive-exact-simulation-1.png){#fig-prior-predictive-exact-simulation fig-align='center' fig-alt='Diagramma di dispersione delle probabilità esatte contro le frequenze simulate. I punti relativi agli undici possibili punteggi si dispongono vicino alla diagonale di uguaglianza.' width=75%}\n:::\n:::\n\n\nLa vicinanza dei punti alla diagonale nella @fig-prior-predictive-exact-simulation mostra che il calcolo esatto e la simulazione descrivono la stessa distribuzione. La simulazione non introduce un principio nuovo: è il modo di eseguire la media quando l'integrale non ha forma chiusa.\n\nUn controllo predittivo a priori non valuta il prior isolatamente, ma l'intera specificazione generativa:\n\n$$\n\\text{prior sui parametri}\n+\n\\text{modello dei dati}\n+\n\\text{scala osservabile}.\n$$\n\nUn prior può sembrare ragionevole sulla scala di un coefficiente e produrre tuttavia dati assurdi dopo essere stato propagato attraverso una funzione di collegamento, una struttura gerarchica o una distribuzione inadeguata. Il controllo deve quindi interrogare almeno quattro aspetti.\n\n| Aspetto | Domande da porre |\n|:---|:---|\n| **Vincoli e supporto** | I dati simulati rispettano i limiti logici e fisici del fenomeno? Un modello per conteggi produce soltanto interi non negativi? Un modello per proporzioni produce valori compresi tra 0 e 1? |\n| **Ordine di grandezza** | I valori simulati hanno una scala realistica? I tempi di reazione sono dell'ordine dei millisecondi o di molte ore? I punteggi sono compatibili con il range dello strumento? |\n| **Dispersione ed estremi** | Il modello rende comuni eventi che dovrebbero essere eccezionali? Oppure esclude quasi completamente eventi che sappiamo essere possibili? |\n| **Struttura dei dati** | Nei modelli complessi, le simulazioni riproducono forme plausibili di asimmetria, eterogeneità tra persone, correlazione, frequenza degli zeri o dipendenza temporale? |\n\n::: {.callout-tip title=\"La domanda guida\"}\n\nSe un esperto del fenomeno osservasse questi dati senza sapere che sono simulati, li considererebbe almeno plausibili?\n\nIl controllo non richiede che le simulazioni anticipino esattamente i dati che saranno osservati. Richiede che non contraddicano in modo evidente ciò che è già noto o i vincoli del problema.\n:::\n\nIl workflow può essere riassunto in cinque passaggi:\n\n1. **specificare** il prior e il modello generativo;\n2. **generare** valori dei parametri dal prior;\n3. **generare** dati condizionati a quei parametri;\n4. **valutare** le conseguenze sulla scala osservabile;\n5. **rivedere** la specificazione quando le conseguenze sono implausibili.\n\nLa revisione non serve a costruire un prior che anticipi i dati reali: serve a eliminare specificazioni incoerenti, troppo permissive o incompatibili con quanto già si sa.\n\n::: {.callout-caution title=\"Uso dei dati e trasparenza\"}\n\nÈ preferibile svolgere il controllo predittivo a priori prima di adattare il modello ai dati in esame. Nella pratica, tuttavia, la costruzione del modello può essere iterativa e alcune revisioni possono avvenire dopo avere osservato caratteristiche dei dati.\n\nIn quel caso la revisione deve essere dichiarata come esplorativa. Le conclusioni possono essere valutate mediante analisi di sensibilità, dati tenuti da parte, nuove osservazioni o repliche. Non è corretto descrivere come completamente pre-specificata una scelta formulata dopo avere esaminato i dati.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Approfondimento: implementazione essenziale in Stan\"}\n\nIl codice seguente rende esplicita la stessa sequenza usata nella simulazione manuale.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbinomial_prior_predictive_stan <- '\ndata {\n  int<lower=1> N;\n  int<lower=1> n_items;\n}\nparameters {\n  real<lower=0, upper=1> theta;\n}\nmodel {\n  theta ~ beta(10, 3);\n}\ngenerated quantities {\n  array[N] int y_tilde;\n  for (i in 1:N) {\n    y_tilde[i] = binomial_rng(n_items, theta);\n  }\n}\n'\n```\n:::\n\n\nIl blocco `model` definisce una distribuzione target che, in assenza di dati osservati, coincide con il prior su $\\theta$. Il campionatore genera quindi valori di $\\theta$ da questa distribuzione. Nel blocco `generated quantities`, ogni valore estratto viene trasformato in possibili dati mediante `binomial_rng()`. Non compare alcuna osservazione reale e non viene calcolata una posterior.\n:::\n\n## Riflessioni conclusive {.unnumbered .unlisted}\n\nLa distribuzione predittiva a priori traduce una distribuzione astratta sui parametri in una distribuzione concreta sui dati osservabili. Il suo significato può essere compreso partendo dalla versione discreta:\n\n$$\np(\\tilde y)\n=\n\\sum_j p(\\tilde y\\mid\\theta_j)p(\\theta_j).\n$$\n\nPer ogni possibile valore del parametro consideriamo la distribuzione dei dati che esso produrrebbe e facciamo una media usando le probabilità a priori come pesi. Quando il parametro è continuo, la somma diventa un integrale, ma il ragionamento resta identico.\n\nLa predittiva incorpora sia l'incertezza sui parametri sia la variabilità dei dati dato il parametro. Per questo, in generale, non coincide con la distribuzione ottenuta fissando il parametro alla media del prior.\n\nIl controllo predittivo a priori è quindi un controllo sostantivo dell'intero modello generativo: rende visibili conseguenze che sulla sola scala dei parametri sarebbero difficili da intuire, e permette di correggere specificazioni implausibili prima che entrino nell'inferenza.\n\nNel capitolo successivo la stessa struttura verrà utilizzata con pesi diversi. La distribuzione predittiva a posteriori sostituisce $p(\\theta)$ con $p(\\theta\\mid y)$:\n\n$$\np(\\tilde y\\mid y)\n=\n\\int p(\\tilde y\\mid\\theta)p(\\theta\\mid y)d\\theta.\n$$\n\nLa meccanica è la stessa; cambia l'informazione usata per pesare i diversi valori del parametro.\n\n## Esercizi {.unnumbered .unlisted}\n\n### Esercizio 1 — Comprendere {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 10 minuti*\n\nNell'esempio discreto del capitolo, $\\theta$ può assumere i valori $0.2$, $0.5$ e $0.8$, con pesi a priori rispettivamente $0.2$, $0.3$ e $0.5$. Il risultato futuro è il numero di successi in due prove.\n\n1. Spiega con parole tue perché, per calcolare $p(\\tilde y=2)$, occorre considerare tutti e tre i valori di $\\theta$.\n2. Interpreta il termine $0.5\\times0.64$ che compare nel calcolo.\n3. Spiega perché il risultato finale, $p(\\tilde y=2)=0.403$, non è una probabilità relativa al parametro.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\n\nDistingui tre oggetti: il peso a priori di $\\theta=0.8$, la probabilità di due successi condizionata a $\\theta=0.8$ e la probabilità marginale del dato futuro.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\n\nPer calcolare la probabilità di due successi dobbiamo considerare tutti gli scenari ammessi dal prior, perché non sappiamo quale valore di $\\theta$ sia quello pertinente. Ogni scenario produce una probabilità diversa di due successi.\n\nIl termine $0.5\\times0.64$ è il contributo dello scenario $\\theta=0.8$: il prior assegna probabilità 0.5 a questo valore e, se $\\theta=0.8$, la probabilità di due successi è 0.64.\n\nIl valore 0.403 è la probabilità predittiva del dato $\\tilde y=2$. È una probabilità sulla scala dei possibili risultati, ottenuta dopo avere mediato sull'incertezza relativa a $\\theta$.\n:::\n\n### Esercizio 2 — Prevedere {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 5–10 minuti*\n\nQuale delle seguenti frasi interpreta correttamente\n\n$$\np(\\tilde y)=\\int p(\\tilde y\\mid\\theta)p(\\theta)d\\theta?\n$$\n\nA. Si sceglie il valore di $\\theta$ con densità a priori più alta e si usa la sua distribuzione dei dati.\n\nB. Si sostituisce $\\theta$ con la media del prior e si genera una sola distribuzione dei dati.\n\nC. Si combinano le distribuzioni dei dati associate a tutti i valori di $\\theta$, pesandole secondo il prior.\n\nD. Si aggiornano i valori di $\\theta$ usando il dato futuro $\\tilde y$.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\n\nChiediti quale termine della formula svolga la funzione di peso e quale sia l'oggetto sul quale viene fatta la media.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\n\nLa risposta corretta è **C**. Il prior $p(\\theta)$ fornisce i pesi, mentre $p(\\tilde y\\mid\\theta)$ fornisce una distribuzione dei dati per ogni possibile valore del parametro.\n\nA confonde integrazione e massimizzazione; B elimina l'incertezza sui parametri; D descrive un aggiornamento a posteriori, che non appartiene alla distribuzione predittiva a priori.\n:::\n\n### Esercizio 3 — Modificare {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 10 minuti*\n\nNel capitolo sono confrontati i prior $\\operatorname{Beta}(3,1)$ e $\\operatorname{Beta}(30,10)$. Entrambi hanno media 0.75, ma il secondo è molto più concentrato.\n\nSenza eseguire nuovi calcoli, indica quale delle due distribuzioni predittive dovrebbe:\n\n1. avere il valore atteso più alto;\n2. essere più dispersa;\n3. assegnare maggiore probabilità ai risultati lontani da 7–8 successi su 10;\n4. riflettere una maggiore incertezza iniziale su $\\theta$.\n\nGiustifica ogni risposta collegando la forma della predittiva alla forza del prior.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\n\nI due prior hanno lo stesso centro. Cambia soltanto la loro concentrazione.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Soluzione commentata\"}\n\nLe due predittive hanno lo stesso valore atteso, perché i prior hanno la stessa media e il numero di prove è lo stesso.\n\nLa predittiva associata a $\\operatorname{Beta}(3,1)$ è più dispersa e assegna maggiore probabilità ai risultati lontani dal centro. Il prior ha concentrazione 4 e ammette valori di $\\theta$ molto diversi tra loro.\n\nLa predittiva associata a $\\operatorname{Beta}(30,10)$ è più concentrata, perché il prior ha concentrazione 40 e colloca quasi tutta la plausibilità vicino a 0.75.\n:::\n\n### Esercizio 4 — Criticare {.unnumbered .unlisted}\n\n*Codice: no · Tempo indicativo: 10 minuti*\n\nUno studente afferma:\n\n> «La distribuzione predittiva a priori è semplicemente la distribuzione dei dati calcolata usando la media del prior. L'integrale serve soltanto a trovare quella media. Se il prior sul parametro sembra ragionevole, non occorre controllare i dati simulati.»\n\nIndividua almeno due errori nell'affermazione e riscrivila correttamente.\n\n::: {.callout-tip collapse=\"true\" title=\"Suggerimento\"}\n\nConsidera sia il significato dell'integrale sia il fatto che il prior viene propagato attraverso l'intero modello generativo.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Elementi per la risposta\"}\n\nL'integrale non serve a sostituire $\\theta$ con la media del prior. Combina le distribuzioni $p(\\tilde y\\mid\\theta)$ associate a tutti i valori del parametro, usando il prior come insieme di pesi. Fissare $\\theta$ alla media elimina una fonte di incertezza e può produrre una distribuzione diversa.\n\nInoltre, un prior può sembrare plausibile sulla scala del parametro ma produrre dati implausibili quando viene propagato attraverso il modello. Il controllo predittivo valuta quindi le conseguenze osservabili dell'intera specificazione, non soltanto l'aspetto del prior.\n:::\n\n::: {.callout-note collapse=\"true\" title=\"Informazioni sull'ambiente di sviluppo\"}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.6.1 (2026-06-24)\n#> Platform: aarch64-apple-darwin23\n#> Running under: macOS Tahoe 26.6.1\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n#> \n#> locale:\n#> [1] C.UTF-8/UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8\n#> \n#> time zone: Europe/Zagreb\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] ragg_1.5.2            tinytable_0.17.0      withr_3.0.3          \n#>  [4] systemfonts_1.3.2     patchwork_1.3.2       ggdist_3.3.3         \n#>  [7] tidybayes_3.0.7       bayesplot_1.15.0      ggplot2_4.0.3        \n#> [10] reliabilitydiag_0.2.1 priorsense_1.2.0      posterior_1.7.0      \n#> [13] loo_2.10.1            rstan_2.32.7          StanHeaders_2.32.10  \n#> [16] brms_2.23.1           Rcpp_1.1.2            sessioninfo_1.2.4    \n#> [19] conflicted_1.2.0      janitor_2.2.1         matrixStats_1.5.0    \n#> [22] modelr_0.1.11         tibble_3.3.1          dplyr_1.2.1          \n#> [25] tidyr_1.3.2           rio_1.3.0             here_1.0.2           \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] svUnit_1.0.8         tidyselect_1.2.1     farver_2.1.2        \n#>  [4] S7_0.2.2             fastmap_1.2.0        tensorA_0.36.2.1    \n#>  [7] digest_0.6.39        timechange_0.4.0     estimability_2.0.0  \n#> [10] lifecycle_1.0.5      magrittr_2.0.5       compiler_4.6.1      \n#> [13] rlang_1.3.0          tools_4.6.1          yaml_2.3.12         \n#> [16] knitr_1.51           labeling_0.4.3       bridgesampling_1.2-1\n#> [19] htmlwidgets_1.6.4    pkgbuild_1.4.8       curl_7.1.0          \n#> [22] RColorBrewer_1.1-3   abind_1.4-8          purrr_1.2.2         \n#> [25] grid_4.6.1           stats4_4.6.1         xtable_1.8-8        \n#> [28] inline_0.3.21        emmeans_2.0.4        scales_1.4.0        \n#> [31] cli_3.6.6            mvtnorm_1.4-2        rmarkdown_2.31      \n#> [34] generics_0.1.4       otel_0.2.0           RcppParallel_6.2.0  \n#> [37] cachem_1.1.0         stringr_1.6.0        parallel_4.6.1      \n#> [40] vctrs_0.7.3          V8_8.2.0             Matrix_1.7-6        \n#> [43] jsonlite_2.0.0       arrayhelpers_1.1-2   glue_1.8.1          \n#> [46] codetools_0.2-20     distributional_0.8.1 lubridate_1.9.5     \n#> [49] stringi_1.8.9        gtable_0.3.6         QuickJSR_1.10.0     \n#> [52] pillar_1.11.1        htmltools_0.5.9      Brobdingnag_1.2-9   \n#> [55] R6_2.6.1             textshaping_1.0.5    rprojroot_2.1.1     \n#> [58] evaluate_1.0.5       lattice_0.22-9       backports_1.5.1     \n#> [61] memoise_2.0.1        broom_1.0.13         snakecase_0.11.1    \n#> [64] rstantools_2.7.0     coda_0.19-4.1        gridExtra_2.3.1     \n#> [67] nlme_3.1-170         checkmate_2.3.4      xfun_0.60           \n#> [70] pkgconfig_2.0.3\n```\n:::\n\n:::\n\n## Bibliografia {.unnumbered .unlisted}\n",
    "supporting": [
      "05_prior_pred_distr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}